-- =========================================================================
-- Units 7–12 Syllables + Keywords sync to Supabase word_entries (stage 4A)
-- 222 unique words. DELETE-free UPDATE wrapped in a single transaction.
--
-- NOTE: these words were originally stage '4B' by mistake; they are stage '4A'
-- (Units 1–12). The UPDATE is scoped to stage='4A' AND Units 7–12 so it cannot
-- accidentally touch same-spelled words in the earlier Units 1–6.
--
-- Regenerated per docs/rules/phonics_rules.md (syllable splits) and
-- docs/rules/VOCABULARY_KEYWORD_GUIDE_1.md (keyword extraction rules).
--
-- HOW TO USE
--   1. Open Supabase SQL Editor -> New query -> paste -> Run
--   2. Verify (Units 7–12 only):
--      SELECT COUNT(*) FROM word_entries WHERE stage='4A'
--        AND unit IN ('Unit 7','Unit 8','Unit 9','Unit 10','Unit 11','Unit 12') AND syllables IS NOT NULL;  -- 223
--      SELECT COUNT(*) FROM word_entries WHERE stage='4A'
--        AND unit IN ('Unit 7','Unit 8','Unit 9','Unit 10','Unit 11','Unit 12') AND keywords IS NOT NULL;   -- 223
--   3. (Optional) Delete this file after success -- one-time script.
--
-- COLUMN TYPES
--   syllables: jsonb   (stored as JSON array of strings)
--   keywords:  jsonb   (stored as JSON array of [phrase, color] pairs)
-- =========================================================================

BEGIN;

UPDATE word_entries AS w
SET syllables = d.syl, keywords = d.kw
FROM (VALUES
  ($$active$$, '["ac", "tive"]'::jsonb, '[["likely to explode violently", "kw-red"], ["fire and hot liquid rock", "kw-gold"]]'::jsonb),
  ($$air conditioning$$, '["air", "con", "di", "tion", "ing"]'::jsonb, '[["cools and dries the air", "kw-red"], ["building or car", "kw-gold"]]'::jsonb),
  ($$album$$, '["al", "bum"]'::jsonb, '[["keep photographs", "kw-red"], ["stamps", "kw-gold"]]'::jsonb),
  ($$alive$$, '["a", "live"]'::jsonb, '[["living; not dead", "kw-red"]]'::jsonb),
  ($$app$$, '["app"]'::jsonb, '[["piece of software", "kw-red"], ["smartphone or tablet", "kw-gold"]]'::jsonb),
  ($$aquarium$$, '["a", "quar", "i", "um"]'::jsonb, '[["see fish and other water creatures", "kw-red"]]'::jsonb),
  ($$artist$$, '["ar", "tist"]'::jsonb, '[["creates art", "kw-red"]]'::jsonb),
  ($$association$$, '["as", "so", "ci", "a", "tion"]'::jsonb, '[["official group of people", "kw-red"], ["particular purpose", "kw-gold"]]'::jsonb),
  ($$attract$$, '["at", "tract"]'::jsonb, '[["go to or move to", "kw-red"], ["towards a place", "kw-gold"]]'::jsonb),
  ($$author$$, '["au", "thor"]'::jsonb, '[["writes books", "kw-red"], ["wrote a particular book", "kw-gold"]]'::jsonb),
  ($$bagel$$, '["ba", "gel"]'::jsonb, '[["hard bread roll", "kw-red"], ["shape of a ring", "kw-gold"]]'::jsonb),
  ($$bank$$, '["bank"]'::jsonb, '[["people keep their money", "kw-red"], ["borrow money", "kw-gold"]]'::jsonb),
  ($$battery$$, '["bat", "ter", "y"]'::jsonb, '[["placed inside a machine", "kw-red"], ["supply it with electricity", "kw-gold"]]'::jsonb),
  ($$bike lane$$, '["bike", "lane"]'::jsonb, '[["only bicycles are allowed", "kw-red"], ["part of a road", "kw-gold"]]'::jsonb),
  ($$billion$$, '["bil", "lion"]'::jsonb, '[["one thousand million", "kw-red"]]'::jsonb),
  ($$branch$$, '["branch"]'::jsonb, '[["part of a tree", "kw-red"], ["grows out from the trunk", "kw-gold"]]'::jsonb),
  ($$brave$$, '["brave"]'::jsonb, '[["willing to do things", "kw-red"], ["difficult or dangerous", "kw-gold"]]'::jsonb),
  ($$bus stop$$, '["bus", "stop"]'::jsonb, '[["side of a road", "kw-red"], ["buses stop", "kw-gold"]]'::jsonb),
  ($$by mistake$$, '["by", "mi", "stake"]'::jsonb, '[["not planned or organised", "kw-red"]]'::jsonb),
  ($$cable car$$, '["ca", "ble", "car"]'::jsonb, '[["hangs from", "kw-red"], ["up and down a mountain", "kw-gold"]]'::jsonb),
  ($$can$$, '["can"]'::jsonb, '[["metal container", "kw-red"], ["food and drink is sold", "kw-gold"]]'::jsonb),
  ($$cardboard$$, '["card", "board"]'::jsonb, '[["stiff and thick kind of paper", "kw-red"], ["making boxes", "kw-gold"]]'::jsonb),
  ($$career$$, '["ca", "reer"]'::jsonb, '[["job or series of jobs", "kw-red"], ["during your working life", "kw-gold"]]'::jsonb),
  ($$cartoon$$, '["car", "toon"]'::jsonb, '[["animated film", "kw-red"], ["television show", "kw-gold"]]'::jsonb),
  ($$cause$$, '["cause"]'::jsonb, '[["make happen", "kw-red"], ["bad or unpleasant", "kw-gold"]]'::jsonb),
  ($$chandelier$$, '["chan", "de", "lier"]'::jsonb, '[["hangs from a ceiling", "kw-red"], ["many light bulbs or candles", "kw-gold"]]'::jsonb),
  ($$channel$$, '["chan", "nel"]'::jsonb, '[["television station", "kw-red"]]'::jsonb),
  ($$cheap$$, '["cheap"]'::jsonb, '[["not costing a lot of money", "kw-red"]]'::jsonb),
  ($$check$$, '["check"]'::jsonb, '[["find mistakes, problems", "kw-red"], ["make sure", "kw-gold"]]'::jsonb),
  ($$chef$$, '["chef"]'::jsonb, '[["professional cook", "kw-red"], ["in charge of a kitchen", "kw-gold"]]'::jsonb),
  ($$chewy$$, '["chew", "y"]'::jsonb, '[["needing to be chewed a lot", "kw-red"]]'::jsonb),
  ($$climate$$, '["cli", "mate"]'::jsonb, '[["regular pattern of weather conditions", "kw-red"]]'::jsonb),
  ($$collection$$, '["col", "lec", "tion"]'::jsonb, '[["group of objects", "kw-red"], ["have been collected", "kw-gold"]]'::jsonb),
  ($$comment$$, '["com", "ment"]'::jsonb, '[["gives an opinion", "kw-red"], ["say or write", "kw-gold"]]'::jsonb),
  ($$cover$$, '["cov", "er"]'::jsonb, '[["place over", "kw-red"], ["hide, protect or decorate", "kw-gold"]]'::jsonb),
  ($$creature$$, '["crea", "ture"]'::jsonb, '[["living thing", "kw-red"], ["can move around", "kw-gold"]]'::jsonb),
  ($$cross the road$$, '["cross", "the", "road"]'::jsonb, '[["one side of the road", "kw-red"], ["walk to other side", "kw-gold"]]'::jsonb),
  ($$curious$$, '["cu", "ri", "ous"]'::jsonb, '[["strong desire to know", "kw-red"]]'::jsonb),
  ($$customer$$, '["cus", "to", "mer"]'::jsonb, '[["buys goods or services", "kw-red"], ["from a shop or business", "kw-gold"]]'::jsonb),
  ($$day off$$, '["day", "off"]'::jsonb, '[["do not have to work", "kw-red"]]'::jsonb),
  ($$design$$, '["de", "sign"]'::jsonb, '[["plan and make decisions", "kw-red"]]'::jsonb),
  ($$designer$$, '["de", "sign", "er"]'::jsonb, '[["plan new things", "kw-red"], ["will look and be made", "kw-gold"]]'::jsonb),
  ($$desire$$, '["de", "sire"]'::jsonb, '[["strong wish", "kw-red"], ["have or do", "kw-gold"]]'::jsonb),
  ($$destination$$, '["des", "ti", "na", "tion"]'::jsonb, '[["place going to", "kw-red"], ["being sent", "kw-gold"]]'::jsonb),
  ($$destroy$$, '["de", "stroy"]'::jsonb, '[["damage badly", "kw-red"], ["no longer exists", "kw-gold"]]'::jsonb),
  ($$detective$$, '["de", "tec", "tive"]'::jsonb, '[["investigate crimes", "kw-red"], ["catch criminals", "kw-gold"]]'::jsonb),
  ($$digital$$, '["dig", "i", "tal"]'::jsonb, '[["stored in the form", "kw-red"], ["numbers 0 and 1", "kw-gold"]]'::jsonb),
  ($$display$$, '["dis", "play"]'::jsonb, '[["people can see it easily", "kw-red"]]'::jsonb),
  ($$distance$$, '["dis", "tance"]'::jsonb, '[["amount of space between two places", "kw-red"]]'::jsonb),
  ($$documentary$$, '["doc", "u", "men", "ta", "ry"]'::jsonb, '[["giving facts", "kw-red"], ["film or a radio", "kw-gold"]]'::jsonb),
  ($$download$$, '["down", "load"]'::jsonb, '[["get data from another computer", "kw-red"], ["using the internet", "kw-gold"]]'::jsonb),
  ($$drip$$, '["drip"]'::jsonb, '[["fall in small drops", "kw-red"]]'::jsonb),
  ($$driver$$, '["dri", "ver"]'::jsonb, '[["drives a vehicle", "kw-red"]]'::jsonb),
  ($$dump$$, '["dump"]'::jsonb, '[["quick and careless way", "kw-red"]]'::jsonb),
  ($$dust$$, '["dust"]'::jsonb, '[["fine powder", "kw-red"], ["small pieces of sand, earth", "kw-gold"]]'::jsonb),
  ($$ecosystem$$, '["e", "co", "sys", "tem"]'::jsonb, '[["plants and living creatures", "kw-red"], ["physical environment", "kw-gold"]]'::jsonb),
  ($$electronics$$, '["e", "lec", "tron", "ics"]'::jsonb, '[["operate using many small electrical parts", "kw-red"]]'::jsonb),
  ($$employee$$, '["em", "ploy", "ee"]'::jsonb, '[["paid to work", "kw-red"]]'::jsonb),
  ($$endangered$$, '["en", "dan", "gered"]'::jsonb, '[["at risk of no longer existing", "kw-red"]]'::jsonb),
  ($$entertain$$, '["en", "ter", "tain"]'::jsonb, '[["interest people", "kw-red"], ["make people laugh", "kw-gold"]]'::jsonb),
  ($$entire$$, '["en", "tire"]'::jsonb, '[["including everything", "kw-red"], ["every part", "kw-gold"]]'::jsonb),
  ($$environmental$$, '["en", "vi", "ron", "men", "tal"]'::jsonb, '[["natural conditions", "kw-red"], ["connected with the environment", "kw-gold"]]'::jsonb),
  ($$erupt$$, '["e", "rupt"]'::jsonb, '[["send out rocks, ash, lava", "kw-red"], ["sudden explosion", "kw-gold"]]'::jsonb),
  ($$escalator$$, '["es", "ca", "la", "tor"]'::jsonb, '[["moving stairs", "kw-red"], ["between different floors", "kw-gold"]]'::jsonb),
  ($$expensive$$, '["ex", "pen", "sive"]'::jsonb, '[["costing a lot of money", "kw-red"]]'::jsonb),
  ($$experience$$, '["ex", "pe", "ri", "ence"]'::jsonb, '[["knowledge and skill", "kw-red"], ["through doing", "kw-gold"]]'::jsonb),
  ($$explorer$$, '["ex", "plor", "er"]'::jsonb, '[["travels to places", "kw-red"], ["few people have been before", "kw-gold"]]'::jsonb),
  ($$fan$$, '["fan"]'::jsonb, '[["creates a current of air", "kw-red"]]'::jsonb),
  ($$ferry$$, '["fer", "ry"]'::jsonb, '[["carries people, vehicles and goods", "kw-red"], ["across a river", "kw-gold"]]'::jsonb),
  ($$film$$, '["film"]'::jsonb, '[["special thin plastic", "kw-red"], ["making photographs or moving pictures", "kw-gold"]]'::jsonb),
  ($$fish$$, '["fish"]'::jsonb, '[["catch or try to catch fish", "kw-red"]]'::jsonb),
  ($$focus on$$, '["fo", "cus", "on"]'::jsonb, '[["give attention, effort, or energy", "kw-red"], ["one specific task", "kw-gold"]]'::jsonb),
  ($$follow (the) directions$$, '["fol", "low", "the", "di", "rec", "tions"]'::jsonb, '[["do as told", "kw-red"], ["go as shown", "kw-gold"]]'::jsonb),
  ($$follower$$, '["fol", "low", "er"]'::jsonb, '[["regularly receive messages", "kw-red"], ["social media service", "kw-gold"]]'::jsonb),
  ($$free$$, '["free"]'::jsonb, '[["not costing any money", "kw-red"]]'::jsonb),
  ($$full-time$$, '["full", "time"]'::jsonb, '[["full number of hours", "kw-red"], ["normal or standard", "kw-gold"]]'::jsonb),
  ($$gallery$$, '["gal", "ler", "y"]'::jsonb, '[["showing works of art", "kw-red"], ["for public", "kw-gold"]]'::jsonb),
  ($$generation$$, '["gen", "er", "a", "tion"]'::jsonb, '[["born and living", "kw-red"], ["same time", "kw-gold"]]'::jsonb),
  ($$generous$$, '["gen", "er", "ous"]'::jsonb, '[["freely giving or sharing", "kw-red"], ["money and other valuable things", "kw-gold"]]'::jsonb),
  ($$get off$$, '["get", "off"]'::jsonb, '[["leave a vehicle", "kw-red"]]'::jsonb),
  ($$get on$$, '["get", "on"]'::jsonb, '[["enter a vehicle", "kw-red"]]'::jsonb),
  ($$global warming$$, '["glo", "bal", "warm", "ing"]'::jsonb, '[["increase in temperature", "kw-red"], ["earth''s atmosphere", "kw-gold"]]'::jsonb),
  ($$go around the corner$$, '["go", "a", "round", "the", "cor", "ner"]'::jsonb, '[["walk or move past a bend", "kw-red"], ["turning in the road", "kw-gold"]]'::jsonb),
  ($$go past (the traffic lights)$$, '["go", "past", "the", "traf", "fic", "lights"]'::jsonb, '[["move beyond", "kw-red"], ["beyond the traffic lights", "kw-gold"]]'::jsonb),
  ($$go straight on$$, '["go", "straight", "on"]'::jsonb, '[["keep moving in the same direction", "kw-red"], ["without turning", "kw-gold"]]'::jsonb),
  ($$gondola$$, '["gon", "do", "la"]'::jsonb, '[["long boat with a flat bottom", "kw-red"], ["canals in Venice", "kw-gold"]]'::jsonb),
  ($$green$$, '["green"]'::jsonb, '[["protect the natural world", "kw-red"]]'::jsonb),
  ($$greenhouse$$, '["green", "house"]'::jsonb, '[["glass sides and a glass roof", "kw-red"], ["growing plants", "kw-gold"]]'::jsonb),
  ($$handle$$, '["han", "dle"]'::jsonb, '[["deal with a situation", "kw-red"], ["strong emotion", "kw-gold"]]'::jsonb),
  ($$humid$$, '["hu", "mid"]'::jsonb, '[["warm and slightly wet", "kw-red"]]'::jsonb),
  ($$iguana$$, '["i", "gua", "na"]'::jsonb, '[["large tropical American lizard", "kw-red"]]'::jsonb),
  ($$imagine$$, '["i", "ma", "gine"]'::jsonb, '[["form a picture in your mind", "kw-red"]]'::jsonb),
  ($$improve$$, '["im", "prove"]'::jsonb, '[["become better than before", "kw-red"], ["make better", "kw-gold"]]'::jsonb),
  ($$information$$, '["in", "for", "ma", "tion"]'::jsonb, '[["knowledge that you get", "kw-red"]]'::jsonb),
  ($$inspector$$, '["in", "spec", "tor"]'::jsonb, '[["check tickets", "kw-red"], ["bus or train", "kw-gold"]]'::jsonb),
  ($$internet$$, '["in", "ter", "net"]'::jsonb, '[["connects computers", "kw-red"], ["throughout the world", "kw-gold"]]'::jsonb),
  ($$invent$$, '["in", "vent"]'::jsonb, '[["create or produce", "kw-red"], ["for the first time", "kw-gold"]]'::jsonb),
  ($$job$$, '["job"]'::jsonb, '[["work that a person does", "kw-red"], ["earn money", "kw-gold"]]'::jsonb),
  ($$jog$$, '["jog"]'::jsonb, '[["run slowly", "kw-red"], ["for exercise", "kw-gold"]]'::jsonb),
  ($$jungle$$, '["jun", "gle"]'::jsonb, '[["tropical forest", "kw-red"], ["grow very thickly", "kw-gold"]]'::jsonb),
  ($$landfill$$, '["land", "fill"]'::jsonb, '[["waste is buried", "kw-red"], ["under the ground", "kw-gold"]]'::jsonb),
  ($$lay eggs$$, '["lay", "eggs"]'::jsonb, '[["produce and put eggs", "kw-red"], ["like birds do", "kw-gold"]]'::jsonb),
  ($$leaf$$, '["leaf"]'::jsonb, '[["flat green part of a plant", "kw-red"], ["from a stem or branch", "kw-gold"]]'::jsonb),
  ($$lift$$, '["lift"]'::jsonb, '[["carries people or goods", "kw-red"], ["up and down to different levels", "kw-gold"]]'::jsonb),
  ($$liquid$$, '["liq", "uid"]'::jsonb, '[["able to flow freely", "kw-red"]]'::jsonb),
  ($$local$$, '["lo", "cal"]'::jsonb, '[["place where you live", "kw-red"]]'::jsonb),
  ($$location$$, '["lo", "ca", "tion"]'::jsonb, '[["place or position", "kw-red"]]'::jsonb),
  ($$loudspeaker$$, '["loud", "speak", "er"]'::jsonb, '[["make sound", "kw-red"], ["many people can hear it", "kw-gold"]]'::jsonb),
  ($$manager$$, '["man", "a", "ger"]'::jsonb, '[["in charge of running a business", "kw-red"]]'::jsonb),
  ($$mark$$, '["mark"]'::jsonb, '[["give marks to students'' work", "kw-red"]]'::jsonb),
  ($$massive$$, '["mas", "sive"]'::jsonb, '[["very large, heavy and solid", "kw-red"]]'::jsonb),
  ($$material$$, '["ma", "te", "ri", "al"]'::jsonb, '[["substance", "kw-red"], ["things can be made from", "kw-gold"]]'::jsonb),
  ($$means$$, '["means"]'::jsonb, '[["way of achieving", "kw-red"]]'::jsonb),
  ($$mechanic$$, '["me", "chan", "ic"]'::jsonb, '[["repairing machines", "kw-red"], ["engines of vehicles", "kw-gold"]]'::jsonb),
  ($$mosaic$$, '["mo", "sa", "ic"]'::jsonb, '[["small pieces of glass", "kw-red"], ["different colours", "kw-gold"]]'::jsonb),
  ($$motorbike$$, '["mo", "tor", "bike"]'::jsonb, '[["two wheels", "kw-red"], ["driven by an engine", "kw-gold"]]'::jsonb),
  ($$national park$$, '["na", "tion", "al", "park"]'::jsonb, '[["protected by the government", "kw-red"], ["natural beauty", "kw-gold"]]'::jsonb),
  ($$neighbourhood (AmE neighborhood)$$, '["neigh", "bour", "hood"]'::jsonb, '[["district or area", "kw-red"], ["of a town", "kw-gold"]]'::jsonb),
  ($$nest$$, '["nest"]'::jsonb, '[["where a bird lays its eggs", "kw-red"], ["takes care of its young", "kw-gold"]]'::jsonb),
  ($$news$$, '["news"]'::jsonb, '[["information that is reported", "kw-red"], ["newspaper, magazine, television", "kw-gold"]]'::jsonb),
  ($$newspaper$$, '["news", "pa", "per"]'::jsonb, '[["large printed sheets of paper", "kw-red"], ["containing news, articles, advertisements", "kw-gold"]]'::jsonb),
  ($$ocean$$, '["o", "cean"]'::jsonb, '[["mass of salt water", "kw-red"], ["covers most of the earth", "kw-gold"]]'::jsonb),
  ($$oil$$, '["oil"]'::jsonb, '[["thick liquid", "kw-red"], ["rock underground", "kw-gold"]]'::jsonb),
  ($$opinion$$, '["o", "pin", "ion"]'::jsonb, '[["your feelings or thoughts", "kw-red"], ["rather than a fact", "kw-gold"]]'::jsonb),
  ($$organisation (AmE organization)$$, '["or", "gan", "i", "sa", "tion"]'::jsonb, '[["group of people", "kw-red"], ["achieve a particular aim", "kw-gold"]]'::jsonb),
  ($$origin$$, '["or", "i", "gin"]'::jsonb, '[["beginning or cause", "kw-red"]]'::jsonb),
  ($$outer space$$, '["out", "er", "space"]'::jsonb, '[["outside the earth''s atmosphere", "kw-red"], ["other planets and stars", "kw-gold"]]'::jsonb),
  ($$oxygen$$, '["ox", "y", "gen"]'::jsonb, '[["chemical element", "kw-red"], ["present in air and water", "kw-gold"]]'::jsonb),
  ($$parking$$, '["par", "king"]'::jsonb, '[["leaving vehicles", "kw-red"]]'::jsonb),
  ($$part-time$$, '["part", "time"]'::jsonb, '[["fewer hours", "kw-red"], ["normal or standard", "kw-gold"]]'::jsonb),
  ($$pass$$, '["pass"]'::jsonb, '[["allowed to enter or leave", "kw-red"], ["ride a vehicle", "kw-gold"]]'::jsonb),
  ($$passenger$$, '["pas", "sen", "ger"]'::jsonb, '[["travelling in a car", "kw-red"], ["not driving it", "kw-gold"]]'::jsonb),
  ($$patient$$, '["pa", "tient"]'::jsonb, '[["wait for a long time", "kw-red"], ["without becoming angry", "kw-gold"]]'::jsonb),
  ($$pedestrian$$, '["pe", "des", "tri", "an"]'::jsonb, '[["walking in the street", "kw-red"], ["not travelling in a vehicle", "kw-gold"]]'::jsonb),
  ($$petrol$$, '["pet", "rol"]'::jsonb, '[["liquid made from petroleum", "kw-red"], ["fuel for engines", "kw-gold"]]'::jsonb),
  ($$planetary$$, '["plan", "e", "ta", "ry"]'::jsonb, '[["relating to a planet", "kw-red"]]'::jsonb),
  ($$planner$$, '["plan", "ner"]'::jsonb, '[["plan the growth and development", "kw-red"], ["of a town", "kw-gold"]]'::jsonb),
  ($$plastic bag$$, '["plas", "tic", "bag"]'::jsonb, '[["light bag", "kw-red"], ["made of plastic", "kw-gold"]]'::jsonb),
  ($$pollute$$, '["pol", "lute"]'::jsonb, '[["dirty and not safe", "kw-red"], ["land, water, air", "kw-gold"]]'::jsonb),
  ($$post$$, '["post"]'::jsonb, '[["put information or pictures", "kw-red"], ["on a website", "kw-gold"]]'::jsonb),
  ($$print$$, '["print"]'::jsonb, '[["appear on paper or cloth", "kw-red"], ["using a machine", "kw-gold"]]'::jsonb),
  ($$product$$, '["pro", "duct"]'::jsonb, '[["grown, produced or created", "kw-red"], ["usually for sale", "kw-gold"]]'::jsonb),
  ($$professional$$, '["pro", "fes", "sion", "al"]'::jsonb, '[["paid job", "kw-red"], ["rather than as a hobby", "kw-gold"]]'::jsonb),
  ($$programme (AmE program)$$, '["pro", "gramme"]'::jsonb, '[["watch on television", "kw-red"], ["listen to on the radio", "kw-gold"]]'::jsonb),
  ($$quality$$, '["qual", "i", "ty"]'::jsonb, '[["how good or bad", "kw-red"]]'::jsonb),
  ($$queue$$, '["queue"]'::jsonb, '[["line of people", "kw-red"], ["waiting", "kw-gold"]]'::jsonb),
  ($$reality show$$, '["re", "al", "i", "ty", "show"]'::jsonb, '[["based on real people", "kw-red"], ["presented as entertainment", "kw-gold"]]'::jsonb),
  ($$record$$, '["rec", "ord"]'::jsonb, '[["store", "kw-red"], ["heard or seen later", "kw-gold"]]'::jsonb),
  ($$recreation$$, '["rec", "re", "a", "tion"]'::jsonb, '[["relax or have fun", "kw-red"]]'::jsonb),
  ($$recycle$$, '["re", "cy", "cle"]'::jsonb, '[["already been used", "kw-red"], ["used again", "kw-gold"]]'::jsonb),
  ($$reporter$$, '["re", "por", "ter"]'::jsonb, '[["collects and reports news", "kw-red"], ["newspapers, radio or television", "kw-gold"]]'::jsonb),
  ($$resident$$, '["res", "i", "dent"]'::jsonb, '[["lives in a particular place", "kw-red"], ["has their home there", "kw-gold"]]'::jsonb),
  ($$review$$, '["re", "view"]'::jsonb, '[["gives their opinion", "kw-red"], ["new book or movie", "kw-gold"]]'::jsonb),
  ($$review (verb)$$, '["re", "view"]'::jsonb, '[["write a report", "kw-red"], ["give your opinion", "kw-gold"]]'::jsonb),
  ($$romantic$$, '["ro", "man", "tic"]'::jsonb, '[["think of love", "kw-red"]]'::jsonb),
  ($$rover$$, '["ro", "ver"]'::jsonb, '[["spacecraft designed to move", "kw-red"], ["on a planet or moon", "kw-gold"]]'::jsonb),
  ($$rubber$$, '["rub", "ber"]'::jsonb, '[["strong substance", "kw-red"], ["can be stretched", "kw-gold"]]'::jsonb),
  ($$rugby$$, '["rug", "by"]'::jsonb, '[["two teams of 13 or 15 players", "kw-red"], ["oval ball", "kw-gold"]]'::jsonb),
  ($$sailor$$, '["sai", "lor"]'::jsonb, '[["works on a ship", "kw-red"], ["member of the crew", "kw-gold"]]'::jsonb),
  ($$sanctuary$$, '["sanc", "tu", "ar", "y"]'::jsonb, '[["wild birds or animals are protected", "kw-red"], ["produce young", "kw-gold"]]'::jsonb),
  ($$sand$$, '["sand"]'::jsonb, '[["tiny, loose pieces of rock", "kw-red"], ["cover beaches, deserts", "kw-gold"]]'::jsonb),
  ($$scavenger hunt$$, '["scav", "en", "ger", "hunt"]'::jsonb, '[["find various objects", "kw-red"], ["players find objects", "kw-gold"]]'::jsonb),
  ($$scooter$$, '["scoo", "ter"]'::jsonb, '[["light motorbike", "kw-red"], ["protect the rider''s legs", "kw-gold"]]'::jsonb),
  ($$sculpture$$, '["sculp", "ture"]'::jsonb, '[["work of art", "kw-red"], ["carving or shaping wood", "kw-gold"]]'::jsonb),
  ($$selfie$$, '["sel", "fie"]'::jsonb, '[["photo of yourself", "kw-red"], ["smartphone or webcam", "kw-gold"]]'::jsonb),
  ($$sense$$, '["sense"]'::jsonb, '[["one of the five powers", "kw-red"], ["information about the world", "kw-gold"]]'::jsonb),
  ($$series$$, '["se", "ries"]'::jsonb, '[["regularly presented television shows", "kw-red"], ["same group of characters", "kw-gold"]]'::jsonb),
  ($$seriously$$, '["se", "ri", "ous", "ly"]'::jsonb, '[["in a serious way", "kw-red"]]'::jsonb),
  ($$shade$$, '["shade"]'::jsonb, '[["dark and cool", "kw-red"], ["under or behind", "kw-gold"]]'::jsonb),
  ($$share$$, '["share"]'::jsonb, '[["give some of what you have", "kw-red"]]'::jsonb),
  ($$shelter$$, '["shel", "ter"]'::jsonb, '[["structure built to give protection", "kw-red"], ["from the weather or from attack", "kw-gold"]]'::jsonb),
  ($$shopping centre (AmE shopping center)$$, '["shop", "ping", "cen", "tre"]'::jsonb, '[["group of shops", "kw-red"], ["under one roof", "kw-gold"]]'::jsonb),
  ($$show$$, '["show"]'::jsonb, '[["let people see", "kw-red"]]'::jsonb),
  ($$sight$$, '["sight"]'::jsonb, '[["interesting places", "kw-red"], ["visited by tourists", "kw-gold"]]'::jsonb),
  ($$sitcom$$, '["sit", "com"]'::jsonb, '[["regular comedy programme", "kw-red"], ["different funny situations", "kw-gold"]]'::jsonb),
  ($$skill$$, '["skill"]'::jsonb, '[["particular ability", "kw-red"]]'::jsonb),
  ($$skyscraper$$, '["sky", "scrap", "er"]'::jsonb, '[["very tall building", "kw-red"], ["in a city", "kw-gold"]]'::jsonb),
  ($$slippery$$, '["slip", "per", "y"]'::jsonb, '[["difficult to stand on", "kw-red"], ["smooth, wet, icy", "kw-gold"]]'::jsonb),
  ($$smell$$, '["smell"]'::jsonb, '[["sense with your nose", "kw-red"]]'::jsonb),
  ($$social media$$, '["so", "cial", "me", "di", "a"]'::jsonb, '[["used for social networking", "kw-red"]]'::jsonb),
  ($$soil$$, '["soil"]'::jsonb, '[["top layer of earth", "kw-red"], ["plants grow", "kw-gold"]]'::jsonb),
  ($$spend$$, '["spend"]'::jsonb, '[["pay for", "kw-red"]]'::jsonb),
  ($$square$$, '["square"]'::jsonb, '[["open area in a town", "kw-red"], ["surrounded by buildings", "kw-gold"]]'::jsonb),
  ($$staff$$, '["staff"]'::jsonb, '[["group of people who work", "kw-red"], ["for an organisation or business", "kw-gold"]]'::jsonb),
  ($$stem$$, '["stem"]'::jsonb, '[["main long and thin part", "kw-red"], ["supports the leaves and flowers", "kw-gold"]]'::jsonb),
  ($$steps$$, '["steps"]'::jsonb, '[["surfaces that you walk on", "kw-red"], ["up or down stairs", "kw-gold"]]'::jsonb),
  ($$sticker$$, '["stick", "er"]'::jsonb, '[["small digital image", "kw-red"], ["express an idea or emotion", "kw-gold"]]'::jsonb),
  ($$sticky$$, '["stick", "y"]'::jsonb, '[["things easily attach to", "kw-red"], ["things stick to", "kw-gold"]]'::jsonb),
  ($$stone$$, '["stone"]'::jsonb, '[["small piece of rock", "kw-red"]]'::jsonb),
  ($$submarine$$, '["sub", "ma", "rine"]'::jsonb, '[["ship that can travel underwater", "kw-red"]]'::jsonb),
  ($$success$$, '["suc", "cess"]'::jsonb, '[["achieved what you want", "kw-red"]]'::jsonb),
  ($$surface$$, '["sur", "face"]'::jsonb, '[["outside or top layer", "kw-red"]]'::jsonb),
  ($$system$$, '["sys", "tem"]'::jsonb, '[["group of related parts", "kw-red"], ["move or work together", "kw-gold"]]'::jsonb),
  ($$tap water$$, '["tap", "wa", "ter"]'::jsonb, '[["supplied through pipes", "kw-red"], ["taps in a building", "kw-gold"]]'::jsonb),
  ($$taste$$, '["taste"]'::jsonb, '[["recognize different foods and drinks", "kw-red"], ["put them in your mouth", "kw-gold"]]'::jsonb),
  ($$taste (verb)$$, '["taste"]'::jsonb, '[["test the taste", "kw-red"], ["eating or drinking a small amount", "kw-gold"]]'::jsonb),
  ($$tax$$, '["tax"]'::jsonb, '[["pay to the government", "kw-red"], ["pay for public services", "kw-gold"]]'::jsonb),
  ($$technology$$, '["tech", "nol", "o", "gy"]'::jsonb, '[["use of science", "kw-red"], ["invent useful things", "kw-gold"]]'::jsonb),
  ($$the Arctic$$, '["the", "arc", "tic"]'::jsonb, '[["regions of the world", "kw-red"], ["around the North Pole", "kw-gold"]]'::jsonb),
  ($$the planet$$, '["the", "plan", "et"]'::jsonb, '[["planet Earth", "kw-red"]]'::jsonb),
  ($$throw away$$, '["throw", "a", "way"]'::jsonb, '[["get rid of", "kw-red"], ["no longer want", "kw-gold"]]'::jsonb),
  ($$ticket$$, '["tick", "et"]'::jsonb, '[["allows you to see a show", "kw-red"], ["travel on a vehicle", "kw-gold"]]'::jsonb),
  ($$ticket machine$$, '["tick", "et", "ma", "chine"]'::jsonb, '[["sells tickets", "kw-red"], ["without needing a human cashier", "kw-gold"]]'::jsonb),
  ($$timetable$$, '["time", "ta", "ble"]'::jsonb, '[["chart showing the times", "kw-red"], ["leave and arrive", "kw-gold"]]'::jsonb),
  ($$tool$$, '["tool"]'::jsonb, '[["hold in your hand", "kw-red"], ["particular task", "kw-gold"]]'::jsonb),
  ($$toxic$$, '["tox", "ic"]'::jsonb, '[["containing poison", "kw-red"]]'::jsonb),
  ($$track$$, '["track"]'::jsonb, '[["train moves along", "kw-red"], ["metal bars", "kw-gold"]]'::jsonb),
  ($$traffic$$, '["traf", "fic"]'::jsonb, '[["vehicles that are on a road", "kw-red"]]'::jsonb),
  ($$tram$$, '["tram"]'::jsonb, '[["travels on streets on metal tracks", "kw-red"], ["carrying passengers", "kw-gold"]]'::jsonb),
  ($$transport (AmE transportation)$$, '["trans", "port"]'::jsonb, '[["carrying people or goods", "kw-red"], ["from one place to another", "kw-gold"]]'::jsonb),
  ($$trap$$, '["trap"]'::jsonb, '[["catch and hold", "kw-red"], ["cannot escape", "kw-gold"]]'::jsonb),
  ($$treasure$$, '["trea", "sure"]'::jsonb, '[["collection of valuable things", "kw-red"], ["gold, silver and jewellery", "kw-gold"]]'::jsonb),
  ($$try$$, '["try"]'::jsonb, '[["make an effort", "kw-red"]]'::jsonb),
  ($$turn left/right$$, '["turn", "left", "right"]'::jsonb, '[["change direction", "kw-red"], ["move to the left or right", "kw-gold"]]'::jsonb),
  ($$upload$$, '["up", "load"]'::jsonb, '[["send data to another computer", "kw-red"]]'::jsonb),
  ($$variety$$, '["va", "ri", "e", "ty"]'::jsonb, '[["several different sorts", "kw-red"]]'::jsonb),
  ($$virtual reality$$, '["vir", "tu", "al", "re", "al", "i", "ty"]'::jsonb, '[["created by a computer", "kw-red"], ["seem almost real", "kw-gold"]]'::jsonb),
  ($$voice$$, '["voice"]'::jsonb, '[["sounds that are made", "kw-red"], ["people speak or sing", "kw-gold"]]'::jsonb),
  ($$volcano$$, '["vol", "ca", "no"]'::jsonb, '[["mountain with a hole", "kw-red"], ["sudden explosion", "kw-gold"]]'::jsonb),
  ($$waste$$, '["waste"]'::jsonb, '[["no longer needed", "kw-red"], ["thrown away", "kw-gold"]]'::jsonb),
  ($$wildlife$$, '["wild", "life"]'::jsonb, '[["animals living in nature", "kw-red"]]'::jsonb),
  ($$worry$$, '["wor", "ry"]'::jsonb, '[["what worries you", "kw-red"]]'::jsonb)
) AS d(word, syl, kw)
WHERE w.stage = '4A'
  AND w.unit IN ('Unit 7','Unit 8','Unit 9','Unit 10','Unit 11','Unit 12')
  AND w.word = d.word;

COMMIT;
