'use client'

import type { Problem, ProblemSet } from '@rosie/core'
import LessonFig8Grid from '@rosie/math/components/lesson/g2/lesson5/Figure/LessonFig8Grid'
import LessonFig8Triangle from '@rosie/math/components/lesson/g2/lesson5/Figure/LessonFig8Triangle'
import LessonFig9Clover from '@rosie/math/components/lesson/g2/lesson5/Figure/LessonFig9Clover'
import LessonFig9Arrow from '@rosie/math/components/lesson/g2/lesson5/Figure/LessonFig9Arrow'
import LessonFig10Grids from '@rosie/math/components/lesson/g2/lesson5/Figure/LessonFig10Grids'
import LessonFig12Squares from '@rosie/math/components/lesson/g2/lesson5/Figure/LessonFig12Squares'
import LessonFig13Shapes from '@rosie/math/components/lesson/g2/lesson5/Figure/LessonFig13Shapes'
import LessonFig14Circles from '@rosie/math/components/lesson/g2/lesson5/Figure/LessonFig14Circles'
import LessonFig15Shapes from '@rosie/math/components/lesson/g2/lesson5/Figure/LessonFig15Shapes'
import HomeworkFig6Grids from '@rosie/math/components/lesson/g2/lesson5/Figure/HomeworkFig6Grids'
import HomeworkFig7Table from '@rosie/math/components/lesson/g2/lesson5/Figure/HomeworkFig7Table'
import HomeworkFig8Grids from '@rosie/math/components/lesson/g2/lesson5/Figure/HomeworkFig8Grids'
import HomeworkFig9Sector from '@rosie/math/components/lesson/g2/lesson5/Figure/HomeworkFig9Sector'
import SupplementFig4Bars from '@rosie/math/components/lesson/g2/lesson5/Figure/SupplementFig4Bars'
import SupplementFig5ArrowFlow from '@rosie/math/components/lesson/g2/lesson5/Figure/SupplementFig5ArrowFlow'
import SupplementFig6Mittens from '@rosie/math/components/lesson/g2/lesson5/Figure/SupplementFig6Mittens'

export const LESSON_TIP =
  '找规律：先观察相邻项的差、比或和；数表题看行、列、斜线；图形题把数字与位置、形状编码对应起来。'

export const TYPE_TIP: Record<string, string> = {
  type1: '数列规律——看相邻两项的差、比、和是否恒定；隔项看、分组看也是常用技巧。',
  type2: '数表与图形——按行、列、斜线找和差积；图形题注意对称与位置轮换。',
  type3: '图形编码——外层、内层图形对应数位；周围小圆与中心大圆往往有乘积关系。',
  type4: '综合挑战——多规律叠加，先拆成几段分别找规律再合并。',
}

export const PROBLEM_TYPES = [
  {
    tag: 'type1',
    color: 'green',
    label: '题型1 · 数列找规律',
    desc: '等差、等比、二级差、隔项分组等数列规律。',
    example: '例：7,11,15,19→每次+4',
  },
  {
    tag: 'type2',
    color: 'blue',
    label: '题型2 · 数表图形',
    desc: '方格数表、三角形数表、位置轮换图形规律。',
    example: '例：4×4数表按行递减',
  },
  {
    tag: 'type3',
    color: 'orange',
    label: '题型3 · 图形编码',
    desc: '图形组合对应数字、周围数决定中心数。',
    example: '例：△=1 □=3，外内组合成两位数',
  },
  {
    tag: 'type4',
    color: 'purple',
    label: '题型4 · 综合挑战',
    desc: '多规律交织、逻辑推理与高级数列。',
    example: '例：交错数列、乘积数表',
  },
]

export const TYPE_STYLE: Record<
  string,
  { bg: string; border: string; titleColor: string; textColor: string }
> = {
  type1: {
    bg: 'bg-emerald-50',
    border: 'border-l-emerald-500',
    titleColor: 'text-emerald-800',
    textColor: 'text-emerald-900',
  },
  type2: {
    bg: 'bg-blue-50',
    border: 'border-l-blue-500',
    titleColor: 'text-blue-800',
    textColor: 'text-blue-900',
  },
  type3: {
    bg: 'bg-orange-50',
    border: 'border-l-orange-500',
    titleColor: 'text-orange-800',
    textColor: 'text-orange-900',
  },
  type4: {
    bg: 'bg-purple-50',
    border: 'border-l-purple-500',
    titleColor: 'text-purple-800',
    textColor: 'text-purple-900',
  },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-emerald-100 text-emerald-700',
  type2: 'bg-blue-100 text-blue-700',
  type3: 'bg-orange-100 text-orange-700',
  type4: 'bg-purple-100 text-purple-700',
}

const LESSON: Problem[] = [
  {
    id: '2-5-L1',
    title: '例题1-1 · 等差数列',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 1,
    text: '找规律填空：<strong>7, 11, 15, 19, __, __, 31</strong>',
    analysis: ['每次加 <strong>4</strong>', '19+4=23，23+4=27', '第二个空填 <strong>27</strong>'],
    type: 'none',
    finalQ: '第二个空填',
    finalUnit: '',
    finalAns: 27,
  },
  {
    id: '2-5-L2',
    title: '例题1-2 · 等比数列',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 2,
    text: '找规律填空：<strong>1, 4, 16, __, 256, 1024</strong>',
    analysis: ['每次乘 <strong>4</strong>', '16×4=<strong>64</strong>'],
    type: 'none',
    finalQ: '空格填',
    finalUnit: '',
    finalAns: 64,
  },
  {
    id: '2-5-L3',
    title: '例题1-3 · 平方数列',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 1,
    text: '找规律填空：<strong>1, 4, 9, 16, 25, __, 49</strong>',
    analysis: ['完全平方数 1²,2²,…', '6²=<strong>36</strong>'],
    type: 'none',
    finalQ: '空格填',
    finalUnit: '',
    finalAns: 36,
  },
  {
    id: '2-5-L4',
    title: '例题2-1 · 二级等差',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 2,
    text: '找规律填空：<strong>1, 5, 11, 19, 29, __, 55</strong>',
    analysis: ['差：4,6,8,10,12,14', '29+12=<strong>41</strong>'],
    type: 'none',
    finalQ: '空格填',
    finalUnit: '',
    finalAns: 41,
  },
  {
    id: '2-5-L5',
    title: '例题2-2 · 差为等比',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 3,
    text: '找规律填空：<strong>2, 3, 6, 15, __, 123</strong>（提示：差是等比）',
    analysis: ['差 1,3,9,27,81', '15+27=<strong>42</strong>'],
    type: 'none',
    finalQ: '空格填',
    finalUnit: '',
    finalAns: 42,
  },
  {
    id: '2-5-L6',
    title: '例题2-3 · 复杂递增',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 4,
    text: '找规律填空：<strong>4, 7, 11, 17, 26, 39, 57, 81, __</strong>',
    analysis: ['差 3,4,6,9,13,18,24,33', '81+33=<strong>114</strong>'],
    type: 'none',
    finalQ: '空格填',
    finalUnit: '',
    finalAns: 114,
  },
  {
    id: '2-5-L7',
    title: '例题3-1 · 递推数列',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 4,
    text: '找规律填空：<strong>1, 2, 6, 16, 44, __, 328</strong>',
    analysis: ['aₙ=3aₙ₋₁−aₙ₋₂', '44×3−16=<strong>128</strong>'],
    type: 'none',
    finalQ: '空格填',
    finalUnit: '',
    finalAns: 128,
  },
  {
    id: '2-5-L8',
    title: '例题3-2 · 斐波那契差',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 3,
    text: '找规律填空：<strong>3, 4, 6, 9, 14, 22, __, 56</strong>',
    analysis: ['差 1,2,3,5,8,13,21', '22+21=<strong>43</strong>'],
    type: 'none',
    finalQ: '空格填',
    finalUnit: '',
    finalAns: 43,
  },
  {
    id: '2-5-L9',
    title: '例题3-3 · 乘2减1',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 3,
    text: '找规律填空：<strong>2, 3, 5, 9, 17, __, 65</strong>',
    analysis: ['×2−1：17×2−1=<strong>33</strong>'],
    type: 'none',
    finalQ: '空格填',
    finalUnit: '',
    finalAns: 33,
  },
  {
    id: '2-5-L10',
    title: '例题4-1 · 交错数列',
    tag: 'type4',
    tagLabel: '综合挑战',
    difficulty: 5,
    text: '找规律填空：<strong>1, 2, 2, 3, 2, 4, 4, 5, 8, 6, __, __, 256, 8</strong>',
    analysis: [
      '奇数位 1,2,2,4,4,8,8,256→×2',
      '偶数位 2,3,4,5,6,8',
      '两空为 <strong>16</strong> 和 <strong>7</strong>，第二空填 <strong>7</strong>',
    ],
    type: 'none',
    finalQ: '第二个空格填',
    finalUnit: '',
    finalAns: 7,
  },
  {
    id: '2-5-L11',
    title: '例题4-2 · 双数列',
    tag: 'type4',
    tagLabel: '综合挑战',
    difficulty: 5,
    text: '找规律填空：<strong>__, 3, 16, 5, 13, 9, 10, 17, 7, 33, 4, __</strong>',
    analysis: [
      '奇数位 1,5,9,7,4→首项 <strong>1</strong>',
      '偶数位 3,16,13,17,33→末项 <strong>60</strong>，首空填 <strong>1</strong>',
    ],
    type: 'none',
    finalQ: '第一个空格填',
    finalUnit: '',
    finalAns: 1,
  },
  {
    id: '2-5-L12',
    title: '例题5-1 · 分组数列',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 4,
    text: '找规律填空：<strong>2, 3, 5, 8, 3, 1, 4, 5, 9, 4, 3, __, __</strong>',
    analysis: [
      '每4个一组，组内和为18',
      '末组 3+__+__=18',
      '两空 <strong>7</strong> 和 <strong>8</strong>，第二空 <strong>8</strong>',
    ],
    type: 'none',
    finalQ: '第二个空格填',
    finalUnit: '',
    finalAns: 8,
  },
  {
    id: '2-5-L13',
    title: '例题5-2 · 周期数列',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 3,
    text: '找规律填空：<strong>2, 3, 6, 8, 8, 4, 2, __, __</strong>',
    analysis: [
      '×1.5,×2,×4/3,×1,×0.5,×0.5 循环',
      '2,1→<strong>1</strong> 和 <strong>2</strong>，第一空 <strong>1</strong>',
    ],
    type: 'none',
    finalQ: '第一个空格填',
    finalUnit: '',
    finalAns: 1,
  },
  {
    id: '2-5-L14',
    title: '例题6 · 配对递增',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 2,
    text: '找规律填空：<strong>0, 1, 2, 3, 6, 7, 14, 15, 30, __, __, 63</strong>',
    analysis: ['成对 (0,1)(2,3)(6,7)(14,15)(30,31)(62,63)', '第一空 <strong>31</strong>'],
    type: 'none',
    finalQ: '第一个空格填',
    finalUnit: '',
    finalAns: 31,
  },
  {
    id: '2-5-L15',
    title: '例题7-1 · 平方减1',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 2,
    text: '找规律填空：<strong>3, 15, 35, 63, 99, __, 195</strong>',
    analysis: ['(2n)²−1：12²−1=<strong>143</strong>'],
    type: 'none',
    finalQ: '空格填',
    finalUnit: '',
    finalAns: 143,
  },
  {
    id: '2-5-L16',
    title: '例题7-2 · 交错复杂',
    tag: 'type4',
    tagLabel: '综合挑战',
    difficulty: 5,
    text: '找规律填空：<strong>7, 22, 11, 34, 17, 52, __, __, __, 20, 10, 5, 16</strong>',
    analysis: [
      '奇数位 ×3+1 再 ÷2；偶数位规律',
      '52 后三空 <strong>26, 13, 8</strong>，第一空 <strong>26</strong>',
    ],
    type: 'none',
    finalQ: '第一个空格填',
    finalUnit: '',
    finalAns: 26,
  },
  {
    id: '2-5-L17',
    title: '例题8-1 · 数表方格',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 3,
    text: '找出数表规律，填「?」处的数。',
    figureNode: <LessonFig8Grid />,
    analysis: ['第3行递减2：14→<strong>12</strong>', '第1行末格 10+2=12', '第4行第2格 22'],
    type: 'none',
    finalQ: '第3行末格填',
    finalUnit: '',
    finalAns: 12,
  },
  {
    id: '2-5-L18',
    title: '例题8-2 · 数表三角',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 4,
    text: '找出三角形数表规律，填「?」处的数。',
    figureNode: <LessonFig8Triangle />,
    analysis: ['对称数表，第6行 6,16,25,25,16,6', '第一个?=<strong>16</strong>'],
    type: 'none',
    finalQ: '第6行第2个数填',
    finalUnit: '',
    finalAns: 16,
  },
  {
    id: '2-5-L19',
    title: '例题9-1 · 四圆规律',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 3,
    text: '找出各组图规律，填「?」处的数。',
    figureNode: <LessonFig9Clover />,
    analysis: ['左+右+下=上', '12+?+11=35', '?=<strong>12</strong>'],
    type: 'none',
    finalQ: '右圆填',
    finalUnit: '',
    finalAns: 12,
  },
  {
    id: '2-5-L20',
    title: '例题9-2 · 箭头图形',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 4,
    text: '找出箭头与圆、菱形图形的规律，填「?」处的数。',
    figureNode: <LessonFig9Arrow />,
    analysis: [
      '右圆=左×箭头+箭头−1',
      '8×7+6=<strong>62</strong>… 验算：6×2+0=16✓',
      '7×8+7−1=<strong>62</strong>',
    ],
    type: 'none',
    finalQ: '右圆填',
    finalUnit: '',
    finalAns: 62,
  },
  {
    id: '2-5-L21',
    title: '例题10 · 乘积数表',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 3,
    text: '找出数表规律，把空白的 2×2 数表填出。',
    figureNode: <LessonFig10Grids />,
    analysis: [
      '左上×右下=左下，左上+右下=右上',
      '第4格：左上8，右下6，左下48，右上14→右上 <strong>17</strong> 验算 8+6≠17',
      '左上8，右上17，左下48，右下6',
    ],
    type: 'none',
    finalQ: '空白格左上是',
    finalUnit: '',
    finalAns: 8,
  },
  {
    id: '2-5-L22',
    title: '例题11 · 图形轮换',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 4,
    text: '观察下图中的规律，请按照这种规律，填出空格中未填完的图形。',
    figureNode: (
      <img
        src="/img/math/53-L22.png"
        alt="例题11 图形轮换"
        className="mx-auto w-full max-w-2xl rounded-lg"
      />
    ),
    analysis: [
      '图形顺时针移一格，同时顺时针旋转 90°',
      '从右下角起依次消失：钩形→直箭头',
      '第4格左上、右上两格待补，共 <strong>2</strong> 个空格',
    ],
    type: 'none',
    finalQ: '第4格有几个空格待补',
    finalUnit: '个',
    finalAns: 2,
  },
  {
    id: '2-5-L23',
    title: '例题12 · 对角与圆点',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 3,
    text: '补全第四个图：圆点按顺时针从右下→右上→左下→<strong>左上</strong>，对角线交替。圆点最终在哪个角？（1=左上 2=右上 3=左下 4=右下）',
    figureNode: <LessonFig12Squares />,
    analysis: ['圆点顺时针：4→2→3→1', '答案编码 <strong>1</strong>（左上）'],
    type: 'none',
    finalQ: '圆点位置编码',
    finalUnit: '',
    finalAns: 1,
  },
  {
    id: '2-5-L24',
    title: '例题13 · 图形组合',
    tag: 'type3',
    tagLabel: '图形编码',
    difficulty: 3,
    text: 'A=□ B=○ C=△ D=□内层。A*B、C*B、B*D 如图，C*D 的内层图形边数是几？',
    figureNode: <LessonFig13Shapes />,
    analysis: ['* 表示外内含', 'C*D=△外□内', '正方形边数 <strong>4</strong>'],
    type: 'none',
    finalQ: '内层图形边数',
    finalUnit: '条',
    finalAns: 4,
  },
  {
    id: '2-5-L25',
    title: '例题14 · 圆圈乘积',
    tag: 'type3',
    tagLabel: '图形编码',
    difficulty: 3,
    text: '中心大圆圈的数由周围小圆圈的数确定，小圆圈里「?」代表多少？',
    figureNode: <LessonFig14Circles />,
    analysis: ['大圆=周围四数之积', '48=6×?×4×1', '?=<strong>2</strong>'],
    type: 'none',
    finalQ: '? 代表',
    finalUnit: '',
    finalAns: 2,
  },
  {
    id: '2-5-L26',
    title: '例题15 · 形状编码',
    tag: 'type3',
    tagLabel: '图形编码',
    difficulty: 3,
    text: '每个图形由△□○中两个构成，观察图形与下面数的关系，「?」应当是几？',
    figureNode: <LessonFig15Shapes />,
    analysis: ['十位=外层 △1 ○2 □3', '个位=内层', '□外○内=<strong>32</strong>'],
    type: 'none',
    finalQ: '? 应当是',
    finalUnit: '',
    finalAns: 32,
  },
]

const HOMEWORK: Problem[] = [
  {
    id: '2-5-H1',
    title: '练习1-1 · 等差',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 1,
    text: '找规律填空：<strong>2, 6, 10, 14, 18, 22, __, __, 34</strong>',
    analysis: ['+4', '30, 34→第一空 <strong>26</strong>'],
    type: 'none',
    finalQ: '第一个空格填',
    finalUnit: '',
    finalAns: 26,
  },
  {
    id: '2-5-H2',
    title: '练习1-2 · 斐波那契',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 2,
    text: '找规律填空：<strong>1, 1, 2, 3, 5, 8, 13, 21, __, __, 89</strong>',
    analysis: ['斐波那契', '34, 55→第一空 <strong>34</strong>'],
    type: 'none',
    finalQ: '第一个空格填',
    finalUnit: '',
    finalAns: 34,
  },
  {
    id: '2-5-H3',
    title: '练习2-1 · 乘积增长',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 3,
    text: '找规律填空：<strong>1, 2, 2, 4, 8, 32, __</strong>',
    analysis: ['aₙ=aₙ₋₁×aₙ₋₂', '4×8=<strong>32</strong>已给，下一项 8×32÷4=<strong>256</strong>'],
    type: 'none',
    finalQ: '空格填',
    finalUnit: '',
    finalAns: 256,
  },
  {
    id: '2-5-H4',
    title: '练习2-2 · 平方数',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 2,
    text: '找规律填空：<strong>1, 9, 25, __, 81, 121, 169</strong>',
    analysis: ['奇数平方', '5²=<strong>49</strong>'],
    type: 'none',
    finalQ: '空格填',
    finalUnit: '',
    finalAns: 49,
  },
  {
    id: '2-5-H5',
    title: '练习3-1 · 隔项减',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 2,
    text: '找规律填空：<strong>75, 3, 74, 3, 73, 3, __, __</strong>',
    analysis: ['奇数位递减1', '72, 3→第一空 <strong>72</strong>'],
    type: 'none',
    finalQ: '第一个空格填',
    finalUnit: '',
    finalAns: 72,
  },
  {
    id: '2-5-H6',
    title: '练习3-2 · 隔项加',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 2,
    text: '找规律填空：<strong>1, 4, 5, 4, 9, 4, __, __</strong>',
    analysis: ['偶数位恒4，奇数位 1,5,9,13', '13, 4→第一空 <strong>13</strong>'],
    type: 'none',
    finalQ: '第一个空格填',
    finalUnit: '',
    finalAns: 13,
  },
  {
    id: '2-5-H7',
    title: '练习4-1 · 双数列',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 3,
    text: '找规律填空：<strong>1, 37, 3, 34, 5, 31, 7, __, __, 25, 11</strong>',
    analysis: ['奇数位+2，偶数位−3', '28, 28→第一空 <strong>28</strong>'],
    type: 'none',
    finalQ: '第一个空格填',
    finalUnit: '',
    finalAns: 28,
  },
  {
    id: '2-5-H8',
    title: '练习4-2 · 乘2规律',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 3,
    text: '找规律填空：<strong>1, 4, 2, 8, 3, 16, 4, 32, 5, __, __, 128, 7</strong>',
    analysis: ['奇数位+1，偶数位×2', '64, 6→第一空 <strong>64</strong>'],
    type: 'none',
    finalQ: '第一个空格填',
    finalUnit: '',
    finalAns: 64,
  },
  {
    id: '2-5-H9',
    title: '练习5 · 斐波那契逆推',
    tag: 'type1',
    tagLabel: '数列找规律',
    difficulty: 4,
    text: '8 个数排成一行，从第3个起每项等于前两项之和。第7、8项分别是 <strong>81</strong> 和 <strong>131</strong>，第一个数是多少？',
    analysis: ['逆推：a6=50,a5=31,a4=19,a3=12,a2=7,a1=<strong>5</strong>'],
    type: 'none',
    finalQ: '第一个数是',
    finalUnit: '',
    finalAns: 5,
  },
  {
    id: '2-5-H10',
    title: '练习6-1 · 方格表①',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 2,
    text: '找规律，在图中空格填入适当的数。',
    figureNode: <HomeworkFig6Grids />,
    analysis: ['行+2列+2', '9+4=<strong>13</strong>'],
    type: 'none',
    finalQ: '①右上角填',
    finalUnit: '',
    finalAns: 13,
  },
  {
    id: '2-5-H11',
    title: '练习6-2 · 方格表②',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 4,
    text: '找规律，在图②空格填入适当的数。',
    figureNode: <HomeworkFig6Grids />,
    analysis: ['下行斐波那契式', '21+13=<strong>34</strong>'],
    type: 'none',
    finalQ: '②右上角填',
    finalUnit: '',
    finalAns: 34,
  },
  {
    id: '2-5-H12',
    title: '练习7 · 双行数表',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 3,
    text: '观察表中数字，找出规律，填出空格中的数。',
    figureNode: <HomeworkFig7Table />,
    analysis: ['两行交错+11/+1规律', '第一行第9格 <strong>26</strong>'],
    type: 'none',
    finalQ: '第一行第9格填',
    finalUnit: '',
    finalAns: 26,
  },
  {
    id: '2-5-H13',
    title: '练习8 · 方格图形',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 4,
    text: '观察三个图形，画出第四个：绿圆逆时针轮换，斜线数递增。第四格斜线有几条？',
    figureNode: <HomeworkFig8Grids />,
    analysis: ['斜线 1,2,3,→<strong>3</strong> 条', '绿圆在左下角'],
    type: 'none',
    finalQ: '第四格斜线条数',
    finalUnit: '条',
    finalAns: 3,
  },
  {
    id: '2-5-H14',
    title: '练习9 · 扇形数',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 3,
    text: '观察扇形中数字规律，在空白处填一个数。',
    figureNode: <HomeworkFig9Sector />,
    analysis: ['相对扇形和为10', '与4相对的空格=<strong>6</strong>'],
    type: 'none',
    finalQ: '空白扇形填',
    finalUnit: '',
    finalAns: 6,
  },
  {
    id: '2-5-H15',
    title: '练习10-1 · 杨辉三角',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 2,
    text: '找规律填空（杨辉三角）：第6行第2个、第7行第4个分别是多少？<br/>第6行：1, ?, 10, 10, 5, 1<br/>第7行：1, 6, 15, ?, 15, 6, 1',
    analysis: ['杨辉三角', '第6行第2个=<strong>5</strong>'],
    type: 'none',
    finalQ: '第6行第2个数是',
    finalUnit: '',
    finalAns: 5,
  },
  {
    id: '2-5-H16',
    title: '练习10-2 · 蛇形数表',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 4,
    text: '5×5数表按蛇形填连续奇数 1,3,5…，第1行末格和第5行首格各是多少？<br/>已知部分格已填。',
    analysis: ['蛇形填奇数', '第1行末格 <strong>33</strong>'],
    type: 'none',
    finalQ: '第1行末格填',
    finalUnit: '',
    finalAns: 33,
  },
  {
    id: '2-5-H17',
    title: '练习11 · 5×5数表',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 4,
    text: '找规律，在5×5空格中填入适当的数。<br/>末行：1,9,41,129,<strong>?</strong>',
    analysis: ['列规律二级差', '末格 <strong>209</strong>'],
    type: 'none',
    finalQ: '右下角填',
    finalUnit: '',
    finalAns: 209,
  },
  {
    id: '2-5-H18',
    title: '练习12-1 · 四圆图',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 3,
    text: '观察四圆图数字规律：29,6,5,1 → 26,17,2,8 → 42,12,4,6 → 40,7,9,?',
    analysis: ['上+左+右=下', '40=7+9+?→下=<strong>24</strong>'],
    type: 'none',
    finalQ: '下圆填',
    finalUnit: '',
    finalAns: 24,
  },
  {
    id: '2-5-H19',
    title: '练习12-2 · 箭头图',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 4,
    text: '箭头图：7,6,5→18；8,11,4→23；5,15,9→29；4,7,8→?',
    analysis: ['左+右+箭头=菱形', '7+8+4=<strong>19</strong>'],
    type: 'none',
    finalQ: '菱形填',
    finalUnit: '',
    finalAns: 19,
  },
  {
    id: '2-5-H20',
    title: '练习13 · 形状数字',
    tag: 'type3',
    tagLabel: '图形编码',
    difficulty: 4,
    text: '观察图形与数字关系：△上□内=68，▽上○内=91，○上○内=11，□上△内=86，○上□内=18，▽上△内=?',
    analysis: ['方向与形状编码', '▽上△内=<strong>69</strong>'],
    type: 'none',
    finalQ: '? 填',
    finalUnit: '',
    finalAns: 69,
  },
  {
    id: '2-5-H21',
    title: '练习14 · 双行圆圈',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 4,
    text: '观察上下圆圈排列，填出最后两个空白圆圈中<strong>上圆</strong>的数。',
    analysis: ['上圆：1,2,5,8,9,32,25', '规律复合', '末对上圆 <strong>25</strong>'],
    type: 'none',
    finalQ: '最后一对上圆填',
    finalUnit: '',
    finalAns: 25,
  },
]

const SUPPLEMENT: Problem[] = [
  {
    id: '2-5-S1',
    title: '附加题1 · 数位规律',
    tag: 'type4',
    tagLabel: '综合挑战',
    difficulty: 5,
    text: '找规律填空：<strong>3, 6, 21, 42, 84, 69, 291, 483, __, __</strong>',
    analysis: ['数位操作规律', '573, 753→第一空 <strong>573</strong>'],
    type: 'none',
    finalQ: '第一个空格填',
    finalUnit: '',
    finalAns: 573,
  },
  {
    id: '2-5-S2',
    title: '附加题2 · 数位和',
    tag: 'type4',
    tagLabel: '综合挑战',
    difficulty: 5,
    text: '找规律填空：<strong>123, 129, 141, 147, 159, 174, 186, 201, 204, __, __, 219</strong>',
    analysis: ['各位数字和递增', '210, 216→第一空 <strong>210</strong>'],
    type: 'none',
    finalQ: '第一个空格填',
    finalUnit: '',
    finalAns: 210,
  },
  {
    id: '2-5-S3',
    title: '附加题3-1 · 三角形',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 4,
    text: '下面的各组图形中的数都有各自的规律，先把规律找出来，再把空缺的数填上。（① 三三角形组）',
    figureNode: (
      <img
        src="/img/math/53-S3.png"
        alt="附加题3 图形组规律"
        className="mx-auto w-full max-w-2xl rounded-lg"
      />
    ),
    analysis: ['上×左×右÷2=中心', '2×3×5÷2=15，7×4×2÷2=28', '4×3×6÷2=<strong>36</strong>'],
    type: 'none',
    finalQ: '第3组中心填',
    finalUnit: '',
    finalAns: 36,
  },
  {
    id: '2-5-S4',
    title: '附加题3-2 · 三圆',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 4,
    text: '下面的各组图形中的数都有各自的规律，先把规律找出来，再把空缺的数填上。（② 大圆三小圆组）',
    figureNode: (
      <img
        src="/img/math/53-S3.png"
        alt="附加题3 图形组规律"
        className="mx-auto w-full max-w-2xl rounded-lg"
      />
    ),
    analysis: ['（上+左+右）×2=中心', '3+7+5=15→30，7+3+8=18→36', '(5+6+9)×2=<strong>40</strong>'],
    type: 'none',
    finalQ: '第3组中心填',
    finalUnit: '',
    finalAns: 40,
  },
  {
    id: '2-5-S5',
    title: '附加题3-3 · 四象限圆',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 4,
    text: '下面的各组图形中的数都有各自的规律，先把规律找出来，再把空缺的数填上。（③ 四象限圆，先求第3个圆右下角）',
    figureNode: (
      <img
        src="/img/math/53-S3.png"
        alt="附加题3 图形组规律"
        className="mx-auto w-full max-w-2xl rounded-lg"
      />
    ),
    analysis: [
      '左上+右上=左下×右下',
      '11+9=5×4，7+9=2×8',
      '13+8=3×?→?<strong>7</strong>（第4圆左上=9）',
    ],
    type: 'none',
    finalQ: '第3圆右下填',
    finalUnit: '',
    finalAns: 7,
  },
  {
    id: '2-5-S6',
    title: '附加题4 · 条形数码',
    tag: 'type4',
    tagLabel: '综合挑战',
    difficulty: 5,
    text: '下图中共有 <strong>12</strong> 个小图形，每一个不同的小图形表示 <strong>1~9</strong> 中的一个数字，每行的三个图形表示一个三位数，四行表示四个三位数：<strong>146、521、658</strong> 和 <strong>692</strong>。问第二行表示哪个三位数？',
    figureNode: <SupplementFig4Bars />,
    analysis: [
      '7 种不同三横条对应数字 1,2,4,5,6,8,9（灰条/白条组合各不相同）',
      '比对 7 种图形：灰灰灰=6，灰灰白=4，灰白灰=1，灰白白=8，白灰灰=5，白灰白=2，白白灰=9',
      '第1行=521，第2行=<strong>658</strong>，第3行=146，第4行=692',
    ],
    type: 'none',
    finalQ: '第二行三位数是',
    finalUnit: '',
    finalAns: 658,
  },
  {
    id: '2-5-S7',
    title: '附加题5-1 · 双行圆',
    tag: 'type2',
    tagLabel: '数表图形',
    difficulty: 5,
    text: '上下两行圆圈按规律排列，最后空对上圆填多少？（1,1)(4,2)(4,7)(10,8)(16,13)(16,32)(?,?)',
    analysis: ['上圆分组规律', '末对上圆 <strong>28</strong>'],
    type: 'none',
    finalQ: '最后一对上圆填',
    finalUnit: '',
    finalAns: 28,
  },
  {
    id: '2-5-S8',
    title: '附加题5-2 · 箭头流',
    tag: 'type4',
    tagLabel: '综合挑战',
    difficulty: 5,
    text: '下图中所填的数之间有着统一的规律，那么空白圆圈内应该填多少？',
    figureNode: <SupplementFig5ArrowFlow />,
    analysis: [
      '斜箭头：上圆 − 下圆(左) = 下圆(右)',
      '99−72=27，45−27=18，39−18=21',
      '36−21=<strong>15</strong>',
    ],
    type: 'none',
    finalQ: '空白圆填',
    finalUnit: '',
    finalAns: 15,
  },
  {
    id: '2-5-S9',
    title: '附加题6-1 · 手套数',
    tag: 'type4',
    tagLabel: '综合挑战',
    difficulty: 5,
    text: '根据下面这些数的排列规律，在空白处准确的写下一个数。',
    figureNode: <SupplementFig6Mittens />,
    analysis: [
      '奇数 n=1,3,5,7… 依次填入',
      '每位：n，n×2，n×4 连写',
      'n=7：7，14，28 → <strong>71428</strong>',
    ],
    type: 'none',
    finalQ: '下一个数是',
    finalUnit: '',
    finalAns: 71428,
  },
  {
    id: '2-5-S10',
    title: '附加题6-2 · 镜像图形',
    tag: 'type4',
    tagLabel: '综合挑战',
    difficulty: 4,
    text: '从所给的四个选项中，选择最合适的一个填入问号处，使之呈现一定的规律性。',
    figureNode: (
      <img
        src="/img/math/53-S10.png"
        alt="附加题6-2 图形规律选择题"
        className="mx-auto w-full max-w-lg rounded-lg"
      />
    ),
    analysis: [
      '每格是数字 1、2、3、4 及其左右镜像拼成的对称图形',
      '下一格应为数字 5 的镜像对称图形',
      '选项 <strong>D</strong> 符合（A=1 B=2 C=3 D=4）',
    ],
    type: 'none',
    finalQ: '应选（A=1 B=2 C=3 D=4）',
    finalUnit: '',
    finalAns: 4,
  },
]

export const PROBLEMS: ProblemSet = {
  pretest: [],
  lesson: LESSON,
  homework: HOMEWORK,
  workbook: [],
  supplement: SUPPLEMENT,
}
