// AUTO-GENERATED DRAFT from pdftotext — review pinyin & lesson mapping before production use.
// Generated by docs/tmp/extract-g2-content.py

import type { AccumulationUnit } from './types'

export const ACCUMULATION: AccumulationUnit[] = [
  {
    "items": [
      {
        "text": "一九二九不出手，三九四九冰上走，五九六九，沿河看柳，七九河开，八九雁来，九九加一九，耕牛遍地走。"
      }
    ],
    "kind": "proverb",
    "unit": 2
  },
  {
    "items": [
      {
        "text": "有山皆图画，无水不文章。"
      },
      {
        "text": "白马西风塞上，杏花烟雨江南。"
      },
      {
        "text": "清风明月本无价，近水远山皆有情。"
      },
      {
        "text": "雾锁山头山锁雾，天连水尾水连天。"
      }
    ],
    "kind": "quote",
    "unit": 4
  },
  {
    "items": [
      {
        "text": "十年树木，百年树人。"
      },
      {
        "text": "树高百尺，叶落归根。"
      },
      {
        "text": "树无根不长，人无志不立。"
      }
    ],
    "kind": "quote",
    "unit": 5
  },
  {
    "items": [
      {
        "source": "《后汉书》",
        "text": "有志者事竟成。"
      },
      {
        "source": "诸葛亮",
        "text": "志当存高远。"
      },
      {
        "source": "王勃",
        "text": "穷且益坚，不坠青云之志。"
      }
    ],
    "kind": "quote",
    "unit": 6
  },
  {
    "items": [
      {
        "source": "《论语》",
        "text": "己所不欲，勿施于人。"
      },
      {
        "source": "《论语》",
        "text": "与朋友交，言而有信。"
      },
      {
        "source": "《孟子》",
        "text": "不以规矩，不能成方圆。"
      }
    ],
    "kind": "quote",
    "unit": 8
  }
]
