// AUTO-GENERATED DRAFT from pdftotext — review pinyin & lesson mapping before production use.
// Generated by docs/tmp/extract-g2-content.py

import type { PhraseEntry } from './types'

export const PHRASES: PhraseEntry[] = [
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "脑袋"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "口袋"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "袋子"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "袋鼠"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "快活"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "生活"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "活动"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "活力"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "欢迎"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "迎接"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "迎风"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "迎面"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 2,
    "lessonKey": "u1-l2",
    "phrase": "灌"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 2,
    "lessonKey": "u1-l2",
    "phrase": "溉"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 2,
    "lessonKey": "u1-l2",
    "phrase": "田"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 2,
    "lessonKey": "u1-l2",
    "phrase": "地"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 2,
    "lessonKey": "u1-l2",
    "phrase": "发"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 2,
    "lessonKey": "u1-l2",
    "phrase": "动"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 2,
    "lessonKey": "u1-l2",
    "phrase": "机"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 2,
    "lessonKey": "u1-l2",
    "phrase": "器"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 2,
    "lessonKey": "u1-l2",
    "phrase": "淹"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 2,
    "lessonKey": "u1-l2",
    "phrase": "没"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 2,
    "lessonKey": "u1-l2",
    "phrase": "庄"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 2,
    "lessonKey": "u1-l2",
    "phrase": "稼"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 2,
    "lessonKey": "u1-l2",
    "phrase": "冲"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 2,
    "lessonKey": "u1-l2",
    "phrase": "毁"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 2,
    "lessonKey": "u1-l2",
    "phrase": "房"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 2,
    "lessonKey": "u1-l2",
    "phrase": "屋"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 1,
    "lesson": 2,
    "lessonKey": "u1-l2",
    "phrase": "读轻声"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 2,
    "lesson": 2,
    "lessonKey": "u2-l2",
    "phrase": "十年树木百年树人"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 2,
    "lesson": 2,
    "lessonKey": "u2-l2",
    "phrase": "树高百尺叶落归根"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 2,
    "lesson": 4,
    "lessonKey": "u2-l4",
    "phrase": "耕田"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 2,
    "lesson": 4,
    "lessonKey": "u2-l4",
    "phrase": "犁地"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 2,
    "lesson": 4,
    "lessonKey": "u2-l4",
    "phrase": "播种"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 2,
    "lesson": 4,
    "lessonKey": "u2-l4",
    "phrase": "插秧"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 2,
    "lesson": 4,
    "lessonKey": "u2-l4",
    "phrase": "除草"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 2,
    "lesson": 4,
    "lessonKey": "u2-l4",
    "phrase": "割麦"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 2,
    "lesson": 4,
    "lessonKey": "u2-l4",
    "phrase": "打谷"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 4,
    "lesson": 7,
    "lessonKey": "u4-l7",
    "phrase": "穷尽"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 4,
    "lesson": 7,
    "lessonKey": "u4-l7",
    "phrase": "山穷水尽"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 4,
    "lesson": 7,
    "lessonKey": "u4-l7",
    "phrase": "层叠"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 4,
    "lesson": 7,
    "lessonKey": "u4-l7",
    "phrase": "层林叠翠"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 4,
    "lesson": 7,
    "lessonKey": "u4-l7",
    "phrase": "烟云"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 4,
    "lesson": 7,
    "lessonKey": "u4-l7",
    "phrase": "烟消云散"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 4,
    "lesson": 7,
    "lessonKey": "u4-l7",
    "phrase": "山川"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 4,
    "lesson": 7,
    "lessonKey": "u4-l7",
    "phrase": "名山大川"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 4,
    "lesson": 9,
    "lessonKey": "u4-l9",
    "phrase": "群山环绕"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 4,
    "lesson": 9,
    "lessonKey": "u4-l9",
    "phrase": "名胜古迹"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 4,
    "lesson": 9,
    "lessonKey": "u4-l9",
    "phrase": "点点灯光"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 4,
    "lesson": 9,
    "lessonKey": "u4-l9",
    "phrase": "树木茂盛"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 4,
    "lesson": 9,
    "lessonKey": "u4-l9",
    "phrase": "山清水秀"
  },
  {
    "grade": 2,
    "semester": "上",
    "unit": 4,
    "lesson": 9,
    "lessonKey": "u4-l9",
    "phrase": "蒙蒙细雨"
  }
]
