// AUTO-GENERATED DRAFT from pdftotext — review pinyin & lesson mapping before production use.
// Generated by docs/tmp/extract-g2-content.py

import type { PoemEntry } from './types'

export const POEMS: PoemEntry[] = [
  {
    "id": "mei-hua",
    "title": "梅花",
    "author": "王安石",
    "dynasty": "宋",
    "source": "garden",
    "unit": 1,
    "requiresRecite": true,
    "lines": [
      "墙角数枝梅，",
      "凌寒独自开。",
      "遥知不是雪，",
      "为有暗香来。"
    ]
  },
  {
    "id": "xiao-er-chui-diao",
    "title": "小儿垂钓",
    "author": "胡令能",
    "dynasty": "唐",
    "source": "garden",
    "unit": 3,
    "requiresRecite": true,
    "lines": [
      "蓬头稚子学垂纶，",
      "侧坐莓苔草映身。",
      "路人借问遥招手，",
      "怕得鱼惊不应人。"
    ]
  },
  {
    "id": "deng-guan-que-lou",
    "title": "登鹳雀楼",
    "author": "王之涣",
    "dynasty": "唐",
    "source": "lesson",
    "unit": 4,
    "lesson": 7,
    "requiresRecite": true,
    "lines": [
      "白日依山尽，",
      "黄河入海流。",
      "欲穷千里目，",
      "更上一层楼。"
    ]
  },
  {
    "id": "wang-lu-shan-pu-bu",
    "title": "望庐山瀑布",
    "author": "李白",
    "dynasty": "唐",
    "source": "lesson",
    "unit": 4,
    "lesson": 7,
    "requiresRecite": true,
    "lines": [
      "日照香炉生紫烟，",
      "遥看瀑布挂前川。",
      "飞流直下三千尺，",
      "疑是银河落九天。"
    ]
  },
  {
    "id": "jiang-xue",
    "title": "江雪",
    "author": "柳宗元",
    "dynasty": "唐",
    "source": "lesson",
    "unit": 7,
    "lesson": 18,
    "requiresRecite": true,
    "lines": [
      "千山鸟飞绝，",
      "万径人踪灭。",
      "孤舟蓑笠翁，",
      "独钓寒江雪。"
    ]
  },
  {
    "id": "chi-le-ge",
    "title": "敕勒歌",
    "author": "北朝民歌",
    "dynasty": "北",
    "source": "lesson",
    "unit": 7,
    "lesson": 18,
    "requiresRecite": true,
    "lines": [
      "敕勒川，阴山下，",
      "天似穹庐，笼盖四野。",
      "天苍苍，野茫茫，",
      "风吹草低见牛羊。"
    ]
  },
  {
    "id": "ye-su-shan-si",
    "title": "夜宿山寺",
    "author": "李白",
    "dynasty": "唐",
    "source": "garden",
    "unit": 7,
    "requiresRecite": true,
    "lines": [
      "危楼高百尺，",
      "手可摘星辰。",
      "不敢高声语，",
      "恐惊天上人。"
    ]
  }
]
