// AUTO-GENERATED DRAFT from pdftotext — review pinyin & lesson mapping before production use.
// Generated by docs/tmp/extract-chinese-g2.py

import type { ChineseUnitEntry } from './types'

export const UNITS: ChineseUnitEntry[] = [
  {
    "unit": 1,
    "title": "第一单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 1,
        "title": "小蝌蚪找妈妈",
        "requiresRecite": false
      },
      {
        "lesson": 2,
        "title": "我是什么",
        "requiresRecite": false
      },
      {
        "lesson": 3,
        "title": "植物妈妈有办法",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地一",
        "kind": "garden"
      },
      {
        "lesson": 0,
        "title": "快乐读书吧",
        "kind": "happy_reading"
      }
    ]
  },
  {
    "unit": 2,
    "title": "第二单元·识字",
    "unitType": "literacy",
    "lessons": [
      {
        "lesson": 1,
        "title": "场景歌",
        "requiresRecite": false
      },
      {
        "lesson": 2,
        "title": "树之歌",
        "requiresRecite": false
      },
      {
        "lesson": 3,
        "title": "拍手歌",
        "requiresRecite": false
      },
      {
        "lesson": 4,
        "title": "田家四季歌",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地二",
        "kind": "garden"
      }
    ]
  },
  {
    "unit": 3,
    "title": "第三单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 4,
        "title": "彩虹",
        "requiresRecite": false
      },
      {
        "lesson": 5,
        "title": "去外婆家",
        "requiresRecite": false
      },
      {
        "lesson": 6,
        "title": "数星星的孩子",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地三",
        "kind": "garden"
      }
    ]
  },
  {
    "unit": 4,
    "title": "第四单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 7,
        "title": "古诗二首",
        "requiresRecite": true,
        "isPoem": true,
        "subPoems": [
          "登鹳雀楼",
          "望庐山瀑布"
        ]
      },
      {
        "lesson": 8,
        "title": "黄山奇石",
        "requiresRecite": false
      },
      {
        "lesson": 9,
        "title": "日月潭",
        "requiresRecite": false
      },
      {
        "lesson": 10,
        "title": "葡萄沟",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地四",
        "kind": "garden"
      }
    ]
  },
  {
    "unit": 5,
    "title": "第五单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 11,
        "title": "坐井观天",
        "requiresRecite": false
      },
      {
        "lesson": 12,
        "title": "寒号鸟",
        "requiresRecite": false
      },
      {
        "lesson": 13,
        "title": "我要的是葫芦",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地五",
        "kind": "garden"
      }
    ]
  },
  {
    "unit": 6,
    "title": "第六单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 14,
        "title": "八角楼上",
        "requiresRecite": false
      },
      {
        "lesson": 15,
        "title": "朱德的扁担",
        "requiresRecite": false
      },
      {
        "lesson": 16,
        "title": "难忘的泼水节",
        "requiresRecite": false
      },
      {
        "lesson": 17,
        "title": "刘胡兰",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地六",
        "kind": "garden"
      }
    ]
  },
  {
    "unit": 7,
    "title": "第七单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 18,
        "title": "古诗二首",
        "requiresRecite": true,
        "isPoem": true,
        "subPoems": [
          "江雪",
          "敕勒歌"
        ]
      },
      {
        "lesson": 19,
        "title": "雾在哪里",
        "requiresRecite": false
      },
      {
        "lesson": 20,
        "title": "雪孩子",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地七",
        "kind": "garden"
      }
    ]
  },
  {
    "unit": 8,
    "title": "第八单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 21,
        "title": "称赞",
        "requiresRecite": false
      },
      {
        "lesson": 22,
        "title": "纸船和风筝",
        "requiresRecite": false
      },
      {
        "lesson": 23,
        "title": "快乐的小河",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地八",
        "kind": "garden"
      }
    ]
  }
]
