// AUTO-GENERATED DRAFT from pdftotext — review pinyin & lesson mapping before production use.
// Generated by docs/tmp/extract-g2-content.py

import type { AccumulationUnit } from './types'

export const ACCUMULATION: AccumulationUnit[] = [
  {
    "items": [
      {
        "text": "予人玫瑰，手有余香。"
      },
      {
        "text": "平时肯帮人，急时有人帮。"
      },
      {
        "text": "与其锦上添花，不如雪中送炭。"
      }
    ],
    "kind": "proverb",
    "unit": 2
  },
  {
    "items": [
      {
        "text": "子鼠 丑牛 寅虎 卯兔 辰龙 巳蛇 午马 未羊 申猴 酉鸡 戌狗 亥猪"
      }
    ],
    "kind": "quote",
    "unit": 3
  },
  {
    "items": [
      {
        "source": "《老子》",
        "text": "轻诺必寡信。"
      },
      {
        "source": "《左传》",
        "text": "失信不立。"
      },
      {
        "source": "《韩非子》",
        "text": "小信成则大信立。"
      }
    ],
    "kind": "quote",
    "unit": 4
  },
  {
    "items": [
      {
        "text": "冠必正，纽必结，袜与履，俱紧切。"
      },
      {
        "text": "置冠服，有定位，勿乱顿，致污秽。"
      },
      {
        "text": "唯德学，唯才艺，不如人，当自砺。"
      },
      {
        "text": "若衣服，若饮食，不如人，勿生戚。"
      }
    ],
    "kind": "quote",
    "unit": 5
  },
  {
    "items": [
      {
        "text": "春雨惊春清谷天，夏满芒夏暑相连。秋处露秋寒霜降，冬雪雪冬小大寒。"
      }
    ],
    "kind": "proverb",
    "unit": 6
  }
]
