// AUTO-GENERATED DRAFT from pdftotext — review pinyin & lesson mapping before production use.
// Generated by docs/tmp/extract-g2-content.py

import type { PhraseEntry } from './types'

export const PHRASES: PhraseEntry[] = [
  {
    "grade": 2,
    "semester": "下",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "祝贺"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "可喜可贺"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "丝绸"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "蚕丝"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "吹拂"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "春风拂面"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "河堤"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 1,
    "lesson": 1,
    "lessonKey": "u1-l1",
    "phrase": "堤岸"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 2,
    "lesson": 6,
    "lessonKey": "u2-l6",
    "phrase": "蛋糕"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 2,
    "lesson": 6,
    "lessonKey": "u2-l6",
    "phrase": "雪糕"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 2,
    "lesson": 6,
    "lessonKey": "u2-l6",
    "phrase": "糕点"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 2,
    "lesson": 6,
    "lessonKey": "u2-l6",
    "phrase": "品尝"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 2,
    "lesson": 6,
    "lessonKey": "u2-l6",
    "phrase": "尝鲜"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 2,
    "lesson": 6,
    "lessonKey": "u2-l6",
    "phrase": "尝试"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 2,
    "lesson": 6,
    "lessonKey": "u2-l6",
    "phrase": "米粉"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 2,
    "lesson": 6,
    "lessonKey": "u2-l6",
    "phrase": "面粉"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 2,
    "lesson": 6,
    "lessonKey": "u2-l6",
    "phrase": "粉丝"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 2,
    "lesson": 6,
    "lessonKey": "u2-l6",
    "phrase": "确定"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 2,
    "lesson": 6,
    "lessonKey": "u2-l6",
    "phrase": "确实"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 2,
    "lesson": 6,
    "lessonKey": "u2-l6",
    "phrase": "正确"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 1,
    "lessonKey": "u3-l1",
    "phrase": "华夏儿女"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 1,
    "lessonKey": "u3-l1",
    "phrase": "炎黄子孙"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 1,
    "lessonKey": "u3-l1",
    "phrase": "神州大地"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 1,
    "lessonKey": "u3-l1",
    "phrase": "巍巍中华"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 1,
    "lessonKey": "u3-l1",
    "phrase": "民族团结"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 1,
    "lessonKey": "u3-l1",
    "phrase": "世界大同"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 1,
    "lessonKey": "u3-l1",
    "phrase": "奋发图强"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 1,
    "lessonKey": "u3-l1",
    "phrase": "繁荣昌盛"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 3,
    "lessonKey": "u3-l3",
    "phrase": "珍贵"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 3,
    "lessonKey": "u3-l3",
    "phrase": "贵重"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 3,
    "lessonKey": "u3-l3",
    "phrase": "损坏"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 3,
    "lessonKey": "u3-l3",
    "phrase": "破损"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 3,
    "lessonKey": "u3-l3",
    "phrase": "硬币"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 3,
    "lessonKey": "u3-l3",
    "phrase": "纸币"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 3,
    "lessonKey": "u3-l3",
    "phrase": "财富"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 3,
    "lessonKey": "u3-l3",
    "phrase": "财产"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 3,
    "lessonKey": "u3-l3",
    "phrase": "赔本"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 3,
    "lessonKey": "u3-l3",
    "phrase": "赔礼"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 3,
    "lessonKey": "u3-l3",
    "phrase": "购买"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 3,
    "lessonKey": "u3-l3",
    "phrase": "采购"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 3,
    "lessonKey": "u3-l3",
    "phrase": "铜镜"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 3,
    "lesson": 3,
    "lessonKey": "u3-l3",
    "phrase": "珠宝"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "聊天"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "闲聊"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "无聊"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "葱郁"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "浓郁"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "郁闷"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "精灵"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "精力"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "精彩"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "梦境"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "环境"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "境界"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 5,
    "lesson": 12,
    "lessonKey": "u5-l12",
    "phrase": "卧室"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 5,
    "lesson": 12,
    "lessonKey": "u5-l12",
    "phrase": "教室"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 5,
    "lesson": 12,
    "lessonKey": "u5-l12",
    "phrase": "办公室"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 5,
    "lesson": 12,
    "lessonKey": "u5-l12",
    "phrase": "而且"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 5,
    "lesson": 12,
    "lessonKey": "u5-l12",
    "phrase": "反而"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 5,
    "lesson": 12,
    "lessonKey": "u5-l12",
    "phrase": "视而不见"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 5,
    "lesson": 12,
    "lessonKey": "u5-l12",
    "phrase": "审题"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 5,
    "lesson": 12,
    "lessonKey": "u5-l12",
    "phrase": "审美"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 5,
    "lesson": 12,
    "lessonKey": "u5-l12",
    "phrase": "审判员"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 5,
    "lesson": 12,
    "lessonKey": "u5-l12",
    "phrase": "喜悦"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 5,
    "lesson": 12,
    "lessonKey": "u5-l12",
    "phrase": "愉悦"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 5,
    "lesson": 12,
    "lessonKey": "u5-l12",
    "phrase": "赏心悦目"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 16,
    "lessonKey": "u6-l16",
    "phrase": "慌张"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 16,
    "lessonKey": "u6-l16",
    "phrase": "辨别"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 16,
    "lessonKey": "u6-l16",
    "phrase": "忠实"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 16,
    "lessonKey": "u6-l16",
    "phrase": "向导"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 16,
    "lessonKey": "u6-l16",
    "phrase": "永远"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 16,
    "lessonKey": "u6-l16",
    "phrase": "惊慌"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 16,
    "lessonKey": "u6-l16",
    "phrase": "分辨"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 16,
    "lessonKey": "u6-l16",
    "phrase": "忠诚"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 16,
    "lessonKey": "u6-l16",
    "phrase": "导游"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 16,
    "lessonKey": "u6-l16",
    "phrase": "永久"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 16,
    "lessonKey": "u6-l16",
    "phrase": "的人"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 17,
    "lessonKey": "u6-l17",
    "phrase": "平稳"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 17,
    "lessonKey": "u6-l17",
    "phrase": "四平八稳"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 17,
    "lessonKey": "u6-l17",
    "phrase": "牢固"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 17,
    "lessonKey": "u6-l17",
    "phrase": "稳固"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 17,
    "lessonKey": "u6-l17",
    "phrase": "姿态"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 17,
    "lessonKey": "u6-l17",
    "phrase": "千姿百态"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 17,
    "lessonKey": "u6-l17",
    "phrase": "使劲"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 6,
    "lesson": 17,
    "lessonKey": "u6-l17",
    "phrase": "使用"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 7,
    "lesson": 21,
    "lessonKey": "u7-l21",
    "phrase": "生机勃勃"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 7,
    "lesson": 21,
    "lessonKey": "u7-l21",
    "phrase": "尽心竭力"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 7,
    "lesson": 21,
    "lessonKey": "u7-l21",
    "phrase": "与世隔绝"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 7,
    "lesson": 21,
    "lessonKey": "u7-l21",
    "phrase": "笨手笨脚"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 7,
    "lesson": 21,
    "lessonKey": "u7-l21",
    "phrase": "色彩斑斓"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 7,
    "lesson": 21,
    "lessonKey": "u7-l21",
    "phrase": "九牛二虎之力"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 8,
    "lesson": 24,
    "lessonKey": "u8-l24",
    "phrase": "洪水"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 8,
    "lesson": 24,
    "lessonKey": "u8-l24",
    "phrase": "防洪"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 8,
    "lesson": 24,
    "lessonKey": "u8-l24",
    "phrase": "毁坏"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 8,
    "lesson": 24,
    "lessonKey": "u8-l24",
    "phrase": "损毁"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 8,
    "lesson": 24,
    "lessonKey": "u8-l24",
    "phrase": "毒蛇"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 8,
    "lesson": 24,
    "lessonKey": "u8-l24",
    "phrase": "毒害"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 8,
    "lesson": 24,
    "lessonKey": "u8-l24",
    "phrase": "继续"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 8,
    "lesson": 24,
    "lessonKey": "u8-l24",
    "phrase": "连续"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 8,
    "lesson": 24,
    "lessonKey": "u8-l24",
    "phrase": "疏通"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 8,
    "lesson": 24,
    "lessonKey": "u8-l24",
    "phrase": "稀疏"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 8,
    "lesson": 24,
    "lessonKey": "u8-l24",
    "phrase": "驱赶"
  },
  {
    "grade": 2,
    "semester": "下",
    "unit": 8,
    "lesson": 24,
    "lessonKey": "u8-l24",
    "phrase": "驱除"
  }
]
