// AUTO-GENERATED DRAFT from pdftotext — review pinyin & lesson mapping before production use.
// Generated by docs/tmp/extract-g2-content.py

import type { PoemEntry } from './types'

export const POEMS: PoemEntry[] = [
  {
    "id": "yong-liu",
    "title": "咏柳",
    "author": "贺知章",
    "dynasty": "唐",
    "source": "lesson",
    "unit": 1,
    "lesson": 1,
    "requiresRecite": true,
    "lines": [
      "碧玉妆成一树高，",
      "万条垂下绿丝绦。",
      "不知细叶谁裁出，",
      "二月春风似剪刀。"
    ]
  },
  {
    "id": "cun-ju",
    "title": "村居",
    "author": "高鼎",
    "dynasty": "清",
    "source": "lesson",
    "unit": 1,
    "lesson": 1,
    "requiresRecite": true,
    "lines": [
      "草长莺飞二月天，",
      "拂堤杨柳醉春烟。",
      "儿童散学归来早，",
      "忙趁东风放纸鸢。"
    ]
  },
  {
    "id": "fu-de-gu-yuan-cao",
    "title": "赋得古原草送别（节选）",
    "author": "白居易",
    "dynasty": "唐",
    "source": "garden",
    "unit": 1,
    "requiresRecite": true,
    "lines": [
      "离离原上草，",
      "一岁一枯荣。",
      "野火烧不尽，",
      "春风吹又生。"
    ]
  },
  {
    "id": "jue-ju",
    "title": "绝句",
    "author": "杜甫",
    "dynasty": "唐",
    "source": "lesson",
    "unit": 6,
    "lesson": 14,
    "requiresRecite": true,
    "lines": [
      "两个黄鹂鸣翠柳，",
      "一行白鹭上青天。",
      "窗含西岭千秋雪，",
      "门泊东吴万里船。"
    ]
  },
  {
    "id": "xiao-chu-jing-ci-si",
    "title": "晓出净慈寺送林子方",
    "author": "杨万里",
    "dynasty": "宋",
    "source": "lesson",
    "unit": 6,
    "lesson": 14,
    "requiresRecite": true,
    "lines": [
      "毕竟西湖六月中，",
      "风光不与四时同。",
      "接天莲叶无穷碧，",
      "映日荷花别样红。"
    ]
  },
  {
    "id": "min-nong",
    "title": "悯农（其一）",
    "author": "李绅",
    "dynasty": "唐",
    "source": "garden",
    "unit": 7,
    "requiresRecite": true,
    "lines": [
      "春种一粒粟，",
      "秋收万颗子。",
      "四海无闲田，",
      "农夫犹饿死。"
    ]
  },
  {
    "id": "jiang-shang-yu-zhe",
    "title": "江上渔者",
    "author": "范仲淹",
    "dynasty": "宋",
    "source": "garden",
    "unit": 8,
    "requiresRecite": true,
    "lines": [
      "江上往来人，",
      "但爱鲈鱼美。",
      "君看一叶舟，",
      "出没风波里。"
    ]
  }
]
