// AUTO-GENERATED DRAFT from pdftotext — review pinyin & lesson mapping before production use.
// Generated by docs/tmp/extract-chinese-g2.py

import type { RadicalEntry } from './types'

export const RADICALS: RadicalEntry[] = []
