// AUTO-GENERATED DRAFT from pdftotext — review pinyin & lesson mapping before production use.
// Generated by docs/tmp/extract-chinese-g2.py

import type { ChineseUnitEntry } from './types'

export const UNITS: ChineseUnitEntry[] = [
  {
    "unit": 1,
    "title": "第一单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 1,
        "title": "古诗二首",
        "requiresRecite": true,
        "isPoem": true,
        "subPoems": [
          "咏柳",
          "村居"
        ]
      },
      {
        "lesson": 2,
        "title": "找春天",
        "requiresRecite": false
      },
      {
        "lesson": 3,
        "title": "开满鲜花的小路",
        "requiresRecite": false
      },
      {
        "lesson": 4,
        "title": "邓小平爷爷植树",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地一",
        "kind": "garden"
      },
      {
        "lesson": 0,
        "title": "快乐读书吧",
        "kind": "happy_reading"
      }
    ]
  },
  {
    "unit": 2,
    "title": "第二单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 5,
        "title": "雷锋叔叔，你在哪里",
        "requiresRecite": false
      },
      {
        "lesson": 6,
        "title": "千人糕",
        "requiresRecite": false
      },
      {
        "lesson": 7,
        "title": "我不是最弱小的",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地二",
        "kind": "garden"
      }
    ]
  },
  {
    "unit": 3,
    "title": "第三单元·识字",
    "unitType": "literacy",
    "lessons": [
      {
        "lesson": 1,
        "title": "神州谣",
        "requiresRecite": false
      },
      {
        "lesson": 2,
        "title": "传统节日",
        "requiresRecite": false
      },
      {
        "lesson": 3,
        "title": "“贝”的故事",
        "requiresRecite": false
      },
      {
        "lesson": 4,
        "title": "中国美食",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地三",
        "kind": "garden"
      }
    ]
  },
  {
    "unit": 4,
    "title": "第四单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 8,
        "title": "彩色的梦",
        "requiresRecite": false
      },
      {
        "lesson": 9,
        "title": "一匹出色的马",
        "requiresRecite": false
      },
      {
        "lesson": 10,
        "title": "枫树上的喜鹊",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地四",
        "kind": "garden"
      }
    ]
  },
  {
    "unit": 5,
    "title": "第五单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 11,
        "title": "寓言二则",
        "requiresRecite": false
      },
      {
        "lesson": 12,
        "title": "画杨桃",
        "requiresRecite": false
      },
      {
        "lesson": 13,
        "title": "小马过河",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地五",
        "kind": "garden"
      }
    ]
  },
  {
    "unit": 6,
    "title": "第六单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 14,
        "title": "古诗二首",
        "requiresRecite": true,
        "isPoem": true,
        "subPoems": [
          "绝句",
          "晓出净慈寺送林子方"
        ]
      },
      {
        "lesson": 15,
        "title": "雷雨",
        "requiresRecite": false
      },
      {
        "lesson": 16,
        "title": "要是你在野外迷了路",
        "requiresRecite": false
      },
      {
        "lesson": 17,
        "title": "太空生活趣事多",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地六",
        "kind": "garden"
      }
    ]
  },
  {
    "unit": 7,
    "title": "第七单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 18,
        "title": "大象的耳朵",
        "requiresRecite": false
      },
      {
        "lesson": 19,
        "title": "蜘蛛开店",
        "requiresRecite": false
      },
      {
        "lesson": 20,
        "title": "青蛙卖泥塘",
        "requiresRecite": false
      },
      {
        "lesson": 21,
        "title": "小毛虫",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地七",
        "kind": "garden"
      }
    ]
  },
  {
    "unit": 8,
    "title": "第八单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 22,
        "title": "羿射九日",
        "requiresRecite": false
      },
      {
        "lesson": 23,
        "title": "黄帝的传说",
        "requiresRecite": false
      },
      {
        "lesson": 24,
        "title": "大禹治水",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地八",
        "kind": "garden"
      }
    ]
  }
]
