// AUTO-GENERATED DRAFT from docs/tmp/语文一年级下册.pdf — review pinyin & lesson mapping before production use.
// Generated by docs/tmp/extract-chinese-g1-down.py

import type { PhraseEntry } from './types'

export const PHRASES: PhraseEntry[] = [
  {
    "grade": 1,
    "semester": "下",
    "unit": 2,
    "lesson": 2,
    "lessonKey": "u2-l2",
    "phrase": "水井"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 2,
    "lesson": 2,
    "lessonKey": "u2-l2",
    "phrase": "井口"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 2,
    "lesson": 2,
    "lessonKey": "u2-l2",
    "phrase": "主席"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 2,
    "lesson": 2,
    "lessonKey": "u2-l2",
    "phrase": "主动"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 2,
    "lesson": 2,
    "lessonKey": "u2-l2",
    "phrase": "乡村"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 2,
    "lesson": 2,
    "lessonKey": "u2-l2",
    "phrase": "村子"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 2,
    "lesson": 2,
    "lessonKey": "u2-l2",
    "phrase": "乡亲"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 2,
    "lesson": 2,
    "lessonKey": "u2-l2",
    "phrase": "亲人"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 2,
    "lesson": 2,
    "lessonKey": "u2-l2",
    "phrase": "想念"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 2,
    "lesson": 2,
    "lessonKey": "u2-l2",
    "phrase": "念书"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 2,
    "lesson": 2,
    "lessonKey": "u2-l2",
    "phrase": "战士"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 2,
    "lesson": 2,
    "lessonKey": "u2-l2",
    "phrase": "战友"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 2,
    "lesson": 3,
    "lessonKey": "u2-l3",
    "phrase": "弯弯的小路"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 2,
    "lesson": 3,
    "lessonKey": "u2-l3",
    "phrase": "宽宽的公路"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 2,
    "lesson": 3,
    "lessonKey": "u2-l3",
    "phrase": "美丽的天山"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 2,
    "lesson": 3,
    "lessonKey": "u2-l3",
    "phrase": "洁白的雪莲"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 2,
    "lesson": 3,
    "lessonKey": "u2-l3",
    "phrase": "雄伟的天安门"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 2,
    "lesson": 3,
    "lessonKey": "u2-l3",
    "phrase": "壮观的升旗仪式"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 3,
    "lesson": 5,
    "lessonKey": "u3-l5",
    "phrase": "从前"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 3,
    "lesson": 5,
    "lessonKey": "u3-l5",
    "phrase": "喜鹊"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 3,
    "lesson": 5,
    "lessonKey": "u3-l5",
    "phrase": "孤单"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 3,
    "lesson": 5,
    "lessonKey": "u3-l5",
    "phrase": "叽叽喳喳"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 3,
    "lesson": 5,
    "lessonKey": "u3-l5",
    "phrase": "后来"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 3,
    "lesson": 5,
    "lessonKey": "u3-l5",
    "phrase": "邻居"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 3,
    "lesson": 5,
    "lessonKey": "u3-l5",
    "phrase": "快乐"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 3,
    "lesson": 5,
    "lessonKey": "u3-l5",
    "phrase": "安安静静"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "胆子"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "胆量"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "大胆"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "勇敢"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "勇气"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "勇士"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "样子"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "一样"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "花样"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "再见"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "再三"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 4,
    "lesson": 8,
    "lessonKey": "u4-l8",
    "phrase": "再次"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 5,
    "lessonKey": "u5-l5",
    "phrase": "蜻蜓展翅"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 5,
    "lessonKey": "u5-l5",
    "phrase": "蝴蝶飞舞"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 5,
    "lessonKey": "u5-l5",
    "phrase": "蚯蚓松土"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 5,
    "lessonKey": "u5-l5",
    "phrase": "蚂蚁搬家"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 5,
    "lessonKey": "u5-l5",
    "phrase": "蝌蚪游泳"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 5,
    "lessonKey": "u5-l5",
    "phrase": "蜘蛛结网"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 6,
    "lessonKey": "u5-l6",
    "phrase": "和风细雨"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 6,
    "lessonKey": "u5-l6",
    "phrase": "夕阳"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 6,
    "lessonKey": "u5-l6",
    "phrase": "严寒"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 6,
    "lessonKey": "u5-l6",
    "phrase": "酷暑"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 6,
    "lessonKey": "u5-l6",
    "phrase": "鸟语花香"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 6,
    "lessonKey": "u5-l6",
    "phrase": "朝霞"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 6,
    "lessonKey": "u5-l6",
    "phrase": "方圆"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 8,
    "lessonKey": "u5-l8",
    "phrase": "相近"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 8,
    "lessonKey": "u5-l8",
    "phrase": "相反"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 8,
    "lessonKey": "u5-l8",
    "phrase": "学习"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 8,
    "lessonKey": "u5-l8",
    "phrase": "练习"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 8,
    "lessonKey": "u5-l8",
    "phrase": "知道"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 8,
    "lessonKey": "u5-l8",
    "phrase": "道路"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 8,
    "lessonKey": "u5-l8",
    "phrase": "专心"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 5,
    "lesson": 8,
    "lessonKey": "u5-l8",
    "phrase": "专门"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 10,
    "lessonKey": "u6-l10",
    "phrase": "浮萍"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 10,
    "lessonKey": "u6-l10",
    "phrase": "飘浮"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 10,
    "lessonKey": "u6-l10",
    "phrase": "爱惜"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 10,
    "lessonKey": "u6-l10",
    "phrase": "可惜"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 10,
    "lessonKey": "u6-l10",
    "phrase": "泉水"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 10,
    "lessonKey": "u6-l10",
    "phrase": "清泉"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 10,
    "lessonKey": "u6-l10",
    "phrase": "照样"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 10,
    "lessonKey": "u6-l10",
    "phrase": "照片"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 10,
    "lessonKey": "u6-l10",
    "phrase": "柔美"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 10,
    "lessonKey": "u6-l10",
    "phrase": "轻柔"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 10,
    "lessonKey": "u6-l10",
    "phrase": "荷花"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 10,
    "lessonKey": "u6-l10",
    "phrase": "荷叶"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 13,
    "lessonKey": "u6-l13",
    "phrase": "水面"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 13,
    "lessonKey": "u6-l13",
    "phrase": "闷热"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 13,
    "lessonKey": "u6-l13",
    "phrase": "消息"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 13,
    "lessonKey": "u6-l13",
    "phrase": "弯腰"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 13,
    "lessonKey": "u6-l13",
    "phrase": "有空"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 13,
    "lessonKey": "u6-l13",
    "phrase": "连忙"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 6,
    "lesson": 13,
    "lessonKey": "u6-l13",
    "phrase": "阴沉沉"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 7,
    "lesson": 14,
    "lessonKey": "u7-l14",
    "phrase": "新书"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 7,
    "lesson": 14,
    "lessonKey": "u7-l14",
    "phrase": "新年"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 7,
    "lesson": 14,
    "lessonKey": "u7-l14",
    "phrase": "新手"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 7,
    "lesson": 14,
    "lessonKey": "u7-l14",
    "phrase": "清新"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 7,
    "lesson": 14,
    "lessonKey": "u7-l14",
    "phrase": "平安"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 7,
    "lesson": 14,
    "lessonKey": "u7-l14",
    "phrase": "平时"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 7,
    "lesson": 14,
    "lessonKey": "u7-l14",
    "phrase": "平常"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 7,
    "lesson": 14,
    "lessonKey": "u7-l14",
    "phrase": "平地"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 7,
    "lesson": 14,
    "lessonKey": "u7-l14",
    "phrase": "伙伴"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 7,
    "lesson": 14,
    "lessonKey": "u7-l14",
    "phrase": "做伴"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 7,
    "lesson": 14,
    "lessonKey": "u7-l14",
    "phrase": "相伴"
  },
  {
    "grade": 1,
    "semester": "下",
    "unit": 7,
    "lesson": 14,
    "lessonKey": "u7-l14",
    "phrase": "结伴"
  }
]
