// AUTO-GENERATED DRAFT from docs/tmp/语文一年级下册.pdf — review pinyin & lesson mapping before production use.
// Generated by docs/tmp/extract-chinese-g1-down.py

import type { PoemEntry } from './types'

export const POEMS: PoemEntry[] = [
  {
    "id": "jing-ye-si",
    "title": "静夜思",
    "author": "李白",
    "dynasty": "唐",
    "source": "lesson",
    "unit": 4,
    "lesson": 7,
    "lines": [
      "床前明月光，",
      "疑是地上霜。",
      "举头望明月，",
      "低头思故乡。"
    ],
    "requiresRecite": true
  },
  {
    "id": "chi-shang",
    "title": "池上",
    "author": "白居易",
    "dynasty": "唐",
    "source": "lesson",
    "unit": 6,
    "lesson": 10,
    "lines": [
      "小娃撑小艇，",
      "偷采白莲回。",
      "不解藏踪迹，",
      "浮萍一道开。"
    ],
    "requiresRecite": true
  },
  {
    "id": "xiao-chi",
    "title": "小池",
    "author": "杨万里",
    "dynasty": "宋",
    "source": "lesson",
    "unit": 6,
    "lesson": 10,
    "lines": [
      "泉眼无声惜细流，",
      "树阴照水爱晴柔。",
      "小荷才露尖尖角，",
      "早有蜻蜓立上头。"
    ],
    "requiresRecite": true
  },
  {
    "id": "chun-xiao",
    "title": "春晓",
    "author": "孟浩然",
    "dynasty": "唐",
    "source": "garden",
    "unit": 1,
    "lines": [
      "春眠不觉晓，",
      "处处闻啼鸟。",
      "夜来风雨声，",
      "花落知多少。"
    ],
    "requiresRecite": true
  },
  {
    "id": "xun-yin-zhe",
    "title": "寻隐者不遇",
    "author": "贾岛",
    "dynasty": "唐",
    "source": "garden",
    "unit": 2,
    "lines": [
      "松下问童子，",
      "言师采药去。",
      "只在此山中，",
      "云深不知处。"
    ],
    "requiresRecite": true
  },
  {
    "id": "zeng-wang-lun",
    "title": "赠汪伦",
    "author": "李白",
    "dynasty": "唐",
    "source": "garden",
    "unit": 3,
    "lines": [
      "李白乘舟将欲行，",
      "忽闻岸上踏歌声。",
      "桃花潭水深千尺，",
      "不及汪伦送我情。"
    ],
    "requiresRecite": true
  },
  {
    "id": "hua-ji",
    "title": "画鸡",
    "author": "唐寅",
    "dynasty": "明",
    "source": "garden",
    "unit": 8,
    "lines": [
      "头上红冠不用裁，",
      "满身雪白走将来。",
      "平生不敢轻言语，",
      "一叫千门万户开。"
    ],
    "requiresRecite": true
  }
]
