-- AUTO-GENERATED — chinese_lessons (run after 00-delete.sql)
insert into public.chinese_lessons (
  lesson_key, grade, semester, unit, lesson, lesson_title, lesson_kind, unit_type, sort_order, recall_phrases
) values
  ('u1-garden', 1, '下', 1, 0, '语文园地一', 'garden', 'literacy', 0, array[]::text[]),
  ('u1-l1', 1, '下', 1, 1, '春夏秋冬', 'lesson', 'literacy', 1, array[]::text[]),
  ('u1-l2', 1, '下', 1, 2, '姓氏歌', 'lesson', 'literacy', 2, array[]::text[]),
  ('u1-l3', 1, '下', 1, 3, '小青蛙', 'lesson', 'literacy', 3, array[]::text[]),
  ('u1-l4', 1, '下', 1, 4, '猜字谜', 'lesson', 'literacy', 4, array[]::text[]),
  ('u2-garden', 1, '下', 2, 0, '语文园地二', 'garden', 'reading', 5, array[]::text[]),
  ('u2-l1', 1, '下', 2, 1, '热爱中国共产党', 'lesson', 'reading', 6, array[]::text[]),
  ('u2-l2', 1, '下', 2, 2, '吃水不忘挖井人', 'lesson', 'reading', 7, array[]::text[]),
  ('u2-l3', 1, '下', 2, 3, '我多想去看看', 'lesson', 'reading', 8, array['壮观的升旗仪式', '宽宽的公路', '弯弯的小路', '洁白的雪莲', '美丽的天山', '雄伟的天安门']::text[]),
  ('u3-garden', 1, '下', 3, 0, '语文园地三', 'garden', 'reading', 9, array[]::text[]),
  ('u3-l4', 1, '下', 3, 4, '小公鸡和小鸭子', 'lesson', 'reading', 10, array[]::text[]),
  ('u3-l5', 1, '下', 3, 5, '树和喜鹊', 'lesson', 'reading', 11, array['叽叽喳喳', '安安静静']::text[]),
  ('u3-l6', 1, '下', 3, 6, '怎么都快乐', 'lesson', 'reading', 12, array[]::text[]),
  ('u4-garden', 1, '下', 4, 0, '语文园地四', 'garden', 'reading', 13, array[]::text[]),
  ('u4-l7', 1, '下', 4, 7, '静夜思', 'lesson', 'reading', 14, array[]::text[]),
  ('u4-l8', 1, '下', 4, 8, '夜色', 'lesson', 'reading', 15, array[]::text[]),
  ('u4-l9', 1, '下', 4, 9, '端午粽', 'lesson', 'reading', 16, array[]::text[]),
  ('u5-garden', 1, '下', 5, 0, '语文园地五', 'garden', 'literacy', 17, array[]::text[]),
  ('u5-l5', 1, '下', 5, 5, '动物儿歌', 'lesson', 'literacy', 18, array['蚂蚁搬家', '蚯蚓松土', '蜘蛛结网', '蜻蜓展翅', '蝌蚪游泳', '蝴蝶飞舞']::text[]),
  ('u5-l6', 1, '下', 5, 6, '古对今', 'lesson', 'literacy', 19, array['和风细雨', '鸟语花香']::text[]),
  ('u5-l7', 1, '下', 5, 7, '操场上', 'lesson', 'literacy', 20, array[]::text[]),
  ('u5-l8', 1, '下', 5, 8, '人之初', 'lesson', 'literacy', 21, array[]::text[]),
  ('u6-garden', 1, '下', 6, 0, '语文园地六', 'garden', 'reading', 22, array[]::text[]),
  ('u6-l10', 1, '下', 6, 10, '古诗二首', 'lesson', 'reading', 23, array[]::text[]),
  ('u6-l11', 1, '下', 6, 11, '浪花', 'lesson', 'reading', 24, array[]::text[]),
  ('u6-l12', 1, '下', 6, 12, '荷叶圆圆', 'lesson', 'reading', 25, array[]::text[]),
  ('u6-l13', 1, '下', 6, 13, '要下雨了', 'lesson', 'reading', 26, array['阴沉沉']::text[]),
  ('u7-garden', 1, '下', 7, 0, '语文园地七', 'garden', 'reading', 27, array[]::text[]),
  ('u7-l14', 1, '下', 7, 14, '文具的家', 'lesson', 'reading', 28, array[]::text[]),
  ('u7-l15', 1, '下', 7, 15, '一分钟', 'lesson', 'reading', 29, array[]::text[]),
  ('u7-l16', 1, '下', 7, 16, '动物王国开大会', 'lesson', 'reading', 30, array[]::text[]),
  ('u7-l17', 1, '下', 7, 17, '小猴子下山', 'lesson', 'reading', 31, array[]::text[]),
  ('u8-garden', 1, '下', 8, 0, '语文园地八', 'garden', 'reading', 32, array[]::text[]),
  ('u8-l18', 1, '下', 8, 18, '棉花姑娘', 'lesson', 'reading', 33, array[]::text[]),
  ('u8-l19', 1, '下', 8, 19, '咕咚', 'lesson', 'reading', 34, array[]::text[]),
  ('u8-l20', 1, '下', 8, 20, '小壁虎借尾巴', 'lesson', 'reading', 35, array[]::text[]);
