// AUTO-GENERATED from docs/tmp/chinese/chinese-words.pdf answer section
// 看拼音写词语 — 一年级下册

export interface PinyinWriteWordEntry {
  lessonKey: string
  lessonTitle: string
  unit: number
  word: string
  pinyin: string
}

export const PINYIN_WRITE_WORDS: PinyinWriteWordEntry[] = [
  { lessonKey: "u1-l1", lessonTitle: "春夏秋冬", unit: 1, word: "春风", pinyin: "chūn fēng" },
  { lessonKey: "u1-l1", lessonTitle: "春夏秋冬", unit: 1, word: "春花", pinyin: "chūn huā" },
  { lessonKey: "u1-l1", lessonTitle: "春夏秋冬", unit: 1, word: "冬天", pinyin: "dōng tiān" },
  { lessonKey: "u1-l1", lessonTitle: "春夏秋冬", unit: 1, word: "吹牛", pinyin: "chuī niú" },
  { lessonKey: "u1-l1", lessonTitle: "春夏秋冬", unit: 1, word: "入冬", pinyin: "rù dōng" },
  { lessonKey: "u1-l1", lessonTitle: "春夏秋冬", unit: 1, word: "飞鸟", pinyin: "fēi niǎo" },
  { lessonKey: "u1-l2", lessonTitle: "姓氏歌", unit: 1, word: "什么", pinyin: "shén me" },
  { lessonKey: "u1-l2", lessonTitle: "姓氏歌", unit: 1, word: "双手", pinyin: "shuāng shǒu" },
  { lessonKey: "u1-l2", lessonTitle: "姓氏歌", unit: 1, word: "古人", pinyin: "gǔ rén" },
  { lessonKey: "u1-l2", lessonTitle: "姓氏歌", unit: 1, word: "二胡", pinyin: "èr hú" },
  { lessonKey: "u1-l2", lessonTitle: "姓氏歌", unit: 1, word: "语言", pinyin: "yǔ yán" },
  { lessonKey: "u1-l3", lessonTitle: "小青蛙", unit: 1, word: "青山", pinyin: "qīng shān" },
  { lessonKey: "u1-l3", lessonTitle: "小青蛙", unit: 1, word: "清水", pinyin: "qīng shuǐ" },
  { lessonKey: "u1-l3", lessonTitle: "小青蛙", unit: 1, word: "晴天", pinyin: "qíng tiān" },
  { lessonKey: "u1-l3", lessonTitle: "小青蛙", unit: 1, word: "请问", pinyin: "qǐng wèn" },
  { lessonKey: "u1-l3", lessonTitle: "小青蛙", unit: 1, word: "禾苗", pinyin: "hé miáo" },
  { lessonKey: "u1-l3", lessonTitle: "小青蛙", unit: 1, word: "生日", pinyin: "shēng rì" },
  { lessonKey: "u1-l4", lessonTitle: "猜字谜", unit: 1, word: "生字", pinyin: "shēng zì" },
  { lessonKey: "u1-l4", lessonTitle: "猜字谜", unit: 1, word: "火红", pinyin: "huǒ hóng" },
  { lessonKey: "u1-l4", lessonTitle: "猜字谜", unit: 1, word: "红花", pinyin: "hóng huā" },
  { lessonKey: "u1-l4", lessonTitle: "猜字谜", unit: 1, word: "万一", pinyin: "wàn yī" },
  { lessonKey: "u1-l4", lessonTitle: "猜字谜", unit: 1, word: "开动", pinyin: "kāi dòng" },
  { lessonKey: "u1-l4", lessonTitle: "猜字谜", unit: 1, word: "出动", pinyin: "chū dòng" },
  { lessonKey: "u1-l4", lessonTitle: "猜字谜", unit: 1, word: "红红火火", pinyin: "hóng hóng huǒ huǒ" },
  { lessonKey: "u1-l4", lessonTitle: "猜字谜", unit: 1, word: "有无", pinyin: "yǒu wú" },
  { lessonKey: "u1-l4", lessonTitle: "猜字谜", unit: 1, word: "清明", pinyin: "qīng míng" },
  { lessonKey: "u1-garden", lessonTitle: "语文园地一", unit: 1, word: "文字", pinyin: "wén zì" },
  { lessonKey: "u1-garden", lessonTitle: "语文园地一", unit: 1, word: "卡片", pinyin: "kǎ piàn" },
  { lessonKey: "u1-garden", lessonTitle: "语文园地一", unit: 1, word: "合力", pinyin: "hé lì" },
  { lessonKey: "u2-l1", lessonTitle: "热爱中国共产党", unit: 2, word: "共产党", pinyin: "gòng chǎn dǎng" },
  { lessonKey: "u2-l1", lessonTitle: "热爱中国共产党", unit: 2, word: "公共", pinyin: "gōng gòng" },
  { lessonKey: "u2-l1", lessonTitle: "热爱中国共产党", unit: 2, word: "目光", pinyin: "mù guāng" },
  { lessonKey: "u2-l1", lessonTitle: "热爱中国共产党", unit: 2, word: "太阳光", pinyin: "tài yáng guāng" },
  { lessonKey: "u2-l1", lessonTitle: "热爱中国共产党", unit: 2, word: "产生", pinyin: "chǎn shēng" },
  { lessonKey: "u2-l2", lessonTitle: "吃水不忘挖井人", unit: 2, word: "井口", pinyin: "jǐng kǒu" },
  { lessonKey: "u2-l2", lessonTitle: "吃水不忘挖井人", unit: 2, word: "江水", pinyin: "jiāng shuǐ" },
  { lessonKey: "u2-l2", lessonTitle: "吃水不忘挖井人", unit: 2, word: "方言", pinyin: "fāng yán" },
  { lessonKey: "u2-l2", lessonTitle: "吃水不忘挖井人", unit: 2, word: "主人", pinyin: "zhǔ rén" },
  { lessonKey: "u2-l2", lessonTitle: "吃水不忘挖井人", unit: 2, word: "住下", pinyin: "zhù xià" },
  { lessonKey: "u2-l2", lessonTitle: "吃水不忘挖井人", unit: 2, word: "后人", pinyin: "hòu rén" },
  { lessonKey: "u2-l2", lessonTitle: "吃水不忘挖井人", unit: 2, word: "水井", pinyin: "shuǐ jǐng" },
  { lessonKey: "u2-l2", lessonTitle: "吃水不忘挖井人", unit: 2, word: "主动", pinyin: "zhǔ dòng" },
  { lessonKey: "u2-l2", lessonTitle: "吃水不忘挖井人", unit: 2, word: "方正", pinyin: "fāng zhèng" },
  { lessonKey: "u2-l2", lessonTitle: "吃水不忘挖井人", unit: 2, word: "后方", pinyin: "hòu fāng" },
  { lessonKey: "u2-l3", lessonTitle: "我多想去看看", unit: 2, word: "不可告人", pinyin: "bù kě gào rén" },
  { lessonKey: "u2-l3", lessonTitle: "我多想去看看", unit: 2, word: "不会", pinyin: "bú huì" },
  { lessonKey: "u2-l3", lessonTitle: "我多想去看看", unit: 2, word: "是的", pinyin: "shì de" },
  { lessonKey: "u2-l3", lessonTitle: "我多想去看看", unit: 2, word: "好的", pinyin: "hǎo de" },
  { lessonKey: "u2-l3", lessonTitle: "我多想去看看", unit: 2, word: "东西南北", pinyin: "dōng xī nán běi" },
  { lessonKey: "u2-l3", lessonTitle: "我多想去看看", unit: 2, word: "广告", pinyin: "guǎng gào" },
  { lessonKey: "u2-l3", lessonTitle: "我多想去看看", unit: 2, word: "北京", pinyin: "běi jīng" },
  { lessonKey: "u2-garden", lessonTitle: "语文园地二", unit: 2, word: "：", pinyin: "：" },
  { lessonKey: "u2-garden", lessonTitle: "语文园地二", unit: 2, word: "认字", pinyin: "rèn zì" },
  { lessonKey: "u2-garden", lessonTitle: "语文园地二", unit: 2, word: "认可", pinyin: "rèn kě" },
  { lessonKey: "u2-garden", lessonTitle: "语文园地二", unit: 2, word: "书写", pinyin: "shū xiě" },
  { lessonKey: "u2-garden", lessonTitle: "语文园地二", unit: 2, word: "手写", pinyin: "shǒu xiě" },
  { lessonKey: "u3-l4", lessonTitle: "小公鸡和小鸭子", unit: 3, word: "走动", pinyin: "zǒu dòng" },
  { lessonKey: "u3-l4", lessonTitle: "小公鸡和小鸭子", unit: 3, word: "河水", pinyin: "hé shuǐ" },
  { lessonKey: "u3-l4", lessonTitle: "小公鸡和小鸭子", unit: 3, word: "说明", pinyin: "shuō míng" },
  { lessonKey: "u3-l4", lessonTitle: "小公鸡和小鸭子", unit: 3, word: "让开", pinyin: "ràng kāi" },
  { lessonKey: "u3-l4", lessonTitle: "小公鸡和小鸭子", unit: 3, word: "自我", pinyin: "zì wǒ" },
  { lessonKey: "u3-l4", lessonTitle: "小公鸡和小鸭子", unit: 3, word: "自己", pinyin: "zì jǐ" },
  { lessonKey: "u3-l5", lessonTitle: "树和喜鹊", unit: 3, word: "从来", pinyin: "cóng lái" },
  { lessonKey: "u3-l5", lessonTitle: "树和喜鹊", unit: 3, word: "你们", pinyin: "nǐ men" },
  { lessonKey: "u3-l5", lessonTitle: "树和喜鹊", unit: 3, word: "他人", pinyin: "tā rén" },
  { lessonKey: "u3-l5", lessonTitle: "树和喜鹊", unit: 3, word: "回来", pinyin: "huí lái" },
  { lessonKey: "u3-l5", lessonTitle: "树和喜鹊", unit: 3, word: "大叫", pinyin: "dà jiào" },
  { lessonKey: "u3-l5", lessonTitle: "树和喜鹊", unit: 3, word: "和好", pinyin: "hé hǎo" },
  { lessonKey: "u3-l6", lessonTitle: "怎么都快乐", unit: 3, word: "快乐", pinyin: "kuài lè" },
  { lessonKey: "u3-l6", lessonTitle: "怎么都快乐", unit: 3, word: "当时", pinyin: "dāng shí" },
  { lessonKey: "u3-l6", lessonTitle: "怎么都快乐", unit: 3, word: "书写", pinyin: "shū xiě" },
  { lessonKey: "u3-l6", lessonTitle: "怎么都快乐", unit: 3, word: "画本", pinyin: "huà běn" },
  { lessonKey: "u3-l6", lessonTitle: "怎么都快乐", unit: 3, word: "牛毛", pinyin: "niú máo" },
  { lessonKey: "u3-l6", lessonTitle: "怎么都快乐", unit: 3, word: "飞快", pinyin: "fēi kuài" },
  { lessonKey: "u3-garden", lessonTitle: "语文园地三", unit: 3, word: "：", pinyin: "：" },
  { lessonKey: "u3-garden", lessonTitle: "语文园地三", unit: 3, word: "中止", pinyin: "zhōng zhǐ" },
  { lessonKey: "u3-garden", lessonTitle: "语文园地三", unit: 3, word: "公斤", pinyin: "gōng jīn" },
  { lessonKey: "u3-garden", lessonTitle: "语文园地三", unit: 3, word: "寸土不让", pinyin: "cùn tǔ bù ràng" },
  { lessonKey: "u3-garden", lessonTitle: "语文园地三", unit: 3, word: "人丁", pinyin: "rén dīng" },
  { lessonKey: "u3-garden", lessonTitle: "语文园地三", unit: 3, word: "千万", pinyin: "qiān wàn" },
  { lessonKey: "u3-garden", lessonTitle: "语文园地三", unit: 3, word: "元日", pinyin: "yuán rì" },
  { lessonKey: "u4-l7", lessonTitle: "静夜思", unit: 4, word: "心思", pinyin: "xīn sī" },
  { lessonKey: "u4-l7", lessonTitle: "静夜思", unit: 4, word: "木床", pinyin: "mù chuáng" },
  { lessonKey: "u4-l7", lessonTitle: "静夜思", unit: 4, word: "床头", pinyin: "chuáng tóu" },
  { lessonKey: "u4-l7", lessonTitle: "静夜思", unit: 4, word: "前后", pinyin: "qián hòu" },
  { lessonKey: "u4-l7", lessonTitle: "静夜思", unit: 4, word: "大地", pinyin: "dà dì" },
  { lessonKey: "u4-l7", lessonTitle: "静夜思", unit: 4, word: "故乡", pinyin: "gù xiāng" },
  { lessonKey: "u4-l7", lessonTitle: "静夜思", unit: 4, word: "思乡", pinyin: "sī xiāng" },
  { lessonKey: "u4-l8", lessonTitle: "夜色", unit: 4, word: "红色", pinyin: "hóng sè" },
  { lessonKey: "u4-l8", lessonTitle: "夜色", unit: 4, word: "春色", pinyin: "chūn sè" },
  { lessonKey: "u4-l8", lessonTitle: "夜色", unit: 4, word: "把手", pinyin: "bǎ shǒu" },
  { lessonKey: "u4-l8", lessonTitle: "夜色", unit: 4, word: "请讲", pinyin: "qǐng jiǎng" },
  { lessonKey: "u4-l8", lessonTitle: "夜色", unit: 4, word: "样子", pinyin: "yàng zi" },
  { lessonKey: "u4-l8", lessonTitle: "夜色", unit: 4, word: "一样", pinyin: "yī yàng" },
  { lessonKey: "u4-l8", lessonTitle: "夜色", unit: 4, word: "好笑", pinyin: "hǎo xiào" },
  { lessonKey: "u4-l8", lessonTitle: "夜色", unit: 4, word: "再见", pinyin: "zài jiàn" },
  { lessonKey: "u4-l9", lessonTitle: "端午粽", unit: 4, word: "春节", pinyin: "chūn jié" },
  { lessonKey: "u4-l9", lessonTitle: "端午粽", unit: 4, word: "节日", pinyin: "jié rì" },
  { lessonKey: "u4-l9", lessonTitle: "端午粽", unit: 4, word: "大米", pinyin: "dà mǐ" },
  { lessonKey: "u4-l9", lessonTitle: "端午粽", unit: 4, word: "中间", pinyin: "zhōng jiān" },
  { lessonKey: "u4-l9", lessonTitle: "端午粽", unit: 4, word: "分开", pinyin: "fēn kāi" },
  { lessonKey: "u4-l9", lessonTitle: "端午粽", unit: 4, word: "十分", pinyin: "shí fēn" },
  { lessonKey: "u4-l9", lessonTitle: "端午粽", unit: 4, word: "好吃", pinyin: "hǎo chī" },
  { lessonKey: "u4-l9", lessonTitle: "端午粽", unit: 4, word: "吃力", pinyin: "chī lì" },
  { lessonKey: "u4-l9", lessonTitle: "端午粽", unit: 4, word: "牛肉", pinyin: "niú ròu" },
  { lessonKey: "u4-garden", lessonTitle: "语文园地四", unit: 4, word: "手册", pinyin: "shǒu cè" },
  { lessonKey: "u4-garden", lessonTitle: "语文园地四", unit: 4, word: "一册书", pinyin: "yī cè shū" },
  { lessonKey: "u4-garden", lessonTitle: "语文园地四", unit: 4, word: "一支笔", pinyin: "yī zhī bǐ" },
  { lessonKey: "u4-garden", lessonTitle: "语文园地四", unit: 4, word: "电动", pinyin: "diàn dòng" },
  { lessonKey: "u4-garden", lessonTitle: "语文园地四", unit: 4, word: "上衣", pinyin: "shàng yī" },
  { lessonKey: "u5-l5", lessonTitle: "动物儿歌", unit: 5, word: "人物", pinyin: "rén wù" },
  { lessonKey: "u5-l5", lessonTitle: "动物儿歌", unit: 5, word: "打造", pinyin: "dǎ zào" },
  { lessonKey: "u5-l5", lessonTitle: "动物儿歌", unit: 5, word: "运用", pinyin: "yùn yòng" },
  { lessonKey: "u5-l5", lessonTitle: "动物儿歌", unit: 5, word: "欢快", pinyin: "huān kuài" },
  { lessonKey: "u5-l5", lessonTitle: "动物儿歌", unit: 5, word: "房子", pinyin: "fáng zi" },
  { lessonKey: "u5-l5", lessonTitle: "动物儿歌", unit: 5, word: "上网", pinyin: "shàng wǎng" },
  { lessonKey: "u5-l6", lessonTitle: "古对今", unit: 5, word: "不对", pinyin: "bú duì" },
  { lessonKey: "u5-l6", lessonTitle: "古对今", unit: 5, word: "今日", pinyin: "jīn rì" },
  { lessonKey: "u5-l6", lessonTitle: "古对今", unit: 5, word: "下雪", pinyin: "xià xuě" },
  { lessonKey: "u5-l6", lessonTitle: "古对今", unit: 5, word: "细雨", pinyin: "xì yǔ" },
  { lessonKey: "u5-l6", lessonTitle: "古对今", unit: 5, word: "夕阳", pinyin: "xī yáng" },
  { lessonKey: "u5-l6", lessonTitle: "古对今", unit: 5, word: "语言", pinyin: "yǔ yán" },
  { lessonKey: "u5-l7", lessonTitle: "操场上", unit: 5, word: "打开", pinyin: "dǎ kāi" },
  { lessonKey: "u5-l7", lessonTitle: "操场上", unit: 5, word: "皮肉", pinyin: "pí ròu" },
  { lessonKey: "u5-l7", lessonTitle: "操场上", unit: 5, word: "快跑", pinyin: "kuài pǎo" },
  { lessonKey: "u5-l7", lessonTitle: "操场上", unit: 5, word: "手足", pinyin: "shǒu zú" },
  { lessonKey: "u5-l7", lessonTitle: "操场上", unit: 5, word: "沙包", pinyin: "shā bāo" },
  { lessonKey: "u5-l8", lessonTitle: "人之初", unit: 5, word: "远近", pinyin: "yuǎn jìn" },
  { lessonKey: "u5-l8", lessonTitle: "人之初", unit: 5, word: "学习", pinyin: "xué xí" },
  { lessonKey: "u5-l8", lessonTitle: "人之初", unit: 5, word: "正义", pinyin: "zhèng yì" },
  { lessonKey: "u5-l8", lessonTitle: "人之初", unit: 5, word: "玉石", pinyin: "yù shí" },
  { lessonKey: "u5-l8", lessonTitle: "人之初", unit: 5, word: "学生", pinyin: "xué shēng" },
  { lessonKey: "u5-garden", lessonTitle: "语文园地五", unit: 5, word: "：", pinyin: "：" },
  { lessonKey: "u5-garden", lessonTitle: "语文园地五", unit: 5, word: "吃饱", pinyin: "chī bǎo" },
  { lessonKey: "u5-garden", lessonTitle: "语文园地五", unit: 5, word: "拥抱", pinyin: "yōng bào" },
  { lessonKey: "u6-l10", lessonTitle: "古诗二首", unit: 6, word: "首先", pinyin: "shǒu xiān" },
  { lessonKey: "u6-l10", lessonTitle: "古诗二首", unit: 6, word: "水池", pinyin: "shuǐ chí" },
  { lessonKey: "u6-l10", lessonTitle: "古诗二首", unit: 6, word: "开采", pinyin: "kāi cǎi" },
  { lessonKey: "u6-l10", lessonTitle: "古诗二首", unit: 6, word: "刀尖", pinyin: "dāo jiān" },
  { lessonKey: "u6-l10", lessonTitle: "古诗二首", unit: 6, word: "牛角", pinyin: "niú jiǎo" },
  { lessonKey: "u6-l10", lessonTitle: "古诗二首", unit: 6, word: "早日", pinyin: "zǎo rì" },
  { lessonKey: "u6-l10", lessonTitle: "古诗二首", unit: 6, word: "文采", pinyin: "wén cǎi" },
  { lessonKey: "u6-l11", lessonTitle: "浪花", unit: 6, word: "玩笑", pinyin: "wán xiào" },
  { lessonKey: "u6-l11", lessonTitle: "浪花", unit: 6, word: "眼泪", pinyin: "yǎn lèi" },
  { lessonKey: "u6-l11", lessonTitle: "浪花", unit: 6, word: "它们", pinyin: "tā men" },
  { lessonKey: "u6-l11", lessonTitle: "浪花", unit: 6, word: "生气", pinyin: "shēng qì" },
  { lessonKey: "u6-l11", lessonTitle: "浪花", unit: 6, word: "分贝", pinyin: "fēn bèi" },
  { lessonKey: "u6-l11", lessonTitle: "浪花", unit: 6, word: "泪水", pinyin: "lèi shuǐ" },
  { lessonKey: "u6-l12", lessonTitle: "荷叶圆圆", unit: 6, word: "飞机", pinyin: "fēi jī" },
  { lessonKey: "u6-l12", lessonTitle: "荷叶圆圆", unit: 6, word: "天台", pinyin: "tiān tái" },
  { lessonKey: "u6-l12", lessonTitle: "荷叶圆圆", unit: 6, word: "合唱", pinyin: "hé chàng" },
  { lessonKey: "u6-l12", lessonTitle: "荷叶圆圆", unit: 6, word: "雨伞", pinyin: "yǔ sǎn" },
  { lessonKey: "u6-l12", lessonTitle: "荷叶圆圆", unit: 6, word: "花朵", pinyin: "huā duǒ" },
  { lessonKey: "u6-l12", lessonTitle: "荷叶圆圆", unit: 6, word: "美好", pinyin: "měi hǎo" },
  { lessonKey: "u6-l13", lessonTitle: "要下雨了", unit: 6, word: "这里", pinyin: "zhè lǐ" },
  { lessonKey: "u6-l13", lessonTitle: "要下雨了", unit: 6, word: "看见", pinyin: "kàn jiàn" },
  { lessonKey: "u6-l13", lessonTitle: "要下雨了", unit: 6, word: "这个", pinyin: "zhè ge" },
  { lessonKey: "u6-l13", lessonTitle: "要下雨了", unit: 6, word: "小鱼", pinyin: "xiǎo yú" },
  { lessonKey: "u6-l13", lessonTitle: "要下雨了", unit: 6, word: "方面", pinyin: "fāng miàn" },
  { lessonKey: "u6-l13", lessonTitle: "要下雨了", unit: 6, word: "问好", pinyin: "wèn hǎo" },
  { lessonKey: "u6-l13", lessonTitle: "要下雨了", unit: 6, word: "加入", pinyin: "jiā rù" },
  { lessonKey: "u6-garden", lessonTitle: "语文园地六", unit: 6, word: "：", pinyin: "：" },
  { lessonKey: "u6-garden", lessonTitle: "语文园地六", unit: 6, word: "土豆", pinyin: "tǔ dòu" },
  { lessonKey: "u6-garden", lessonTitle: "语文园地六", unit: 6, word: "斗篷", pinyin: "dǒu péng" },
  { lessonKey: "u6-garden", lessonTitle: "语文园地六", unit: 6, word: "红豆", pinyin: "hóng dòu" },
  { lessonKey: "u6-garden", lessonTitle: "语文园地六", unit: 6, word: "北斗", pinyin: "běi dǒu" },
  { lessonKey: "u7-l14", lessonTitle: "文具的家", unit: 7, word: "红笔", pinyin: "hóng bǐ" },
  { lessonKey: "u7-l14", lessonTitle: "文具的家", unit: 7, word: "知道", pinyin: "zhī dào" },
  { lessonKey: "u7-l14", lessonTitle: "文具的家", unit: 7, word: "放好", pinyin: "fàng hǎo" },
  { lessonKey: "u7-l14", lessonTitle: "文具的家", unit: 7, word: "平安", pinyin: "píng ān" },
  { lessonKey: "u7-l14", lessonTitle: "文具的家", unit: 7, word: "放下", pinyin: "fàng xià" },
  { lessonKey: "u7-l15", lessonTitle: "一分钟", unit: 7, word: "车灯", pinyin: "chē dēng" },
  { lessonKey: "u7-l15", lessonTitle: "一分钟", unit: 7, word: "站住", pinyin: "zhàn zhù" },
  { lessonKey: "u7-l15", lessonTitle: "一分钟", unit: 7, word: "上课", pinyin: "shàng kè" },
  { lessonKey: "u7-l15", lessonTitle: "一分钟", unit: 7, word: "坐下", pinyin: "zuò xià" },
  { lessonKey: "u7-l15", lessonTitle: "一分钟", unit: 7, word: "老师", pinyin: "lǎo shī" },
  { lessonKey: "u7-l16", lessonTitle: "动物王国开大会", unit: 7, word: "国王", pinyin: "guó wáng" },
  { lessonKey: "u7-l16", lessonTitle: "动物王国开大会", unit: 7, word: "百万", pinyin: "bǎi wàn" },
  { lessonKey: "u7-l16", lessonTitle: "动物王国开大会", unit: 7, word: "全都", pinyin: "quán dōu" },
  { lessonKey: "u7-l16", lessonTitle: "动物王国开大会", unit: 7, word: "听写", pinyin: "tīng xiě" },
  { lessonKey: "u7-l16", lessonTitle: "动物王国开大会", unit: 7, word: "平时", pinyin: "píng shí" },
  { lessonKey: "u7-l16", lessonTitle: "动物王国开大会", unit: 7, word: "时光", pinyin: "shí guāng" },
  { lessonKey: "u7-l16", lessonTitle: "动物王国开大会", unit: 7, word: "点头", pinyin: "diǎn tóu" },
  { lessonKey: "u7-l16", lessonTitle: "动物王国开大会", unit: 7, word: "竹林", pinyin: "zhú lín" },
  { lessonKey: "u7-l17", lessonTitle: "小猴子下山", unit: 7, word: "高兴", pinyin: "gāo xìng" },
  { lessonKey: "u7-l17", lessonTitle: "小猴子下山", unit: 7, word: "往后", pinyin: "wǎng hòu" },
  { lessonKey: "u7-l17", lessonTitle: "小猴子下山", unit: 7, word: "瓜子", pinyin: "guā zi" },
  { lessonKey: "u7-l17", lessonTitle: "小猴子下山", unit: 7, word: "放着", pinyin: "fàng zhe" },
  { lessonKey: "u7-l17", lessonTitle: "小猴子下山", unit: 7, word: "兔子", pinyin: "tù zi" },
  { lessonKey: "u7-l17", lessonTitle: "小猴子下山", unit: 7, word: "白兔", pinyin: "bái tù" },
  { lessonKey: "u7-l17", lessonTitle: "小猴子下山", unit: 7, word: "进出", pinyin: "jìn chū" },
  { lessonKey: "u7-l17", lessonTitle: "小猴子下山", unit: 7, word: "进入", pinyin: "jìn rù" },
  { lessonKey: "u7-l17", lessonTitle: "小猴子下山", unit: 7, word: "听着", pinyin: "tīng zhe" },
  { lessonKey: "u7-garden", lessonTitle: "语文园地七", unit: 7, word: "毛巾", pinyin: "máo jīn" },
  { lessonKey: "u7-garden", lessonTitle: "语文园地七", unit: 7, word: "洗衣", pinyin: "xǐ yī" },
  { lessonKey: "u7-garden", lessonTitle: "语文园地七", unit: 7, word: "清洗", pinyin: "qīng xǐ" },
  { lessonKey: "u8-l18", lessonTitle: "棉花姑娘", unit: 8, word: "她们", pinyin: "tā men" },
  { lessonKey: "u8-l18", lessonTitle: "棉花姑娘", unit: 8, word: "空气", pinyin: "kōng qì" },
  { lessonKey: "u8-l18", lessonTitle: "棉花姑娘", unit: 8, word: "还有", pinyin: "hái yǒu" },
  { lessonKey: "u8-l18", lessonTitle: "棉花姑娘", unit: 8, word: "才干", pinyin: "cái gàn" },
  { lessonKey: "u8-l18", lessonTitle: "棉花姑娘", unit: 8, word: "身高", pinyin: "shēn gāo" },
  { lessonKey: "u8-l18", lessonTitle: "棉花姑娘", unit: 8, word: "星空", pinyin: "xīng kōng" },
  { lessonKey: "u8-l18", lessonTitle: "棉花姑娘", unit: 8, word: "北斗星", pinyin: "běi dǒu xīng" },
  { lessonKey: "u8-l18", lessonTitle: "棉花姑娘", unit: 8, word: "不久", pinyin: "bù jiǔ" },
  { lessonKey: "u8-l19", lessonTitle: "咕咚", unit: 8, word: "可怕", pinyin: "kě pà" },
  { lessonKey: "u8-l19", lessonTitle: "咕咚", unit: 8, word: "吓人", pinyin: "xià rén" },
  { lessonKey: "u8-l19", lessonTitle: "咕咚", unit: 8, word: "为什么", pinyin: "wèi shén me" },
  { lessonKey: "u8-l19", lessonTitle: "咕咚", unit: 8, word: "家人", pinyin: "jiā rén" },
  { lessonKey: "u8-l19", lessonTitle: "咕咚", unit: 8, word: "大象", pinyin: "dà xiàng" },
  { lessonKey: "u8-l19", lessonTitle: "咕咚", unit: 8, word: "没有", pinyin: "méi yǒu" },
  { lessonKey: "u8-l19", lessonTitle: "咕咚", unit: 8, word: "到家", pinyin: "dào jiā" },
  { lessonKey: "u8-l19", lessonTitle: "咕咚", unit: 8, word: "气象", pinyin: "qì xiàng" },
  { lessonKey: "u8-l20", lessonTitle: "小壁虎借尾巴", unit: 8, word: "方向", pinyin: "fāng xiàng" },
  { lessonKey: "u8-l20", lessonTitle: "小壁虎借尾巴", unit: 8, word: "身边", pinyin: "shēn biān" },
  { lessonKey: "u8-l20", lessonTitle: "小壁虎借尾巴", unit: 8, word: "不行", pinyin: "bù xíng" },
  { lessonKey: "u8-l20", lessonTitle: "小壁虎借尾巴", unit: 8, word: "向前", pinyin: "xiàng qián" },
  { lessonKey: "u8-l20", lessonTitle: "小壁虎借尾巴", unit: 8, word: "行动", pinyin: "xíng dòng" },
  { lessonKey: "u8-l20", lessonTitle: "小壁虎借尾巴", unit: 8, word: "青草", pinyin: "qīng cǎo" },
  { lessonKey: "u8-l20", lessonTitle: "小壁虎借尾巴", unit: 8, word: "赶早", pinyin: "gǎn zǎo" },
  { lessonKey: "u8-l20", lessonTitle: "小壁虎借尾巴", unit: 8, word: "过冬", pinyin: "guò dōng" },
  { lessonKey: "u8-l20", lessonTitle: "小壁虎借尾巴", unit: 8, word: "找人", pinyin: "zhǎo rén" },
  { lessonKey: "u8-l20", lessonTitle: "小壁虎借尾巴", unit: 8, word: "找出", pinyin: "zhǎo chū" },
  { lessonKey: "u8-garden", lessonTitle: "语文园地八", unit: 8, word: "书页", pinyin: "shū yè" },
  { lessonKey: "u8-garden", lessonTitle: "语文园地八", unit: 8, word: "户口", pinyin: "hù kǒu" },
  { lessonKey: "u8-garden", lessonTitle: "语文园地八", unit: 8, word: "住户", pinyin: "zhù hù" },
  { lessonKey: "u8-garden", lessonTitle: "语文园地八", unit: 8, word: "交往", pinyin: "jiāo wǎng" },
  { lessonKey: "u8-garden", lessonTitle: "语文园地八", unit: 8, word: "公交", pinyin: "gōng jiāo" },
  { lessonKey: "u8-garden", lessonTitle: "语文园地八", unit: 8, word: "父子", pinyin: "fù zǐ" },
]
