// AUTO-GENERATED DRAFT from docs/tmp/语文一年级下册.pdf — review pinyin & lesson mapping before production use.
// Generated by docs/tmp/extract-chinese-g1b.py

import type { RadicalEntry } from './types'

export const RADICALS: RadicalEntry[] = [
  {
    "radical": "刂",
    "name": "立刀旁",
    "examples": [
      "刷",
      "别"
    ]
  },
  {
    "radical": "亠",
    "name": "京字头",
    "examples": [
      "京",
      "亮"
    ]
  },
  {
    "radical": "冫",
    "name": "两点水",
    "examples": [
      "凉",
      "减"
    ]
  },
  {
    "radical": "力",
    "name": "力字旁",
    "examples": [
      "动",
      "劲"
    ]
  },
  {
    "radical": "又",
    "name": "又字旁",
    "examples": [
      "欢",
      "难"
    ]
  },
  {
    "radical": "大",
    "name": "大字头",
    "examples": [
      "牵",
      "奇"
    ]
  },
  {
    "radical": "彳",
    "name": "双人旁",
    "examples": [
      "得",
      "很"
    ]
  },
  {
    "radical": "饣",
    "name": "食字旁",
    "examples": [
      "饭",
      "饱"
    ]
  },
  {
    "radical": "广",
    "name": "广字头",
    "examples": [
      "席",
      "座"
    ]
  },
  {
    "radical": "忄",
    "name": "竖心旁",
    "examples": [
      "情",
      "快"
    ]
  },
  {
    "radical": "尸",
    "name": "尸字头",
    "examples": [
      "居",
      "展"
    ]
  },
  {
    "radical": "弓",
    "name": "弓字旁",
    "examples": [
      "张"
    ]
  },
  {
    "radical": "子",
    "name": "子字旁",
    "examples": [
      "孙",
      "孤"
    ]
  },
  {
    "radical": "王",
    "name": "王字旁",
    "examples": [
      "玩",
      "现"
    ]
  },
  {
    "radical": "车",
    "name": "车字旁",
    "examples": [
      "轮",
      "转"
    ]
  },
  {
    "radical": "牛",
    "name": "牛字旁",
    "examples": [
      "物"
    ]
  },
  {
    "radical": "攵",
    "name": "反文旁",
    "examples": [
      "攻",
      "故"
    ]
  },
  {
    "radical": "⺮",
    "name": "爪字头",
    "examples": [
      "爱"
    ]
  },
  {
    "radical": "火",
    "name": "火字旁",
    "examples": [
      "炮",
      "灯"
    ]
  },
  {
    "radical": "户",
    "name": "户字头",
    "examples": [
      "房",
      "扇"
    ]
  },
  {
    "radical": "礻",
    "name": "示字旁",
    "examples": [
      "福",
      "视"
    ]
  },
  {
    "radical": "心",
    "name": "心字底",
    "examples": [
      "想",
      "思"
    ]
  },
  {
    "radical": "目",
    "name": "目字旁",
    "examples": [
      "眼",
      "睡"
    ]
  },
  {
    "radical": "皿",
    "name": "皿字底",
    "examples": [
      "盒",
      "盆"
    ]
  },
  {
    "radical": "钅",
    "name": "金字旁",
    "examples": [
      "铃",
      "铅"
    ]
  },
  {
    "radical": "疒",
    "name": "病字头",
    "examples": [
      "病"
    ]
  },
  {
    "radical": "衤",
    "name": "衣字旁",
    "examples": [
      "裤",
      "初"
    ]
  },
  {
    "radical": "页",
    "name": "页字旁",
    "examples": [
      "领",
      "顶"
    ]
  },
  {
    "radical": "虫",
    "name": "虫字旁",
    "examples": [
      "蚂",
      "蚊"
    ]
  },
  {
    "radical": "舌",
    "name": "舌字旁",
    "examples": [
      "乱",
      "甜"
    ]
  },
  {
    "radical": "米",
    "name": "米字旁",
    "examples": [
      "粽",
      "粮"
    ]
  },
  {
    "radical": "辶",
    "name": "走字底",
    "examples": [
      "赶"
    ]
  },
  {
    "radical": "足",
    "name": "足字旁",
    "examples": [
      "跟",
      "跑"
    ]
  },
  {
    "radical": "雨",
    "name": "雨字头",
    "examples": [
      "霜",
      "露"
    ]
  }
]
