// AUTO-GENERATED from 教材 PDF + docs/chinese/一下课课贴.pdf（写字表字段）
// Generated by docs/tmp/extract-chinese-g1-down.py

import type { StrokeRuleEntry } from './types'

export const STROKE_RULES: StrokeRuleEntry[] = [
  {
    "unit": 1,
    "rule": "先外后内再封口",
    "examples": [
      "四",
      "白"
    ]
  },
  {
    "unit": 4,
    "rule": "点在正上方或左上方，先写点",
    "examples": [
      "床",
      "间"
    ]
  },
  {
    "unit": 4,
    "rule": "点在右上方，后写点",
    "examples": [
      "书",
      "我"
    ]
  },
  {
    "unit": 7,
    "rule": "左上包围和右上包围的字先外后内",
    "examples": [
      "房",
      "着",
      "包"
    ]
  }
]
