import type { Problem, ProblemSet } from '@rosie/core'

export const LESSON_TIP =
  '等量代换与归一：先读题找已知条件和所求问题，分析数量关系，先求每份量（归一），再列式求解，最后把答案代回检验。'

export const TYPE_TIP: Record<string, string> = {
  type1: '归一问题——先求总量或每份量，再按题意乘或除；有增减时先算净变化量。',
  type2: '等量代换——找相等关系列式，如「剩下重量=原来几箱」→ 用字母表示每份量。',
  type3: '分组统计——按组合分类计数，先算特殊组，再用「相等」条件求全某类组数。',
  type4: '位置与顺序——画线段图或数轴，按左右关系确定顺序再求距离或数量。',
  type5: '逻辑与综合——分段计费、最值保证、逻辑推理，注意分类讨论与检验。',
}

const LESSON: Problem[] = [
  {
    id: '50-L1',
    title: '例1 · 水果采购',
    tag: 'type1',
    tagLabel: '归一问题',
    difficulty: 2,
    text: '某单位采购水果，共买了 <strong>100</strong> 千克苹果和梨，其中有 <strong>4</strong> 箱是苹果，每箱 <strong>9</strong> 千克；还有 <strong>8</strong> 箱是梨，那么每箱梨多少千克？',
    analysis: [
      '苹果共：4 × 9 = 36 千克',
      '梨共：100 − 36 = 64 千克',
      '每箱梨：64 ÷ 8 = <strong>8</strong> 千克',
    ],
    type: 'none',
    finalQ: '每箱梨多少千克？',
    finalUnit: '千克',
    finalAns: 8,
  },
  {
    id: '50-L2',
    title: '例2 · 买二送一',
    tag: 'type5',
    tagLabel: '优惠问题',
    difficulty: 2,
    text: '超市中某种汉堡每个 <strong>10</strong> 元，推出"买二送一"优惠（付 2 个的钱得 3 个）。纳纳和朋友需要 <strong>9</strong> 个汉堡，至少需要花多少元？',
    analysis: [
      '9 个 = 3 组"买二送一"，只需付 6 个的钱',
      '6 × 10 = <strong>60</strong> 元',
    ],
    type: 'none',
    finalQ: '至少需要花多少元？',
    finalUnit: '元',
    finalAns: 60,
  },
  {
    id: '50-L3',
    title: '例3 · 习题册天数',
    tag: 'type1',
    tagLabel: '归一问题',
    difficulty: 2,
    text: '纳纳每天做 <strong>4</strong> 道，需 <strong>50</strong> 天做完；约约每天比纳纳多做 <strong>1</strong> 道，可以比纳纳提前多少天做完？',
    analysis: [
      '习题册共：4 × 50 = 200 道',
      '约约每天 5 道，需 200 ÷ 5 = 40 天',
      '提前：50 − 40 = <strong>10</strong> 天',
    ],
    type: 'none',
    finalQ: '约约比纳纳提前多少天？',
    finalUnit: '天',
    finalAns: 10,
  },
  {
    id: '50-L4',
    title: '例4 · 鸡蛋够吃几天',
    tag: 'type1',
    tagLabel: '归一问题',
    difficulty: 2,
    text: '立立家买了 <strong>72</strong> 个鸡蛋，母鸡每天下 <strong>1</strong> 个蛋，每天吃 <strong>4</strong> 个，够连续吃多少天？',
    analysis: [
      '每天净消耗：4 − 1 = 3 个',
      '72 ÷ 3 = <strong>24</strong> 天',
    ],
    type: 'none',
    finalQ: '够吃多少天？',
    finalUnit: '天',
    finalAns: 24,
  },
  {
    id: '50-L5',
    title: '例5 · 分组数男生',
    tag: 'type3',
    tagLabel: '分组统计',
    difficulty: 4,
    text: '全校 <strong>400</strong> 名同学，每 <strong>4</strong> 人一组。只有 1 个男生的 20 组，只有 1 个女生的 10 组，只有 2 个女生的 24 组，全男生组数=全女生组数，共有多少名男生？',
    analysis: [
      '共 100 组；前三类组含男生 20+30+48=98 名',
      '剩余 46 组，全男、全女各 23 组，全男组 92 名',
      '男生共：98 + 92 = <strong>190</strong> 名',
    ],
    type: 'none',
    finalQ: '全校共有多少名男生？',
    finalUnit: '名',
    finalAns: 190,
  },
  {
    id: '50-L6',
    title: '练一练 · 糖果分组',
    tag: 'type3',
    tagLabel: '分组统计',
    difficulty: 4,
    text: '甲乙两种糖果共 <strong>300</strong> 块，每堆 <strong>3</strong> 块分 <strong>100</strong> 堆。只有 1 块甲的 17 堆，有 2 或 3 块乙的 36 堆，3 块甲的堆数=3 块乙的堆数，甲种糖果共多少块？',
    analysis: [
      '设 3 甲=3 乙堆数为 x，由 17+x=36 得 x=19',
      '另有 45 堆为 2 甲 1 乙',
      '甲共：17×1 + 19×3 + 45×2 = <strong>164</strong> 块',
    ],
    type: 'none',
    finalQ: '甲种糖果共有多少块？',
    finalUnit: '块',
    finalAns: 164,
  },
  {
    id: '50-L7',
    title: '例6 · 排队距离',
    tag: 'type4',
    tagLabel: '位置推理',
    difficulty: 3,
    text: '甲、乙、丙、丁、戊站成一排。丙在戊右边 <strong>4</strong> 米，丁在甲右边 <strong>5</strong> 米，丙在丁右边 <strong>6</strong> 米，戊在乙左边 <strong>5</strong> 米。最左与最右相距多少米？',
    analysis: [
      '甲 0 米，丁 5 米，戊 7 米，丙 11 米，乙 12 米',
      '最左甲、最右乙，相距 <strong>12</strong> 米',
    ],
    type: 'none',
    finalQ: '最左与最右相距多少米？',
    finalUnit: '米',
    finalAns: 12,
  },
  {
    id: '50-L8',
    title: '例7 · 扑克牌点数',
    tag: 'type5',
    tagLabel: '逻辑综合',
    difficulty: 3,
    text: '3 张不同扑克牌（1~13），第 1、2 张和为 <strong>25</strong>，第 2、3 张和为 <strong>13</strong>，第 3 张点数是多少？',
    analysis: [
      '25 = 13 + 12，第 2 张为 12',
      '第 3 张：13 − 12 = <strong>1</strong>',
    ],
    type: 'none',
    finalQ: '第 3 张点数是多少？',
    finalUnit: '',
    finalAns: 1,
  },
  {
    id: '50-L9',
    title: '例8 · 帽子与气球',
    tag: 'type5',
    tagLabel: '逻辑综合',
    difficulty: 4,
    text: '8 名小朋友戴红或蓝帽。看到另外 <strong>3</strong> 名及以上戴红帽则拿红气球，否则蓝气球。既有红气球也有蓝气球，戴红帽多少名？',
    analysis: [
      '3 名戴红帽：蓝帽者各见 3 红→红气球；红帽者各见 2 红→蓝气球',
      '既有红气球也有蓝气球，戴红帽 <strong>3</strong> 名',
    ],
    type: 'none',
    finalQ: '戴红帽子多少名？',
    finalUnit: '名',
    finalAns: 3,
  },
  {
    id: '50-L10',
    title: '例9 · 合作加工时间',
    tag: 'type5',
    tagLabel: '逻辑综合',
    difficulty: 3,
    text: '张、王共同加工 <strong>200</strong> 个零件，张每 <strong>4</strong> 分钟 1 个，王每 <strong>6</strong> 分钟 1 个，共需多少小时？',
    analysis: [
      '合作效率：1/4 + 1/6 = 5/12 个/分钟',
      '200 ÷ (5/12) = 480 分钟 = <strong>8</strong> 小时',
    ],
    type: 'none',
    finalQ: '共需多少小时？',
    finalUnit: '小时',
    finalAns: 8,
  },
]

const SUPPLEMENT: Problem[] = [
  {
    id: '50-S1',
    title: '附加1 · 电话计费',
    tag: 'type5',
    tagLabel: '附加题',
    difficulty: 5,
    text: '8:49 起打电话，前 3 分钟 6 角/分，之后 3 角/分，9 点后 1 角/分。共花 <strong>5</strong> 元，打了多少分钟？',
    analysis: [
      '8:49 到 9:00 共 11 分钟：3×0.6 + 8×0.3 = 4.2 元',
      '剩余 0.8 元，9 点后 8 分钟',
      '共 11 + 8 = <strong>19</strong> 分钟',
    ],
    type: 'none',
    finalQ: '共打多少分钟？',
    finalUnit: '分钟',
    finalAns: 19,
  },
  {
    id: '50-S2',
    title: '附加2 · 文具分配',
    tag: 'type2',
    tagLabel: '附加题',
    difficulty: 3,
    text: '铅笔、圆珠笔、钢笔各买同样数量。每人发 1 铅笔、2 圆珠笔、3 钢笔，圆珠笔剩 <strong>42</strong> 支，铅笔和钢笔共剩多少支？',
    analysis: [
      '设原各 n 支，发 k 人：圆珠笔剩 n−2k=42',
      '铅笔剩 n−k，钢笔剩 n−3k，合计 2(n−2k)=2×42=<strong>84</strong> 支',
    ],
    type: 'none',
    finalQ: '铅笔和钢笔共剩多少支？',
    finalUnit: '支',
    finalAns: 84,
  },
  {
    id: '50-S3',
    title: '附加3 · 选举班长',
    tag: 'type5',
    tagLabel: '附加题',
    difficulty: 4,
    text: '52 人投票，甲 <strong>17</strong>、乙 <strong>16</strong>、丙 <strong>11</strong> 票，剩 8 票未计。甲最少再得多少票保证当选？',
    analysis: [
      '甲再得 4 票→21 票',
      '即使其余 4 票全给乙，乙仅 20 票，甲保证当选',
      '最少再得 <strong>4</strong> 票',
    ],
    type: 'none',
    finalQ: '甲最少再得多少票？',
    finalUnit: '票',
    finalAns: 4,
  },
  {
    id: '50-S4',
    title: '附加4 · 动物平衡',
    tag: 'type5',
    tagLabel: '附加题',
    difficulty: 5,
    text: '鼠、猫、狗三种动物：猫≤狗则狗欺猫，鼠≤猫则猫欺鼠，猫+狗≤鼠则鼠偷吃。现相安无事，再进任意 1 只即失衡，原来共多少只？',
    analysis: [
      '需 m>c>d 且 c+d>m（严格大于才相安）',
      '5 鼠 3 猫 1 狗满足条件，共 <strong>9</strong> 只',
    ],
    type: 'none',
    finalQ: '原来共多少只？',
    finalUnit: '只',
    finalAns: 9,
  },
  {
    id: '50-S5',
    title: '附加5 · 击掌次数',
    tag: 'type5',
    tagLabel: '附加题',
    difficulty: 4,
    text: '<strong>50</strong> 名同学围圈报数 1~100，含数字 7 或是 7 的倍数时击掌 1 次，共击掌多少次？',
    analysis: [
      '7 的倍数：14 个',
      '含 7 但不是 7 的倍数：16 个',
      '共 <strong>30</strong> 次（每数至多击掌 1 次）',
    ],
    type: 'none',
    finalQ: '共击掌多少次？',
    finalUnit: '次',
    finalAns: 30,
  },
]

const HOMEWORK: Problem[] = [
  {
    id: '50-H1',
    title: '练习1 · 水果单价',
    tag: 'type1',
    tagLabel: '归一问题',
    difficulty: 2,
    text: '立立带 <strong>200</strong> 元买水果，苹果花 <strong>100</strong> 元，其余买橘子。共 <strong>30</strong> 千克，橘子 <strong>10</strong> 元/千克，苹果单价多少？',
    analysis: [
      '橘子 100 元 → 10 千克；苹果 20 千克',
      '苹果单价：100 ÷ 20 = <strong>5</strong> 元/千克',
    ],
    type: 'none',
    finalQ: '苹果单价多少元/千克？',
    finalUnit: '元/千克',
    finalAns: 5,
  },
  {
    id: '50-H2',
    title: '练习2 · 苹果箱重',
    tag: 'type2',
    tagLabel: '等量代换',
    difficulty: 3,
    text: '学校买 <strong>6</strong> 箱苹果，每箱取出 <strong>3</strong> 千克后，剩下总重=原来 <strong>4</strong> 箱总重，原来每箱重多少千克？',
    analysis: [
      '设每箱 x 千克：6(x−3) = 4x',
      '2x = 18，x = <strong>9</strong> 千克',
    ],
    type: 'none',
    finalQ: '原来每箱重多少千克？',
    finalUnit: '千克',
    finalAns: 9,
  },
  {
    id: '50-H3',
    title: '练习3 · 饼干天数',
    tag: 'type1',
    tagLabel: '归一问题',
    difficulty: 2,
    text: '思思的饼干每天吃 <strong>3</strong> 块可吃 <strong>20</strong> 天，若每天多吃 <strong>2</strong> 块，可吃多少天？',
    analysis: [
      '共 3 × 20 = 60 块',
      '每天 5 块，60 ÷ 5 = <strong>12</strong> 天',
    ],
    type: 'none',
    finalQ: '可吃多少天？',
    finalUnit: '天',
    finalAns: 12,
  },
  {
    id: '50-H4',
    title: '练习4 · 租车问题',
    tag: 'type1',
    tagLabel: '归一问题',
    difficulty: 2,
    text: '大车每辆 <strong>8</strong> 人，小车每辆 <strong>4</strong> 人，共 <strong>200</strong> 人，已租 <strong>19</strong> 辆大车，还需多少辆小车？',
    analysis: [
      '大车坐 19 × 8 = 152 人',
      '剩 48 人，需 48 ÷ 4 = <strong>12</strong> 辆小车',
    ],
    type: 'none',
    finalQ: '还需多少辆小车？',
    finalUnit: '辆',
    finalAns: 12,
  },
  {
    id: '50-H5',
    title: '练习5 · 正方形站位',
    tag: 'type4',
    tagLabel: '位置推理',
    difficulty: 4,
    text: '4 人站正方形顶点，每边中点再站 4 人，均面向中心。甲对面乙，甲左丁右丙，丙丁相距 <strong>10</strong> 米，甲乙相距多少米？',
    analysis: [
      '丙丁为同一边两端，边长 10 米',
      '甲、乙分别为对边中点，相距等于边长 <strong>10</strong> 米',
    ],
    type: 'none',
    finalQ: '甲和乙相距多少米？',
    finalUnit: '米',
    finalAns: 10,
  },
  {
    id: '50-H6',
    title: '练习6 · 鸡蛋与母鸡',
    tag: 'type1',
    tagLabel: '归一问题',
    difficulty: 2,
    text: '奶奶买 <strong>24</strong> 个鸡蛋，<strong>2</strong> 只母鸡每天各下 1 个，每天吃 <strong>5</strong> 个，够吃多少天？',
    analysis: [
      '每天净消耗：5 − 2 = 3 个',
      '24 ÷ 3 = <strong>8</strong> 天',
    ],
    type: 'none',
    finalQ: '够吃多少天？',
    finalUnit: '天',
    finalAns: 8,
  },
  {
    id: '50-H7',
    title: '练习7 · 三种糖果',
    tag: 'type2',
    tagLabel: '等量代换',
    difficulty: 3,
    text: '甲、乙、丙三种糖果各买同样块数。乙比甲贵 <strong>5</strong> 元，丙比乙贵 <strong>5</strong> 元，乙种花了 <strong>10</strong> 元，甲和丙共买了多少块？',
    analysis: [
      '各买 1 块时，乙花 10 元',
      '甲和丙共 <strong>2</strong> 块',
    ],
    type: 'none',
    finalQ: '甲和丙共多少块？',
    finalUnit: '块',
    finalAns: 2,
  },
  {
    id: '50-H8',
    title: '练习8 · 读书计划',
    tag: 'type1',
    tagLabel: '归一问题',
    difficulty: 3,
    text: '思思每 <strong>5</strong> 天读完 1 本，妈妈每 <strong>10</strong> 天买 1 本，现有 <strong>20</strong> 本，多少天能读完？',
    analysis: [
      '每 10 天净读 1 本（读 2 本，买 1 本）',
      '从 20 本到剩 1 本需 19×10 = 190 天',
      '最后一本再读 5 天，共 190 + 5 = <strong>195</strong> 天',
    ],
    type: 'none',
    finalQ: '多少天读完？',
    finalUnit: '天',
    finalAns: 195,
  },
  {
    id: '50-H9',
    title: '练习9 · 合作加工',
    tag: 'type5',
    tagLabel: '逻辑综合',
    difficulty: 3,
    text: '甲比乙每小时多 <strong>2</strong> 个，乙每小时 <strong>3</strong> 个，甲单独需 <strong>160</strong> 小时，甲乙合作需多久？',
    analysis: [
      '甲每小时 5 个，总量 5 × 160 = 800 个',
      '合作 8 个/小时，800 ÷ 8 = <strong>100</strong> 小时',
    ],
    type: 'none',
    finalQ: '合作需多少小时？',
    finalUnit: '小时',
    finalAns: 100,
  },
  {
    id: '50-H10',
    title: '练习10 · 球堆顺序',
    tag: 'type4',
    tagLabel: '位置推理',
    difficulty: 4,
    text: '红、黄、蓝、绿 4 堆共 <strong>50</strong> 球。红堆左边 20 个，黄堆左边 35 个，绿堆左边 30 个，红球多少个？',
    analysis: [
      '顺序：蓝 20、红 10、绿 5、黄 15',
      '红球 <strong>10</strong> 个',
    ],
    type: 'none',
    finalQ: '红球多少个？',
    finalUnit: '个',
    finalAns: 10,
  },
  {
    id: '50-H11',
    title: '练习11 · 彩旗分组',
    tag: 'type3',
    tagLabel: '分组统计',
    difficulty: 4,
    text: '红、黄旗共 <strong>200</strong> 面，每 <strong>5</strong> 面一组。仅 1 红旗 10 组，仅 1 黄旗 5 组，仅 2 红旗 5 组，仅 2 黄旗 10 组，全红旗组=全黄旗组，红旗多少面？',
    analysis: [
      '共 40 组；已知组红旗 10+20+10+30 = 70 面',
      '已知组黄旗 80 面；剩余 50 面由全红全黄各 5 组平分',
      '全红 5 组 25 面，红旗共 70 + 25 = <strong>95</strong> 面',
    ],
    type: 'none',
    finalQ: '红旗多少面？',
    finalUnit: '面',
    finalAns: 95,
  },
  {
    id: '50-H12',
    title: '练习12 · 扎花分组',
    tag: 'type3',
    tagLabel: '分组统计',
    difficulty: 4,
    text: '红、黄花共 <strong>300</strong> 朵，每 <strong>3</strong> 朵一束。仅 1 红花 24 束，2 或 3 黄花 50 束，3 红花束数=3 黄花束数，红花多少朵？',
    analysis: [
      '3 红=3 黄束数 x=26，另有 24 束 2 红 1 黄',
      '红花：24×1 + 26×3 + 24×2 = <strong>150</strong> 朵',
    ],
    type: 'none',
    finalQ: '红花多少朵？',
    finalUnit: '朵',
    finalAns: 150,
  },
]

export const PROBLEMS: ProblemSet = {
  pretest: [],
  lesson: LESSON,
  homework: HOMEWORK,
  workbook: [],
  supplement: SUPPLEMENT,
}

export const PROBLEM_TYPES = [
  { tag: 'type1', color: 'blue', label: '题型1 · 归一问题', desc: '先求总量或每份量，再按题意计算。', example: '例：4×50 道→5 道/天→提前几天' },
  { tag: 'type2', color: 'green', label: '题型2 · 等量代换', desc: '找相等关系列式，用字母表示未知量。', example: '例：6(x−3)=4x 求每箱重量' },
  { tag: 'type3', color: 'orange', label: '题型3 · 分组统计', desc: '按组合分类，利用「相等」条件求全某类组数。', example: '例：100 堆糖果求甲种块数' },
  { tag: 'type4', color: 'purple', label: '题型4 · 位置推理', desc: '画线段图确定顺序，再求距离或数量。', example: '例：五人排队求最远距离' },
  { tag: 'type5', color: 'red', label: '题型5 · 逻辑综合', desc: '优惠、工程、分段计费、最值与逻辑推理。', example: '例：买二送一、击掌计数' },
]

export const TYPE_STYLE: Record<string, { bg: string; border: string; titleColor: string; textColor: string }> = {
  type1: { bg: 'bg-blue-50', border: 'border-blue-400', titleColor: 'text-blue-700', textColor: 'text-blue-800' },
  type2: { bg: 'bg-green-50', border: 'border-green-400', titleColor: 'text-green-700', textColor: 'text-green-800' },
  type3: { bg: 'bg-orange-50', border: 'border-orange-400', titleColor: 'text-orange-700', textColor: 'text-orange-800' },
  type4: { bg: 'bg-purple-50', border: 'border-purple-400', titleColor: 'text-purple-700', textColor: 'text-purple-800' },
  type5: { bg: 'bg-red-50', border: 'border-red-400', titleColor: 'text-red-700', textColor: 'text-red-800' },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-blue-100 text-blue-700',
  type2: 'bg-green-100 text-green-700',
  type3: 'bg-orange-100 text-orange-700',
  type4: 'bg-purple-100 text-purple-700',
  type5: 'bg-red-100 text-red-700',
}
