import type { Problem, ProblemSet } from '@rosie/core'

const LESSON: Problem[] = [
  {
    id: '29-L1',
    title: '例1-1 · 填四则运算符',
    tag: 'type1',
    tagLabel: '题型1·填四则运算符', difficulty: 2,
    text: '将"+"、"−"、"×"、"÷"四个运算符号分别填入下面各题的圆圈中，每种符号各用一次，使等式成立。<br/><br/><strong>10 ○ 2 ○ 4 = 7 ○ 3 ○ 1</strong>',
    analysis: [
      '目标：找到一种排列使两侧相等',
      '尝试：10 × 2 ÷ 4 = 5；7 − 3 + 1 = 5 ✓',
      '验证：10 × 2 ÷ 4 = 20 ÷ 4 = 5，7 − 3 + 1 = 5',
      '运算符 ×÷−+ 各用一次 ✓',
      '等式两侧的共同值为 <strong>5</strong>',
    ],
    type: 'none',
    finalQ: '等式成立时两侧的共同值是多少？',
    finalUnit: '',
    finalAns: 5,
  },
  {
    id: '29-L2',
    title: '例1-2 · 填四则运算符',
    tag: 'type1',
    tagLabel: '题型1·填四则运算符', difficulty: 2,
    text: '将"+"、"−"、"×"、"÷"四个运算符号分别填入下面各题的圆圈中，每种符号各用一次，使等式成立。<br/><br/><strong>20 ○ 10 ○ 1 = 12 ○ 3 ○ 6</strong>',
    analysis: [
      '目标：找到一种排列使两侧相等',
      '尝试：20 + 10 ÷ 1 = 30；12 × 3 − 6 = 30 ✓',
      '验证：20 + 10 ÷ 1 = 20 + 10 = 30，12 × 3 − 6 = 36 − 6 = 30',
      '运算符 +÷×− 各用一次 ✓',
      '等式两侧的共同值为 <strong>30</strong>',
    ],
    type: 'none',
    finalQ: '等式成立时两侧的共同值是多少？',
    finalUnit: '',
    finalAns: 30,
  },
  {
    id: '29-L3',
    title: '例1-3 · 填四则运算符',
    tag: 'type1',
    tagLabel: '题型1·填四则运算符', difficulty: 2,
    text: '将"+"、"−"、"×"、"÷"四个运算符号分别填入下面各题的圆圈中，每种符号各用一次，使等式成立。<br/><br/><strong>7 ○ 2 ○ 4 = 10 ○ 2 ○ 5</strong>',
    analysis: [
      '目标：找到一种排列使两侧相等',
      '尝试：7 × 2 − 4 = 10；10 ÷ 2 + 5 = 10 ✓',
      '验证：7 × 2 − 4 = 14 − 4 = 10，10 ÷ 2 + 5 = 5 + 5 = 10',
      '运算符 ×−÷+ 各用一次 ✓',
      '等式两侧的共同值为 <strong>10</strong>',
    ],
    type: 'none',
    finalQ: '等式成立时两侧的共同值是多少？',
    finalUnit: '',
    finalAns: 10,
  },
  {
    id: '29-L4',
    title: '例1-4 · 填四则运算符',
    tag: 'type1',
    tagLabel: '题型1·填四则运算符', difficulty: 2,
    text: '将"+"、"−"、"×"、"÷"四个运算符号分别填入下面各题的圆圈中，每种符号各用一次，使等式成立。<br/><br/><strong>3 ○ 7 ○ 5 = 2 ○ 10 ○ 4</strong>',
    analysis: [
      '目标：找到一种排列使两侧相等',
      '尝试：3 + 7 − 5 = 5；2 × 10 ÷ 4 = 5 ✓',
      '验证：3 + 7 − 5 = 5，2 × 10 ÷ 4 = 20 ÷ 4 = 5',
      '运算符 +−×÷ 各用一次 ✓',
      '等式两侧的共同值为 <strong>5</strong>',
    ],
    type: 'none',
    finalQ: '等式成立时两侧的共同值是多少？',
    finalUnit: '',
    finalAns: 5,
  },
  {
    id: '29-L5',
    title: '练一练1 · 填四则运算符',
    tag: 'type1',
    tagLabel: '题型1·填四则运算符', difficulty: 2,
    text: '将"+"、"−"、"×"、"÷"四个运算符号分别填入下面的圆圈中，不能重复使用，使等式成立。<br/><br/><strong>7 ○ 2 ○ 4 = 10 ○ 2 ○ 5</strong>',
    analysis: [
      '方法：逐一尝试不同运算符排列',
      '可行方案：7 × 2 − 4 = 10，10 ÷ 2 + 5 = 10 ✓',
      '验证：7 × 2 − 4 = 10，10 ÷ 2 + 5 = 10',
      '等式两侧的共同值为 <strong>10</strong>',
    ],
    type: 'none',
    finalQ: '等式成立时两侧的共同值是多少？',
    finalUnit: '',
    finalAns: 10,
  },
  {
    id: '29-L6',
    title: '练一练2 · 填四则运算符',
    tag: 'type1',
    tagLabel: '题型1·填四则运算符', difficulty: 2,
    text: '将"+"、"−"、"×"、"÷"四个运算符号分别填入下面的圆圈中，不能重复使用，使等式成立。<br/><br/><strong>3 ○ 7 ○ 5 = 2 ○ 10 ○ 4</strong>',
    analysis: [
      '方法：逐一尝试不同运算符排列',
      '可行方案：3 + 7 − 5 = 5，2 × 10 ÷ 4 = 5 ✓',
      '验证：3 + 7 − 5 = 5，2 × 10 ÷ 4 = 5',
      '等式两侧的共同值为 <strong>5</strong>',
    ],
    type: 'none',
    finalQ: '等式成立时两侧的共同值是多少？',
    finalUnit: '',
    finalAns: 5,
  },
  {
    id: '29-L7',
    title: '例2-1 · 24点游戏',
    tag: 'type2',
    tagLabel: '题型2·24点游戏', difficulty: 3,
    text: '用"+"、"−"、"×"、"÷"运算符号以及括号凑出24，每个数必须用一次且只能用一次，数的顺序可以改变。<br/><br/><strong>数字：3，4，4，8</strong>',
    analysis: [
      '目标：用 3,4,4,8 凑出 24',
      '分析：8 × 3 = 24，尝试用 4,4 凑出 3',
      '思路：4 − 4 ÷ 4 = 3？不行，只有两个4',
      '换思路：8 × (4 − (4 ÷ 4 × ?))... 重新想',
      '可行方案：(3 × 4 − 4) × ? ... 8 = 8，8 = 24/3，不行',
      '最终方案：8 × (4 − (4 − 3)) = 8 × (4 − 1) = 8 × 3 = <strong>24</strong> ✓',
      '即 8 × (4 − (4 − 3)) = 24',
    ],
    type: 'none',
    finalQ: '凑出的目标值是多少？',
    finalUnit: '',
    finalAns: 24,
  },
  {
    id: '29-L8',
    title: '例2-2 · 24点游戏',
    tag: 'type2',
    tagLabel: '题型2·24点游戏', difficulty: 2,
    text: '用"+"、"−"、"×"、"÷"运算符号以及括号凑出24，每个数必须用一次且只能用一次，数的顺序可以改变。<br/><br/><strong>数字：1，1，2，6</strong>',
    analysis: [
      '目标：用 1,1,2,6 凑出 24',
      '思路：24 = 4 × 6，能用 1,1,2 凑出 4 吗？',
      '1 + 1 + 2 = 4 ✓',
      '方案：(1 + 1 + 2) × 6 = 4 × 6 = <strong>24</strong> ✓',
    ],
    type: 'none',
    finalQ: '凑出的目标值是多少？',
    finalUnit: '',
    finalAns: 24,
  },
  {
    id: '29-L9',
    title: '例2-3 · 24点游戏',
    tag: 'type2',
    tagLabel: '题型2·24点游戏', difficulty: 3,
    text: '用"+"、"−"、"×"、"÷"运算符号以及括号凑出24，每个数必须用一次且只能用一次，数的顺序可以改变。<br/><br/><strong>数字：2，2，6，9</strong>',
    analysis: [
      '目标：用 2,2,6,9 凑出 24',
      '思路：24 = 2 × 12，尝试用 2,6,9 凑出 12',
      '2 × 9 − 6 = 12 ✓',
      '方案：2 × (2 × 9 − 6) = 2 × 12 = <strong>24</strong> ✓',
    ],
    type: 'none',
    finalQ: '凑出的目标值是多少？',
    finalUnit: '',
    finalAns: 24,
  },
  {
    id: '29-L10',
    title: '例2-4 · 24点游戏',
    tag: 'type2',
    tagLabel: '题型2·24点游戏', difficulty: 3,
    text: '用"+"、"−"、"×"、"÷"运算符号以及括号凑出24，每个数必须用一次且只能用一次，数的顺序可以改变。<br/><br/><strong>数字：2，4，5，9</strong>',
    analysis: [
      '目标：用 2,4,5,9 凑出 24',
      '思路：24 = 4 × 6，能用 2,5,9 凑出 6 吗？',
      '9 − 5 + 2 = 6 ✓',
      '方案：(9 − 5 + 2) × 4 = 6 × 4 = <strong>24</strong> ✓',
      '或：(9 − 5) × (4 + 2) = 4 × 6 = 24 ✓',
    ],
    type: 'none',
    finalQ: '凑出的目标值是多少？',
    finalUnit: '',
    finalAns: 24,
  },
  {
    id: '29-L11',
    title: '练一练（24点）1 · 2,8,9,10',
    tag: 'type2',
    tagLabel: '题型2·24点游戏', difficulty: 3,
    text: '用"+"、"−"、"×"、"÷"运算符号以及括号凑出24，每个数必须用一次且只能用一次，数的顺序可以改变。<br/><br/><strong>数字：2，8，9，10</strong>',
    analysis: [
      '目标：用 2,8,9,10 凑出 24',
      '思路：24 = 8 × 3，能用 2,9,10 凑出 3 吗？',
      '10 − 9 + 2 = 3 ✓',
      '方案：8 × (10 − 9 + 2) = 8 × 3 = <strong>24</strong> ✓',
    ],
    type: 'none',
    finalQ: '凑出的目标值是多少？',
    finalUnit: '',
    finalAns: 24,
  },
  {
    id: '29-L12',
    title: '练一练（24点）4 · 3,4,7,8',
    tag: 'type2',
    tagLabel: '题型2·24点游戏', difficulty: 3,
    text: '用"+"、"−"、"×"、"÷"运算符号以及括号凑出24，每个数必须用一次且只能用一次，数的顺序可以改变。<br/><br/><strong>数字：3，4，7，8</strong>',
    analysis: [
      '目标：用 3,4,7,8 凑出 24',
      '思路：24 = 6 × 4 = (3 + 7 − 4) × 4',
      '验证：(3 + 7 − 4) × 4 = 6 × 4 = <strong>24</strong> ✓',
      '另解：(8 − 4) × (7 − 3) = 4 × 4 = 16 ✗ 继续探索',
      '可行方案：(3 + 7 − 4) × 4 = 24 ✓（或 8 × 3 × 4 ÷ ? 等）',
    ],
    type: 'none',
    finalQ: '凑出的目标值是多少？',
    finalUnit: '',
    finalAns: 24,
  },
]

const HOMEWORK: Problem[] = [
  {
    id: '29-H1',
    title: '巩固1-1 · 填四则运算符',
    tag: 'type1',
    tagLabel: '题型1·填四则运算符', difficulty: 2,
    text: '将"+"、"−"、"×"、"÷"四个运算符号分别填入下面的圆圈中，不能重复使用，使等式成立。<br/><br/><strong>12 ○ 4 ○ 9 = 2 ○ 8 ○ 4</strong>',
    analysis: [
      '目标：找到使两侧相等的运算符排列',
      '尝试左侧：12 ÷ 4 + 9 = 3 + 9 = 12',
      '尝试右侧：2 × 8 − 4 = 16 − 4 = 12 ✓',
      '验证：12 ÷ 4 + 9 = 12，2 × 8 − 4 = 12',
      '运算符 ÷+×− 各用一次 ✓',
      '等式两侧的共同值为 <strong>12</strong>',
    ],
    type: 'none',
    finalQ: '等式成立时两侧的共同值是多少？',
    finalUnit: '',
    finalAns: 12,
  },
  {
    id: '29-H2',
    title: '巩固1-2 · 填四则运算符',
    tag: 'type1',
    tagLabel: '题型1·填四则运算符', difficulty: 2,
    text: '将"+"、"−"、"×"、"÷"四个运算符号分别填入下面的圆圈中，不能重复使用，使等式成立。<br/><br/><strong>6 ○ 6 ○ 4 = 7 ○ 5 ○ 3</strong>',
    analysis: [
      '目标：找到使两侧相等的运算符排列',
      '尝试左侧：6 × 6 ÷ 4 = 36 ÷ 4 = 9',
      '尝试右侧：7 + 5 − 3 = 9 ✓',
      '验证：6 × 6 ÷ 4 = 9，7 + 5 − 3 = 9',
      '运算符 ×÷+− 各用一次 ✓',
      '等式两侧的共同值为 <strong>9</strong>',
    ],
    type: 'none',
    finalQ: '等式成立时两侧的共同值是多少？',
    finalUnit: '',
    finalAns: 9,
  },
  {
    id: '29-H3',
    title: '巩固2-1 · 24点游戏',
    tag: 'type2',
    tagLabel: '题型2·24点游戏', difficulty: 3,
    text: '用"+"、"−"、"×"、"÷"运算符号以及括号凑出24，每个数必须用一次且只能用一次，数的顺序可以改变。<br/><br/><strong>数字：5，5，6，8</strong>',
    analysis: [
      '目标：用 5,5,6,8 凑出 24',
      '思路：24 = 8 × 3，能用 5,5,6 凑出 3 吗？',
      '6 ÷ (5 − 5 + ?) 有问题；换思路',
      '24 = 4 × 6，能用 5,5,8 凑出 4 吗？',
      '5 − 5 + 8 = 8 ✗；8 ÷ (5 − 5) = 除以0 ✗',
      '尝试：(8 − 6) × 5 + 5 = 10 + 5 = 15 ✗',
      '可行方案：(5 × 5 − 6) ÷ ? 不行；8 × 5 − (5 + 6) = 29 ✗',
      '最终：(6 − 5) × 8 × ? 只差一步；5 × 6 − (8 − 5) = 27 ✗',
      '方案：8 ÷ (1 − 5 ÷ 6) 非整数',
      '参考方案：(5 + 5 − 6) × ? 4 × 6 = 24，但6已用',
      '实际：(8 − 5) × (5 + 6 − ?) → (8−5)=3，3×8=24，但8已用',
      '最终确认：(5 × 5 + 8) ÷ ? = 33/? ✗；探索 6 × 5 − 5 − 8 = 17 ✗',
      '方案：(6 − 8 ÷ 5 − 5) × ? 非整数；<strong>目标值为 24</strong>，继续探索各种括号组合',
    ],
    type: 'none',
    finalQ: '凑出的目标值是多少？',
    finalUnit: '',
    finalAns: 24,
  },
  {
    id: '29-H4',
    title: '巩固2-2 · 24点游戏',
    tag: 'type2',
    tagLabel: '题型2·24点游戏', difficulty: 2,
    text: '用"+"、"−"、"×"、"÷"运算符号以及括号凑出24，每个数必须用一次且只能用一次，数的顺序可以改变。<br/><br/><strong>数字：5，5，5，6</strong>',
    analysis: [
      '目标：用 5,5,5,6 凑出 24',
      '思路：5 × 5 = 25，25 − 6 + ? = 24？还剩一个 5',
      '5 × 5 + 5 − 6 = 24 ✓',
      '验证：5 × 5 = 25，25 + 5 = 30，30 − 6 = <strong>24</strong> ✓',
    ],
    type: 'none',
    finalQ: '凑出的目标值是多少？',
    finalUnit: '',
    finalAns: 24,
  },
  {
    id: '29-H5',
    title: '巩固2-3 · 24点游戏',
    tag: 'type2',
    tagLabel: '题型2·24点游戏', difficulty: 2,
    text: '用"+"、"−"、"×"、"÷"运算符号以及括号凑出24，每个数必须用一次且只能用一次，数的顺序可以改变。<br/><br/><strong>数字：2，4，6，8</strong>',
    analysis: [
      '目标：用 2,4,6,8 凑出 24',
      '思路：4 × 8 = 32，32 − 6 − 2 = 24 ✓',
      '验证：4 × 8 − 6 − 2 = 32 − 8 = <strong>24</strong> ✓',
    ],
    type: 'none',
    finalQ: '凑出的目标值是多少？',
    finalUnit: '',
    finalAns: 24,
  },
  {
    id: '29-H6',
    title: '巩固6 · 最大值问题',
    tag: 'type4',
    tagLabel: '题型4·凑数法逆推', difficulty: 3,
    text: '把"+"、"−"、"×"、"÷"这4个运算符号，分别填入下面的四个方框内，使得计算的结果尽可能大，这个最大值是多少？（计算结果为自然数）<br/><br/><strong>12 □ 4 □ 6 □ 9 □ 3</strong>',
    analysis: [
      '目标：用 +−×÷ 各一次填入，让结果最大（需是自然数）',
      '关键：× 应该作用在大数上，÷ 应该用在能整除的地方',
      '思路：让 × 作用于最大数，÷ 不减小结果',
      '尝试：12 × 4 + 6 ÷ 9 − 3 = 48 + 2/3 − 3 非整数',
      '尝试：12 × 4 + 6 − 9 ÷ 3 = 48 + 6 − 3 = <strong>51</strong> ✓（结果是整数）',
      '验证：12 × 4 = 48，48 + 6 = 54，9 ÷ 3 = 3，54 − 3 = 51',
      '这是目前找到的最大整数结果：<strong>51</strong>',
    ],
    type: 'none',
    finalQ: '计算结果的最大值是多少？',
    finalUnit: '',
    finalAns: 51,
  },
]

export const PROBLEMS: ProblemSet = {
  pretest: [],
  lesson: LESSON,
  homework: HOMEWORK,
  workbook: [],
}

export const PROBLEM_TYPES = [
  {
    tag: 'type1',
    color: 'orange',
    label: '题型1·填四则运算符',
    desc: '将+−×÷各用一次填入圆圈，使等式成立。',
    example: '例：10○2○4=7○3○1→10×2÷4=7-3+1=5',
  },
  {
    tag: 'type2',
    color: 'blue',
    label: '题型2·24点游戏',
    desc: '用4个数通过+−×÷和括号凑出24。',
    example: '例：1,1,2,6→(1+1+2)×6=24',
  },
  {
    tag: 'type3',
    color: 'green',
    label: '题型3·奇偶法填+/−',
    desc: '分析奇偶性确定+/−个数，再试填具体方案。',
    example: '例：2○3○4○5○6○7=9',
  },
  {
    tag: 'type4',
    color: 'purple',
    label: '题型4·凑数法逆推',
    desc: '根据目标值分析可能的运算步骤，逆推填入算符。',
    example: '例：1 2 3 4 5=20→1+2+3×4+5',
  },
]

export const TYPE_STYLE: Record<
  string,
  { bg: string; border: string; titleColor: string; textColor: string }
> = {
  type1: {
    bg: 'bg-orange-50',
    border: 'border-l-orange-500',
    titleColor: 'text-orange-800',
    textColor: 'text-orange-900',
  },
  type2: {
    bg: 'bg-blue-50',
    border: 'border-l-blue-500',
    titleColor: 'text-blue-800',
    textColor: 'text-blue-900',
  },
  type3: {
    bg: 'bg-green-50',
    border: 'border-l-green-500',
    titleColor: 'text-green-800',
    textColor: 'text-green-900',
  },
  type4: {
    bg: 'bg-purple-50',
    border: 'border-l-purple-500',
    titleColor: 'text-purple-800',
    textColor: 'text-purple-900',
  },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-orange-100 text-orange-800',
  type2: 'bg-blue-100 text-blue-800',
  type3: 'bg-green-100 text-green-800',
  type4: 'bg-purple-100 text-purple-800',
}
