import type { Problem, ProblemSet } from '@rosie/core'

export const LESSON_TIP =
  '差倍问题：先找「差」与「倍」的对应关系，画线段图；和差问题先求和与差再各半；移多补少要分清调前调后。'

export const TYPE_TIP: Record<string, string> = {
  type1: '基本差倍——知道和（或总量）与两量之差，先求较小量再求较大量。',
  type2: '移多补少——调动后建立新的倍数关系，注意调动引起的差值变化。',
  type3: '年龄问题——年龄差不变，几年后倍数关系列方程。',
  type4: '几何与和倍——周长求长宽、和倍分配先求1份。',
  type5: '综合挑战——多步推理、三元相等或隐含条件。',
}

const LESSON: Problem[] = [
  {
    id: '52-L1',
    title: '例题1 · 甲乙和差',
    tag: 'type1',
    tagLabel: '和差问题',
    difficulty: 2,
    text: '甲和乙的和是 <strong>75</strong>，甲和乙的差是 <strong>17</strong>，那么甲和乙分别是多少？',
    analysis: [
      '和差公式：较大数=(和+差)÷2',
      '甲=(75+17)÷2=<strong>46</strong>，乙=75−46=<strong>29</strong>',
    ],
    type: 'none',
    finalQ: '甲是',
    finalUnit: '',
    finalAns: 46,
  },
  {
    id: '52-L2',
    title: '例题2 · 减法三量',
    tag: 'type1',
    tagLabel: '和差问题',
    difficulty: 3,
    text: '被减数、减数、差的和是 <strong>2010</strong>，减数比差大 <strong>155</strong>，减数是多少？',
    analysis: [
      '被减数=减数+差，三量和=2×(减数+差)=2010 → 减数+差=1005',
      '减数−差=155，两式相加：2×减数=1160',
      '减数 <strong>580</strong>',
    ],
    type: 'none',
    finalQ: '减数是',
    finalUnit: '',
    finalAns: 580,
  },
  {
    id: '52-L3',
    title: '例题3 · 小组转人',
    tag: 'type2',
    tagLabel: '移多补少',
    difficulty: 3,
    text: '计算机小组和航模小组共有 <strong>20</strong> 个同学，但有 <strong>6</strong> 个同学中途从计算机小组转到了航模小组，这时计算机小组便比航模小组少了 <strong>10</strong> 人。那么这两个小组原来各有多少人？',
    analysis: [
      '转人后：计算机比航模少10人 → 原计算机比航模多2人',
      '设航模原 x 人，计算机 x+2：x+(x+2)=20',
      '计算机小组原来 <strong>11</strong> 人',
    ],
    type: 'none',
    finalQ: '计算机小组原来有',
    finalUnit: '人',
    finalAns: 11,
  },
  {
    id: '52-L4',
    title: '例题4 · 三小组造件',
    tag: 'type1',
    tagLabel: '和差问题',
    difficulty: 3,
    text: '某工厂开展劳动竞赛，三个小组共造零件 <strong>420</strong> 个，第一组比第二组多造 <strong>10</strong> 个，第二组比第三组少造 <strong>17</strong> 个，3 个小组各造零件多少个？',
    analysis: [
      '设第二组 x 个：第一组 x+10，第三组 x+17',
      '(x+10)+x+(x+17)=420 → 3x=393',
      '第一组 <strong>141</strong> 个',
    ],
    type: 'none',
    finalQ: '第一组造了',
    finalUnit: '个',
    finalAns: 141,
  },
  {
    id: '52-L5',
    title: '例题5 · 三班调人',
    tag: 'type2',
    tagLabel: '移多补少',
    difficulty: 4,
    text: '红旗小学三年级有甲、乙、丙三个班，一共有学生 <strong>184</strong> 人。如果从甲班转出 <strong>3</strong> 个人到乙班，则甲、乙两班人数相同；如果这时再从丙班转出 <strong>5</strong> 个人到乙班，则乙、丙两班人数相同。请问：甲班原来有多少人？',
    analysis: [
      '甲给乙3人后相等 → 甲原比乙多6人：甲=乙+6',
      '丙给乙5人后乙=丙 → 丙原比乙多13人：丙=乙+13',
      '3乙+19=184 → 乙=55，甲 <strong>61</strong> 人',
    ],
    type: 'none',
    finalQ: '甲班原来有',
    finalUnit: '人',
    finalAns: 61,
  },
  {
    id: '52-L6',
    title: '例题6 · 奥运志愿者',
    tag: 'type4',
    tagLabel: '和倍问题',
    difficulty: 2,
    text: '某大学共有 <strong>210</strong> 人是奥运志愿者，其中男生人数是女生的 <strong>5</strong> 倍，那么男生比女生多几人？',
    analysis: [
      '和倍：总份数 5+1=6 份',
      '女生 210÷6=35 人，男生 175 人',
      '男生比女生多 <strong>140</strong> 人',
    ],
    type: 'none',
    finalQ: '男生比女生多',
    finalUnit: '人',
    finalAns: 140,
  },
  {
    id: '52-L7',
    title: '例题7 · 植树节',
    tag: 'type4',
    tagLabel: '和倍问题',
    difficulty: 3,
    text: '植树节到了，纳纳和约约一起到郊外义务植树。他们一共植了 <strong>47</strong> 棵树，纳纳植的树比约约植的树的 <strong>4</strong> 倍少 <strong>13</strong> 棵，那么纳纳比约约多植了几棵？',
    analysis: [
      '设约约 x 棵，纳纳 4x−13',
      'x+(4x−13)=47 → x=12，纳纳 35 棵',
      '纳纳比约约多 <strong>23</strong> 棵',
    ],
    type: 'none',
    finalQ: '纳纳比约约多植了',
    finalUnit: '棵',
    finalAns: 23,
  },
  {
    id: '52-L8',
    title: '例题8 · 三色气球',
    tag: 'type4',
    tagLabel: '和倍问题',
    difficulty: 3,
    text: '玩具厂生产红、黄、白气球共 <strong>125</strong> 个；其中，红气球的个数是黄气球的 <strong>3</strong> 倍，白气球比黄气球少 <strong>25</strong> 个。三种气球各生产了多少个？',
    analysis: [
      '设黄气球 y 个：红 3y，白 y−25',
      'y+3y+(y−25)=125 → y=30',
      '红气球 <strong>90</strong> 个',
    ],
    type: 'none',
    finalQ: '红气球生产了',
    finalUnit: '个',
    finalAns: 90,
  },
  {
    id: '52-L9',
    title: '例题9 · 三数和倍',
    tag: 'type4',
    tagLabel: '和倍问题',
    difficulty: 3,
    text: '甲、乙、丙三个数和为 <strong>91</strong>，甲是乙的 <strong>3</strong> 倍，乙是丙的 <strong>3</strong> 倍，求这三个数分别是多少？',
    analysis: [
      '设丙 x：乙 3x，甲 9x',
      'x+3x+9x=91 → x=7',
      '甲 <strong>63</strong>，乙 21，丙 7',
    ],
    type: 'none',
    finalQ: '甲是',
    finalUnit: '',
    finalAns: 63,
  },
  {
    id: '52-L10',
    title: '例题10 · 三船捕鱼',
    tag: 'type4',
    tagLabel: '和倍问题',
    difficulty: 4,
    text: '甲、乙、丙三艘渔船共捕捞了 <strong>1000</strong> 斤金枪鱼，其中甲船捕捞的金枪鱼比乙船的 <strong>2</strong> 倍多 <strong>200</strong> 斤，而乙船捕捞的则是丙船的 <strong>3</strong> 倍，那么甲船比丙船多捕捞了几斤？',
    analysis: [
      '设丙 x 斤：乙 3x，甲 6x+200',
      'x+3x+6x+200=1000 → x=80',
      '甲比丙多 680−80=<strong>600</strong> 斤',
    ],
    type: 'none',
    finalQ: '甲船比丙船多捕捞了',
    finalUnit: '斤',
    finalAns: 600,
  },
  {
    id: '52-L11',
    title: '例题11 · 三班人数',
    tag: 'type4',
    tagLabel: '和倍问题',
    difficulty: 4,
    text: '甲、乙、丙三个班的人数和为 <strong>194</strong>，乙班人数是甲班人数的 <strong>5</strong> 倍还多 <strong>1</strong>，丙班人数是乙班人数的 <strong>5</strong> 倍还多 <strong>2</strong>，求三个班的人数各是多少？',
    analysis: [
      '设甲 x 人：乙 5x+1，丙 25x+7',
      'x+5x+1+25x+7=194 → 31x=186',
      '甲班 <strong>6</strong> 人',
    ],
    type: 'none',
    finalQ: '甲班有',
    finalUnit: '人',
    finalAns: 6,
  },
  {
    id: '52-L12',
    title: '例题12 · 投篮比赛',
    tag: 'type1',
    tagLabel: '差倍问题',
    difficulty: 2,
    text: '纳纳和约约进行投篮比赛，纳纳投中的次数是约约的 <strong>4</strong> 倍，并且约约比纳纳少投中 <strong>9</strong> 次，请问纳纳和约约一共投中了几次？',
    analysis: [
      '差倍：4份−1份=3份=9 次',
      '约约 3 次，纳纳 12 次',
      '一共 <strong>15</strong> 次',
    ],
    type: 'none',
    finalQ: '一共投中了',
    finalUnit: '次',
    finalAns: 15,
  },
  {
    id: '52-L13',
    title: '例题13 · 商与差',
    tag: 'type1',
    tagLabel: '差倍问题',
    difficulty: 2,
    text: '已知两个数的商是 <strong>4</strong>，而这两个数的差是 <strong>39</strong>，那么其中较小的数等于多少？',
    analysis: [
      '较大数=4×较小数，差=3×较小数',
      '3×较小数=39',
      '较小数 <strong>13</strong>',
    ],
    type: 'none',
    finalQ: '较小的数是',
    finalUnit: '',
    finalAns: 13,
  },
  {
    id: '52-L14',
    title: '例题14 · 两根绳子',
    tag: 'type2',
    tagLabel: '移多补少',
    difficulty: 3,
    text: '有两根同样长的绳子，第一根截去 <strong>12</strong> 米，第二根接上 <strong>14</strong> 米。这时第二根长度是第一根长的 <strong>3</strong> 倍，两根绳子原来各长多少米？',
    analysis: [
      '设原长 L 米：L+14=3(L−12)',
      'L+14=3L−36 → 2L=50',
      '原来各长 <strong>25</strong> 米',
    ],
    type: 'none',
    finalQ: '原来每根长',
    finalUnit: '米',
    finalAns: 25,
  },
  {
    id: '52-L15',
    title: '例题15 · 施工队调人',
    tag: 'type2',
    tagLabel: '移多补少',
    difficulty: 4,
    text: '甲、乙两个施工队人数相等，但甲队最近向乙队抽调了 <strong>14</strong> 人。抽调完后，乙队的人数比甲队的 <strong>5</strong> 倍少 <strong>4</strong> 人。请问甲、乙两队原来各有几人？',
    analysis: [
      '设原各 x 人：乙+14=5(甲−14)−4',
      'x+14=5x−70−4 → 4x=88',
      '原来各有 <strong>22</strong> 人',
    ],
    type: 'none',
    finalQ: '原来每队有',
    finalUnit: '人',
    finalAns: 22,
  },
  {
    id: '52-L16',
    title: '例题16 · 分书问题',
    tag: 'type2',
    tagLabel: '移多补少',
    difficulty: 4,
    text: '甲、乙各有若干本书，若甲给乙 <strong>45</strong> 本，则二人的书相等，若乙给甲 <strong>45</strong> 本，则甲的本数是乙的 <strong>4</strong> 倍。甲、乙各有多少本书？',
    analysis: [
      '甲给乙45本相等 → 甲比乙多90本',
      '乙给甲45本：甲+45=4(乙−45)',
      '甲 <strong>195</strong> 本，乙 105 本',
    ],
    type: 'none',
    finalQ: '甲有',
    finalUnit: '本',
    finalAns: 195,
  },
  {
    id: '52-L17',
    title: '例题17 · 车马炮',
    tag: 'type1',
    tagLabel: '差倍问题',
    difficulty: 3,
    text: '用中国象棋中的车、马、炮分别代表不同的自然数。已知车 ÷ 马 = <strong>2</strong>，炮 ÷ 车 = <strong>4</strong>，炮 − 马 = <strong>56</strong>。求：车 + 马 + 炮等于多少？',
    analysis: [
      '设马 m：车 2m，炮 8m',
      '8m−m=56 → m=8',
      '车+马+炮=16+8+64=<strong>88</strong>',
    ],
    type: 'none',
    finalQ: '车+马+炮等于',
    finalUnit: '',
    finalAns: 88,
  },
  {
    id: '52-L18',
    title: '例题18 · 连续自然数',
    tag: 'type1',
    tagLabel: '差倍问题',
    difficulty: 3,
    text: '三个连续自然数，后面两个数的积与前面两个数的积的差是 <strong>88</strong>，那么最小的那个自然数是几？',
    analysis: [
      '设最小为 n：(n+1)(n+2)−n(n+1)=2(n+1)',
      '2(n+1)=88 → n+1=44',
      '最小自然数 <strong>43</strong>',
    ],
    type: 'none',
    finalQ: '最小的自然数是',
    finalUnit: '',
    finalAns: 43,
  },
  {
    id: '52-L19',
    title: '例题19 · 三国军队',
    tag: 'type5',
    tagLabel: '综合应用',
    difficulty: 4,
    text: '三国时期，魏国、蜀国、吴国交战。已知吴国军队比蜀国军队多 <strong>6</strong> 万人；魏国军队人数是吴国的 <strong>3</strong> 倍，又是蜀国的 <strong>5</strong> 倍。魏国军队有多少万人？',
    analysis: [
      '魏=3吴=5蜀，吴=蜀+6',
      '5蜀=3(蜀+6) → 蜀=9 万',
      '魏国 <strong>45</strong> 万人',
    ],
    type: 'none',
    finalQ: '魏国军队有',
    finalUnit: '万人',
    finalAns: 45,
  },
  {
    id: '52-L20',
    title: '例题20 · 图书馆藏书',
    tag: 'type5',
    tagLabel: '综合应用',
    difficulty: 4,
    text: '图书馆小学馆一共有三类图书：科技书、辅导书、小说书，一共 <strong>900</strong> 本。已知小说书的数量等于其他两类书之和，科技书和小说书的总量是辅导书的 <strong>5</strong> 倍。那么图书馆一共有科技书多少本？',
    analysis: [
      '小说=其他两类之和 → 小说=450 本',
      '科技+450=5×辅导，科技+辅导=450',
      '辅导 150 本，科技 <strong>300</strong> 本',
    ],
    type: 'none',
    finalQ: '科技书有',
    finalUnit: '本',
    finalAns: 300,
  },
  {
    id: '52-L21',
    title: '例题21 · 三人吃糖',
    tag: 'type5',
    tagLabel: '综合应用',
    difficulty: 4,
    text: '甲、乙、丙三人在一起吃糖果，一共有 <strong>100</strong> 颗。如果甲吃掉 <strong>1</strong> 颗，乙吃掉 <strong>3</strong> 颗，丙吃掉 <strong>6</strong> 颗的话，那么甲剩下的糖果是乙的 <strong>3</strong> 倍，而乙剩下的糖果是丙的 <strong>2</strong> 倍。那么甲原来有多少颗糖？',
    analysis: [
      '设丙剩 c 颗：乙剩 2c，甲剩 6c',
      '6c+2c+c+10=100 → c=10',
      '甲原来 6×10+1=<strong>61</strong> 颗',
    ],
    type: 'none',
    finalQ: '甲原来有',
    finalUnit: '颗',
    finalAns: 61,
  },
  {
    id: '52-L22',
    title: '例题22 · 三座水库',
    tag: 'type5',
    tagLabel: '综合应用',
    difficulty: 5,
    text: '甲、乙、丙三座水库中一共有 <strong>168</strong> 亿立方米。如果从甲水库调 <strong>10</strong> 亿立方米到乙水库，再从丙水库调 <strong>13</strong> 亿立方米到乙水库，这样的话甲、丙两个水库的水量就相等了，而乙水库的储水量则是其他两个之和。那么乙水库原来有水多少亿立方米？',
    analysis: [
      '调水后甲=丙=x，乙=2x，4x=168 → x=42',
      '乙调水后 84 亿，原 84−23',
      '乙水库原来 <strong>61</strong> 亿立方米',
    ],
    type: 'none',
    finalQ: '乙水库原来有',
    finalUnit: '亿立方米',
    finalAns: 61,
  },
  {
    id: '52-L23',
    title: '例题23 · 蚂蚁窝',
    tag: 'type5',
    tagLabel: '综合应用',
    difficulty: 4,
    text: '一窝蚂蚁由蚁后、工蚁、兵蚁和雄蚁组成。其中蚁后只有 <strong>1</strong> 只，工蚁的数目要比雄蚁多 <strong>5</strong> 倍，而兵蚁的数目要比雄蚁多 <strong>2</strong> 倍，这窝蚂蚁一共有 <strong>801</strong> 只，请问：这窝蚂蚁中一共有多少只工蚁？',
    analysis: [
      '设雄蚁 m 只：工蚁 6m，兵蚁 3m',
      '1+m+6m+3m=801 → m=80',
      '工蚁 <strong>480</strong> 只',
    ],
    type: 'none',
    finalQ: '工蚁一共有',
    finalUnit: '只',
    finalAns: 480,
  },
]

const HOMEWORK: Problem[] = [
  {
    id: '52-H1',
    title: '练习1 · 钢管锯段',
    tag: 'type1',
    tagLabel: '基本差倍',
    difficulty: 2,
    text: '有一根钢管长 <strong>25</strong> 米，要锯成两段，使第一段比第二段短 <strong>5</strong> 米，第一段长多少米？',
    analysis: [
      '设第一段 x 米，第二段 x+5 米',
      'x+(x+5)=25 → 2x=20',
      '第一段 <strong>10</strong> 米',
    ],
    type: 'none',
    finalQ: '第一段长',
    finalUnit: '米',
    finalAns: 10,
  },
  {
    id: '52-H2',
    title: '练习2 · 连续奇数',
    tag: 'type1',
    tagLabel: '基本差倍',
    difficulty: 2,
    text: '两个连续奇数的和是 <strong>36</strong>，较大的奇数是多少？',
    analysis: [
      '设较小奇数为 n，较大为 n+2',
      'n+(n+2)=36 → n=17',
      '较大奇数 <strong>19</strong>',
    ],
    type: 'none',
    finalQ: '较大的奇数是',
    finalUnit: '',
    finalAns: 19,
  },
  {
    id: '52-H3',
    title: '练习3 · 专家组调人',
    tag: 'type2',
    tagLabel: '移多补少',
    difficulty: 3,
    text: '两个专家组共有专家 <strong>298</strong> 名，从第一组调出 <strong>20</strong> 人到第二组后两组人数相等，原来第一组有多少名专家？',
    analysis: [
      '调人后第一组比第二组多 40 人',
      '设第二组原有 x 人：x+40+x=298',
      '第一组原有 <strong>169</strong> 名',
    ],
    type: 'none',
    finalQ: '原来第一组有',
    finalUnit: '名',
    finalAns: 169,
  },
  {
    id: '52-H4',
    title: '练习4 · 两桶水',
    tag: 'type2',
    tagLabel: '移多补少',
    difficulty: 3,
    text: '两桶水共重 <strong>72</strong> 公斤，从第一桶取出 <strong>12</strong> 公斤倒入第二桶后，第二桶比第一桶少 <strong>4</strong> 公斤，原来第一桶有多少公斤？',
    analysis: [
      '设原第一桶 x 公斤，第二桶 72−x',
      '倒水后：(72−x+12)=(x−12)−4',
      'x=<strong>50</strong> 公斤',
    ],
    type: 'none',
    finalQ: '原来第一桶有',
    finalUnit: '公斤',
    finalAns: 50,
  },
  {
    id: '52-H5',
    title: '练习5 · 操场长宽',
    tag: 'type4',
    tagLabel: '几何与和倍',
    difficulty: 3,
    text: '长方形操场长与宽相差 <strong>120</strong> 米，沿操场跑一周 <strong>800</strong> 米，操场长多少米？',
    analysis: [
      '长+宽=800÷2=400 米',
      '长−宽=120 → 长=(400+120)÷2',
      '长 <strong>260</strong> 米',
    ],
    type: 'none',
    finalQ: '操场长',
    finalUnit: '米',
    finalAns: 260,
  },
  {
    id: '52-H6',
    title: '练习6 · 铅笔用去',
    tag: 'type2',
    tagLabel: '移多补少',
    difficulty: 3,
    text: '纳纳和约约共有铅笔 <strong>25</strong> 支，纳纳用去 <strong>4</strong> 支、约约用去 <strong>3</strong> 支后，纳纳仍比约约多 <strong>2</strong> 支，纳纳原来有多少支？',
    analysis: [
      '用去后纳纳比约约多 2 支 → 原来多 3 支',
      '纳纳+约约=25，纳纳−约约=3',
      '纳纳原来 <strong>14</strong> 支',
    ],
    type: 'none',
    finalQ: '纳纳原来有',
    finalUnit: '支',
    finalAns: 14,
  },
  {
    id: '52-H7',
    title: '练习7 · 分糖三人',
    tag: 'type1',
    tagLabel: '基本差倍',
    difficulty: 2,
    text: '有 <strong>99</strong> 块糖分给甲、乙、丙，甲比乙多 <strong>3</strong> 块，丙比乙多 <strong>6</strong> 块，乙分得多少块？',
    analysis: [
      '设乙 x 块：x+(x+3)+(x+6)=99',
      '3x+9=99 → x=30',
      '乙分得 <strong>30</strong> 块',
    ],
    type: 'none',
    finalQ: '乙分得',
    finalUnit: '块',
    finalAns: 30,
  },
  {
    id: '52-H8',
    title: '练习8 · 荔枝黄杏',
    tag: 'type1',
    tagLabel: '基本差倍',
    difficulty: 2,
    text: '<strong>2</strong> 箱荔枝和 <strong>2</strong> 箱黄杏共重 <strong>80</strong> 千克，每箱荔枝是每箱黄杏的 <strong>3</strong> 倍，每箱荔枝重多少千克？',
    analysis: [
      '设每箱黄杏 x 千克，荔枝 3x',
      '2×3x+2x=80 → 8x=80',
      '每箱荔枝 <strong>30</strong> 千克',
    ],
    type: 'none',
    finalQ: '每箱荔枝重',
    finalUnit: '千克',
    finalAns: 30,
  },
  {
    id: '52-H9',
    title: '练习9 · 模型转让',
    tag: 'type2',
    tagLabel: '移多补少',
    difficulty: 3,
    text: '纳纳有 <strong>24</strong> 个模型，约约有 <strong>15</strong> 个，约约给纳纳多少个后纳纳的模型数是约约的 <strong>2</strong> 倍？',
    analysis: [
      '设给 x 个：24+x=2(15−x)',
      '24+x=30−2x → 3x=6',
      '约约给 <strong>2</strong> 个',
    ],
    type: 'none',
    finalQ: '约约给纳纳',
    finalUnit: '个',
    finalAns: 2,
  },
  {
    id: '52-H10',
    title: '练习10 · 分糖两人',
    tag: 'type1',
    tagLabel: '基本差倍',
    difficulty: 2,
    text: '有 <strong>100</strong> 颗糖分给甲、乙，甲是乙的 <strong>2</strong> 倍多 <strong>4</strong> 颗，乙分得多少颗？',
    analysis: [
      '设乙 x 颗，甲 2x+4',
      '3x+4=100 → x=32',
      '乙分得 <strong>32</strong> 颗',
    ],
    type: 'none',
    finalQ: '乙分得',
    finalUnit: '颗',
    finalAns: 32,
  },
  {
    id: '52-H11',
    title: '练习11 · 父女年龄',
    tag: 'type3',
    tagLabel: '年龄问题',
    difficulty: 3,
    text: '爸爸和女儿年龄和是 <strong>55</strong> 岁，<strong>4</strong> 年后爸爸年龄是女儿的 <strong>2</strong> 倍，女儿今年多少岁？',
    analysis: [
      '设女儿今年 x 岁，爸爸 55−x',
      '55−x+4=2(x+4)',
      '女儿今年 <strong>17</strong> 岁',
    ],
    type: 'none',
    finalQ: '女儿今年',
    finalUnit: '岁',
    finalAns: 17,
  },
  {
    id: '52-H12',
    title: '练习12 · 下雨天数',
    tag: 'type4',
    tagLabel: '几何与和倍',
    difficulty: 3,
    text: '去年 <strong>365</strong> 天中，不下雨天数比下雨天数 <strong>3</strong> 倍多 <strong>5</strong> 天，去年下雨多少天？',
    analysis: [
      '设下雨 x 天，不下雨 3x+5',
      'x+3x+5=365 → 4x=360',
      '下雨 <strong>90</strong> 天',
    ],
    type: 'none',
    finalQ: '下雨',
    finalUnit: '天',
    finalAns: 90,
  },
  {
    id: '52-H13',
    title: '练习13 · 一家三口年龄',
    tag: 'type3',
    tagLabel: '年龄问题',
    difficulty: 3,
    text: '一家三口年龄和 <strong>72</strong> 岁，爸妈同岁，妈妈年龄是孩子的 <strong>4</strong> 倍，孩子多少岁？',
    analysis: [
      '设孩子 x 岁，爸妈各 4x',
      '4x+4x+x=72 → 9x=72',
      '孩子 <strong>8</strong> 岁',
    ],
    type: 'none',
    finalQ: '孩子',
    finalUnit: '岁',
    finalAns: 8,
  },
  {
    id: '52-H14',
    title: '练习14 · 彩票纸盒',
    tag: 'type4',
    tagLabel: '几何与和倍',
    difficulty: 3,
    text: '红、黄、蓝三盒共 <strong>63</strong> 张彩票，红是黄的 <strong>2</strong> 倍，蓝是黄的 <strong>4</strong> 倍，黄色盒有多少张？',
    analysis: [
      '设黄 x 张：2x+4x+x=63',
      '7x=63 → x=9',
      '黄色盒 <strong>9</strong> 张',
    ],
    type: 'none',
    finalQ: '黄色盒有',
    finalUnit: '张',
    finalAns: 9,
  },
  {
    id: '52-H15',
    title: '练习15 · 三种商品',
    tag: 'type4',
    tagLabel: '几何与和倍',
    difficulty: 3,
    text: '甲、乙、丙三种商品，乙是甲的 <strong>2</strong> 倍，丙比甲多 <strong>3</strong> 元，买各 <strong>2</strong> 个共 <strong>70</strong> 元，甲多少元？',
    analysis: [
      '设甲 x 元：2(x+2x+x+3)=70',
      '8x+6=70 → x=8',
      '甲 <strong>8</strong> 元',
    ],
    type: 'none',
    finalQ: '甲的价格是',
    finalUnit: '元',
    finalAns: 8,
  },
  {
    id: '52-H16',
    title: '练习16 · 书架藏书',
    tag: 'type4',
    tagLabel: '几何与和倍',
    difficulty: 2,
    text: '爸爸书架藏书是小纳的 <strong>6</strong> 倍，爸爸比小纳多 <strong>135</strong> 本，爸爸书架有多少本？',
    analysis: [
      '多出的 5 份=135 本',
      '1 份=27 本，爸爸 6 份',
      '爸爸 <strong>162</strong> 本',
    ],
    type: 'none',
    finalQ: '爸爸书架有',
    finalUnit: '本',
    finalAns: 162,
  },
  {
    id: '52-H17',
    title: '练习17 · 每天存钱',
    tag: 'type3',
    tagLabel: '年龄问题',
    difficulty: 3,
    text: '甲有 <strong>100</strong> 元、乙有 <strong>20</strong> 元，两人每天各存 <strong>2</strong> 元，多少天后乙的钱是甲的一半？',
    analysis: [
      '设 x 天后：20+2x=(100+2x)÷2',
      '40+4x=100+2x → 2x=60',
      '<strong>30</strong> 天后',
    ],
    type: 'none',
    finalQ: '多少天后',
    finalUnit: '天',
    finalAns: 30,
  },
  {
    id: '52-H18',
    title: '练习18 · 纸带剪段',
    tag: 'type1',
    tagLabel: '基本差倍',
    difficulty: 3,
    text: '两条纸带长 <strong>21</strong> 厘米和 <strong>13</strong> 厘米，各剪下同样长的一段后，长条剩下的是短条的 <strong>3</strong> 倍，剪下多少厘米？',
    analysis: [
      '设剪 x 厘米：21−x=3(13−x)',
      '21−x=39−3x → 2x=18',
      '剪下 <strong>9</strong> 厘米',
    ],
    type: 'none',
    finalQ: '剪下',
    finalUnit: '厘米',
    finalAns: 9,
  },
  {
    id: '52-H19',
    title: '练习19 · 花布售出',
    tag: 'type2',
    tagLabel: '移多补少',
    difficulty: 3,
    text: '两块同样长的花布，第一块卖出 <strong>31</strong> 米，第二块卖出 <strong>19</strong> 米后，第二块剩下是第一块的 <strong>4</strong> 倍，原来每块多少米？',
    analysis: [
      '设原长 L：L−19=4(L−31)',
      'L−19=4L−124 → 3L=105',
      '原来每块 <strong>35</strong> 米',
    ],
    type: 'none',
    finalQ: '原来每块长',
    finalUnit: '米',
    finalAns: 35,
  },
  {
    id: '52-H20',
    title: '练习20 · 父子年龄',
    tag: 'type3',
    tagLabel: '年龄问题',
    difficulty: 2,
    text: '爸爸今年 <strong>43</strong> 岁，小新 <strong>9</strong> 岁，再过几年爸爸年龄是小新的 <strong>3</strong> 倍？',
    analysis: [
      '设 x 年后：43+x=3(9+x)',
      '43+x=27+3x → 2x=16',
      '再过 <strong>8</strong> 年',
    ],
    type: 'none',
    finalQ: '再过',
    finalUnit: '年',
    finalAns: 8,
  },
  {
    id: '52-H21',
    title: '练习21 · 叔叔年龄',
    tag: 'type3',
    tagLabel: '年龄问题',
    difficulty: 2,
    text: '叔叔比小纳大 <strong>19</strong> 岁，正好是小纳年龄的 <strong>3</strong> 倍多 <strong>1</strong> 岁，小纳多少岁？',
    analysis: [
      '19=2×小纳+1',
      '小纳 <strong>9</strong> 岁',
    ],
    type: 'none',
    finalQ: '小纳',
    finalUnit: '岁',
    finalAns: 9,
  },
  {
    id: '52-H22',
    title: '练习22 · 仓库调运',
    tag: 'type2',
    tagLabel: '移多补少',
    difficulty: 4,
    text: '甲乙仓库原存同样多电视机，从甲调 <strong>200</strong> 台到乙后，乙比甲 <strong>2</strong> 倍少 <strong>40</strong> 台，两仓库共有多少台？',
    analysis: [
      '设原各 x 台：x+200=2(x−200)−40',
      'x+200=2x−440 → x=640',
      '共有 <strong>1280</strong> 台',
    ],
    type: 'none',
    finalQ: '两仓库共有',
    finalUnit: '台',
    finalAns: 1280,
  },
  {
    id: '52-H23',
    title: '练习23 · 两筐水果',
    tag: 'type2',
    tagLabel: '移多补少',
    difficulty: 4,
    text: '甲乙两筐水果原来重量相等，从甲拿出 <strong>21</strong> 千克放入乙后，乙是甲的 <strong>5</strong> 倍多 <strong>2</strong> 千克，原来每筐多少千克？',
    analysis: [
      '设原各 x 千克：x+21=5(x−21)+2',
      'x+21=5x−103 → 4x=124',
      '原来每筐 <strong>31</strong> 千克',
    ],
    type: 'none',
    finalQ: '原来每筐',
    finalUnit: '千克',
    finalAns: 31,
  },
]

const SUPPLEMENT: Problem[] = [
  {
    id: '52-S1',
    title: '附加作业1 · 图书转让',
    tag: 'type5',
    tagLabel: '附加题',
    difficulty: 4,
    text: '最初甲图书是乙的 <strong>7</strong> 倍，甲给乙 <strong>10</strong> 本后，乙是甲的 <strong>3</strong> 倍，两人共有图书多少本？',
    analysis: [
      '设乙原有 b 本，甲 7b',
      'b+10=3(7b−10) → b=2',
      '共有 7×2+2=<strong>16</strong> 本',
    ],
    type: 'none',
    finalQ: '两人共有',
    finalUnit: '本',
    finalAns: 16,
  },
  {
    id: '52-S2',
    title: '附加作业2 · 钢琴测试',
    tag: 'type5',
    tagLabel: '附加题',
    difficulty: 4,
    text: '钢琴等级测试中，男生比女生 <strong>3</strong> 倍多 <strong>8</strong> 人，比女生 <strong>5</strong> 倍少 <strong>10</strong> 人，男生有多少人？',
    analysis: [
      '3女+8=5女−10 → 2女=18',
      '女生 9 人，男生 <strong>35</strong> 人',
    ],
    type: 'none',
    finalQ: '男生有',
    finalUnit: '人',
    finalAns: 35,
  },
  {
    id: '52-S3',
    title: '附加作业3 · 两袋糖',
    tag: 'type5',
    tagLabel: '附加题',
    difficulty: 5,
    text: '甲、乙各一袋糖（每袋不到 <strong>20</strong> 粒）。甲给乙若干粒后甲是乙的 <strong>2</strong> 倍；乙给甲同样多后甲是乙的 <strong>3</strong> 倍，两人共有多少粒？',
    analysis: [
      '设给 k 粒，推得乙=7k，k=1 时甲17乙7',
      '两人共 <strong>24</strong> 粒',
    ],
    type: 'none',
    finalQ: '两人共有',
    finalUnit: '粒',
    finalAns: 24,
  },
  {
    id: '52-S4',
    title: '附加作业4 · 三校人数',
    tag: 'type5',
    tagLabel: '附加题',
    difficulty: 5,
    text: '甲、乙、丙三校学生共 <strong>2021</strong> 人，甲的 <strong>2</strong> 倍、乙减 <strong>5</strong>、丙加 <strong>9</strong> 相等，甲校多少人？',
    analysis: [
      '设相等量为 k：甲=k/2，乙=k+5，丙=k−9',
      'k/2+k+5+k−9=2021 → k=810',
      '甲校 <strong>405</strong> 人',
    ],
    type: 'none',
    finalQ: '甲校有',
    finalUnit: '人',
    finalAns: 405,
  },
]

const PRETEST: Problem[] = [
  { id: '52-P1', title: '课前测1 · 移苹果', tag: 'type2', tagLabel: '移多补少', difficulty: 3, text: '甲筐比乙筐多 <strong>19</strong> 千克，从甲筐取出若干千克放入乙筐，可使乙筐比甲筐多 <strong>3</strong> 千克。应取出多少千克？', analysis: ['(B+x)−(A−x)=3，A−B=19', '2x=22，取出 <strong>11</strong> 千克'], type: 'none', finalQ: '应取出', finalUnit: '千克', finalAns: 11 },
  { id: '52-P2', title: '课前测2 · 两校人数', tag: 'type1', tagLabel: '和差问题', difficulty: 3, text: '甲、乙两校共 <strong>1050</strong> 人，甲校转入乙校 <strong>20</strong> 人后甲校仍比乙校多 <strong>10</strong> 人。甲校原来有多少人？', analysis: ['A−B=50，A+B=1050', '甲 = <strong>550</strong> 人'], type: 'none', finalQ: '甲校原来有', finalUnit: '人', finalAns: 550 },
  { id: '52-P3', title: '课前测3 · 开分店', tag: 'type1', tagLabel: '和差问题', difficulty: 2, text: '北京、上海共开 <strong>34</strong> 家分店，北京比上海多 <strong>8</strong> 家。北京计划开多少家？', analysis: ['(34+8)÷2 = <strong>21</strong> 家'], type: 'none', finalQ: '北京开', finalUnit: '家', finalAns: 21 },
  { id: '52-P4', title: '课前测4 · 水果箱', tag: 'type1', tagLabel: '差倍问题', difficulty: 3, text: '葡萄比橘子多 <strong>100</strong> 箱，葡萄是橘子的 <strong>6</strong> 倍。葡萄多少箱？', analysis: ['5 份=100，葡萄 = <strong>120</strong> 箱'], type: 'none', finalQ: '葡萄', finalUnit: '箱', finalAns: 120 },
  { id: '52-P5', title: '课前测5 · 三人书本', tag: 'type5', tagLabel: '综合挑战', difficulty: 4, text: '小明比小红多 <strong>13</strong> 本，比小华多 <strong>6</strong> 本，小红和小华共 <strong>47</strong> 本。小明有多少本？', analysis: ['2M−19=47', 'M = <strong>33</strong> 本'], type: 'none', finalQ: '小明有', finalUnit: '本', finalAns: 33 },
  { id: '52-P6', title: '课前测6 · 水池', tag: 'type2', tagLabel: '移多补少', difficulty: 4, text: '甲池 <strong>2600</strong> m³，乙池 <strong>1200</strong> m³。甲流入乙多少 m³ 后，乙是甲的 <strong>4</strong> 倍？', analysis: ['1200+x=4(2600−x)', 'x = <strong>1840</strong> m³'], type: 'none', finalQ: '流入', finalUnit: '立方米', finalAns: 1840 },
  { id: '52-P7', title: '课前测7 · 三种水果', tag: 'type4', tagLabel: '和倍应用', difficulty: 4, text: '西瓜、苹果、芒果共 <strong>78</strong> 斤，西瓜是苹果的 2 倍，芒果比苹果的 3 倍多 6 斤。芒果多少斤？', analysis: ['6 份+6=78，芒果 = <strong>42</strong> 斤'], type: 'none', finalQ: '芒果', finalUnit: '斤', finalAns: 42 },
  { id: '52-P8', title: '课前测8 · 鸡鸭鹅', tag: 'type1', tagLabel: '差倍问题', difficulty: 4, text: '鸡比鸭的 4 倍多 132 只，鹅是鸭的 2 倍，鸡比鹅多 452 只。鸡多少只？', analysis: ['4D+132=2D+452，D=160', '鸡 = <strong>772</strong> 只'], type: 'none', finalQ: '鸡', finalUnit: '只', finalAns: 772 },
  { id: '52-P9', title: '课前测9 · 三种水果重量', tag: 'type5', tagLabel: '综合挑战', difficulty: 4, text: '橘子、苹果、香蕉共 <strong>53</strong> 千克，橘子比苹果的 3 倍少 3 千克，香蕉比苹果的 2 倍多 2 千克。橘子重多少千克？', analysis: ['6a=54，橘子 = <strong>24</strong> 千克'], type: 'none', finalQ: '橘子重', finalUnit: '千克', finalAns: 24 },
  { id: '52-P10', title: '课前测10 · 三数之和', tag: 'type5', tagLabel: '综合挑战', difficulty: 4, text: '甲、乙、丙三数之和 <strong>183</strong>，乙比丙的 2 倍少 4，甲比丙的 3 倍多 7。甲是多少？', analysis: ['6c=180，甲 = <strong>97</strong>'], type: 'none', finalQ: '甲是', finalUnit: '', finalAns: 97 },
  { id: '52-P11', title: '课前测11 · 除法关系', tag: 'type5', tagLabel: '综合挑战', difficulty: 3, text: '被除数、除数、商之和 <strong>212</strong>，商是 <strong>2</strong>。被除数是多少？', analysis: ['被=2×除，被 = <strong>140</strong>'], type: 'none', finalQ: '被除数是', finalUnit: '', finalAns: 140 },
  { id: '52-P12', title: '课前测12 · 两桶水', tag: 'type2', tagLabel: '移多补少', difficulty: 3, text: '大小两桶原来水一样多，从小桶倒 <strong>8</strong> 千克到大桶，则大桶是小桶的 3 倍。原来大桶有多少千克？', analysis: ['w+8=3(w−8)，w = <strong>16</strong> 千克'], type: 'none', finalQ: '原来大桶有', finalUnit: '千克', finalAns: 16 },
  { id: '52-P13', title: '课前测13 · 三种花', tag: 'type4', tagLabel: '和倍应用', difficulty: 4, text: '黄花朵数是红花的 4 倍、也是蓝花的 3 倍，蓝花比红花多 <strong>20</strong> 盆。一共有多少盆花？', analysis: ['红 60，黄 240，蓝 80', '共 <strong>380</strong> 盆'], type: 'none', finalQ: '一共有', finalUnit: '盆', finalAns: 380 },
  { id: '52-P14', title: '课前测14 · 三物重量', tag: 'type5', tagLabel: '综合挑战', difficulty: 4, text: '甲、乙、丙总重 <strong>93</strong> 千克，甲比乙丙之和轻 1 千克，乙比丙的 2 倍多 2 千克。甲重多少千克？', analysis: ['乙+丙=47，甲 = <strong>46</strong> 千克'], type: 'none', finalQ: '甲重', finalUnit: '千克', finalAns: 46 },
]

export const PROBLEMS: ProblemSet = {
  pretest: PRETEST,
  lesson: LESSON,
  homework: HOMEWORK,
  workbook: [],
  supplement: SUPPLEMENT,
}

export const PROBLEM_TYPES = [
  { tag: 'type1', color: 'blue', label: '题型1 · 基本差倍', desc: '知道和与差，先求较小量。', example: '例：钢管锯两段' },
  { tag: 'type2', color: 'green', label: '题型2 · 移多补少', desc: '调动后建立倍数关系列式。', example: '例：调人使两组相等' },
  { tag: 'type3', color: 'orange', label: '题型3 · 年龄问题', desc: '年龄差不变，列方程求年数。', example: '例：4年后爸爸2倍女儿' },
  { tag: 'type4', color: 'purple', label: '题型4 · 几何与和倍', desc: '周长与和差、和倍分配。', example: '例：长宽差+周长求长' },
  { tag: 'type5', color: 'red', label: '题型5 · 综合挑战', desc: '多步推理与三元问题。', example: '例：三校人数相等量' },
]

export const TYPE_STYLE: Record<string, { bg: string; border: string; titleColor: string; textColor: string }> = {
  type1: { bg: 'bg-blue-50', border: 'border-l-blue-500', titleColor: 'text-blue-800', textColor: 'text-blue-900' },
  type2: { bg: 'bg-green-50', border: 'border-l-green-500', titleColor: 'text-green-800', textColor: 'text-green-900' },
  type3: { bg: 'bg-orange-50', border: 'border-l-orange-500', titleColor: 'text-orange-800', textColor: 'text-orange-900' },
  type4: { bg: 'bg-purple-50', border: 'border-l-purple-500', titleColor: 'text-purple-800', textColor: 'text-purple-900' },
  type5: { bg: 'bg-red-50', border: 'border-l-red-500', titleColor: 'text-red-800', textColor: 'text-red-900' },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-app-blue-light text-app-blue-dark',
  type2: 'bg-app-green-light text-app-green-dark',
  type3: 'bg-orange-100 text-orange-700',
  type4: 'bg-app-purple-light text-app-purple-dark',
  type5: 'bg-red-100 text-red-700',
}
