import type { Problem, ProblemSet } from '@rosie/core'

export const LESSON_TIP =
  '最不利原则：先把"最倒霉"的情况全拿完，再加 1（或加到目标个数）就一定能保证！抽屉原理：物体数 ÷ 抽屉数，向上取整就是某个抽屉至少有的个数。'

const PRETEST: Problem[] = [
  {
    id: '46-P1',
    title: '课前测1 · 练习本',
    tag: 'type2',
    tagLabel: '保证两个相同',
    difficulty: 2,
    text: '有 A、B、C、D、E <strong>五种</strong>类型的练习本各 3 个，至少要取出多少个练习本才能保证存在 <strong>两个同类型</strong>的练习本？',
    analysis: [
      '最不利：5 种各取 1 个 = 5 个，仍然两两不同',
      '再取 1 个必与已有某种相同',
      '5 + 1 = <strong>6</strong> 个',
    ],
    type: 'none',
    finalQ: '至少要取多少个？',
    finalUnit: '个',
    finalAns: 6,
  },
  {
    id: '46-P2',
    title: '课前测2 · 取球记录',
    tag: 'type6',
    tagLabel: '组合·完全相同',
    difficulty: 4,
    text: '口袋里有红、橙、黄、绿四种颜色的小球各 1 个，娜娜每次拿出 <strong>两个</strong>球记录颜色后放回。她至少要取多少次才能保证一定有 <strong>2 次</strong>拿出的颜色情况相同？',
    analysis: [
      '每次拿 2 个（必为不同色），不同的取法 = 4 选 2 = 6 种',
      '最不利：前 6 次各不相同',
      '6 + 1 = <strong>7</strong> 次',
    ],
    type: 'none',
    finalQ: '至少要取多少次？',
    finalUnit: '次',
    finalAns: 7,
  },
  {
    id: '46-P3',
    title: '课前测3 · 保证有黄笔',
    tag: 'type3',
    tagLabel: '保证目标出现',
    difficulty: 2,
    text: '盒子里有红笔 <strong>7</strong> 支、黄笔 <strong>10</strong> 支、绿笔 <strong>15</strong> 支。一次至少要取出多少支才能保证拿出的笔中 <strong>有黄色</strong>的？',
    analysis: [
      '最不利：先把非黄色全取完 = 7 + 15 = 22 支',
      '再取 1 支一定是黄色',
      '22 + 1 = <strong>23</strong> 支',
    ],
    type: 'none',
    finalQ: '至少要取多少支？',
    finalUnit: '支',
    finalAns: 23,
  },
  {
    id: '46-P4',
    title: '课前测3 · 保证两种颜色',
    tag: 'type4',
    tagLabel: '保证种类齐全',
    difficulty: 2,
    text: '盒子里有红笔 <strong>7</strong> 支、黄笔 <strong>10</strong> 支、绿笔 <strong>15</strong> 支。一次至少要取出多少支才能保证 <strong>最少有两种颜色</strong>的笔？',
    analysis: [
      '最不利：取的全是数量最多的一种（绿 15 支）',
      '再取 1 支必是另一种颜色',
      '15 + 1 = <strong>16</strong> 支',
    ],
    type: 'none',
    finalQ: '至少要取多少支？',
    finalUnit: '支',
    finalAns: 16,
  },
  {
    id: '46-P5',
    title: '课前测4 · 保证三种颜色',
    tag: 'type4',
    tagLabel: '保证种类齐全',
    difficulty: 3,
    text: '布袋里红球 <strong>10</strong> 个、黄球 <strong>8</strong> 个、蓝球 <strong>3</strong> 个、绿球 <strong>1</strong> 个。至少取出多少个球，才能保证取出的球 <strong>至少有三种颜色</strong>？',
    analysis: [
      '最不利：取的全是数量最多的两种（红 10 + 黄 8 = 18 个）',
      '再取 1 个必是第三种颜色',
      '18 + 1 = <strong>19</strong> 个',
    ],
    type: 'none',
    finalQ: '至少要取多少个？',
    finalUnit: '个',
    finalAns: 19,
  },
  {
    id: '46-P6',
    title: '课前测4 · 保证有红和黄',
    tag: 'type4',
    tagLabel: '保证种类齐全',
    difficulty: 4,
    text: '布袋里红球 <strong>10</strong> 个、黄球 <strong>8</strong> 个、蓝球 <strong>3</strong> 个、绿球 <strong>1</strong> 个。至少取出多少个球，才能保证其中 <strong>必有红球和黄球</strong>？',
    analysis: [
      '要同时保证有红、有黄，看最难凑齐的那种',
      '最不利：把所有非黄色取完 = 10 + 3 + 1 = 14 个（此时红已在内）',
      '再取 1 个必是黄色，红黄都有了：14 + 1 = <strong>15</strong> 个',
    ],
    type: 'none',
    finalQ: '至少要取多少个？',
    finalUnit: '个',
    finalAns: 15,
  },
  {
    id: '46-P7',
    title: '课前测5 · 5 张同花色',
    tag: 'type1',
    tagLabel: '抽屉原理',
    difficulty: 3,
    text: '一副扑克牌 54 张（4 种花色各 13 张，大、小王各 1 张）。至少摸出多少张，才能保证 <strong>至少有 5 张牌花色相同</strong>？',
    analysis: [
      '最不利：每种花色 4 张 = 4 × 4 = 16 张，再加 2 张王',
      '16 + 2 = 18 张仍没有 5 张同花色',
      '再摸 1 张必凑成 5 张同花色：18 + 1 = <strong>19</strong> 张',
    ],
    type: 'none',
    finalQ: '至少要摸多少张？',
    finalUnit: '张',
    finalAns: 19,
  },
  {
    id: '46-P8',
    title: '课前测5 · 四种花色都有',
    tag: 'type4',
    tagLabel: '保证种类齐全',
    difficulty: 4,
    text: '一副扑克牌 54 张（4 种花色各 13 张，大、小王各 1 张）。至少摸出多少张，才能保证 <strong>四种花色的牌都有</strong>？',
    analysis: [
      '最不利：摸完 3 种花色 = 13 × 3 = 39 张，再加 2 张王 = 41 张',
      '再摸 1 张必是第四种花色',
      '41 + 1 = <strong>42</strong> 张',
    ],
    type: 'none',
    finalQ: '至少要摸多少张？',
    finalUnit: '张',
    finalAns: 42,
  },
  {
    id: '46-P9',
    title: '课前测5 · 3 张红桃',
    tag: 'type3',
    tagLabel: '保证目标出现',
    difficulty: 4,
    text: '一副扑克牌 54 张（4 种花色各 13 张，大、小王各 1 张）。至少摸出多少张，才能保证 <strong>至少有 3 张红桃</strong>？',
    analysis: [
      '最不利：先摸完所有非红桃 = 54 − 13 = 41 张',
      '再摸 3 张必是红桃',
      '41 + 3 = <strong>44</strong> 张',
    ],
    type: 'none',
    finalQ: '至少要摸多少张？',
    finalUnit: '张',
    finalAns: 44,
  },
  {
    id: '46-P10',
    title: '课前测5 · 3 张点数相同',
    tag: 'type1',
    tagLabel: '抽屉原理',
    difficulty: 4,
    text: '一副扑克牌 54 张（4 种花色各 13 张，大、小王各 1 张）。至少摸出多少张，才能保证 <strong>至少有 3 张点数一样</strong>？',
    analysis: [
      '共 13 种点数，最不利：每种点数 2 张 = 13 × 2 = 26 张，再加 2 张王 = 28 张',
      '再摸 1 张必凑成 3 张同点数',
      '28 + 1 = <strong>29</strong> 张',
    ],
    type: 'none',
    finalQ: '至少要摸多少张？',
    finalUnit: '张',
    finalAns: 29,
  },
]

const LESSON: Problem[] = [
  {
    id: '46-L1',
    title: '例题1 · 苹果放抽屉',
    tag: 'type1',
    tagLabel: '抽屉原理',
    difficulty: 1,
    text: '把 <strong>10</strong> 个苹果放到 <strong>9</strong> 个抽屉中，无论怎么放，一定能找到一个苹果最多的抽屉，它里面至少有多少个苹果？',
    analysis: [
      '10 个苹果放 9 个抽屉，先每个抽屉放 1 个',
      '剩下 1 个无论放哪，都会让某个抽屉变成 2 个',
      '至少 <strong>2</strong> 个（10 ÷ 9，向上取整）',
    ],
    type: 'none',
    finalQ: '最多的抽屉里至少有几个？',
    finalUnit: '个',
    finalAns: 2,
  },
  {
    id: '46-L2',
    title: '练一练 · 饼干放抽屉',
    tag: 'type1',
    tagLabel: '抽屉原理',
    difficulty: 2,
    text: '把 <strong>13</strong> 盒饼干放到 <strong>6</strong> 个抽屉里，一定能找到一个放饼干最多的抽屉，它里面至少有多少盒？',
    analysis: [
      '先每个抽屉放 2 盒 = 12 盒',
      '还剩 1 盒，必让某抽屉变成 3 盒',
      '13 ÷ 6 向上取整 = <strong>3</strong> 盒',
    ],
    type: 'none',
    finalQ: '最多的抽屉里至少有几盒？',
    finalUnit: '盒',
    finalAns: 3,
  },
  {
    id: '46-L3',
    title: '例题2 · 同一天生日',
    tag: 'type1',
    tagLabel: '抽屉原理',
    difficulty: 2,
    text: '一个班有 <strong>35</strong> 名 6 月份出生的学生（6 月共 30 天），至少有几名学生的生日在 <strong>同一天</strong>？',
    analysis: [
      '把 30 天当作 30 个抽屉',
      '35 ÷ 30 = 1 …… 5，向上取整 = 2',
      '至少 <strong>2</strong> 名学生同一天生日',
    ],
    type: 'none',
    finalQ: '至少有几名同一天生日？',
    finalUnit: '名',
    finalAns: 2,
  },
  {
    id: '46-L4',
    title: '练一练 · 鸽子回舍',
    tag: 'type1',
    tagLabel: '抽屉原理',
    difficulty: 2,
    text: '<strong>22</strong> 只鸽子飞回 <strong>4</strong> 个鸽舍，至少有几只鸽子要飞进 <strong>同一个</strong>鸽舍？',
    analysis: [
      '22 ÷ 4 = 5 …… 2',
      '向上取整 = 6',
      '至少 <strong>6</strong> 只飞进同一鸽舍',
    ],
    type: 'none',
    finalQ: '至少几只飞进同一鸽舍？',
    finalUnit: '只',
    finalAns: 6,
  },
  {
    id: '46-L5',
    title: '例题3 · 4 种玩具',
    tag: 'type2',
    tagLabel: '保证两个相同',
    difficulty: 2,
    text: '货架上有 <strong>4 种</strong>玩具，每种都很多。至少要拿出多少个才能保证有 <strong>2 个相同</strong>的玩具？',
    analysis: [
      '最不利：4 种各拿 1 个 = 4 个，全不同',
      '再拿 1 个必与某种相同',
      '4 + 1 = <strong>5</strong> 个',
    ],
    type: 'none',
    finalQ: '至少要拿几个？',
    finalUnit: '个',
    finalAns: 5,
  },
  {
    id: '46-L6',
    title: '例题3 · 摸出同色球',
    tag: 'type2',
    tagLabel: '保证两个相同',
    difficulty: 2,
    text: '木箱里有 <strong>3</strong> 个红球、<strong>5</strong> 个黄球、<strong>6</strong> 个蓝球。闭眼摸球，为保证取出的球中有 <strong>2 个颜色相同</strong>，最少要取多少个？',
    analysis: [
      '最不利：3 种颜色各取 1 个 = 3 个',
      '再取 1 个必与某色相同',
      '3 + 1 = <strong>4</strong> 个',
    ],
    type: 'none',
    finalQ: '最少要取几个？',
    finalUnit: '个',
    finalAns: 4,
  },
  {
    id: '46-L7',
    title: '练一练 · 借书同种',
    tag: 'type1',
    tagLabel: '抽屉原理',
    difficulty: 2,
    text: '图书馆有故事书、科普书、历史书 <strong>3 种</strong>。每个同学只借一本，至少要几个同学才能保证一定有 <strong>两人借的书属于同一种</strong>？',
    analysis: [
      '3 种书当作 3 个抽屉',
      '最不利：3 人各借不同种',
      '再来 1 人必与某人同种：3 + 1 = <strong>4</strong> 人',
    ],
    type: 'none',
    finalQ: '至少要几个同学？',
    finalUnit: '人',
    finalAns: 4,
  },
  {
    id: '46-L8',
    title: '例题4 · 保证有酸奶味',
    tag: 'type3',
    tagLabel: '保证目标出现',
    difficulty: 2,
    text: '口哨糖：苹果味 <strong>5</strong> 个、巧克力味 <strong>6</strong> 个、酸奶味 <strong>9</strong> 个。一次至少取多少个，才能保证有 <strong>酸奶味</strong>的？',
    analysis: [
      '最不利：把非酸奶味全取完 = 5 + 6 = 11 个',
      '再取 1 个必是酸奶味',
      '11 + 1 = <strong>12</strong> 个',
    ],
    type: 'none',
    finalQ: '至少要取几个？',
    finalUnit: '个',
    finalAns: 12,
  },
  {
    id: '46-L9',
    title: '例题4 · 保证两种口味',
    tag: 'type4',
    tagLabel: '保证种类齐全',
    difficulty: 2,
    text: '口哨糖：苹果味 <strong>5</strong> 个、巧克力味 <strong>6</strong> 个、酸奶味 <strong>9</strong> 个。一次至少取多少个，才能保证有 <strong>两种不同口味</strong>？',
    analysis: [
      '最不利：取的全是最多的一种（酸奶味 9 个）',
      '再取 1 个必是另一种口味',
      '9 + 1 = <strong>10</strong> 个',
    ],
    type: 'none',
    finalQ: '至少要取几个？',
    finalUnit: '个',
    finalAns: 10,
  },
  {
    id: '46-L10',
    title: '练一练 · 保证有黄球',
    tag: 'type3',
    tagLabel: '保证目标出现',
    difficulty: 3,
    text: '玻璃球：黄 <strong>3</strong> 个、绿 <strong>4</strong> 个、红 <strong>5</strong> 个、蓝 <strong>8</strong> 个。至少拿多少个才能保证一定有 <strong>1 个黄色</strong>？',
    analysis: [
      '最不利：把非黄色全拿完 = 4 + 5 + 8 = 17 个',
      '再拿 1 个必是黄色',
      '17 + 1 = <strong>18</strong> 个',
    ],
    type: 'none',
    finalQ: '至少要拿几个？',
    finalUnit: '个',
    finalAns: 18,
  },
  {
    id: '46-L11',
    title: '练一练 · 保证两种颜色',
    tag: 'type4',
    tagLabel: '保证种类齐全',
    difficulty: 2,
    text: '玻璃球：黄 <strong>3</strong> 个、绿 <strong>4</strong> 个、红 <strong>5</strong> 个、蓝 <strong>8</strong> 个。至少拿多少个才能保证一定有 <strong>两种颜色</strong>？',
    analysis: [
      '最不利：全拿最多的一种（蓝 8 个）',
      '再拿 1 个必是另一种颜色',
      '8 + 1 = <strong>9</strong> 个',
    ],
    type: 'none',
    finalQ: '至少要拿几个？',
    finalUnit: '个',
    finalAns: 9,
  },
  {
    id: '46-L12',
    title: '例题5 · 游览鸟巢',
    tag: 'type6',
    tagLabel: '组合·完全相同',
    difficulty: 4,
    text: '<strong>32</strong> 名营员游览鸟巢、颐和园、长城 3 处，每人最少去 1 处、最多去 2 处。至少有几个人游览的地方 <strong>完全相同</strong>？',
    analysis: [
      '去 1 处有 3 种，去 2 处有 3 种，共 3 + 3 = 6 种方案（6 个抽屉）',
      '32 ÷ 6 = 5 …… 2，向上取整 = 6',
      '至少 <strong>6</strong> 个人完全相同',
    ],
    type: 'none',
    finalQ: '至少有几人完全相同？',
    finalUnit: '人',
    finalAns: 6,
  },
  {
    id: '46-L13',
    title: '练一练 · 报名项目',
    tag: 'type6',
    tagLabel: '组合·完全相同',
    difficulty: 4,
    text: '<strong>41</strong> 名同学参加运动会，项目有跳远、铅球、跳高、跑步 4 项，每人必须参加且最多参加 2 项。至少有几位同学报名的项目 <strong>完全相同</strong>？',
    analysis: [
      '参加 1 项有 4 种，参加 2 项有 6 种，共 4 + 6 = 10 种（10 个抽屉）',
      '41 ÷ 10 = 4 …… 1，向上取整 = 5',
      '至少 <strong>5</strong> 位同学完全相同',
    ],
    type: 'none',
    finalQ: '至少有几位完全相同？',
    finalUnit: '人',
    finalAns: 5,
  },
  {
    id: '46-L14',
    title: '例题6 · 三色手套都取到',
    tag: 'type4',
    tagLabel: '保证种类齐全',
    difficulty: 3,
    text: '红、黄、绿三种颜色的手套各 <strong>10</strong> 只（不分左右）。至少取多少只才能保证 <strong>三种颜色都取到</strong>？',
    analysis: [
      '最不利：取完两种颜色 = 10 + 10 = 20 只',
      '再取 1 只必是第三种颜色',
      '20 + 1 = <strong>21</strong> 只',
    ],
    type: 'none',
    finalQ: '至少要取几只？',
    finalUnit: '只',
    finalAns: 21,
  },
  {
    id: '46-L15',
    title: '例题6 · 保证 1 双红手套',
    tag: 'type5',
    tagLabel: '保证成双',
    difficulty: 4,
    text: '红、黄、绿三种颜色的手套各 <strong>10</strong> 只（不分左右）。至少取多少只才能保证有 <strong>1 双红色</strong>手套（2 只红即成 1 双）？',
    analysis: [
      '最不利：先取完所有非红色 = 10 + 10 = 20 只',
      '再取 2 只必都是红色，凑成 1 双',
      '20 + 2 = <strong>22</strong> 只',
    ],
    type: 'none',
    finalQ: '至少要取几只？',
    finalUnit: '只',
    finalAns: 22,
  },
  {
    id: '46-L16',
    title: '例题6 · 保证 2 双同色',
    tag: 'type5',
    tagLabel: '保证成双',
    difficulty: 4,
    text: '红、黄、绿三种颜色的手套各 <strong>10</strong> 只（不分左右）。至少取多少只才能保证有 <strong>2 双颜色相同</strong>的手套（同色 4 只 = 2 双）？',
    analysis: [
      '要 2 双同色 = 某种颜色取到 4 只',
      '最不利：每种颜色各取 3 只 = 3 × 3 = 9 只（每色都不足 4）',
      '再取 1 只必使某色达到 4 只：9 + 1 = <strong>10</strong> 只',
    ],
    type: 'none',
    finalQ: '至少要取几只？',
    finalUnit: '只',
    finalAns: 10,
  },
  {
    id: '46-L17',
    title: '练一练 · 四色袜子都取到',
    tag: 'type4',
    tagLabel: '保证种类齐全',
    difficulty: 3,
    text: '红、白、黑、绿四种颜色的袜子各 <strong>6</strong> 只（不分左右）。至少取多少只才能保证 <strong>四种颜色都取到</strong>？',
    analysis: [
      '最不利：取完三种颜色 = 6 × 3 = 18 只',
      '再取 1 只必是第四种颜色',
      '18 + 1 = <strong>19</strong> 只',
    ],
    type: 'none',
    finalQ: '至少要取几只？',
    finalUnit: '只',
    finalAns: 19,
  },
  {
    id: '46-L18',
    title: '练一练 · 保证 2 双同色袜',
    tag: 'type5',
    tagLabel: '保证成双',
    difficulty: 4,
    text: '红、白、黑、绿四种颜色的袜子各 <strong>6</strong> 只（不分左右）。至少取多少只才能保证有 <strong>2 双颜色相同</strong>的袜子（同色 4 只 = 2 双）？',
    analysis: [
      '要 2 双同色 = 某色取到 4 只',
      '最不利：每色各取 3 只 = 3 × 4 = 12 只',
      '再取 1 只必使某色达到 4 只：12 + 1 = <strong>13</strong> 只',
    ],
    type: 'none',
    finalQ: '至少要取几只？',
    finalUnit: '只',
    finalAns: 13,
  },
]

const HOMEWORK: Problem[] = [
  {
    id: '46-H1',
    title: '巩固1 · 同月出生',
    tag: 'type1',
    tagLabel: '抽屉原理',
    difficulty: 1,
    text: '一个小组共 <strong>19</strong> 个人，至少有多少个人在 <strong>同一个月</strong>出生？',
    analysis: [
      '一年 12 个月当作 12 个抽屉',
      '19 ÷ 12 = 1 …… 7，向上取整 = 2',
      '至少 <strong>2</strong> 人同月出生',
    ],
    type: 'none',
    finalQ: '至少几人同月出生？',
    finalUnit: '人',
    finalAns: 2,
  },
  {
    id: '46-H2',
    title: '巩固2 · 故事书放抽屉',
    tag: 'type1',
    tagLabel: '抽屉原理',
    difficulty: 2,
    text: '把 <strong>13</strong> 本故事书放到 <strong>5</strong> 个抽屉里，一定能找到一个故事书最多的抽屉，它里面至少有几本？',
    analysis: [
      '先每抽屉放 2 本 = 10 本，还剩 3 本',
      '13 ÷ 5 = 2 …… 3，向上取整 = 3',
      '至少 <strong>3</strong> 本',
    ],
    type: 'none',
    finalQ: '最多的抽屉里至少几本？',
    finalUnit: '本',
    finalAns: 3,
  },
  {
    id: '46-H3',
    title: '巩固3 · 4 张同花色',
    tag: 'type1',
    tagLabel: '抽屉原理',
    difficulty: 3,
    text: '一副扑克牌 54 张，至少摸出多少张才能保证有 <strong>4 张花色相同</strong>？（大、小王不算花色）',
    analysis: [
      '最不利：每种花色 3 张 = 3 × 4 = 12 张，再加 2 张王 = 14 张',
      '再摸 1 张必凑成 4 张同花色',
      '14 + 1 = <strong>15</strong> 张',
    ],
    type: 'none',
    finalQ: '至少要摸几张？',
    finalUnit: '张',
    finalAns: 15,
  },
  {
    id: '46-H4',
    title: '巩固4 · 3 条同品种鱼',
    tag: 'type1',
    tagLabel: '抽屉原理',
    difficulty: 3,
    text: '鱼缸里有红帽鱼、珍珠鱼、紫龙井鱼、绒球 <strong>4 个</strong>品种，至少捞出多少条才能保证有 <strong>3 条品种相同</strong>？',
    analysis: [
      '最不利：每品种 2 条 = 2 × 4 = 8 条',
      '再捞 1 条必凑成 3 条同品种',
      '8 + 1 = <strong>9</strong> 条',
    ],
    type: 'none',
    finalQ: '至少要捞几条？',
    finalUnit: '条',
    finalAns: 9,
  },
  {
    id: '46-H5',
    title: '巩固5 · 拿水果相同',
    tag: 'type6',
    tagLabel: '组合·完全相同',
    difficulty: 4,
    text: '篮子里有苹果、梨、桃、桔子。<strong>61</strong> 个小朋友每人任意拿 <strong>2 个</strong>水果（可拿相同的），至少有多少个小朋友拿的水果 <strong>相同</strong>？',
    analysis: [
      '从 4 种里拿 2 个（可重复）共 10 种搭配（10 个抽屉）',
      '61 ÷ 10 = 6 …… 1，向上取整 = 7',
      '至少 <strong>7</strong> 个小朋友相同',
    ],
    type: 'none',
    finalQ: '至少几个小朋友相同？',
    finalUnit: '人',
    finalAns: 7,
  },
  {
    id: '46-H6',
    title: '巩固6 · 保证 1 支红笔',
    tag: 'type3',
    tagLabel: '保证目标出现',
    difficulty: 3,
    text: '铅笔盒中有红笔 <strong>3</strong> 支、蓝笔 <strong>6</strong> 支、黑笔 <strong>10</strong> 支。随意抓一把要保证至少有 <strong>1 支红笔</strong>，最少要拿多少支？',
    analysis: [
      '最不利：把非红笔全拿完 = 6 + 10 = 16 支',
      '再拿 1 支必是红笔',
      '16 + 1 = <strong>17</strong> 支',
    ],
    type: 'none',
    finalQ: '最少要拿几支？',
    finalUnit: '支',
    finalAns: 17,
  },
]

const WORKBOOK: Problem[] = [
  {
    id: '46-W1',
    title: '闯关1 · 保证有白球',
    tag: 'type3',
    tagLabel: '保证目标出现',
    difficulty: 2,
    text: '口袋里有黑球 <strong>10</strong> 个、白球 <strong>5</strong> 个、红球 <strong>3</strong> 个。至少取出多少个才能保证其中 <strong>有白球</strong>？',
    analysis: [
      '最不利：把非白球全取完 = 10 + 3 = 13 个',
      '再取 1 个必是白球',
      '13 + 1 = <strong>14</strong> 个',
    ],
    type: 'none',
    finalQ: '至少要取几个？',
    finalUnit: '个',
    finalAns: 14,
  },
  {
    id: '46-W2',
    title: '闯关2 · 拿球种类一致',
    tag: 'type6',
    tagLabel: '组合·完全相同',
    difficulty: 4,
    text: '仓库有足球、排球、篮球。<strong>50</strong> 名同学每人至少拿 1 个、至多拿 2 个，至少有几名同学所拿的球 <strong>种类一致</strong>？',
    analysis: [
      '拿 1 个有 3 种，拿 2 个（可同种）有 6 种，共 3 + 6 = 9 种（9 个抽屉）',
      '50 ÷ 9 = 5 …… 5，向上取整 = 6',
      '至少 <strong>6</strong> 名同学一致',
    ],
    type: 'none',
    finalQ: '至少几名同学一致？',
    finalUnit: '人',
    finalAns: 6,
  },
  {
    id: '46-W3',
    title: '闯关3 · 2 个同味果冻',
    tag: 'type2',
    tagLabel: '保证两个相同',
    difficulty: 2,
    text: '盒子里果冻：苹果味 <strong>10</strong> 个、巧克力味 <strong>12</strong> 个、草莓味 <strong>18</strong> 个。至少取多少个才能保证有 <strong>2 个口味相同</strong>？',
    analysis: [
      '最不利：3 种各取 1 个 = 3 个',
      '再取 1 个必与某味相同',
      '3 + 1 = <strong>4</strong> 个',
    ],
    type: 'none',
    finalQ: '至少要取几个？',
    finalUnit: '个',
    finalAns: 4,
  },
  {
    id: '46-W4',
    title: '闯关4 · 2 条同品种鱼',
    tag: 'type2',
    tagLabel: '保证两个相同',
    difficulty: 2,
    text: '鱼缸里有甲、乙、丙三个品种的金鱼，每种各 <strong>8</strong> 条。小花猫至少吃多少条才能保证吃到 <strong>2 条品种相同</strong>的鱼？',
    analysis: [
      '最不利：3 种各吃 1 条 = 3 条',
      '再吃 1 条必与某种相同',
      '3 + 1 = <strong>4</strong> 条',
    ],
    type: 'none',
    finalQ: '至少要吃几条？',
    finalUnit: '条',
    finalAns: 4,
  },
  {
    id: '46-W5',
    title: '闯关5 · 保证 1 支绿笔',
    tag: 'type3',
    tagLabel: '保证目标出现',
    difficulty: 3,
    text: '红色铅笔 <strong>15</strong> 支、绿色 <strong>12</strong> 支、蓝色 <strong>18</strong> 支。一次至少取多少支才能保证一定有 <strong>1 支绿色</strong>？',
    analysis: [
      '最不利：把非绿色全取完 = 15 + 18 = 33 支',
      '再取 1 支必是绿色',
      '33 + 1 = <strong>34</strong> 支',
    ],
    type: 'none',
    finalQ: '至少要取几支？',
    finalUnit: '支',
    finalAns: 34,
  },
  {
    id: '46-W6',
    title: '闯关6 · 保证 1 双红袜',
    tag: 'type5',
    tagLabel: '保证成双',
    difficulty: 3,
    text: '红、绿、蓝、黄四种颜色的长筒袜各 <strong>10</strong> 只。至少摸出多少只才能保证一定有 <strong>1 双红色</strong>的袜子？',
    analysis: [
      '最不利：先摸完所有非红色 = 10 × 3 = 30 只',
      '再摸 2 只必都是红色，凑成 1 双',
      '30 + 2 = <strong>32</strong> 只',
    ],
    type: 'none',
    finalQ: '至少要摸几只？',
    finalUnit: '只',
    finalAns: 32,
  },
  {
    id: '46-W7',
    title: '闯关7 · 2 件同色衣服',
    tag: 'type2',
    tagLabel: '保证两个相同',
    difficulty: 2,
    text: '绿色衣服 <strong>10</strong> 件、白色 <strong>6</strong> 件、红色 <strong>7</strong> 件、蓝色 <strong>2</strong> 件。至少取多少件才能保证有 <strong>2 件颜色相同</strong>？',
    analysis: [
      '最不利：4 种颜色各取 1 件 = 4 件',
      '再取 1 件必与某色相同',
      '4 + 1 = <strong>5</strong> 件',
    ],
    type: 'none',
    finalQ: '至少要取几件？',
    finalUnit: '件',
    finalAns: 5,
  },
  {
    id: '46-W8',
    title: '闯关8 · 4 位同学礼物相同',
    tag: 'type6',
    tagLabel: '组合·完全相同',
    difficulty: 5,
    text: '礼物有橡皮、铅笔、故事书、拼图 4 种，每人任选 <strong>2 种</strong>（可选相同种）。至少有多少位同学才能保证一定有 <strong>4 位</strong>挑到的礼物种类 <strong>完全相同</strong>？',
    analysis: [
      '从 4 种里选 2 个（可重复）共 10 种搭配（10 个抽屉）',
      '要保证 4 位相同：最不利每种 3 位 = 3 × 10 = 30 位',
      '再来 1 位必凑成 4 位相同：30 + 1 = <strong>31</strong> 位',
    ],
    type: 'none',
    finalQ: '至少要几位同学？',
    finalUnit: '人',
    finalAns: 31,
  },
  {
    id: '46-W9',
    title: '闯关9 · 订阅种类相同',
    tag: 'type6',
    tagLabel: '组合·完全相同',
    difficulty: 5,
    text: '一年级 <strong>64</strong> 名同学，都订阅甲、乙、丙三种漫画中的 1 种、2 种或 3 种。至少有多少名学生订阅的 <strong>种类相同</strong>？',
    analysis: [
      '订 1 种 3 种、订 2 种 3 种、订 3 种 1 种，共 3 + 3 + 1 = 7 种（7 个抽屉）',
      '64 ÷ 7 = 9 …… 1，向上取整 = 10',
      '至少 <strong>10</strong> 名学生种类相同',
    ],
    type: 'none',
    finalQ: '至少几名学生相同？',
    finalUnit: '人',
    finalAns: 10,
  },
  {
    id: '46-W10',
    title: '闯关10 · 4 张同花色',
    tag: 'type1',
    tagLabel: '抽屉原理',
    difficulty: 3,
    text: '一副扑克牌 54 张（2 张王 + 4 种花色各 13 张）。要保证取出的牌中有 <strong>4 张花色相同</strong>，最少要取多少张？',
    analysis: [
      '最不利：每种花色 3 张 = 3 × 4 = 12 张，再加 2 张王 = 14 张',
      '再取 1 张必凑成 4 张同花色',
      '14 + 1 = <strong>15</strong> 张',
    ],
    type: 'none',
    finalQ: '至少要取几张？',
    finalUnit: '张',
    finalAns: 15,
  },
  {
    id: '46-W11',
    title: '闯关11 · 3 双同色手套',
    tag: 'type5',
    tagLabel: '保证成双',
    difficulty: 5,
    text: '白手套 <strong>5</strong> 只、黑 <strong>4</strong> 只、红 <strong>8</strong> 只、黄 <strong>10</strong> 只、绿 <strong>15</strong> 只。至少摸多少只才能保证有 <strong>颜色相同的三双</strong>（同色 6 只）？',
    analysis: [
      '三双同色 = 某色摸到 6 只。最不利：每色尽量摸到 5 只（不足 6）',
      '白 5 + 黑 4 + 红 5 + 黄 5 + 绿 5 = 24 只（黑只有 4 只）',
      '再摸 1 只必使某色达到 6 只：24 + 1 = <strong>25</strong> 只',
    ],
    type: 'none',
    finalQ: '至少要摸几只？',
    finalUnit: '只',
    finalAns: 25,
  },
  {
    id: '46-W12',
    title: '闯关11 · 3 双不同色手套',
    tag: 'type5',
    tagLabel: '保证成双',
    difficulty: 5,
    text: '白手套 <strong>5</strong> 只、黑 <strong>4</strong> 只、红 <strong>8</strong> 只、黄 <strong>10</strong> 只、绿 <strong>15</strong> 只。至少摸多少只才能保证有 <strong>颜色不同的三双</strong>（三种颜色各成 1 双）？',
    analysis: [
      '最不利：只让两种颜色成双，其余颜色各只摸 1 只',
      '绿 15 + 黄 10 全摸（两色成双）+ 白 1 + 黑 1 + 红 1 = 28 只',
      '再摸 1 只必让第三种颜色也成双：28 + 1 = <strong>29</strong> 只',
    ],
    type: 'none',
    finalQ: '至少要摸几只？',
    finalUnit: '只',
    finalAns: 29,
  },
  {
    id: '46-W13',
    title: '闯关12 · 汤圆 2 种馅',
    tag: 'type2',
    tagLabel: '保证两个相同',
    difficulty: 5,
    text: '汤圆：黑芝麻 <strong>1</strong>、花生 <strong>2</strong>、白糖 <strong>3</strong>、豆沙 <strong>8</strong>、山楂 <strong>10</strong>。约约至少吃多少个才能保证 <strong>至少吃到 2 种馅，且有一种馅至少吃了 2 个</strong>？',
    analysis: [
      '最不利：拼命只吃同一种最多的馅 → 全吃山楂 10 个（只有 1 种馅）',
      '此时已满足"一种馅 ≥ 2 个"，只差"第 2 种馅"',
      '再吃 1 个必是另一种馅：10 + 1 = <strong>11</strong> 个',
    ],
    type: 'none',
    finalQ: '至少要吃几个？',
    finalUnit: '个',
    finalAns: 11,
  },
]

const SUPPLEMENT: Problem[] = [
  {
    id: '46-S1',
    title: '附加题1 · 3 只动物买水果相同',
    tag: 'type6',
    tagLabel: '组合·完全相同',
    difficulty: 5,
    text: '超市有 A、B、C、D 四种水果，每只小动物任意买 <strong>2 种</strong>（可买相同种）。至少有多少只小动物才能保证一定有 <strong>3 只</strong>买的水果种类 <strong>完全相同</strong>？',
    analysis: [
      '从 4 种里买 2 个（可重复）共 10 种搭配（10 个抽屉）',
      '要保证 3 只相同：最不利每种 2 只 = 2 × 10 = 20 只',
      '再来 1 只必凑成 3 只相同：20 + 1 = <strong>21</strong> 只',
    ],
    type: 'none',
    finalQ: '至少要几只小动物？',
    finalUnit: '只',
    finalAns: 21,
  },
  {
    id: '46-S2',
    title: '附加题2 · 三花色各 3 张',
    tag: 'type4',
    tagLabel: '保证种类齐全',
    difficulty: 5,
    text: '一副扑克牌 54 张（2 张王 + 4 种花色各 13 张）。要保证取出的牌 <strong>至少含三种花色，且这三种花色都至少有 3 张</strong>，最少要取多少张？',
    analysis: [
      '最不利：让两种花色取满，另两种花色各只取 2 张，再加 2 张王',
      '13 + 13 + 2 + 2 + 2 = 32 张（此时只有 2 种花色 ≥ 3）',
      '再取 1 张必让第三种花色达到 3 张：32 + 1 = <strong>33</strong> 张',
    ],
    type: 'none',
    finalQ: '至少要取几张？',
    finalUnit: '张',
    finalAns: 33,
  },
]

export const PROBLEMS: ProblemSet = {
  pretest: PRETEST,
  lesson: LESSON,
  homework: HOMEWORK,
  workbook: WORKBOOK,
  supplement: SUPPLEMENT,
}

export const PROBLEM_TYPES = [
  {
    tag: 'type1',
    color: 'blue',
    label: '题型1 · 抽屉原理',
    desc: '物体数 ÷ 抽屉数，向上取整就是某个抽屉里至少的个数。',
    example: '例：10 个苹果放 9 个抽屉 → 至少 2 个',
  },
  {
    tag: 'type2',
    color: 'green',
    label: '题型2 · 保证两个相同',
    desc: '最不利：每种各取 1 个后再加 1，就一定有 2 个相同。',
    example: '例：4 种玩具 → 4 + 1 = 5 个',
  },
  {
    tag: 'type3',
    color: 'orange',
    label: '题型3 · 保证目标出现',
    desc: '最不利：把不要的全取完，再加 1（或加到目标张数）。',
    example: '例：保证有黄笔 → 取完非黄 + 1',
  },
  {
    tag: 'type4',
    color: 'purple',
    label: '题型4 · 保证种类齐全',
    desc: '最不利：取完数量最多的几种，再加 1 凑出新颜色。',
    example: '例：保证三种颜色 → 取完两种 + 1',
  },
  {
    tag: 'type5',
    color: 'red',
    label: '题型5 · 保证成双',
    desc: '成双 = 同色凑够 2、4、6 只；先排除干扰再凑双。',
    example: '例：保证 1 双红 → 取完非红 + 2',
  },
  {
    tag: 'type6',
    color: 'pink',
    label: '题型6 · 组合·完全相同',
    desc: '先数清所有搭配方案当抽屉，再用抽屉原理求人数。',
    example: '例：每人去 1~2 处 → 6 种方案',
  },
]

export const TYPE_STYLE: Record<
  string,
  { bg: string; border: string; titleColor: string; textColor: string }
> = {
  type1: { bg: 'bg-blue-50', border: 'border-l-blue-500', titleColor: 'text-blue-800', textColor: 'text-blue-900' },
  type2: { bg: 'bg-green-50', border: 'border-l-green-500', titleColor: 'text-green-800', textColor: 'text-green-900' },
  type3: { bg: 'bg-orange-50', border: 'border-l-orange-500', titleColor: 'text-orange-800', textColor: 'text-orange-900' },
  type4: { bg: 'bg-purple-50', border: 'border-l-purple-500', titleColor: 'text-purple-800', textColor: 'text-purple-900' },
  type5: { bg: 'bg-red-50', border: 'border-l-red-500', titleColor: 'text-red-800', textColor: 'text-red-900' },
  type6: { bg: 'bg-pink-50', border: 'border-l-pink-500', titleColor: 'text-pink-800', textColor: 'text-pink-900' },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-app-blue-light text-app-blue-dark',
  type2: 'bg-app-green-light text-app-green-dark',
  type3: 'bg-orange-100 text-orange-700',
  type4: 'bg-app-purple-light text-app-purple-dark',
  type5: 'bg-red-100 text-red-700',
  type6: 'bg-pink-100 text-pink-700',
}
