import type { Problem, ProblemSet } from '@rosie/core'

export const LESSON_TIP =
  '等量代换：把不同对象换成同一种再计算——先找代换关系，统一单位后求单一量。归一问题：先求「每份」或「每人每天」的效率，再按目标份数或时间计算；门、水管等反比例题先求总工作量（门·分钟、管·小时），再除以份数。'

export const TYPE_TIP: Record<string, string> = {
  type1: '等量代换——先写出 A=B 的关系，把题目统一成一种量；连环代换从最基础的量往上推。',
  type2: '消元求单价——对比两次购买，消去相同部分求单价；或整体缩小、相加找组合价。',
  type3: '直接归一——先求单一效率（每人每天、每小时、每趟），再乘或除得到答案。',
  type4: '反比例归一——门越多时间越短、管越多越快；先求总工作量，再除以份数。',
  type5: '综合应用——先统一量或求总量，再分步计算；一题多问时先理清各问关系。',
}

const LESSON: Problem[] = [
  {
    id: '51-L1',
    title: '例1 · 动物体重代换',
    tag: 'type1',
    tagLabel: '等量代换',
    difficulty: 2,
    text: '如果 <strong>2 只小狗</strong>的体重等于 <strong>3 只小猫</strong>的体重，<strong>1 只小猫</strong>的体重等于 <strong>3 只鸭子</strong>的体重，那么 <strong>81 只鸭子</strong>的体重等于多少只小狗的体重？',
    analysis: [
      '因为 1 猫 = 3 鸭，所以 3 猫 = 9 鸭',
      '已知 2 狗 = 3 猫，可以得出：2 狗 = 9 鸭',
      '扩大倍数：18 狗 = 81 鸭',
    ],
    type: 'none',
    finalQ: '81 只鸭子的体重等于',
    finalUnit: '只小狗',
    finalAns: 18,
  },
  {
    id: '51-L2',
    title: '练一练 · 西瓜菠萝柚子',
    tag: 'type1',
    tagLabel: '等量代换',
    difficulty: 2,
    text: '<strong>1 个西瓜</strong>的重量等于 <strong>2 个菠萝</strong>的重量，<strong>1 个菠萝</strong>的重量等于 <strong>2 个柚子</strong>的重量。<strong>1 个柚子</strong>重 <strong>400 克</strong>，那么 <strong>1 个西瓜</strong>重多少克？',
    analysis: [
      '因为 1 菠 = 2 柚，所以 2 菠 = 4 柚',
      '已知 1 西 = 2 菠，可以得出：1 西 = 4 柚',
      '西瓜总重量：4 × 400 = <strong>1600</strong>（克）',
    ],
    type: 'none',
    finalQ: '1 个西瓜重',
    finalUnit: '克',
    finalAns: 1600,
  },
  {
    id: '51-L3',
    title: '例2 · 买本子问题',
    tag: 'type1',
    tagLabel: '等量代换',
    difficulty: 3,
    text: '纳纳和约约一起到文具店买东西，两人一共带了 <strong>36 元</strong>。约约用他带的钱买了 <strong>6 个作文本</strong>，纳纳用他带的钱买了 <strong>12 个单线本</strong>，他们的钱都刚好花完。已知买 <strong>1 个作文本</strong>的钱恰好可以买 <strong>4 个单线本</strong>。纳纳和约约分别带了多少钱？如果约约改买单线本，纳纳改买作文本，那么两人一共将买到多少个本子？',
    analysis: [
      '钱数关系：6 作 + 12 单 = 36 元；代换：1 作 = 4 单，则 6 作 = 24 单',
      '24 单 + 12 单 = 36 元 → 1 个单线本 = 1 元，1 个作文本 = 4 元',
      '纳纳：12 × 1 = 12（元）；约约：6 × 4 = 24（元）',
      '改买后：约约 24÷1 = 24（个单线本），纳纳 12÷4 = 3（个作文本），共 24 + 3 = <strong>27</strong>（个）',
    ],
    type: 'none',
    finalQ: '改买后两人一共将买到',
    finalUnit: '个本子',
    finalAns: 27,
  },
  {
    id: '51-L4',
    title: '练一练 · 西瓜与榴莲',
    tag: 'type1',
    tagLabel: '等量代换',
    difficulty: 3,
    text: '甲乙两筐中一共有 <strong>208 斤</strong>水果。甲筐全是西瓜，一共有 <strong>20 个</strong>；乙筐中全是榴莲，一共有 <strong>12 个</strong>。已知 <strong>1 个西瓜</strong>的重量等于 <strong>2 个榴莲</strong>的重量，甲筐中有多少斤西瓜？乙筐中有多少斤榴莲？',
    analysis: [
      '因为 1 西 = 2 榴，所以 20 西 = 40 榴',
      '40 榴 + 12 榴 = 208 斤 → 1 个榴莲 = 4 斤，1 个西瓜 = 8 斤',
      '甲筐（西瓜）：20 × 8 = <strong>160</strong>（斤）；乙筐：12 × 4 = 48（斤）',
    ],
    type: 'none',
    finalQ: '甲筐中有',
    finalUnit: '斤西瓜',
    finalAns: 160,
  },
  {
    id: '51-L5',
    title: '例3 · 大小盘包子',
    tag: 'type1',
    tagLabel: '等量代换',
    difficulty: 3,
    text: '功夫熊猫一连吃了 <strong>100 个包子</strong>，其中有 <strong>4 大盘</strong>，还有 <strong>10 小盘</strong>。如果 <strong>3 大盘</strong>里的包子个数等于 <strong>5 小盘</strong>里的包子个数，那么 <strong>1 大盘和 1 小盘</strong>共有多少个包子？',
    analysis: [
      '已知 3 大 = 5 小，两边同时乘 2 得：6 大 = 10 小',
      '4 大 + 10 小 = 100 个 → 4 大 + 6 大 = 100 → 1 大盘 = 10 个',
      '10 小 = 6 大 = 60 个 → 1 小盘 = 6 个；1 大 + 1 小 = 10 + 6 = <strong>16</strong>（个）',
    ],
    type: 'none',
    finalQ: '1 大盘和 1 小盘共有',
    finalUnit: '个包子',
    finalAns: 16,
  },
  {
    id: '51-L6',
    title: '例4 · 师徒组装零件',
    tag: 'type1',
    tagLabel: '等量代换',
    difficulty: 4,
    text: '师傅和两个徒弟一起组装零件，师傅组装 <strong>5 个</strong>与大徒弟组装 <strong>3 个</strong>所用的时间相同，而大徒弟组装 <strong>5 个</strong>与小徒弟组装 <strong>2 个</strong>所用的时间相同。小徒弟组装 <strong>6 个</strong>的时间，师傅能装几个零件？',
    analysis: [
      '师 5 个 = 大 3 个（×5：师 25 个 = 大 15 个）',
      '大 5 个 = 小 2 个（×3：大 15 个 = 小 6 个）',
      '通过「大徒弟 15 个」建立桥梁：师 25 个 = 小 6 个',
    ],
    type: 'none',
    finalQ: '小徒弟组装 6 个的时间师傅能装',
    finalUnit: '个零件',
    finalAns: 25,
  },
  {
    id: '51-L7',
    title: '例5 · 足球和篮球价格',
    tag: 'type2',
    tagLabel: '消元求单价',
    difficulty: 3,
    text: '学校买来一些足球和篮球。已知买 <strong>3 个足球和 5 个篮球</strong>共花了 <strong>281 元</strong>；买 <strong>3 个足球和 7 个篮球</strong>共花了 <strong>355 元</strong>。现在要买 <strong>5 个足球、4 个篮球</strong>共花多少元？',
    analysis: [
      '数量差：2 篮 = 355 − 281 = 74 元 → 1 个篮球 = 37 元',
      '3 个足球 = 281 − 5×37 = 96 元 → 1 个足球 = 32 元',
      '5×32 + 4×37 = 160 + 148 = <strong>308</strong>（元）',
    ],
    type: 'none',
    finalQ: '5 个足球、4 个篮球共花',
    finalUnit: '元',
    finalAns: 308,
  },
  {
    id: '51-L8',
    title: '例6 · 笔袋与圆珠笔',
    tag: 'type2',
    tagLabel: '消元求单价',
    difficulty: 3,
    text: '纳纳买了 <strong>2 个笔袋、3 支圆珠笔</strong>，用去 <strong>25 元</strong>；约约买了 <strong>1 个笔袋、2 支圆珠笔</strong>，用去 <strong>14 元</strong>。买 <strong>1 个笔袋、1 支圆珠笔</strong>分别需要多少元？',
    analysis: [
      '算式差：(2 袋+3 笔)−(1 袋+2 笔) = 25−14 → 1 袋+1 笔 = 11 元',
      '(1 袋+2 笔)−(1 袋+1 笔) = 14−11 → 1 支圆珠笔 = 3 元',
      '1 个笔袋 = 11 − 3 = <strong>8</strong>（元）',
    ],
    type: 'none',
    finalQ: '1 个笔袋需要',
    finalUnit: '元',
    finalAns: 8,
  },
  {
    id: '51-L9',
    title: '例7 · 工人生产零件',
    tag: 'type3',
    tagLabel: '归一问题',
    difficulty: 3,
    text: '汽车厂 <strong>3 名工人</strong>每天生产汽车零件 <strong>36 个</strong>。按照这样的速度，<strong>11 名工人 2 天</strong>能生产多少个零件？如果要用 <strong>5 天</strong>的时间生产出 <strong>1200 个</strong>零件，那么需要多少名工人？',
    analysis: [
      '单人单日效率：36 ÷ 3 = 12（个/人·天）',
      '11 名工人 2 天：12 × 11 × 2 = 264（个）',
      '5 天人均产量 = 12 × 5 = 60（个/人）；需要人数 = 1200 ÷ 60 = <strong>20</strong>（名）',
    ],
    type: 'none',
    finalQ: '5 天生产 1200 个零件需要',
    finalUnit: '名工人',
    finalAns: 20,
  },
  {
    id: '51-L10',
    title: '练一练 · 学生植树挖坑',
    tag: 'type3',
    tagLabel: '归一问题',
    difficulty: 2,
    text: '<strong>30 名</strong>同学去植树，每小时能挖 <strong>60 个</strong>树坑。按照这样的速度，<strong>60 名同学 4 小时</strong>能挖多少个坑？如果要用 <strong>3 小时</strong>挖出 <strong>600 个</strong>坑，需要多少名学生？',
    analysis: [
      '单人单小时效率：60 ÷ 30 = 2（个/人·小时）',
      '60 名同学 4 小时：2 × 60 × 4 = 480（个）',
      '3 小时单人挖坑 = 2 × 3 = 6（个/人）；需要人数 = 600 ÷ 6 = <strong>100</strong>（名）',
    ],
    type: 'none',
    finalQ: '3 小时挖 600 个坑需要',
    finalUnit: '名学生',
    finalAns: 100,
  },
]

const HOMEWORK: Problem[] = [
  {
    id: '51-H1',
    title: '练习1 · 连环代换',
    tag: 'type1',
    tagLabel: '等量代换',
    difficulty: 3,
    text: '<strong>1 个西瓜</strong>的重量等于 <strong>3 个哈密瓜</strong>的重量，<strong>1 个哈密瓜</strong>的重量等于 <strong>5 个小凤梨</strong>的重量，<strong>1 个小凤梨</strong>的重量等于 <strong>4 个荔枝</strong>的重量。已知一个荔枝重 <strong>100 克</strong>，那么 <strong>1 个西瓜</strong>重多少克？',
    analysis: [
      '1 个小凤梨 = 4×100 = 400 克',
      '1 个哈密瓜 = 5×400 = 2000 克',
      '1 个西瓜 = 3×2000 = <strong>6000</strong> 克',
    ],
    type: 'none',
    finalQ: '1 个西瓜重',
    finalUnit: '克',
    finalAns: 6000,
  },
  {
    id: '51-H2',
    title: '练习2 · 计算题量代换',
    tag: 'type1',
    tagLabel: '等量代换',
    difficulty: 3,
    text: '小纳在十一假期完成 <strong>240 道</strong>计算题。其中有 <strong>4 篇加减法</strong>计算，还有 <strong>9 篇乘除法</strong>计算。如果 <strong>2 篇加减法</strong>计算的题量等于 <strong>3 篇乘除法</strong>计算的题量，那么 <strong>1 篇加减法</strong>和 <strong>1 篇乘除法</strong>分别有多少道计算题？',
    analysis: [
      '4 篇加减法 = 6 篇乘除法；共 6 + 9 = 15 篇乘除法',
      '1 篇乘除法 = 240 ÷ 15 = 16 道',
      '2 篇加减法 = 3×16 = 48 道 → 1 篇加减法 = <strong>24</strong> 道',
    ],
    type: 'none',
    finalQ: '1 篇加减法计算有',
    finalUnit: '道题',
    finalAns: 24,
  },
  {
    id: '51-H3',
    title: '练习3 · 荔枝与黄杏',
    tag: 'type1',
    tagLabel: '等量代换',
    difficulty: 4,
    text: '甲乙两筐中一共有 <strong>48 千克</strong>水果。甲筐全是荔枝，一共有 <strong>246 个</strong>；乙筐中全是黄杏，一共有 <strong>177 个</strong>。已知 <strong>1 个黄杏</strong>的重量等于 <strong>2 个荔枝</strong>的重量，甲筐中有多少克荔枝？乙筐中有多少克黄杏？',
    analysis: [
      '总重量 48 千克 = 48000 克',
      '246 个荔枝 = 123 个黄杏；共 123 + 177 = 300 个黄杏',
      '1 个黄杏 = 48000 ÷ 300 = 160 克；1 个荔枝 = 80 克',
      '甲筐：80×246 = <strong>19680</strong> 克；乙筐：160×177 = 28320 克',
    ],
    type: 'none',
    finalQ: '甲筐中有',
    finalUnit: '克荔枝',
    finalAns: 19680,
  },
  {
    id: '51-H4',
    title: '练习4 · 水果糖与巧克力',
    tag: 'type2',
    tagLabel: '消元求单价',
    difficulty: 3,
    text: '小约买来一些水果糖和巧克力。已知买 <strong>10 个水果糖和 15 个巧克力</strong>共花了 <strong>17 元</strong>；买 <strong>10 个水果糖和 20 个巧克力</strong>共花了 <strong>21 元</strong>。现在要买 <strong>6 个水果糖、6 个巧克力</strong>共花多少钱？',
    analysis: [
      '巧克力多了 5 个，多花 4 元 → 1 个巧克力 = 0.8 元',
      '10 个水果糖 = 17 − 15×0.8 = 5 元 → 1 个水果糖 = 0.5 元',
      '6×(0.5+0.8) = <strong>7.8</strong> 元',
    ],
    type: 'none',
    finalQ: '6 个水果糖、6 个巧克力共花',
    finalUnit: '元',
    finalAns: 7.8,
  },
  {
    id: '51-H5',
    title: '练习5 · 张师傅加工零件',
    tag: 'type3',
    tagLabel: '归一问题',
    difficulty: 2,
    text: '张师傅 <strong>5 小时</strong>能加工 <strong>200 个</strong>零件，那么他 <strong>6 小时</strong>能加工多少个零件？他加工 <strong>440 个</strong>零件需要多少小时？',
    analysis: [
      '每小时加工：200 ÷ 5 = 40 个',
      '6 小时：40×6 = 240 个',
      '440 个需要：440 ÷ 40 = <strong>11</strong> 小时',
    ],
    type: 'none',
    finalQ: '加工 440 个零件需要',
    finalUnit: '小时',
    finalAns: 11,
  },
  {
    id: '51-H6',
    title: '练习6 · 卡车运沙石',
    tag: 'type3',
    tagLabel: '归一问题',
    difficulty: 4,
    text: '<strong>10 辆卡车 10 趟</strong>可以运走沙石 <strong>10 吨</strong>，那么 <strong>60 辆卡车 60 趟</strong>可以运走沙石多少吨？<strong>5 辆卡车</strong>要运走 <strong>20 吨</strong>沙石，需要多少趟？',
    analysis: [
      '1 辆车 1 趟运 10÷10÷10 = 1/10 吨',
      '60 辆×60 趟 = 360 吨',
      '5 辆车 1 趟运 0.5 吨；运 20 吨需要 20÷0.5 = <strong>40</strong> 趟',
    ],
    type: 'none',
    finalQ: '5 辆卡车运 20 吨需要',
    finalUnit: '趟',
    finalAns: 40,
  },
  {
    id: '51-H7',
    title: '练习7 · 橙子苹果梨',
    tag: 'type2',
    tagLabel: '消元求单价',
    difficulty: 3,
    text: '小明买了 <strong>10 个橙子和 5 个苹果</strong>花了 <strong>50 元</strong>，小红买了 <strong>5 个橙子和 5 个梨</strong>花了 <strong>25 元</strong>，那么小立买了 <strong>5 个橙子、2 个苹果、1 个梨</strong>花了多少钱？',
    analysis: [
      '小明组合÷5：2 橙+1 苹果 = 10 元；小红组合÷5：1 橙+1 梨 = 5 元',
      '小立买 5 橙+2 苹果+1 梨 = 2×(2橙+1苹果) + 1×(1橙+1梨)',
      '2×10 + 5 = <strong>25</strong> 元',
    ],
    type: 'none',
    finalQ: '小立共花',
    finalUnit: '元',
    finalAns: 25,
  },
  {
    id: '51-H8',
    title: '练习8 · 钢笔铅笔本子',
    tag: 'type2',
    tagLabel: '消元求单价',
    difficulty: 3,
    text: '思思买了 <strong>10 支钢笔和 20 支铅笔</strong>，一共花了 <strong>300 元</strong>，辰辰买了 <strong>10 支钢笔和 20 个本</strong>也花了 <strong>300 元</strong>，那么买 <strong>1 支钢笔、1 支铅笔、1 个本</strong>要花多少元？',
    analysis: [
      '思思账单÷10：1 钢笔+2 铅笔 = 30 元；辰辰账单÷10：1 钢笔+2 本 = 30 元',
      '两式相加：2 钢笔+2 铅笔+2 本 = 60 元',
      '÷2：1 钢笔+1 铅笔+1 本 = <strong>30</strong> 元',
    ],
    type: 'none',
    finalQ: '买 1 钢笔、1 铅笔、1 本要花',
    finalUnit: '元',
    finalAns: 30,
  },
  {
    id: '51-H9',
    title: '练习9 · 甲乙做题比赛',
    tag: 'type3',
    tagLabel: '归一问题',
    difficulty: 4,
    text: '甲乙两人一起比赛做题，甲 <strong>5 分钟</strong>可以做 <strong>3 道题</strong>，乙每 <strong>5 分钟</strong>比甲少做 <strong>1 道题</strong>，一共有 <strong>100 道题</strong>，甲先做 <strong>50 分钟</strong>，乙还需要做多少分钟？',
    analysis: [
      '乙 5 分钟做 2 道题',
      '甲 50 分钟做 10×3 = 30 道；剩下 70 道由乙完成',
      '70÷2 = 35 组，每组 5 分钟 → 35×5 = <strong>175</strong> 分钟',
    ],
    type: 'none',
    finalQ: '乙还需要做',
    finalUnit: '分钟',
    finalAns: 175,
  },
  {
    id: '51-H10',
    title: '练习10 · 分水果',
    tag: 'type5',
    tagLabel: '综合应用',
    difficulty: 4,
    text: '有一批水果，每人分 <strong>6 个梨和 3 个苹果</strong>，可以分给 <strong>27 个人</strong>。如果先给 <strong>12 个人</strong>分 <strong>2 个梨和 1 个苹果</strong>，剩下的水果仍然每人分 <strong>6 个梨和 3 个苹果</strong>，还能分多少人？',
    analysis: [
      '梨总数：27×6 = 162；苹果总数：27×3 = 81',
      '剩下梨：162−12×2 = 138；剩下苹果：81−12×1 = 69',
      '138÷6 = 69÷3 = <strong>23</strong> 人',
    ],
    type: 'none',
    finalQ: '还能分给',
    finalUnit: '人',
    finalAns: 23,
  },
  {
    id: '51-H11',
    title: '练习11 · 水池排水',
    tag: 'type4',
    tagLabel: '反比例归一',
    difficulty: 4,
    text: '有一个水池，有 <strong>6 根出水管</strong>，每根管子出水量相同。如果打开 <strong>2 根出水管</strong>，<strong>12 小时</strong>可以排干一半的水，那么打开 <strong>4 根出水管</strong>，用多久能排干整池水？',
    analysis: [
      '2 根管 12 小时排一半 → 排整池需 24 小时（2 根管）',
      '管子从 2 根变 4 根，效率翻倍，时间减半',
      '24 ÷ 2 = <strong>12</strong> 小时',
    ],
    type: 'none',
    finalQ: '4 根出水管排干整池水需要',
    finalUnit: '小时',
    finalAns: 12,
  },
  {
    id: '51-H12',
    title: '练习12 · 博物馆开门',
    tag: 'type4',
    tagLabel: '反比例归一',
    difficulty: 3,
    text: '博物馆一共有 <strong>10 个门</strong>，如果打开 <strong>3 个门</strong>，<strong>24 分钟</strong>博物馆的人就会达到上限。如果打开 <strong>6 个门</strong>，需要多久会达到人数上限？如果打开 <strong>9 个门</strong>呢？',
    analysis: [
      '总工作量：3×24 = 72（门·分钟）',
      '6 个门：72÷6 = 12 分钟',
      '9 个门：72÷9 = <strong>8</strong> 分钟',
    ],
    type: 'none',
    finalQ: '打开 9 个门需要',
    finalUnit: '分钟',
    finalAns: 8,
  },
  {
    id: '51-H13',
    title: '练习13 · 摘桃子',
    tag: 'type3',
    tagLabel: '归一问题',
    difficulty: 2,
    text: '小明和小红去摘桃子，两个人 <strong>10 分钟</strong>可以摘 <strong>20 个桃子</strong>，那么摘 <strong>50 个桃子</strong>要多久？摘 <strong>50 分钟</strong>可以摘多少桃子？',
    analysis: [
      '2 人组合每分钟摘 20÷10 = 2 个',
      '摘 50 个：50÷2 = 25 分钟',
      '摘 50 分钟：50×2 = <strong>100</strong> 个',
    ],
    type: 'none',
    finalQ: '摘 50 分钟可以摘',
    finalUnit: '个桃子',
    finalAns: 100,
  },
  {
    id: '51-H14',
    title: '练习14 · 工人制作零件',
    tag: 'type3',
    tagLabel: '归一问题',
    difficulty: 3,
    text: '<strong>5 名工人 7 天</strong>可以制作 <strong>15 个零件</strong>，那么 <strong>35 名工人 13 天</strong>可以制作多少个零件？',
    analysis: [
      '工人扩大 35÷5 = 7 倍；天数扩大 13÷7 倍',
      '15×7÷7×13 = 15×13 = <strong>195</strong> 个',
    ],
    type: 'none',
    finalQ: '35 名工人 13 天可以制作',
    finalUnit: '个零件',
    finalAns: 195,
  },
]

const PRETEST: Problem[] = [
  { id: '51-P1', title: '课前测1 · 猫狗鸡', tag: 'type1', tagLabel: '等量代换', difficulty: 2, text: '两只猫的重量等于三只狗，一只狗等于四只鸡。一只猫等于几只鸡？', analysis: ['1 狗=4 鸡，2 猫=3 狗=12 鸡', '1 猫 = <strong>6</strong> 只鸡'], type: 'none', finalQ: '一只猫等于', finalUnit: '只鸡', finalAns: 6 },
  { id: '51-P2', title: '课前测2 · 大盘小盘', tag: 'type1', tagLabel: '等量代换', difficulty: 3, text: '<strong>8</strong> 个大盘和 <strong>13</strong> 个小盘共装 <strong>100</strong> 个苹果，<strong>2</strong> 个大盘与 <strong>3</strong> 个小盘一样多。每个大盘装多少个？', analysis: ['2 大=3 小，8 大=12 小', '25 小=100，大 = <strong>6</strong> 个'], type: 'none', finalQ: '每个大盘', finalUnit: '个', finalAns: 6 },
  { id: '51-P3', title: '课前测3 · 租公寓', tag: 'type2', tagLabel: '消元求单价', difficulty: 3, text: '租 3 月普通房+5 月标准房=2810 元；租 3 月普通房+8 月标准房=3920 元。租半年标准房和半年普通房共花多少元？', analysis: ['标准 370 元/月，普通 320 元/月', '6×(320+370) = <strong>4140</strong> 元'], type: 'none', finalQ: '共花', finalUnit: '元', finalAns: 4140 },
  { id: '51-P4', title: '课前测4 · 水果价', tag: 'type2', tagLabel: '消元求单价', difficulty: 3, text: '买 2 斤苹果+4 斤菠萝=14 元；买 3 斤苹果+2 斤菠萝=13 元。1 斤苹果+1 斤菠萝多少钱？', analysis: ['苹果 3 元/斤，菠萝 2 元/斤', '1+1 = <strong>5</strong> 元'], type: 'none', finalQ: '共', finalUnit: '元', finalAns: 5 },
  { id: '51-P5', title: '课前测5 · 植树', tag: 'type3', tagLabel: '归一问题', difficulty: 2, text: '<strong>5</strong> 个人 <strong>2</strong> 小时植树 <strong>20</strong> 棵，<strong>6</strong> 个人 <strong>3</strong> 小时植树多少棵？', analysis: ['1 人 1 时 2 棵', '6×3×2 = <strong>36</strong> 棵'], type: 'none', finalQ: '植树', finalUnit: '棵', finalAns: 36 },
  { id: '51-P6', title: '课前测6 · 加工零件', tag: 'type3', tagLabel: '归一问题', difficulty: 3, text: '<strong>3</strong> 名工人 <strong>5</strong> 小时加工 <strong>90</strong> 个零件，要在 <strong>10</strong> 小时完成 <strong>540</strong> 个，需要工人多少名？', analysis: ['1 人 1 时 6 个', '540÷(10×6) = <strong>9</strong> 名'], type: 'none', finalQ: '需要', finalUnit: '名', finalAns: 9 },
]

export const PROBLEMS: ProblemSet = {
  pretest: PRETEST,
  lesson: LESSON,
  homework: HOMEWORK,
  workbook: [],
}

export const PROBLEM_TYPES = [
  {
    tag: 'type1',
    color: 'blue',
    label: '题型1 · 等量代换',
    desc: '利用 A=B 的关系，把不同对象统一成同一种量再计算。',
    example: '例：2狗=3猫，1猫=3鸭',
  },
  {
    tag: 'type2',
    color: 'green',
    label: '题型2 · 消元求单价',
    desc: '对比两次购买消去相同部分，或整体缩小、相加求组合价。',
    example: '例：多买5个巧克力多花4元',
  },
  {
    tag: 'type3',
    color: 'orange',
    label: '题型3 · 归一问题',
    desc: '先求单一效率（每人每天、每小时），再乘或除得答案。',
    example: '例：3人每天36个→11人2天',
  },
  {
    tag: 'type4',
    color: 'purple',
    label: '题型4 · 反比例归一',
    desc: '门越多时间越短；先求总工作量，再除以份数。',
    example: '例：3门24分钟→9门8分钟',
  },
  {
    tag: 'type5',
    color: 'red',
    label: '题型5 · 综合应用',
    desc: '先求总量，再分步计算；多条件综合判断。',
    example: '例：先分一批再按标准分',
  },
]

export const TYPE_STYLE: Record<
  string,
  { bg: string; border: string; titleColor: string; textColor: string }
> = {
  type1: { bg: 'bg-blue-50', border: 'border-l-blue-500', titleColor: 'text-blue-800', textColor: 'text-blue-900' },
  type2: { bg: 'bg-green-50', border: 'border-l-green-500', titleColor: 'text-green-800', textColor: 'text-green-900' },
  type3: { bg: 'bg-orange-50', border: 'border-l-orange-500', titleColor: 'text-orange-800', textColor: 'text-orange-900' },
  type4: { bg: 'bg-purple-50', border: 'border-l-purple-500', titleColor: 'text-purple-800', textColor: 'text-purple-900' },
  type5: { bg: 'bg-red-50', border: 'border-l-red-500', titleColor: 'text-red-800', textColor: 'text-red-900' },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-app-blue-light text-app-blue-dark',
  type2: 'bg-app-green-light text-app-green-dark',
  type3: 'bg-orange-100 text-orange-700',
  type4: 'bg-app-purple-light text-app-purple-dark',
  type5: 'bg-red-100 text-red-700',
}
