import type { WordEntry } from './type'

export const SAMPLE_WORDS: WordEntry[] = [
  {
    unit: 'Unit 1', lesson: 'Lesson 1', word: 'a great time',
    explanation: 'a fun and happy time doing something you enjoy',
    ipa: '/ə ɡreɪt taɪm/',
    example: 'We had a great time at the theme park yesterday.',
  },
  {
    unit: 'Unit 1', lesson: 'Lesson 1', word: 'laugh',
    explanation: 'to make the sounds and movements of your face that show you think something is funny or silly',
    ipa: '/lɑːf/',
    example: 'The funny video made everyone laugh out loud.',
  },
  {
    unit: 'Unit 1', lesson: 'Lesson 1', word: 'enjoy',
    explanation: 'to have fun or feel happy when doing something',
    ipa: '/ɪnˈdʒɔɪ/',
    example: 'I really enjoy reading books on rainy days.',
  },
  {
    unit: 'Unit 1', lesson: 'Lesson 1', word: 'grandchild',
    explanation: 'a child of your son or daughter',
    ipa: '/ˈɡræntʃaɪld/',
    example: 'She is the youngest grandchild in the family.',
  },
  {
    unit: 'Unit 1', lesson: 'Lesson 1', word: 'lazy',
    explanation: 'unwilling to work or be active; doing as little as possible',
    ipa: '/ˈleɪzi/',
    example: 'He was too lazy to clean his room all week.',
  },
  {
    unit: 'Unit 1', lesson: 'Lesson 1', word: 'nephew',
    explanation: 'the son of your brother or sister',
    ipa: '/ˈnefjuː/',
    example: 'My nephew is six years old and loves dinosaurs.',
  },
  {
    unit: 'Unit 1', lesson: 'Lesson 1', word: 'niece',
    explanation: 'the daughter of your brother or sister',
    ipa: '/niːs/',
    example: 'I bought a birthday present for my niece.',
  },
  {
    unit: 'Unit 1', lesson: 'Lesson 1', word: 'waste',
    explanation: 'to use too much of something or use something badly when there is a limited amount of it',
    ipa: '/weɪst/',
    example: "Don't waste water — turn off the tap when you brush your teeth.",
  },
  {
    unit: 'Unit 1', lesson: 'Lesson 2', word: 'population',
    explanation: 'a particular group of people or animals living in a particular area',
    ipa: '/ˌpɒpjuˈleɪʃn/',
    example: 'The population of our city has grown a lot in recent years.',
  },
  {
    unit: 'Unit 1', lesson: 'Lesson 2', word: 'protect',
    explanation: 'to make sure that somebody/something is not harmed, injured, damaged, etc.',
    ipa: '/prəˈtekt/',
    example: 'We should protect wild animals from hunters.',
  },
  {
    unit: 'Unit 1', lesson: 'Lesson 2', word: 'danger',
    explanation: 'the possibility of something happening that will injure, harm or kill somebody, or damage or destroy something',
    ipa: '/ˈdeɪndʒər/',
    example: 'The hikers were in danger when the storm suddenly started.',
  },
  {
    unit: 'Unit 2', lesson: 'Lesson 1', word: 'careful',
    explanation: 'giving attention or thought to what you are doing so that you avoid hurting yourself, damaging something or doing something wrong',
    ipa: '/ˈkeərfl/',
    example: 'Be careful when you cross the road.',
  },
  {
    unit: 'Unit 2', lesson: 'Lesson 1', word: 'hate',
    explanation: 'to dislike somebody/something very much',
    ipa: '/heɪt/',
    example: 'I hate getting up early on cold mornings.',
  },
  {
    unit: 'Unit 2', lesson: 'Lesson 1', word: 'furniture',
    explanation: 'objects that can be moved, such as tables, chairs and beds, that are put into a house or an office to make it suitable for living or working in',
    ipa: '/ˈfɜːrnɪtʃər/',
    example: 'They bought some new furniture for the bedroom.',
  },
]

export const SYLLABLE_MAP: Record<string, string[]> = {
  laugh: ['laugh'], enjoy: ['en', 'joy'], grandchild: ['grand', 'child'], lazy: ['la', 'zy'],
  nephew: ['neph', 'ew'], niece: ['niece'], waste: ['waste'], population: ['pop', 'u', 'la', 'tion'],
  hunt: ['hunt'], hurt: ['hurt'], protect: ['pro', 'tect'], danger: ['dan', 'ger'], kill: ['kill'],
  reach: ['reach'], livestock: ['live', 'stock'], roar: ['roar'],
  conservationist: ['con', 'ser', 'va', 'tion', 'ist'], frightening: ['fright', 'en', 'ing'],
  initiative: ['i', 'ni', 'tia', 'tive'], million: ['mil', 'lion'], affect: ['af', 'fect'],
  diver: ['di', 'ver'], pay: ['pay'], save: ['save'], awful: ['aw', 'ful'], careful: ['care', 'ful'],
  hate: ['hate'], rich: ['rich'], armchair: ['arm', 'chair'], fridge: ['fridge'], oven: ['o', 'ven'],
  shower: ['show', 'er'], sink: ['sink'], sofa: ['so', 'fa'], toilet: ['toi', 'let'],
  wardrobe: ['ward', 'robe'], furniture: ['fur', 'ni', 'ture'], glass: ['glass'], modern: ['mod', 'ern'],
  plastic: ['plas', 'tic'], reuse: ['re', 'use'], rubbish: ['rub', 'bish'], earthquake: ['earth', 'quake'],
  balcony: ['bal', 'co', 'ny'], bookcase: ['book', 'case'], floor: ['floor'], roof: ['roof'], rug: ['rug'],
  recycle: ['re', 'cy', 'cle'], ecological: ['e', 'co', 'log', 'i', 'cal'], type: ['type'],
  appliance: ['ap', 'pli', 'ance'], late: ['late'], deep: ['deep'], wrong: ['wrong'], dive: ['dive'],
  equipment: ['e', 'quip', 'ment'], explore: ['ex', 'plore'], hobby: ['hob', 'by'], sure: ['sure'],
  trick: ['trick'], hill: ['hill'], pull: ['pull'], rope: ['rope'], slide: ['slide'], bored: ['bored'],
  boring: ['bor', 'ing'], excited: ['ex', 'cit', 'ed'], exciting: ['ex', 'cit', 'ing'],
  interested: ['in', 'ter', 'est', 'ed'], interesting: ['in', 'ter', 'est', 'ing'],
  relaxed: ['re', 'laxed'], relaxing: ['re', 'lax', 'ing'], tired: ['tired'], tiring: ['tir', 'ing'],
  pastime: ['pas', 'time'], blog: ['blog'], code: ['code'], post: ['post'], link: ['link'],
  comment: ['com', 'ment'], disgusting: ['dis', 'gust', 'ing'], delicious: ['de', 'li', 'cious'],
  full: ['full'], thirsty: ['thirs', 'ty'], altogether: ['al', 'to', 'geth', 'er'],
  buffet: ['buf', 'fet'], lobby: ['lob', 'by'], meat: ['meat'], healthy: ['health', 'y'],
  pot: ['pot'], raw: ['raw'], sauce: ['sauce'], seafood: ['sea', 'food'], soup: ['soup'],
  add: ['add'], boil: ['boil'], chop: ['chop'], fry: ['fry'], mix: ['mix'], slice: ['slice'],
  dip: ['dip'], dish: ['dish'], pan: ['pan'], gently: ['gent', 'ly'], recipe: ['rec', 'i', 'pe'],
  remove: ['re', 'move'], pour: ['pour'], serving: ['serv', 'ing'], tablespoon: ['ta', 'ble', 'spoon'],
  consume: ['con', 'sume'], reject: ['re', 'ject'], bell: ['bell'], canteen: ['can', 'teen'],
  magazine: ['mag', 'a', 'zine'], sweatshirt: ['sweat', 'shirt'], break: ['break'], term: ['term'],
  cheat: ['cheat'], fair: ['fair'], strict: ['strict'], test: ['test'], fencing: ['fenc', 'ing'],
  exam: ['ex', 'am'], discuss: ['dis', 'cuss'], friendship: ['friend', 'ship'],
  understanding: ['un', 'der', 'stand', 'ing'], education: ['ed', 'u', 'ca', 'tion'], marks: ['marks'],
  report: ['re', 'port'], natural: ['nat', 'u', 'ral'], solve: ['solve'], path: ['path'],
  imagine: ['i', 'mag', 'ine'], interview: ['in', 'ter', 'view'], project: ['pro', 'ject'],
  brilliant: ['bril', 'liant'], earache: ['ear', 'ache'], cough: ['cough'], headache: ['head', 'ache'],
  sneeze: ['sneeze'], ache: ['ache'], toothache: ['tooth', 'ache'],
  thermometer: ['ther', 'mom', 'e', 'ter'], temperature: ['tem', 'per', 'a', 'ture'], ankle: ['an', 'kle'],
  chest: ['chest'], elbow: ['el', 'bow'], knee: ['knee'], shoulder: ['shoul', 'der'],
  stomach: ['stom', 'ach'], tail: ['tail'], stump: ['stump'], common: ['com', 'mon'], virus: ['vi', 'rus'],
  throat: ['throat'], bleed: ['bleed'], injure: ['in', 'jure'], lungs: ['lungs'], mummy: ['mum', 'my'],
  ill: ['ill'], weak: ['weak'], skin: ['skin'], sore: ['sore'], tattoo: ['tat', 'too'],
  ancient: ['an', 'cient'], mystery: ['mys', 'ter', 'y'], discovery: ['dis', 'cov', 'er', 'y'],
  arrowhead: ['ar', 'row', 'head'], perhaps: ['per', 'haps'], living: ['liv', 'ing'],
  pollinate: ['pol', 'li', 'nate'], active: ['ac', 'tive'], honeycomb: ['hon', 'ey', 'comb'],
  screen: ['screen'], beehive: ['bee', 'hive'], hydrated: ['hy', 'drat', 'ed'],
  especially: ['es', 'pe', 'cial', 'ly'], stretch: ['stretch'],
}

export const KW_MAP: Record<string, [string, string][]> = {
  'a great time': [['fun and happy', 'kw-red']],
  'Look at the time!': [['surprise', 'kw-red'], ['later than expected', 'kw-gold']],
  'on time': [['correct time', 'kw-red'], ['not late', 'kw-gold']],
  'waste (one\'s) time': [['not useful or fun', 'kw-red']],
  'time for': [['right or planned moment', 'kw-red']],
  laugh: [['funny or silly', 'kw-red']],
  enjoy: [['fun or feel happy', 'kw-red']],
  grandchild: [['child of your son or daughter', 'kw-red']],
  lazy: [['unwilling to work', 'kw-red'], ['as little as possible', 'kw-gold']],
  'only child': [['no brothers or sisters', 'kw-red']],
  nephew: [['son', 'kw-red'], ['brother or sister', 'kw-blue']],
  niece: [['daughter', 'kw-red'], ['brother or sister', 'kw-blue']],
  waste: [['use too much', 'kw-red'], ['limited amount', 'kw-gold']],
  population: [['group of people or animals', 'kw-red'], ['particular area', 'kw-blue']],
  hunt: [['wild animals', 'kw-blue'], ['catch or kill', 'kw-red']],
  hurt: [['physical pain', 'kw-red'], ['injure', 'kw-gold']],
  protect: [['not harmed, injured, damaged', 'kw-red']],
  danger: [['injure, harm or kill', 'kw-red'], ['possibility', 'kw-gold']],
  kill: [['die', 'kw-red']],
  'care for': [['look after', 'kw-red'], ['sick', 'kw-gold']],
  'frightened of': [['scared or afraid', 'kw-red']],
  'in fact': [['extra details', 'kw-red']],
  'look after': [['responsible', 'kw-red'], ['take care', 'kw-gold']],
  reach: [['attention', 'kw-red']],
  livestock: [['animals kept on a farm', 'kw-red']],
  roar: [['loud deep sound', 'kw-red'], ['lion', 'kw-blue']],
  'big cat': [['large wild animal', 'kw-red'], ['cat family', 'kw-blue']],
  conservationist: [['protection of the environment', 'kw-red']],
  frightening: [['feel afraid', 'kw-red']],
  initiative: [['new plan', 'kw-red'], ['particular problem', 'kw-blue']],
  million: [['1,000,000', 'kw-red']],
  affect: [['produce a change', 'kw-red']],
  diver: [['swims underwater', 'kw-red'], ['special equipment', 'kw-blue']],
  pay: [['give somebody money', 'kw-red'], ['work, goods, services', 'kw-blue']],
  'save (money)': [['keep money', 'kw-red'], ['instead of spending', 'kw-gold']],
  awful: [['very bad or unpleasant', 'kw-red']],
  careful: [['avoid hurting', 'kw-red'], ['attention or thought', 'kw-gold']],
  hate: [['dislike', 'kw-red'], ['very much', 'kw-gold']],
  rich: [['a lot of money or property', 'kw-red']],
  armchair: [['comfortable chair', 'kw-red'], ['rest your arms', 'kw-gold']],
  'coffee table': [['small low table', 'kw-red'], ['in front of a sofa', 'kw-blue']],
  fridge: [['food is kept cold', 'kw-red'], ['stays fresh', 'kw-gold']],
  oven: [['food is cooked or heated', 'kw-red'], ['box with a door', 'kw-blue']],
  shower: [['flow of water', 'kw-blue'], ['wash yourself', 'kw-red']],
  sink: [['washing dishes', 'kw-red'], ['kitchen', 'kw-blue']],
  sofa: [['comfortable seat', 'kw-red'], ['two or more people', 'kw-gold']],
  toilet: [['get rid of waste matter', 'kw-red'], ['body', 'kw-blue']],
  wardrobe: [['hanging clothes', 'kw-red'], ['cupboard', 'kw-blue']],
  furniture: [['tables, chairs and beds', 'kw-blue'], ['house or office', 'kw-red']],
  glass: [['hard', 'kw-gold'], ['clear', 'kw-red'], ['windows and bottles', 'kw-blue']],
  modern: [['latest technology', 'kw-red']],
  plastic: [['light strong material', 'kw-red'], ['chemical processes', 'kw-blue']],
  reuse: [['use something again', 'kw-red']],
  rubbish: [['throw away', 'kw-red'], ['no longer want or need', 'kw-gold']],
  earthquake: [['violent shaking', 'kw-red'], ['earth', 'kw-blue']],
  recycle: [['already been used', 'kw-gold'], ['used again', 'kw-red']],
  ecological: [['plants and living creatures', 'kw-blue'], ['environment', 'kw-red']],
  type: [['kind or sort', 'kw-red']],
  deep: [['large distance', 'kw-gold'], ['top or surface to the bottom', 'kw-red']],
  wrong: [['not as it should be', 'kw-red'], ['problems or difficulties', 'kw-gold']],
  dive: [['jump into water', 'kw-red'], ['head and arms going in first', 'kw-gold']],
  equipment: [['things that are needed', 'kw-red'], ['particular purpose or activity', 'kw-blue']],
  explore: [['travel', 'kw-gold'], ['learn about it', 'kw-red']],
  hobby: [['pleasure', 'kw-red'], ['not working', 'kw-gold']],
  sure: [['confident', 'kw-red'], ['you are right', 'kw-gold']],
  boring: [['not interesting', 'kw-red'], ['tired and impatient', 'kw-gold']],
  excited: [['happiness and enthusiasm', 'kw-red']],
  exciting: [['great interest or excitement', 'kw-red']],
  interesting: [['special, exciting or unusual', 'kw-red']],
  brilliant: [['very good', 'kw-red']],
}
