import type { Problem, ProblemSet } from './type'
import PretestFig4 from '@/components/math/lesson44/Figure/PretestFig4'
import LessonFig6 from '@/components/math/lesson44/Figure/LessonFig6'
import LessonFig12 from '@/components/math/lesson44/Figure/LessonFig12'
import HomeworkFig5 from '@/components/math/lesson44/Figure/HomeworkFig5'
import WorkbookFig9 from '@/components/math/lesson44/Figure/WorkbookFig9'

const PRETEST: Problem[] = [
  {
    id: '44-P1',
    title: '课前测1 · 打扫卫生',
    tag: 'type1',
    tagLabel: '合理安排时间',
    difficulty: 2,
    text: '欣欣和妈妈打扫卫生，每件事由一个人完成。扫地 <strong>5</strong> 分钟，擦地 <strong>10</strong> 分钟，洗拖鞋 <strong>8</strong> 分钟，洗衣 <strong>25</strong> 分钟，晾衣 <strong>3</strong> 分钟，铺床 <strong>15</strong> 分钟，扔垃圾 <strong>5</strong> 分钟。她们最少需要多长时间做完？',
    analysis: [
      '欣欣：扫地 5 + 擦地 10 + 扔垃圾 5 = 20 分钟，再铺床 15 → 35 分钟',
      '妈妈：洗拖鞋 8 + 洗衣 25（8 分起）+ 晾衣 3 → 36 分钟',
      '两人并行，总时间取较长者 → <strong>36</strong> 分钟',
    ],
    type: 'none',
    finalQ: '最少需要多长时间？',
    finalUnit: '分钟',
    finalAns: 36,
  },
  {
    id: '44-P2',
    title: '课前测2 · 农夫过河',
    tag: 'type4',
    tagLabel: '过河问题',
    difficulty: 3,
    text: '农夫带 <strong>1</strong> 条狗、<strong>1</strong> 只兔子和 <strong>1</strong> 筐青菜过河，船每次只能带一样东西，带一样过河 <strong>2</strong> 分钟，空船 <strong>1</strong> 分钟。狗会咬兔，兔会吃菜。农夫最少花多少时间全部安全带过河？',
    analysis: [
      '带兔过河（2）→ 空船回（1）',
      '带狗过河（2）→ 带兔回（2）',
      '带菜过河（2）→ 空船回（1）',
      '带兔过河（2）→ 共 <strong>12</strong> 分钟',
    ],
    type: 'none',
    finalQ: '最少花多少分钟？',
    finalUnit: '分钟',
    finalAns: 12,
  },
  {
    id: '44-P3',
    title: '课前测3 · 打开水',
    tag: 'type2',
    tagLabel: '等候时间最短',
    difficulty: 2,
    text: '甲、乙、丙分别拿 <strong>2</strong>、<strong>3</strong>、<strong>1</strong> 个热水瓶同时到达，每次打满一瓶水需 <strong>1</strong> 分钟，水龙头只有一个。怎样安排顺序使总时间（含等候）最少？',
    analysis: [
      '用时短的先打：丙 → 甲 → 乙',
      '总时间 = 1×3 + 2×2 + 3×1 = 3 + 4 + 3 = <strong>10</strong> 分钟',
    ],
    type: 'none',
    finalQ: '总时间最少是多少分钟？',
    finalUnit: '分钟',
    finalAns: 10,
  },
  {
    id: '44-P4',
    title: '课前测4 · 最短路径',
    tag: 'type6',
    tagLabel: '最短路径',
    difficulty: 3,
    text: '下图是道路图，每段路旁数字表示优优走这段路所需的分钟数。优优从 <strong>A</strong> 出发走到 <strong>B</strong> 最快需要多少分钟？',
    analysis: [
      '路线 A→下→中→B：3 + 2 + 3 = 8',
      '路线 A→上→中→B：4 + 2 + 3 = 9',
      '最快 <strong>8</strong> 分钟',
    ],
    type: 'none',
    figureNode: <PretestFig4 />,
    finalQ: '最快需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 8,
  },
  {
    id: '44-P5',
    title: '课前测5 · 猎人过河',
    tag: 'type4',
    tagLabel: '过河问题',
    difficulty: 4,
    text: '猎人带 <strong>3</strong> 条狗和 <strong>2</strong> 只松鼠过河，船最多带 <strong>2</strong> 只动物，带一只 <strong>2</strong> 分钟，带两只 <strong>3</strong> 分钟，空船 <strong>1</strong> 分钟。狗会咬松鼠。猎人最少花多少时间全部安全带过河？',
    analysis: [
      '2 只松鼠先过河（3）→ 猎人回（1）',
      '2 只狗过河（3）→ 1 只狗回（2）',
      '2 只松鼠再过河（3）→ 1 只松鼠回（2）',
      '2 只狗再过河（3）→ 最后 1 狗 + 1 松鼠过河（3）',
      '共 <strong>17</strong> 分钟',
    ],
    type: 'none',
    finalQ: '最少花多少分钟？',
    finalUnit: '分钟',
    finalAns: 17,
  },
]

const LESSON: Problem[] = [
  {
    id: '44-L1',
    title: '例1 · 冲牛奶',
    tag: 'type1',
    tagLabel: '合理安排时间',
    difficulty: 2,
    text: '洗水壶要 <strong>1</strong> 分钟，洗杯子和勺子各要 <strong>1</strong> 分钟，烧开水要 <strong>11</strong> 分钟，取奶粉 <strong>2</strong> 分钟，冲奶粉 <strong>1</strong> 分钟。怎样安排才能尽快喝上牛奶？',
    analysis: [
      '先洗水壶 <strong>1</strong> 分钟，再烧水 <strong>11</strong> 分钟',
      '烧水时同时洗杯、洗勺（共 2 分钟）并取奶粉（2 分钟）',
      '水开后冲奶粉 <strong>1</strong> 分钟 → 最少 <strong>13</strong> 分钟',
    ],
    type: 'none',
    finalQ: '最少需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 13,
  },
  {
    id: '44-L2',
    title: '练一练 · 榨果汁',
    tag: 'type1',
    tagLabel: '合理安排时间',
    difficulty: 2,
    text: '摘果子 <strong>5</strong> 分钟，洗果子 <strong>2</strong> 分钟，洗杯子 <strong>3</strong> 分钟，榨汁 <strong>4</strong> 分钟，倒果汁 <strong>1</strong> 分钟。怎样安排时间最短？',
    analysis: [
      '先摘果子 5 分钟，再洗果子 2 分钟',
      '榨汁 4 分钟的同时洗杯子 3 分钟',
      '最后倒果汁 1 分钟 → <strong>12</strong> 分钟',
    ],
    type: 'none',
    finalQ: '最少需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 12,
  },
  {
    id: '44-L3',
    title: '例2 · 四人用水',
    tag: 'type2',
    tagLabel: '等候时间最短',
    difficulty: 3,
    text: '甲洗拖把 <strong>5</strong> 分钟，乙洗抹布 <strong>2</strong> 分钟，丙接水 <strong>1</strong> 分钟，丁洗衣服 <strong>15</strong> 分钟。怎样安排用水顺序，使四人花的总时间（含等候）最少？',
    analysis: [
      '用时短的先进行：丙 → 乙 → 甲 → 丁',
      '总时间 = 1×4 + 2×3 + 5×2 + 15×1 = <strong>35</strong> 分钟',
    ],
    type: 'none',
    finalQ: '总时间最少是多少分钟？',
    finalUnit: '分钟',
    finalAns: 35,
  },
  {
    id: '44-L4',
    title: '练一练 · 三人看病',
    tag: 'type2',
    tagLabel: '等候时间最短',
    difficulty: 2,
    text: '小立打针 <strong>5</strong> 分钟，小纳换纱布 <strong>3</strong> 分钟，小约点眼药水 <strong>1</strong> 分钟。怎样安排次序使总时间最少？',
    analysis: [
      '顺序：小约 → 小纳 → 小立',
      '总时间 = 1×3 + 3×2 + 5×1 = <strong>14</strong> 分钟',
    ],
    type: 'none',
    finalQ: '总时间最少是多少分钟？',
    finalUnit: '分钟',
    finalAns: 14,
  },
  {
    id: '44-L5',
    title: '例3 · 两面刷漆',
    tag: 'type3',
    tagLabel: '刷漆晾晒',
    difficulty: 3,
    text: '一面刷漆要 <strong>1</strong> 分钟，必须等 <strong>5</strong> 分钟漆干才能刷另一面。漆完 <strong>5</strong> 块小木板至少需要多少分钟？',
    analysis: [
      '先连续刷 5 块的第一面（5 分钟）',
      '利用晾干时间穿插刷背面，流水线作业',
      '漆完 5 块最少 <strong>11</strong> 分钟（6 块 13 分钟，11 块 23 分钟）',
    ],
    type: 'none',
    finalQ: '漆完 5 块至少需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 11,
  },
  {
    id: '44-L6',
    title: '练一练 · 木板刷漆',
    tag: 'type3',
    tagLabel: '刷漆晾晒',
    difficulty: 3,
    text: '一面刷漆要 <strong>2</strong> 分钟，必须等 <strong>7</strong> 分钟漆干才能刷另一面。漆完 <strong>4</strong> 块小木板至少需要多少分钟？',
    analysis: [
      '先刷 4 块第一面（8 分钟）',
      '第一块晾干后刷背面，依次流水线',
      '最少 <strong>17</strong> 分钟',
    ],
    type: 'none',
    finalQ: '漆完 4 块至少需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 17,
  },
  {
    id: '44-L7',
    title: '例4 · 赶牛过河',
    tag: 'type4',
    tagLabel: '过河问题',
    difficulty: 3,
    text: '甲牛 <strong>1</strong> 分、乙牛 <strong>2</strong> 分、丙牛 <strong>5</strong> 分、丁牛 <strong>6</strong> 分过河，每次最多赶两头且需骑牛。把 4 头牛都赶到对岸最少要多少分钟？',
    analysis: [
      '甲+乙过河（2）→ 甲返回（1）→ 丙+丁过河（6）→ 乙返回（2）→ 甲+乙过河（2）',
      '最少 <strong>13</strong> 分钟',
    ],
    type: 'none',
    finalQ: '最少要用多少分钟？',
    finalUnit: '分钟',
    finalAns: 13,
  },
  {
    id: '44-L8',
    title: '练一练 · 三头牛过河',
    tag: 'type4',
    tagLabel: '过河问题',
    difficulty: 3,
    text: '大牛 <strong>2</strong> 分、中牛 <strong>4</strong> 分、小牛 <strong>7</strong> 分过河，每次最多两头。三头牛都过河最少要多少分钟？',
    analysis: [
      '大牛+中牛过河（4）→ 大牛返回（2）→ 大牛+小牛过河（7）→ 大牛返回（2）→ 大牛+中牛过河（4）',
      '最少 <strong>19</strong> 分钟',
    ],
    type: 'none',
    finalQ: '最少要用多少分钟？',
    finalUnit: '分钟',
    finalAns: 19,
  },
  {
    id: '44-L9',
    title: '例5 · 烙饼问题',
    tag: 'type5',
    tagLabel: '烙饼问题',
    difficulty: 2,
    text: '平底锅每次最多放 <strong>2</strong> 张饼，烙熟 1 张需 <strong>4</strong> 分钟（正反面各 2 分钟）。烙熟 <strong>3</strong> 张饼至少需要多少分钟？',
    analysis: [
      '0–2 分：饼 A 正面、饼 B 正面',
      '2–4 分：饼 A 反面、饼 C 正面',
      '4–6 分：饼 B 反面、饼 C 反面',
      '最少 <strong>6</strong> 分钟',
    ],
    type: 'none',
    finalQ: '烙熟 3 张饼至少需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 6,
  },
  {
    id: '44-L10',
    title: '练一练 · 煎牛排',
    tag: 'type5',
    tagLabel: '烙饼问题',
    difficulty: 3,
    text: '平底锅每次最多 <strong>2</strong> 块牛排，煎熟 1 块需 <strong>6</strong> 分钟（正反面各 3 分钟）。煎熟 <strong>7</strong> 块至少需要多少分钟？',
    analysis: [
      '每块需煎两面，锅每次煎 2 面',
      '7 块共 14 个面，每次煎 2 面需 3 分钟',
      '14 ÷ 2 × 3 = <strong>21</strong> 分钟',
    ],
    type: 'none',
    finalQ: '煎熟 7 块至少需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 21,
  },
  {
    id: '44-L11',
    title: '例6 · 最短路径',
    tag: 'type6',
    tagLabel: '最短路径',
    difficulty: 3,
    text: '下图是从纳纳家到游乐场的道路示意图，每段路上的数字表示所需时间（分钟）。纳纳从家到游乐场最快要多少分钟？',
    analysis: [
      '比较各条路线：家→上→中→游乐场 = 3+2+4 = 9',
      '家→下→中→游乐场 = 6+1+2 = 9',
      '家→上→下→游乐场 = 3+4+2 = 9',
      '最快 <strong>9</strong> 分钟',
    ],
    type: 'none',
    figureNode: <LessonFig6 />,
    finalQ: '最快要多少分钟？',
    finalUnit: '分钟',
    finalAns: 9,
  },
  {
    id: '44-L12',
    title: '练一练 · 校园最短路径',
    tag: 'type6',
    tagLabel: '最短路径',
    difficulty: 3,
    text: '下图是某大学平面图，小约从 A 到 B 取快递，每段路上的数字表示所需时间（分钟）。小约至少需要多少分钟？',
    analysis: [
      '路线 A→下→中→B：2+3+2 = 7',
      '路线 A→上→中→B：4+1+2 = 7',
      '最快 <strong>7</strong> 分钟',
    ],
    type: 'none',
    figureNode: <LessonFig12 />,
    finalQ: '至少需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 7,
  },
]

const HOMEWORK: Problem[] = [
  {
    id: '44-H1',
    title: '巩固1 · 早晨安排',
    tag: 'type1',
    tagLabel: '合理安排时间',
    difficulty: 2,
    text: '叠被子 <strong>2</strong> 分，刷牙洗脸 <strong>5</strong> 分，烤面包 <strong>11</strong> 分，吃面包 <strong>8</strong> 分，整理书包 <strong>3</strong> 分。小婷怎样安排能最快做完？',
    analysis: [
      '烤面包 11 分钟时叠被子+刷牙（7 分钟）',
      '吃面包 8 分钟时整理书包 3 分钟',
      '最少 <strong>19</strong> 分钟',
    ],
    type: 'none',
    finalQ: '最少用多少分钟？',
    finalUnit: '分钟',
    finalAns: 19,
  },
  {
    id: '44-H2',
    title: '巩固2 · 理发店排队',
    tag: 'type2',
    tagLabel: '等候时间最短',
    difficulty: 3,
    text: '五位顾客理发分别需 <strong>10、12、15、20、24</strong> 分钟。怎样安排顺序使五人理发和等候总时间最短？',
    analysis: [
      '按用时从短到长排列',
      '总时间 = 10×5 + 12×4 + 15×3 + 20×2 + 24×1 = <strong>207</strong> 分钟',
    ],
    type: 'none',
    finalQ: '最短总时间是多少分钟？',
    finalUnit: '分钟',
    finalAns: 207,
  },
  {
    id: '44-H3',
    title: '巩固3 · 涂贺卡',
    tag: 'type3',
    tagLabel: '刷漆晾晒',
    difficulty: 3,
    text: '涂 1 面要 <strong>2</strong> 分钟，必须等 <strong>13</strong> 分钟颜料干才能涂另一面。涂完 <strong>7</strong> 张贺卡最少要多少分钟？',
    analysis: [
      '先连续涂 7 张正面（14 分钟）',
      '利用晾干时间流水线涂背面',
      '最少 <strong>29</strong> 分钟',
    ],
    type: 'none',
    finalQ: '最少要多少分钟？',
    finalUnit: '分钟',
    finalAns: 29,
  },
  {
    id: '44-H4',
    title: '巩固4 · 烙11张饼',
    tag: 'type5',
    tagLabel: '烙饼问题',
    difficulty: 3,
    text: '平底锅每次放 <strong>2</strong> 张饼，烙 1 张需 <strong>2</strong> 分钟（正反面各 1 分钟）。烙 <strong>11</strong> 张饼至少需要多少分钟？',
    analysis: [
      '11 张饼共 22 个面，每次烙 2 面需 1 分钟',
      '22 ÷ 2 = <strong>11</strong> 分钟',
    ],
    type: 'none',
    finalQ: '至少需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 11,
  },
  {
    id: '44-H5',
    title: '巩固5 · 森林路径',
    tag: 'type6',
    tagLabel: '最短路径',
    difficulty: 3,
    text: '下图是光头强从家到森林的道路图，每段数字表示所需时间（分钟）。光头强从家到森林最少要多少时间？',
    analysis: [
      '路线 家→下→中→森林：2+2+4 = 8',
      '比经上路更快',
      '最少 <strong>8</strong> 分钟',
    ],
    type: 'none',
    figureNode: <HomeworkFig5 />,
    finalQ: '最少要多少分钟？',
    finalUnit: '分钟',
    finalAns: 8,
  },
  {
    id: '44-H6',
    title: '巩固6 · 三人过桥',
    tag: 'type4',
    tagLabel: '过河问题',
    difficulty: 4,
    text: '甲需 <strong>3</strong> 分、乙需 <strong>5</strong> 分、丙需 <strong>7</strong> 分过桥，桥每次最多 2 人，只有一只手电筒。三人全部过桥最少要多少分钟？',
    analysis: [
      '甲+乙先过河（5）→ 甲返回（3）→ 甲+丙过河（7）',
      '乙在起点等待，甲再返回接乙',
      '最优策略下全部过河最少 <strong>15</strong> 分钟',
    ],
    type: 'none',
    finalQ: '三人全部过桥最少要多少分钟？',
    finalUnit: '分钟',
    finalAns: 15,
  },
]

const WORKBOOK: Problem[] = [
  {
    id: '44-W1',
    title: '闯关1 · 泡感冒药',
    tag: 'type1',
    tagLabel: '合理安排时间',
    difficulty: 2,
    text: '倒开水 <strong>1</strong> 分，等开水变温 <strong>6</strong> 分，找药 <strong>1</strong> 分，量体温 <strong>5</strong> 分。怎样安排让小红最快吃完药休息？',
    analysis: ['倒开水 1 分 → 等 6 分（同时找药 1 分+量体温 5 分）→ 吃药', '最少 <strong>7</strong> 分钟'],
    type: 'none',
    finalQ: '最少需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 7,
  },
  {
    id: '44-W2',
    title: '闯关2 · 沏茶',
    tag: 'type1',
    tagLabel: '合理安排时间',
    difficulty: 3,
    text: '洗水壶 <strong>2</strong> 分，烧水 <strong>15</strong> 分，洗茶壶 <strong>3</strong> 分，洗茶杯 <strong>5</strong> 分，拿茶叶 <strong>2</strong> 分，沏茶 <strong>1</strong> 分。怎样安排时间最短？',
    analysis: [
      '洗壶 2 分 → 烧水 15 分（同时洗壶壶、洗杯、拿茶共 10 分）→ 沏茶 1 分',
      '最少 <strong>18</strong> 分钟',
    ],
    type: 'none',
    finalQ: '最少需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 18,
  },
  {
    id: '44-W3',
    title: '闯关3 · 买零食排队',
    tag: 'type2',
    tagLabel: '等候时间最短',
    difficulty: 2,
    text: '甲买零食 <strong>15</strong> 分，乙 <strong>6</strong> 分，丙 <strong>3</strong> 分。怎样安排购买顺序使总时间最少？',
    analysis: ['顺序：丙 → 乙 → 甲', '总时间 = 3×3 + 6×2 + 15×1 = <strong>36</strong> 分钟'],
    type: 'none',
    finalQ: '总时间最少是多少分钟？',
    finalUnit: '分钟',
    finalAns: 36,
  },
  {
    id: '44-W4',
    title: '闯关4 · 接水排队',
    tag: 'type2',
    tagLabel: '等候时间最短',
    difficulty: 3,
    text: '悦悦接水 <strong>3</strong> 分，苗苗 <strong>8</strong> 分，立立 <strong>5</strong> 分。怎样安排接水顺序使等候总时间最少？',
    analysis: ['顺序：悦悦 → 立立 → 苗苗', '总时间 = 3×3 + 5×2 + 8×1 = <strong>27</strong> 分钟'],
    type: 'none',
    finalQ: '等候总时间最少是多少分钟？',
    finalUnit: '分钟',
    finalAns: 27,
  },
  {
    id: '44-W5',
    title: '闯关5 · 煎10条鱼',
    tag: 'type5',
    tagLabel: '烙饼问题',
    difficulty: 3,
    text: '平底锅每次煎 <strong>2</strong> 条鱼，煎 1 条需 <strong>4</strong> 分钟（正反面各 2 分钟）。煎 <strong>10</strong> 条鱼至少需要多少分钟？',
    analysis: ['10 条共 20 个面，每次煎 2 面需 2 分钟', '20 ÷ 2 × 2 = <strong>20</strong> 分钟'],
    type: 'none',
    finalQ: '至少需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 20,
  },
  {
    id: '44-W6',
    title: '闯关6 · 不对称烙饼',
    tag: 'type5',
    tagLabel: '烙饼问题',
    difficulty: 4,
    text: '锅中每次最多 <strong>2</strong> 个饼，烙第一面 <strong>4</strong> 分，第二面 <strong>3</strong> 分。烙好 <strong>5</strong> 张饼最少需要多少分钟？',
    analysis: [
      '合理安排翻面顺序，避免锅空等',
      '5 张饼最少约 <strong>20</strong> 分钟',
    ],
    type: 'none',
    finalQ: '最少需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 20,
  },
  {
    id: '44-W7',
    title: '闯关7 · 刷油桶',
    tag: 'type3',
    tagLabel: '刷漆晾晒',
    difficulty: 4,
    text: '两个漆工给 <strong>3</strong> 个油桶内外刷漆，每面各需 <strong>5</strong> 分钟。怎样安排刷漆时间最少？',
    analysis: [
      '3 桶 × 2 面 = 6 面次，两名漆工同时工作',
      '合理安排内外面交替，最少 <strong>15</strong> 分钟',
    ],
    type: 'none',
    finalQ: '最少需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 15,
  },
  {
    id: '44-W8',
    title: '闯关8 · 五马过河',
    tag: 'type4',
    tagLabel: '过河问题',
    difficulty: 5,
    text: '五匹马过河分别需 <strong>2、4、5、7、8</strong> 分钟，每次最多赶 <strong>3</strong> 匹。全部过河最少要多少分钟？',
    analysis: [
      '每次带最慢的几匹马中较快的组合返回',
      '经典策略下最少约 <strong>17</strong> 分钟',
    ],
    type: 'none',
    finalQ: '最少要多少分钟？',
    finalUnit: '分钟',
    finalAns: 17,
  },
  {
    id: '44-W9',
    title: '闯关9 · 上学路径',
    tag: 'type6',
    tagLabel: '最短路径',
    difficulty: 3,
    text: '下图是小纳从家到学校的道路图，每段数字表示所需时间（分钟）。最快需要多少分钟？',
    analysis: [
      '路线 家→下→中→学校：3+4+1 = 8',
      '路线 家→上→中→学校：5+2+1 = 8',
      '最快 <strong>8</strong> 分钟',
    ],
    type: 'none',
    figureNode: <WorkbookFig9 />,
    finalQ: '最快需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 8,
  },
  {
    id: '44-W10',
    title: '闯关10 · 师徒过河',
    tag: 'type4',
    tagLabel: '过河问题',
    difficulty: 3,
    text: '沙僧划船 <strong>2</strong> 分，猪八戒 <strong>3</strong> 分，唐僧 <strong>5</strong> 分，小船每次坐 <strong>2</strong> 人。三人全部过河最少要多少分钟？',
    analysis: [
      '沙+猪过河（3）→ 沙返回（2）→ 沙+唐过河（5）→ 沙返回（2）→ 沙+猪过河（3）',
      '最少 <strong>15</strong> 分钟',
    ],
    type: 'none',
    finalQ: '最少要多少分钟？',
    finalUnit: '分钟',
    finalAns: 15,
  },
  {
    id: '44-W11',
    title: '闯关11 · 四人过桥',
    tag: 'type4',
    tagLabel: '过河问题',
    difficulty: 4,
    text: '甲 <strong>2</strong> 分、乙 <strong>3</strong> 分、丙 <strong>8</strong> 分、丁 <strong>10</strong> 分过桥，每次最多 2 人，只有一个手电筒。最短要多少分钟？',
    analysis: [
      '甲+乙过河（3）→ 甲返回（2）→ 丙+丁过河（10）→ 乙返回（3）→ 甲+乙过河（3）',
      '最少 <strong>21</strong> 分钟',
    ],
    type: 'none',
    finalQ: '最短要多少分钟？',
    finalUnit: '分钟',
    finalAns: 21,
  },
  {
    id: '44-W12',
    title: '闯关12 · 贴奖状',
    tag: 'type1',
    tagLabel: '合理安排时间',
    difficulty: 4,
    text: '涂胶水 <strong>2</strong> 分，等 <strong>2</strong> 分才能贴，贴 <strong>1</strong> 分；超过 <strong>6</strong> 分胶水会干。贴完 <strong>5</strong> 张奖状最快要多少分钟？',
    analysis: [
      '流水线：涂胶与等待、粘贴交替进行',
      '5 张奖状最快约 <strong>12</strong> 分钟',
    ],
    type: 'none',
    finalQ: '最快要多少分钟？',
    finalUnit: '分钟',
    finalAns: 12,
  },
]

const SUPPLEMENT: Problem[] = [
  {
    id: '44-S1',
    title: '附加1 · 独木桥',
    tag: 'type4',
    tagLabel: '过河问题',
    difficulty: 4,
    text: '天天 <strong>10</strong> 分、小妍 <strong>15</strong> 分、小冬 <strong>3</strong> 分、欣欣 <strong>1</strong> 分过桥，手电筒电量只够 <strong>25</strong> 分钟，两人可借助灯光同时过桥。怎样安排？',
    analysis: [
      '先让快的两人过桥减少往返',
      '欣欣+小冬(3) → 欣欣回(1) → 天天+小妍(15) → 小冬回(3) → 欣欣+小冬(3)',
      '总时间 <strong>25</strong> 分钟内可全部过桥',
    ],
    type: 'none',
    finalQ: '全部过桥最少要多少分钟？',
    finalUnit: '分钟',
    finalAns: 25,
  },
  {
    id: '44-S2',
    title: '附加2 · 橡皮船渡河',
    tag: 'type4',
    tagLabel: '过河问题',
    difficulty: 4,
    text: '<strong>31</strong> 名游客过河，橡皮船可乘 <strong>7</strong> 人，过一次河需 <strong>3</strong> 分钟（来回都算）。全部运到对岸最少要多少分钟？',
    analysis: [
      '每次过河 7 人，需 1 人把船划回',
      '有效运送：每往返净运 6 人，(31−7)÷6=4 次往返 + 首次 = 5 次过河 + 4 次返回',
      '5×3 + 4×3 = <strong>27</strong> 分钟',
    ],
    type: 'none',
    finalQ: '最少要多少分钟？',
    finalUnit: '分钟',
    finalAns: 27,
  },
  {
    id: '44-S3',
    title: '附加3 · 公共汽车站',
    tag: 'type6',
    tagLabel: '最短路径',
    difficulty: 4,
    text: 'A、B、C、D、E 五间房子分别住 <strong>4、5、6、7、8</strong> 人，相邻房子相距 <strong>100</strong> 米。在某间门口建汽车站，使所有人到车站距离之和最小，最少总和多少米？',
    analysis: [
      '人数较多处权重更大，车站应建在 C 或 D 附近',
      '建在 C：4×200+5×100+7×100+8×200 = <strong>3600</strong> 米',
    ],
    type: 'none',
    finalQ: '距离总和最少多少米？',
    finalUnit: '米',
    finalAns: 3600,
  },
  {
    id: '44-S4',
    title: '附加4 · 运费最少',
    tag: 'type2',
    tagLabel: '统筹分配',
    difficulty: 5,
    text: '北京 <strong>10</strong> 台、上海 <strong>6</strong> 台车床分给武汉 <strong>11</strong> 台、西安 <strong>5</strong> 台。运费：北京→武汉 <strong>500</strong>、→西安 <strong>600</strong>；上海→武汉 <strong>700</strong>、→西安 <strong>1000</strong>（元/台）。总运费最少多少元？',
    analysis: [
      '优先用便宜的线路：北京→武汉 500，北京→西安 600',
      '北京 5 台→西安(3000)+5 台→武汉(2500)，上海 6 台→武汉(4200)',
      '总运费 = <strong>9700</strong> 元',
    ],
    type: 'none',
    finalQ: '总运费最少多少元？',
    finalUnit: '元',
    finalAns: 9700,
  },
  {
    id: '44-S5',
    title: '附加5 · 合作植树',
    tag: 'type1',
    tagLabel: '合理安排时间',
    difficulty: 4,
    text: '每人植 <strong>2</strong> 棵树：挖坑 <strong>10</strong> 分/棵，取树苗 <strong>20</strong> 分（最多 4 棵），运水 <strong>20</strong> 分（可浇 4 棵），栽树 <strong>10</strong> 分/棵。一人单干 2 棵树要多少分？两人合作统筹安排要多少分？',
    analysis: [
      '一人：挖 20 + 取 20 + 运 20 + 栽 20 = <strong>80</strong> 分钟',
      '两人分工并行：一人挖+栽，一人取+运，约 <strong>40</strong> 分钟',
    ],
    type: 'none',
    finalQ: '两人合作最少要多少分钟？',
    finalUnit: '分钟',
    finalAns: 40,
  },
]

export const PROBLEMS: ProblemSet = {
  pretest: PRETEST,
  lesson: LESSON,
  homework: HOMEWORK,
  workbook: WORKBOOK,
  supplement: SUPPLEMENT,
}

export const PROBLEM_TYPES = [
  {
    tag: 'type1',
    color: 'blue',
    label: '题型1 · 合理安排',
    desc: '能并行的工序同时进行，缩短总时间。',
    example: '例：烧水时洗杯、取奶粉',
  },
  {
    tag: 'type2',
    color: 'green',
    label: '题型2 · 等候最短',
    desc: '多人排队按用时从短到长安排，减少总等候。',
    example: '例：1、2、5、15 分钟四人用水',
  },
  {
    tag: 'type3',
    color: 'orange',
    label: '题型3 · 刷漆晾晒',
    desc: '利用晾干时间流水线刷另一面。',
    example: '例：刷漆 1 分，晾干 5 分',
  },
  {
    tag: 'type4',
    color: 'purple',
    label: '题型4 · 过河过桥',
    desc: '快者往返带手电筒，慢者结伴过河。',
    example: '例：1、2、5、6 分钟四牛过河',
  },
  {
    tag: 'type5',
    color: 'red',
    label: '题型5 · 烙饼问题',
    desc: '锅每次烙两面，合理安排翻面顺序。',
    example: '例：3 张饼最少 6 分钟',
  },
  {
    tag: 'type6',
    color: 'pink',
    label: '题型6 · 最短路径',
    desc: '比较各条路线时间之和，选最小值。',
    example: '例：标数法找最快路线',
  },
]

export const TYPE_STYLE: Record<string, { bg: string; border: string; titleColor: string; textColor: string }> = {
  type1: { bg: 'bg-blue-50', border: 'border-l-blue-500', titleColor: 'text-blue-800', textColor: 'text-blue-900' },
  type2: { bg: 'bg-green-50', border: 'border-l-green-500', titleColor: 'text-green-800', textColor: 'text-green-900' },
  type3: { bg: 'bg-orange-50', border: 'border-l-orange-500', titleColor: 'text-orange-800', textColor: 'text-orange-900' },
  type4: { bg: 'bg-purple-50', border: 'border-l-purple-500', titleColor: 'text-purple-800', textColor: 'text-purple-900' },
  type5: { bg: 'bg-red-50', border: 'border-l-red-500', titleColor: 'text-red-800', textColor: 'text-red-900' },
  type6: { bg: 'bg-pink-50', border: 'border-l-pink-500', titleColor: 'text-pink-800', textColor: 'text-pink-900' },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-app-blue-light text-app-blue-dark',
  type2: 'bg-app-green-light text-app-green-dark',
  type3: 'bg-orange-100 text-orange-800',
  type4: 'bg-app-purple-light text-app-purple-dark',
  type5: 'bg-red-100 text-red-800',
  type6: 'bg-pink-100 text-pink-800',
}
