import type { Problem, ProblemSet } from './type'

const PRETEST: Problem[] = [
  {
    id: '41-P1',
    title: '课前测1 · 爬楼梯',
    tag: 'type2',
    tagLabel: '爬楼梯',
    text: '奇奇家住在 <strong>15 层</strong>，每层楼梯有 <strong>20 个阶梯</strong>。有天电梯坏了，他只能爬楼梯，如果他每上一个阶梯需要 <strong>1 秒</strong>，请问他到家需要多少秒？',
    analysis: [
      '从1楼到15楼，共有 15 − 1 = 14 个楼层间隔',
      '每个楼层间隔有 20 个台阶',
      '总台阶数 = 14 × 20 = 280 个',
      '每个台阶 1 秒，共需 280 秒',
    ],
    type: 'none',
    finalQ: '奇奇到家需要多少秒？',
    finalUnit: '秒',
    finalAns: 280,
  },
  {
    id: '41-P2',
    title: '课前测2 · 植树问题',
    tag: 'type4',
    tagLabel: '圆形与队列',
    text: '有一块三角形的土地，三条边长度分别为 <strong>120 米、150 米、80 米</strong>，在这块土地的四周每隔 <strong>10 米</strong>种一棵树，一共要种多少棵树？',
    analysis: [
      '三角形土地的周长 = 120 + 150 + 80 = 350 米',
      '封闭图形种树：棵数 = 间隔数 = 周长 ÷ 间距',
      '棵数 = 350 ÷ 10 = 35 棵',
      '⚠️ 封闭图形头尾相接，棵数 = 间隔数（无需 +1）',
    ],
    type: 'none',
    finalQ: '一共要种多少棵树？',
    finalUnit: '棵',
    finalAns: 35,
  },
  {
    id: '41-P3',
    title: '课前测3 · 锯圆木',
    tag: 'type1',
    tagLabel: '锯木头与切割',
    text: '有 <strong>8 根木料</strong>，每根长 <strong>10 米</strong>，需要把它们锯成长为 <strong>2 米</strong>的圆木，每锯开一处需要 <strong>4 分钟</strong>，请问全部锯完需要多少分钟？',
    analysis: [
      '每根 10 米锯成 2 米：10 ÷ 2 = 5 段，需 5 − 1 = 4 次',
      '8 根共需：8 × 4 = 32 次',
      '总时间 = 32 × 4 = 128 分钟',
    ],
    type: 'none',
    finalQ: '全部锯完需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 128,
  },
  {
    id: '41-P4',
    title: '课前测4 · 双色锯点',
    tag: 'type1',
    tagLabel: '锯木头与切割',
    text: '一根 <strong>90 厘米</strong>长的木棍，先每隔 <strong>5 厘米</strong>画一个红点，每隔 <strong>6 厘米</strong>画一个绿点，沿红点和绿点锯开，一共可以得到多少段小木棍？',
    analysis: [
      '红点（不含端点90cm）：5, 10, …, 85，共 17 个',
      '绿点（不含端点90cm）：6, 12, …, 84，共 14 个',
      '重合点（LCM=30，不含90cm）：30, 60，共 2 个',
      '切割点总数 = 17 + 14 − 2 = 29 个',
      '段数 = 29 + 1 = 30 段',
    ],
    type: 'none',
    finalQ: '一共可以得到多少段小木棍？',
    finalUnit: '段',
    finalAns: 30,
  },
  {
    id: '41-P5',
    title: '课前测5 · 圆圈站队（一）',
    tag: 'type4',
    tagLabel: '圆形与队列',
    text: '某班有 <strong>43 名学生</strong>，站成一圆形的圈，从某人 A 开始数。立立是顺时针数第 <strong>27</strong> 个，奇奇是逆时针数第 <strong>31</strong> 个，立立与奇奇之间（不经过 A 的一侧）有多少名同学？',
    analysis: [
      '立立在顺时针位置 27',
      '逆时针第31个 → 顺时针位置 = 43 − 31 + 2 = 14，即奇奇在位置 14',
      '从位置14到位置27顺时针，中间经过：15, 16, …, 26',
      '共 26 − 15 + 1 = 12 名同学',
    ],
    type: 'none',
    finalQ: '立立与奇奇之间有多少名同学？',
    finalUnit: '名',
    finalAns: 12,
  },
  {
    id: '41-P6',
    title: '课前测6 · 圆圈站队（二）',
    tag: 'type4',
    tagLabel: '圆形与队列',
    text: '某班有 <strong>43 名学生</strong>，站成一圆形的圈，从某人 A 开始数。立立是顺时针数第 <strong>22</strong> 个，奇奇是逆时针数第 <strong>13</strong> 个，立立与奇奇之间（较短的一侧）有多少名同学？',
    analysis: [
      '立立在顺时针位置 22',
      '逆时针第13个 → 顺时针位置 = 43 − 13 + 2 = 32，即奇奇在位置 32',
      '从位置22到位置32顺时针，中间经过：23, 24, …, 31',
      '共 31 − 23 + 1 = 9 名同学',
    ],
    type: 'none',
    finalQ: '立立与奇奇之间有多少名同学？',
    finalUnit: '名',
    finalAns: 9,
  },
  {
    id: '41-P7',
    title: '课前测7 · 圆圈站队（三）',
    tag: 'type4',
    tagLabel: '圆形与队列',
    text: '某班有 <strong>43 名学生</strong>，站成一圆形的圈，从某人 A 开始数。立立是顺时针数第 <strong>26</strong> 个，奇奇是顺时针数第 <strong>17</strong> 个，立立与奇奇之间（较短的一侧）有多少名同学？',
    analysis: [
      '立立在顺时针位置 26，奇奇在顺时针位置 17',
      '从位置17到位置26顺时针，中间经过：18, 19, …, 25',
      '共 25 − 18 + 1 = 8 名同学',
    ],
    type: 'none',
    finalQ: '立立与奇奇之间有多少名同学？',
    finalUnit: '名',
    finalAns: 8,
  },
]

const LESSON: Problem[] = [
  {
    id: '41-L1',
    title: '例1 · 多根木棍全锯完',
    tag: 'type1',
    tagLabel: '锯木头与切割',
    text: '有 <strong>6 根木棍</strong>，每根长 <strong>12 米</strong>，需要把它们锯成长为 <strong>3 米</strong>的短棍，每锯开一处需要 <strong>2 分钟</strong>，请问全部锯完需要多少分钟？',
    analysis: [
      '每根 12 米锯成 3 米：12 ÷ 3 = 4 段，需 4 − 1 = 3 次',
      '6 根共需：6 × 3 = 18 次',
      '总时间 = 18 × 2 = 36 分钟',
    ],
    type: 'none',
    finalQ: '全部锯完需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 36,
  },
  {
    id: '41-L2',
    title: '练一练 · 锯面包',
    tag: 'type1',
    tagLabel: '锯木头与切割',
    text: '小气鬼把一根面包分成 <strong>5 段</strong>用了 <strong>20 秒</strong>，若以同样的速度，他要把另外同样的 <strong>3 根面包每根分成 4 段</strong>，要用多少秒？',
    analysis: [
      '1根→5段，需 5 − 1 = 4 次；20秒 ÷ 4 = 5 秒/次',
      '每根→4段，需 4 − 1 = 3 次',
      '3根共需：3 × 3 = 9 次',
      '总时间 = 9 × 5 = 45 秒',
    ],
    type: 'none',
    finalQ: '把3根面包每根分成4段共需多少秒？',
    finalUnit: '秒',
    finalAns: 45,
  },
  {
    id: '41-L3',
    title: '例2 · 比较工作量',
    tag: 'type1',
    tagLabel: '锯木头与切割',
    text: '甲、乙两组分别领取 <strong>4 米、3 米</strong>圆木，要求都锯成 <strong>1 米</strong>长的小段，每次锯需 <strong>1 分钟</strong>，且甲、乙最后均锯出了 <strong>12 段</strong>，工作量最小的组共锯多少分钟？',
    analysis: [
      '甲：4米→1米=4段，需3次/根；12段=3根，共 3×3=9次 → 9分钟',
      '乙：3米→1米=3段，需2次/根；12段=4根，共 4×2=8次 → 8分钟',
      '工作量最小的是乙组：8 分钟',
    ],
    type: 'none',
    finalQ: '工作量最小的组共锯了多少分钟？',
    finalUnit: '分钟',
    finalAns: 8,
  },
  {
    id: '41-L4',
    title: '练一练 · 多规格比较',
    tag: 'type1',
    tagLabel: '锯木头与切割',
    text: '纳纳和约约分别领取 <strong>8 米、10 米</strong>木棍，都按 <strong>2 米</strong>规格锯开。最后，纳纳锯了 <strong>24 段</strong>，约约锯了 <strong>25 段</strong>，工作量大的比工作量小的多锯多少次？',
    analysis: [
      '纳纳：8÷2=4段，需3次/根；24段=6根，共 6×3=18次',
      '约约：10÷2=5段，需4次/根；25段=5根，共 5×4=20次',
      '约约更多：20 − 18 = 2 次',
    ],
    type: 'none',
    finalQ: '工作量大的比工作量小的多锯多少次？',
    finalUnit: '次',
    finalAns: 2,
  },
  {
    id: '41-L5',
    title: '例3 · 爬楼梯求时间',
    tag: 'type2',
    tagLabel: '爬楼梯',
    text: '文文家住在 <strong>8 楼</strong>，电梯坏了，他从 <strong>1 楼走到 5 楼</strong>共用了 <strong>36 秒</strong>，照此速度他还要走多少秒才能到家？',
    analysis: [
      '1楼→5楼：5 − 1 = 4 个楼层间隔，用时 36 秒',
      '每个间隔：36 ÷ 4 = 9 秒',
      '5楼→8楼还有：8 − 5 = 3 个间隔',
      '还需时间：3 × 9 = 27 秒',
    ],
    type: 'none',
    finalQ: '文文还要走多少秒才能到家？',
    finalUnit: '秒',
    finalAns: 27,
  },
  {
    id: '41-L6',
    title: '练一练 · 送餐员爬楼',
    tag: 'type2',
    tagLabel: '爬楼梯',
    text: '送餐员从大厦 <strong>1 层</strong>开始爬楼梯，速度保持不变。他爬到 <strong>5 层</strong>用了 <strong>7 分钟</strong>，又过了 <strong>21 分钟</strong>，请问他爬到了几层？',
    analysis: [
      '1层→5层：5 − 1 = 4 个间隔，用时 7 分钟',
      '每个间隔：7 ÷ 4 分钟',
      '21分钟可走：21 ÷ (7÷4) = 21 × 4 ÷ 7 = 12 个间隔',
      '到达楼层：5 + 12 = 17 层',
    ],
    type: 'none',
    finalQ: '送餐员爬到了几层？',
    finalUnit: '层',
    finalAns: 17,
  },
  {
    id: '41-L7',
    title: '例4 · 速度比较',
    tag: 'type2',
    tagLabel: '爬楼梯',
    text: '奇奇和立立同时从 <strong>1 楼</strong>往上走。当奇奇到达 <strong>3 层</strong>时，立立恰好到了 <strong>5 层</strong>。照此速度，当立立走到 <strong>17 层</strong>时，奇奇到达了哪一层？',
    analysis: [
      '奇奇: 1→3层 = 2 个间隔；立立: 1→5层 = 4 个间隔',
      '速度比 奇奇:立立 = 2:4 = 1:2',
      '立立从1到17层共走 17 − 1 = 16 个间隔',
      '同时间奇奇走：16 × (1÷2) = 8 个间隔',
      '奇奇到达：1 + 8 = 9 层',
    ],
    type: 'none',
    finalQ: '当立立走到17层时，奇奇到达了哪一层？',
    finalUnit: '层',
    finalAns: 9,
  },
  {
    id: '41-L8',
    title: '练一练 · 青蛙跳台阶',
    tag: 'type2',
    tagLabel: '爬楼梯',
    text: '蹦蹦和跳跳从 <strong>1 楼</strong>开始比赛跳台阶，当蹦蹦跳到 <strong>3 楼</strong>时，跳跳才刚到 <strong>2 楼</strong>，那么当蹦蹦跳到 <strong>9 楼</strong>时，跳跳能到几楼？',
    analysis: [
      '蹦蹦: 1→3层 = 2 个间隔；跳跳: 1→2层 = 1 个间隔',
      '速度比 蹦蹦:跳跳 = 2:1',
      '蹦蹦从1到9层共走 9 − 1 = 8 个间隔',
      '同时间跳跳走：8 × (1÷2) = 4 个间隔',
      '跳跳到达：1 + 4 = 5 楼',
    ],
    type: 'none',
    finalQ: '当蹦蹦跳到9楼时，跳跳能到几楼？',
    finalUnit: '楼',
    finalAns: 5,
  },
  {
    id: '41-L9',
    title: '例5 · 几点钟敲几下',
    tag: 'type3',
    tagLabel: '敲钟与计时',
    text: '五点钟的时候，挂钟敲了 <strong>5 下</strong>，用了 <strong>12 秒</strong>，那么在 <strong>十一点钟</strong>时，挂钟敲了 11 下，用了多少秒？',
    analysis: [
      '5 下之间有 5 − 1 = 4 个间隔，用时 12 秒',
      '每个间隔：12 ÷ 4 = 3 秒',
      '11 下之间有 11 − 1 = 10 个间隔',
      '总时间：10 × 3 = 30 秒',
    ],
    type: 'none',
    finalQ: '十一点钟敲11下共用了多少秒？',
    finalUnit: '秒',
    finalAns: 30,
  },
  {
    id: '41-L10',
    title: '练一练 · 钟楼敲钟',
    tag: 'type3',
    tagLabel: '敲钟与计时',
    text: '钟楼上的大钟整点时敲相应的点数，早上 <strong>6 点</strong>时敲钟用了 <strong>40 秒</strong>，那么 <strong>12 点</strong>时敲钟共用了多少秒？',
    analysis: [
      '6 下之间有 6 − 1 = 5 个间隔，用时 40 秒',
      '每个间隔：40 ÷ 5 = 8 秒',
      '12 下之间有 12 − 1 = 11 个间隔',
      '总时间：11 × 8 = 88 秒',
    ],
    type: 'none',
    finalQ: '12点敲钟共用了多少秒？',
    finalUnit: '秒',
    finalAns: 88,
  },
  {
    id: '41-L11',
    title: '例6 · 间隔计时推算',
    tag: 'type3',
    tagLabel: '敲钟与计时',
    text: '手机从响第 1 声开始，每隔 <strong>5 秒</strong>响一下。响第 <strong>21 下</strong>的时刻为早上 8 点 20 分 36 秒，请问从第 1 声到第 21 声共经过了多少秒？',
    analysis: [
      '从第1声到第21声，共有 21 − 1 = 20 个间隔',
      '每个间隔 5 秒',
      '共经过：20 × 5 = 100 秒',
      '因此第1声比第21声早 100 秒，即第1声在 8 点 18 分 56 秒',
    ],
    type: 'none',
    finalQ: '从第1声到第21声共经过了多少秒？',
    finalUnit: '秒',
    finalAns: 100,
  },
  {
    id: '41-L12',
    title: '练一练 · 庙里敲钟倒推',
    tag: 'type3',
    tagLabel: '敲钟与计时',
    text: '山上的庙里有一座钟，每隔 <strong>10 秒</strong>敲一下。敲第 <strong>20 下</strong>的时候为早上 8 点 17 分 40 秒，请问从第 1 下到第 20 下共经过了多少秒？',
    analysis: [
      '从第1下到第20下，共有 20 − 1 = 19 个间隔',
      '每个间隔 10 秒',
      '共经过：19 × 10 = 190 秒',
      '因此第1下在 8 点 14 分 30 秒',
    ],
    type: 'none',
    finalQ: '从第1下到第20下共经过了多少秒？',
    finalUnit: '秒',
    finalAns: 190,
  },
]

const HOMEWORK: Problem[] = [
  {
    id: '41-H1',
    title: '巩固1 · 两根锯成8段',
    tag: 'type1',
    tagLabel: '锯木头与切割',
    text: '奇奇将一根木头锯成 <strong>2 段</strong>需要 <strong>4 分钟</strong>，如果他要把同样的 <strong>两根木头每根都锯成 8 段</strong>，需要锯多少分钟？',
    analysis: [
      '1根→2段，需 1 次；4分钟/次',
      '每根→8段，需 8 − 1 = 7 次',
      '两根共需：2 × 7 = 14 次',
      '总时间：14 × 4 = 56 分钟',
    ],
    type: 'none',
    finalQ: '需要锯多少分钟？',
    finalUnit: '分钟',
    finalAns: 56,
  },
  {
    id: '41-H2',
    title: '巩固2 · 谁用时最短',
    tag: 'type1',
    tagLabel: '锯木头与切割',
    text: '奇奇和文文比赛锯木头，都要锯成 <strong>1 米</strong>长的段，每锯一次花 <strong>5 分钟</strong>。奇奇每根 <strong>4 米</strong>，文文每根 <strong>3 米</strong>。最后，奇奇锯出 <strong>28 段</strong>，文文锯出 <strong>30 段</strong>，用时最短的人共花了多少分钟？',
    analysis: [
      '奇奇：4米→4段，需3次/根；28段=7根，共 7×3=21次，21×5=105分钟',
      '文文：3米→3段，需2次/根；30段=10根，共 10×2=20次，20×5=100分钟',
      '文文用时最短：100 分钟',
    ],
    type: 'none',
    finalQ: '用时最短的人共花了多少分钟？',
    finalUnit: '分钟',
    finalAns: 100,
  },
  {
    id: '41-H3',
    title: '巩固3 · 快递员爬楼',
    tag: 'type2',
    tagLabel: '爬楼梯',
    text: '快递员从一楼走到 <strong>七楼</strong>用了 <strong>12 分钟</strong>，按照同样的速度往上爬，又爬了 <strong>16 分钟</strong>才到客户家，请问客户家在几楼？',
    analysis: [
      '1楼→7楼：7 − 1 = 6 个间隔，用时 12 分钟',
      '每个间隔：12 ÷ 6 = 2 分钟',
      '16分钟可走：16 ÷ 2 = 8 个间隔',
      '到达楼层：7 + 8 = 15 楼',
    ],
    type: 'none',
    finalQ: '客户家在几楼？',
    finalUnit: '楼',
    finalAns: 15,
  },
  {
    id: '41-H4',
    title: '巩固4 · 约约和奶奶',
    tag: 'type2',
    tagLabel: '爬楼梯',
    text: '约约和奶奶同时从 <strong>1 层</strong>爬楼梯回 <strong>16 层</strong>的家。当约约走到 <strong>4 层</strong>时，奶奶正好上到 <strong>2 层</strong>，当约约走到家时，奶奶在第几层？',
    analysis: [
      '约约: 1→4层 = 3 个间隔；奶奶: 1→2层 = 1 个间隔',
      '速度比 约约:奶奶 = 3:1',
      '约约从1到16层共走 16 − 1 = 15 个间隔',
      '同时间奶奶走：15 × (1÷3) = 5 个间隔',
      '奶奶在：1 + 5 = 6 层',
    ],
    type: 'none',
    finalQ: '当约约走到家时，奶奶在第几层？',
    finalUnit: '层',
    finalAns: 6,
  },
  {
    id: '41-H5',
    title: '巩固5 · 石英钟敲钟',
    tag: 'type3',
    tagLabel: '敲钟与计时',
    text: '思思家的石英钟敲 <strong>5 下</strong>要 <strong>8 秒钟</strong>，请问敲 <strong>8 下</strong>要多少秒？',
    analysis: [
      '5 下之间有 5 − 1 = 4 个间隔，用时 8 秒',
      '每个间隔：8 ÷ 4 = 2 秒',
      '8 下之间有 8 − 1 = 7 个间隔',
      '总时间：7 × 2 = 14 秒',
    ],
    type: 'none',
    finalQ: '敲8下要多少秒？',
    finalUnit: '秒',
    finalAns: 14,
  },
  {
    id: '41-H6',
    title: '巩固6 · 敲鼓推算',
    tag: 'type3',
    tagLabel: '敲钟与计时',
    text: '约约每天早上练习敲鼓，从敲第 <strong>1 下</strong>开始，每隔 <strong>8 秒</strong>敲一下。敲第 <strong>11 下</strong>的时刻为早上 <strong>8 点 08 分 12 秒</strong>，请问从第 1 下到第 11 下共经过了多少秒？',
    analysis: [
      '从第1下到第11下，共有 11 − 1 = 10 个间隔',
      '每个间隔 8 秒',
      '共经过：10 × 8 = 80 秒',
      '因此第1下在 8 点 06 分 52 秒',
    ],
    type: 'none',
    finalQ: '从第1下到第11下共经过了多少秒？',
    finalUnit: '秒',
    finalAns: 80,
  },
]

const WORKBOOK: Problem[] = [
  {
    id: '41-W1',
    title: '闯关1 · 伐木场比赛',
    tag: 'type1',
    tagLabel: '锯木头与切割',
    text: '光头强把一根 <strong>45 米</strong>的木材锯成 <strong>3 米</strong>一段只要 <strong>140 秒</strong>，按这样的速度，他把同样一根木材锯成 <strong>9 段</strong>需要多少秒？',
    analysis: [
      '45米→3米：45÷3=15段，需 15−1=14次；140÷14=10秒/次',
      '锯成9段需 9 − 1 = 8 次',
      '总时间：8 × 10 = 80 秒',
    ],
    type: 'none',
    finalQ: '把木材锯成9段需要多少秒？',
    finalUnit: '秒',
    finalAns: 80,
  },
  {
    id: '41-W2',
    title: '闯关2 · 多根截多段',
    tag: 'type1',
    tagLabel: '锯木头与切割',
    text: '把一根木头截成 <strong>3 段</strong>要花 <strong>6 分钟</strong>，要把 <strong>10 根木头都截成 6 段</strong>，请问需要多少分钟？',
    analysis: [
      '3段需 3 − 1 = 2 次；6分钟÷2=3分钟/次',
      '6段需 6 − 1 = 5 次',
      '10根共：10 × 5 = 50 次',
      '总时间：50 × 3 = 150 分钟',
    ],
    type: 'none',
    finalQ: '需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 150,
  },
  {
    id: '41-W3',
    title: '闯关3 · 钢管锯次数',
    tag: 'type1',
    tagLabel: '锯木头与切割',
    text: '有 <strong>13 根钢管</strong>，其中 <strong>8 米长</strong>的有 4 根，<strong>6 米长</strong>的有 9 根，现在要把它们都锯成 <strong>1 米</strong>长的钢管，请问一共要锯多少次？',
    analysis: [
      '8米→1米：8段，需 7次；4根共 4×7=28次',
      '6米→1米：6段，需 5次；9根共 9×5=45次',
      '总锯次：28 + 45 = 73 次',
    ],
    type: 'none',
    finalQ: '一共要锯多少次？',
    finalUnit: '次',
    finalAns: 73,
  },
  {
    id: '41-W4',
    title: '闯关4 · 三人锯木比较',
    tag: 'type1',
    tagLabel: '锯木头与切割',
    text: '甲、乙、丙三人锯木棍，分别领取 <strong>8 米、10 米、6 米</strong>，都按 <strong>2 米</strong>规格锯开。最后，甲、乙、丙分别锯了 <strong>24、25、21 段</strong>，工作量最大的比工作量最小的多锯多少次？',
    analysis: [
      '甲：8÷2=4段，需3次/根；24段=6根，共 6×3=18次',
      '乙：10÷2=5段，需4次/根；25段=5根，共 5×4=20次',
      '丙：6÷2=3段，需2次/根；21段=7根，共 7×2=14次',
      '最大（乙20次）−最小（丙14次）= 6 次',
    ],
    type: 'none',
    finalQ: '工作量最大的比最小的多锯多少次？',
    finalUnit: '次',
    finalAns: 6,
  },
  {
    id: '41-W5',
    title: '闯关5 · 思思爬楼梯',
    tag: 'type2',
    tagLabel: '爬楼梯',
    text: '思思从一楼爬到 <strong>三楼</strong>用 <strong>6 分钟</strong>，按照同样的速度往上爬，又爬了 <strong>15 分钟</strong>才到家，那么思思家住在几楼？',
    analysis: [
      '1楼→3楼：3 − 1 = 2 个间隔，用时 6 分钟',
      '每个间隔：6 ÷ 2 = 3 分钟',
      '15分钟可走：15 ÷ 3 = 5 个间隔',
      '到达楼层：3 + 5 = 8 楼',
    ],
    type: 'none',
    finalQ: '思思家住在几楼？',
    finalUnit: '楼',
    finalAns: 8,
  },
  {
    id: '41-W6',
    title: '闯关6 · 台阶总数',
    tag: 'type2',
    tagLabel: '爬楼梯',
    text: '小立住 <strong>6 楼</strong>，小奇住 <strong>5 楼</strong>，两人每天从一楼爬楼回家。小立上楼走 <strong>100 级台阶</strong>，每层楼梯数相同，请问小奇每天上楼走多少级台阶？',
    analysis: [
      '1楼→6楼：6 − 1 = 5 个间隔，共 100 级',
      '每层台阶：100 ÷ 5 = 20 级',
      '1楼→5楼：5 − 1 = 4 个间隔',
      '小奇：4 × 20 = 80 级台阶',
    ],
    type: 'none',
    finalQ: '小奇每天上楼要走多少级台阶？',
    finalUnit: '级',
    finalAns: 80,
  },
  {
    id: '41-W7',
    title: '闯关7 · 电线杆追问',
    tag: 'type2',
    tagLabel: '爬楼梯',
    text: '纳纳和爷爷同时从 <strong>第1根电线杆</strong>出发，速度保持不变。当爷爷走到 <strong>第4根</strong>时，纳纳恰好走到 <strong>第7根</strong>。请问当纳纳走到 <strong>第13根</strong>时，爷爷走到了第几根？',
    analysis: [
      '爷爷: 1→4 = 3个间隔；纳纳: 1→7 = 6个间隔',
      '速度比 爷爷:纳纳 = 3:6 = 1:2',
      '纳纳从1到13根共走 13 − 1 = 12 个间隔',
      '同时间爷爷走：12 × (1÷2) = 6 个间隔',
      '爷爷到达：1 + 6 = 第 7 根',
    ],
    type: 'none',
    finalQ: '当纳纳走到第13根时，爷爷走到了第几根？',
    finalUnit: '根',
    finalAns: 7,
  },
  {
    id: '41-W8',
    title: '闯关8 · 时钟敲12下',
    tag: 'type3',
    tagLabel: '敲钟与计时',
    text: '时钟 <strong>7 点</strong>敲了 <strong>7 下</strong>，花了 <strong>12 秒</strong>，照这样计算，请问 <strong>12 点</strong>敲 12 下需要多少秒？',
    analysis: [
      '7 下之间有 7 − 1 = 6 个间隔，用时 12 秒',
      '每个间隔：12 ÷ 6 = 2 秒',
      '12 下之间有 12 − 1 = 11 个间隔',
      '总时间：11 × 2 = 22 秒',
    ],
    type: 'none',
    finalQ: '12点敲12下需要多少秒？',
    finalUnit: '秒',
    finalAns: 22,
  },
  {
    id: '41-W9',
    title: '闯关9 · 怪钟响几次',
    tag: 'type3',
    tagLabel: '敲钟与计时',
    text: '立立家有一个怪钟，每隔 <strong>15 分钟</strong>响一次，从 <strong>上午 10 点</strong>到 <strong>中午 12 点</strong>（两头都响）一共响了多少次？',
    analysis: [
      '上午10点到中午12点：共 120 分钟',
      '间隔数：120 ÷ 15 = 8 个间隔',
      '两头都响：响的次数 = 间隔数 + 1 = 9 次',
      '⚠️ 两端均计入时，次数 = 间隔数 + 1',
    ],
    type: 'none',
    finalQ: '一共响了多少次？',
    finalUnit: '次',
    finalAns: 9,
  },
  {
    id: '41-W10',
    title: '闯关10 · 实验记录倒推',
    tag: 'type3',
    tagLabel: '敲钟与计时',
    text: '约约在实验室每隔 <strong>5 小时</strong>做一次记录。做第 <strong>12 次</strong>记录时，正好是 <strong>2021 年 1 月 1 日早上 9 点整</strong>。请问从第 1 次到第 12 次共经过了多少小时？',
    analysis: [
      '从第1次到第12次，共有 12 − 1 = 11 个间隔',
      '每个间隔 5 小时',
      '共经过：11 × 5 = 55 小时',
      '因此第1次在 2020 年 12 月 30 日 2 点整',
    ],
    type: 'none',
    finalQ: '从第1次到第12次共经过了多少小时？',
    finalUnit: '小时',
    finalAns: 55,
  },
  {
    id: '41-W11',
    title: '闯关11 · 敲钟带休息',
    tag: 'type3',
    tagLabel: '敲钟与计时',
    text: '庙里的钟从敲第 <strong>1 下</strong>开始，每隔 <strong>5 秒</strong>敲一下，每敲完 <strong>10 下</strong>后休息 <strong>2 分钟</strong>。敲第 <strong>20 下</strong>时为早上 <strong>8 点 17 分 40 秒</strong>，请问从第 1 下到第 20 下共经过了多少秒？',
    analysis: [
      '第1-10下：9个间隔 × 5秒 = 45秒',
      '第10下后休息：2分钟 = 120秒',
      '第11-20下：9个间隔 × 5秒 = 45秒',
      '共经过：45 + 120 + 45 = 210 秒',
      '因此第1下在 8 点 14 分 10 秒',
    ],
    type: 'none',
    finalQ: '从第1下到第20下共经过了多少秒？',
    finalUnit: '秒',
    finalAns: 210,
  },
  {
    id: '41-W12',
    title: '闯关12 · 交替锯木棍',
    tag: 'type1',
    tagLabel: '锯木头与切割',
    text: '一根长 <strong>350 厘米</strong>的木棍，从一端开始，先 <strong>30 厘米</strong>一段，再 <strong>10 厘米</strong>一段，这样长短交替锯成小段，请问可以锯成多少段长 <strong>30 厘米</strong>的木棍？',
    analysis: [
      '每组"30cm+10cm" = 40cm',
      '350 ÷ 40 = 8 组，余 30cm',
      '8 组各含 1 段 30cm，余下 30cm 再得 1 段',
      '共 8 + 1 = 9 段长 30cm 的木棍',
    ],
    type: 'none',
    finalQ: '可以锯成多少段长30厘米的木棍？',
    finalUnit: '段',
    finalAns: 9,
  },
]

export const PROBLEMS: ProblemSet = {
  pretest: PRETEST,
  lesson: LESSON,
  homework: HOMEWORK,
  workbook: WORKBOOK,
}

export const PROBLEM_TYPES = [
  {
    tag: 'type1',
    color: 'orange',
    label: '题型1 · 锯木头与切割',
    desc: '多根木头：先算单根时间，再乘根数。递推：想算时间→算总次数→每根锯次=(段数-1)。',
    example: '例：6根，每根锯成4段→3次/根，共18次',
  },
  {
    tag: 'type2',
    color: 'green',
    label: '题型2 · 爬楼梯与行进',
    desc: '爬的楼层数=终点楼层−起点楼层。两人速度比=出发后间隔数之比，无整倍数时可自比。',
    example: '例：1→5楼=4间隔；速度比=间隔数之比',
  },
  {
    tag: 'type3',
    color: 'purple',
    label: '题型3 · 敲钟与计时',
    desc: 'n下之间有 n−1 个间隔，总时间=间隔时间×间隔数。由结束时间倒推开始时间：先算经过的总时间。',
    example: '例：敲20下=19间隔×5秒=95秒；结束时刻-95秒=开始时刻',
  },
  {
    tag: 'type4',
    color: 'blue',
    label: '题型4 · 圆形与队列',
    desc: '封闭图形棵数=间隔数（头尾相接不需+1）；逆时针k位=顺时针(总数-k)位。',
    example: '例：周长350÷间距10=35棵',
  },
]

export const TYPE_STYLE: Record<string, { bg: string; border: string; titleColor: string; textColor: string }> = {
  type1: { bg: 'bg-orange-50', border: 'border-l-orange-500', titleColor: 'text-orange-800', textColor: 'text-orange-900' },
  type2: { bg: 'bg-green-50', border: 'border-l-green-500', titleColor: 'text-green-800', textColor: 'text-green-900' },
  type3: { bg: 'bg-purple-50', border: 'border-l-purple-500', titleColor: 'text-purple-800', textColor: 'text-purple-900' },
  type4: { bg: 'bg-blue-50', border: 'border-l-blue-500', titleColor: 'text-blue-800', textColor: 'text-blue-900' },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-orange-100 text-orange-800',
  type2: 'bg-green-100 text-green-800',
  type3: 'bg-purple-100 text-purple-800',
  type4: 'bg-blue-100 text-blue-800',
}
