import type { Problem, ProblemSet } from './type'

const PRETEST: Problem[] = []

const LESSON: Problem[] = [
  {
    id: '42-L1',
    title: '例1 · 砝码单边称重',
    tag: 'type1',
    tagLabel: '砝码称重组合',
    text: '一台天平在称物时，只允许在天平的一边放砝码，现在给你 <strong>1 克、2 克、5 克、7 克</strong>的砝码各一个，那么在天平上能称出几种不同重量的物体？',
    analysis: [
      '每个砝码"用 / 不用" → 共 2⁴ − 1 = 15 种组合（去掉一个都不放）',
      '列出所有组合的和：1, 2, 5, 7, 3, 6, 8, 7, 9, 12, 8, 10, 13, 14, 15',
      '⚠️ 出现重复：7 = 7 = 2+5；8 = 1+7 = 1+2+5（各重一次）',
      '不同重量 = 15 − 2 = 13 种',
    ],
    type: 'none',
    finalQ: '能称出几种不同重量？',
    finalUnit: '种',
    finalAns: 13,
    analysisImg: '/img/math/42-L1.png',
  },
  {
    id: '42-L2',
    title: '练一练 · 三砝码单边',
    tag: 'type1',
    tagLabel: '砝码称重组合',
    text: '一台天平在称物时，只允许在天平的一边放砝码，现在给你 <strong>2 克、3 克、4 克</strong>的砝码各一个，那么在天平上能称出几种不同重量的物体？',
    analysis: [
      '非空子集共 2³ − 1 = 7 种',
      '单个：2、3、4',
      '两两组合：5(2+3)、6(2+4)、7(3+4)',
      '三个一起：9(2+3+4)',
      '7 种和全部不同 → 7 种',
    ],
    type: 'none',
    finalQ: '能称出几种不同重量？',
    finalUnit: '种',
    finalAns: 7,
    analysisImg: '/img/math/42-L2.png',
  },
  {
    id: '42-L3',
    title: '例2 · 砝码两边称重',
    tag: 'type1',
    tagLabel: '砝码称重组合',
    text: '现有重量分别为 <strong>1 克、3 克、9 克</strong>的 3 个砝码，可放在天平的两边，用这 3 个砝码能够称出几种不同重量的物体？',
    analysis: [
      '每个砝码 3 种状态：右盘(+) / 不用(0) / 左盘(−) → 共 3³ = 27 种',
      '去掉全 0 一种 → 26 种，左右镜像两两相同 → 26 ÷ 2 = 13 种',
      '可称重量：1、2、3、4、5、6、7、8、9、10、11、12、13 克 → 共 13 种',
      '⚠️ 1+3+9=13，每一克到 13 克都可表示',
    ],
    type: 'none',
    finalQ: '能称出几种不同重量？',
    finalUnit: '种',
    finalAns: 13,
    analysisImg: '/img/math/42-L3.png',
  },
  {
    id: '42-L4',
    title: '练一练 · 两边称重',
    tag: 'type1',
    tagLabel: '砝码称重组合',
    text: '文文有 3 个砝码，重量分别为 <strong>1 克、2 克、6 克</strong>，砝码可以放在天平的两边，用这 3 个砝码能够称出几种不同重量的物体？',
    analysis: [
      '每个砝码 3 态：3³ = 27，去全 0 = 26，去镜像 ÷2 = 13 种组合',
      '逐一列出可称重量（绝对值）：1、2、3(1+2)、4(6−2)、5(6−1)、6、7(6+1)、8(6+2)、9(6+2+1)',
      '⚠️ 部分组合重复（如 6−2−1=3 与 1+2=3 同值），去重后共 9 种',
    ],
    type: 'none',
    finalQ: '能称出几种不同重量？',
    finalUnit: '种',
    finalAns: 9,
    analysisImg: '/img/math/42-L4.png',
  },
  {
    id: '42-L5',
    title: '例3 · 三人买面包分账',
    tag: 'type2',
    tagLabel: '公平分账',
    text: '甲、乙、丙三人共买了 <strong>9 个相同的面包</strong>，每人吃了 <strong>3 个</strong>。甲付了 5 个面包的钱，乙付了 4 个面包的钱，丙没有付钱。吃完后，丙拿出 <strong>6 元钱</strong>补给甲、乙两人，<strong>甲应得多少元</strong>？',
    analysis: [
      '丙吃 3 个，实付 6 元 → 每个面包 6 ÷ 3 = 2 元',
      '甲多付了5-3=2个面包的钱，甲应得(5-3)×2=4元',
      '乙多付了4-3=1个面包的钱，乙应得(4-3)×2=2元',
    ],
    type: 'none',
    finalQ: '甲应得多少元？',
    finalUnit: '元',
    finalAns: 4,
    analysisImg: '/img/math/42-L5.png',
  },
  {
    id: '42-L6',
    title: '练一练 · 雪糕分账',
    tag: 'type2',
    tagLabel: '公平分账',
    text: '纳纳、约约和立立三人共买了 <strong>12 块相同的梦龙雪糕</strong>，每人吃 <strong>4 块</strong>。纳纳付了 7 块雪糕的钱，约约付了 5 块雪糕的钱，立立没有付钱。吃完后，立立拿出 <strong>16 元钱</strong>补给纳纳和约约，请问<strong>纳纳应得多少元</strong>？',
    analysis: [
      '立立吃 4 块，付 16 元 → 每块 16 ÷ 4 = 4 元',
      '纳纳付 7 × 4 = 28 元；纳纳吃 4 × 4 = 16 元；应得 28 − 16 = 12 元',
      '约约付 5 × 4 = 20 元；约约吃 4 × 4 = 16 元；应得 20 − 16 = 4 元',
      '验算：12 + 4 = 16 元 ✓',
    ],
    type: 'none',
    finalQ: '纳纳应得多少元？',
    finalUnit: '元',
    finalAns: 12,
    analysisImg: '/img/math/42-L6.png',
  },
  {
    id: '42-L7',
    title: '例4 · 4 空瓶换 1 瓶',
    tag: 'type3',
    tagLabel: '空瓶换水',
    text: '商店规定：<strong>4 个空瓶可换 1 瓶</strong>矿泉水。纳纳有 <strong>15 个空瓶</strong>，最多能喝几瓶水？（空瓶不够时可以借，但要归还相同数量的空瓶）',
    analysis: [
      '思路：每喝 1 瓶水，最终净消耗 (4 − 1) = 3 个空瓶（喝完又得 1 个，相当于只用 3 个）',
      '所以最多喝 15 ÷ 3 = 5 瓶',
      '具体操作：15 → 换 3 瓶 + 剩 3 空 = 6 空；6 → 换 1 瓶 + 剩 2 空 = 3 空；3 → 借 1 个 = 4 空换 1 瓶 → 还回 1 空',
      '总计 3 + 1 + 1 = 5 瓶 ✓',
    ],
    type: 'none',
    finalQ: '最多能喝几瓶水？',
    finalUnit: '瓶',
    finalAns: 5,
    analysisImg: '/img/math/42-L7.png',
  },
  {
    id: '42-L8',
    title: '练一练 · 桃核换桃',
    tag: 'type3',
    tagLabel: '空瓶换水',
    text: '纳约水果店"<strong>3 个桃核换 1 个桃</strong>"促销（桃核不够时可借，但要归还相同数量的桃核），一个桃售价 <strong>1 元</strong>。如果你有 <strong>10 元钱</strong>，最多能吃几个桃？',
    analysis: [
      '10 元先直接买 10 个桃 → 得 10 个桃核',
      '剩余桃核换桃：每换 1 个桃净消耗 (3 − 1) = 2 个桃核',
      '10 个桃核 → 10 ÷ 2 = 5 个桃',
      '总计 10 + 5 = 15 个桃',
    ],
    type: 'none',
    finalQ: '最多能吃几个桃？',
    finalUnit: '个',
    finalAns: 15,
    analysisImg: '/img/math/42-L8.png',
  },
  {
    id: '42-L9',
    title: '例5 · 绳子定时 9 分钟',
    tag: 'type4',
    tagLabel: '计时与量水',
    text: '两根粗细均匀的绳子，每根从一端点燃可烧 <strong>12 分钟</strong>，绳子不能折叠。如果要用 <strong>两根绳子</strong>准确定出 <strong>9 分钟</strong>的时间，应如何操作？',
    analysis: [
      '关键技巧：一根绳两端同时点燃 → 燃烧时间减半（12 ÷ 2 = 6 分钟）',
      '操作：A 两端点 + B 一端点 → 6 分钟时 A 烧完，此刻 B 还剩 6 分钟',
      '此时把 B 另一端也点燃 → 剩下 6 分钟两端烧，需 3 分钟烧完',
      '总时长 6 + 3 = 9 分钟 ✓',
    ],
    type: 'none',
    finalQ: '准确测出的时间是多少分钟？',
    finalUnit: '分钟',
    finalAns: 9,
    analysisImg: '/img/math/42-L9.png',
  },
  {
    id: '42-L10',
    title: '练一练 · 香测 15 分钟',
    tag: 'type4',
    tagLabel: '计时与量水',
    text: '有两支粗细不均匀且长度不同的香，每支点燃后都能燃烧 <strong>1 个小时</strong>。怎样用这两支香准确定出 <strong>15 分钟</strong>？',
    analysis: [
      '香 A 两端同时点燃 → 30 分钟烧完；同时香 B 一端点燃',
      'A 烧完时（30 分钟过去），B 还剩 30 分钟',
      '立刻把 B 另一端也点燃 → 剩下 30 分钟两端烧 → 15 分钟烧完',
      '从 A 烧完到 B 烧完恰好 15 分钟 ✓',
    ],
    type: 'none',
    finalQ: '测出的时间是多少分钟？',
    finalUnit: '分钟',
    finalAns: 15,
    analysisImg: '/img/math/42-L10.png',
  },
  {
    id: '42-L11',
    title: '例6 · 量出 100 克水',
    tag: 'type4',
    tagLabel: '计时与量水',
    text: '有大、中、小 3 个瓶子，分别可以装入水 <strong>1000 克、700 克、300 克</strong>。现在大瓶装满水，希望通过水在 3 个瓶子间的流动，使得中瓶和小瓶上都标出 <strong>100 克</strong>的刻度线，问最少要倒几次水？',
    analysis: [
      '①大→中：大 1000→300，中 0→700',
      '②中→小：中 700→400，小 0→300',
      '③小→大：大 300→600，小 300→0',
      '④中→小：中 400→100（标中 100 克✨），小 0→300',
      '⑤小→大：大 600→900，小 300→0',
      '⑥中→小：中 100→0，小 0→100（标小 100 克✨）',
      '共 6 次',
    ],
    type: 'none',
    finalQ: '最少要倒几次水？',
    finalUnit: '次',
    finalAns: 6,
    analysisImg: '/img/math/42-L11.png',
  },
  {
    id: '42-L12',
    title: '练一练 · 量 3 升水',
    tag: 'type4',
    tagLabel: '计时与量水',
    text: '有两个没有刻度的杯子，大杯装满 <strong>8 升</strong>水，小杯装满 <strong>5 升</strong>水。如何用这两个杯子准确量出 <strong>3 升水</strong>？最少要倒几步？',
    analysis: [
      '①把大杯装满（8 升）',
      '②大杯倒入小杯，倒到小杯装满为止：大杯剩 8 − 5 = 3 升',
      '此时大杯里恰好就是 3 升水 ✓',
      '至少 2 步（装满 + 倒一次）',
    ],
    type: 'none',
    finalQ: '最少要倒几步？',
    finalUnit: '步',
    finalAns: 2,
    analysisImg: '/img/math/42-L12.png',
  },
  {
    id: '42-L13',
    title: '附加题1 · 9 枚金币找假币',
    tag: 'type5',
    tagLabel: '天平找异物',
    text: '有 <strong>9 枚金币</strong>外观完全相同，其中 8 枚真币、1 枚假币，假币<strong>不知轻重</strong>（真币重量一样）。用一台无砝码的天平称，请问<strong>至少称几次</strong>才能保证找出假币？',
    analysis: [
      '不知轻重 → 第一次称要锁定假币所在分组及它"偏轻"还是"偏重"',
      '把 9 枚分成 3 组（3 + 3 + 3）：左 3 右 3 上天平，剩 3 在外',
      '若平衡 → 假在外面 3 枚里；若不平 → 假在天平上 6 枚里且偏向某侧',
      '第 2 次再分 3 等分 → 第 3 次比较两枚定真假',
      '总共需要 3 次',
    ],
    type: 'none',
    finalQ: '至少称几次能找出假币？',
    finalUnit: '次',
    finalAns: 3,
  },
  {
    id: '42-L14',
    title: '附加题2 · 27 个球找次品',
    tag: 'type5',
    tagLabel: '天平找异物',
    text: '有 <strong>27 个球</strong>，其中 1 个次品，外观与正品相同但<strong>比正品轻</strong>。用一台无砝码的天平称，<strong>最少称几次</strong>能找出这个次品？',
    analysis: [
      '已知次品偏轻 → 每次称可把目标分成 3 组等分',
      '27 = 3 × 3 × 3 = 3³ → 三次三等分即可',
      '①9 vs 9：轻的一边/平衡 → 锁定 9 个',
      '②3 vs 3：轻的一边/平衡 → 锁定 3 个',
      '③1 vs 1：轻的就是次品（若平衡则剩下那个是次品）',
      '共需 3 次',
    ],
    type: 'none',
    finalQ: '最少称几次能找出次品？',
    finalUnit: '次',
    finalAns: 3,
    analysisImg: '/img/math/42-L14.png',
  },
]

const HOMEWORK: Problem[] = [
  {
    id: '42-H1',
    title: '巩固1 · 砝码两边称重',
    tag: 'type1',
    tagLabel: '砝码称重组合',
    text: '奇奇有 3 个砝码，重量分别为 <strong>2 克、3 克和 4 克</strong>，砝码可以放在天平的<strong>两边</strong>，用这 3 个砝码可以称出几种不同重量的物体？',
    analysis: [
      '每个砝码 3 种状态：右盘(+) / 不用(0) / 左盘(−) → 3³ = 27 种',
      '去掉全 0 一种 → 26 种，左右镜像两两相同 → 26 ÷ 2 = 13 种组合',
      '逐一列出可称重量（绝对值）：单个 2、3、4；两两相加 5(2+3)、6(2+4)、7(3+4)；两两相减 1(3−2)、2(4−2)、1(4−3)；三个一起 9；三种组合 5(4+3−2)、3(4+2−3)、1(4−3−2)',
      '去重后不同重量：1、2、3、4、5、6、7、9 → 共 8 种',
      '⚠️ 例如 2 出现 4 次（单 2、4−2、4+3−5… 等），都计 1 种',
    ],
    type: 'none',
    finalQ: '能称出几种不同重量？',
    finalUnit: '种',
    finalAns: 8,
    analysisImg: '/img/math/42-H1.png',
  },
  {
    id: '42-H2',
    title: '巩固2 · 棒棒糖三人分账',
    tag: 'type2',
    tagLabel: '公平分账',
    text: '纳纳、约约和立立三人共买了 <strong>15 个相同的棒棒糖</strong>，每人吃 <strong>5 个</strong>。纳纳付了 <strong>9 个</strong>棒棒糖的钱，约约付了 <strong>6 个</strong>棒棒糖的钱，立立没有付钱。吃完后，立立拿出 <strong>25 元钱</strong>补给纳纳和约约，请问<strong>纳纳和约约分别应得多少元</strong>？',
    analysis: [
      '立立吃 5 个，付 25 元 → 每个棒棒糖 25 ÷ 5 = 5 元',
      '纳纳付 9 × 5 = 45 元；吃 5 × 5 = 25 元；应得 45 − 25 = 20 元',
      '约约付 6 × 5 = 30 元；吃 5 × 5 = 25 元；应得 30 − 25 = 5 元',
      '验算：20 + 5 = 25 元 ✓',
    ],
    type: 'none',
    finalQ: '纳纳应得多少元？',
    finalUnit: '元',
    finalAns: 20,
    analysisImg: '/img/math/42-H2.png',
  },
  {
    id: '42-H3',
    title: '巩固3 · 3 空瓶换 1 瓶',
    tag: 'type3',
    tagLabel: '空瓶换水',
    text: '某商店规定：<strong>3 个空瓶可换 1 瓶汽水</strong>。纳纳买了 <strong>12 瓶汽水</strong>，请问他最多可喝多少瓶汽水？（空瓶不够时可借，但要归还相同数量的空瓶）',
    analysis: [
      '思路：每喝 1 瓶净消耗 (3 − 1) = 2 个空瓶',
      '12 瓶汽水喝完后 → 12 个空瓶 → 还可换 12 ÷ 2 = 6 瓶',
      '总共能喝 12 + 6 = 18 瓶',
      '验证：12 空瓶 → 换 4 瓶 + 剩 0 空 → 喝完再得 4 空 → 换 1 瓶 + 剩 1 空 → 借 2 空(共 3) 换 1 瓶 + 喝完归还 → 共 4 + 1 + 1 = 6 瓶',
    ],
    type: 'none',
    finalQ: '最多可喝多少瓶？',
    finalUnit: '瓶',
    finalAns: 18,
    analysisImg: '/img/math/42-H3.png',
  },
  {
    id: '42-H4',
    title: '巩固4 · 木棍测 30 分钟',
    tag: 'type4',
    tagLabel: '计时与量水',
    text: '有两根粗细不均匀且长度不同的木棍，每根木棍点燃后都能燃烧 <strong>2 个小时（120 分钟）</strong>，怎样用这样的两根木棍确定 <strong>30 分钟</strong>的时间？',
    analysis: [
      '木棍 A 两端同时点燃 → 60 分钟烧完；同时木棍 B 一端点燃',
      'A 烧完时（60 分钟过去），B 还剩 60 分钟',
      '立刻把 B 另一端也点燃 → 剩下 60 分钟两端烧 → 30 分钟烧完',
      '从 A 烧完到 B 烧完恰好 30 分钟 ✓',
    ],
    type: 'none',
    finalQ: '测出的时间是多少分钟？',
    finalUnit: '分钟',
    finalAns: 30,
  },
  {
    id: '42-H5',
    title: '巩固5 · 12 升啤酒分 6 升',
    tag: 'type4',
    tagLabel: '计时与量水',
    text: '某人有 <strong>12 升啤酒</strong>一瓶，想从中倒出 <strong>6 升</strong>。他没有 6 升的容器，只有一个 <strong>8 升</strong>的容器和一个 <strong>5 升</strong>的容器。怎样倒才能使 8 升容器中恰好装好 <strong>6 升</strong>啤酒？',
    analysis: [
      '①12 升瓶 → 8 升容器装满：12→4，8→8，5→0',
      '②8 升容器 → 5 升容器装满：8→3，5→5',
      '③5 升容器 → 12 升瓶：12→9，5→0',
      '④8 升容器 → 5 升容器：8→0，5→3',
      '⑤12 升瓶 → 8 升容器装满：12→1，8→8',
      '⑥8 升容器 → 5 升容器装满：8→6 ✓ ，5→5',
      '共 6 步',
    ],
    type: 'none',
    finalQ: '最少倒几步？',
    finalUnit: '步',
    finalAns: 6,
  },
  {
    id: '42-H6',
    title: '巩固6 · 3 硬币不知轻重',
    tag: 'type5',
    tagLabel: '天平找异物',
    text: '有 <strong>3 枚外表完全相同的硬币</strong>，已知其中有一枚假币和真币的重量不一样，但<strong>不知道假币比真币轻还是重</strong>。用一台无砝码的天平，请问至少要称几次才能找出这枚假币，并推断出假币比真币轻还是重？',
    analysis: [
      '设三枚为 A、B、C',
      '第①次：A 与 B 称',
      '若平衡 → 假币是 C（但还不知轻重）→ 需第②次：C 与 A 比较，重就是重、轻就是轻',
      '若 A>B → 假币在 A、B 中（一重一轻可能）→ 需第②次：A 与 C 比较；平衡说明 B 偏轻，A>C 说明 A 偏重',
      '总共 2 次能同时找出假币 + 判定轻重',
    ],
    type: 'none',
    finalQ: '至少需要称几次？',
    finalUnit: '次',
    finalAns: 2,
    analysisImg: '/img/math/42-H6.png',
  },
]

const WORKBOOK: Problem[] = [
  {
    id: '42-W1',
    title: '闯关1 · 4 砝码两边',
    tag: 'type1',
    tagLabel: '砝码称重组合',
    text: '现有重量分别为 <strong>1 克、2 克、3 克、4 克</strong>的 4 个砝码，砝码可放在天平的<strong>两边</strong>，用这 4 个砝码能够称出几种不同重量的物体？',
    analysis: [
      '每个砝码 3 态：3⁴ = 81 种状态，去全 0 = 80，去镜像 ÷2 = 40 种组合',
      '能称的最大重量 = 1+2+3+4 = 10 克',
      '尝试 1~10 每个数能否表示：',
      '1=1；2=2；3=3 或 1+2；4=4 或 1+3；5=2+3 或 4+1；6=2+4 或 1+2+3；7=3+4；8=1+3+4；9=2+3+4；10=1+2+3+4',
      '全部 1~10 都能表示 → 共 10 种不同重量',
    ],
    type: 'none',
    finalQ: '能称出几种不同重量？',
    finalUnit: '种',
    finalAns: 10,
    analysisImg: '/img/math/42-W1.png',
  },
  {
    id: '42-W2',
    title: '闯关2 · 24 巧克力三人分',
    tag: 'type2',
    tagLabel: '公平分账',
    text: '甲、乙、丙三人一起买了 <strong>24 块巧克力</strong>，平均分着吃。乙没带钱，甲出了 <strong>10 块</strong>巧克力的钱，丙出了 <strong>14 块</strong>巧克力的钱。回家后乙拿出 <strong>24 元钱</strong>给甲、丙两人分。请问甲、丙各应拿多少钱？',
    analysis: [
      '三人平分 → 每人吃 24 ÷ 3 = 8 块',
      '乙吃 8 块付 24 元 → 每块 24 ÷ 8 = 3 元',
      '甲付 10 × 3 = 30 元；甲吃 8 × 3 = 24 元；应得 30 − 24 = 6 元',
      '丙付 14 × 3 = 42 元；丙吃 8 × 3 = 24 元；应得 42 − 24 = 18 元',
      '验算：6 + 18 = 24 元 ✓',
    ],
    type: 'none',
    finalQ: '丙应得多少元？',
    finalUnit: '元',
    finalAns: 18,
    analysisImg: '/img/math/42-W2.png',
  },
  {
    id: '42-W3',
    title: '闯关3 · 5 空盒换 1 盒糖',
    tag: 'type3',
    tagLabel: '空瓶换水',
    text: '纳约糖果店活动：吃完糖果后，<strong>5 个空盒可换 1 盒糖</strong>。奇奇和小朋友共买了 <strong>8 盒糖</strong>。每人吃 1 盒，最多有几人能吃到糖果？（空盒不够时可借，但要归还）',
    analysis: [
      '每换 1 盒净消耗 (5 − 1) = 4 个空盒',
      '8 个空盒 → 8 ÷ 4 = 2 盒',
      '总共能吃 8 + 2 = 10 盒 → 10 人',
    ],
    type: 'none',
    finalQ: '最多几人能吃到糖？',
    finalUnit: '人',
    finalAns: 10,
    analysisImg: '/img/math/42-W3.png',
  },
  {
    id: '42-W4',
    title: '闯关4 · 啤酒花费',
    tag: 'type3',
    tagLabel: '空瓶换水',
    text: '饭店里 <strong>5 个空啤酒瓶可换 1 瓶啤酒</strong>，1 瓶 <strong>5 元</strong>。老魏一伙想喝 <strong>20 瓶</strong>啤酒，最少需花多少钱？（空瓶不够时可借，但要归还）',
    analysis: [
      '每换 1 瓶净消耗 (5 − 1) = 4 个空瓶',
      '设买 x 瓶 → 共喝 x + x ÷ 4 = 20 → 5x/4 = 20 → x = 16',
      '即买 16 瓶，凑空瓶共换 4 瓶（最后一次借 1 还 1），合计 20 瓶',
      '花费 = 16 × 5 = 80 元',
    ],
    type: 'none',
    finalQ: '最少花多少钱？',
    finalUnit: '元',
    finalAns: 80,
    analysisImg: '/img/math/42-W4.png',
  },
  {
    id: '42-W5',
    title: '闯关5 · 8 分钟绳测 6 分钟',
    tag: 'type4',
    tagLabel: '计时与量水',
    text: '有两根长短粗细相同的绳子，从一端点火每根都正好 <strong>8 分钟</strong>燃尽。怎样用这两根绳子确定 <strong>6 分钟</strong>的时间？',
    analysis: [
      '绳 A 两端同时点燃 + 绳 B 一端点燃',
      'A 烧完时 4 分钟过去，B 还剩 4 分钟',
      '立刻把 B 另一端也点燃 → 剩下 4 分钟双端烧 → 2 分钟烧完',
      '从开始到 B 烧完共 4 + 2 = 6 分钟 ✓',
    ],
    type: 'none',
    finalQ: '测出多少分钟？',
    finalUnit: '分钟',
    finalAns: 6,
  },
  {
    id: '42-W6',
    title: '闯关6 · 10 升牛奶分 2+2',
    tag: 'type4',
    tagLabel: '计时与量水',
    text: '卖牛奶的人有两桶 <strong>10 升装</strong>的牛奶。两个顾客各带容器买 <strong>2 升</strong>牛奶。一个带 <strong>5 升</strong>容器，另一个带 <strong>4 升</strong>容器。怎样解决？（核心要给两人各分出 2 升）',
    analysis: [
      '先给"带 4 升容器"的顾客：',
      '①10 升桶 → 5 升容器装满：桶 5，5 容器 5',
      '②5 升容器 → 4 升容器装满：5 容器 1，4 容器 4 → 4 升给顾客',
      '③5 升容器剩 1 升倒入 4 升容器 → 1 升装入',
      '④10 升桶 → 5 升容器装满：5 容器 5',
      '⑤5 升容器 → 4 升容器装满（容器中已有 1 升，再加 3 升装满）→ 5 容器剩 2 升 ✓ 给第二位顾客',
      '共约 5 步',
    ],
    type: 'none',
    finalQ: '最少几步可分好？',
    finalUnit: '步',
    finalAns: 5,
  },
  {
    id: '42-W7',
    title: '闯关7 · 18 硬币找轻假',
    tag: 'type5',
    tagLabel: '天平找异物',
    text: '现有形状完全相同的硬币 <strong>18 枚</strong>，其中有 1 枚假币，<strong>假币比真币轻</strong>。用无砝码的天平，至少称几次才能找出这枚假币？',
    analysis: [
      '已知偏轻 → 每次三等分',
      '①把 18 分成 6+6+6，左 6 vs 右 6',
      '   - 平衡 → 假在外 6 枚里；不平 → 假在轻的 6 枚里',
      '②把锁定的 6 枚分成 2+2+2，左 2 vs 右 2',
      '   - 平衡 → 假在外 2 枚里；不平 → 假在轻的 2 枚里',
      '③把 2 枚 1 vs 1，轻的就是假币',
      '共 3 次',
    ],
    type: 'none',
    finalQ: '最少称几次？',
    finalUnit: '次',
    finalAns: 3,
    analysisImg: '/img/math/42-W7.png',
  },
  {
    id: '42-W8',
    title: '闯关8 · 12 硬币不知轻重',
    tag: 'type5',
    tagLabel: '天平找异物',
    text: '有 <strong>12 枚外表完全相同的硬币</strong>，其中一枚是假币，<strong>不知道假币比真币轻还是重</strong>。用无砝码的天平，至少称几次能找出假币并判断轻重？',
    analysis: [
      '①把 12 枚分成 4+4+4 三组：左 4 vs 右 4',
      '   情况 A 平衡 → 假在外 4 枚',
      '   情况 B 不平 → 假在天平 8 枚中，可记录哪边偏重',
      '② A 情况：从外 4 枚取 3 枚 vs 3 枚真币（已知），平衡说明剩 1 枚为假 → 第③次比对定轻重',
      '② B 情况：换位巧妙重称，将一部分嫌疑币与已知真币混合调换 → 可在第②次同时定位 & 判断轻重',
      '③最终 3 次称完即可',
    ],
    type: 'none',
    finalQ: '至少称几次？',
    finalUnit: '次',
    finalAns: 3,
    analysisImg: '/img/math/42-W8.png',
  },
  {
    id: '42-W9',
    title: '闯关9 · 10 箱零件电子秤',
    tag: 'type5',
    tagLabel: '天平找异物',
    text: '有 <strong>10 箱零件</strong>，每箱 10 个。9 箱每个零件重 10 克，1 箱每个重 9 克。能否用<strong>电子秤只称一次</strong>就确定哪一箱重量是 9 克？',
    analysis: [
      '给箱子编号 1 ~ 10，从第 k 号箱中取出 k 个零件，全部放电子秤上',
      '若都是 10 克 → 总重 = (1+2+…+10) × 10 = 550 克',
      '实际称得 W 克 → 缺重 = 550 − W ',
      '次品箱号 = 缺重，因为每个少 1 克：第 k 号箱出 k 个零件，少 k 克即说明假在 k 号箱',
      '只需 1 次电子秤 ✓',
    ],
    type: 'none',
    finalQ: '最少称几次？',
    finalUnit: '次',
    finalAns: 1,
  },
  {
    id: '42-W10',
    title: '闯关10 · 25 人 7 人船渡河',
    tag: 'type6',
    tagLabel: '综合策略',
    text: '一年级一班共 <strong>25 名</strong>同学要渡过一条河。只有一条可乘 <strong>7 人</strong>的橡皮船（无船工），<strong>每过一次河需 3 分钟</strong>。请问最少需多少分钟？',
    analysis: [
      '船无船工 → 中途每次去后必须有 1 人划回（净送 7 − 1 = 6 人）',
      '最后一次不需返航 → 把最后 7 人单独算',
      '前期需送 25 − 7 = 18 人 → 18 ÷ 6 = 3 次往返',
      '总单程数 = 3 × 2 + 1 = 7 趟',
      '总时长 = 7 × 3 = 21 分钟 ✓',
    ],
    type: 'none',
    finalQ: '最少需多少分钟？',
    finalUnit: '分钟',
    finalAns: 21,
  },
  {
    id: '42-W11',
    title: '闯关11 · 3 圆分 10 妖精',
    tag: 'type6',
    tagLabel: '综合策略',
    text: '白雪公主被女巫困住，七个小矮人前去营救。女巫说：<strong>只要在圆形阵法中画出 3 个一样大的圆圈，把 10 个妖精一个一个地分开</strong>就放人。能帮小矮人想想办法吗？',
    analysis: [
      '关键：3 个圆两两相交划分平面，可形成最多 (3×3−3)+1 = 7 个区域',
      '加上"圆形阵法"外圈（女巫的大圆形阵法）相当于第 4 道线 → 进一步细分',
      '巧妙安排 3 个等圆两两相交，圆 + 阵法外圈合起来能把 10 个妖精分别隔在 10 个独立小区域',
      '画法核心：让每个妖精都落入不同的"圆/阵法"组合所形成的区域',
      '所以最少需要 3 个圆 ✓',
    ],
    type: 'none',
    finalQ: '至少需画几个圆？',
    finalUnit: '个',
    finalAns: 3,
  },
  {
    id: '42-W12',
    title: '闯关12 · 两堆火柴博弈',
    tag: 'type6',
    tagLabel: '综合策略',
    text: '有两堆火柴，一堆 <strong>35 根</strong>，另一堆 <strong>24 根</strong>。小纳、小约轮流取，小纳先取。每次只能在<strong>任一堆</strong>中取且不限根数，但不能不取。规定取得最后一根者为胜者。若都采用最佳方法，<strong>小纳第一次取多少根可必胜</strong>？',
    analysis: [
      '必胜策略：让两堆数量相同后，模仿对方在另一堆的操作',
      '一旦两堆相等，对方在 A 堆取 k 根，我就在 B 堆取 k 根',
      '这样两堆始终保持相等 → 最终对方面对 (0, 0) 无法取，我已取完最后一根',
      '小纳第一步：从 35 根那堆取出 35 − 24 = 11 根 → 两堆变成 (24, 24)',
      '此后模仿对方 → 小纳必胜',
    ],
    type: 'none',
    finalQ: '小纳第一次取几根？',
    finalUnit: '根',
    finalAns: 11,
  },
]

const SUPPLEMENT: Problem[] = [
  {
    id: '42-S1',
    title: '附加1 · 大小和尚过河',
    tag: 'type6',
    tagLabel: '综合策略',
    text: '一个大和尚带着两个小和尚过河。大和尚 <strong>50 千克</strong>，每个小和尚 <strong>25 千克</strong>。河上没有桥，他们不会游泳，只有一只最大载重 <strong>50 千克</strong>的小船。怎样让三人全部过河？',
    analysis: [
      '①两个小和尚一起过河（25+25=50 千克）',
      '②留一个小和尚在对岸，另一个把船划回来',
      '③大和尚独自过河（50 千克）',
      '④对岸小和尚把船划回来',
      '⑤两个小和尚再次一起过河',
      '共 5 步全部过河 ✓',
    ],
    type: 'none',
    finalQ: '最少几步可全部过河？',
    finalUnit: '步',
    finalAns: 5,
  },
  {
    id: '42-S2',
    title: '附加2 · 绳子对折 5 次剪',
    tag: 'type6',
    tagLabel: '综合策略',
    text: '把一根绳子对折 <strong>5 次</strong>后，再从中间剪一次，这根绳子被分成了多少段？',
    analysis: [
      '规律：对折 n 次后从中间剪一刀 → 共 2ⁿ + 1 段',
      '对折 1 次：2¹ + 1 = 3 段',
      '对折 2 次：2² + 1 = 5 段',
      '对折 5 次：2⁵ + 1 = 33 段 ✓',
    ],
    type: 'none',
    finalQ: '一共被分成多少段？',
    finalUnit: '段',
    finalAns: 33,
  },
  {
    id: '42-S3',
    title: '附加3 · 六边形切角',
    tag: 'type6',
    tagLabel: '综合策略',
    text: '一个六边形被<strong>切去一个角</strong>之后还剩下几个角？',
    analysis: [
      '依切法不同有三种情况：',
      '① 切线不经过任何顶点 → 切口新生 2 个角 → 6 − 1 + 2 = 7 个角',
      '② 切线经过 1 个顶点 → 切口生 1 个新角 + 顶点 → 仍为 6 个角',
      '③ 切线经过 2 个不相邻顶点 → 切掉 2 角 → 6 − 2 = 5 个角',
      '答：可能剩 5、6 或 7 个角；本题取最大 7',
    ],
    type: 'none',
    finalQ: '最多剩多少个角？',
    finalUnit: '个',
    finalAns: 7,
  },
  {
    id: '42-S4',
    title: '附加4 · 49 同学过河',
    tag: 'type6',
    tagLabel: '综合策略',
    text: '三年级一班共 <strong>49 名</strong>同学要渡河，只有一条可乘 <strong>7 人</strong>的橡皮船。<strong>每过一次河需 3 分钟</strong>。用这条橡皮艇把全班同学都运到对岸，最少需多少分钟？',
    analysis: [
      '每次往返净送 7 − 1 = 6 人',
      '最后一次不返 → 先扣 7 人 → 剩 49 − 7 = 42 人',
      '42 ÷ 6 = 7 次往返 → 7 × 2 = 14 趟单程',
      '加最后一次单程 → 共 15 趟单程',
      '总耗时 = 15 × 3 = 45 分钟 ✓',
    ],
    type: 'none',
    finalQ: '最少需多少分钟？',
    finalUnit: '分钟',
    finalAns: 45,
  },
  {
    id: '42-S5',
    title: '附加5 · 棋子盒子',
    tag: 'type6',
    tagLabel: '综合策略',
    text: '若干个同样的盒子排成一排，小明把 <strong>五十多个同样的棋子</strong>分装在盒中，其中只有 1 个盒子<strong>没装棋子</strong>。然后他外出。小光从每个有棋子的盒子里各拿 1 个棋子放在空盒内，再把盒子重新排了一下。小明回来仔细查看，<strong>没发现动过</strong>。请问共有多少个盒子？',
    analysis: [
      '"看不出来"的关键：操作前后盒子棋子数的分布完全不变',
      '原本盒中棋子数必须是从 0 开始的连续自然数 0, 1, 2, …, n',
      '总棋子数 = 0+1+…+n = n(n+1)/2 介于 51~59',
      '试 n = 10：0+1+…+10 = 55 ✓ 在五十多',
      '所以盒子数 = n + 1 = 11 个 ✓',
    ],
    type: 'none',
    finalQ: '共有几个盒子？',
    finalUnit: '个',
    finalAns: 11,
  },
  {
    id: '42-S6',
    title: '附加6 · 4×4 加 4 碟子',
    tag: 'type6',
    tagLabel: '综合策略',
    text: '桌上放了 4 排碟子，每排 4 个，共 <strong>16 个</strong>。现在<strong>再放 4 个碟子</strong>，要使<strong>横看、竖看、对角线看</strong>每排都是 5 个，<strong>碟子总数</strong>是几？',
    analysis: [
      '每行、每列、每条对角线都恰好多 1 个 → 新增 4 个分别占 4 个不同行 + 4 个不同列',
      '可放在坐标 (1,1)、(2,3)、(3,4)、(4,2) 上',
      '验证：每行/每列/两条对角线都各多 1 个，由 4 个变 5 个 ✓',
      '总数 = 原 16 + 新 4 = 20 个',
    ],
    type: 'none',
    finalQ: '碟子总数是多少？',
    finalUnit: '个',
    finalAns: 20,
  },
]

export const PROBLEMS: ProblemSet = {
  pretest: PRETEST,
  lesson: LESSON,
  homework: HOMEWORK,
  workbook: WORKBOOK,
  supplement: SUPPLEMENT,
}

export const PROBLEM_TYPES = [
  {
    tag: 'type1',
    color: 'rose',
    label: '题型1 · 砝码称重组合',
    desc: '单边放砝码：求子集和；可放两边：求 ±组合的绝对值。注意去重——多个组合可能得到相同重量。',
    example: '例：1+2+5+7 单边放 → 15 个子集和去重 = 13 种',
  },
  {
    tag: 'type2',
    color: 'amber',
    label: '题型2 · 公平分账',
    desc: '用"没付钱的人补出的钱"反推单价：单价 = 补偿金 ÷ 该人吃的份数。每人应得 = 实付钱 − 实吃钱。',
    example: '例：丙补 6 元/3 块 = 2 元/块；甲付 10 − 吃 6 = 得 4 元',
  },
  {
    tag: 'type3',
    color: 'green',
    label: '题型3 · 空瓶换水',
    desc: '允许借空瓶时：可喝瓶数 = 总空瓶 ÷ (换购比 − 1)。每喝 1 瓶相当于净消耗 (换购比 − 1) 个空瓶。',
    example: '例：4 换 1，15 空瓶 → 15 ÷ 3 = 5 瓶',
  },
  {
    tag: 'type4',
    color: 'sky',
    label: '题型4 · 计时与量水',
    desc: '绳子/香两端同时点燃 → 时间减半；量水靠"装满-倒满-差值"组合，配合三个容器互相倒水标刻度。',
    example: '例：两根 12 分钟绳测 9 分钟 = 6 (两端) + 3 (两端再点)',
  },
  {
    tag: 'type5',
    color: 'purple',
    label: '题型5 · 天平找异物',
    desc: '已知轻重：每次称把目标分 3 等分 → 3ⁿ ≥ 总数 → n 次。不知轻重通常多需 1 次确认偏向。',
    example: '例：27 个球(已知轻) → 3³=27 → 3 次',
  },
  {
    tag: 'type6',
    color: 'teal',
    label: '题型6 · 综合策略',
    desc: '过河、博弈、剪绳、几何切割等没有公式的智力题：模型化 → 找规律 / 利用对称 / 构造必胜策略。',
    example: '例：35+24 火柴 → 先取 11 根使两堆相等，模仿对方 → 必胜',
  },
]

export const TYPE_STYLE: Record<
  string,
  { bg: string; border: string; titleColor: string; textColor: string }
> = {
  type1: {
    bg: 'bg-rose-50',
    border: 'border-l-rose-500',
    titleColor: 'text-rose-800',
    textColor: 'text-rose-900',
  },
  type2: {
    bg: 'bg-amber-50',
    border: 'border-l-amber-500',
    titleColor: 'text-amber-800',
    textColor: 'text-amber-900',
  },
  type3: {
    bg: 'bg-green-50',
    border: 'border-l-green-500',
    titleColor: 'text-green-800',
    textColor: 'text-green-900',
  },
  type4: {
    bg: 'bg-sky-50',
    border: 'border-l-sky-500',
    titleColor: 'text-sky-800',
    textColor: 'text-sky-900',
  },
  type5: {
    bg: 'bg-purple-50',
    border: 'border-l-purple-500',
    titleColor: 'text-purple-800',
    textColor: 'text-purple-900',
  },
  type6: {
    bg: 'bg-teal-50',
    border: 'border-l-teal-500',
    titleColor: 'text-teal-800',
    textColor: 'text-teal-900',
  },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-rose-100 text-rose-800',
  type2: 'bg-amber-100 text-amber-800',
  type3: 'bg-green-100 text-green-800',
  type4: 'bg-sky-100 text-sky-800',
  type5: 'bg-purple-100 text-purple-800',
  type6: 'bg-teal-100 text-teal-800',
}
