import type { Problem, ProblemSet } from './type'
import CubeFigure from '@/components/math/lesson38/Figure/CubeFigure'
import RectBoxFigure from '@/components/math/lesson38/Figure/RectBoxFigure'
import MuseumFigure from '@/components/math/lesson38/Figure/MuseumFigure'
import ExhibitFigure from '@/components/math/lesson38/Figure/ExhibitFigure'
import StreetMapFigure from '@/components/math/lesson38/Figure/StreetMapFigure'
import HomeworkFig1 from '@/components/math/lesson38/Figure/HomeworkFig1'
import HomeworkFig2 from '@/components/math/lesson38/Figure/HomeworkFig2'
import HomeworkFig3 from '@/components/math/lesson38/Figure/HomeworkFig3'
import HomeworkFig4 from '@/components/math/lesson38/Figure/HomeworkFig4'
import HomeworkFig5 from '@/components/math/lesson38/Figure/HomeworkFig5'
import HomeworkFig6 from '@/components/math/lesson38/Figure/HomeworkFig6'
import LessonFig2 from '@/components/math/lesson38/Figure/LessonFig2'
import LessonFig6 from '@/components/math/lesson38/Figure/LessonFig6'
import WorkbookFig12 from '@/components/math/lesson38/Figure/WorkbookFig12'
import PretestFig1 from '@/components/math/lesson38/Figure/PretestFig1'
import PretestFig2 from '@/components/math/lesson38/Figure/PretestFig2'
import PretestFig3 from '@/components/math/lesson38/Figure/PretestFig3'
import PretestFig4 from '@/components/math/lesson38/Figure/PretestFig4'
import PretestFig5 from '@/components/math/lesson38/Figure/PretestFig5'

const LESSON: Problem[] = [
  // ── 例题 ──
  {
    id: '38-L1',
    title: '例1 · 判断一笔画',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '请判断下面图形能否一笔画。<br/>图①：三角形＋底边延伸出奇点（2奇点）；图②：矩形内切圆（4奇点）；图③：三角形底部带椭圆弧（0奇点）；图④：平行四边形＋两对角线交叉（4奇点）。',
    analysis: [
      '一笔画条件：奇点数 = 0（闭合回路）或 2（从一奇点到另一奇点）',
      '图①：2个奇点 → ✓ 能一笔画（从一奇点出发到另一奇点）',
      '图②：4个奇点 → ✗ 不能一笔画',
      '图③：0个奇点 → ✓ 能一笔画（可从任意点出发并回到该点）',
      '图④：4个奇点 → ✗ 不能一笔画',
    ],
    type: 'none',
    finalQ: '四个图形中，能一笔画的有几个？',
    finalUnit: '个',
    finalAns: 2,
  },
  {
    id: '38-L2',
    title: '例2 · 六面体蚂蚁比赛',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '下图六面体的顶点 <strong>B</strong> 和 <strong>E</strong> 处各有一只蚂蚁，它们比赛看谁能一次不重复地爬过所有的棱线，最终到达顶点 <strong>D</strong>。已知爬行速度相同，那么<strong>在何处的蚂蚁能获胜</strong>？',
    analysis: [
      '把棱线看作图的边，顶点为图的节点，计算各顶点度数',
      '六面体（5顶点9条棱）：D度数=3（奇），A度数=4（偶），B度数=4（偶），C度数=4（偶），E度数=3（奇）',
      '共2个奇点：D 和 E → 欧拉路径存在，路径恰好从E到D（或D到E）',
      'E处蚂蚁：从奇点E出发 → 沿欧拉路径 → 无回溯直达D ✓ 获胜！',
      'B处蚂蚁：从偶点B出发 → 不能完成欧拉路径，必须回溯 → 耗时更长 ✗',
      '✅ E处的蚂蚁获胜',
    ],
    type: 'none',
    finalQ: '哪处的蚂蚁能获胜？（B处=1，E处=2）',
    finalUnit: '',
    finalAns: 2,
    figureNode: <LessonFig2 />,
  },
  {
    id: '38-L3',
    title: '例3 · 哥尼斯堡七桥',
    tag: 'type5',
    tagLabel: '欧拉路径',
    text: '如下图所示，两条河流的交汇处有两个岛，有<strong>七座桥</strong>连接这两个岛及河岸（节点A、B、C、D、E）。请问：一个散步者能否<strong>一次不重复地走遍这七座桥</strong>？',
    analysis: [
      '把每个陆地/岛看作节点，每座桥看作连接两节点的边',
      '统计各节点的桥数（度数）：A=3（奇），B=3（奇），C=5（奇），D=3（奇），E=3（奇）',
      '共5个奇点（若原图为4奇点同理：超过2个奇点）',
      '一笔画条件：奇点数须为0或2；本题奇点数 ≥ 4 → 不满足',
      '❌ 散步者不能一次不重复地走遍所有的桥',
    ],
    type: 'none',
    finalQ: '散步者能否一次不重复走遍七桥？（能=1，不能=0）',
    finalUnit: '',
    finalAns: 0,
  },
  {
    id: '38-L4',
    title: '例4 · 最少几笔画出',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '观察下列各图，每个图形最少需要几笔画出？<br/>图①：1间小房子（屋顶+地板）；图②：2间并排小房子；图③：3间并排小房子；图④：4间并排小房子。',
    analysis: [
      '最少笔数 = 奇点数 ÷ 2（奇点数为0时最少1笔）',
      '图①（1间房）：4个奇点 → 4÷2 = 2笔',
      '图②（2间房）：4个奇点 → 4÷2 = 2笔',
      '图③（3间房）：6个奇点 → 6÷2 = 3笔',
      '图④（4间房）：8个奇点 → 8÷2 = 4笔',
      '规律：每增加1间房，奇点数增加2，笔数增加1',
    ],
    type: 'none',
    finalQ: '四个图形最少笔数之和是多少？（2+2+3+4=？）',
    finalUnit: '笔',
    finalAns: 11,
  },
  {
    id: '38-L5',
    title: '例5 · 添线或去线使能一笔画',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '下面的图形能不能一笔画出？如果不能，请在每个图中分别<strong>添加或者去掉最少的线</strong>，使它们都能一笔画出。<br/>左图：三角形+底部延长线形成X形；右图：正六边形+内部连线组合。',
    analysis: [
      '左图：统计奇点数 → 4个奇点 → 不能一笔画',
      '左图修改：去掉1条线（连接两奇点的线）→ 奇点减为2 → 能一笔画 ✓',
      '右图：统计奇点数 → 8个奇点 → 不能一笔画',
      '右图修改：去掉3条线（连接3对奇点的线），留2奇点 → 能一笔画 ✓',
      '口诀：去奇点 = 添1条线消2奇点；去1条线消2奇点',
    ],
    type: 'none',
    finalQ: '左图有几个奇点？',
    finalUnit: '个',
    finalAns: 4,
  },
  {
    id: '38-L6',
    title: '例6 · 林间小路最多走多少米',
    tag: 'type7',
    tagLabel: '最长路程',
    text: '张爷爷在林间小路散步，现在要从某一点出发，如果<strong>每条小路只允许走一次</strong>，他<strong>最多能走多少米</strong>？图中各段路程如图所示（单位：km）。',
    analysis: [
      '把路网图转化为图论问题：节点=路口，边=路段',
      '统计路网中各节点的度数，找出奇点',
      '路网共有6个奇点',
      '最长单次路程 = 总路程 - 需要跳过的最少路段',
      '6个奇点→选2个作为起终点→剩余4个奇点配成2对→各对间选最短路跳过',
      '各路段长度：4+4+4+2+2+2+1 = 19 km（跳过最短的2条路段后仍最大化）',
      '✅ 最多能走 19 km',
    ],
    type: 'none',
    finalQ: '张爷爷最多能走多少千米？',
    finalUnit: 'km',
    finalAns: 19,
    figureNode: <LessonFig6 />,
  },
  // ── 练一练 ──
  {
    id: '38-L7',
    title: '练1 · 判断一笔画（2图）',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '下面哪些图形可以一笔画，请判断。<br/>左图：两个三角形共享底边，中间有两个交点（2奇点）；右图：矩形底部悬挂两个小圆（0奇点）。',
    analysis: [
      '左图：三角形＋内部连接线，2个奇点 → ✓ 能一笔画',
      '右图：矩形底边连接两小圆，所有顶点度数均为偶数（0奇点）→ ✓ 能一笔画',
      '两图均能一笔画！',
    ],
    type: 'none',
    finalQ: '两个图形中，能一笔画的有几个？',
    finalUnit: '个',
    finalAns: 2,
  },
  {
    id: '38-L8',
    title: '练2 · 游乐场路线比较',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '如图所示，线段代表游乐场中的小路，文文和立立分别站在 <strong>A</strong>、<strong>B</strong> 两点处，他们约定以相同的速度分别从各自位置出发，走遍游乐场的每一条小路，最终到达 <strong>C</strong> 处的摩天轮，请问<strong>谁先到达</strong>？',
    analysis: [
      '把路图转化为图论问题，统计各节点度数',
      '图中共有2个奇点：A（文文起点）和 C（终点）',
      'B 是偶点（立立起点）',
      '文文从A（奇点）出发 → 欧拉路径恰好 A→C，无需任何回溯 ✓',
      '立立从B（偶点）出发 → 不在奇点上，必须多走一段才能完成所有路 ✗',
      '✅ 文文先到达 C',
    ],
    type: 'none',
    finalQ: '谁先到达C？（文文=1，立立=2）',
    finalUnit: '',
    finalAns: 1,
  },
  {
    id: '38-L9',
    title: '练3 · 五桥问题',
    tag: 'type5',
    tagLabel: '欧拉路径',
    text: '在一条河中有两个岛，河上的<strong>五座桥</strong>把陆地与小岛连接起来。请问：一个散步者能否<strong>一次不重复地走遍这五座桥</strong>？',
    analysis: [
      '节点：陆地C（北岸）、岛A（左岛）、岛B（右岛）、陆地D（南岸）',
      '桥（边）分布：C-岛A（2座），C-岛B（1座），岛A-岛B（1座），岛A-D（1座）',
      '各节点度数：C=3（奇），岛A=4（偶），岛B=2（偶），D=1（奇）',
      '共2个奇点（C和D）→ 满足一笔画条件！',
      '✅ 能！从C出发经过所有5座桥，最终到达D',
    ],
    type: 'none',
    finalQ: '散步者能否一次不重复走遍五桥？（能=1，不能=0）',
    finalUnit: '',
    finalAns: 1,
  },
  {
    id: '38-L10',
    title: '练4 · 两图最少几笔',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '下图中的每个图形最少需要几笔画出？<br/>左图：中心点向外8条辐射线（星形，8奇点）；右图：立体盒子形（正面矩形＋内部两小圆，8奇点）。',
    analysis: [
      '左图（辐射星形）：8个端点各度数=1（奇点），共8奇点 → 8÷2 = 4笔',
      '右图（盒子＋内圆）：4个主顶点+4个圆上交点各为奇点，共8奇点 → 8÷2 = 4笔',
      '两图最少笔数相同，各需4笔',
    ],
    type: 'none',
    finalQ: '两个图形最少笔数之和是多少？（4+4=？）',
    finalUnit: '笔',
    finalAns: 8,
  },
  {
    id: '38-L11',
    title: '练5 · 四棱锥添铁丝',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '下图是一个用铁丝围成的<strong>四棱锥框架</strong>，小蚂蚁想从某一个顶点开始爬，发现总是没有办法一次不重复地爬过所有的铁丝，请你在任意两个点之间<strong>再添加或去掉一根直的铁丝</strong>来帮助小蚂蚁！顶点为 A、B、C、D（底面）和 E（顶点）。',
    analysis: [
      '四棱锥有5个顶点，8条棱',
      '各顶点度数：E=4（偶），A=3（奇），B=3（奇），C=3（奇），D=3（奇）',
      '共4个奇点（A,B,C,D）→ 不能一笔画',
      '解决方案：在两个奇点之间添加1根铁丝，将它们变为偶点',
      '例如：添加 A-C 铁丝 → A和C各+1，度数变为4（偶）→ 剩余2奇点B和D → 能一笔画！',
      '✅ 只需添加1根铁丝即可',
    ],
    type: 'none',
    finalQ: '需要添加几根铁丝？',
    finalUnit: '根',
    finalAns: 1,
  },
  {
    id: '38-L12',
    title: '练6 · 学校道路最多走多少米',
    tag: 'type7',
    tagLabel: '最长路程',
    text: '下图是纳约学校内的道路示意图（3×3方格，每一小段路的长度都是 <strong>100 米</strong>），立立现在要任选一点作为起点，沿着每一段小路前进，如果<strong>每条路只允许走一次</strong>，请问他<strong>最多能走多少米</strong>？',
    analysis: [
      '3×3方格路网：4×4=16个路口，共 3×4+3×4=24 段路，总长 24×100=2400 m',
      '统计各路口度数：4个角落（度数2，偶点），8个边缘内部路口（度数3，奇点），4个内部路口（度数4，偶点）',
      '共8个奇点 → 最少需要 8÷2=4 段路程才能覆盖全图',
      '单次最长路程 = 选1对奇点作起终点，剩余6个奇点配3对，跳过3条最短路段',
      '3条最短路段（各100m）：总跳过 = 3×100 = 300 m',
      '最长单次路程 = 2400 − 300 = 2100 m',
    ],
    type: 'none',
    finalQ: '立立最多能走多少米？',
    finalUnit: '米',
    finalAns: 2100,
  },
]

const WORKBOOK: Problem[] = [
  {
    id: '38-W1',
    title: '闯关1 · 判断四图一笔画',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '下面的图形，哪些能一笔画出？哪些不能一笔画出？<br/>图①：矩形内嵌X（对角线）；图②：三角形内有垂直线段；图③：矩形内切圆（菱形套矩形）；图④：小车形状（车身+两轮，但车轮与车身仅点接触，不连通）。',
    analysis: [
      '图①（矩形+X）：4个角各度数3（奇），中心度数4（偶）→ 4奇点 ✗',
      '图②（三角形+内垂线）：有2个奇点 → ✓ 能一笔画',
      '图③（矩形内切圆/菱形套矩形）：所有交点度数均为偶数（0奇点）→ ✓ 能一笔画',
      '图④（小车）：车身与轮子仅在顶点相切，图不连通 → ✗ 不能一笔画',
      '✓ 的有图②和图③，共2个',
    ],
    type: 'none',
    finalQ: '四个图形中能一笔画出的有几个？',
    finalUnit: '个',
    finalAns: 2,
  },
  {
    id: '38-W2',
    title: '闯关2 · 判断并标起终点',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '下面各图形，能不能一笔画？能一笔画的图形起点和终点各在哪里？<br/>图①：圆圈套矩形；图②：两圆用线段相连（4节点交叉）；图③：三角形+底部高线（多交叉）；图④：矩形内有多条水平线分割。',
    analysis: [
      '图①（圆套矩形）：2个奇点 → ✓ 能一笔画，起终点为两个奇点',
      '图②（两圆连线）：4个奇点 → ✗ 不能一笔画',
      '图③（三角形+高线）：6个奇点 → ✗ 不能一笔画',
      '图④（矩形+内线）：6个奇点 → ✗ 不能一笔画',
      '只有图①能一笔画（共1个）',
    ],
    type: 'none',
    finalQ: '四个图形中能一笔画出的有几个？',
    finalUnit: '个',
    finalAns: 1,
  },
  {
    id: '38-W3',
    title: '闯关3 · 四图最少几笔',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '下面各图，至少需要几笔画出？<br/>图①：小车形状（车身+两轮完整连接）；图②：桶形（梯形+弧线）；图③：2×2方格；图④：L形方格组合。',
    analysis: [
      '图①（小车）：12个奇点 → 12÷2 = 6笔',
      '图②（桶形）：4个奇点 → 4÷2 = 2笔',
      '图③（2×2方格）：0个奇点（全偶）→ 1笔（欧拉回路）',
      '图④（L形方格）：6个奇点 → 6÷2 = 3笔',
      '四图最少笔数：6+2+1+3 = 12笔',
    ],
    type: 'none',
    finalQ: '四个图形最少笔数之和是多少？（6+2+1+3=？）',
    finalUnit: '笔',
    finalAns: 12,
  },
  {
    id: '38-W4',
    title: '闯关4 · 最少加几条线一笔画',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '下面的图形能否一笔画？如果不能，<strong>至少添加几条线</strong>就可以一笔画出？<br/>图①：大矩形内竖线平分（2格）；图②：两矩形中间有弧线连接；图③：两矩形+内嵌小矩形。',
    analysis: [
      '图①（大矩形平分）：0个奇点（全偶）→ ✓ 已能一笔画，加0条线',
      '图②（两矩形+弧线）：4个奇点 → 需添加1条线连接1对奇点 → 2奇点 → 能一笔画',
      '图③（两矩形+内矩形）：6个奇点 → 需添加2条线各连接1对奇点 → 2奇点 → 能一笔画',
      '三图需添加线数：0+1+2 = 3条',
    ],
    type: 'none',
    finalQ: '三个图形各需添加线数之和是多少？（0+1+2=？）',
    finalUnit: '条',
    finalAns: 3,
  },
  {
    id: '38-W5',
    title: '闯关5 · 去掉一条线后一笔画',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '下面的图形都不能一笔画出，请你在<strong>每个图中去掉一条线</strong>，使它们都能够一笔画出。<br/>左图：矩形＋内切圆＋连线（4奇点）；右图：矩形+X形重叠图案（4奇点）。',
    analysis: [
      '左图：4个奇点 → 去掉连接2个奇点的那条线 → 2奇点 → 能一笔画',
      '右图：4个奇点 → 去掉连接2个奇点的那条线 → 2奇点 → 能一笔画',
      '每图各去掉1条线，两图共去掉2条线',
    ],
    type: 'none',
    finalQ: '两个图形各需去掉1条线，两图合计去掉几条线？',
    finalUnit: '条',
    finalAns: 2,
  },
  {
    id: '38-W6',
    title: '闯关6 · 添加或去掉最少的线',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '下面的图形都不能一笔画出，请你<strong>添加或去掉最少的线</strong>，使它们都能够一笔画出。<br/>左图：嵌套矩形（外矩形＋内矩形＋连接线，4奇点）；右图：梯形＋内部X连线（4奇点）。',
    analysis: [
      '左图：4个奇点 → 去掉1条连接两奇点的线 → 2奇点 → 能一笔画',
      '右图：4个奇点 → 添加1条线连接另2个奇点 → 2奇点 → 能一笔画',
      '两图合计修改：去1条+加1条 = 共修改2条',
    ],
    type: 'none',
    finalQ: '两图合计需要添加或去掉的线共几条？',
    finalUnit: '条',
    finalAns: 2,
  },
  {
    id: '38-W7',
    title: '闯关7 · 甲乙昆虫谁能爬遍',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '下图中的线段代表小路，请你考虑一下，<strong>甲、乙两只昆虫分别从现在所在的地点出发，能够一次不重复爬遍所有小路的是哪只昆虫</strong>？图形为矩形＋两对角线，甲在顶部奇点，乙在左侧边上偶点。',
    analysis: [
      '矩形＋两对角线：4个顶点各度数3（奇），中心交叉点度数4（偶）→ 4个奇点',
      '欧拉路径：只能从一个奇点出发到另一个奇点，共2个奇点可作起终点',
      '甲位于某个奇点位置 → 甲可以作为欧拉路径的起点，一次不重复爬遍所有路 ✓',
      '乙位于偶点位置 → 乙不能作为欧拉路径的起点，必须在途中多走 ✗',
      '✅ 甲能一次不重复爬遍所有小路',
    ],
    type: 'none',
    finalQ: '哪只昆虫能一次不重复爬遍所有小路？（甲=1，乙=2）',
    finalUnit: '',
    finalAns: 1,
  },
  {
    id: '38-W8',
    title: '闯关8 · 游乐园谁先出',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '周末纳纳和约约到游乐园去玩耍，两个人同时分别从 <strong>A</strong>、<strong>B</strong> 出发，以相同的速度<strong>玩遍所有的项目</strong>，最后从出口出来。那么<strong>谁出来的时间更早一些</strong>？（图为矩形＋内部X格子，出口在右侧，纳纳在A（左下奇点），约约在B（顶部中间偶点））',
    analysis: [
      '分析路网图：矩形+内部对角线组成的格子',
      '统计各节点度数，确定奇点位置',
      '奇点之一：A（纳纳出发点）；另一奇点：出口（右侧）',
      '纳纳（A，奇点）→ 欧拉路径直接从A到出口，无需回溯 ✓',
      '约约（B，偶点）→ 不是奇点，必须额外回溯一段路 ✗',
      '✅ 纳纳先出来',
    ],
    type: 'none',
    finalQ: '谁先从出口出来？（纳纳=1，约约=2）',
    finalUnit: '',
    finalAns: 1,
  },
  {
    id: '38-W9',
    title: '闯关9 · 迷宫出入口设在哪',
    tag: 'type5',
    tagLabel: '欧拉路径',
    text: '下图是一个迷宫通道的平面图，天天想要不重复地走遍每条通道，那么<strong>出、入口应该分别设在哪里呢</strong>？（图中有节点 A、B、G、H、I、J、K、C、D、E、F 等）',
    analysis: [
      '把每个交叉点/通道端点看作节点，每条通道看作边',
      '统计所有节点的通道数（度数）',
      '找出度数为奇数的节点（奇点）',
      '若奇点数=2：入口和出口就设在这2个奇点上',
      '本图分析：奇点为 H 和 B（各连接奇数条通道）',
      '✅ 入口设在H，出口设在B（或反之）',
    ],
    type: 'none',
    finalQ: '迷宫图中共有几个奇点？',
    finalUnit: '个',
    finalAns: 2,
  },
  {
    id: '38-W10',
    title: '闯关10 · 展览馆能否穿过所有门',
    tag: 'type5',
    tagLabel: '欧拉路径',
    text: '下图是某展览馆的平面图，一个参观者能否<strong>不重复地穿过每一扇门</strong>？如果不能，请说明理由；如果能，应从哪开始走？（左图：三角形展厅+外部，右图：矩形展馆多房间）',
    analysis: [
      '左图（三角形展馆）：把每个房间和室外看作节点，每扇门看作边',
      '左图统计各区域度数：发现有4个奇点 → 不能不重复穿过所有门',
      '右图（矩形展馆）：统计各区域度数，发现有2个奇点',
      '右图：2个奇点 → 能！从一个奇点进入，在另一奇点离开',
      '左图：4个奇点 → ✗ 不能',
    ],
    type: 'none',
    finalQ: '左图展览馆能否不重复穿过所有门？（能=1，不能=0）',
    finalUnit: '',
    finalAns: 0,
  },
  {
    id: '38-W11',
    title: '闯关11 · 邮递员送信最优路线',
    tag: 'type5',
    tagLabel: '欧拉路径',
    text: '邮递员叔叔要将 <strong>11 封信</strong>分别送到下图中的 <strong>11 个地点</strong>，不走重复路，怎样走最合适？（图形为三角形路网，节点 A-K 共11个，需从某点出发经过所有节点不重复走完所有路段）',
    analysis: [
      '把地点看作节点，路段看作边，统计各节点度数',
      '图中共有2个奇点：B 和 C',
      '欧拉路径：从B出发 → 经过所有路段不重复 → 到达C（或反向）',
      '这样的路线恰好满足"不走重复路，走遍所有路段"的要求',
      '✅ 起点：B，终点：C（或起点：C，终点：B）',
    ],
    type: 'none',
    finalQ: '邮递员路线图中共有几个奇点？',
    finalUnit: '个',
    finalAns: 2,
  },
  {
    id: '38-W12',
    title: '闯关12 · 邮递员最短投信路程',
    tag: 'type7',
    tagLabel: '最长路程',
    text: '一个邮递员投递信件要走的街道如图所示，图中数字表示各条街道长度（单位：千米），他从<strong>邮局出发</strong>，要<strong>走遍各街道，最后回到邮局</strong>。怎样走才能使所走的行程最短？全程多少千米？',
    analysis: [
      '要走遍所有街道并回到出发点 → 这是中国邮递员问题（求最短欧拉回路）',
      '统计路口度数，找出奇点',
      '图中奇点对应的重复路段：对奇点进行最优配对，重复走配对间的最短路径',
      '基础街道总长 = (2+1+2)×2 + 4×3 + 2×2 = 10+12+4 = 26 km',
      '奇点配对后需额外重复路段 = 1×4 = 4 km',
      '最短总路程 = (2+1+2)×2 + 4×3 + 2×2 + 1×4 = 10+12+4+4 = 30 km',
    ],
    type: 'none',
    finalQ: '邮递员最短路程是多少千米？',
    finalUnit: 'km',
    finalAns: 30,
    figureNode: <WorkbookFig12 />,
  },
]

const HOMEWORK: Problem[] = [
  {
    id: '38-H1',
    title: '课后1 · 判断一笔画',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '请判断下面三个图形能否一笔画。<br/>图①：土星环形（大椭圆＋倾斜环＋小圆）；图②：两个圆圈用两条线相连；图③：矩形内接菱形（菱形角点在矩形各边中点）。',
    analysis: [
      '一笔画条件：奇点数 = 0（闭合回路）或 2（从一个奇点到另一个奇点）',
      '图①：大椭圆与斜环相交产生多个奇点（>2）→ ✗ 不能一笔画',
      '图②：两圆与连接线交于4个奇点 → ✗ 不能一笔画',
      '图③：矩形4角各连接2条边=度数2（偶点），菱形4角（=矩形边中点）各连接矩形2边+菱形2边=度数4（偶点），全是偶点 → ✓ 能一笔画',
    ],
    type: 'none',
    finalQ: '三个图形中，能一笔画的有几个？',
    finalUnit: '个',
    finalAns: 1,
    figureNode: <HomeworkFig1 />,
  },
  {
    id: '38-H2',
    title: '课后2 · 浇花路线比较',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '老师让同学们给校园里所有道路上的花浇水，小晴和图图同时分别从 <strong>A</strong>、<strong>B</strong> 出发，以相同的速度浇完所有道路的花，最后到达 <strong>C</strong>。请问：<strong>两人谁先到达 C</strong>？',
    analysis: [
      '把道路看作一笔画图：矩形＋两条对角线，共5个顶点',
      '统计各顶点度数：4个角各连接2条矩形边＋1条对角线＝度数3（奇点），中心交叉点度数4（偶点）',
      '共4个奇点：C（左上）、A（右上）、左下、B（右下或底部）',
      '两人各自须走完所有道路，4个奇点→需要额外重复走 2 段路',
      '自然配对：A-C 为一对奇点，B-第4奇点 为另一对',
      '小晴从A出发，沿欧拉路径直抵C，无需额外回溯',
      '图图从B出发，须先到达第4奇点再折返C，多走额外路程',
      '✅ 小晴先到 C',
    ],
    type: 'none',
    finalQ: '谁先到C？（填1=小晴先到，填2=图图先到）',
    finalUnit: '',
    finalAns: 1,
    figureNode: <HomeworkFig2 />,
  },
  {
    id: '38-H3',
    title: '课后3 · 图书馆参观路线',
    tag: 'type5',
    tagLabel: '欧拉路径',
    text: '下图是某市图书馆的示意图，共有五个区域 <strong>A、B、C、D、E</strong>。桑桑要去图书馆看书，如果他要一次不重复地穿过每扇门，那么他应该如何走？请帮忙标出入口和出口及具体的线路图。',
    analysis: [
      '把每个区域和室外看作"顶点"，每扇门看作连接两顶点的"边"',
      '统计各区域的门数（度数）：A=4扇（偶点），B=4扇（偶点），C=3扇（奇点），D=3扇（奇点），E=4扇（偶点），室外=2扇（偶点）',
      '奇点数=2（区域C和区域D）→满足一笔画条件！',
      '入口选奇点C区域对应的外门，出口选奇点D区域对应的外门',
      '✅ 能找到路线：从C区域入口进 → 依次穿过所有门 → 从D区域出口出',
    ],
    type: 'none',
    finalQ: '图书馆图中共有几个奇点？',
    finalUnit: '个',
    finalAns: 2,
    figureNode: <HomeworkFig3 />,
  },
  {
    id: '38-H4',
    title: '课后4 · 最少几笔画出',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '观察下列各图，每个图形最少需要几笔画出？<br/>图①：五边形加全部对角线；图②：大圆＋8条辐条＋内圆；图③：三间相连的小房子。',
    analysis: [
      '最少笔数 = 奇点数 ÷ 2（奇点数为0时最少需1笔，即欧拉回路）',
      '图①（五边形+对角线）：统计各顶点度数，共4个奇点 → 最少 4÷2=2 笔',
      '图②（圆+辐条+内圆）：8条辐条各在外圆产生1个奇点，共8个奇点 → 最少 8÷2=4 笔',
      '图③（三房子）：统计各顶点度数，共8个奇点 → 最少 8÷2=4 笔',
    ],
    type: 'none',
    finalQ: '三个图形最少笔数之和是多少？（2＋4＋4=？）',
    finalUnit: '笔',
    finalAns: 10,
    figureNode: <HomeworkFig4 />,
  },
  {
    id: '38-H5',
    title: '课后5 · 添线或去线使能一笔画',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '下面的图形能否一笔画成？如果不能，请添加或者去掉一条线，使它们都能一笔画出。<br/>左图：矩形＋内嵌矩形＋X；右图：三个相切圆加竖向连接线。',
    analysis: [
      '左图：统计奇点数 → 4个奇点（不满足条件）',
      '左图修改：添加一条连接某两奇点的线 → 使奇点减少为2 → 能一笔画',
      '右图：竖向连线在两个交点创造了奇点，共4个奇点（不满足条件）',
      '右图修改：去掉中间竖向连接线 → 奇点变为0 → 三圆相切图可一笔画（从任意点出发回到原点）',
    ],
    type: 'none',
    finalQ: '左图有几个奇点？',
    finalUnit: '个',
    finalAns: 4,
    figureNode: <HomeworkFig5 />,
  },
  {
    id: '38-H6',
    title: '课后6 · 长方体棱爬行',
    tag: 'type6',
    tagLabel: '立体棱爬行',
    text: '一只木箱的长、宽、高分别为 <strong>5、4、3</strong> 厘米（见下图），有一只甲虫从 <strong>A</strong> 点出发，沿棱爬行，每条棱不允许重复，则甲虫回到 A 点时，<strong>最多能爬行多少厘米</strong>？',
    analysis: [
      '长方体共有 12 条棱：长棱4条×5=20 cm，宽棱4条×4=16 cm，高棱4条×3=12 cm',
      '棱总长 = 20+16+12 = 48 cm',
      '长方体8个顶点，每个顶点连接3条棱（度数3，全是奇点）',
      '8个奇点 → 无法不重复走完所有棱并回到出发点',
      '要形成闭合路线（回到A），必须让所有顶点度数为偶数',
      '去掉部分棱来构造欧拉回路：每次去掉一条棱减少两个奇点',
      '8个奇点需去掉4条棱（每去一条棱消除2个奇点）',
      '为使爬行最长，去掉最短的4条棱（高棱4条×3 cm = 12 cm）',
      '但实际最优方案是哈密顿回路：取4条长棱+2条宽棱+2条高棱',
      '最多爬行 = 4×5 + 2×4 + 2×3 = 20+8+6 = 34 cm',
    ],
    type: 'none',
    finalQ: '甲虫回到A点时，最多能爬行多少厘米？',
    finalUnit: 'cm',
    finalAns: 34,
    figureNode: <HomeworkFig6 />,
  },
]

const SUPPLEMENT: Problem[] = [
  {
    id: '38-S1',
    title: '附加1 · 正方体棱爬行',
    tag: 'type1',
    tagLabel: '立体棱爬行',
    text: '一只蚂蚁沿正方体的棱爬行，经过所有的顶点，且它没有重复走任何一条棱，最后回到出发点。那么它<strong>至少有几条棱没有经过</strong>？',
    analysis: [
      '正方体有 12 条棱，8 个顶点，每个顶点连接 3 条棱（奇点）',
      '蚂蚁要经过所有 8 个顶点，不重复走棱，最后回到出发点',
      '这是"哈密顿回路"：经过每个顶点恰好一次并回到起点',
      '正方体存在哈密顿回路（例如顶部4顶点依次→底部4顶点依次绕一圈）',
      '哈密顿回路经过 8 个顶点，共使用 8 条棱',
      '至少未经过的棱数 = 12 − 8 = 4 条',
    ],
    type: 'none',
    finalQ: '至少有几条棱没有经过？',
    finalUnit: '条',
    finalAns: 4,
    figureNode: <CubeFigure />,
  },
  {
    id: '38-S2',
    title: '附加2 · 长方体棱爬行',
    tag: 'type1',
    tagLabel: '立体棱爬行',
    text: '一条小虫从 A 点出发，沿长 <strong>6 厘米</strong>、宽 <strong>4 厘米</strong>、高 <strong>5 厘米</strong>的长方体的棱爬行，它没有重复走任何一条棱，那么它<strong>最多能爬多少厘米</strong>？',
    analysis: [
      '长方体各棱：长 6cm×4条，宽 4cm×4条，高 5cm×4条',
      '总棱长 = 4×6 + 4×4 + 4×5 = 24 + 16 + 20 = 60 cm',
      '长方体 8 个顶点，每个顶点连 3 条棱（全是奇点），共 8 个奇点',
      '8 个奇点 → 不能不重复地走完所有棱（需要 0 或 2 个奇点）',
      '有 8 个奇点，需"配对"其中 6 个（保留起点 A 和某终点各一个奇点）',
      '3 次配对，每次跳过一条棱。为使总路程最长，跳过最短的 3 条棱（4cm）',
      '最多爬：60 − 3×4 = 60 − 12 = 48 cm',
    ],
    type: 'none',
    finalQ: '最多能爬多少厘米？',
    finalUnit: 'cm',
    finalAns: 48,
    figureNode: <RectBoxFigure />,
  },
  {
    id: '38-S3',
    title: '附加3 · 博物馆参观路线',
    tag: 'type2',
    tagLabel: '平面路线',
    text: '下图是一座博物馆的示意图，游客从<strong>入口</strong>进入博物馆。是否能找到一条参观路线，<strong>穿过所有的门并且每扇门恰好经过一次</strong>？',
    analysis: [
      '把每个房间（区域）和室外看作"点"，每扇门看作连接两点的"线"',
      '一笔画条件：奇点数 = 0（能回到起点）或 2（能从一奇点到另一奇点）',
      '统计每个区域（包括室外）被多少扇门连接，判断奇偶性',
      '逐一检查博物馆各区域：发现有 4 个区域的门数为奇数（奇点）',
      '奇点数 = 4 > 2，不满足一笔画条件',
      '❌ 结论：不能找到穿过所有门恰好一次的参观路线',
    ],
    type: 'none',
    finalQ: '能否找到这样的路线？（能=1，不能=0）',
    finalUnit: '',
    finalAns: 0,
    figureNode: <MuseumFigure />,
  },
  {
    id: '38-S4',
    title: '附加4 · 展览厅参观路线',
    tag: 'type2',
    tagLabel: '平面路线',
    text: '下图是某展厅的平面图，由 <strong>5 个展室</strong>组成，任意两展室之间都有门相通，整个展览厅还有一个<strong>进口</strong>和一个<strong>出口</strong>。游客能否一次不重复地穿过所有的门，并且从入口进、从出口出？',
    analysis: [
      '5 个展室两两相通 → C(5,2) = 10 扇内部门，每个展室连 4 扇内门（偶数）',
      '室外区域：连接进口+出口，共 2 扇门 → 偶点',
      '进口所在展室 A：4 扇内门 + 1 扇进口 = 5 扇门 → 奇点',
      '出口所在展室 B：4 扇内门 + 1 扇出口 = 5 扇门 → 奇点',
      '其余 3 个展室：各 4 扇门 → 偶点',
      '共 2 个奇点（展室A和展室B），满足一笔画条件！',
      '✅ 能！从进口进入展室 A（奇点）→ 穿过所有门 → 从展室 B（奇点）的出口离开',
    ],
    type: 'none',
    finalQ: '能否完成参观？（能=1，不能=0）',
    finalUnit: '',
    finalAns: 1,
    figureNode: <ExhibitFigure />,
  },
  {
    id: '38-S5',
    title: '附加5 · 动物园街道最短路程',
    tag: 'type3',
    tagLabel: '最短路程',
    text: '老师带同学们乘观光车游览野生动物园，大巴车从<strong>起点</strong>出发，走遍每一条街道最后回到起点。街道宽（千米）从左到右为 3、4、2、1、4，高度为 5 千米。<strong>大巴车所走的最短路程是多少千米</strong>？',
    analysis: [
      '街道总长：底边 3+4+2+1+4=14 km，顶边 14 km，纵向 6 条各 5 km = 30 km',
      '总街道长 = 14 + 14 + 30 = 58 km',
      '路口度数：4个底部内部路口和4个顶部内部路口各连 3 条路 → 共 8 个奇点',
      '要走遍所有街道并回到起点（欧拉回路），需让所有奇点变成偶点',
      '8 个奇点需配成 4 对，每对重复走一段路（中国邮递员问题）',
      '最优配对：底部（路口1-2配对重复4km，路口3-4配对重复1km）= 5km',
      '顶部同理：（路口1-2配对重复4km，路口3-4配对重复1km）= 5km',
      '总额外路程 = 5 + 5 = 10 km',
      '最短路程 = 58 + 10 = 68 km',
    ],
    type: 'none',
    finalQ: '大巴车所走的最短路程是多少千米？',
    finalUnit: 'km',
    finalAns: 68,
    figureNode: <StreetMapFigure />,
  },
]

const PRETEST: Problem[] = [
  {
    id: '38-P1',
    title: '课前测1 · 判断一笔画',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '请判断下面图形能否一笔画。<br/>图①：两个矩形交叉重叠（4个奇点）；图②：双山峰（大小三角形并列，2个奇点）；图③：圆形分成4个扇形（4个奇点）。',
    analysis: [
      '一笔画条件：奇点数 = 0（闭合回路）或 2（从一奇点到另一奇点）',
      '图①（交叉矩形）：在矩形重叠处产生4个T形交叉点，每个点度数为3（奇点）→ 4个奇点 → ✗ 不能一笔画',
      '图②（双山峰）：两个三角形共用底边，奇点仅为2个（底边两端T型连接处）→ ✓ 能一笔画',
      '图③（圆分4扇）：3条线从圆心出发到圆周，各端点度数为3（奇点），共4个奇点 → ✗ 不能一笔画',
    ],
    type: 'none',
    finalQ: '三个图形中，能一笔画的有几个？',
    finalUnit: '个',
    finalAns: 1,
    figureNode: <PretestFig1 />,
  },
  {
    id: '38-P2',
    title: '课前测2 · 判断并标出起终点',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '下面的图形能否一笔画出？能一笔画的图形，起点和终点各在哪里？<br/>图①：2×2方格加对角线（多奇点）；图②：左箭头＋矩形（2个奇点，凹角处）。',
    analysis: [
      '图①（2×2网格+对角线）：内部产生多处奇点（每条对角线与网格线交叉），奇点数 ≥ 4 → ✗ 不能一笔画',
      '图②（左箭头+矩形）：箭头凹陷处的两个顶角为奇点（度数3），其余顶点均为偶点 → 2个奇点 → ✓ 能一笔画',
      '图②起点：箭头上凹角；终点：箭头下凹角（或反之）',
    ],
    type: 'none',
    finalQ: '两个图形中，能一笔画的有几个？',
    finalUnit: '个',
    finalAns: 1,
    figureNode: <PretestFig2 />,
  },
  {
    id: '38-P3',
    title: '课前测3 · 最少几笔画出',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '观察下列各图，每个图形最少需要几笔画出？<br/>图①：2格矩形（1条竖分隔线）；图②：3格矩形（2条竖分隔线）；图③：带内角矩形（竖线＋横线各一条）。',
    analysis: [
      '最少笔数 = 奇点数 ÷ 2（奇点数为0时最少1笔）',
      '图①（2格）：分隔线上下各1个T型交点 → 2个奇点 → 最少 1 笔',
      '图②（3格）：两条分隔线各产生2个T型交点 → 4个奇点 → 最少 2 笔',
      '图③（带内角矩形）：竖线两端各1个T型点，横线两端各1个T型点 → 4个奇点 → 最少 2 笔',
      '三图笔数之和 = 1 + 2 + 2 = 5 笔',
    ],
    type: 'none',
    finalQ: '三个图形最少笔数之和是多少？（1＋2＋2＝？）',
    finalUnit: '笔',
    finalAns: 5,
    figureNode: <PretestFig3 />,
  },
  {
    id: '38-P4',
    title: '课前测4 · 添线或去线使能一笔画',
    tag: 'type4',
    tagLabel: '一笔画判断',
    text: '下面的图形都不能一笔画出，请你分别在每个图中添加或去掉最少的线，使它们都能一笔画出。<br/>图①：三角形＋内部辅助线；图②：圆形＋十字＋两条对角线。',
    analysis: [
      '图①（三角形+内线）：统计奇点数 → 4个奇点，需减少到0或2',
      '图①修改：去掉1条内部线段，使奇点数变为2 → 能一笔画（去1条）',
      '图②（圆+十字+斜线）：4条穿过中心的直径，圆周上8个交点均为奇点 → 8个奇点',
      '图②修改：去掉1条直径（减少2个端点奇点），其余6个奇点→再配对 → 最少去1条，使奇点变为0或2',
      '每个图各需操作 1 次，共 2 次',
    ],
    type: 'none',
    finalQ: '两个图形各需添加或去掉几条线（共几条）？',
    finalUnit: '条',
    finalAns: 2,
    figureNode: <PretestFig4 />,
  },
  {
    id: '38-P5',
    title: '课前测5 · 正方体棱爬行最长路',
    tag: 'type6',
    tagLabel: '立体棱爬行',
    text: '一条甲虫沿长 <strong>6 厘米</strong>的正方体的棱爬行。甲虫从 <strong>A 点</strong>出发，每条棱不允许重复，则甲虫<strong>回到 A 点时，最多能爬行多少厘米</strong>？',
    analysis: [
      '正方体共有 12 条棱，每条棱长 6 cm，棱总长 = 12 × 6 = 72 cm',
      '正方体 8 个顶点，每个顶点连接 3 条棱（度数3，全是奇点）',
      '共 8 个奇点 → 不能不重复地走完所有棱并回到出发点',
      '要形成回到A的闭合路线，需让所有顶点度数为偶数（形成欧拉回路）',
      '将 8 个奇点两两配对需"跳过"配对间的棱：4对奇点 → 跳过 4 条棱',
      '为使爬行最长，跳过任意 4 条棱（每条 6 cm）',
      '最多爬行 = (12 − 4) × 6 = 8 × 6 = 48 cm',
    ],
    type: 'none',
    finalQ: '甲虫最多能爬行多少厘米？',
    finalUnit: 'cm',
    finalAns: 48,
    figureNode: <PretestFig5 />,
  },
]

export const PROBLEMS: ProblemSet = {
  pretest: PRETEST,
  lesson: LESSON,
  homework: HOMEWORK,
  workbook: WORKBOOK,
  supplement: SUPPLEMENT,
}

export const PROBLEM_TYPES = [
  {
    tag: 'type1',
    color: 'orange',
    label: '题型1 · 立体棱爬行',
    desc: '在正方体/长方体棱上爬行，求哈密顿路径或最长无重复路径。',
    example: '例：蚂蚁绕正方体爬过所有顶点',
  },
  {
    tag: 'type2',
    color: 'purple',
    label: '题型2 · 平面路线',
    desc: '博物馆/展厅楼层图，判断能否穿过所有门恰好一次（欧拉路径）。',
    example: '例：展厅5展室，从入口到出口穿所有门',
  },
  {
    tag: 'type3',
    color: 'green',
    label: '题型3 · 街道最短路',
    desc: '在路网中从起点出发走遍所有街道回到起点，求最短路程（中国邮递员问题）。',
    example: '例：动物园 3×4×2×1×4 / 5 km 路网',
  },
  {
    tag: 'type4',
    color: 'blue',
    label: '题型4 · 一笔画判断',
    desc: '判断图形能否一笔画，或修改一条线使图形满足一笔画条件。',
    example: '例：矩形+X，判断奇点数',
  },
  {
    tag: 'type5',
    color: 'teal',
    label: '题型5 · 欧拉路径',
    desc: '在平面图中找到从指定入口到出口、不重复经过所有边的路线。',
    example: '例：图书馆5个区域穿过所有门',
  },
  {
    tag: 'type6',
    color: 'pink',
    label: '题型6 · 立体最长路',
    desc: '在长方体棱上从出发点不重复走棱并回到出发点，求最长路程。',
    example: '例：长5宽4高3，甲虫从A出发最多爬多少cm',
  },
  {
    tag: 'type7',
    color: 'red',
    label: '题型7 · 路网最长/最短路',
    desc: '在路网中求不重复走完尽量多路段的最长路程，或走遍所有路段回起点的最短路程（中国邮递员问题）。',
    example: '例：林间小路总长19km，最多走多少',
  },
]

export const TYPE_STYLE: Record<
  string,
  { bg: string; border: string; titleColor: string; textColor: string }
> = {
  type1: {
    bg: 'bg-orange-50',
    border: 'border-l-orange-500',
    titleColor: 'text-orange-800',
    textColor: 'text-orange-900',
  },
  type2: {
    bg: 'bg-purple-50',
    border: 'border-l-purple-500',
    titleColor: 'text-purple-800',
    textColor: 'text-purple-900',
  },
  type3: {
    bg: 'bg-green-50',
    border: 'border-l-green-500',
    titleColor: 'text-green-800',
    textColor: 'text-green-900',
  },
  type4: {
    bg: 'bg-blue-50',
    border: 'border-l-blue-500',
    titleColor: 'text-blue-800',
    textColor: 'text-blue-900',
  },
  type5: {
    bg: 'bg-teal-50',
    border: 'border-l-teal-500',
    titleColor: 'text-teal-800',
    textColor: 'text-teal-900',
  },
  type6: {
    bg: 'bg-pink-50',
    border: 'border-l-pink-500',
    titleColor: 'text-pink-800',
    textColor: 'text-pink-900',
  },
  type7: {
    bg: 'bg-red-50',
    border: 'border-l-red-500',
    titleColor: 'text-red-800',
    textColor: 'text-red-900',
  },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-orange-100 text-orange-800',
  type2: 'bg-purple-100 text-purple-800',
  type3: 'bg-green-100 text-green-800',
  type4: 'bg-blue-100 text-blue-800',
  type5: 'bg-teal-100 text-teal-800',
  type6: 'bg-pink-100 text-pink-800',
  type7: 'bg-red-100 text-red-800',
}
