import type { Problem, ProblemSet } from './type'

const PRETEST: Problem[] = []

const LESSON: Problem[] = [
  {
    id: '42-L1',
    title: '例1 · 砝码单边称重',
    tag: 'type1',
    tagLabel: '砝码称重组合',
    text: '一台天平在称物时，只允许在天平的一边放砝码，现在给你 <strong>1 克、2 克、5 克、7 克</strong>的砝码各一个，那么在天平上能称出几种不同重量的物体？',
    analysis: [
      '每个砝码"用 / 不用" → 共 2⁴ − 1 = 15 种组合（去掉一个都不放）',
      '列出所有组合的和：1, 2, 5, 7, 3, 6, 8, 7, 9, 12, 8, 10, 13, 14, 15',
      '⚠️ 出现重复：7 = 7 = 2+5；8 = 1+7 = 1+2+5（各重一次）',
      '不同重量 = 15 − 2 = 13 种',
    ],
    type: 'none',
    finalQ: '能称出几种不同重量？',
    finalUnit: '种',
    finalAns: 13,
    analysisImg: '/img/math/42-L1.png',
  },
  {
    id: '42-L2',
    title: '练一练 · 三砝码单边',
    tag: 'type1',
    tagLabel: '砝码称重组合',
    text: '一台天平在称物时，只允许在天平的一边放砝码，现在给你 <strong>2 克、3 克、4 克</strong>的砝码各一个，那么在天平上能称出几种不同重量的物体？',
    analysis: [
      '非空子集共 2³ − 1 = 7 种',
      '单个：2、3、4',
      '两两组合：5(2+3)、6(2+4)、7(3+4)',
      '三个一起：9(2+3+4)',
      '7 种和全部不同 → 7 种',
    ],
    type: 'none',
    finalQ: '能称出几种不同重量？',
    finalUnit: '种',
    finalAns: 7,
    analysisImg: '/img/math/42-L2.png',
  },
  {
    id: '42-L3',
    title: '例2 · 砝码两边称重',
    tag: 'type1',
    tagLabel: '砝码称重组合',
    text: '现有重量分别为 <strong>1 克、3 克、9 克</strong>的 3 个砝码，可放在天平的两边，用这 3 个砝码能够称出几种不同重量的物体？',
    analysis: [
      '每个砝码 3 种状态：右盘(+) / 不用(0) / 左盘(−) → 共 3³ = 27 种',
      '去掉全 0 一种 → 26 种，左右镜像两两相同 → 26 ÷ 2 = 13 种',
      '可称重量：1、2、3、4、5、6、7、8、9、10、11、12、13 克 → 共 13 种',
      '⚠️ 1+3+9=13，每一克到 13 克都可表示',
    ],
    type: 'none',
    finalQ: '能称出几种不同重量？',
    finalUnit: '种',
    finalAns: 13,
    analysisImg: '/img/math/42-L3.png',
  },
  {
    id: '42-L4',
    title: '练一练 · 两边称重',
    tag: 'type1',
    tagLabel: '砝码称重组合',
    text: '文文有 3 个砝码，重量分别为 <strong>1 克、2 克、6 克</strong>，砝码可以放在天平的两边，用这 3 个砝码能够称出几种不同重量的物体？',
    analysis: [
      '每个砝码 3 态：3³ = 27，去全 0 = 26，去镜像 ÷2 = 13 种组合',
      '逐一列出可称重量（绝对值）：1、2、3(1+2)、4(6−2)、5(6−1)、6、7(6+1)、8(6+2)、9(6+2+1)',
      '⚠️ 部分组合重复（如 6−2−1=3 与 1+2=3 同值），去重后共 9 种',
    ],
    type: 'none',
    finalQ: '能称出几种不同重量？',
    finalUnit: '种',
    finalAns: 9,
    analysisImg: '/img/math/42-L4.png',
  },
  {
    id: '42-L5',
    title: '例3 · 三人买面包分账',
    tag: 'type2',
    tagLabel: '公平分账',
    text: '甲、乙、丙三人共买了 <strong>9 个相同的面包</strong>，每人吃了 <strong>3 个</strong>。甲付了 5 个面包的钱，乙付了 4 个面包的钱，丙没有付钱。吃完后，丙拿出 <strong>6 元钱</strong>补给甲、乙两人，<strong>甲应得多少元</strong>？',
    analysis: [
      '丙吃 3 个，实付 6 元 → 每个面包 6 ÷ 3 = 2 元',
      '甲多付了5-3=2个面包的钱，甲应得(5-3)×2=4元',
      '乙多付了4-3=1个面包的钱，乙应得(4-3)×2=2元',
    ],
    type: 'none',
    finalQ: '甲应得多少元？',
    finalUnit: '元',
    finalAns: 4,
    analysisImg: '/img/math/42-L5.png',
  },
  {
    id: '42-L6',
    title: '练一练 · 雪糕分账',
    tag: 'type2',
    tagLabel: '公平分账',
    text: '纳纳、约约和立立三人共买了 <strong>12 块相同的梦龙雪糕</strong>，每人吃 <strong>4 块</strong>。纳纳付了 7 块雪糕的钱，约约付了 5 块雪糕的钱，立立没有付钱。吃完后，立立拿出 <strong>16 元钱</strong>补给纳纳和约约，请问<strong>纳纳应得多少元</strong>？',
    analysis: [
      '立立吃 4 块，付 16 元 → 每块 16 ÷ 4 = 4 元',
      '纳纳付 7 × 4 = 28 元；纳纳吃 4 × 4 = 16 元；应得 28 − 16 = 12 元',
      '约约付 5 × 4 = 20 元；约约吃 4 × 4 = 16 元；应得 20 − 16 = 4 元',
      '验算：12 + 4 = 16 元 ✓',
    ],
    type: 'none',
    finalQ: '纳纳应得多少元？',
    finalUnit: '元',
    finalAns: 12,
    analysisImg: '/img/math/42-L6.png',
  },
  {
    id: '42-L7',
    title: '例4 · 4 空瓶换 1 瓶',
    tag: 'type3',
    tagLabel: '空瓶换水',
    text: '商店规定：<strong>4 个空瓶可换 1 瓶</strong>矿泉水。纳纳有 <strong>15 个空瓶</strong>，最多能喝几瓶水？（空瓶不够时可以借，但要归还相同数量的空瓶）',
    analysis: [
      '思路：每喝 1 瓶水，最终净消耗 (4 − 1) = 3 个空瓶（喝完又得 1 个，相当于只用 3 个）',
      '所以最多喝 15 ÷ 3 = 5 瓶',
      '具体操作：15 → 换 3 瓶 + 剩 3 空 = 6 空；6 → 换 1 瓶 + 剩 2 空 = 3 空；3 → 借 1 个 = 4 空换 1 瓶 → 还回 1 空',
      '总计 3 + 1 + 1 = 5 瓶 ✓',
    ],
    type: 'none',
    finalQ: '最多能喝几瓶水？',
    finalUnit: '瓶',
    finalAns: 5,
    analysisImg: '/img/math/42-L7.png',
  },
  {
    id: '42-L8',
    title: '练一练 · 桃核换桃',
    tag: 'type3',
    tagLabel: '空瓶换水',
    text: '纳约水果店"<strong>3 个桃核换 1 个桃</strong>"促销（桃核不够时可借，但要归还相同数量的桃核），一个桃售价 <strong>1 元</strong>。如果你有 <strong>10 元钱</strong>，最多能吃几个桃？',
    analysis: [
      '10 元先直接买 10 个桃 → 得 10 个桃核',
      '剩余桃核换桃：每换 1 个桃净消耗 (3 − 1) = 2 个桃核',
      '10 个桃核 → 10 ÷ 2 = 5 个桃',
      '总计 10 + 5 = 15 个桃',
    ],
    type: 'none',
    finalQ: '最多能吃几个桃？',
    finalUnit: '个',
    finalAns: 15,
    analysisImg: '/img/math/42-L8.png',
  },
  {
    id: '42-L9',
    title: '例5 · 绳子定时 9 分钟',
    tag: 'type4',
    tagLabel: '计时与量水',
    text: '两根粗细均匀的绳子，每根从一端点燃可烧 <strong>12 分钟</strong>，绳子不能折叠。如果要用 <strong>两根绳子</strong>准确定出 <strong>9 分钟</strong>的时间，应如何操作？',
    analysis: [
      '关键技巧：一根绳两端同时点燃 → 燃烧时间减半（12 ÷ 2 = 6 分钟）',
      '操作：A 两端点 + B 一端点 → 6 分钟时 A 烧完，此刻 B 还剩 6 分钟',
      '此时把 B 另一端也点燃 → 剩下 6 分钟两端烧，需 3 分钟烧完',
      '总时长 6 + 3 = 9 分钟 ✓',
    ],
    type: 'none',
    finalQ: '准确测出的时间是多少分钟？',
    finalUnit: '分钟',
    finalAns: 9,
  },
  {
    id: '42-L10',
    title: '练一练 · 香测 15 分钟',
    tag: 'type4',
    tagLabel: '计时与量水',
    text: '有两支粗细不均匀且长度不同的香，每支点燃后都能燃烧 <strong>1 个小时</strong>。怎样用这两支香准确定出 <strong>15 分钟</strong>？',
    analysis: [
      '香 A 两端同时点燃 → 30 分钟烧完；同时香 B 一端点燃',
      'A 烧完时（30 分钟过去），B 还剩 30 分钟',
      '立刻把 B 另一端也点燃 → 剩下 30 分钟两端烧 → 15 分钟烧完',
      '从 A 烧完到 B 烧完恰好 15 分钟 ✓',
    ],
    type: 'none',
    finalQ: '测出的时间是多少分钟？',
    finalUnit: '分钟',
    finalAns: 15,
  },
  {
    id: '42-L11',
    title: '例6 · 量出 100 克水',
    tag: 'type4',
    tagLabel: '计时与量水',
    text: '有大、中、小 3 个瓶子，分别可以装入水 <strong>1000 克、700 克、300 克</strong>。现在大瓶装满水，希望通过水在 3 个瓶子间的流动，使得中瓶和小瓶上都标出 <strong>100 克</strong>的刻度线，问最少要倒几次水？',
    analysis: [
      '①大→中：大 1000→300，中 0→700',
      '②中→小：中 700→400，小 0→300',
      '③小→大：大 300→600，小 300→0',
      '④中→小：中 400→100（标中 100 克✨），小 0→300',
      '⑤小→大：大 600→900，小 300→0',
      '⑥中→小：中 100→0，小 0→100（标小 100 克✨）',
      '共 6 次',
    ],
    type: 'none',
    finalQ: '最少要倒几次水？',
    finalUnit: '次',
    finalAns: 6,
  },
  {
    id: '42-L12',
    title: '练一练 · 量 3 升水',
    tag: 'type4',
    tagLabel: '计时与量水',
    text: '有两个没有刻度的杯子，大杯装满 <strong>8 升</strong>水，小杯装满 <strong>5 升</strong>水。如何用这两个杯子准确量出 <strong>3 升水</strong>？最少要倒几步？',
    analysis: [
      '①把大杯装满（8 升）',
      '②大杯倒入小杯，倒到小杯装满为止：大杯剩 8 − 5 = 3 升',
      '此时大杯里恰好就是 3 升水 ✓',
      '至少 2 步（装满 + 倒一次）',
    ],
    type: 'none',
    finalQ: '最少要倒几步？',
    finalUnit: '步',
    finalAns: 2,
  },
  {
    id: '42-L13',
    title: '附加题1 · 9 枚金币找假币',
    tag: 'type5',
    tagLabel: '天平找异物',
    text: '有 <strong>9 枚金币</strong>外观完全相同，其中 8 枚真币、1 枚假币，假币<strong>不知轻重</strong>（真币重量一样）。用一台无砝码的天平称，请问<strong>至少称几次</strong>才能保证找出假币？',
    analysis: [
      '不知轻重 → 第一次称要锁定假币所在分组及它"偏轻"还是"偏重"',
      '把 9 枚分成 3 组（3 + 3 + 3）：左 3 右 3 上天平，剩 3 在外',
      '若平衡 → 假在外面 3 枚里；若不平 → 假在天平上 6 枚里且偏向某侧',
      '第 2 次再分 3 等分 → 第 3 次比较两枚定真假',
      '总共需要 3 次',
    ],
    type: 'none',
    finalQ: '至少称几次能找出假币？',
    finalUnit: '次',
    finalAns: 3,
  },
  {
    id: '42-L14',
    title: '附加题2 · 27 个球找次品',
    tag: 'type5',
    tagLabel: '天平找异物',
    text: '有 <strong>27 个球</strong>，其中 1 个次品，外观与正品相同但<strong>比正品轻</strong>。用一台无砝码的天平称，<strong>最少称几次</strong>能找出这个次品？',
    analysis: [
      '已知次品偏轻 → 每次称可把目标分成 3 组等分',
      '27 = 3 × 3 × 3 = 3³ → 三次三等分即可',
      '①9 vs 9：轻的一边/平衡 → 锁定 9 个',
      '②3 vs 3：轻的一边/平衡 → 锁定 3 个',
      '③1 vs 1：轻的就是次品（若平衡则剩下那个是次品）',
      '共需 3 次',
    ],
    type: 'none',
    finalQ: '最少称几次能找出次品？',
    finalUnit: '次',
    finalAns: 3,
    analysisImg: '/img/math/42-L14.png',
  },
]

const HOMEWORK: Problem[] = []

const WORKBOOK: Problem[] = []

export const PROBLEMS: ProblemSet = {
  pretest: PRETEST,
  lesson: LESSON,
  homework: HOMEWORK,
  workbook: WORKBOOK,
}

export const PROBLEM_TYPES = [
  {
    tag: 'type1',
    color: 'rose',
    label: '题型1 · 砝码称重组合',
    desc: '单边放砝码：求子集和；可放两边：求 ±组合的绝对值。注意去重——多个组合可能得到相同重量。',
    example: '例：1+2+5+7 单边放 → 15 个子集和去重 = 13 种',
  },
  {
    tag: 'type2',
    color: 'amber',
    label: '题型2 · 公平分账',
    desc: '用"没付钱的人补出的钱"反推单价：单价 = 补偿金 ÷ 该人吃的份数。每人应得 = 实付钱 − 实吃钱。',
    example: '例：丙补 6 元/3 块 = 2 元/块；甲付 10 − 吃 6 = 得 4 元',
  },
  {
    tag: 'type3',
    color: 'green',
    label: '题型3 · 空瓶换水',
    desc: '允许借空瓶时：可喝瓶数 = 总空瓶 ÷ (换购比 − 1)。每喝 1 瓶相当于净消耗 (换购比 − 1) 个空瓶。',
    example: '例：4 换 1，15 空瓶 → 15 ÷ 3 = 5 瓶',
  },
  {
    tag: 'type4',
    color: 'sky',
    label: '题型4 · 计时与量水',
    desc: '绳子/香两端同时点燃 → 时间减半；量水靠"装满-倒满-差值"组合，配合三个容器互相倒水标刻度。',
    example: '例：两根 12 分钟绳测 9 分钟 = 6 (两端) + 3 (两端再点)',
  },
  {
    tag: 'type5',
    color: 'purple',
    label: '题型5 · 天平找异物',
    desc: '已知轻重：每次称把目标分 3 等分 → 3ⁿ ≥ 总数 → n 次。不知轻重通常多需 1 次确认偏向。',
    example: '例：27 个球(已知轻) → 3³=27 → 3 次',
  },
]

export const TYPE_STYLE: Record<
  string,
  { bg: string; border: string; titleColor: string; textColor: string }
> = {
  type1: {
    bg: 'bg-rose-50',
    border: 'border-l-rose-500',
    titleColor: 'text-rose-800',
    textColor: 'text-rose-900',
  },
  type2: {
    bg: 'bg-amber-50',
    border: 'border-l-amber-500',
    titleColor: 'text-amber-800',
    textColor: 'text-amber-900',
  },
  type3: {
    bg: 'bg-green-50',
    border: 'border-l-green-500',
    titleColor: 'text-green-800',
    textColor: 'text-green-900',
  },
  type4: {
    bg: 'bg-sky-50',
    border: 'border-l-sky-500',
    titleColor: 'text-sky-800',
    textColor: 'text-sky-900',
  },
  type5: {
    bg: 'bg-purple-50',
    border: 'border-l-purple-500',
    titleColor: 'text-purple-800',
    textColor: 'text-purple-900',
  },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-rose-100 text-rose-800',
  type2: 'bg-amber-100 text-amber-800',
  type3: 'bg-green-100 text-green-800',
  type4: 'bg-sky-100 text-sky-800',
  type5: 'bg-purple-100 text-purple-800',
}
