'use client'

import type { ProblemSet } from './type'

export const LESSON_TIP =
  '剪切法：剪后周长和 = 原周长 + 2×所有切割线总长\n平移法：阶梯形周长 = 2×(最大宽 + 最大高)\n标向法：给每条边标方向，水平、竖直各自成对'

export const PROBLEM_TYPES = [
  {
    tag: 'type1',
    color: 'blue',
    label: '题型1 · 拼图法',
    desc: '将相同小图形拼成大图形，分析拼法求周长或种数。',
    example: '例：3个4×2长方形→2种周长：28或20厘米',
  },
  {
    tag: 'type2',
    color: 'orange',
    label: '题型2 · 剪切法',
    desc: '剪后周长和 = 原周长 + 2×全部切割线长度之和。',
    example: '例：7×3纸横剪1刀竖剪2刀，周长和=46',
  },
  {
    tag: 'type3',
    color: 'green',
    label: '题型3 · 平移法',
    desc: '把凹入的边"平移"到外侧，化为矩形周长。',
    example: '例：5层礼品盒阶梯，P=2×5×(20+10)=300',
  },
  {
    tag: 'type4',
    color: 'purple',
    label: '题型4 · 标向法',
    desc: '给各边标方向（↑↓←→），同方向之和相等替换。',
    example: '例：凹凸多边形，按方向累加求总长',
  },
]

export const TYPE_STYLE: Record<
  string,
  { bg: string; border: string; titleColor: string; textColor: string }
> = {
  type1: { bg: 'bg-blue-50', border: 'border-l-blue-500', titleColor: 'text-blue-800', textColor: 'text-blue-900' },
  type2: { bg: 'bg-orange-50', border: 'border-l-orange-500', titleColor: 'text-orange-800', textColor: 'text-orange-900' },
  type3: { bg: 'bg-green-50', border: 'border-l-green-500', titleColor: 'text-green-800', textColor: 'text-green-900' },
  type4: { bg: 'bg-purple-50', border: 'border-l-purple-500', titleColor: 'text-purple-800', textColor: 'text-purple-900' },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-blue-100 text-blue-700',
  type2: 'bg-orange-100 text-orange-700',
  type3: 'bg-green-100 text-green-700',
  type4: 'bg-purple-100 text-purple-700',
}

export const PROBLEMS: ProblemSet = {
  pretest: [
    {
      id: '40-P1',
      title: '课前测1 · 正方形排成一行',
      tag: 'type1',
      tagLabel: '拼图法',
      text: '把边长分别是 <strong>5</strong>、<strong>4</strong>、<strong>3</strong>、<strong>2</strong> 厘米的 4 个正方形按从大到小的顺序排成一行，排成的图形周长是多少厘米？',
      figureNode: <img src="/img/lesson40/pretest1.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '底边 = 5+4+3+2 = 14厘米',
        '用平移法：顶边各段平移后与底边等长，顶边总和 = 14厘米',
        '左边 = 5厘米，右边 = 2厘米',
        '相邻正方形高度差各为 1厘米，共 3 处竖向阶梯段，合计 = 3厘米',
        'P = 14+14+5+2+3 = 38厘米',
      ],
      type: 'none',
      finalQ: '排成图形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 38,
    },
    {
      id: '40-P2',
      title: '课前测2 · 长方形纸片横竖剪刀',
      tag: 'type2',
      tagLabel: '剪切法',
      text: '一张长为 <strong>10</strong> 厘米、宽为 <strong>5</strong> 厘米的长方形纸片，横着剪了 <strong>2</strong> 刀，竖着剪了 <strong>3</strong> 刀，请问剪完后得到的所有长方形的周长之和是多少厘米？',
      figureNode: <img src="/img/lesson40/pretest2.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '剪切公式：周长和 = 2×(横刀数+1)×长 + 2×(竖刀数+1)×宽',
        '= 2×(2+1)×10 + 2×(3+1)×5',
        '= 2×3×10 + 2×4×5',
        '= 60 + 40 = 100厘米',
      ],
      type: 'none',
      finalQ: '剪完后所有长方形的周长之和是多少厘米？',
      finalUnit: '厘米',
      finalAns: 100,
    },
    {
      id: '40-P3',
      title: '课前测3 · 大长方形分成12个小正方形',
      tag: 'type1',
      tagLabel: '拼图法',
      text: '把一个大长方形分成 <strong>12</strong> 个小正方形，已知每个小正方形的周长为 <strong>8</strong> 厘米，求大长方形的周长。',
      figureNode: <img src="/img/lesson40/pretest3.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '小正方形周长 = 8厘米，边长 = 8÷4 = 2厘米',
        '12个小正方形排成 4×3 的网格（4列3行）',
        '大长方形：长 = 4×2 = 8厘米，宽 = 3×2 = 6厘米',
        'P = 2×(8+6) = 28厘米',
      ],
      type: 'none',
      finalQ: '大长方形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 28,
    },
    {
      id: '40-P4',
      title: '课前测4 · 15个小长方形组合图',
      tag: 'type3',
      tagLabel: '平移法',
      text: '下图是由 <strong>15</strong> 个长为 <strong>10</strong> 厘米、宽为 <strong>4</strong> 厘米的小长方形组合而成的阶梯图形，求这个图形的周长。',
      figureNode: <img src="/img/lesson40/pretest4.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '图形是 5 层阶梯（1+2+3+4+5=15块）',
        '用平移法：每层的阶梯凹凸边可"平移"成矩形',
        'P = 2×层数×(长+宽) = 2×5×(10+4)',
        '= 10×14 = 140厘米',
      ],
      type: 'none',
      finalQ: '这个图形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 140,
    },
    {
      id: '40-P5',
      title: '课前测5 · 相邻边垂直多边形',
      tag: 'type4',
      tagLabel: '标向法',
      text: '如图所示，相邻的两条线段互相垂直，求这个多边形的周长是多少厘米？',
      figureNode: <img src="/img/lesson40/pretest5.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '用标向法：给每条边标上方向（↑↓←→）',
        '所有向右（→）的边之和 = 所有向左（←）的边之和',
        '所有向上（↑）的边之和 = 所有向下（↓）的边之和',
        '水平方向总和 = 2×最大宽，竖直方向总和 = 2×最大高',
        'P = 2×（水平+竖直）= 30厘米',
      ],
      type: 'none',
      finalQ: '这个多边形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 30,
    },
  ],

  lesson: [
    {
      id: '40-L1',
      title: '课1 · 3个长方形拼大长方形（种数）',
      tag: 'type1',
      tagLabel: '拼图法',
      text: '用 <strong>3</strong> 个长 <strong>4</strong> 厘米、宽 <strong>2</strong> 厘米的长方形拼成一个大长方形，请问拼成的大长方形的周长有多少种不同的可能？',
      figureNode: <img src="/img/lesson40/lesson1.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '拼法1：全部横排 → 大长方形 12×2，P = 2×(12+2) = 28厘米',
        '拼法2：全部竖排叠放 → 大长方形 4×6，P = 2×(4+6) = 20厘米',
        '⚠️ 3 是奇数，无法均分为 2 行（不能有半个），故只有这 2 种',
        '共有 2 种不同的周长',
      ],
      type: 'none',
      finalQ: '共有几种不同的周长？',
      finalUnit: '种',
      finalAns: 2,
    },
    {
      id: '40-L2',
      title: '练一练1 · 6个正方形拼大长方形（种数）',
      tag: 'type1',
      tagLabel: '拼图法',
      text: '用 <strong>6</strong> 个边长为 <strong>3</strong> 厘米的正方形拼成一个大长方形，请问拼成的大长方形的周长有多少种不同的可能？',
      analysis: [
        '6的因数对：1×6、2×3',
        '拼法1：1行6列 → 18×3，P = 2×(18+3) = 42厘米',
        '拼法2：2行3列 → 9×6，P = 2×(9+6) = 30厘米',
        '共有 2 种不同的周长',
      ],
      type: 'none',
      finalQ: '共有几种不同的周长？',
      finalUnit: '种',
      finalAns: 2,
    },
    {
      id: '40-L3',
      title: '课2 · 4个小长方形拼大长方形',
      tag: 'type1',
      tagLabel: '拼图法',
      text: '如图所示，用 <strong>4</strong> 个相同的长为 <strong>9</strong> 厘米的小长方形拼成一个大长方形，请问大长方形的周长是多少厘米？',
      figureNode: <img src="/img/lesson40/lesson2.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '由图可知：4个小长方形竖向叠放',
        '大长方形宽 = 小长方形长 = 9厘米',
        '由拼法可推出小长方形宽 = 3厘米',
        '大长方形高 = 4×3 = 12厘米',
        'P = 2×(9+12) = 42厘米',
      ],
      type: 'none',
      finalQ: '大长方形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 42,
    },
    {
      id: '40-L4',
      title: '练一练2 · 4个小长方形拼大长方形',
      tag: 'type1',
      tagLabel: '拼图法',
      text: '如图所示，用 <strong>4</strong> 个相同的宽为 <strong>5</strong> 厘米的小长方形拼成一个大长方形，请问大长方形的周长是多少厘米？',
      figureNode: <img src="/img/lesson40/lessonPr2.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '由图可知：4个小长方形横向排列，宽=5厘米',
        '由拼法可推出小长方形长 = 10厘米',
        '大长方形宽 = 4×5 = 20厘米，长 = 10厘米',
        'P = 2×(10+20) = 60厘米',
      ],
      type: 'none',
      finalQ: '大长方形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 60,
    },
    {
      id: '40-L5',
      title: '课3 · 长方形横剪1刀竖剪2刀',
      tag: 'type2',
      tagLabel: '剪切法',
      text: '一张长为 <strong>7</strong> 厘米、宽为 <strong>3</strong> 厘米的长方形纸片，横着剪了 <strong>1</strong> 刀，竖着剪了 <strong>2</strong> 刀，请问剪完后得到的所有长方形的周长之和是多少厘米？',
      figureNode: <img src="/img/lesson40/lesson3.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '剪切公式：周长和 = 2×(横刀数+1)×长 + 2×(竖刀数+1)×宽',
        '= 2×(1+1)×7 + 2×(2+1)×3',
        '= 2×2×7 + 2×3×3',
        '= 28 + 18 = 46厘米',
      ],
      type: 'none',
      finalQ: '所有小长方形的周长之和是多少厘米？',
      finalUnit: '厘米',
      finalAns: 46,
    },
    {
      id: '40-L6',
      title: '练一练3 · 正方形横剪1刀竖剪1刀',
      tag: 'type2',
      tagLabel: '剪切法',
      text: '纳纳将一张边长为 <strong>8</strong> 厘米的正方形纸片横着剪了 <strong>1</strong> 刀，竖着剪了 <strong>1</strong> 刀，请问剪完后得到的所有长方形的周长之和是多少厘米？',
      figureNode: <img src="/img/lesson40/lessonPr3.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '周长和 = 2×(1+1)×8 + 2×(1+1)×8',
        '= 2×2×8 + 2×2×8',
        '= 32 + 32 = 64厘米',
        '⚠️ 正方形长=宽=8，两个方向公式相同',
      ],
      type: 'none',
      finalQ: '所有小长方形的周长之和是多少厘米？',
      finalUnit: '厘米',
      finalAns: 64,
    },
    {
      id: '40-L7',
      title: '课4 · 礼品盒阶梯形周长',
      tag: 'type3',
      tagLabel: '平移法',
      text: '六一儿童节快要到了，一年级一班准备了一些礼品盒，每个礼品盒长 <strong>20</strong> 厘米，高 <strong>10</strong> 厘米，摆成如图所示的阶梯形，请问整个图形的周长是多少厘米？',
      figureNode: <img src="/img/lesson40/lesson4.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '图形是 5 层阶梯，用平移法化简',
        '每层的凹凸边可平移合并：周长 = 2×层数×(长+高)',
        '= 2×5×(20+10)',
        '= 10×30 = 300厘米',
      ],
      type: 'none',
      finalQ: '整个图形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 300,
    },
    {
      id: '40-L8',
      title: '练一练4 · 等边三角形拼平行四边形',
      tag: 'type3',
      tagLabel: '平移法',
      text: '用 <strong>20</strong> 个边长为 <strong>4</strong> 厘米的等边三角形拼接成一个大的平行四边形，请问大平行四边形的周长是多少厘米？',
      figureNode: <img src="/img/lesson40/lessonPr4.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '20个等边三角形拼成平行四边形：每行10个三角形（正+倒各5），共2行',
        '平行四边形：底边 = 10×2 = 20厘米（注：底为三角形底边拼合）',
        '⚠️ 实际：底边=10×4/2×2=20... 由图析：底=5×4=20，斜边=4×2=8',
        '大平行四边形 P = 2×(20+4) = 2×24 = 48... ',
        '由图更精确分析：长底边=10×4÷2×2=40，短斜=4×2... → P = 2×(40+4) = 88厘米',
      ],
      type: 'none',
      finalQ: '大平行四边形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 88,
    },
    {
      id: '40-L9',
      title: '课5 · 小区平面图晨跑',
      tag: 'type3',
      tagLabel: '平移法',
      text: '下图是某个小区的平面图（单位：米），约约每天早上会沿着小区晨跑 <strong>2</strong> 圈，请问约约每天跑多少米？',
      figureNode: <img src="/img/lesson40/lesson5.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '用平移法：凹凸边平移后，小区轮廓等效为长方形',
        '等效长方形：长 = 150米，宽 = 150米',
        '一圈周长 = 2×(150+150) = 600米',
        '2圈 = 600×2 = 1200米',
      ],
      type: 'none',
      finalQ: '约约每天跑多少米？',
      finalUnit: '米',
      finalAns: 1200,
    },
    {
      id: '40-L10',
      title: '练一练5 · 凹凸图形周长（平移法）',
      tag: 'type3',
      tagLabel: '平移法',
      text: '如图，两个凹凸图形的相邻边都互相垂直，用平移法求这两个图形的周长。（单位：厘米）',
      analysis: [
        '平移法核心：把凹入的边"平移"到对侧，凹凸图形→等效长方形',
        '水平方向：所有向右之和 = 所有向左之和 = 最大宽度',
        '竖直方向：所有向上之和 = 所有向下之和 = 最大高度',
        'P = 2×(最大宽 + 最大高)',
        '由图中数据代入计算得 P = 28厘米',
      ],
      type: 'none',
      finalQ: '图形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 28,
    },
    {
      id: '40-L11',
      title: '课6 · 标向法求多边形周长',
      tag: 'type4',
      tagLabel: '标向法',
      text: '如图所示，这个多边形任意相邻的两条边都互相垂直，求这个多边形的周长是多少？（单位：厘米）',
      figureNode: <img src="/img/lesson40/lesson6.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '用标向法：对每条边标注方向（→、←、↑、↓）',
        '水平方向：→ 之和 = ← 之和（补全缺失边）',
        '竖直方向：↑ 之和 = ↓ 之和（补全缺失边）',
        '由图中已知边推算：水平总和=2×11=22，竖直总和=2×10=20',
        'P = 22+20 = 42厘米',
      ],
      type: 'none',
      finalQ: '这个多边形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 42,
    },
    {
      id: '40-L12',
      title: '练一练6 · 两图形标向法',
      tag: 'type4',
      tagLabel: '标向法',
      text: '如下图，两个多边形任意相邻的两条边都互相垂直，分别求两个多边形的周长。（单位：厘米）',
      figureNode: <img src="/img/lesson40/lessonPr6.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '图①：用标向法，水平总和=2×6=12，竖直总和=2×6=12，P₁ = 24厘米',
        '图②：用标向法，水平总和=2×10=20，竖直总和=2×10=20，P₂ = 40厘米',
        '两图形周长之和 = 24+40 = 64厘米',
      ],
      type: 'none',
      finalQ: '两个图形的周长之和是多少厘米？',
      finalUnit: '厘米',
      finalAns: 64,
    },
  ],

  homework: [
    {
      id: '40-H1',
      title: '课后巩固1 · 4个长方形拼大长方形（种数）',
      tag: 'type1',
      tagLabel: '拼图法',
      text: '用 <strong>4</strong> 个长 <strong>6</strong> 厘米、宽 <strong>2</strong> 厘米的长方形拼成一个大长方形，请问拼成的大长方形的周长有多少种不同的可能？',
      figureNode: <img src="/img/lesson40/homework1.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '拼法1：4个横排 → 24×2，P = 2×(24+2) = 52厘米',
        '拼法2：2行×2列 → 12×4，P = 2×(12+4) = 32厘米',
        '拼法3：4个竖排叠放 → 6×8，P = 2×(6+8) = 28厘米',
        '共有 3 种不同的周长：52、32、28厘米',
      ],
      type: 'none',
      finalQ: '共有几种不同的周长？',
      finalUnit: '种',
      finalAns: 3,
    },
    {
      id: '40-H2',
      title: '课后巩固2 · 5个小长方形拼大长方形',
      tag: 'type1',
      tagLabel: '拼图法',
      text: '如图所示，用 <strong>5</strong> 个相同的长为 <strong>12</strong> 厘米的小长方形拼成一个大长方形，请问大长方形的周长是多少厘米？',
      figureNode: <img src="/img/lesson40/homework2.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '由图：上方2个横放（共24厘米宽），下方3个竖放（共24厘米宽）',
        '设小长方形宽为 w，上排高=w，下排高=12',
        '由宽相等：2×12 = 3×宽₂ → 宽₂=8厘米，小长方形宽=w=8厘米',
        '大长方形：宽=24厘米，高=8+12=20厘米',
        'P = 2×(24+20) = 88厘米',
      ],
      type: 'none',
      finalQ: '大长方形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 88,
    },
    {
      id: '40-H3',
      title: '课后巩固3 · 长方形横剪2刀竖剪3刀',
      tag: 'type2',
      tagLabel: '剪切法',
      text: '一个长为 <strong>20</strong> 厘米、宽为 <strong>10</strong> 厘米的长方形纸片，被横着剪了 <strong>2</strong> 刀，竖着剪了 <strong>3</strong> 刀，剪完后所形成的所有长方形的周长总和是多少？',
      figureNode: <img src="/img/lesson40/homework3.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '周长和 = 2×(横刀数+1)×长 + 2×(竖刀数+1)×宽',
        '= 2×(2+1)×20 + 2×(3+1)×10',
        '= 2×3×20 + 2×4×10',
        '= 120 + 80 = 200厘米',
      ],
      type: 'none',
      finalQ: '所有长方形的周长总和是多少厘米？',
      finalUnit: '厘米',
      finalAns: 200,
    },
    {
      id: '40-H4',
      title: '课后巩固4 · 砖墙阶梯形周长',
      tag: 'type3',
      tagLabel: '平移法',
      text: '下图是一面砖墙的平面图，每块砖长 <strong>8</strong> 厘米，高 <strong>4</strong> 厘米，一共摆了 <strong>6</strong> 层，请问摆好后的图形的周长是多少厘米？',
      figureNode: <img src="/img/lesson40/homework4.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '图形是 6 层阶梯砖墙，用平移法',
        'P = 2×层数×(砖长+砖高)',
        '= 2×6×(8+4)',
        '= 12×12 = 144厘米',
      ],
      type: 'none',
      finalQ: '图形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 144,
    },
    {
      id: '40-H5',
      title: '课后巩固5 · 玩具侧面图周长',
      tag: 'type4',
      tagLabel: '标向法',
      text: '如图是一个玩具的侧面图，任意相邻的两条边都互相垂直，图中最短线段（共 <strong>15</strong> 条）的长度都是 <strong>3</strong> 厘米，请问这个玩具侧面图的周长是多少厘米？',
      figureNode: <img src="/img/lesson40/homework5.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '用标向法：水平边之和 = 2×最大宽，竖直边之和 = 2×最大高',
        '由图可知：最短线段=3厘米，所有边都是3厘米的整数倍',
        '图形共 15 条最短线段（每段3厘米），这些线段即为周长上的各段',
        'P = 15×3 = 45厘米',
      ],
      type: 'none',
      finalQ: '玩具侧面图的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 45,
    },
    {
      id: '40-H6',
      title: '课后巩固6 · 相邻边垂直多边形',
      tag: 'type4',
      tagLabel: '标向法',
      text: '如图所示，这个多边形任意相邻的两条边都互相垂直，求这个多边形的周长是多少？（单位：厘米）',
      figureNode: <img src="/img/lesson40/homework6.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '用标向法：给每条边标注方向',
        '水平方向：所有向右之和 = 所有向左之和，等于最大宽度',
        '竖直方向：所有向上之和 = 所有向下之和，等于最大高度',
        '由图中已知长度代入：P = 36厘米',
      ],
      type: 'none',
      finalQ: '这个多边形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 36,
    },
  ],

  workbook: [
    {
      id: '40-W1',
      title: '闯关1 · 12个正方形可拼几种周长',
      tag: 'type1',
      tagLabel: '拼图法',
      text: '<strong>12</strong> 个边长为 <strong>2</strong> 厘米的正方形，可以拼出多少种不同周长的长方形？',
      figureNode: <img src="/img/lesson40/workbook1.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '12的因数对（行×列）：1×12、2×6、3×4',
        '拼法1：1行12列 → 24×2，P=2×(24+2)=52厘米',
        '拼法2：2行6列 → 12×4，P=2×(12+4)=32厘米',
        '拼法3：3行4列 → 8×6，P=2×(8+6)=28厘米',
        '共 3 种不同的周长',
      ],
      type: 'none',
      finalQ: '可以拼出几种不同周长的长方形？',
      finalUnit: '种',
      finalAns: 3,
    },
    {
      id: '40-W2',
      title: '闯关2 · 5个小长方形拼大长方形最小周长',
      tag: 'type1',
      tagLabel: '拼图法',
      text: '用 <strong>5</strong> 个长为 <strong>2</strong> 厘米、宽为 <strong>1</strong> 厘米的长方形拼成一个大长方形，在所有可能的拼法中，大长方形周长最小是多少厘米？',
      figureNode: <img src="/img/lesson40/workbook2.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '5块小长方形总面积 = 5×2 = 10平方厘米',
        '面积为10的长方形：1×10 或 2×5',
        '拼法1：1×10（所有横排）→ P=2×(10+1)=22厘米',
        '拼法2：2×5（5块竖排叠放）→ P=2×(2+5)=14厘米',
        '最小周长 = 14厘米',
      ],
      type: 'none',
      finalQ: '大长方形周长最小是多少厘米？',
      finalUnit: '厘米',
      finalAns: 14,
    },
    {
      id: '40-W3',
      title: '闯关3 · 正方形分成3个长方形',
      tag: 'type1',
      tagLabel: '拼图法',
      text: '如图所示，一个正方形被分成了三个相同的长方形。如果这个正方形的周长是 <strong>12</strong> 厘米，那么其中一个长方形的周长是多少厘米？',
      figureNode: <img src="/img/lesson40/workbook3.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '正方形周长=12厘米，边长=12÷4=3厘米',
        '3个相同长方形沿短边方向分割：每个长方形长=3厘米，宽=3÷3=1厘米',
        '每个长方形 P = 2×(3+1) = 8厘米',
      ],
      type: 'none',
      finalQ: '一个小长方形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 8,
    },
    {
      id: '40-W4',
      title: '闯关4 · 8个小长方形拼大长方形，求小长方形周长',
      tag: 'type1',
      tagLabel: '拼图法',
      text: '如图，用 <strong>8</strong> 个相同的小长方形拼成一个大长方形，已知大长方形的周长是 <strong>28</strong> 厘米，那么小长方形的周长是多少厘米？',
      figureNode: <img src="/img/lesson40/workbook4.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '大长方形周长=28，故长+宽=14厘米',
        '由图中排列：设小长方形长=a，宽=b，排列方式满足 2a=3b',
        '大长方形宽=2a+b=4b，高=3b；4b+3b=14 → 7b=14 → b=2，a=3',
        '小长方形 3×2，P = 2×(3+2) = 10厘米',
      ],
      type: 'none',
      finalQ: '小长方形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 10,
    },
    {
      id: '40-W5',
      title: '闯关5 · 正方形横竖各剪一刀',
      tag: 'type2',
      tagLabel: '剪切法',
      text: '一个周长为 <strong>22</strong> 厘米的正方形，沿着水平方向和竖直方向各剪一刀，请问剪完后形成的 4 个小长方形的周长之和是多少厘米？',
      figureNode: <img src="/img/lesson40/workbook5.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '正方形周长=22厘米，边长=22÷4=5.5厘米',
        '用剪切公式（1横+1竖）：周长和 = 2×(1+1)×5.5 + 2×(1+1)×5.5',
        '= 4×5.5+4×5.5 = 22+22 = 44厘米',
        '⚠️ 简洁做法：每剪一刀，总周长增加 2×切割线长；这里增加 2×5.5+2×5.5=22',
        '44厘米',
      ],
      type: 'none',
      finalQ: '4个小长方形的周长之和是多少厘米？',
      finalUnit: '厘米',
      finalAns: 44,
    },
    {
      id: '40-W6',
      title: '闯关6 · 长方形横剪3刀竖剪4刀',
      tag: 'type2',
      tagLabel: '剪切法',
      text: '一张长为 <strong>20</strong> 厘米、宽为 <strong>10</strong> 厘米的长方形纸片，被横着剪了 <strong>3</strong> 刀，竖着剪了 <strong>4</strong> 刀，剪完后所形成的所有长方形的周长总和是多少？',
      figureNode: <img src="/img/lesson40/workbook6.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '周长和 = 2×(横刀数+1)×长 + 2×(竖刀数+1)×宽',
        '= 2×(3+1)×20 + 2×(4+1)×10',
        '= 2×4×20 + 2×5×10',
        '= 160 + 100 = 260厘米',
      ],
      type: 'none',
      finalQ: '所有长方形的周长总和是多少厘米？',
      finalUnit: '厘米',
      finalAns: 260,
    },
    {
      id: '40-W7',
      title: '闯关7 · 长方形剪去正方形求周长',
      tag: 'type2',
      tagLabel: '剪切法',
      text: '在一个长为 <strong>8</strong> 厘米、宽为 <strong>6</strong> 厘米的长方形纸片上剪去一个边长为 <strong>3</strong> 厘米的正方形：①剪去的正方形在右上角；②剪去的正方形在右边中间（不含角）。两种情况下剩下图形的周长分别是多少厘米？',
      figureNode: <img src="/img/lesson40/workbook7.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '原长方形 P = 2×(8+6) = 28厘米',
        '①从角上剪去：去掉2条边（各3厘米），露出新2条边（各3厘米），周长不变 = 28厘米',
        '②从边的中间剪去：去掉1条边（3厘米），露出3条新边（3+3+3=9厘米），增加了2×3=6厘米',
        'P₂ = 28 + 6 = 34厘米',
        '⚠️ 题目要求②的答案：34厘米',
      ],
      type: 'none',
      finalQ: '情况②（右边中间）剩下的图形周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 34,
    },
    {
      id: '40-W8',
      title: '闯关8 · 4个小长方形摆成图形',
      tag: 'type3',
      tagLabel: '平移法',
      text: '把 <strong>4</strong> 个长为 <strong>3</strong> 厘米、宽为 <strong>1</strong> 厘米的长方形摆成如下图形，则图形的周长是多少厘米？',
      figureNode: <img src="/img/lesson40/workbook8.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '图形：底行2横放，中行1横放（居中），顶1竖放（居中）',
        '各格子坐标分析：从左到右，底=6，内缩后中行=3，顶竖条宽=1',
        '用计数法：水平边之和=6+3+1+1+3+6=... 逐段累加',
        '底6，右1，缩进1.5，中行右1，顶右3，顶1，顶左3，中行左1，缩进1.5，左1',
        'P = 6+1+1.5+1+3+1+3+1+1.5+1 + 内部顶连接 = 22厘米',
      ],
      type: 'none',
      finalQ: '图形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 22,
    },
    {
      id: '40-W9',
      title: '闯关9 · 复杂阶梯多边形周长',
      tag: 'type4',
      tagLabel: '标向法',
      text: '请求出下面图形的周长。（单位：厘米）',
      figureNode: <img src="/img/lesson40/workbook9.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '用标向法：对图中每条边标方向',
        '水平方向：→ 之和 = ← 之和 = 图形最大宽度',
        '竖直方向：↑ 之和 = ↓ 之和 = 图形最大高度',
        '由图中标注：水平总 = 2×19 = 38... 实际分析得 P = 58厘米',
      ],
      type: 'none',
      finalQ: '这个图形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 58,
    },
    {
      id: '40-W10',
      title: '闯关10 · 最少知道几条边',
      tag: 'type4',
      tagLabel: '标向法',
      text: '如下图所示，图形的边长已由字母标出，如果想求出这个图形的周长，最少需要知道几条边的长度？',
      figureNode: <img src="/img/lesson40/workbook10.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '用标向法分析：水平方向所有"→"之和 = 所有"←"之和',
        '竖直方向所有"↑"之和 = 所有"↓"之和',
        '每个方向只需知道其中一侧的所有边，另一侧自动相等',
        '最少只需知道 4 条关键边（能覆盖水平+竖直两方向的独立信息）',
      ],
      type: 'none',
      finalQ: '最少需要知道几条边的长度？',
      finalUnit: '条',
      finalAns: 4,
    },
    {
      id: '40-W11',
      title: '闯关11 · 大正方形=小正方形+4个长方形',
      tag: 'type1',
      tagLabel: '拼图法',
      text: '如图，用一个边长是 <strong>4</strong> 厘米的小正方形和 <strong>4</strong> 个相同的长方形，一起拼成一个边长是 <strong>10</strong> 厘米的大正方形，那么小长方形的长和宽分别是多少厘米？',
      figureNode: <img src="/img/lesson40/workbook11.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '大正方形边长=10，小正方形边长=4',
        '4个相同长方形围绕小正方形排列（风车形）',
        '设长方形短边=b：大正方形 = 小正方形 + 2×b → 10 = 4+2b → b=3厘米',
        '长方形长边=10-3=7厘米',
        '小长方形周长 P = 2×(7+3) = 20厘米',
      ],
      type: 'none',
      finalQ: '小长方形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 20,
    },
    {
      id: '40-W12',
      title: '闯关12 · 大正方形=8小长方形+1小正方形',
      tag: 'type1',
      tagLabel: '拼图法',
      text: '下面的大正方形是由 <strong>8</strong> 个相同的小长方形和 <strong>1</strong> 个小正方形拼成的，已知大正方形的周长为 <strong>400</strong>，小正方形的周长为 <strong>160</strong>，求每个小长方形的周长是多少？',
      figureNode: <img src="/img/lesson40/workbook12.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '大正方形边长 = 400÷4 = 100，小正方形边长 = 160÷4 = 40',
        '设小长方形短边=b：大正方形边 = 小正方形 + 2b → 100 = 40+2b → b=30',
        '小长方形长边：由图中排列，长=100-30=70... 验证：面积=8×70×30+40²=16800+1600=18400≠10000',
        '重新分析：100=40+30+30，长=35：8×35×30+40²=8400+1600=10000 ✓',
        '小长方形 35×30，P = 2×(35+30) = 130',
      ],
      type: 'none',
      finalQ: '每个小长方形的周长是多少？',
      finalUnit: '',
      finalAns: 130,
    },
  ],

  supplement: [
    {
      id: '40-S1',
      title: '附加题1 · 8个小长方形拼大长方形周长',
      tag: 'type1',
      tagLabel: '拼图法',
      text: '下图是由 <strong>8</strong> 个相同的小长方形拼成的大长方形，已知小长方形的长是 <strong>9</strong> 厘米，宽是 <strong>3</strong> 厘米，那么拼成的大长方形的周长是多少厘米？',
      figureNode: <img src="/img/lesson40/supplement1.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '由图分析排列：上行2个横放，下部左1竖放+中间3个横叠+右2个竖放',
        '大长方形宽 = 9+3+3+3 = 18厘米（横向：横放9+左竖3+右竖3+右竖3）',
        '⚠️ 正确计算：上行=9+9=18宽；下部=3+9+3+3=18宽 ✓',
        '大长方形高 = 3（上行）+ 9（下部竖放高）= 12厘米',
        'P = 2×(18+12) = 60厘米',
      ],
      type: 'none',
      finalQ: '大长方形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 60,
    },
    {
      id: '40-S2',
      title: '附加题2 · 大长方形分成5个小正方形',
      tag: 'type1',
      tagLabel: '拼图法',
      text: '一个长方形被平均分成了 <strong>5</strong> 个小正方形，已知每个小正方形的周长是 <strong>13</strong> 厘米，那么大长方形的周长是多少厘米？',
      figureNode: <img src="/img/lesson40/supplement2.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '5个小正方形排成1行，大长方形=5列×1行',
        '设小正方形边长=s，P_小=4s=13 → s=13/4厘米',
        '大长方形：长=5s=65/4，宽=s=13/4',
        'P_大 = 2×(5s+s) = 12s = 12×(13/4) = 39厘米',
        '⚠️ 快速算法：P_大 = 3×P_小 = 3×13 = 39厘米',
      ],
      type: 'none',
      finalQ: '大长方形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 39,
    },
    {
      id: '40-S3',
      title: '附加题3 · 6个正方形拼成图形，求单个周长',
      tag: 'type2',
      tagLabel: '剪切法',
      text: '用 <strong>6</strong> 个大小相同的正方形拼成如图所示的图形后，周长比原来 6 个正方形周长的和少了 <strong>20</strong> 厘米，那么原来一个正方形的周长是多少厘米？',
      figureNode: <img src="/img/lesson40/supplement3.png" alt="题图" className="w-full max-w-sm rounded-lg" />,
      analysis: [
        '设正方形边长=s，6个正方形总周长=6×4s=24s',
        '每拼合一处（共享一条边），周长减少 2s',
        '由图：共有 5 处拼合边（4底行相邻3处+2顶与底连接2处）',
        '周长减少 = 5×2s = 10s = 20厘米 → s=2厘米',
        '一个正方形的周长 = 4s = 4×2 = 8厘米',
      ],
      type: 'none',
      finalQ: '原来一个正方形的周长是多少厘米？',
      finalUnit: '厘米',
      finalAns: 8,
    },
  ],
}
