import type { Problem, ProblemSet } from './type'

const PRETEST: Problem[] = [
  {
    id: '15-P1',
    title: '课前测1 · 气球和差',
    tag: 'type1',
    tagLabel: '基本和差', difficulty: 1,
    text: '红气球和黄气球排成一排，纳纳数了数发现<strong>红气球比黄气球多 4 个</strong>，红气球和黄气球<strong>一共有 12 个</strong>。你知道红气球和黄气球各有多少个吗？',
    analysis: [
      '大数（红）= (和 + 差) ÷ 2 = (12 + 4) ÷ 2 = 8',
      '小数（黄）= (和 − 差) ÷ 2 = (12 − 4) ÷ 2 = 4',
      '红气球有 <strong>8</strong> 个，黄气球有 4 个',
    ],
    type: 'none',
    finalQ: '红气球有多少个？',
    finalUnit: '个',
    finalAns: 8,
  },
  {
    id: '15-P2',
    title: '课前测2 · 汉堡饮料',
    tag: 'type1',
    tagLabel: '基本和差', difficulty: 1,
    text: '丁丁到西餐厅买了一份汉堡和一杯饮料，<strong>一共花了 40 元</strong>，<strong>汉堡的价格比饮料贵 12 元</strong>，你能帮丁丁算出汉堡和饮料各是多少元吗？',
    analysis: [
      '大数（汉堡）= (和 + 差) ÷ 2 = (40 + 12) ÷ 2 = 26',
      '小数（饮料）= (和 − 差) ÷ 2 = (40 − 12) ÷ 2 = 14',
      '汉堡 <strong>26 元</strong>，饮料 14 元',
    ],
    type: 'none',
    finalQ: '汉堡多少元？',
    finalUnit: '元',
    finalAns: 26,
  },
  {
    id: '15-P3',
    title: '课前测3 · 千纸鹤',
    tag: 'type4',
    tagLabel: '移多补少', difficulty: 2,
    text: '纳纳和约约<strong>一共叠了 60 只千纸鹤</strong>，如果<strong>纳纳给约约 10 只</strong>，那么两人的千纸鹤数目就一样多，她们两人各叠了多少只千纸鹤？',
    analysis: [
      '移多补少：给出 10 只后相等，说明差 = 2 × 10 = 20',
      '纳纳（大数）= (60 + 20) ÷ 2 = 40',
      '约约（小数）= (60 − 20) ÷ 2 = 20',
      '纳纳叠了 <strong>40</strong> 只，约约叠了 20 只',
    ],
    type: 'none',
    finalQ: '纳纳叠了多少只？',
    finalUnit: '只',
    finalAns: 40,
  },
  {
    id: '15-P4',
    title: '课前测4 · 苹果维尼熊',
    tag: 'type5',
    tagLabel: '双向变化找差', difficulty: 3,
    text: '维尼熊和小猪<strong>一共摘了 17 个苹果</strong>，如果<strong>维尼熊把自己摘的苹果给小猪 5 个后，还比小猪多 1 个</strong>，那么维尼熊摘了多少个？',
    analysis: [
      '维尼熊给小猪 5 个后还多 1 个，说明变化后差 = 1',
      '原来差 = 变化后差 + 2 × 转移量 = 1 + 2 × 5 = 11',
      '维尼熊（大数）= (17 + 11) ÷ 2 = 14',
      '维尼熊原来摘了 <strong>14</strong> 个',
    ],
    type: 'none',
    finalQ: '维尼熊摘了多少个？',
    finalUnit: '个',
    finalAns: 14,
  },
  {
    id: '15-P5',
    title: '课前测5 · 两箱水果',
    tag: 'type5',
    tagLabel: '双向变化找差', difficulty: 3,
    text: '甲、乙<strong>两箱水果共重 50 千克</strong>，如果<strong>从甲箱中取出 4 千克，乙箱中放入 6 千克</strong>，两箱水果正好相等。原来甲、乙两箱各有水果多少千克？',
    analysis: [
      '甲取出 4，乙放入 6 后相等，说明甲减 4，乙加 6',
      '变化后两箱相等，变化量合计：甲减了 4，乙多了 6，共差 10',
      '原来甲比乙多 4 + 6 = 10 千克',
      '甲（大数）= (50 + 10) ÷ 2 = <strong>30</strong>，乙 = 20 千克',
    ],
    type: 'none',
    finalQ: '原来甲箱有多少千克？',
    finalUnit: '千克',
    finalAns: 30,
  },
]

const LESSON: Problem[] = [
  {
    id: '15-L1',
    title: '例1 · 汉堡与饮料',
    tag: 'type1',
    tagLabel: '基本和差', difficulty: 1,
    text: '甜甜到西餐厅买了一个汉堡和一杯饮料，<strong>一共花了 22 元</strong>，<strong>汉堡的价格比饮料贵 2 元</strong>，那么一个汉堡和一杯饮料的价钱分别是多少？',
    analysis: [
      '和 = 22，差 = 2',
      '大数（汉堡）= (和 + 差) ÷ 2 = (22 + 2) ÷ 2 = 12',
      '小数（饮料）= (和 − 差) ÷ 2 = (22 − 2) ÷ 2 = 10',
      '汉堡 <strong>12 元</strong>，饮料 10 元',
    ],
    type: 'none',
    finalQ: '汉堡多少元？',
    finalUnit: '元',
    finalAns: 12,
  },
  {
    id: '15-L2',
    title: '练一练 · 桃树梨树',
    tag: 'type1',
    tagLabel: '基本和差', difficulty: 1,
    text: '果园里有桃树和梨树<strong>一共 48 棵</strong>，立立数了一下发现<strong>桃树比梨树少 8 棵</strong>，那么桃树和梨树各有多少棵？',
    analysis: [
      '和 = 48，差 = 8（梨树比桃树多）',
      '大数（梨树）= (48 + 8) ÷ 2 = 28',
      '小数（桃树）= (48 − 8) ÷ 2 = 20',
      '桃树 <strong>20</strong> 棵，梨树 28 棵',
    ],
    type: 'none',
    finalQ: '桃树有多少棵？',
    finalUnit: '棵',
    finalAns: 20,
  },
  {
    id: '15-L3',
    title: '例2 · 口算题时间匹配',
    tag: 'type2',
    tagLabel: '时间匹配和差', difficulty: 2,
    text: '小立和小约两人 <strong>3 分钟共做了 120 道口算题</strong>，已知<strong>小立每分钟比小约多做 20 道</strong>，那么他们每分钟各做了多少道口算题？',
    analysis: [
      '每分钟总量 = 120 ÷ 3 = 40 道',
      '和 = 40，差 = 20',
      '立立每分钟（大数）= (40 + 20) ÷ 2 = 30',
      '约约每分钟（小数）= (40 − 20) ÷ 2 = 10',
      '立立每分钟 <strong>30</strong> 道，约约 10 道',
    ],
    type: 'none',
    finalQ: '立立每分钟多少道？',
    finalUnit: '道',
    finalAns: 30,
  },
  {
    id: '15-L4',
    title: '练一练 · 打字速度',
    tag: 'type2',
    tagLabel: '时间匹配和差', difficulty: 2,
    text: '奇奇和苗苗两人 <strong>2 分钟一共打字 100 个</strong>，已知<strong>奇奇每分钟比苗苗少打 10 个字</strong>，那么奇奇和苗苗每分钟分别能打多少个字？',
    analysis: [
      '每分钟总量 = 100 ÷ 2 = 50 个',
      '和 = 50，差 = 10（苗苗比奇奇多）',
      '苗苗每分钟（大数）= (50 + 10) ÷ 2 = 30',
      '奇奇每分钟（小数）= (50 − 10) ÷ 2 = 20',
      '奇奇每分钟 <strong>20</strong> 个',
    ],
    type: 'none',
    finalQ: '奇奇每分钟多少个？',
    finalUnit: '个',
    finalAns: 20,
  },
  {
    id: '15-L5',
    title: '例3 · 语数平均分',
    tag: 'type3',
    tagLabel: '平均数变形', difficulty: 2,
    text: '辰辰在期中考试时，语文、数学两科<strong>平均分是 95 分</strong>，<strong>数学比语文多 10 分</strong>，那么辰辰语文和数学各得了多少分？',
    analysis: [
      '和 = 平均分 × 2 = 95 × 2 = 190',
      '差 = 10（数学比语文多）',
      '数学（大数）= (190 + 10) ÷ 2 = 100',
      '语文（小数）= (190 − 10) ÷ 2 = 90',
      '语文 <strong>90 分</strong>，数学 100 分',
    ],
    type: 'none',
    finalQ: '语文多少分？',
    finalUnit: '分',
    finalAns: 90,
  },
  {
    id: '15-L6',
    title: '练一练 · 玩具身高',
    tag: 'type3',
    tagLabel: '平均数变形', difficulty: 2,
    text: '纳纳在给玩具小猴和小马测量身高，已知<strong>它们的平均身高是 80 厘米</strong>，<strong>小猴比小马矮 40 厘米</strong>。你能算出玩具小猴和小马的身高分别是多少厘米吗？',
    analysis: [
      '和 = 平均数 × 2 = 80 × 2 = 160',
      '差 = 40（小马比小猴高）',
      '小马（大数）= (160 + 40) ÷ 2 = 100',
      '小猴（小数）= (160 − 40) ÷ 2 = 60',
      '玩具小猴身高 <strong>60</strong> 厘米',
    ],
    type: 'none',
    finalQ: '玩具小猴身高多少cm？',
    finalUnit: 'cm',
    finalAns: 60,
  },
  {
    id: '15-L7',
    title: '例4 · 书架上下层',
    tag: 'type4',
    tagLabel: '移多补少', difficulty: 2,
    text: '图书馆的书架<strong>上下两层共存书 52 本</strong>，如果<strong>从上层拿 6 本给下层</strong>，则两层书一样多。那么上层、下层各有书多少本？',
    analysis: [
      '移多补少：从上层移 6 本后相等，差 = 2 × 6 = 12',
      '上层（大数）= (52 + 12) ÷ 2 = 32',
      '下层（小数）= (52 − 12) ÷ 2 = 20',
      '上层 <strong>32</strong> 本，下层 20 本',
    ],
    type: 'none',
    finalQ: '上层有多少本？',
    finalUnit: '本',
    finalAns: 32,
  },
  {
    id: '15-L8',
    title: '练一练 · 红黄油桶',
    tag: 'type4',
    tagLabel: '移多补少', difficulty: 2,
    text: '有红色和黄色两桶油，<strong>一共有 34 升</strong>，如果<strong>将红色油桶中的 3 升油倒入黄色油桶中</strong>，这时两桶油就一样多了。请问两桶油各有多少升？',
    analysis: [
      '移多补少：从红桶移 3 升后相等，差 = 2 × 3 = 6',
      '红桶（大数）= (34 + 6) ÷ 2 = 20',
      '黄桶（小数）= (34 − 6) ÷ 2 = 14',
      '红桶 <strong>20</strong> 升，黄桶 14 升',
    ],
    type: 'none',
    finalQ: '红桶有多少升？',
    finalUnit: '升',
    finalAns: 20,
  },
  {
    id: '15-L9',
    title: '例5 · 萝卜小白黑兔',
    tag: 'type5',
    tagLabel: '双向变化找差', difficulty: 3,
    text: '兔妈妈拔了 <strong>13 个萝卜</strong>分给了小白兔和小黑兔，兔妈妈让<strong>小白兔给小黑兔 3 根，这时发现小白兔比小黑兔少了 1 根</strong>，你知道原来小白兔和小黑兔各分到了多少根萝卜吗？',
    analysis: [
      '小白给小黑 3 根后，小白比小黑少 1 根，变化后差 = −1（白 < 黑）',
      '原来差 = 变化后差 + 2 × 3 = −1 + 6 = 5（白 > 黑）',
      '原来小白（大数）= (13 + 5) ÷ 2 = 9',
      '原来小黑（小数）= (13 − 5) ÷ 2 = 4',
      '小白兔原来有 <strong>9</strong> 根',
    ],
    type: 'none',
    finalQ: '原来小白兔有多少根？',
    finalUnit: '根',
    finalAns: 9,
  },
  {
    id: '15-L10',
    title: '练一练 · 零花钱乐乐豆丁',
    tag: 'type5',
    tagLabel: '双向变化找差', difficulty: 3,
    text: '乐乐和豆丁<strong>一共有 28 元</strong>的零花钱，<strong>乐乐给了豆丁 5 元，这时乐乐还比豆丁多 2 元</strong>，那么乐乐和豆丁原来分别有多少元钱？',
    analysis: [
      '乐乐给豆丁 5 元后，乐乐还多 2 元，变化后差 = 2',
      '原来差 = 变化后差 + 2 × 5 = 2 + 10 = 12',
      '乐乐（大数）= (28 + 12) ÷ 2 = 20',
      '豆丁（小数）= (28 − 12) ÷ 2 = 8',
      '乐乐原来有 <strong>20</strong> 元',
    ],
    type: 'none',
    finalQ: '乐乐原来有多少元？',
    finalUnit: '元',
    finalAns: 20,
  },
  {
    id: '15-L11',
    title: '例6 · 数学英语兴趣小组',
    tag: 'type5',
    tagLabel: '双向变化找差', difficulty: 3,
    text: '数学兴趣小组和英语兴趣小组<strong>一共有 45 人</strong>，如果<strong>数学兴趣小组增加 4 个人、英语兴趣小组减少 1 个人</strong>，这时两个小组人数一样多，那么数学兴趣小组原来有多少人？',
    analysis: [
      '变化后相等：数学 +4，英语 −1，合计差变了 4+1=5',
      '变化后相等，说明原来英语 > 数学，差 = 5',
      '数学（小数）= (45 − 5) ÷ 2 = 20',
      '英语（大数）= (45 + 5) ÷ 2 = 25',
      '数学组原来 <strong>20</strong> 人',
    ],
    type: 'none',
    finalQ: '数学组原来多少人？',
    finalUnit: '人',
    finalAns: 20,
  },
  {
    id: '15-L12',
    title: '练一练 · 故事科技书',
    tag: 'type5',
    tagLabel: '双向变化找差', difficulty: 3,
    text: '图书馆志愿者娜娜发现故事书和科技书<strong>一共有 60 本</strong>。周二故事书<strong>被借出去了 2 本</strong>，科技书<strong>还回来了 4 本</strong>，这时故事书和科技书一样多。那么故事书和科技书各有多少本？',
    analysis: [
      '变化后相等：故事书 −2，科技书 +4，合计差变了 2+4=6',
      '变化后相等，说明原来故事书 > 科技书，差 = 6',
      '故事书（大数）= (60 + 6) ÷ 2 = 33',
      '科技书（小数）= (60 − 6) ÷ 2 = 27',
      '故事书有 <strong>33</strong> 本',
    ],
    type: 'none',
    finalQ: '故事书有多少本？',
    finalUnit: '本',
    finalAns: 33,
  },
]

const HOMEWORK: Problem[] = [
  {
    id: '15-H1',
    title: '巩固1 · 两筐水果',
    tag: 'type1',
    tagLabel: '基本和差', difficulty: 1,
    text: '两筐水果<strong>共重 150 千克</strong>，<strong>第一筐比第二筐少 10 千克</strong>，两筐水果各重多少千克？',
    analysis: [
      '和 = 150，差 = 10（第二筐比第一筐多）',
      '第二筐（大数）= (150 + 10) ÷ 2 = 80',
      '第一筐（小数）= (150 − 10) ÷ 2 = 70',
      '第一筐 <strong>70</strong> 千克，第二筐 80 千克',
    ],
    type: 'none',
    finalQ: '第一筐有多少千克？',
    finalUnit: '千克',
    finalAns: 70,
  },
  {
    id: '15-H2',
    title: '巩固2 · 剪纸速度',
    tag: 'type2',
    tagLabel: '时间匹配和差', difficulty: 2,
    text: '小明和小花两人比赛剪纸，已知<strong>两人 5 分钟一共剪纸 40 个</strong>，<strong>小明比小花每分钟少剪 2 个</strong>，那么小明和小花每人每分钟各剪多少个？',
    analysis: [
      '每分钟总量 = 40 ÷ 5 = 8 个',
      '和 = 8，差 = 2（小花比小明多）',
      '小花（大数）= (8 + 2) ÷ 2 = 5',
      '小明（小数）= (8 − 2) ÷ 2 = 3',
      '小明每分钟 <strong>3</strong> 个',
    ],
    type: 'none',
    finalQ: '小明每分多少个？',
    finalUnit: '个',
    finalAns: 3,
  },
  {
    id: '15-H3',
    title: '巩固3 · 平均年龄',
    tag: 'type3',
    tagLabel: '平均数变形', difficulty: 1,
    text: '纳纳和约约两人的<strong>平均年龄是 11 岁</strong>，<strong>约约比纳纳大 2 岁</strong>，那么纳纳和约约两人的年龄分别是多少？',
    analysis: [
      '和 = 11 × 2 = 22，差 = 2（约约比纳纳大）',
      '约约（大数）= (22 + 2) ÷ 2 = 12',
      '纳纳（小数）= (22 − 2) ÷ 2 = 10',
      '纳纳 <strong>10</strong> 岁，约约 12 岁',
    ],
    type: 'none',
    finalQ: '纳纳多少岁？',
    finalUnit: '岁',
    finalAns: 10,
  },
  {
    id: '15-H4',
    title: '巩固4 · 转班学生',
    tag: 'type4',
    tagLabel: '移多补少', difficulty: 2,
    text: '阳光小学一年级（1）班和（2）班<strong>一共有 60 名学生</strong>，如果<strong>（1）班有 5 名学生转班到（2）班</strong>，那么两个班的学生人数一样多。请问一年级（1）班和（2）班分别有多少名学生？',
    analysis: [
      '移多补少：从（1）班移 5 人后相等，差 = 2 × 5 = 10',
      '（1）班（大数）= (60 + 10) ÷ 2 = 35',
      '（2）班（小数）= (60 − 10) ÷ 2 = 25',
      '（1）班 <strong>35</strong> 人，（2）班 25 人',
    ],
    type: 'none',
    finalQ: '(1)班有多少名学生？',
    finalUnit: '名',
    finalAns: 35,
  },
  {
    id: '15-H5',
    title: '巩固5 · 两桶水',
    tag: 'type5',
    tagLabel: '双向变化找差', difficulty: 3,
    text: '两桶水<strong>共重 35 斤</strong>，如果<strong>从第一桶取出 2 斤倒入第二桶，那么第一桶水的重量比第二桶还多 1 斤</strong>。原来第一桶和第二桶各有水多少斤？',
    analysis: [
      '第一桶取 2 斤给第二桶后，第一桶还多 1 斤，变化后差 = 1',
      '原来差 = 变化后差 + 2 × 2 = 1 + 4 = 5',
      '第一桶（大数）= (35 + 5) ÷ 2 = 20',
      '第二桶（小数）= (35 − 5) ÷ 2 = 15',
      '第一桶原来 <strong>20</strong> 斤',
    ],
    type: 'none',
    finalQ: '第一桶有多少斤？',
    finalUnit: '斤',
    finalAns: 20,
  },
  {
    id: '15-H6',
    title: '巩固6 · 停车场',
    tag: 'type5',
    tagLabel: '双向变化找差', difficulty: 3,
    text: '某商场停车场分为上下两层，<strong>原来一共停有车辆 45 辆</strong>，一个小时后，<strong>上层开走了 3 辆，下层开走了 10 辆</strong>，这时上下两层停车场停有车辆一样多。请问原来上下停车场各有多少辆车？',
    analysis: [
      '上层 −3，下层 −10 后相等；下层开走得更多，说明原来下层多',
      '变化后相等，说明原来下层 > 上层，原差 = 10 − 3 = 7',
      '上层（小数）= (45 − 7) ÷ 2 = 19，下层（大数）= (45 + 7) ÷ 2 = 26',
      '上层 <strong>26</strong> 辆，下层 19 辆（注：题目问上层原来）',
    ],
    type: 'none',
    finalQ: '上层原来有多少辆？',
    finalUnit: '辆',
    finalAns: 26,
  },
]

const WORKBOOK: Problem[] = [
  {
    id: '15-W1',
    title: '闯关1 · 作业本田格本',
    tag: 'type1',
    tagLabel: '基本和差', difficulty: 1,
    text: '爸爸给豆包买回作业本和田格本<strong>共 20 本</strong>，已知<strong>作业本比田格本多 6 本</strong>，那么爸爸买回的作业本和田格本各多少本？',
    analysis: [
      '和 = 20，差 = 6',
      '作业本（大数）= (20 + 6) ÷ 2 = 13',
      '田格本（小数）= (20 − 6) ÷ 2 = 7',
      '作业本 <strong>13</strong> 本，田格本 7 本',
    ],
    type: 'none',
    finalQ: '作业本有多少本？',
    finalUnit: '本',
    finalAns: 13,
  },
  {
    id: '15-W2',
    title: '闯关2 · 奶油饼干',
    tag: 'type4',
    tagLabel: '移多补少', difficulty: 2,
    text: '毛毛和豆豆<strong>共有 47 块奶油饼干</strong>，如果<strong>豆豆吃掉 7 块后</strong>，两人的饼干数就相等了。那么毛毛和豆豆分别有多少块饼干？',
    analysis: [
      '豆豆吃掉 7 块后与毛毛相等，说明豆豆原来比毛毛多 7 块，差 = 7',
      '豆豆（大数）= (47 + 7) ÷ 2 = 27',
      '毛毛（小数）= (47 − 7) ÷ 2 = 20',
      '毛毛有 <strong>20</strong> 块，豆豆有 27 块',
    ],
    type: 'none',
    finalQ: '毛毛有多少块？',
    finalUnit: '块',
    finalAns: 20,
  },
  {
    id: '15-W3',
    title: '闯关3 · 甲乙仓库大米',
    tag: 'type4',
    tagLabel: '移多补少', difficulty: 2,
    text: '甲、乙两个仓库<strong>共存大米 50 吨</strong>，如果<strong>从甲仓库运 8 吨大米到乙仓库</strong>，两个仓库大米吨数正好相等。请问：原来两个仓库各有大米多少吨？',
    analysis: [
      '移多补少：从甲移 8 吨后相等，差 = 2 × 8 = 16',
      '甲（大数）= (50 + 16) ÷ 2 = 33',
      '乙（小数）= (50 − 16) ÷ 2 = 17',
      '甲仓库 <strong>33</strong> 吨，乙仓库 17 吨',
    ],
    type: 'none',
    finalQ: '甲仓有多少吨？',
    finalUnit: '吨',
    finalAns: 33,
  },
  {
    id: '15-W4',
    title: '闯关4 · 思思约约零花钱',
    tag: 'type5',
    tagLabel: '双向变化找差', difficulty: 3,
    text: '思思和约约两人<strong>共有 160 元</strong>，如果<strong>思思增加 13 元，而约约减少 27 元</strong>，那么两人的钱数就相等，请问他俩原来各有多少元钱？',
    analysis: [
      '变化后相等：思思 +13，约约 −27，合计差变了 13+27=40',
      '约约减得多，说明原来约约 > 思思，原差 = 40',
      '约约（大数）= (160 + 40) ÷ 2 = 100',
      '思思（小数）= (160 − 40) ÷ 2 = 60',
      '思思原来 <strong>60</strong> 元，约约 <strong>100</strong> 元',
    ],
    type: 'none',
    finalQ: '思思原来有多少元？',
    finalUnit: '元',
    finalAns: 60,
  },
  {
    id: '15-W5',
    title: '闯关5 · 甲乙苹果箱',
    tag: 'type5',
    tagLabel: '双向变化找差', difficulty: 3,
    text: '甲、乙两箱有苹果 <strong>35 千克</strong>，如果<strong>从甲箱中取 2 千克放到乙箱中，这时甲箱比乙箱多 3 千克</strong>，那么两箱原有苹果多少千克？',
    analysis: [
      '甲取 2 千克给乙后甲还多 3，变化后差 = 3',
      '原来差 = 变化后差 + 2 × 2 = 3 + 4 = 7',
      '甲（大数）= (35 + 7) ÷ 2 = 21',
      '乙（小数）= (35 − 7) ÷ 2 = 14',
      '甲箱原来 <strong>21</strong> 千克',
    ],
    type: 'none',
    finalQ: '甲箱原有多少千克？',
    finalUnit: '千克',
    finalAns: 21,
  },
  {
    id: '15-W6',
    title: '闯关6 · 豆丁豆包图画书',
    tag: 'type5',
    tagLabel: '双向变化找差', difficulty: 4,
    text: '豆丁和豆包<strong>共有图画书 61 本</strong>，<strong>豆丁给了豆包 5 本后，豆包自己又新买了 3 本，豆丁现在比豆包少 2 本</strong>图画书。那么豆包原来有多少本图画书？',
    analysis: [
      '设豆包原来有 x 本，豆丁有 61−x 本',
      '变化后：豆包 = x+5+3 = x+8，豆丁 = 61−x−5 = 56−x',
      '豆丁比豆包少 2：(56−x) − (x+8) = −2 → 48−2x = −2 → x = 25',
      '豆包原来有 <strong>25</strong> 本',
    ],
    type: 'none',
    finalQ: '豆包原来有多少本？',
    finalUnit: '本',
    finalAns: 25,
  },
  {
    id: '15-W7',
    title: '闯关7 · 三只兔萝卜',
    tag: 'type1',
    tagLabel: '基本和差', difficulty: 3,
    text: '兔妈妈拔了 <strong>33 根萝卜</strong>分给黑兔、白兔和灰兔，已知<strong>黑兔比白兔多 1 根，白兔又比灰兔多 1 根</strong>，请问它们分别分到了多少根萝卜？',
    analysis: [
      '设灰兔 = x，白兔 = x+1，黑兔 = x+2',
      '3x + 3 = 33 → x = 10',
      '灰兔 <strong>10</strong> 根，白兔 11 根，黑兔 12 根',
    ],
    type: 'none',
    finalQ: '灰兔有多少根？',
    finalUnit: '根',
    finalAns: 10,
  },
  {
    id: '15-W8',
    title: '闯关8 · 三人卡片',
    tag: 'type1',
    tagLabel: '基本和差', difficulty: 3,
    text: '立立、奇奇、苗苗<strong>一共有 73 张卡片</strong>，<strong>立立比奇奇多 5 张，苗苗比奇奇少 4 张</strong>，那么苗苗有多少张卡片？',
    analysis: [
      '设奇奇 = x，立立 = x+5，苗苗 = x−4',
      '3x + 1 = 73 → 3x = 72 → x = 24',
      '苗苗 = 24 − 4 = <strong>20</strong> 张',
    ],
    type: 'none',
    finalQ: '苗苗有多少张？',
    finalUnit: '张',
    finalAns: 20,
  },
  {
    id: '15-W9',
    title: '闯关9 · 三种蔬菜',
    tag: 'type1',
    tagLabel: '基本和差', difficulty: 4,
    text: '学校食堂共有三种蔬菜，其中<strong>黄瓜、番茄共重 28 千克，青菜、黄瓜共重 30 千克，青菜、番茄共重 32 千克</strong>。这三种蔬菜各有多少千克？',
    analysis: [
      '三式相加：2×(黄瓜+番茄+青菜) = 28+30+32 = 90',
      '黄瓜+番茄+青菜 = 45',
      '黄瓜 = 45 − 32 = 13，番茄 = 45 − 30 = 15，青菜 = 45 − 28 = 17',
      '黄瓜 <strong>13</strong> 千克',
    ],
    type: 'none',
    finalQ: '黄瓜有多少千克？',
    finalUnit: '千克',
    finalAns: 13,
  },
]

export const PROBLEMS: ProblemSet = {
  pretest: PRETEST,
  lesson: LESSON,
  homework: HOMEWORK,
  workbook: WORKBOOK,
}

export const PROBLEM_TYPES = [
  {
    tag: 'type1',
    color: 'blue',
    label: '题型1·基本和差',
    desc: '大数=(和+差)÷2，小数=(和-差)÷2。',
    example: '例：和22，差2 → 大=12，小=10',
  },
  {
    tag: 'type2',
    color: 'green',
    label: '题型2·时间匹配和差',
    desc: '先求每分钟总量，再用和差公式分配。',
    example: '例：3分钟共120题，每分钟差20 → 大=30，小=10',
  },
  {
    tag: 'type3',
    color: 'orange',
    label: '题型3·平均数变形',
    desc: '平均数=和÷2，利用平均数推出每个量。',
    example: '例：平均95，差10 → 大=100，小=90',
  },
  {
    tag: 'type4',
    color: 'purple',
    label: '题型4·移多补少',
    desc: '移多补少：移动后相等，2×移动量=差。',
    example: '例：移6本后相等 → 差=12本',
  },
  {
    tag: 'type5',
    color: 'red',
    label: '题型5·双向变化找差',
    desc: '两量各自变化后相等，综合求原来的差。',
    example: '例：一增一减后相等，新差=原差±变化',
  },
]

export const TYPE_STYLE: Record<
  string,
  { bg: string; border: string; titleColor: string; textColor: string }
> = {
  type1: {
    bg: 'bg-blue-50',
    border: 'border-l-blue-500',
    titleColor: 'text-blue-800',
    textColor: 'text-blue-900',
  },
  type2: {
    bg: 'bg-green-50',
    border: 'border-l-green-500',
    titleColor: 'text-green-800',
    textColor: 'text-green-900',
  },
  type3: {
    bg: 'bg-orange-50',
    border: 'border-l-orange-500',
    titleColor: 'text-orange-800',
    textColor: 'text-orange-900',
  },
  type4: {
    bg: 'bg-purple-50',
    border: 'border-l-purple-500',
    titleColor: 'text-purple-800',
    textColor: 'text-purple-900',
  },
  type5: {
    bg: 'bg-red-50',
    border: 'border-l-red-500',
    titleColor: 'text-red-800',
    textColor: 'text-red-900',
  },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-blue-100 text-blue-800',
  type2: 'bg-green-100 text-green-800',
  type3: 'bg-orange-100 text-orange-800',
  type4: 'bg-purple-100 text-purple-800',
  type5: 'bg-red-100 text-red-800',
}
