import type { Problem, ProblemSet } from './type'

const LESSON: Problem[] = [
  {
    id: '39-L1',
    title: '例1 · 盈盈问题：买铅笔',
    tag: 'type1',
    tagLabel: '盈盈',
    text: '妈妈给了文文一些钱去买铅笔。到了文具店，文文发现如果买 <strong>6 支</strong>铅笔，剩下 <strong>11 元</strong>；如果买 <strong>4 支</strong>同样的铅笔，剩下 <strong>19 元</strong>。请问，妈妈给了文文多少钱？',
    analysis: [
      '两次购买都有剩余（盈盈问题）',
      '买的数量差：6 − 4 = 2（支）',
      '剩余差额：19 − 11 = 8（元）',
      '铅笔单价 = 差额 ÷ 数量差 = 8 ÷ 2 = 4（元）',
      '妈妈的钱 = 单价 × 支数 + 剩余 = 4 × 6 + 11 = 35（元）',
      '验证：4 × 4 + 19 = 16 + 19 = 35（元）✓',
    ],
    type: 'none',
    finalQ: '妈妈给了文文多少钱？',
    finalUnit: '元',
    finalAns: 35,
  },
  {
    id: '39-L2',
    title: '练一练 · 盈盈问题：孙悟空发香蕉',
    tag: 'type1',
    tagLabel: '盈盈',
    text: '孙悟空给小猴子发香蕉，每只小猴子发的香蕉一样多。如果每只小猴子发 <strong>7 根</strong>香蕉，最后还能剩 <strong>4 根</strong>；如果每只小猴子发 <strong>4 根</strong>香蕉，最后能剩 <strong>25 根</strong>。请问孙悟空一共准备了多少根香蕉？',
    analysis: [
      '两次分配都有剩余（盈盈问题）',
      '每份差额：7 − 4 = 3（根）',
      '剩余差额：25 − 4 = 21（根）',
      '小猴子数 = 剩余差额 ÷ 每份差额 = 21 ÷ 3 = 7（只）',
      '香蕉总数 = 7 × 7 + 4 = 53（根）',
      '验证：7 × 4 + 25 = 28 + 25 = 53（根）✓',
    ],
    type: 'none',
    finalQ: '孙悟空一共准备了多少根香蕉？',
    finalUnit: '根',
    finalAns: 53,
  },
  {
    id: '39-L3',
    title: '例2 · 盈恰问题：弹珠放盒子',
    tag: 'type4',
    tagLabel: '盈恰',
    text: '奇奇要把一些弹珠放在盒子里。如果每个盒子放 <strong>2 个</strong>，最后剩下 <strong>9 个</strong>；如果每个盒子放 <strong>5 个</strong>，<strong>正好放完</strong>。那么有多少个盒子？有多少个弹珠？',
    analysis: [
      '一次有剩余（盈），一次正好（恰）→ 盈恰问题',
      '每份差额：5 − 2 = 3（个）',
      '盈的数量：9（个）',
      '盒子数 = 盈的数量 ÷ 每份差额 = 9 ÷ 3 = 3（个）',
      '弹珠总数 = 3 × 2 + 9 = 15（个）',
      '验证：3 × 5 = 15（个）✓',
    ],
    type: 'none',
    finalQ: '弹珠一共有多少个？',
    finalUnit: '个',
    finalAns: 15,
  },
  {
    id: '39-L4',
    title: '练一练 · 亏恰问题：约约做数学题',
    tag: 'type5',
    tagLabel: '亏恰',
    text: '约约在假期中计划做一些数学题。若每天做 <strong>4 道题</strong>，则会剩 <strong>12 道题</strong>做不完；若每天做 <strong>5 道题</strong>，<strong>正好全部做完</strong>。请问假期有多少天？约约一共准备做多少道题？',
    analysis: [
      '一次不足（亏），一次正好（恰）→ 亏恰问题',
      '每份差额：5 − 4 = 1（道）',
      '亏的数量：12（道）',
      '天数 = 亏的数量 ÷ 每份差额 = 12 ÷ 1 = 12（天）',
      '题目总数 = 12 × 4 + 12 = 60（道）',
      '验证：12 × 5 = 60（道）✓',
    ],
    type: 'none',
    finalQ: '约约一共准备做多少道题？',
    finalUnit: '道',
    finalAns: 60,
  },
  {
    id: '39-L5',
    title: '例3 · 亏亏问题：张阿姨的玫瑰花',
    tag: 'type2',
    tagLabel: '亏亏',
    text: '张阿姨准备把一些玫瑰花放到花瓶中。如果每瓶放入 <strong>9 朵</strong>玫瑰花，还差 <strong>6 朵</strong>；如果每瓶放入 <strong>10 朵</strong>玫瑰花，还差 <strong>11 朵</strong>。请问有多少个花瓶？有多少朵玫瑰花？',
    analysis: [
      '两次放置都不够（亏亏问题）',
      '每份差额：10 − 9 = 1（朵）',
      '不足差额：11 − 6 = 5（朵）',
      '花瓶数 = 不足差额 ÷ 每份差额 = 5 ÷ 1 = 5（个）',
      '玫瑰花总数 = 5 × 9 − 6 = 39（朵）',
      '验证：5 × 10 − 11 = 50 − 11 = 39（朵）✓',
    ],
    type: 'none',
    finalQ: '一共有多少朵玫瑰花？',
    finalUnit: '朵',
    finalAns: 39,
  },
  {
    id: '39-L6',
    title: '练一练 · 亏亏问题：花花买发卡',
    tag: 'type2',
    tagLabel: '亏亏',
    text: '花花想买一定数量的发卡。如果每个发卡 <strong>8 角钱</strong>，就少了 <strong>1 元 3 角</strong>（即 13 角）；如果每个发卡 <strong>1 元钱</strong>（即 10 角），就少了 <strong>3 元 7 角</strong>（即 37 角）。那么花花一共带了多少钱（单位：角）？',
    analysis: [
      '两次都钱不够（亏亏问题），统一单位用"角"',
      '每份差额：10 − 8 = 2（角）',
      '不足差额：37 − 13 = 24（角）',
      '发卡数 = 不足差额 ÷ 每份差额 = 24 ÷ 2 = 12（个）',
      '花花带的钱 = 12 × 8 − 13 = 83（角）',
      '验证：12 × 10 − 37 = 120 − 37 = 83（角）✓',
      '即 8 元 3 角',
    ],
    type: 'none',
    finalQ: '花花一共带了多少角钱？',
    finalUnit: '角',
    finalAns: 83,
  },
  {
    id: '39-L7',
    title: '例4 · 盈亏问题：兔妈妈的萝卜',
    tag: 'type3',
    tagLabel: '盈亏',
    text: '兔妈妈要出趟远门，给小白兔留下了一筐萝卜。如果小白兔每天吃 <strong>4 个</strong>，会多出 <strong>23 个</strong>萝卜；如果每天吃 <strong>6 个</strong>，则又少 <strong>7 个</strong>萝卜。那么这筐萝卜有多少个？',
    analysis: [
      '一次有多余（盈23个），一次不够（亏7个）→ 盈亏问题',
      '每份差额：6 − 4 = 2（个）',
      '总差额：盈 + 亏 = 23 + 7 = 30（个）',
      '天数 = 总差额 ÷ 每份差额 = 30 ÷ 2 = 15（天）',
      '萝卜总数 = 15 × 4 + 23 = 83（个）',
      '验证：15 × 6 − 7 = 90 − 7 = 83（个）✓',
    ],
    type: 'none',
    finalQ: '这筐萝卜有多少个？',
    finalUnit: '个',
    finalAns: 83,
  },
  {
    id: '39-L8',
    title: '练一练 · 盈亏问题：搬砖',
    tag: 'type3',
    tagLabel: '盈亏',
    text: '五一劳动节，一个小组的同学们去参加搬砖劳动。如果每人搬 <strong>3 块砖</strong>，还会剩下 <strong>16 块砖</strong>没人搬；如果每人搬 <strong>9 块砖</strong>，则还少 <strong>2 块砖</strong>。请问这个小组有多少人？要搬的砖共有多少块？',
    analysis: [
      '一次有多余（盈16块），一次不够（亏2块）→ 盈亏问题',
      '每份差额：9 − 3 = 6（块）',
      '总差额：盈 + 亏 = 16 + 2 = 18（块）',
      '人数 = 总差额 ÷ 每份差额 = 18 ÷ 6 = 3（人）',
      '砖的总数 = 3 × 3 + 16 = 25（块）',
      '验证：3 × 9 − 2 = 27 − 2 = 25（块）✓',
    ],
    type: 'none',
    finalQ: '要搬的砖共有多少块？',
    finalUnit: '块',
    finalAns: 25,
  },
  {
    id: '39-L9',
    title: '例5 · 盈亏问题：合唱队开会',
    tag: 'type3',
    tagLabel: '盈亏',
    text: '"百灵鸟"合唱队的同学到会议室开会。若每条长椅上坐 <strong>3 人</strong>，就会有 <strong>9 位同学</strong>没地方坐；若每条长椅上坐 <strong>7 人</strong>，则会空出 <strong>1 条长椅</strong>。请问合唱队有多少人？',
    analysis: [
      '坐3人时人多（盈9人），坐7人时椅多（空1条=亏7人）→ 盈亏问题',
      '每份差额：7 − 3 = 4（人）',
      '总差额：9 + 7 = 16（人）',
      '椅子数 = 总差额 ÷ 每份差额 = 16 ÷ 4 = 4（条）',
      '合唱队人数 = 3 × 4 + 9 = 21（人）',
      '验证：4 × 7 − 7 = 28 − 7 = 21（人）；(4−1) × 7 = 21（人）✓',
    ],
    type: 'none',
    finalQ: '合唱队有多少人？',
    finalUnit: '人',
    finalAns: 21,
  },
  {
    id: '39-L10',
    title: '练一练 · 盈亏问题：朱朱的水果箱',
    tag: 'type3',
    tagLabel: '盈亏',
    text: '朱朱给班里同学买了若干箱水果，班里男生去搬水果。如果每 <strong>3 个人</strong>抬一个箱子，那么就会有 <strong>2 个箱子</strong>没人抬；如果每 <strong>2 个人</strong>抬一个箱子，那么抬完全部的箱子后，还有 <strong>7 个人</strong>没有干活。请问班里共有多少名男生？',
    analysis: [
      '每3人/箱时，2箱没人抬 → 缺少 2×3=6 人（亏6人）',
      '每2人/箱时，多出7人没活干（盈7人）',
      '每份差额：3 − 2 = 1（人/箱）',
      '总差额：6 + 7 = 13（箱）',
      '箱子数 = 13（箱）',
      '男生人数 = 13 × 2 + 7 = 33（人）',
      '验证：13 × 3 − 6 = 39 − 6 = 33（人）✓',
    ],
    type: 'none',
    finalQ: '班里共有多少名男生？',
    finalUnit: '人',
    finalAns: 33,
  },
  {
    id: '39-L11',
    title: '例6 · 变形盈亏：少先队员植树',
    tag: 'type3',
    tagLabel: '盈亏',
    text: '少先队员去植树。如果每人挖 <strong>5 个</strong>树坑，则有 <strong>2 个人</strong>没有树坑挖；如果其中两人各挖 <strong>6 个</strong>树坑，其余每人挖 <strong>3 个</strong>树坑，就恰好挖完所有的树坑。请问共有多少名少先队员？共挖了多少个树坑？',
    analysis: [
      '条件①：每人挖5个，2人没坑挖 → 多了 2×5=10 个"坑的容量"（相当于亏10坑）',
      '条件②：2人各挖6个、其余挖3个，恰好 → 相比"全员挖3个"多了 2×(6−3)=6 个坑（盈6坑）',
      '每份差额：5 − 3 = 2（坑/人）',
      '总差额：10 + 6 = 16（坑）',
      '人数 = 16 ÷ 2 = 8（人）',
      '树坑总数 = 8 × 5 − 10 = 30（个）',
      '验证：6×2 + 3×(8−2) = 12+18 = 30（个）✓',
    ],
    type: 'none',
    finalQ: '共挖了多少个树坑？',
    finalUnit: '个',
    finalAns: 30,
  },
  {
    id: '39-L12',
    title: '练一练 · 变形盈亏：韦老师安排帐篷',
    tag: 'type3',
    tagLabel: '盈亏',
    text: '韦老师带着一年级孩子们去露营。若每个帐篷住 <strong>7 人</strong>，则有 <strong>2 个帐篷</strong>没有人住；若其中两个帐篷各住 <strong>6 人</strong>，其余帐篷各住 <strong>4 人</strong>，则刚好所有学生都住下。那么共有多少个帐篷？共有多少个孩子？',
    analysis: [
      '条件①：每帐住7人，2帐没人住 → 多了 2×7=14 个"住宿容量"（亏14人）',
      '条件②：2帐各住6人、其余住4人，恰好 → 相比"全部住4人"多了 2×(6−4)=4 人（盈4人）',
      '每份差额：7 − 4 = 3（人/帐）',
      '总差额：14 + 4 = 18',
      '帐篷数 = 18 ÷ 3 = 6（个）',
      '孩子人数 = 7 × (6−2) = 28（人）',
      '验证：2×6 + (6−2)×4 = 12+16 = 28（人）✓',
    ],
    type: 'none',
    finalQ: '共有多少个孩子？',
    finalUnit: '人',
    finalAns: 28,
  },
]

export const PROBLEMS: ProblemSet = {
  pretest: [],
  lesson: LESSON,
  homework: [],
  workbook: [],
}

export const PROBLEM_TYPES = [
  {
    tag: 'type1',
    color: 'blue',
    label: '题型1 · 盈盈问题',
    desc: '两种分法都有剩余。用"剩余差÷每份差=份数"求份数，再求总量。',
    example: '例：买6支剩11元，买4支剩19元',
  },
  {
    tag: 'type2',
    color: 'red',
    label: '题型2 · 亏亏问题',
    desc: '两种分法都不够。用"不足差÷每份差=份数"求份数，再求总量。',
    example: '例：每人3个差5个，每人5个差15个',
  },
  {
    tag: 'type3',
    color: 'purple',
    label: '题型3 · 盈亏问题',
    desc: '一种分法有剩余，一种分法不足。用"(盈+亏)÷每份差=份数"。',
    example: '例：每人3个多2个，每人5个差4个',
  },
  {
    tag: 'type4',
    color: 'green',
    label: '题型4 · 盈恰问题',
    desc: '一种分法有剩余，另一种分法正好。用"盈÷每份差=份数"。',
    example: '例：放2个剩9个，放5个正好',
  },
  {
    tag: 'type5',
    color: 'amber',
    label: '题型5 · 亏恰问题',
    desc: '一种分法不足，另一种分法正好。用"亏÷每份差=份数"。',
    example: '例：做4道剩12道未完，做5道正好完',
  },
]

export const TYPE_STYLE: Record<
  string,
  { bg: string; border: string; titleColor: string; textColor: string }
> = {
  type1: { bg: 'bg-blue-50',   border: 'border-l-blue-500',   titleColor: 'text-blue-800',   textColor: 'text-blue-900' },
  type2: { bg: 'bg-red-50',    border: 'border-l-red-500',    titleColor: 'text-red-800',    textColor: 'text-red-900' },
  type3: { bg: 'bg-purple-50', border: 'border-l-purple-500', titleColor: 'text-purple-800', textColor: 'text-purple-900' },
  type4: { bg: 'bg-green-50',  border: 'border-l-green-500',  titleColor: 'text-green-800',  textColor: 'text-green-900' },
  type5: { bg: 'bg-amber-50',  border: 'border-l-amber-500',  titleColor: 'text-amber-800',  textColor: 'text-amber-900' },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-blue-100 text-blue-800',
  type2: 'bg-red-100 text-red-800',
  type3: 'bg-purple-100 text-purple-800',
  type4: 'bg-green-100 text-green-800',
  type5: 'bg-amber-100 text-amber-800',
}
