import type { Problem, ProblemSet } from '@rosie/core'
import {
  gongBudengSudoku,
  gongChangguiSudoku,
  gongChuangkouSudoku,
  gongDuijiaoxianSudoku,
  gongJuchiSudoku,
  gongShufang,
  gongShulian,
  gongShuqiao,
  gongWumaSudoku,
} from '@rosie/math/components/lesson/g1/lesson47/gong/create-gong-problem'

// 玩法规则（按题型复用）
const RULE_SHULIAN =
  '将相同的数字两两相连，连线只能<strong>横向或纵向</strong>行走，彼此不能交叉或重叠，且要走过<strong>所有</strong>格子。'
const RULE_SHUQIAO =
  '圆圈是岛，圈中数字表示该岛的桥数。用横/竖直线把岛连起来，两岛之间最多 <strong>2</strong> 座桥，桥不能交叉、不能跨岛，所有岛要连成一片。'
const RULE_SHUFANG =
  '把棋盘划分成长方形或正方形，每一片恰好含 1 个数字，数字 = 该片的<strong>面积</strong>（每小格面积为 1）。'
const RULE_BUDENG =
  '每行、每列、每宫填入不重复的数字，并满足格子之间标注的 <strong>&gt; / &lt;</strong> 大小关系。'
const RULE_WUMA =
  '把 1~6 填入空格，每行、每列、每宫都不重复；互为<strong>马步</strong>（象棋"马走日"）的两格数字也不能相同。'
const RULE_CHUANGKOU =
  '把 1~9 填入空格，每行、每列、每宫都不重复；另外四个<strong>窗口</strong>区域内的数字也不能重复。'
const RULE_CHANGGUI = '把数字填入空格，使每行、每列、每宫内的数字都<strong>不重复</strong>。'
const RULE_DUIJIAOXIAN =
  '把 1~6 填入空格，每行、每列、每宫<strong>以及两条对角线</strong>上的数字都不重复。'
const RULE_JUCHI =
  '每个宫是粗线框成的不规则<strong>锯齿形</strong>，把 1~6 填入，使每宫、每行、每列都不重复。'

const PRETEST: Problem[] = []

const LESSON: Problem[] = [
  {
    id: '1-47-L1',
    title: '例题1 · 数连',
    tag: 'type1',
    tagLabel: '数连',
    difficulty: 2,
    text: RULE_SHULIAN,
    analysis: [
      '先点一个数字格选中颜色，再点空格画出连线',
      '同色的两个数字之间只能拐直角，不能交叉或重叠',
      '所有空格都要被某条连线经过',
    ],
    ...gongShulian({
      rows: [5],
      cells: [
        [1, 1, 3],
        [1, 3, 2],
        [2, 1, 1],
        [2, 3, 2],
        [3, 5, 3],
        [4, 2, 4],
        [5, 4, 1],
        [5, 5, 4],
      ],
    }),
  },
  {
    id: '1-47-L2',
    title: '练一练 · 数连',
    tag: 'type1',
    tagLabel: '数连',
    difficulty: 2,
    text: RULE_SHULIAN,
    analysis: ['先点数字格选颜色，再点空格连线', '连线不能交叉、不能重叠', '所有格子都要走到'],
    ...gongShulian({
      rows: [5],
      cells: [
        [1, 1, 1],
        [1, 2, 2],
        [1, 3, 3],
        [2, 4, 4],
        [3, 2, 4],
        [3, 3, 2],
        [5, 3, 1],
        [5, 4, 3],
      ],
    }),
  },
  {
    id: '1-47-L3',
    title: '例题2 · 数桥',
    tag: 'type2',
    tagLabel: '数桥',
    difficulty: 3,
    text: RULE_SHUQIAO,
    analysis: [
      '圈里的数字 = 这座岛连出的桥总数',
      '两岛之间最多搭 2 座桥，桥不能斜、不能交叉、不能跨岛',
      '最后所有岛要连成一整片',
    ],
    ...gongShuqiao({
      rows: [5],
      cells: [
        [1, 1, 3],
        [1, 2, 3],
        [1, 4, 1],
        [2, 2, 4],
        [2, 5, 2],
        [3, 3, 4],
        [3, 4, 2],
        [4, 2, 1],
        [5, 1, 4],
        [5, 3, 6],
        [5, 5, 2],
      ],
    }),
  },
  {
    id: '1-47-L4',
    title: '练一练 · 数桥',
    tag: 'type2',
    tagLabel: '数桥',
    difficulty: 3,
    text: RULE_SHUQIAO,
    analysis: ['数字 = 该岛的桥数', '两岛最多 2 座桥，不交叉、不跨岛', '所有岛连成一片'],
    ...gongShuqiao({
      rows: [5],
      cells: [
        [1, 2, 3],
        [1, 5, 4],
        [2, 1, 1],
        [2, 3, 3],
        [2, 4, 2],
        [3, 2, 1],
        [4, 1, 2],
        [4, 3, 4],
        [4, 5, 4],
        [5, 3, 2],
        [5, 5, 2],
      ],
    }),
  },
  {
    id: '1-47-L5',
    title: '例题3 · 数方',
    tag: 'type3',
    tagLabel: '数方',
    difficulty: 3,
    text: RULE_SHUFANG,
    analysis: [
      '点数字格选颜色，再点空格把同一片涂成一种颜色',
      '每片必须是长方形或正方形',
      '片里的数字 = 该片的格子数（面积）',
    ],
    ...gongShufang({
      rows: [5],
      cells: [
        [1, 3, 2],
        [1, 5, 4],
        [2, 2, 3],
        [2, 3, 4],
        [3, 4, 2],
        [4, 1, 4],
        [5, 1, 2],
        [5, 5, 4],
      ],
    }),
  },
  {
    id: '1-47-L6',
    title: '练一练 · 数方',
    tag: 'type3',
    tagLabel: '数方',
    difficulty: 3,
    text: RULE_SHUFANG,
    analysis: ['每片是长方形或正方形', '数字 = 该片面积', '所有格子都要被划进某一片'],
    ...gongShufang({
      rows: [5],
      cells: [
        [1, 2, 3],
        [2, 3, 2],
        [2, 5, 2],
        [3, 1, 5],
        [3, 3, 3],
        [3, 4, 3],
        [3, 5, 3],
        [4, 2, 4],
      ],
    }),
  },
  {
    id: '1-47-L7',
    title: '例题4 · 不等号数独',
    tag: 'type4',
    tagLabel: '不等号数独',
    difficulty: 2,
    text: '在每个方格内填入 1~4，使每行、每列、每宫内数字不重复，同时满足标注的 <strong>&gt; / &lt;</strong> 大小关系。',
    analysis: [
      '先看不等号链，找最小或最大的格子下手',
      '每行、每列、每宫 1~4 各一次',
      '点开口大的一端填大数',
    ],
    ...gongBudengSudoku({
      rows: [4],
      hIneq: [
        [1, 2, '<'],
        [1, 3, '<'],
        [2, 3, '>'],
        [4, 3, '>'],
      ],
      vIneq: [
        [1, 3, '>'],
        [3, 4, '>'],
      ],
      cells: [[2, 2, 2]],
    }),
  },
  {
    id: '1-47-L8',
    title: '练一练 · 不等号数独',
    tag: 'type4',
    tagLabel: '不等号数独',
    difficulty: 2,
    text: '在每个方格内填入 1~4，使每行、每列、每宫内数字不重复，同时满足标注的 <strong>&gt; / &lt;</strong> 大小关系。',
    analysis: [RULE_BUDENG, '从不等号最长的一串开始推'],
    ...gongBudengSudoku({
      rows: [4],
      hIneq: [
        [1, 2, '<'],
        [2, 2, '<'],
        [4, 4, '>'],
      ],
      vIneq: [[4, 2, '>']],
      cells: [
        [2, 3, 3],
        [3, 3, 1],
      ],
    }),
  },
  {
    id: '1-47-L9',
    title: '例题5 · 无马数独',
    tag: 'type5',
    tagLabel: '无马数独',
    difficulty: 4,
    text: RULE_WUMA,
    analysis: [
      '每行、每列、每宫 1~6 各一次',
      '想象一个"马"放在某格，它能跳到的两格不能和它同数',
      '先填已知多的行/列',
    ],
    ...gongWumaSudoku({
      rows: [6],
      cells: [
        [1, 3, 2],
        [1, 4, 1],
        [1, 5, 4],
        [2, 1, 5],
        [3, 1, 4],
        [3, 6, 1],
        [4, 1, 1],
        [4, 6, 6],
        [5, 6, 3],
        [6, 2, 6],
        [6, 3, 5],
        [6, 4, 2],
      ],
    }),
  },
  {
    id: '1-47-L10',
    title: '练一练 · 无马数独',
    tag: 'type5',
    tagLabel: '无马数独',
    difficulty: 4,
    text: RULE_WUMA,
    analysis: [RULE_WUMA, '马步 = "日"字两端的两格'],
    ...gongWumaSudoku({
      rows: [6],
      cells: [
        [1, 3, 3],
        [1, 6, 4],
        [2, 3, 6],
        [3, 1, 5],
        [3, 2, 6],
        [4, 5, 6],
        [5, 6, 5],
        [5, 4, 2],
        [6, 1, 6],
        [6, 4, 5],
      ],
    }),
  },
  {
    id: '1-47-L11',
    title: '例题6 · 窗口数独',
    tag: 'type6',
    tagLabel: '窗口数独',
    difficulty: 5,
    text: RULE_CHUANGKOU,
    analysis: [
      '每行、每列、每宫 1~9 各一次',
      '四个高亮的窗口区域内 1~9 也各一次',
      '善用窗口与宫的重叠格快速推数',
    ],
    ...gongChuangkouSudoku({
      rows: [9],
      cells: [
        [1, 4, 8],
        [1, 5, 4],
        [1, 6, 6],
        [2, 3, 3],
        [2, 4, 7],
        [2, 6, 1],
        [2, 7, 5],
        [3, 2, 6],
        [3, 3, 4],
        [3, 7, 7],
        [3, 8, 2],
        [4, 1, 7],
        [4, 2, 2],
        [4, 8, 4],
        [4, 9, 5],
        [5, 1, 6],
        [5, 9, 1],
        [6, 1, 4],
        [6, 2, 5],
        [6, 8, 9],
        [6, 9, 6],
        [7, 2, 1],
        [7, 3, 2],
        [7, 7, 6],
        [7, 8, 8],
        [8, 3, 7],
        [8, 4, 6],
        [8, 6, 5],
        [8, 7, 4],
        [9, 4, 1],
        [9, 5, 7],
        [9, 6, 2],
      ],
      window: [
        [
          [2, 2],
          [2, 6],
          [6, 2],
          [6, 6],
        ],
        [3, 3],
      ],
    }),
  },
  {
    id: '1-47-L12',
    title: '练一练 · 窗口数独',
    tag: 'type6',
    tagLabel: '窗口数独',
    difficulty: 5,
    text: RULE_CHUANGKOU,
    analysis: [RULE_CHUANGKOU, '四个窗口区域内 1~9 不重复'],
    ...gongChuangkouSudoku({
      rows: [9],
      cells: [
        [1, 4, 3],
        [1, 5, 5],
        [1, 6, 7],
        [2, 2, 4],
        [2, 3, 7],
        [2, 7, 5],
        [2, 8, 8],
        [3, 2, 3],
        [3, 3, 6],
        [3, 7, 2],
        [3, 8, 7],
        [4, 1, 4],
        [4, 5, 7],
        [4, 9, 6],
        [5, 1, 8],
        [5, 4, 6],
        [5, 6, 5],
        [5, 9, 4],
        [6, 1, 1],
        [6, 5, 9],
        [6, 9, 8],
        [7, 2, 8],
        [7, 3, 2],
        [7, 7, 9],
        [7, 8, 4],
        [8, 2, 9],
        [8, 3, 1],
        [8, 7, 6],
        [8, 8, 3],
        [9, 4, 2],
        [9, 5, 6],
        [9, 6, 9],
      ],
      window: [
        [
          [2, 2],
          [2, 6],
          [6, 2],
          [6, 6],
        ],
        [3],
      ],
    }),
  },
]

const HOMEWORK: Problem[] = [
  {
    id: '1-47-H1',
    title: '巩固1 · 数连',
    tag: 'type1',
    tagLabel: '数连',
    difficulty: 3,
    text: RULE_SHULIAN,
    analysis: ['点数字格选颜色再连线', '不交叉、不重叠', '走过所有格子'],
    ...gongShulian({
      rows: [5],
      cells: [
        [1, 1, 3],
        [1, 2, 1],
        [1, 4, 2],
        [2, 4, 4],
        [3, 1, 4],
        [3, 2, 3],
        [4, 2, 1],
        [5, 5, 2],
      ],
    }),
  },
  {
    id: '1-47-H2',
    title: '巩固2 · 数桥',
    tag: 'type2',
    tagLabel: '数桥',
    difficulty: 3,
    text: RULE_SHUQIAO,
    analysis: ['数字 = 该岛桥数', '两岛最多 2 桥，不交叉不跨岛', '所有岛连成一片'],
    ...gongShuqiao({
      rows: [5],
      cells: [
        [1, 1, 1],
        [2, 3, 3],
        [2, 5, 1],
        [3, 1, 3],
        [3, 3, 5],
        [5, 3, 1],
      ],
    }),
  },
  {
    id: '1-47-H3',
    title: '巩固3 · 数方',
    tag: 'type3',
    tagLabel: '数方',
    difficulty: 3,
    text: RULE_SHUFANG,
    analysis: ['每片是长方形或正方形', '数字 = 该片面积', '所有格子都要划进某片'],
    ...gongShufang({
      rows: [5],
      cells: [
        [1, 2, 3],
        [2, 2, 3],
        [2, 4, 2],
        [3, 1, 2],
        [3, 3, 2],
        [3, 5, 3],
        [4, 4, 2],
        [5, 1, 2],
        [5, 2, 2],
        [5, 4, 3],
      ],
    }),
  },
  {
    id: '1-47-H4',
    title: '巩固4 · 不等号数独',
    tag: 'type4',
    tagLabel: '不等号数独',
    difficulty: 3,
    text: '在每个方格内填入 1~4，使每行、每列、每宫内数字不重复，同时满足标注的 <strong>&gt; / &lt;</strong> 大小关系。',
    analysis: [RULE_BUDENG, '从不等号链的端点突破'],
    ...gongBudengSudoku({
      rows: [4],
      hIneq: [
        [2, 2, '<'],
        [2, 4, '<'],
        [3, 4, '<'],
      ],
      vIneq: [
        [4, 2, '<'],
        [2, 4, '<'],
      ],
      cells: [
        [1, 1, 1],
        [1, 3, 3],
      ],
    }),
  },
  {
    id: '1-47-H5',
    title: '巩固5 · 无马数独',
    tag: 'type5',
    tagLabel: '无马数独',
    difficulty: 4,
    text: RULE_WUMA,
    analysis: [RULE_WUMA, '先填已知多的行列'],
    ...gongWumaSudoku({
      rows: [6],
      cells: [
        [1, 2, 3],
        [1, 6, 1],
        [2, 2, 5],
        [2, 6, 6],
        [3, 3, 2],
        [4, 4, 5],
        [5, 1, 6],
        [5, 5, 2],
        [6, 1, 3],
        [6, 5, 1],
      ],
    }),
  },
  {
    id: '1-47-H6',
    title: '巩固6 · 窗口数独',
    tag: 'type6',
    tagLabel: '窗口数独',
    difficulty: 5,
    text: RULE_CHUANGKOU,
    analysis: [RULE_CHUANGKOU, '窗口与宫的重叠格最好推'],
    ...gongChuangkouSudoku({
      rows: [9],
      cells: [
        [1, 4, 3],
        [1, 6, 8],
        [1, 8, 7],
        [2, 1, 3],
        [2, 3, 8],
        [2, 7, 2],
        [3, 2, 7],
        [3, 4, 9],
        [3, 8, 3],
        [4, 1, 8],
        [4, 5, 7],
        [4, 7, 5],
        [4, 9, 6],
        [5, 4, 8],
        [5, 6, 5],
        [6, 1, 2],
        [6, 3, 1],
        [6, 5, 6],
        [7, 2, 8],
        [7, 6, 2],
        [7, 8, 6],
        [8, 3, 9],
        [8, 7, 3],
        [8, 9, 8],
        [9, 2, 4],
        [9, 4, 5],
        [9, 6, 3],
      ],
      window: [
        [
          [2, 2],
          [2, 6],
          [6, 2],
          [6, 6],
        ],
        [3],
      ],
    }),
  },
]

const WORKBOOK: Problem[] = [
  {
    id: '1-47-W1',
    title: '闯关1 · 常规数独（四宫）',
    tag: 'type7',
    tagLabel: '常规数独',
    difficulty: 1,
    text: '将数字 1~4 填入空格，使每行、每列、每宫内的数字均不重复。',
    analysis: [RULE_CHANGGUI, '从已知数字最多的行/列入手'],
    ...gongChangguiSudoku({
      rows: [4],
      cells: [
        [1, 1, 3],
        [3, 3, 4],
        [4, 2, 2],
        [4, 3, 3],
      ],
    }),
  },
  {
    id: '1-47-W2',
    title: '闯关2 · 数连',
    tag: 'type1',
    tagLabel: '数连',
    difficulty: 3,
    text: RULE_SHULIAN,
    analysis: ['点数字格选颜色再连线', '不交叉、不重叠', '走过所有格子'],
    ...gongShulian({
      rows: [5],
      cells: [
        [1, 1, 3],
        [1, 5, 2],
        [2, 1, 1],
        [2, 3, 2],
        [2, 4, 1],
        [3, 4, 3],
        [5, 1, 4],
        [5, 5, 4],
      ],
    }),
  },
  {
    id: '1-47-W3',
    title: '闯关3 · 数桥',
    tag: 'type2',
    tagLabel: '数桥',
    difficulty: 3,
    text: RULE_SHUQIAO,
    analysis: ['数字 = 该岛桥数', '两岛最多 2 桥，不交叉不跨岛', '所有岛连成一片'],
    ...gongShuqiao({
      rows: [5],
      cells: [
        [1, 1, 1],
        [1, 3, 3],
        [1, 5, 3],
        [3, 1, 2],
        [3, 3, 4],
        [3, 5, 2],
        [5, 1, 3],
        [5, 3, 5],
        [5, 5, 1],
      ],
    }),
  },
  {
    id: '1-47-W4',
    title: '闯关4 · 数方',
    tag: 'type3',
    tagLabel: '数方',
    difficulty: 3,
    text: RULE_SHUFANG,
    analysis: ['每片是长方形或正方形', '数字 = 该片面积', '所有格子都要划进某片'],
    ...gongShufang({
      rows: [5],
      cells: [
        [1, 3, 2],
        [1, 4, 2],
        [2, 1, 4],
        [3, 4, 2],
        [3, 5, 4],
        [4, 2, 4],
        [5, 1, 3],
        [5, 2, 2],
        [5, 5, 2],
      ],
    }),
  },
  {
    id: '1-47-W5',
    title: '闯关5 · 不等式数独',
    tag: 'type4',
    tagLabel: '不等号数独',
    difficulty: 3,
    text: '每行、每列、每宫填入 1~4 且不重复，并满足版面上的 <strong>&gt; / &lt;</strong> 不等式。',
    analysis: [RULE_BUDENG, '顺着不等式方向逐格推'],
    ...gongBudengSudoku({
      rows: [4],
      vIneq: [
        [1, 2, '>'],
        [1, 3, '>'],
        [2, 3, '>'],
        [3, 4, '<'],
      ],
      cells: [
        [4, 1, 4],
        [4, 4, 1],
      ],
    }),
  },
  {
    id: '1-47-W6',
    title: '闯关6 · 不等号数独',
    tag: 'type4',
    tagLabel: '不等号数独',
    difficulty: 4,
    text: '在每个方格内填入 1~4，使每行、每列、每宫内数字不重复，同时满足全部 <strong>&gt; / &lt;</strong> 大小关系。',
    analysis: [RULE_BUDENG, '此题没有给已知数，全靠不等号推理，先找局部最大/最小'],
    ...gongBudengSudoku({
      rows: [4],
      hIneq: [
        [1, 2, '<'],
        [1, 4, '<'],
        [2, 2, '>'],
        [2, 4, '>'],
        [3, 2, '<'],
        [3, 4, '<'],
        [4, 2, '>'],
        [4, 4, '>'],
      ],
      vIneq: [
        [1, 2, '>'],
        [1, 4, '<'],
        [2, 2, '<'],
        [2, 4, '<'],
        [3, 2, '>'],
        [3, 4, '>'],
        [4, 2, '<'],
        [4, 4, '>'],
      ],
    }),
  },
  {
    id: '1-47-W7',
    title: '闯关7 · 六宫数独',
    tag: 'type7',
    tagLabel: '常规数独',
    difficulty: 3,
    text: '将数字 1~6 填入空格，使每行、每列、每宫内的数字均不重复。',
    analysis: [RULE_CHANGGUI, '每宫为 2×3 的小块'],
    ...gongChangguiSudoku({
      rows: [6],
      cells: [
        [1, 1, 3],
        [1, 3, 4],
        [1, 4, 2],
        [1, 5, 1],
        [2, 1, 1],
        [2, 4, 4],
        [3, 4, 5],
        [3, 5, 3],
        [4, 2, 3],
        [4, 3, 6],
        [4, 6, 4],
        [5, 3, 1],
        [5, 6, 2],
        [6, 2, 4],
        [6, 3, 3],
        [6, 4, 6],
      ],
    }),
  },
  {
    id: '1-47-W8',
    title: '闯关8 · 对角线数独',
    tag: 'type8',
    tagLabel: '对角线数独',
    difficulty: 3,
    text: RULE_DUIJIAOXIAN,
    analysis: [RULE_DUIJIAOXIAN, '别忘了两条对角线也要 1~6 各一次'],
    ...gongDuijiaoxianSudoku({
      rows: [6],
      cells: [
        [1, 5, 4],
        [2, 1, 2],
        [2, 3, 6],
        [3, 2, 5],
        [3, 5, 1],
        [4, 2, 6],
        [4, 5, 2],
        [5, 4, 2],
        [5, 6, 4],
        [6, 2, 2],
      ],
    }),
  },
  {
    id: '1-47-W9',
    title: '闯关9 · 对角线数独',
    tag: 'type8',
    tagLabel: '对角线数独',
    difficulty: 3,
    text: RULE_DUIJIAOXIAN,
    analysis: [RULE_DUIJIAOXIAN, '两条对角线也不能重复'],
    ...gongDuijiaoxianSudoku({
      rows: [6],
      cells: [
        [1, 2, 5],
        [2, 4, 5],
        [3, 2, 1],
        [3, 6, 2],
        [4, 1, 4],
        [4, 2, 3],
        [5, 2, 6],
        [5, 5, 2],
        [6, 3, 4],
        [6, 4, 1],
        [6, 5, 6],
      ],
    }),
  },
  {
    id: '1-47-W10',
    title: '闯关10 · 锯齿数独',
    tag: 'type9',
    tagLabel: '锯齿数独',
    difficulty: 4,
    text: RULE_JUCHI,
    analysis: [RULE_JUCHI, '粗线框出的不规则宫，每宫 1~6 各一次'],
    ...gongJuchiSudoku({
      rows: [6],
      cells: [
        [1, 1, 6],
        [1, 3, 5],
        [1, 5, 3],
        [1, 6, 4],
        [2, 2, 2],
        [2, 5, 5],
        [3, 2, 5],
        [3, 3, 1],
        [3, 6, 3],
        [4, 1, 4],
        [4, 4, 5],
        [4, 5, 1],
        [5, 2, 6],
        [5, 3, 2],
        [5, 6, 5],
        [6, 1, 5],
        [6, 3, 3],
        [6, 4, 1],
        [6, 5, 2],
      ],
      hLine: [
        [1, 3],
        [2, 4],
        [2, 5],
        [2, 6],
        [3, 2],
        [3, 3],
        [3, 4],
        [4, 5],
        [5, 5],
        [6, 3],
      ],
      vLine: [
        [3, 2],
        [5, 2],
        [1, 3],
        [3, 3],
        [4, 3],
        [6, 3],
        [2, 4],
        [4, 4],
        [1, 5],
        [2, 5],
        [3, 5],
        [4, 5],
        [5, 5],
        [6, 5],
        [3, 6],
        [4, 6],
      ],
    }),
  },
  {
    id: '1-47-W11',
    title: '闯关11 · 不等号数独（六宫）',
    tag: 'type4',
    tagLabel: '不等号数独',
    difficulty: 4,
    text: '在每个方格内填入 1~6，使每行、每列、每宫内数字不重复，同时满足标注的 <strong>&gt; / &lt;</strong> 大小关系。',
    analysis: [RULE_BUDENG, '结合已知数与不等号一起推'],
    ...gongBudengSudoku({
      rows: [6],
      hIneq: [
        [1, 4, '<'],
        [3, 3, '<'],
        [4, 5, '>'],
        [6, 4, '>'],
      ],
      vIneq: [
        [4, 2, '<'],
        [2, 4, '>'],
        [5, 4, '<'],
        [3, 6, '<'],
      ],
      cells: [
        [2, 1, 3],
        [3, 1, 5],
        [3, 6, 3],
        [4, 1, 4],
        [4, 6, 6],
        [5, 6, 2],
      ],
    }),
  },
  {
    id: '1-47-W12',
    title: '闯关12 · 九宫数独',
    tag: 'type7',
    tagLabel: '常规数独',
    difficulty: 4,
    text: '将数字 1~9 填入空格，使每行、每列、每宫内的数字均不重复。',
    analysis: [RULE_CHANGGUI, '标准九宫格数独，从候选最少的格子下手'],
    ...gongChangguiSudoku({
      rows: [9],
      cells: [
        [1, 2, 5],
        [1, 3, 2],
        [1, 4, 7],
        [1, 6, 1],
        [1, 7, 3],
        [1, 8, 4],
        [2, 1, 1],
        [2, 5, 2],
        [2, 9, 8],
        [3, 1, 9],
        [3, 9, 5],
        [4, 1, 8],
        [4, 4, 1],
        [4, 6, 7],
        [4, 9, 3],
        [5, 1, 5],
        [5, 5, 9],
        [5, 9, 1],
        [6, 2, 9],
        [6, 4, 2],
        [6, 6, 3],
        [6, 8, 7],
        [7, 1, 3],
        [7, 3, 4],
        [7, 7, 1],
        [7, 9, 2],
        [8, 4, 5],
        [8, 6, 2],
        [9, 1, 2],
        [9, 5, 3],
        [9, 9, 7],
      ],
    }),
  },
]

export const PROBLEMS: ProblemSet = {
  pretest: PRETEST,
  lesson: LESSON,
  homework: HOMEWORK,
  workbook: WORKBOOK,
}

/** 首页题型卡片：规则 + 突破口（可扩展字段） */
export type Lesson47ProblemType = {
  tag: string
  color: string
  label: string
  /** 路径/连接/划分 或 变型数独 */
  category: 'path' | 'sudoku'
  rules: readonly string[]
  breakthroughs: readonly string[]
}

const SUDOKU_GENERAL_BREAKTHROUGHS = [
  '标出每格候选数（排除行/列/宫已有值）',
  '找唯一候选数的格，直接填入（显性唯一）',
  '找某行/列/宫中某数字只能出现在一格（隐性唯一）',
  '应用变型约束进一步排除候选数',
  '若仍无法推进，对候选数最少（2 个）的格假设验证矛盾',
] as const

export const PROBLEM_TYPES: readonly Lesson47ProblemType[] = [
  {
    tag: 'type1',
    color: 'green',
    label: '题型1 · 数连',
    category: 'path',
    rules: [
      '相同数字两两相连，每对数字对应唯一路径',
      '路径只能横向或纵向走，不能交叉、重叠',
      '路径必须走遍所有格子（无空格）',
    ],
    breakthroughs: [
      '先找角落格和边缘格——位于角/边的数字出发方向受限，可直接确定路径方向',
      '找距离最近的同号数字对，路径选择余地最小',
      '若某格被三面封死，其唯一出路即为路径方向',
    ],
  },
  {
    tag: 'type2',
    color: 'blue',
    label: '题型2 · 数桥',
    category: 'path',
    rules: [
      '岛（圆圈）之间用水平/垂直直线连接',
      '数字 = 该岛所需的总桥数',
      '两岛之间最多 2 座桥，桥不可交叉/跨越其他岛',
      '所有岛必须连成一片（连通图）',
    ],
    breakthroughs: [
      '找孤岛（仅一侧有可连邻岛），该方向桥数直接确定',
      '找数字极大岛：若某岛数字 = 邻岛数 × 2，则每条都必须搭双桥',
      '利用「最大可能桥数 = 邻岛数 × 2」反推下限，当下限 = 需求值则全部确定',
      '最后验证全图连通性',
    ],
  },
  {
    tag: 'type3',
    color: 'orange',
    label: '题型3 · 数方',
    category: 'path',
    rules: [
      '将棋盘分割为若干长方形/正方形区域',
      '每个区域内恰好含一个数字，数字 = 区域面积',
      '区域不重叠，覆盖全部格子',
    ],
    breakthroughs: [
      '先处理质数面积（2、3、5、7）——质数只有 1×N 一种矩形形状，方向有限',
      '看角落数字，只能向内延伸，方向唯一',
      '面积较大的数字（如 4 = 1×4 或 2×2）结合位置可排除不合理形状',
    ],
  },
  {
    tag: 'type4',
    color: 'purple',
    label: '题型4 · 不等号数独',
    category: 'sudoku',
    rules: ['每行/列/宫数字不重复', '格子之间标注的 > / < 大小关系必须满足'],
    breakthroughs: [
      '找不等号链：A < B < C 时，A 只能填最小值，C 只能填较大值，范围大幅缩小',
      '找只有一个方向可满足不等号的格',
      '结合行/列/宫唯一性用排除法逐步确定',
    ],
  },
  {
    tag: 'type5',
    color: 'red',
    label: '题型5 · 无马数独',
    category: 'sudoku',
    rules: [
      '6×6 宫格，每行/列/宫填 1–6 不重复',
      '国际象棋马步可达的两格数字不能相同',
      '马步：横 2 纵 1 或横 1 纵 2 的 L 形跳法，每格最多 8 个马步位置',
    ],
    breakthroughs: [
      '先用常规数独候选数排除（行/列/宫）',
      '对已确定格，标记其马步范围内不得出现的相同数字',
      '候选数被马步排除后，若某格只剩一个候选数则直接确定',
      '边角格马步范围小，约束最弱，可作检验点',
    ],
  },
  {
    tag: 'type6',
    color: 'pink',
    label: '题型6 · 窗口数独',
    category: 'sudoku',
    rules: [
      '9×9 标准数独：行/列/宫各填 1–9 不重复',
      '额外 4 个「窗口区域」（3×3）内数字也不重复',
      '窗口由四角坐标与尺寸定义，例如 [[[2,2],[2,6],[6,2],[6,6]], 3]',
    ],
    breakthroughs: [
      '窗口区域与标准宫格部分重叠，形成额外交叉约束',
      '找同时属于「宫」又属于「窗口」的格子——双重约束，候选数最少',
      '利用已知格在窗口内的数字，快速排除同窗口其他格的候选数',
      '优先从重叠区切入，往往能快速打开局面',
    ],
  },
  {
    tag: 'type7',
    color: 'teal',
    label: '题型7 · 常规数独',
    category: 'sudoku',
    rules: ['四宫 / 六宫 / 九宫：每行、每列、每宫内数字均不重复'],
    breakthroughs: [...SUDOKU_GENERAL_BREAKTHROUGHS],
  },
  {
    tag: 'type8',
    color: 'cyan',
    label: '题型8 · 对角线数独',
    category: 'sudoku',
    rules: ['6×6 宫格，每行、每列、每宫填 1–6 不重复', '主对角线与副对角线上的数字也不重复'],
    breakthroughs: [
      ...SUDOKU_GENERAL_BREAKTHROUGHS.slice(0, 3),
      '对角线约束与行列宫交叉，优先填对角线上的已知格以缩小候选',
      SUDOKU_GENERAL_BREAKTHROUGHS[4],
    ],
  },
  {
    tag: 'type9',
    color: 'amber',
    label: '题型9 · 锯齿数独',
    category: 'sudoku',
    rules: ['每个宫是粗线框成的不规则锯齿形', '每宫、每行、每列填 1–6 不重复'],
    breakthroughs: [
      ...SUDOKU_GENERAL_BREAKTHROUGHS.slice(0, 3),
      '锯齿宫形状不规则，先找格子数最少的宫下手',
      SUDOKU_GENERAL_BREAKTHROUGHS[4],
    ],
  },
]

export const TYPE_STYLE: Record<
  string,
  { bg: string; border: string; titleColor: string; textColor: string }
> = {
  type1: {
    bg: 'bg-green-50',
    border: 'border-l-green-500',
    titleColor: 'text-green-800',
    textColor: 'text-green-900',
  },
  type2: {
    bg: 'bg-blue-50',
    border: 'border-l-blue-500',
    titleColor: 'text-blue-800',
    textColor: 'text-blue-900',
  },
  type3: {
    bg: 'bg-orange-50',
    border: 'border-l-orange-500',
    titleColor: 'text-orange-800',
    textColor: 'text-orange-900',
  },
  type4: {
    bg: 'bg-purple-50',
    border: 'border-l-purple-500',
    titleColor: 'text-purple-800',
    textColor: 'text-purple-900',
  },
  type5: {
    bg: 'bg-red-50',
    border: 'border-l-red-500',
    titleColor: 'text-red-800',
    textColor: 'text-red-900',
  },
  type6: {
    bg: 'bg-pink-50',
    border: 'border-l-pink-500',
    titleColor: 'text-pink-800',
    textColor: 'text-pink-900',
  },
  type7: {
    bg: 'bg-teal-50',
    border: 'border-l-teal-500',
    titleColor: 'text-teal-800',
    textColor: 'text-teal-900',
  },
  type8: {
    bg: 'bg-cyan-50',
    border: 'border-l-cyan-500',
    titleColor: 'text-cyan-800',
    textColor: 'text-cyan-900',
  },
  type9: {
    bg: 'bg-amber-50',
    border: 'border-l-amber-500',
    titleColor: 'text-amber-800',
    textColor: 'text-amber-900',
  },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-app-green-light text-app-green-dark',
  type2: 'bg-app-blue-light text-app-blue-dark',
  type3: 'bg-orange-100 text-orange-700',
  type4: 'bg-app-purple-light text-app-purple-dark',
  type5: 'bg-red-100 text-red-700',
  type6: 'bg-pink-100 text-pink-700',
  type7: 'bg-teal-100 text-teal-700',
  type8: 'bg-cyan-100 text-cyan-700',
  type9: 'bg-amber-100 text-amber-700',
}
