-- Step 1: 在 word_entries 表中添加 chinese_def 列
ALTER TABLE word_entries ADD COLUMN IF NOT EXISTS chinese_def text;

-- Step 2: 批量写入中文释义
-- 如需限定用户，在每条语句末尾的分号前加 AND user_id = 'your-uuid'

UPDATE word_entries SET chinese_def = '美好时光' WHERE word = 'a great time';
UPDATE word_entries SET chinese_def = '都几点了！' WHERE word = 'Look at the time!';
UPDATE word_entries SET chinese_def = '准时；按时' WHERE word = 'on time';
UPDATE word_entries SET chinese_def = '浪费时间' WHERE word = 'waste (one''s) time';
UPDATE word_entries SET chinese_def = '该……的时候了' WHERE word = 'time for';
UPDATE word_entries SET chinese_def = '笑；大笑' WHERE word = 'laugh';
UPDATE word_entries SET chinese_def = '享受；喜欢做……' WHERE word = 'enjoy';
UPDATE word_entries SET chinese_def = '孙子／孙女；外孙／外孙女' WHERE word = 'grandchild';
UPDATE word_entries SET chinese_def = '懒惰的' WHERE word = 'lazy';
UPDATE word_entries SET chinese_def = '独生子女' WHERE word = 'only child';
UPDATE word_entries SET chinese_def = '侄子；外甥' WHERE word = 'nephew';
UPDATE word_entries SET chinese_def = '侄女；外甥女' WHERE word = 'niece';
UPDATE word_entries SET chinese_def = '浪费；白白消耗' WHERE word = 'waste';
UPDATE word_entries SET chinese_def = '人口；（某地区的）人或动物总数' WHERE word = 'population';
UPDATE word_entries SET chinese_def = '打猎；猎捕' WHERE word = 'hunt';
UPDATE word_entries SET chinese_def = '使受伤；使疼痛' WHERE word = 'hurt';
UPDATE word_entries SET chinese_def = '保护；防护' WHERE word = 'protect';
UPDATE word_entries SET chinese_def = '危险；危险情况' WHERE word = 'danger';
UPDATE word_entries SET chinese_def = '杀死；弄死' WHERE word = 'kill';
UPDATE word_entries SET chinese_def = '照顾；照料' WHERE word = 'care for';
UPDATE word_entries SET chinese_def = '害怕……；对……感到恐惧' WHERE word = 'frightened of';
UPDATE word_entries SET chinese_def = '事实上；其实' WHERE word = 'in fact';
UPDATE word_entries SET chinese_def = '照顾；照看' WHERE word = 'look after';
UPDATE word_entries SET chinese_def = '传到；被……知道' WHERE word = 'reach';
UPDATE word_entries SET chinese_def = '牲畜；家畜' WHERE word = 'livestock';
UPDATE word_entries SET chinese_def = '吼叫声；咆哮声' WHERE word = 'roar';
UPDATE word_entries SET chinese_def = '大型猫科动物' WHERE word = 'big cat';
UPDATE word_entries SET chinese_def = '自然保育人士；环保人士' WHERE word = 'conservationist';
UPDATE word_entries SET chinese_def = '令人害怕的；吓人的' WHERE word = 'frightening';
UPDATE word_entries SET chinese_def = '新举措；倡议' WHERE word = 'initiative';
UPDATE word_entries SET chinese_def = '百万' WHERE word = 'million';
UPDATE word_entries SET chinese_def = '影响；对……产生作用' WHERE word = 'affect';
UPDATE word_entries SET chinese_def = '潜水员' WHERE word = 'diver';
UPDATE word_entries SET chinese_def = '付钱；支付' WHERE word = 'pay';
UPDATE word_entries SET chinese_def = '储蓄；存钱' WHERE word = 'save (money)';
UPDATE word_entries SET chinese_def = '很糟糕的；令人不快的' WHERE word = 'awful';
UPDATE word_entries SET chinese_def = '小心的；谨慎的' WHERE word = 'careful';
UPDATE word_entries SET chinese_def = '非常不喜欢；讨厌' WHERE word = 'hate';
UPDATE word_entries SET chinese_def = '富有的；有钱的' WHERE word = 'rich';
UPDATE word_entries SET chinese_def = '扶手椅' WHERE word = 'armchair';
UPDATE word_entries SET chinese_def = '茶几；咖啡桌' WHERE word = 'coffee table';
UPDATE word_entries SET chinese_def = '冰箱' WHERE word = 'fridge';
UPDATE word_entries SET chinese_def = '烤箱；烤炉' WHERE word = 'oven';
UPDATE word_entries SET chinese_def = '淋浴；花洒' WHERE word = 'shower';
UPDATE word_entries SET chinese_def = '洗涤槽；水槽' WHERE word = 'sink';
UPDATE word_entries SET chinese_def = '沙发' WHERE word = 'sofa';
UPDATE word_entries SET chinese_def = '马桶；厕所' WHERE word = 'toilet';
UPDATE word_entries SET chinese_def = '衣柜；大衣橱' WHERE word = 'wardrobe';
UPDATE word_entries SET chinese_def = '搬入；迁入（新居）' WHERE word = 'move in';
UPDATE word_entries SET chinese_def = '搬出；迁出（旧居）' WHERE word = 'move out';
UPDATE word_entries SET chinese_def = '家具' WHERE word = 'furniture';
UPDATE word_entries SET chinese_def = '玻璃' WHERE word = 'glass';
UPDATE word_entries SET chinese_def = '现代的；时新的' WHERE word = 'modern';
UPDATE word_entries SET chinese_def = '塑料的；由塑料制成的' WHERE word = 'plastic';
UPDATE word_entries SET chinese_def = '再次使用；重复利用' WHERE word = 'reuse';
UPDATE word_entries SET chinese_def = '垃圾；废物' WHERE word = 'rubbish';
UPDATE word_entries SET chinese_def = '地震' WHERE word = 'earthquake';
UPDATE word_entries SET chinese_def = '阳台' WHERE word = 'balcony';
UPDATE word_entries SET chinese_def = '吸尘器' WHERE word = 'vacuum cleaner';
UPDATE word_entries SET chinese_def = '书架；书柜' WHERE word = 'bookcase';
UPDATE word_entries SET chinese_def = '洗衣机' WHERE word = 'washing machine';
UPDATE word_entries SET chinese_def = '地板；地面' WHERE word = 'floor';
UPDATE word_entries SET chinese_def = '微波炉' WHERE word = 'microwave oven';
UPDATE word_entries SET chinese_def = '屋顶' WHERE word = 'roof';
UPDATE word_entries SET chinese_def = '小地毯；地毯' WHERE word = 'rug';
UPDATE word_entries SET chinese_def = '回收利用；循环再用' WHERE word = 'recycle';
UPDATE word_entries SET chinese_def = '生态的；生态学的' WHERE word = 'ecological';
UPDATE word_entries SET chinese_def = '种类；类型' WHERE word = 'type';
UPDATE word_entries SET chinese_def = '起居室；客厅' WHERE word = 'sitting room';
UPDATE word_entries SET chinese_def = '家用电器；家电' WHERE word = 'appliance';
UPDATE word_entries SET chinese_def = '扔掉；丢弃' WHERE word = 'throw away';
UPDATE word_entries SET chinese_def = '迟到的；晚的' WHERE word = 'late';
UPDATE word_entries SET chinese_def = '深的' WHERE word = 'deep';
UPDATE word_entries SET chinese_def = '有问题的；出故障的' WHERE word = 'wrong';
UPDATE word_entries SET chinese_def = '跳水；潜入水中' WHERE word = 'dive';
UPDATE word_entries SET chinese_def = '设备；装备；器材' WHERE word = 'equipment';
UPDATE word_entries SET chinese_def = '探索；探险' WHERE word = 'explore';
UPDATE word_entries SET chinese_def = '爱好；业余爱好' WHERE word = 'hobby';
UPDATE word_entries SET chinese_def = '确定的；有把握的' WHERE word = 'sure';
UPDATE word_entries SET chinese_def = '最终到达；以……告终' WHERE word = 'end up';
UPDATE word_entries SET chinese_def = '放弃' WHERE word = 'give up';
UPDATE word_entries SET chinese_def = '开始学；开始从事（某活动）' WHERE word = 'take up';
UPDATE word_entries SET chinese_def = '试用；试试看' WHERE word = 'try out';
UPDATE word_entries SET chinese_def = '打开；开启（电源、开关等）' WHERE word = 'turn on';
UPDATE word_entries SET chinese_def = '水肺潜水；带氧气瓶潜水' WHERE word = 'scuba diving';
UPDATE word_entries SET chinese_def = '把戏；花招' WHERE word = 'trick';
UPDATE word_entries SET chinese_def = '炫耀；卖弄' WHERE word = 'show off';
UPDATE word_entries SET chinese_def = '小山；丘陵' WHERE word = 'hill';
UPDATE word_entries SET chinese_def = '拉；拖' WHERE word = 'pull';
UPDATE word_entries SET chinese_def = '绳子；粗绳' WHERE word = 'rope';
UPDATE word_entries SET chinese_def = '滑动；滑行' WHERE word = 'slide';
UPDATE word_entries SET chinese_def = '感到无聊的；厌倦的' WHERE word = 'bored';
UPDATE word_entries SET chinese_def = '无聊的；枯燥的' WHERE word = 'boring';
UPDATE word_entries SET chinese_def = '兴奋的；激动的' WHERE word = 'excited';
UPDATE word_entries SET chinese_def = '令人兴奋的；刺激的' WHERE word = 'exciting';
UPDATE word_entries SET chinese_def = '感兴趣的；有兴趣的' WHERE word = 'interested';
UPDATE word_entries SET chinese_def = '有趣的；吸引人的' WHERE word = 'interesting';
UPDATE word_entries SET chinese_def = '放松的；平静的' WHERE word = 'relaxed';
UPDATE word_entries SET chinese_def = '令人放松的；使人舒适的' WHERE word = 'relaxing';
UPDATE word_entries SET chinese_def = '疲倦的；疲惫的' WHERE word = 'tired';
UPDATE word_entries SET chinese_def = '令人疲惫的；累人的' WHERE word = 'tiring';
UPDATE word_entries SET chinese_def = '用完；耗尽' WHERE word = 'use up';
UPDATE word_entries SET chinese_def = '消遣；娱乐活动' WHERE word = 'pastime';
UPDATE word_entries SET chinese_def = '博客（网站）' WHERE word = 'blog';
UPDATE word_entries SET chinese_def = '写博客；发博文' WHERE word = 'blog (verb)';
UPDATE word_entries SET chinese_def = '编写代码；编程' WHERE word = 'code';
UPDATE word_entries SET chinese_def = '发布（到网上）；上传' WHERE word = 'post';
UPDATE word_entries SET chinese_def = '链接；超链接' WHERE word = 'link';
UPDATE word_entries SET chinese_def = '评论；意见' WHERE word = 'comment';
UPDATE word_entries SET chinese_def = '等一下！稍等！' WHERE word = 'Hang on!';
UPDATE word_entries SET chinese_def = '完全不知道；毫无头绪' WHERE word = 'have got no idea';
UPDATE word_entries SET chinese_def = '真不敢相信！' WHERE word = 'I don''t believe it.';
UPDATE word_entries SET chinese_def = '吃点心；吃零食' WHERE word = 'have a snack';
UPDATE word_entries SET chinese_def = '快点！赶快！' WHERE word = 'Hurry up!';
UPDATE word_entries SET chinese_def = '恶心的；令人作呕的' WHERE word = 'disgusting';
UPDATE word_entries SET chinese_def = '美味的；好吃的' WHERE word = 'delicious';
UPDATE word_entries SET chinese_def = '吃饱的；饱的' WHERE word = 'full';
UPDATE word_entries SET chinese_def = '口渴的' WHERE word = 'thirsty';
UPDATE word_entries SET chinese_def = '总共；合计' WHERE word = 'altogether';
UPDATE word_entries SET chinese_def = '自助餐' WHERE word = 'buffet';
UPDATE word_entries SET chinese_def = '大厅；（酒店等的）门厅' WHERE word = 'lobby';
UPDATE word_entries SET chinese_def = '肉；肉类' WHERE word = 'meat';
UPDATE word_entries SET chinese_def = '健康的；有益健康的' WHERE word = 'healthy';
UPDATE word_entries SET chinese_def = '锅；深锅' WHERE word = 'pot';
UPDATE word_entries SET chinese_def = '生的；未煮熟的' WHERE word = 'raw';
UPDATE word_entries SET chinese_def = '酱；酱汁' WHERE word = 'sauce';
UPDATE word_entries SET chinese_def = '海鲜；海产食品' WHERE word = 'seafood';
UPDATE word_entries SET chinese_def = '汤；汤羹' WHERE word = 'soup';
UPDATE word_entries SET chinese_def = '加入；添加' WHERE word = 'add';
UPDATE word_entries SET chinese_def = '煮沸；烧开' WHERE word = 'boil';
UPDATE word_entries SET chinese_def = '切碎；剁' WHERE word = 'chop';
UPDATE word_entries SET chinese_def = '炸；煎；炒' WHERE word = 'fry';
UPDATE word_entries SET chinese_def = '混合；搅拌' WHERE word = 'mix';
UPDATE word_entries SET chinese_def = '切片；切成薄片' WHERE word = 'slice';
UPDATE word_entries SET chinese_def = '蘸；浸' WHERE word = 'dip';
UPDATE word_entries SET chinese_def = '一道菜；菜肴' WHERE word = 'dish';
UPDATE word_entries SET chinese_def = '辣椒' WHERE word = 'chilli pepper (AmE Chili pepper)';
UPDATE word_entries SET chinese_def = '平底锅；煎锅' WHERE word = 'pan';
UPDATE word_entries SET chinese_def = '轻轻地；温和地' WHERE word = 'gently';
UPDATE word_entries SET chinese_def = '食谱；烹饪方法' WHERE word = 'recipe';
UPDATE word_entries SET chinese_def = '把……移走；取出' WHERE word = 'remove';
UPDATE word_entries SET chinese_def = '倒；浇；淋' WHERE word = 'pour';
UPDATE word_entries SET chinese_def = '一份（食物）' WHERE word = 'serving';
UPDATE word_entries SET chinese_def = '大汤匙；汤勺' WHERE word = 'tablespoon';
UPDATE word_entries SET chinese_def = '食用；饮用' WHERE word = 'consume';
UPDATE word_entries SET chinese_def = '拒绝；驳回' WHERE word = 'reject';
UPDATE word_entries SET chinese_def = '铃；钟' WHERE word = 'bell';
UPDATE word_entries SET chinese_def = '食堂；餐厅' WHERE word = 'canteen';
UPDATE word_entries SET chinese_def = '杂志；期刊' WHERE word = 'magazine';
UPDATE word_entries SET chinese_def = '运动衫；卫衣' WHERE word = 'sweatshirt';
UPDATE word_entries SET chinese_def = '休息；课间休息' WHERE word = 'break';
UPDATE word_entries SET chinese_def = '学期' WHERE word = 'term';
UPDATE word_entries SET chinese_def = '作弊；欺骗' WHERE word = 'cheat';
UPDATE word_entries SET chinese_def = '公平的；合理的' WHERE word = 'fair';
UPDATE word_entries SET chinese_def = '校长' WHERE word = 'head teacher';
UPDATE word_entries SET chinese_def = '严格的；严厉的' WHERE word = 'strict';
UPDATE word_entries SET chinese_def = '测验；考试' WHERE word = 'test';
UPDATE word_entries SET chinese_def = '击剑（运动）' WHERE word = 'fencing';
UPDATE word_entries SET chinese_def = '考试；（正式）测验' WHERE word = 'exam';
UPDATE word_entries SET chinese_def = '自然保护区' WHERE word = 'nature reserve';
UPDATE word_entries SET chinese_def = '讨论；商量' WHERE word = 'discuss';
UPDATE word_entries SET chinese_def = '友谊；友情' WHERE word = 'friendship';
UPDATE word_entries SET chinese_def = '在野外；在自然环境中' WHERE word = 'in the wild';
UPDATE word_entries SET chinese_def = '理解；认识；了解' WHERE word = 'understanding';
UPDATE word_entries SET chinese_def = '寄宿学校' WHERE word = 'boarding school';
UPDATE word_entries SET chinese_def = '教育；教育过程' WHERE word = 'education';
UPDATE word_entries SET chinese_def = '分数；成绩' WHERE word = 'marks';
UPDATE word_entries SET chinese_def = '（老师写给家长的）成绩报告' WHERE word = 'report';
UPDATE word_entries SET chinese_def = '休息时间；假期' WHERE word = 'time off';
UPDATE word_entries SET chinese_def = '天然的；自然的' WHERE word = 'natural';
UPDATE word_entries SET chinese_def = '解决（问题）；找到答案' WHERE word = 'solve';
UPDATE word_entries SET chinese_def = '小路；小径' WHERE word = 'path';
UPDATE word_entries SET chinese_def = '想象；设想' WHERE word = 'imagine';
UPDATE word_entries SET chinese_def = '采访；访谈' WHERE word = 'interview';
UPDATE word_entries SET chinese_def = '学习项目；课题' WHERE word = 'project';
UPDATE word_entries SET chinese_def = '很棒的；出色的' WHERE word = 'brilliant';
UPDATE word_entries SET chinese_def = '感冒；着凉' WHERE word = '(catch a) cold';
UPDATE word_entries SET chinese_def = '耳痛；耳朵痛' WHERE word = 'earache';
UPDATE word_entries SET chinese_def = '咳嗽' WHERE word = 'cough';
UPDATE word_entries SET chinese_def = '头痛' WHERE word = 'headache';
UPDATE word_entries SET chinese_def = '打喷嚏' WHERE word = 'sneeze';
UPDATE word_entries SET chinese_def = '胃痛；肚子痛' WHERE word = 'stomach ache (also stomachache)';
UPDATE word_entries SET chinese_def = '（持续的）疼痛；酸痛' WHERE word = 'ache';
UPDATE word_entries SET chinese_def = '牙痛' WHERE word = 'toothache';
UPDATE word_entries SET chinese_def = '温度计；体温计' WHERE word = 'thermometer';
UPDATE word_entries SET chinese_def = '温度；体温' WHERE word = 'temperature';
UPDATE word_entries SET chinese_def = '脚踝' WHERE word = 'ankle';
UPDATE word_entries SET chinese_def = '胸部；胸腔' WHERE word = 'chest';
UPDATE word_entries SET chinese_def = '肘；肘部' WHERE word = 'elbow';
UPDATE word_entries SET chinese_def = '膝盖；膝关节' WHERE word = 'knee';
UPDATE word_entries SET chinese_def = '肩膀；肩部' WHERE word = 'shoulder';
UPDATE word_entries SET chinese_def = '胃' WHERE word = 'stomach';
UPDATE word_entries SET chinese_def = '尾巴' WHERE word = 'tail';
UPDATE word_entries SET chinese_def = '后空翻' WHERE word = 'back flip (also backflip)';
UPDATE word_entries SET chinese_def = '树桩；树墩' WHERE word = 'stump';
UPDATE word_entries SET chinese_def = '常见的；普通的' WHERE word = 'common';
UPDATE word_entries SET chinese_def = '病毒' WHERE word = 'virus';
UPDATE word_entries SET chinese_def = '喉咙；咽喉' WHERE word = 'throat';
UPDATE word_entries SET chinese_def = '流血；出血' WHERE word = 'bleed';
UPDATE word_entries SET chinese_def = '使受伤；伤害' WHERE word = 'injure';
UPDATE word_entries SET chinese_def = '肺；肺部' WHERE word = 'lungs';
UPDATE word_entries SET chinese_def = '木乃伊' WHERE word = 'mummy';
UPDATE word_entries SET chinese_def = '生病的；不舒服的' WHERE word = 'ill';
UPDATE word_entries SET chinese_def = '虚弱的；体弱的' WHERE word = 'weak';
UPDATE word_entries SET chinese_def = '皮肤' WHERE word = 'skin';
UPDATE word_entries SET chinese_def = '疼痛的；酸痛的' WHERE word = 'sore';
UPDATE word_entries SET chinese_def = '纹身' WHERE word = 'tattoo';
UPDATE word_entries SET chinese_def = '古代的；古老的' WHERE word = 'ancient';
UPDATE word_entries SET chinese_def = '谜；神秘的事物' WHERE word = 'mystery';
UPDATE word_entries SET chinese_def = '发现；（首次）发现' WHERE word = 'discovery';
UPDATE word_entries SET chinese_def = '箭头' WHERE word = 'arrowhead';
UPDATE word_entries SET chinese_def = '也许；可能' WHERE word = 'perhaps';
UPDATE word_entries SET chinese_def = '生活方式' WHERE word = 'living';
UPDATE word_entries SET chinese_def = '给……授粉；传粉' WHERE word = 'pollinate';
UPDATE word_entries SET chinese_def = '积极活跃的；爱运动的' WHERE word = 'active';
UPDATE word_entries SET chinese_def = '蜂巢；蜂房' WHERE word = 'honeycomb';
UPDATE word_entries SET chinese_def = '屏幕；荧幕' WHERE word = 'screen';
UPDATE word_entries SET chinese_def = '蜂箱；蜂巢' WHERE word = 'beehive';
UPDATE word_entries SET chinese_def = '补充了足够水分的' WHERE word = 'hydrated';
UPDATE word_entries SET chinese_def = '尤其；特别是' WHERE word = 'especially';
UPDATE word_entries SET chinese_def = '伸展（身体）；拉伸' WHERE word = 'stretch';
