#!/usr/bin/env node

import { createHash } from 'node:crypto'
import {
  curriculumHashInput,
  curriculumRegistrySources,
  type CurriculumRegistrySource,
} from '../packages/calc/src/utils/calc-curriculum-registry'

interface RegistryManifestRow {
  blockId: string
  curriculumVersion: string
  universeSize: number
  curriculumHash: string
  coverageKind: CurriculumRegistrySource['coverageKind']
}

function sha256(value: string): string {
  return createHash('sha256').update(value).digest('hex')
}

export function buildRegistryManifest(): RegistryManifestRow[] {
  return curriculumRegistrySources().map((source) => ({
    blockId: source.blockId,
    curriculumVersion: source.version,
    universeSize: source.members.length,
    curriculumHash: sha256(curriculumHashInput(source)),
    coverageKind: source.coverageKind,
  }))
}

function quoteSql(value: string): string {
  return `'${value.replaceAll("'", "''")}'`
}

export function registrySeedSql(rows: RegistryManifestRow[]): string {
  const values = rows
    .map(
      (row) =>
        `  (${quoteSql(row.blockId)}, ${quoteSql(row.curriculumVersion)}, ${row.universeSize}, ${quoteSql(row.curriculumHash)}, ${quoteSql(row.coverageKind)}, 'draft')`,
    )
    .join(',\n')
  return [
    '-- Generated by pnpm calc:progress -- registry-sql.',
    '-- Draft-only and non-destructive: activation is a separate reviewed migration.',
    'INSERT INTO public.calc_curriculum_registry (',
    '  block_id, curriculum_version, universe_size, curriculum_hash, coverage_kind, status',
    ') VALUES',
    values,
    'ON CONFLICT (block_id, curriculum_version) DO UPDATE SET',
    '  universe_size = EXCLUDED.universe_size,',
    '  curriculum_hash = EXCLUDED.curriculum_hash,',
    '  coverage_kind = EXCLUDED.coverage_kind',
    "WHERE public.calc_curriculum_registry.status = 'draft';",
  ].join('\n')
}

function usage(): void {
  console.log('pnpm calc:progress -- registry-manifest')
  console.log('pnpm calc:progress -- registry-sql')
  console.log('pnpm calc:progress -- audit-registry scripts/calc-curriculum-registry.json')
  console.log('pnpm calc:progress -- compare-legacy-mistakes --user <uuid>  # read-only')
}

function option(args: string[], name: string): string | undefined {
  const index = args.indexOf(name)
  return index >= 0 ? args[index + 1] : undefined
}

async function compareLegacyMistakes(userId: string): Promise<void> {
  const { createClient } = await import('../packages/core/node_modules/@supabase/supabase-js')
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !key) {
    throw new Error(
      '只读对比需要 NEXT_PUBLIC_SUPABASE_URL 和 SUPABASE_SERVICE_ROLE_KEY；不会执行写入',
    )
  }
  const client = createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  })
  const [{ data: mistakes, error: mistakeError }, { data: states, error: stateError }] =
    await Promise.all([
      client
        .from('calc_mistakes')
        .select('signature,resolved,consecutive_correct,last_wrong_at,session_no')
        .eq('user_id', userId),
      client
        .from('calc_problem_state')
        .select(
          'signature,needs_remediation,remediation_correct_count,last_wrong_at,last_wrong_session_no',
        )
        .eq('user_id', userId),
    ])
  if (mistakeError) throw new Error(`读取 calc_mistakes 失败：${mistakeError.message}`)
  if (stateError) {
    throw new Error(
      `读取统一 problem state 失败（可能尚未应用 additive migration）：${stateError.message}`,
    )
  }
  const stateBySignature = new Map((states ?? []).map((row) => [row.signature, row]))
  const unresolved = (mistakes ?? []).filter((row) => !row.resolved)
  const missingProjection = unresolved
    .filter((row) => !stateBySignature.get(row.signature)?.needs_remediation)
    .map((row) => row.signature)
  const orphanProjection = (states ?? [])
    .filter(
      (row) =>
        row.needs_remediation &&
        !(mistakes ?? []).some(
          (mistake) => mistake.signature === row.signature && !mistake.resolved,
        ),
    )
    .map((row) => row.signature)
  const countMismatch = unresolved
    .filter((row) => {
      const state = stateBySignature.get(row.signature)
      return state?.needs_remediation && state.remediation_correct_count !== row.consecutive_correct
    })
    .map((row) => row.signature)
  const digest = (values: string[]) =>
    values.map((value) => sha256(`${userId}:${value}`).slice(0, 12)).sort()
  console.log(
    JSON.stringify(
      {
        user: sha256(userId).slice(0, 12),
        legacyRows: mistakes?.length ?? 0,
        legacyUnresolved: unresolved.length,
        projectedRemediation: (states ?? []).filter((row) => row.needs_remediation).length,
        missingProjection: digest(missingProjection),
        orphanProjection: digest(orphanProjection),
        countMismatch: digest(countMismatch),
        consistent:
          missingProjection.length === 0 &&
          orphanProjection.length === 0 &&
          countMismatch.length === 0,
      },
      null,
      2,
    ),
  )
}

async function auditManifest(path: string): Promise<void> {
  const { readFile } = await import('node:fs/promises')
  const expected = buildRegistryManifest()
  const actual = JSON.parse(await readFile(path, 'utf8')) as unknown
  if (JSON.stringify(actual) !== JSON.stringify(expected)) {
    throw new Error(`registry manifest 与代码课程不一致：${path}`)
  }
  console.log(`registry manifest OK: ${expected.length} curricula`)
}

async function main(): Promise<void> {
  const args = process.argv.slice(2).filter((argument) => argument !== '--')
  const command = args[0]
  if (!command || command === '--help' || command === 'help') {
    usage()
    return
  }
  if (command === 'registry-manifest') {
    console.log(JSON.stringify(buildRegistryManifest(), null, 2))
    return
  }
  if (command === 'registry-sql') {
    console.log(registrySeedSql(buildRegistryManifest()))
    return
  }
  if (command === 'audit-registry') {
    const path = args[1]
    if (!path) throw new Error('audit-registry 需要 manifest 路径')
    await auditManifest(path)
    return
  }
  if (command === 'compare-legacy-mistakes') {
    const userId = option(args, '--user')
    if (!userId) throw new Error('compare-legacy-mistakes 必须显式提供 --user <uuid>')
    await compareLegacyMistakes(userId)
    return
  }
  throw new Error(`未知命令：${command}`)
}

void main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : String(error))
  process.exitCode = 1
})
