#!/usr/bin/env node

import { createHash } from 'node:crypto'
import {
  curriculumHashInput,
  curriculumRegistrySources,
  type CurriculumRegistrySource,
} from '../packages/calc/src/utils/calc-curriculum-registry'

interface RegistryManifestRow {
  blockId: string
  curriculumVersion: string
  universeSize: number
  curriculumHash: string
  coverageKind: CurriculumRegistrySource['coverageKind']
}

function sha256(value: string): string {
  return createHash('sha256').update(value).digest('hex')
}

export function buildRegistryManifest(): RegistryManifestRow[] {
  return curriculumRegistrySources().map((source) => ({
    blockId: source.blockId,
    curriculumVersion: source.version,
    universeSize: source.members.length,
    curriculumHash: sha256(curriculumHashInput(source)),
    coverageKind: source.coverageKind,
  }))
}

function quoteSql(value: string): string {
  return `'${value.replaceAll("'", "''")}'`
}

export function registrySeedSql(rows: RegistryManifestRow[]): string {
  const values = rows
    .map(
      (row) =>
        `  (${quoteSql(row.blockId)}, ${quoteSql(row.curriculumVersion)}, ${row.universeSize}, ${quoteSql(row.curriculumHash)}, ${quoteSql(row.coverageKind)}, 'draft')`,
    )
    .join(',\n')
  return [
    '-- Generated by pnpm calc:progress -- registry-sql.',
    '-- Draft-only and non-destructive: activation is a separate reviewed migration.',
    'INSERT INTO public.calc_curriculum_registry (',
    '  block_id, curriculum_version, universe_size, curriculum_hash, coverage_kind, status',
    ') VALUES',
    values,
    'ON CONFLICT (block_id, curriculum_version) DO UPDATE SET',
    '  universe_size = EXCLUDED.universe_size,',
    '  curriculum_hash = EXCLUDED.curriculum_hash,',
    '  coverage_kind = EXCLUDED.coverage_kind',
    "WHERE public.calc_curriculum_registry.status = 'draft';",
  ].join('\n')
}

function usage(): void {
  console.log('pnpm calc:progress -- registry-manifest')
  console.log('pnpm calc:progress -- registry-sql')
  console.log('pnpm calc:progress -- audit-registry scripts/calc-curriculum-registry.json')
  console.log('pnpm calc:progress -- audit --user <uuid>  # read-only')
}

async function serviceClient() {
  const { createClient } = await import('../packages/core/node_modules/@supabase/supabase-js')
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !key) {
    throw new Error('需要 NEXT_PUBLIC_SUPABASE_URL 和 SUPABASE_SERVICE_ROLE_KEY')
  }
  return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } })
}

async function auditUser(userId: string): Promise<void> {
  const client = await serviceClient()
  const [runtimeResult, progressResult, sessionResult, stateResult] =
    await Promise.all([
      client
        .from('calc_user_runtime')
        .select('state_revision,last_session_no')
        .eq('user_id', userId)
        .maybeSingle(),
      client
        .from('calc_block_progress')
        .select(
          'block_id,curriculum_version,universe_size,covered_count,within_target_count,fluent_count,mastered_count,applied_revision,health_status',
        )
        .eq('user_id', userId),
      client
        .from('calc_sessions')
        .select('id,session_no,state_revision,idempotency_key,question_log')
        .eq('user_id', userId)
        .not('idempotency_key', 'is', null)
        .order('session_no', { ascending: false })
        .limit(500),
      client
        .from('calc_problem_state')
        .select('signature,needs_remediation,applied_revision')
        .eq('user_id', userId),
    ])
  for (const result of [runtimeResult, progressResult, sessionResult, stateResult]) {
    if (result.error) throw new Error(result.error.message)
  }
  const sessions = sessionResult.data ?? []
  const duplicateKeys = new Set<string>()
  const seenKeys = new Set<string>()
  let incompleteFacts = 0
  for (const session of sessions) {
    if (session.idempotency_key) {
      if (seenKeys.has(session.idempotency_key)) duplicateKeys.add(session.idempotency_key)
      seenKeys.add(session.idempotency_key)
    }
    if (
      !Array.isArray(session.question_log) ||
      session.question_log.some(
        (entry) =>
          typeof entry !== 'object' ||
          entry === null ||
          !('signature' in entry) ||
          !('ms' in entry),
      )
    ) {
      incompleteFacts += 1
    }
  }
  console.log(
    JSON.stringify(
      {
        user: sha256(userId).slice(0, 12),
        runtime: runtimeResult.data,
        unifiedSessions: sessions.length,
        incompleteSessionFacts: incompleteFacts,
        duplicateIdempotencyKeys: duplicateKeys.size,
        progressRows: progressResult.data?.length ?? 0,
        unhealthyProgressRows: (progressResult.data ?? []).filter(
          (row) => row.health_status !== 'healthy',
        ).length,
        remediationRows: (stateResult.data ?? []).filter((row) => row.needs_remediation).length,
        rebuildSafe: incompleteFacts === 0 && duplicateKeys.size === 0,
      },
      null,
      2,
    ),
  )
}

function option(args: string[], name: string): string | undefined {
  const index = args.indexOf(name)
  return index >= 0 ? args[index + 1] : undefined
}

async function auditManifest(path: string): Promise<void> {
  const { readFile } = await import('node:fs/promises')
  const expected = buildRegistryManifest()
  const actual = JSON.parse(await readFile(path, 'utf8')) as unknown
  if (JSON.stringify(actual) !== JSON.stringify(expected)) {
    throw new Error(`registry manifest 与代码课程不一致：${path}`)
  }
  console.log(`registry manifest OK: ${expected.length} curricula`)
}

async function main(): Promise<void> {
  const args = process.argv.slice(2).filter((argument) => argument !== '--')
  const command = args[0]
  if (!command || command === '--help' || command === 'help') {
    usage()
    return
  }
  if (command === 'registry-manifest') {
    console.log(JSON.stringify(buildRegistryManifest(), null, 2))
    return
  }
  if (command === 'registry-sql') {
    console.log(registrySeedSql(buildRegistryManifest()))
    return
  }
  if (command === 'audit-registry') {
    const path = args[1]
    if (!path) throw new Error('audit-registry 需要 manifest 路径')
    await auditManifest(path)
    return
  }
  if (command === 'audit') {
    const userId = option(args, '--user')
    if (!userId) throw new Error('audit 必须显式提供 --user <uuid>；禁止默认全量扫描')
    await auditUser(userId)
    return
  }
  throw new Error(`未知命令：${command}`)
}

void main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : String(error))
  process.exitCode = 1
})
