-- =========================================================================
-- 4B Vocabulary Load for Rosie Learning Platform
-- 223 words across Units 7–12, generated 2026-06-05
--
-- HOW TO USE
--   1. Open Supabase Dashboard → SQL Editor → New query
--   2. Replace `YOUR_LOGIN_EMAIL_HERE` (line below) with your Supabase auth email
--   3. Click RUN. Should complete in a few seconds.
--   4. Verify: SELECT COUNT(*) FROM word_entries WHERE stage = '4B';
--      Expected: 223
--   5. (Optional) After success, delete this file — it is a one-time script.
--
-- BEHAVIOR
--   Wraps DELETE-of-4B and INSERT-223 in a single transaction. Safe to re-run.
--   Touches ONLY stage='4B' rows. All other stages (4A etc.) are untouched.
--   Uses DELETE+INSERT instead of UPSERT because the table currently has no
--   (unit,lesson,word,stage) unique constraint required by ON CONFLICT.
-- =========================================================================

BEGIN;

-- Clear any prior 4B rows (no-op on first run)
DELETE FROM word_entries WHERE stage = '4B';

-- Insert all 223 4B rows in one statement
WITH me AS (
  SELECT id FROM auth.users WHERE email = 'rosie@rosie.app' LIMIT 1
)
INSERT INTO word_entries
  (creator, stage, unit, lesson, word, explanation, ipa, example, chinese_def)
SELECT
  me.id, d.stage, d.unit, d.lesson, d.word, d.explanation, d.ipa, d.example, d.chinese_def
FROM me, (VALUES
  ($$4B$$, $$Unit 7$$, $$Lesson 1$$, $$national park$$, $$an area of land that is protected by the government for people to visit because of its natural beauty and historical or scientific interest$$, $$/ˈnæʃnəl pɑːk/$$, $$Last summer we visited a national park and saw three iguanas.$$, $$国家公园$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 1$$, $$iguana$$, $$a large tropical American lizard$$, $$/ɪˈɡwɑːnə/$$, $$Dad showed me a green iguana sitting on a warm rock.$$, $$鬣蜥$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 1$$, $$branch$$, $$a part of a tree that grows out from the trunk$$, $$/brɑːntʃ/$$, $$A little bird was singing on a branch of the apple tree.$$, $$树枝$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 1$$, $$jungle$$, $$an area of tropical forest where trees and plants grow very thickly$$, $$/ˈdʒʌŋɡl/$$, $$We saw colourful parrots flying high above the green jungle.$$, $$丛林；热带雨林$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 1$$, $$lay eggs$$, $$to produce and put eggs outside the body, like birds do$$, $$/leɪ eɡz/$$, $$Our hens lay eggs every morning in the little wooden box.$$, $$产卵；下蛋$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 1$$, $$sand$$, $$the very tiny, loose pieces of rock that cover beaches, deserts, etc.$$, $$/sænd/$$, $$Rosie built a tall sand castle on the sunny beach.$$, $$沙子$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 1$$, $$leaf$$, $$a flat green part of a plant, growing from a stem or branch or from the root$$, $$/liːf/$$, $$A tiny caterpillar was eating a green leaf in the garden.$$, $$叶子$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 1$$, $$volcano$$, $$a mountain with a hole in the top or side that sometimes sends out rocks, ash, lava, etc., in a sudden explosion (called an eruption)$$, $$/vɒlˈkeɪnəʊ/$$, $$The huge volcano on the island sent smoke high into the sky.$$, $$火山$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 1$$, $$nest$$, $$the place where a bird lays its eggs and takes care of its young$$, $$/nest/$$, $$Three baby birds were chirping happily in their cosy nest.$$, $$鸟巢；窝$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 1$$, $$wildlife$$, $$animals living in nature$$, $$/ˈwaɪldlaɪf/$$, $$The national park is home to lots of amazing wildlife.$$, $$野生动物$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 1$$, $$soil$$, $$the top layer of earth in which plants grow$$, $$/sɔɪl/$$, $$We dug holes in the soft soil to plant our sunflower seeds.$$, $$土壤$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 1$$, $$erupt$$, $$to send out rocks, ash, lava, etc., in a sudden explosion$$, $$/ɪˈrʌpt/$$, $$The old volcano can still erupt and send out red lava.$$, $$（火山）喷发$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 1$$, $$stone$$, $$a small piece of rock of any shape$$, $$/stəʊn/$$, $$Rosie picked up a smooth grey stone beside the river.$$, $$石头$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 1$$, $$active$$, $$likely to explode violently or produce fire and hot liquid rock$$, $$/ˈæktɪv/$$, $$The active volcano on the island sometimes shoots out hot lava.$$, $$（火山）活跃的；活火山的$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 2$$, $$humid$$, $$(of the air or climate) warm and slightly wet$$, $$/ˈhjuːmɪd/$$, $$The jungle air felt very humid and sticky in the afternoon.$$, $$潮湿的；湿润的$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 2$$, $$smell$$, $$the quality of a thing that you can sense with your nose$$, $$/smel/$$, $$I love the sweet smell of Mum's freshly baked cookies.$$, $$气味$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 2$$, $$alive$$, $$living; not dead$$, $$/əˈlaɪv/$$, $$The little fish we found in the pond was still alive.$$, $$活着的；有生命的$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 2$$, $$creature$$, $$a living thing, real or imaginary, that can move around, such as an animal$$, $$/ˈkriːtʃə/$$, $$A tiny furry creature was hiding under the garden bench.$$, $$生物；动物$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 2$$, $$curious$$, $$having a strong desire to know about something$$, $$/ˈkjʊəriəs/$$, $$Rosie is very curious about how baby chicks hatch from eggs.$$, $$好奇的$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 2$$, $$liquid$$, $$a substance that is able to flow freely$$, $$/ˈlɪkwɪd/$$, $$Hot lava is a red liquid that flows down the volcano.$$, $$液体$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 2$$, $$massive$$, $$very large, heavy and solid$$, $$/ˈmæsɪv/$$, $$We saw a massive elephant drinking water at the zoo.$$, $$巨大的；厚重的$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 2$$, $$stem$$, $$the main long and thin part of a plant that rises above the soil and supports the leaves and flowers$$, $$/stem/$$, $$The sunflower has a long green stem and bright yellow petals.$$, $$茎；干$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 2$$, $$slippery$$, $$difficult to stand on, move on, or hold because of being smooth, wet, icy, etc.$$, $$/ˈslɪpəri/$$, $$Be careful, the kitchen floor is very slippery when it's wet.$$, $$滑的；湿滑的$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 2$$, $$trap$$, $$to catch and hold something (or someone) so it cannot escape$$, $$/træp/$$, $$The clever plant can trap little flies inside its leaves.$$, $$困住；诱捕$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 2$$, $$sticky$$, $$having a substance (such as glue or honey) on it that things easily attach to: covered in a substance that things stick to$$, $$/ˈstɪki/$$, $$My fingers got really sticky after eating the honey toast.$$, $$黏的；黏糊糊的$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 2$$, $$climate$$, $$the regular pattern of weather conditions of a particular place$$, $$/ˈklaɪmət/$$, $$The jungle has a warm and wet climate all year round.$$, $$气候$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 2$$, $$variety$$, $$several different sorts of the same thing$$, $$/vəˈraɪəti/$$, $$The park has a wide variety of beautiful flowers and trees.$$, $$种类；多样$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 3$$, $$sanctuary$$, $$an area where wild birds or animals are protected and encouraged to produce young$$, $$/ˈsæŋktʃuəri/$$, $$We visited a bird sanctuary and saw many baby pandas being cared for.$$, $$（鸟类、动物的）保护区$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 3$$, $$success$$, $$the fact that you have achieved something that you want and have been trying to do or get$$, $$/səkˈses/$$, $$Rosie's first school play was a huge success with her parents.$$, $$成功$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 3$$, $$endangered$$, $$(used especially about groups of animals, plants, etc.) at risk of no longer existing$$, $$/ɪnˈdeɪndʒəd/$$, $$Giant pandas are endangered animals that need our care and love.$$, $$濒危的$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 3$$, $$cause$$, $$to make something happen, especially something bad or unpleasant; to make somebody do something$$, $$/kɔːz/$$, $$Heavy rain can cause the little river to flood the fields.$$, $$导致；引起$$),
  ($$4B$$, $$Unit 7$$, $$Lesson 3$$, $$ocean$$, $$the mass of salt water that covers most of the earth's surface$$, $$/ˈəʊʃn/$$, $$Lots of amazing creatures live deep down in the blue ocean.$$, $$海洋$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 1$$, $$cover$$, $$to place something over or in front of something in order to hide, protect or decorate it$$, $$/ˈkʌvə/$$, $$She used a blanket to cover the puppy when it was cold.$$, $$盖；遮盖；覆盖$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 1$$, $$battery$$, $$a device that is placed inside a machine (such as a clock, toy, or car) to supply it with electricity$$, $$/ˈbætəri/$$, $$Dad put a new battery into my noisy toy robot.$$, $$电池$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 1$$, $$dump$$, $$to put (something) somewhere in a quick and careless way$$, $$/dʌmp/$$, $$Don't dump your wet socks on the clean kitchen floor.$$, $$丢弃；倾倒；随意乱放$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 1$$, $$can$$, $$a metal container in which food and drink is sold$$, $$/kæn/$$, $$Mum opened a can of tomato soup for our quick lunch.$$, $$罐头；金属罐$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 1$$, $$landfill$$, $$an area where waste is buried under the ground$$, $$/ˈlændfɪl/$$, $$Too much plastic from our city ends up in the landfill.$$, $$垃圾填埋场$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 1$$, $$cardboard$$, $$a stiff and thick kind of paper that is used especially for making boxes$$, $$/ˈkɑːdbɔːd/$$, $$We built a cool spaceship from an old cardboard box.$$, $$硬纸板；卡纸$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 1$$, $$environmental$$, $$connected with the natural conditions in which people, animals and plants live; connected with the environment$$, $$/ɪnˌvaɪrənˈmentl/$$, $$Our class joined an environmental project to clean the park.$$, $$环境的；有关环境的$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 1$$, $$electronics$$, $$devices (such as televisions, radios, and computers) that operate using many small electrical parts$$, $$/ɪˌlekˈtrɒnɪks/$$, $$Please don't throw old electronics into the rubbish bin.$$, $$电子设备；电子产品$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 1$$, $$improve$$, $$to become better than before; to make something/somebody better than before$$, $$/ɪmˈpruːv/$$, $$Rosie practises every day to improve her English reading.$$, $$改善；提高；变得更好$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 1$$, $$newspaper$$, $$a set of large printed sheets of paper, or a website, containing news, articles, advertisements, etc. and published every day or every week$$, $$/ˈnjuːzpeɪpə/$$, $$Grandpa reads the newspaper at breakfast every Sunday morning.$$, $$报纸$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 1$$, $$system$$, $$a group of related parts that move or work together$$, $$/ˈsɪstəm/$$, $$Our school has a new system for sorting paper and plastic.$$, $$系统；体系$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 1$$, $$plastic bag$$, $$a light bag made of plastic$$, $$/ˈplæstɪk bæɡ/$$, $$She carried the apples home in a small plastic bag.$$, $$塑料袋$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 1$$, $$recreation$$, $$something people do to relax or have fun$$, $$/ˌrekriˈeɪʃn/$$, $$Riding bikes in the park is my favourite weekend recreation.$$, $$娱乐；消遣$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 1$$, $$rubber$$, $$A strong substance that can be stretched and does not allow liquids to pass through it, used for making tyres, boots, etc.$$, $$/ˈrʌbə/$$, $$My new rain boots are made of soft yellow rubber.$$, $$橡胶$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 1$$, $$association$$, $$an official group of people who have joined together for a particular purpose$$, $$/əˌsəʊsiˈeɪʃn/$$, $$Our parents joined an association to plant trees near the school.$$, $$协会；社团$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 1$$, $$handle$$, $$to deal with a situation, a person, an area of work or a strong emotion$$, $$/ˈhændl/$$, $$Rosie can handle her homework all by herself now.$$, $$处理；应对$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 2$$, $$petrol$$, $$a liquid made from petroleum and used especially as a fuel for engines$$, $$/ˈpetrəl/$$, $$Dad stopped the car to buy some petrol before our trip.$$, $$汽油$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 2$$, $$pollute$$, $$to make (land, water, air, etc.) dirty and not safe or suitable to use$$, $$/pəˈluːt/$$, $$Cars and factories pollute the air in many big cities.$$, $$污染$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 2$$, $$recycle$$, $$to treat things that have already been used so that they can be used again$$, $$/ˌriːˈsaɪkl/$$, $$We recycle paper and bottles in the green bin at home.$$, $$回收利用；再利用$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 2$$, $$tap water$$, $$water supplied through pipes to taps in a building$$, $$/tæp ˈwɔːtə/$$, $$I filled my bottle with cold tap water from the kitchen.$$, $$自来水$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 2$$, $$throw away$$, $$to get rid of something that you no longer want$$, $$/θrəʊ əˈweɪ/$$, $$Please don't throw away the box; we can paint it.$$, $$扔掉；丢弃$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 2$$, $$destroy$$, $$to damage something so badly that it no longer exists, works, etc.$$, $$/dɪˈstrɔɪ/$$, $$The big storm nearly destroyed our wooden treehouse last night.$$, $$摧毁；毁坏$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 2$$, $$oil$$, $$a thick liquid that is found in rock underground$$, $$/ɔɪl/$$, $$Big ships carry oil across the ocean to many countries.$$, $$石油；原油$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 2$$, $$air conditioning$$, $$a system that cools and dries the air in a building or car$$, $$/ˈeə kənˌdɪʃənɪŋ/$$, $$The air conditioning kept our classroom cool on the hot day.$$, $$空调；空调系统$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 2$$, $$fan$$, $$a machine that creates a current of air$$, $$/fæn/$$, $$Mum turned on the fan because the kitchen was too warm.$$, $$风扇$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 2$$, $$free$$, $$not costing any money$$, $$/friː/$$, $$The zoo gives kids a free balloon on their birthday.$$, $$免费的$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 2$$, $$green$$, $$trying to protect or meant to protect the natural world$$, $$/ɡriːn/$$, $$Our school is very green and saves water every day.$$, $$环保的；绿色的$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 2$$, $$product$$, $$a thing that is grown, produced or created, usually for sale$$, $$/ˈprɒdʌkt/$$, $$This shampoo is a new product made from natural plants.$$, $$产品；制品$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 2$$, $$waste$$, $$materials that are no longer needed and are thrown away$$, $$/weɪst/$$, $$Our family puts all food waste into a small brown bin.$$, $$废料；垃圾$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 2$$, $$by mistake$$, $$in a way that is not planned or organised$$, $$/baɪ mɪˈsteɪk/$$, $$I put salt in my tea by mistake this morning.$$, $$错误地；无意中$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 2$$, $$ecosystem$$, $$all the plants and living creatures in a particular area considered in relation to their physical environment$$, $$/ˈiːkəʊsɪstəm/$$, $$Frogs and fish share the same pond ecosystem in our garden.$$, $$生态系统$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 3$$, $$shade$$, $$an area that is dark and cool under or behind something, for example a tree or building, because the sun's light does not get to it$$, $$/ʃeɪd/$$, $$We had our picnic in the shade of a tall tree.$$, $$阴凉处；树荫$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 3$$, $$oxygen$$, $$A chemical element. A gas that is present in air and water and is necessary for people, animals and plants to live.$$, $$/ˈɒksɪdʒən/$$, $$Trees give us the oxygen we breathe every day.$$, $$氧气$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 3$$, $$drip$$, $$(of liquid) to fall in small drops$$, $$/drɪp/$$, $$Rain began to drip from the leaves onto my hat.$$, $$滴下；滴落$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 3$$, $$global warming$$, $$the increase in temperature of the earth's atmosphere that is caused by the increase of particular gases, especially carbon dioxide$$, $$/ˌɡləʊbl ˈwɔːmɪŋ/$$, $$Planting more trees can help slow down global warming.$$, $$全球变暖$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 3$$, $$explorer$$, $$a person who travels to places where few people have been before or places that are not well known$$, $$/ɪkˈsplɔːrə/$$, $$Rosie dreams of becoming a brave explorer in the jungle.$$, $$探险家；勘探者$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 3$$, $$tool$$, $$something (such as a hammer, saw, shovel, etc.) that you hold in your hand and use for a particular task$$, $$/tuːl/$$, $$Dad picked the right tool to fix my broken bicycle.$$, $$工具$$),
  ($$4B$$, $$Unit 8$$, $$Lesson 3$$, $$generation$$, $$a group of people born and living during the same time$$, $$/ˌdʒenəˈreɪʃn/$$, $$Our generation must care for the planet for future kids.$$, $$一代人；一代$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 1$$, $$design$$, $$to plan and make decisions about (something that is being built or created)$$, $$/dɪˈzaɪn/$$, $$The children helped design the new playground at our school.$$, $$设计；规划$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 1$$, $$cross the road$$, $$to walk from one side of the road to the other$$, $$/krɒs ðə rəʊd/$$, $$Always look both ways before you cross the road.$$, $$过马路；穿过马路$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 1$$, $$follow (the) directions$$, $$to do what someone tells you or to go the way someone shows you$$, $$/ˈfɒləʊ ðə dəˈrekʃnz/$$, $$Follow the directions on the map to find the park.$$, $$按照指示；听从指引$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 1$$, $$go past (the traffic lights)$$, $$to move beyond something — like walking or driving beyond the traffic lights$$, $$/ɡəʊ pɑːst ðə ˈtræfɪk laɪts/$$, $$Go past the traffic lights and you will see my house.$$, $$经过（红绿灯）；走过（红绿灯）$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 1$$, $$information$$, $$knowledge that you get about someone or something$$, $$/ˌɪnfəˈmeɪʃn/$$, $$Our teacher gave us information about the school trip.$$, $$信息；资料$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 1$$, $$go straight on$$, $$to keep moving in the same direction without turning$$, $$/ɡəʊ streɪt ɒn/$$, $$Go straight on until you reach the big bookshop.$$, $$一直往前走；笔直走$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 1$$, $$sight$$, $$the interesting places, especially in a town or city, that are often visited by tourists$$, $$/saɪt/$$, $$We visited many famous sights on our holiday in London.$$, $$（旅游）景点；名胜$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 1$$, $$turn left/right$$, $$to change direction and move to the left or right$$, $$/tɜːn left raɪt/$$, $$Turn left at the corner to find the playground.$$, $$向左/右转$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 1$$, $$location$$, $$a place or position$$, $$/ləʊˈkeɪʃn/$$, $$The new playground has a sunny location near our school.$$, $$位置；地点$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 1$$, $$scavenger hunt$$, $$a game in which players have to find various objects$$, $$/ˈskævɪndʒə hʌnt/$$, $$We played a fun scavenger hunt in the garden on Saturday.$$, $$寻物游戏；寻宝游戏$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 1$$, $$treasure$$, $$a collection of valuable things such as gold, silver and jewellery$$, $$/ˈtreʒə/$$, $$The pirates buried their treasure on a tiny island.$$, $$财宝；珍宝$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 1$$, $$go around the corner$$, $$to walk or move past a bend or turning in the road$$, $$/ɡəʊ əˈraʊnd ðə ˈkɔːnə/$$, $$Go around the corner and you will see the ice cream shop.$$, $$拐过街角；绕过转角$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 1$$, $$mark$$, $$to give marks to students' work$$, $$/mɑːk/$$, $$My teacher will mark our spelling test tonight at home.$$, $$批改（作业）；打分$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 2$$, $$cheap$$, $$not costing a lot of money$$, $$/tʃiːp/$$, $$The little toy car was very cheap at the shop.$$, $$便宜的；廉价的$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 2$$, $$expensive$$, $$costing a lot of money$$, $$/ɪkˈspensɪv/$$, $$That shiny new bike is too expensive for my pocket money.$$, $$昂贵的；价格高的$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 2$$, $$collection$$, $$a group of objects, often of the same sort, that have been collected$$, $$/kəˈlekʃn/$$, $$My sister has a big collection of pretty seashells.$$, $$收藏品；收集$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 2$$, $$bank$$, $$a business where people keep their money, borrow money, etc.$$, $$/bæŋk/$$, $$Dad went to the bank to get some cash today.$$, $$银行$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 2$$, $$fish$$, $$to catch or try to catch fish$$, $$/fɪʃ/$$, $$We like to fish in the little pond on weekends.$$, $$钓鱼；捕鱼$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 2$$, $$ferry$$, $$a boat or ship that carries people, vehicles and goods across a river or across a narrow part of the sea$$, $$/ˈferi/$$, $$We took a ferry across the river on our holiday.$$, $$渡船；轮渡$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 2$$, $$spend$$, $$to pay for something$$, $$/spend/$$, $$I want to spend my pocket money on a new book.$$, $$花费（钱）；支付$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 2$$, $$shopping centre (AmE shopping center)$$, $$a group of shops built together, sometimes under one roof$$, $$/ˈʃɒpɪŋ ˈsentə/$$, $$Mum took us to the shopping centre on Saturday morning.$$, $$购物中心；商场$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 2$$, $$ticket$$, $$a piece of paper that allows you to see a show, participate in an event, travel on a vehicle, etc.$$, $$/ˈtɪkɪt/$$, $$Dad bought a ticket for the puppet show this weekend.$$, $$票；入场券$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 2$$, $$skyscraper$$, $$a very tall building in a city$$, $$/ˈskaɪskreɪpə/$$, $$The shiny skyscraper in the city touches the fluffy clouds.$$, $$摩天大楼$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 2$$, $$try$$, $$to make an effort to do something$$, $$/traɪ/$$, $$I will try to finish my homework before dinner tonight.$$, $$尝试；努力$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 2$$, $$square$$, $$an open area in a town, usually with four sides, surrounded by buildings$$, $$/skweə/$$, $$Children played with balloons in the town square on Sunday.$$, $$广场$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 2$$, $$steps$$, $$the surfaces that you walk on when you go up or down stairs$$, $$/steps/$$, $$We sat on the steps in front of our house.$$, $$台阶；楼梯$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 2$$, $$outer space$$, $$the area outside the earth's atmosphere where all the other planets and stars are$$, $$/ˈaʊtə speɪs/$$, $$Astronauts travel to outer space inside very fast rockets.$$, $$外太空；太空$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 2$$, $$bagel$$, $$a hard bread roll in the shape of a ring$$, $$/ˈbeɪɡl/$$, $$I ate a warm bagel with cream cheese for breakfast.$$, $$百吉饼；贝果$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 2$$, $$chewy$$, $$needing to be chewed a lot before it can be eaten$$, $$/ˈtʃuːi/$$, $$The toffee sweets in my lunchbox are very chewy.$$, $$有嚼劲的；耐嚼的$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 3$$, $$opinion$$, $$your feelings or thoughts about somebody/something, rather than a fact$$, $$/əˈpɪnjən/$$, $$My opinion is that puppies make the very best pets.$$, $$观点；看法$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 3$$, $$origin$$, $$the beginning or cause of something$$, $$/ˈɒrɪdʒɪn/$$, $$Our teacher told us about the origin of the pizza.$$, $$起源；由来$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 3$$, $$material$$, $$a substance that things can be made from$$, $$/məˈtɪəriəl/$$, $$We used soft material to make a cosy dog bed.$$, $$材料；原料$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 3$$, $$local$$, $$belonging to or connected with the particular place or area that you are talking about or with the place where you live$$, $$/ˈləʊkl/$$, $$We buy fresh apples from the local farm every weekend.$$, $$当地的；本地的$$),
  ($$4B$$, $$Unit 9$$, $$Lesson 3$$, $$jog$$, $$to run slowly especially for exercise$$, $$/dʒɒɡ/$$, $$Dad and I jog around the park every Saturday morning.$$, $$慢跑（锻炼）$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 1$$, $$social media$$, $$websites and software programs used for social networking$$, $$/ˈsəʊʃl ˈmiːdiə/$$, $$Mum says I'm too young to use social media yet.$$, $$社交媒体$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 1$$, $$album$$, $$a book in which you keep photographs, stamps, etc.$$, $$/ˈælbəm/$$, $$Grandma showed me an old album full of family photos.$$, $$相册；集邮册$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 1$$, $$app$$, $$a piece of software that you can download to a device such as a smartphone or tablet, for example to look up information or to play a game$$, $$/æp/$$, $$Dad downloaded a new maths app for my tablet.$$, $$应用程序$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 1$$, $$print$$, $$to cause (words, images, etc.) to appear on paper or cloth by using a machine (called a printer)$$, $$/prɪnt/$$, $$My teacher asked me to print the homework on white paper.$$, $$打印；印刷$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 1$$, $$digital$$, $$of or relating to information that is stored in the form of the numbers 0 and 1$$, $$/ˈdɪdʒɪtl/$$, $$I keep all my holiday photos in a digital album.$$, $$数字的；数码的$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 1$$, $$show$$, $$to let somebody see something$$, $$/ʃəʊ/$$, $$Please show me your new puppy after school today.$$, $$给…看；展示$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 1$$, $$download$$, $$to get data from another computer, usually using the internet$$, $$/ˌdaʊnˈləʊd/$$, $$Can I download this game onto your phone, Dad?$$, $$下载$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 1$$, $$comment$$, $$something that you say or write that gives an opinion on or explains somebody/something$$, $$/ˈkɒment/$$, $$My friend left a kind comment under my drawing online.$$, $$评论；意见$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 1$$, $$internet$$, $$a system that connects computers throughout the world$$, $$/ˈɪntənet/$$, $$We use the internet to find fun science facts at home.$$, $$互联网$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 1$$, $$post$$, $$to put information or pictures on a website$$, $$/pəʊst/$$, $$Mum likes to post photos of our dog online.$$, $$发布（信息或图片到网上）$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 1$$, $$upload$$, $$to send data to another computer$$, $$/ˌʌpˈləʊd/$$, $$I'll upload my school project to the class website tonight.$$, $$上传$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 1$$, $$share$$, $$to give some of what you have to somebody else$$, $$/ʃeə(r)/$$, $$I always share my cookies with my little sister.$$, $$分享$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 1$$, $$film$$, $$special thin plastic used for making photographs or moving pictures, used in cameras$$, $$/fɪlm/$$, $$Grandpa's old camera still needs a roll of film.$$, $$胶卷；胶片$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 1$$, $$rugby$$, $$A game played by two teams of 13 or 15 players, using an oval ball which may be kicked or carried. Teams try to put the ball over the other team's line.$$, $$/ˈrʌɡbi/$$, $$My brother plays rugby with his friends every Saturday morning.$$, $$橄榄球（运动）$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 1$$, $$selfie$$, $$a photo of yourself that you take, typically with a smartphone or webcam, and usually put on social media$$, $$/ˈselfi/$$, $$We took a funny selfie with the puppy at the park.$$, $$自拍照$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 1$$, $$sticker$$, $$a small digital image that you can use to express an idea or emotion on social media or on a messaging app$$, $$/ˈstɪkə(r)/$$, $$I sent Mum a smiling cat sticker after lunch.$$, $$（聊天/社交媒体上的）表情贴纸$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 2$$, $$invent$$, $$to create or produce (something useful) for the first time$$, $$/ɪnˈvent/$$, $$One day I want to invent a robot that cleans rooms.$$, $$发明；创造$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 2$$, $$programme (AmE program)$$, $$something that people watch on television or listen to on the radio$$, $$/ˈprəʊɡræm/$$, $$My favourite programme about animals starts at seven tonight.$$, $$（电视或广播）节目$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 2$$, $$quality$$, $$how good or bad something is$$, $$/ˈkwɒləti/$$, $$The quality of this new cartoon is really wonderful.$$, $$质量；品质$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 2$$, $$record$$, $$to store (something, such as sounds, music, images, etc.) on tape or on a disk so that it can be heard or seen later$$, $$/rɪˈkɔːd/$$, $$Dad will record the football match for me to watch later.$$, $$录制；录音$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 2$$, $$technology$$, $$the use of science in industry, engineering, etc., to invent useful things or to solve problems$$, $$/tekˈnɒlədʒi/$$, $$New technology helps farmers grow tastier fruit and vegetables.$$, $$技术；科技$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 2$$, $$entertain$$, $$to interest somebody or make somebody laugh in order to please them$$, $$/ˌentəˈteɪn/$$, $$Dad tells funny stories to entertain us during long car trips.$$, $$使快乐；使有兴趣$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 2$$, $$imagine$$, $$to form a picture in your mind of what something might be like$$, $$/ɪˈmædʒɪn/$$, $$I like to imagine flying over the mountains with my dog.$$, $$想象$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 2$$, $$cartoon$$, $$an animated film or television show$$, $$/kɑːˈtuːn/$$, $$My little brother watches a cartoon about rabbits every morning.$$, $$动画片；卡通片$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 2$$, $$documentary$$, $$a film or a radio or television programme giving facts about something$$, $$/ˌdɒkjuˈmentri/$$, $$We watched a documentary about pandas in the bamboo forest.$$, $$纪录片$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 2$$, $$news$$, $$information that is reported in a newspaper, magazine, television news programme, etc.$$, $$/njuːz/$$, $$Grandpa watches the evening news while eating his dinner.$$, $$新闻$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 2$$, $$reality show$$, $$television shows that are based on real people (not actors) in real situations, presented as entertainment$$, $$/riˈæləti ʃəʊ/$$, $$Mum loves a cooking reality show with real families competing.$$, $$真人秀$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 2$$, $$series$$, $$a set of regularly presented television shows involving the same group of characters or the same subject$$, $$/ˈsɪəriːz/$$, $$My favourite series about magic ponies has a new episode tonight.$$, $$（电视）系列节目；剧集$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 2$$, $$sitcom$$, $$a regular comedy programme on television that shows the same characters in different funny situations$$, $$/ˈsɪtkɒm/$$, $$We laugh together at our favourite family sitcom every Friday night.$$, $$情景喜剧$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 2$$, $$virtual reality$$, $$images and sounds created by a computer that seem almost real to the user, who can interact with them by using sensors (= VR)$$, $$/ˌvɜːtʃuəl riˈæləti/$$, $$My cousin tried virtual reality and swam with friendly cartoon dolphins.$$, $$虚拟现实（VR）$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 3$$, $$follower$$, $$a person who chooses to regularly receive somebody's messages using a social media service$$, $$/ˈfɒləʊə(r)/$$, $$My aunt has a new follower on her cooking page today.$$, $$（社交媒体上的）关注者；粉丝$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 3$$, $$channel$$, $$a television station$$, $$/ˈtʃænl/$$, $$There is a channel that shows cartoons all day long.$$, $$（电视）频道；电视台$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 3$$, $$review$$, $$a report in the media in which someone gives their opinion of something such as a new book or movie$$, $$/rɪˈvjuː/$$, $$I read a great review of that new dinosaur film online.$$, $$评论文章；评价$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 3$$, $$review (verb)$$, $$to write a report of a book, play, film, product, etc. in which you give your opinion of it$$, $$/rɪˈvjuː/$$, $$My sister loves to review her favourite story books online.$$, $$评论；写评论$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 3$$, $$voice$$, $$the sounds that are made when people speak or sing$$, $$/vɔɪs/$$, $$My grandma has a soft, kind voice when she sings.$$, $$嗓音；声音$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 3$$, $$generous$$, $$freely giving or sharing money and other valuable things$$, $$/ˈdʒenərəs/$$, $$My generous uncle always brings sweets for all the children.$$, $$慷慨的；大方的$$),
  ($$4B$$, $$Unit 10$$, $$Lesson 3$$, $$neighbourhood (AmE neighborhood)$$, $$a district or an area of a town$$, $$/ˈneɪbəhʊd/$$, $$Lots of friendly cats live in our quiet neighbourhood.$$, $$街区；社区$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 1$$, $$destination$$, $$a place to which a person is going or something is being sent$$, $$/ˌdestɪˈneɪʃn/$$, $$Our holiday destination this summer is a sunny beach in Spain.$$, $$目的地$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 1$$, $$bus stop$$, $$a place at the side of a road that is marked with a sign, where buses stop$$, $$/bʌs stɒp/$$, $$Mum waits with me at the bus stop every school morning.$$, $$公共汽车站$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 1$$, $$get on$$, $$to enter a vehicle (bus, train, plane, etc.)$$, $$/ɡet ɒn/$$, $$We get on the school bus right after breakfast each day.$$, $$上车$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 1$$, $$driver$$, $$a person who drives a vehicle$$, $$/ˈdraɪvə(r)/$$, $$Our bus driver smiled and waved at every child this morning.$$, $$司机$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 1$$, $$get off$$, $$to leave a vehicle (bus, train, plane, etc.)$$, $$/ɡet ɒf/$$, $$We get off the train at the next stop near grandma's house.$$, $$下车$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 1$$, $$bike lane$$, $$a part of a road that only bicycles are allowed to use$$, $$/baɪk leɪn/$$, $$Dad and I rode safely along the new bike lane on Sunday.$$, $$自行车道$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 1$$, $$parking$$, $$a space or an area for leaving vehicles$$, $$/ˈpɑːkɪŋ/$$, $$The parking near the playground was full on Saturday afternoon.$$, $$停车场；停车位$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 1$$, $$tram$$, $$a vehicle that travels on streets on metal tracks and that is used for carrying passengers$$, $$/træm/$$, $$We took a bright yellow tram to the museum in the city.$$, $$有轨电车$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 1$$, $$pedestrian$$, $$a person walking in the street and not travelling in a vehicle$$, $$/pəˈdestriən/$$, $$A kind pedestrian helped my little brother cross the busy road.$$, $$行人$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 1$$, $$motorbike$$, $$a road vehicle with two wheels, driven by an engine, with one seat for the driver and often a seat for a passenger behind the driver$$, $$/ˈməʊtəbaɪk/$$, $$My uncle rides his shiny red motorbike to work every day.$$, $$摩托车$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 1$$, $$traffic$$, $$the vehicles that are on a road at a particular time$$, $$/ˈtræfɪk/$$, $$The traffic was very heavy on our way home from school.$$, $$交通；车流$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 1$$, $$scooter$$, $$a light motorbike, usually with small wheels and a curved cover at the front to protect the rider's legs$$, $$/ˈskuːtə(r)/$$, $$My cousin rides a little blue scooter to the corner shop.$$, $$小型摩托车$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 1$$, $$resident$$, $$a person who lives in a particular place or who has their home there$$, $$/ˈrezɪdənt/$$, $$Every resident on our street came to the weekend garden party.$$, $$居民$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 1$$, $$transport (AmE transportation)$$, $$a system for carrying people or goods from one place to another using vehicles, roads, etc.$$, $$/ˈtrænspɔːt/$$, $$Buses and trains are the main transport in our small town.$$, $$交通运输$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 1$$, $$planner$$, $$a person whose job is to plan the growth and development of a town$$, $$/ˈplænə(r)/$$, $$The town planner showed us a map of the new playground.$$, $$城市规划师$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 2$$, $$passenger$$, $$a person who is travelling in a car, bus, train, plane or ship and who is not driving it or working on it$$, $$/ˈpæsɪndʒə(r)/$$, $$Every passenger on the bus smiled at the cute little puppy.$$, $$乘客$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 2$$, $$track$$, $$rails (= metal bars) that a train moves along$$, $$/træk/$$, $$We watched the long train rumble loudly along the shiny track.$$, $$铁轨$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 2$$, $$billion$$, $$1,000,000,000; one thousand million$$, $$/ˈbɪljən/$$, $$More than a billion people around the world love football.$$, $$十亿$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 2$$, $$display$$, $$to put something in a place where people can see it easily$$, $$/dɪˈspleɪ/$$, $$Our teacher will display our paintings on the classroom wall today.$$, $$展示；陈列$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 2$$, $$inspector$$, $$a person whose job is to check tickets on a bus or train$$, $$/ɪnˈspektə(r)/$$, $$The friendly inspector checked our tickets on the train to London.$$, $$检票员$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 2$$, $$escalator$$, $$moving stairs that carry people between different floors of a large building$$, $$/ˈeskəleɪtə(r)/$$, $$We rode the long escalator up to the toy shop floor.$$, $$自动扶梯$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 2$$, $$lift$$, $$a machine that carries people or goods up and down to different levels in a building or a mine$$, $$/lɪft/$$, $$We took the lift up to the tenth floor of the hotel.$$, $$电梯$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 2$$, $$gallery$$, $$a room or building for showing works of art, especially to the public$$, $$/ˈɡæləri/$$, $$Our class visited a bright art gallery on Friday afternoon.$$, $$美术馆；画廊$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 2$$, $$loudspeaker$$, $$a device that is used to make sound (such as music or a person's voice) louder and to send it out so that many people can hear it in a public space$$, $$/ˌlaʊdˈspiːkə(r)/$$, $$The loudspeaker at the station told us our train was late.$$, $$扩音器；喇叭$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 2$$, $$ticket machine$$, $$an automatic device that sells tickets for public transportation (trains, buses, etc.), parking, or events without needing a human cashier$$, $$/ˈtɪkɪt məˌʃiːn/$$, $$Dad bought our train tickets from the shiny ticket machine quickly.$$, $$售票机$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 2$$, $$timetable$$, $$a chart showing the times at which trains, buses and planes leave and arrive$$, $$/ˈtaɪmteɪbl/$$, $$We checked the timetable to find the next train to grandma's.$$, $$时刻表$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 2$$, $$the planet$$, $$the planet Earth$$, $$/ðə ˈplænɪt/$$, $$We must take care of the planet by recycling our rubbish.$$, $$地球$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 2$$, $$chandelier$$, $$a large, decorated light that hangs from a ceiling and has branches for holding many light bulbs or candles$$, $$/ˌʃændəˈlɪə(r)/$$, $$A huge sparkling chandelier hung above the dining table at grandma's.$$, $$枝形吊灯$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 2$$, $$mosaic$$, $$a picture or pattern made by placing together small pieces of glass, stone, etc. of different colours$$, $$/məʊˈzeɪɪk/$$, $$We made a beautiful mosaic of a fish in art class today.$$, $$马赛克；镶嵌画$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 2$$, $$sculpture$$, $$a work of art that is a solid figure or object made by carving or shaping wood, stone, clay, metal, etc.$$, $$/ˈskʌlptʃə(r)/$$, $$A tall stone sculpture of a lion stood near the museum door.$$, $$雕塑$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 3$$, $$pass$$, $$a card or ticket which shows that you are allowed to enter or leave a particular place or to ride a vehicle$$, $$/pɑːs/$$, $$I showed my bus pass to the driver before sitting down.$$, $$通行证；乘车卡$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 3$$, $$gondola$$, $$a long boat with a flat bottom and high parts at each end, used on canals in Venice$$, $$/ˈɡɒndələ/$$, $$We rode a black gondola along a quiet canal in Venice.$$, $$贡多拉（威尼斯小船）$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 3$$, $$romantic$$, $$making someone think of love$$, $$/rəʊˈmæntɪk/$$, $$Mum says a sunset boat ride is very romantic and sweet.$$, $$浪漫的$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 3$$, $$cable car$$, $$a vehicle that hangs from and is pulled by a moving cable and that carries passengers up and down a mountain$$, $$/ˈkeɪbl kɑː(r)/$$, $$We rode a swinging cable car up the snowy mountain yesterday.$$, $$缆车$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 3$$, $$means$$, $$a way of achieving or doing something$$, $$/miːnz/$$, $$Riding bikes is a fun means of getting to school quickly.$$, $$方法；方式$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 3$$, $$aquarium$$, $$a building where people can go to see fish and other water creatures$$, $$/əˈkweəriəm/$$, $$We saw a giant turtle at the aquarium on Saturday morning.$$, $$水族馆$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 3$$, $$entire$$, $$including everything, everyone or every part$$, $$/ɪnˈtaɪə(r)/$$, $$My entire family went to the park for a big picnic.$$, $$整个的；全部的$$),
  ($$4B$$, $$Unit 11$$, $$Lesson 3$$, $$distance$$, $$the amount of space between two places or things$$, $$/ˈdɪstəns/$$, $$The distance from our house to school is about one kilometre.$$, $$距离$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 1$$, $$check$$, $$to look at (something) carefully to find mistakes, problems, etc., or to make sure there is nothing wrong with it$$, $$/tʃek/$$, $$Please check your homework before you put it in your bag.$$, $$检查；查看$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 1$$, $$artist$$, $$a person who creates art$$, $$/ˈɑːtɪst/$$, $$My sister wants to be an artist when she grows up.$$, $$艺术家$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 1$$, $$patient$$, $$able to wait for a long time or accept annoying behaviour or difficulties without becoming angry$$, $$/ˈpeɪʃnt/$$, $$Be patient and wait for your turn on the slide.$$, $$有耐心的$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 1$$, $$chef$$, $$a professional cook who usually is in charge of a kitchen in a restaurant$$, $$/ʃef/$$, $$The chef made us a delicious pizza for dinner.$$, $$厨师；大厨$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 1$$, $$customer$$, $$a person who buys goods or services from a shop or business$$, $$/ˈkʌstəmə(r)/$$, $$The shop owner smiled kindly at every customer who came in.$$, $$顾客$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 1$$, $$detective$$, $$a person, especially a police officer, whose job is to investigate crimes and catch criminals$$, $$/dɪˈtektɪv/$$, $$The detective found important clues at the playground.$$, $$侦探$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 1$$, $$queue$$, $$a line of people, cars, etc. waiting for something or to do something$$, $$/kjuː/$$, $$We stood in a long queue to buy ice cream.$$, $$队伍；排队的人$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 1$$, $$mechanic$$, $$a person whose job is repairing machines, especially the engines of vehicles$$, $$/məˈkænɪk/$$, $$The mechanic fixed our car after it broke down on holiday.$$, $$机械师；修理工$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 1$$, $$opinion$$, $$your feelings or thoughts about somebody/something, rather than a fact$$, $$/əˈpɪnjən/$$, $$In my opinion, chocolate ice cream is the best flavour.$$, $$观点；看法$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 1$$, $$reporter$$, $$a person who collects and reports news for newspapers, radio or television$$, $$/rɪˈpɔːtə(r)/$$, $$The reporter asked the children about their school sports day.$$, $$记者$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 1$$, $$skill$$, $$a particular ability or type of ability$$, $$/skɪl/$$, $$Riding a bike is a useful skill to learn.$$, $$技能；技巧$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 1$$, $$sailor$$, $$a person who works on a ship as a member of the crew$$, $$/ˈseɪlə(r)/$$, $$The brave sailor waved to us from the big ship.$$, $$水手；船员$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 1$$, $$tax$$, $$money that you have to pay to the government so that it can pay for public services$$, $$/tæks/$$, $$Dad said we pay tax to help build new schools and roads.$$, $$税；税款$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 1$$, $$desire$$, $$a strong wish to have or do something$$, $$/dɪˈzaɪə(r)/$$, $$She had a strong desire to visit the zoo on Saturday.$$, $$渴望；愿望$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 1$$, $$sense$$, $$one of the five powers (sight, hearing, smell, taste and touch) that your body uses to get information about the world around you$$, $$/sens/$$, $$Dogs have a much better sense of smell than people.$$, $$感官；知觉$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 1$$, $$taste$$, $$the sense you have that allows you to recognize different foods and drinks when you put them in your mouth$$, $$/teɪst/$$, $$My sense of taste is weaker when I have a cold.$$, $$味觉$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 1$$, $$taste (verb)$$, $$to test the taste of something by eating or drinking a small amount of it$$, $$/teɪst/$$, $$Please taste the soup and tell me if it needs more salt.$$, $$品尝；尝味道$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$designer$$, $$a person who plans how something new will look and be made$$, $$/dɪˈzaɪnə(r)/$$, $$The designer drew a pretty dress for the school play.$$, $$设计师$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$day off$$, $$a day on which you do not have to work$$, $$/deɪ ɒf/$$, $$Mum took a day off so we could go to the park.$$, $$休息日$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$focus on$$, $$to give attention, effort, or energy to one specific task, goal, or activity$$, $$/ˈfəʊkəs ɒn/$$, $$Try to focus on your reading and ignore the noise outside.$$, $$专注于；集中于$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$full-time$$, $$done during the full number of hours considered normal or standard$$, $$/ˌfʊl ˈtaɪm/$$, $$My dad has a full-time job at the hospital.$$, $$全职的$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$part-time$$, $$working or involving fewer hours than is considered normal or standard$$, $$/ˌpɑːt ˈtaɪm/$$, $$My aunt has a part-time job at the small bakery.$$, $$兼职的$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$job$$, $$the work that a person does regularly in order to earn money$$, $$/dʒɒb/$$, $$My mum has a job at a busy children's hospital.$$, $$工作；职业$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$author$$, $$a person who writes books or the person who wrote a particular book$$, $$/ˈɔːθə(r)/$$, $$The author of my favourite story book visited our school.$$, $$作家；作者$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$career$$, $$the job or series of jobs that you do during your working life, especially if you continue to get better jobs and earn more money$$, $$/kəˈrɪə(r)/$$, $$She wants a career as a doctor when she grows up.$$, $$职业；事业$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$employee$$, $$a person who is paid to work for somebody$$, $$/ɪmˈplɔɪiː/$$, $$Every employee at the toy shop wore a bright red shirt.$$, $$雇员；员工$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$experience$$, $$the knowledge and skill that you have gained through doing something for a period of time$$, $$/ɪkˈspɪəriəns/$$, $$Grandma has lots of experience baking yummy birthday cakes.$$, $$经验；经历$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$manager$$, $$a person who is in charge of running a business, a shop or a similar organisation or part of one$$, $$/ˈmænɪdʒə(r)/$$, $$The manager of the bookshop helped us find a fun story.$$, $$经理；管理者$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$staff$$, $$a group of people who work for an organisation or business$$, $$/stɑːf/$$, $$The staff at our school are kind and very helpful.$$, $$全体员工$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$organisation (AmE organization)$$, $$a group of people who form a business, club, etc. together in order to achieve a particular aim$$, $$/ˌɔːɡənaɪˈzeɪʃn/$$, $$We joined an organisation that helps look after stray puppies.$$, $$组织；机构$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$the Arctic$$, $$the regions of the world around the North Pole$$, $$/ðə ˈɑːktɪk/$$, $$Polar bears and seals live in the Arctic all year round.$$, $$北极地区$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$surface$$, $$the outside or top layer of something$$, $$/ˈsɜːfɪs/$$, $$Tiny ants crawled across the surface of the picnic table.$$, $$表面$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$rover$$, $$a spacecraft designed to move on a planet or moon$$, $$/ˈrəʊvə(r)/$$, $$The rover sent back amazing photos from the surface of Mars.$$, $$漫游车；探测车$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$greenhouse$$, $$a building with glass sides and a glass roof for growing plants in$$, $$/ˈɡriːnhaʊs/$$, $$Grandpa grows juicy tomatoes inside his little greenhouse.$$, $$温室；暖房$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$shelter$$, $$a structure built to give protection, especially from the weather or from attack$$, $$/ˈʃeltə(r)/$$, $$We built a shelter from branches to hide from the rain.$$, $$避难所；遮蔽处$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$planetary$$, $$relating to a planet or planets$$, $$/ˈplænətri/$$, $$The museum had a cool planetary display about Jupiter and Mars.$$, $$行星的$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$toxic$$, $$containing poison$$, $$/ˈtɒksɪk/$$, $$Never touch toxic plants or berries you find in the woods.$$, $$有毒的$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 2$$, $$dust$$, $$a fine powder that consists of very small pieces of sand, earth, etc.$$, $$/dʌst/$$, $$There was a thick layer of dust on the old toy box.$$, $$灰尘；尘土$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 3$$, $$submarine$$, $$a ship that can travel underwater$$, $$/ˌsʌbməˈriːn/$$, $$The yellow submarine dived deep to see colourful fish.$$, $$潜水艇$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 3$$, $$attract$$, $$to cause (someone or something) to go to or move to or towards a place$$, $$/əˈtrækt/$$, $$Sweet flowers attract bees and butterflies to our garden.$$, $$吸引$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 3$$, $$brave$$, $$willing to do things that are difficult or dangerous; not afraid$$, $$/breɪv/$$, $$My little brother was very brave at the dentist today.$$, $$勇敢的$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 3$$, $$professional$$, $$doing something as a paid job rather than as a hobby$$, $$/prəˈfeʃənl/$$, $$My cousin is a professional football player on a big team.$$, $$专业的；职业的$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 3$$, $$worry$$, $$something that worries you$$, $$/ˈwʌri/$$, $$My biggest worry is forgetting my lines in the school play.$$, $$烦恼；担忧的事$$),
  ($$4B$$, $$Unit 12$$, $$Lesson 3$$, $$seriously$$, $$in a serious way$$, $$/ˈsɪəriəsli/$$, $$The coach spoke seriously about playing safely on the field.$$, $$严肃地；认真地$$)
) AS d(stage, unit, lesson, word, explanation, ipa, example, chinese_def);

COMMIT;
