-- Exact replay log for adaptive English practice rounds.
-- One immutable session row plus one transition row per touched word.

CREATE TABLE public.adaptive_practice_sessions (
  id UUID PRIMARY KEY,
  plan_id UUID NOT NULL REFERENCES public.adaptive_word_plans (id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  practice_date DATE NOT NULL,
  mode VARCHAR(20) NOT NULL CHECK (mode IN ('normal', 'boss')),
  started_at TIMESTAMPTZ NOT NULL,
  finished_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  new_word_count INT NOT NULL DEFAULT 0 CHECK (new_word_count >= 0),
  review_word_count INT NOT NULL DEFAULT 0 CHECK (review_word_count >= 0),
  question_count INT NOT NULL CHECK (question_count >= 0),
  correct_count INT NOT NULL CHECK (correct_count BETWEEN 0 AND question_count),
  stars_earned INT NOT NULL DEFAULT 0 CHECK (stars_earned >= 0),
  boss_passed BOOLEAN,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT adaptive_practice_sessions_time_chk CHECK (finished_at >= started_at)
);

CREATE INDEX idx_adaptive_practice_sessions_plan_date
  ON public.adaptive_practice_sessions (plan_id, practice_date, started_at);
CREATE INDEX idx_adaptive_practice_sessions_user_date
  ON public.adaptive_practice_sessions (user_id, practice_date DESC);

ALTER TABLE public.adaptive_practice_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY adaptive_practice_sessions_select
  ON public.adaptive_practice_sessions FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);
CREATE POLICY adaptive_practice_sessions_insert
  ON public.adaptive_practice_sessions FOR INSERT TO authenticated
  WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY adaptive_practice_sessions_update
  ON public.adaptive_practice_sessions FOR UPDATE TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE TABLE public.adaptive_practice_word_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id UUID NOT NULL REFERENCES public.adaptive_practice_sessions (id) ON DELETE CASCADE,
  plan_id UUID NOT NULL REFERENCES public.adaptive_word_plans (id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  word_key VARCHAR(255) NOT NULL,
  outcomes JSONB NOT NULL DEFAULT '[]'::jsonb,
  question_count INT NOT NULL CHECK (question_count > 0),
  correct_count INT NOT NULL CHECK (correct_count BETWEEN 0 AND question_count),
  box_before INT CHECK (box_before IS NULL OR box_before BETWEEN 1 AND 5),
  box_after INT CHECK (box_after IS NULL OR box_after BETWEEN 1 AND 5),
  status_before VARCHAR(50) NOT NULL,
  status_after VARCHAR(50) NOT NULL,
  next_review_before DATE,
  next_review_after DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT adaptive_practice_word_logs_session_word_key UNIQUE (session_id, word_key),
  CONSTRAINT adaptive_practice_word_logs_status_before_chk
    CHECK (status_before IN ('NOT_STARTED', 'LEARNING_PENDING', 'LEARNING', 'MASTERED')),
  CONSTRAINT adaptive_practice_word_logs_status_after_chk
    CHECK (status_after IN ('NOT_STARTED', 'LEARNING_PENDING', 'LEARNING', 'MASTERED')),
  CONSTRAINT adaptive_practice_word_logs_outcomes_array_chk CHECK (jsonb_typeof(outcomes) = 'array')
);

CREATE INDEX idx_adaptive_practice_word_logs_plan_session
  ON public.adaptive_practice_word_logs (plan_id, session_id);
CREATE INDEX idx_adaptive_practice_word_logs_user_word
  ON public.adaptive_practice_word_logs (user_id, word_key);

ALTER TABLE public.adaptive_practice_word_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY adaptive_practice_word_logs_select
  ON public.adaptive_practice_word_logs FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);
CREATE POLICY adaptive_practice_word_logs_insert
  ON public.adaptive_practice_word_logs FOR INSERT TO authenticated
  WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY adaptive_practice_word_logs_update
  ON public.adaptive_practice_word_logs FOR UPDATE TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

-- New projects may not expose SQL-created tables through the Data API unless
-- privileges are granted explicitly (Supabase breaking change, April 2026).
GRANT SELECT, INSERT, UPDATE ON public.adaptive_practice_sessions TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.adaptive_practice_word_logs TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.adaptive_practice_word_logs_id_seq TO authenticated;
