import type { Problem, ProblemSet } from './type'

const PRETEST: Problem[] = [
  {
    id: '13-P1',
    title: '课前测1 · 两侧种树总棵数',
    tag: 'type1',
    tagLabel: '直线型两端都种', difficulty: 2,
    text: '在一条长 <strong>200 米</strong>的公路两边栽树，每隔 <strong>5 米</strong>栽一棵，两端都要栽树，一共要栽多少棵？（先求一边的棵数，再算两边的棵数）',
    analysis: [
      '一边棵数 = 路长 ÷ 间距 + 1 = 200 ÷ 5 + 1 = 41 棵',
      '两边总棵数 = 41 × 2 = <strong>82 棵</strong>',
    ],
    type: 'none',
    finalQ: '一共要栽多少棵？',
    finalUnit: '棵',
    finalAns: 82,
  },
  {
    id: '13-P2',
    title: '课前测2 · 行程与速度求石凳编号',
    tag: 'type5',
    tagLabel: '行程与速度', difficulty: 3,
    text: '张奶奶在公园亭廊间散步，从第 <strong>1 个</strong>石凳处走到第 <strong>10 个</strong>石凳处共用了 <strong>36 分钟</strong>，张奶奶走了 <strong>80 分钟</strong>，请问张奶奶可以走到第几个石凳处？',
    analysis: [
      '第1到第10石凳 = 9 个间距，用时 36 分钟',
      '每个间距用时 = 36 ÷ 9 = 4 分钟',
      '80 分钟走了 80 ÷ 4 = 20 个间距',
      '走到第 1 + 20 = <strong>第 21 个石凳</strong>',
    ],
    type: 'none',
    finalQ: '走了80分钟，张奶奶可以走到第几个石凳？',
    finalUnit: '',
    finalAns: 21,
  },
  {
    id: '13-P3',
    title: '课前测3 · 长方形四周种树',
    tag: 'type4',
    tagLabel: '封闭型', difficulty: 2,
    text: '有一块长方形的土地，长、宽分别为 <strong>100 米</strong>、<strong>60 米</strong>，在这块土地的四周每隔 <strong>10 米</strong>种一棵树，4 个顶点处也要种树，一共要种多少棵树？',
    analysis: [
      '周长 = (100 + 60) × 2 = 320 米',
      '封闭型：棵数 = 周长 ÷ 间距 = 320 ÷ 10 = <strong>32 棵</strong>',
    ],
    type: 'none',
    finalQ: '一共要种多少棵树？',
    finalUnit: '棵',
    finalAns: 32,
  },
  {
    id: '13-P4',
    title: '课前测4 · 六边形花圃摆花盆',
    tag: 'type4',
    tagLabel: '封闭型', difficulty: 2,
    text: '在一个六边形花圃四周摆花盆，六个顶点都摆放，每边摆 <strong>7 盆</strong>花，这个花圃共摆放了多少盆花？',
    analysis: [
      '封闭型多边形：总盆数 = 边数 × (每边盆数 − 1)',
      '= 6 × (7 − 1) = 6 × 6 = <strong>36 盆</strong>',
    ],
    type: 'none',
    finalQ: '这个花圃共摆放了多少盆花？',
    finalUnit: '盆',
    finalAns: 36,
  },
  {
    id: '13-P5',
    title: '课前测5 · 剪绳子所需时间',
    tag: 'type2',
    tagLabel: '直线型一端不种', difficulty: 2,
    text: '有 <strong>6 根</strong>绳子，每根长 <strong>10 米</strong>，现在需要把它们剪成长为 <strong>2 米</strong>的短绳，如果每剪开一处需要 <strong>3 分钟</strong>，问全部剪完需要多少分钟？',
    analysis: [
      '1 根 10 米绳子剪成 2 米短绳，需剪成 5 段 → 需剪 4 次',
      '1 根绳子耗时 = 4 × 3 = 12 分钟',
      '6 根绳子总时间 = 6 × 12 = <strong>72 分钟</strong>',
    ],
    type: 'none',
    finalQ: '全部剪完需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 72,
  },
]

const LESSON: Problem[] = [
  {
    id: '13-L1',
    title: '例1 · 已知棵数求路长',
    tag: 'type1',
    tagLabel: '直线型两端都种', difficulty: 2,
    text: '在一条马路的两侧种树，每隔 <strong>5 米</strong>种一棵树，从头到尾共种了 <strong>42 棵</strong>，那么这条马路有多长？（树的宽度忽略不计）',
    analysis: [
      '两侧共 42 棵 → 一侧 42 ÷ 2 = 21 棵',
      '间距数 = 21 − 1 = 20 个',
      '路长 = 20 × 5 = <strong>100 米</strong>',
    ],
    type: 'none',
    finalQ: '这条马路有多长？',
    finalUnit: '米',
    finalAns: 100,
  },
  {
    id: '13-L2',
    title: '练一练 · 已知棵数求路长',
    tag: 'type1',
    tagLabel: '直线型两端都种', difficulty: 1,
    text: '一条马路正在进行绿化工程，准备在马路的一侧种树，两端都种，共种了 <strong>31 棵</strong>树，每两棵树之间的距离是 <strong>4 米</strong>，那么这条马路长多少米？（树的宽度忽略不计）',
    analysis: [
      '间距数 = 31 − 1 = 30 个',
      '路长 = 30 × 4 = <strong>120 米</strong>',
    ],
    type: 'none',
    finalQ: '这条马路长多少米？',
    finalUnit: '米',
    finalAns: 120,
  },
  {
    id: '13-L3',
    title: '例2(1) · 两端都放',
    tag: 'type1',
    tagLabel: '直线型两端都种', difficulty: 1,
    text: '公园的一条林荫大道长 <strong>100 米</strong>，在它的一侧每隔 <strong>20 米</strong>放一个垃圾桶。<strong>两端都放</strong>，一共能放多少个垃圾桶？',
    analysis: [
      '棵数 = 路长 ÷ 间距 + 1 = 100 ÷ 20 + 1 = <strong>6 个</strong>',
    ],
    type: 'none',
    finalQ: '两端都放，一共能放多少个垃圾桶？',
    finalUnit: '个',
    finalAns: 6,
  },
  {
    id: '13-L4',
    title: '例2(2) · 只一端放',
    tag: 'type2',
    tagLabel: '直线型一端不种', difficulty: 1,
    text: '公园的一条林荫大道长 <strong>100 米</strong>，在它的一侧每隔 <strong>20 米</strong>放一个垃圾桶。<strong>只在一端放</strong>，一共能放多少个垃圾桶？',
    analysis: [
      '棵数 = 路长 ÷ 间距 = 100 ÷ 20 = <strong>5 个</strong>',
    ],
    type: 'none',
    finalQ: '只在一端放，一共能放多少个垃圾桶？',
    finalUnit: '个',
    finalAns: 5,
  },
  {
    id: '13-L5',
    title: '例2(3) · 两端都不放',
    tag: 'type3',
    tagLabel: '直线型两端不种', difficulty: 1,
    text: '公园的一条林荫大道长 <strong>100 米</strong>，在它的一侧每隔 <strong>20 米</strong>放一个垃圾桶。<strong>两端都不放</strong>，一共能放多少个垃圾桶？',
    analysis: [
      '棵数 = 路长 ÷ 间距 − 1 = 100 ÷ 20 − 1 = <strong>4 个</strong>',
    ],
    type: 'none',
    finalQ: '两端都不放，一共能放多少个垃圾桶？',
    finalUnit: '个',
    finalAns: 4,
  },
  {
    id: '13-L6',
    title: '练一练 · 桥上挂彩灯',
    tag: 'type1',
    tagLabel: '直线型两端都种', difficulty: 1,
    text: '一座大桥长 <strong>400 米</strong>，在它的一侧每隔 <strong>4 米</strong>挂一个彩灯，从桥头到桥尾，一共挂了多少个彩灯？',
    analysis: [
      '棵数 = 路长 ÷ 间距 + 1 = 400 ÷ 4 + 1 = <strong>101 个</strong>',
    ],
    type: 'none',
    finalQ: '一共挂了多少个彩灯？',
    finalUnit: '个',
    finalAns: 101,
  },
  {
    id: '13-L7',
    title: '例3 · 已知路长和棵数求间距',
    tag: 'type1',
    tagLabel: '直线型两端都种', difficulty: 2,
    text: '学校有一条长 <strong>45 米</strong>的小道，在小道两边等距离地栽树，两端都种树，共栽了 <strong>12 棵</strong>，那么每两棵树之间的距离是多少米？（树的宽度忽略不计）',
    analysis: [
      '两边共 12 棵 → 一边 12 ÷ 2 = 6 棵',
      '间距数 = 6 − 1 = 5 个',
      '间距 = 45 ÷ 5 = <strong>9 米</strong>',
    ],
    type: 'none',
    finalQ: '每两棵树之间的距离是多少米？',
    finalUnit: '米',
    finalAns: 9,
  },
  {
    id: '13-L8',
    title: '练一练 · 110米栏架间距',
    tag: 'type1',
    tagLabel: '直线型两端都种', difficulty: 2,
    text: '纳约中学举行田径运动会，马上就要进行男子 <strong>110 米</strong>栏的比赛，一共需要摆放 <strong>11 个</strong>栏架，起点和终点都需要摆放，请问每两个栏架之间的距离是多少米？',
    analysis: [
      '间距数 = 11 − 1 = 10 个',
      '间距 = 110 ÷ 10 = <strong>11 米</strong>',
    ],
    type: 'none',
    finalQ: '每两个栏架之间的距离是多少米？',
    finalUnit: '米',
    finalAns: 11,
  },
  {
    id: '13-L9',
    title: '例4 · 行程速度求距离',
    tag: 'type5',
    tagLabel: '行程与速度', difficulty: 3,
    text: '马路的一边，每隔 <strong>10 米</strong>有一棵柳树，张叔叔乘汽车从家到公司，从看到第 <strong>1 棵</strong>树到第 <strong>61 棵</strong>树为止，共用时 <strong>2 分钟</strong>，张叔叔从家到公司共坐了 <strong>8 分钟</strong>的汽车，那么他们家距离公司多远？',
    analysis: [
      '第 1 到第 61 棵 = 60 个间距 = 600 米，用时 2 分钟',
      '速度 = 600 ÷ 2 = 300 米/分钟',
      '家到公司距离 = 300 × 8 = <strong>2400 米</strong>',
    ],
    type: 'none',
    finalQ: '家距离公司多远？',
    finalUnit: '米',
    finalAns: 2400,
  },
  {
    id: '13-L10',
    title: '练一练 · 行程速度求总距离',
    tag: 'type5',
    tagLabel: '行程与速度', difficulty: 3,
    text: '马路的一边，相隔 <strong>6 米</strong>有一棵杨树，辰辰乘公共汽车从家去学校，从看到第 <strong>1 棵</strong>树到第 <strong>41 棵</strong>树共用了 <strong>3 分钟</strong>，辰辰从家到学校共坐了 <strong>半小时</strong>的汽车，请问：辰辰家距离学校多远？',
    analysis: [
      '第 1 到第 41 棵 = 40 个间距 = 240 米，用时 3 分钟',
      '速度 = 240 ÷ 3 = 80 米/分钟',
      '家到学校距离 = 80 × 30 = <strong>2400 米</strong>',
    ],
    type: 'none',
    finalQ: '辰辰家距离学校多远？',
    finalUnit: '米',
    finalAns: 2400,
  },
  {
    id: '13-L11',
    title: '例题(练习)1 · 改变间距求时间',
    tag: 'type5',
    tagLabel: '行程与速度', difficulty: 4,
    text: '一条路的一边，每隔 <strong>10 米</strong>种一棵树，小明走路从第 <strong>1 棵</strong>树到第 <strong>51 棵</strong>树用了 <strong>30 分钟</strong>。如果每隔 <strong>5 米</strong>种一棵树，那么小明走完同样的路程需要多少分钟？',
    analysis: [
      '第 1 到第 51 棵 = 50 个间距 = 500 米，用时 30 分钟',
      '同样路程 500 米，间距改为 5 米不影响路程总长',
      '走完同样的路程仍需 <strong>30 分钟</strong>',
    ],
    type: 'none',
    finalQ: '走完同样的路程需要多少分钟？',
    finalUnit: '分钟',
    finalAns: 30,
  },
  {
    id: '13-L12',
    title: '例题(练习)2 · 改变间距求棵数',
    tag: 'type1',
    tagLabel: '直线型两端都种', difficulty: 3,
    text: '一条路的一边，每隔 <strong>4 米</strong>种一棵树，小小走完这条路共经过了 <strong>40 棵</strong>树。如果改成每隔 <strong>6 米</strong>种一棵树，那么小小走完同样的路程共经过了多少棵树？',
    analysis: [
      '路长 = (40 − 1) × 4 = 156 米',
      '改为 6 米间距，棵数 = 156 ÷ 6 + 1 = 26 + 1 = <strong>27 棵</strong>',
    ],
    type: 'none',
    finalQ: '改成每隔6米种一棵，共经过了多少棵树？',
    finalUnit: '棵',
    finalAns: 27,
  },
  {
    id: '13-L13',
    title: '例5 · 三角形池塘封闭型',
    tag: 'type4',
    tagLabel: '封闭型', difficulty: 2,
    text: '有一个三角形的池塘，三条边长度分别为 <strong>120 米</strong>、<strong>140 米</strong>、<strong>90 米</strong>，每个顶点处都要放一盆鲜花，在这个池塘的周围每隔 <strong>10 米</strong>摆放一盆鲜花，一共要摆放多少盆鲜花？',
    analysis: [
      '周长 = 120 + 140 + 90 = 350 米',
      '封闭型：盆数 = 周长 ÷ 间距 = 350 ÷ 10 = <strong>35 盆</strong>',
    ],
    type: 'none',
    finalQ: '一共要摆放多少盆鲜花？',
    finalUnit: '盆',
    finalAns: 35,
  },
  {
    id: '13-L14',
    title: '练一练 · 长方形地种杨树',
    tag: 'type4',
    tagLabel: '封闭型', difficulty: 2,
    text: '在一块长 <strong>80 米</strong>、宽 <strong>60 米</strong>的长方形地的周围种杨树，每个顶点处都要种树，每隔 <strong>4 米</strong>种一棵，一共要种多少棵杨树？',
    analysis: [
      '周长 = (80 + 60) × 2 = 280 米',
      '封闭型：棵数 = 280 ÷ 4 = <strong>70 棵</strong>',
    ],
    type: 'none',
    finalQ: '一共要种多少棵杨树？',
    finalUnit: '棵',
    finalAns: 70,
  },
  {
    id: '13-L15',
    title: '例6 · 圆形鱼池求周长和花盆数',
    tag: 'type4',
    tagLabel: '封闭型', difficulty: 3,
    text: '一个圆形养鱼池的一周种了 <strong>25 棵</strong>杨树，每两棵杨树之间的距离是 <strong>4 米</strong>，鱼池的周长是多少米？如果每两棵杨树之间摆放了 <strong>2 盆</strong>鲜花，一共摆放了多少盆鲜花？',
    analysis: [
      '封闭型：周长 = 棵数 × 间距 = 25 × 4 = 100 米',
      '每两棵杨树之间放 2 盆花，共 25 个间距',
      '花盆数 = 25 × 2 = <strong>50 盆</strong>',
    ],
    type: 'none',
    finalQ: '一共摆放了多少盆鲜花？',
    finalUnit: '盆',
    finalAns: 50,
  },
  {
    id: '13-L16',
    title: '练一练 · 正方形池塘求周长',
    tag: 'type4',
    tagLabel: '封闭型', difficulty: 2,
    text: '张伯伯在承包的正方形池塘四周种上树，每隔 <strong>5 米</strong>种一棵，四个角上各种一棵，共种了 <strong>40 棵</strong>，池塘的周长是多少米？',
    analysis: [
      '封闭型：周长 = 棵数 × 间距 = 40 × 5 = <strong>200 米</strong>',
    ],
    type: 'none',
    finalQ: '池塘的周长是多少米？',
    finalUnit: '米',
    finalAns: 200,
  },
  {
    id: '13-L17',
    title: '附加题1 · 改变间距求最多棵数',
    tag: 'type4',
    tagLabel: '封闭型', difficulty: 4,
    text: '在一条道路的两侧植树，如果每隔 <strong>3 米</strong>植一棵树，最多可以植 <strong>78 棵</strong>，如果每隔 <strong>2 米</strong>植一棵树，最多可以植多少棵？',
    analysis: [
      '"最多"对应封闭型：棵数 = 间距数，即两侧共 78 棵 → 一侧 39 棵',
      '一侧路长 = 39 × 3 = 117 米',
      '改每 2 米：一侧棵数 = 117 ÷ 2 = 58.5，封闭型两侧 = 117 棵',
      '（封闭型：周长 = 棵数 × 间距）两侧合计周长 = 78 × 3 = 234 米，改 2 米 → 234 ÷ 2 = <strong>117 棵</strong>',
    ],
    type: 'none',
    finalQ: '每隔2米植一棵树，最多可以植多少棵？',
    finalUnit: '棵',
    finalAns: 117,
  },
]

const HOMEWORK: Problem[] = [
  {
    id: '13-H1',
    title: '巩固1 · 两侧种树求路长',
    tag: 'type1',
    tagLabel: '直线型两端都种', difficulty: 2,
    text: '在一条马路的两侧种树，每隔 <strong>7 米</strong>种一棵树，两端都种，总共种了 <strong>22 棵</strong>树，那么这条马路长多少米？（树的宽度忽略不计）',
    analysis: [
      '两侧共 22 棵 → 一侧 11 棵',
      '间距数 = 11 − 1 = 10 个',
      '路长 = 10 × 7 = <strong>70 米</strong>',
    ],
    type: 'none',
    finalQ: '这条马路长多少米？',
    finalUnit: '米',
    finalAns: 70,
  },
  {
    id: '13-H2',
    title: '巩固2 · 一端不安装电线杆',
    tag: 'type2',
    tagLabel: '直线型一端不种', difficulty: 1,
    text: '在一条 <strong>63 米</strong>长的公路一侧安装电线杆，每隔 <strong>7 米</strong>安装一根。如果其中一端不安装，那么一共要安装多少根电线杆？',
    analysis: [
      '一端不装：根数 = 路长 ÷ 间距 = 63 ÷ 7 = <strong>9 根</strong>',
    ],
    type: 'none',
    finalQ: '一共要安装多少根电线杆？',
    finalUnit: '根',
    finalAns: 9,
  },
  {
    id: '13-H3',
    title: '巩固3 · 300米路求间距',
    tag: 'type1',
    tagLabel: '直线型两端都种', difficulty: 2,
    text: '在一条长 <strong>300 米</strong>的路的两侧栽树，起点和终点都栽，一共栽了 <strong>102 棵</strong>，每两棵树之间的距离都相等，你知道每两棵树之间是多少米吗？',
    analysis: [
      '两侧共 102 棵 → 一侧 51 棵',
      '间距数 = 51 − 1 = 50 个',
      '间距 = 300 ÷ 50 = <strong>6 米</strong>',
    ],
    type: 'none',
    finalQ: '每两棵树之间是多少米？',
    finalUnit: '米',
    finalAns: 6,
  },
  {
    id: '13-H4',
    title: '巩固4 · 已知局部距离求路长',
    tag: 'type1',
    tagLabel: '直线型两端都种', difficulty: 3,
    text: '在一条路的一边等间距地栽树，两端都栽，一共要栽 <strong>41 棵</strong>。已知从第 <strong>1 棵</strong>到第 <strong>10 棵</strong>有 <strong>90 米</strong>，那么这条路长多少米？',
    analysis: [
      '第 1 到第 10 棵 = 9 个间距 = 90 米',
      '间距 = 90 ÷ 9 = 10 米',
      '路长 = (41 − 1) × 10 = <strong>400 米</strong>',
    ],
    type: 'none',
    finalQ: '这条路长多少米？',
    finalUnit: '米',
    finalAns: 400,
  },
  {
    id: '13-H5',
    title: '巩固5 · 圆形鱼塘种树',
    tag: 'type4',
    tagLabel: '封闭型', difficulty: 1,
    text: '一个鱼塘的周长是 <strong>600 米</strong>，沿鱼塘周围每隔 <strong>6 米</strong>栽一棵杨树，需要种多少棵杨树？',
    analysis: [
      '封闭型：棵数 = 周长 ÷ 间距 = 600 ÷ 6 = <strong>100 棵</strong>',
    ],
    type: 'none',
    finalQ: '需要种多少棵杨树？',
    finalUnit: '棵',
    finalAns: 100,
  },
  {
    id: '13-H6',
    title: '巩固6 · 正方形广场种柳树',
    tag: 'type4',
    tagLabel: '封闭型', difficulty: 1,
    text: '在一个边长为 <strong>100 米</strong>的正方形广场的周围种柳树，每隔 <strong>10 米</strong>种一棵，且正方形广场的四个角必须要种树，那么一共要种多少棵柳树？',
    analysis: [
      '周长 = 100 × 4 = 400 米',
      '封闭型：棵数 = 400 ÷ 10 = <strong>40 棵</strong>',
    ],
    type: 'none',
    finalQ: '一共要种多少棵柳树？',
    finalUnit: '棵',
    finalAns: 40,
  },
]

const WORKBOOK: Problem[] = [
  {
    id: '13-W1',
    title: '闯关1 · 一端不种求间距',
    tag: 'type2',
    tagLabel: '直线型一端不种', difficulty: 2,
    text: '一条长 <strong>500 米</strong>的马路正在进行绿化工程，准备在马路的一侧种树，如果两端只有一端种树，一共种树 <strong>50 棵</strong>，那么相邻两棵树之间相距多少米？（树的宽度忽略不计）',
    analysis: [
      '一端不种：棵数 = 间距数 → 间距数 = 50',
      '间距 = 500 ÷ 50 = <strong>10 米</strong>',
    ],
    type: 'none',
    finalQ: '相邻两棵树之间相距多少米？',
    finalUnit: '米',
    finalAns: 10,
  },
  {
    id: '13-W2',
    title: '闯关2 · 两端都种求棵数',
    tag: 'type1',
    tagLabel: '直线型两端都种', difficulty: 2,
    text: '奇奇家和苗苗家之间有一条小路，在小路的一边，每隔 <strong>6 米</strong>有一棵树，已知奇奇家到苗苗家一共 <strong>600 米</strong>，那么奇奇家到苗苗家的这条小路上一共有多少棵树？（树的宽度忽略不计）',
    analysis: [
      '棵数 = 路长 ÷ 间距 + 1 = 600 ÷ 6 + 1 = 100 + 1 = <strong>101 棵</strong>',
    ],
    type: 'none',
    finalQ: '一共有多少棵树？',
    finalUnit: '棵',
    finalAns: 101,
  },
  {
    id: '13-W3',
    title: '闯关3 · 两侧路灯求间距',
    tag: 'type1',
    tagLabel: '直线型两端都种', difficulty: 2,
    text: '在一段 <strong>200 米</strong>长的马路两侧安装路灯，从两端开始等间距地安装了 <strong>22 盏</strong>路灯，那么相邻两盏路灯之间的距离是多少米？',
    analysis: [
      '两侧共 22 盏 → 一侧 11 盏',
      '间距数 = 11 − 1 = 10 个',
      '间距 = 200 ÷ 10 = <strong>20 米</strong>',
    ],
    type: 'none',
    finalQ: '相邻两盏路灯之间的距离是多少米？',
    finalUnit: '米',
    finalAns: 20,
  },
  {
    id: '13-W4',
    title: '闯关4 · 两侧种树求路长',
    tag: 'type1',
    tagLabel: '直线型两端都种', difficulty: 2,
    text: '公园里有一条小路，在小路两边种植了杨树，每隔 <strong>5 米</strong>栽一棵树，两端都种树，一共种植了 <strong>62 棵</strong>，那么这条小路有多长呢？（树的宽度忽略不计）',
    analysis: [
      '两边共 62 棵 → 一边 31 棵',
      '间距数 = 31 − 1 = 30 个',
      '路长 = 30 × 5 = <strong>150 米</strong>',
    ],
    type: 'none',
    finalQ: '这条小路有多长？',
    finalUnit: '米',
    finalAns: 150,
  },
  {
    id: '13-W5',
    title: '闯关5 · 圆形花坛求间距',
    tag: 'type4',
    tagLabel: '封闭型', difficulty: 1,
    text: '一个圆形花坛，周长是 <strong>160 米</strong>，在花坛的周围均匀地放了 <strong>10 盆</strong>芍药花，请问每两盆芍药花之间的距离是多少米？',
    analysis: [
      '封闭型：间距 = 周长 ÷ 棵数 = 160 ÷ 10 = <strong>16 米</strong>',
    ],
    type: 'none',
    finalQ: '每两盆芍药花之间的距离是多少米？',
    finalUnit: '米',
    finalAns: 16,
  },
  {
    id: '13-W6',
    title: '闯关6 · 五边形花圃摆花盆',
    tag: 'type4',
    tagLabel: '封闭型', difficulty: 2,
    text: '在一个五边形花圃四周摆花盆，五个顶点都摆放，每边摆 <strong>8 个</strong>花盆，这个花圃共摆放了多少盆花？',
    analysis: [
      '封闭型多边形：总盆数 = 边数 × (每边盆数 − 1)',
      '= 5 × (8 − 1) = 5 × 7 = <strong>35 盆</strong>',
    ],
    type: 'none',
    finalQ: '这个花圃共摆放了多少盆花？',
    finalUnit: '盆',
    finalAns: 35,
  },
  {
    id: '13-W7',
    title: '闯关7 · 长方形地基打桩',
    tag: 'type4',
    tagLabel: '封闭型', difficulty: 2,
    text: '建筑工程队要盖一栋楼，需要在长 <strong>120 米</strong>、宽 <strong>30 米</strong>的长方形地基上打桩，四个角上都要打桩，每隔 <strong>3 米</strong>打一根桩，这个地基的四周要打多少根桩？',
    analysis: [
      '周长 = (120 + 30) × 2 = 300 米',
      '封闭型：桩数 = 300 ÷ 3 = <strong>100 根</strong>',
    ],
    type: 'none',
    finalQ: '这个地基的四周要打多少根桩？',
    finalUnit: '根',
    finalAns: 100,
  },
  {
    id: '13-W8',
    title: '闯关8 · 路灯行走求路灯编号',
    tag: 'type5',
    tagLabel: '行程与速度', difficulty: 3,
    text: '老爷爷在公路上散步，已知他从第 <strong>1 个</strong>路灯走到第 <strong>12 个</strong>路灯处共用了 <strong>22 分钟</strong>，每两个路灯之间距离相等。那么当这位老爷爷走了 <strong>40 分钟</strong>时，他走到了第几个路灯处？',
    analysis: [
      '第 1 到第 12 路灯 = 11 个间距，用时 22 分钟',
      '每个间距用时 = 22 ÷ 11 = 2 分钟',
      '40 分钟走了 40 ÷ 2 = 20 个间距',
      '走到第 1 + 20 = <strong>第 21 个路灯</strong>',
    ],
    type: 'none',
    finalQ: '走了40分钟，走到了第几个路灯处？',
    finalUnit: '',
    finalAns: 21,
  },
  {
    id: '13-W9',
    title: '闯关9 · 改变间距求棵数',
    tag: 'type1',
    tagLabel: '直线型两端都种', difficulty: 3,
    text: '在两栋楼之间的马路两侧每隔 <strong>4 米</strong>种一棵樱花树，可以种 <strong>34 棵</strong>。现在改成每隔 <strong>6 米</strong>种一棵樱花树，一共可以种多少棵樱花树？（树的宽度忽略不计）',
    analysis: [
      '两侧共 34 棵 → 一侧 17 棵，间距数 = 16，路长 = 16 × 4 = 64 米',
      '改 6 米间距：一侧棵数 = 64 ÷ 6 + 1 ≈ 11 棵（取整）',
      '两侧总棵数 = 11 × 2 = <strong>22 棵</strong>',
    ],
    type: 'none',
    finalQ: '改成每隔6米，一共可以种多少棵樱花树？',
    finalUnit: '棵',
    finalAns: 22,
  },
  {
    id: '13-W10',
    title: '闯关10 · "田"字道路最少种树',
    tag: 'type4',
    tagLabel: '封闭型', difficulty: 5,
    text: '有一个长方形的"田"字道路，整个长方形的长为 <strong>16 米</strong>、宽为 <strong>12 米</strong>。现在需要在所有道路上种树，相邻两棵树之间的距离都相等，而且要求交叉路或拐弯处（顶点或中点）都要种上树，那么最少要种多少棵树？',
    analysis: [
      '"田"字：一条水平中线（将宽12米分为两段各6米），一条垂直中线（将长16米分为两段各8米）',
      '最大间距 = 最大公约数(6, 8) = 2 米',
      '水平方向每条线：x=0到16，每2米一棵，共9棵，3条横线共9×3=27点',
      '垂直方向每条线：y=0到12，每2米一棵，共7棵，3条竖线共7×3=21点',
      '减去交叉重叠：3条横线 × 3条竖线 = 9个交叉点',
      '总树数 = 27 + 21 − 9 = <strong>39 棵</strong>',
    ],
    type: 'none',
    finalQ: '最少要种多少棵树？',
    finalUnit: '棵',
    finalAns: 39,
  },
  {
    id: '13-W11',
    title: '闯关11 · 圆形花坛三色堇与风信子',
    tag: 'type4',
    tagLabel: '封闭型', difficulty: 3,
    text: '公园内有一个圆形花坛，绕着它走一圈是 <strong>120 米</strong>。如果沿着这一圈每隔 <strong>6 米</strong>栽一株三色堇，再在每相邻的两株三色堇之间等距离地栽 <strong>2 株</strong>风信子，可栽三色堇多少株？可栽风信子多少株？两株相邻的风信子之间相距多少米？',
    analysis: [
      '三色堇数 = 周长 ÷ 间距 = 120 ÷ 6 = 20 株',
      '风信子数 = 20 个间距 × 2 株 = 40 株',
      '两株风信子间距 = 6 ÷ 3 = 2 米',
    ],
    type: 'none',
    finalQ: '可栽风信子多少株？',
    finalUnit: '株',
    finalAns: 40,
  },
  {
    id: '13-W12',
    title: '闯关12 · 光缆连接器与固定器',
    tag: 'type5',
    tagLabel: '行程与速度', difficulty: 5,
    text: '纳约小区建设了多栋楼，物业叔叔为了小区的网络覆盖要把各栋楼用光缆连接起来，每根光缆的两头都用连接器连接，同一个连接器可以连接相邻的两根光缆，每根光缆的中间再用一个固定器固定，最后发现连接器和固定器一共用了 <strong>93 个</strong>，那么此次网络覆盖共用了多少根光缆？',
    analysis: [
      '设光缆根数为 n，则连接器数 = n + 1，固定器数 = n',
      '(n + 1) + n = 93 → 2n + 1 = 93 → 2n = 92 → n = <strong>46 根</strong>',
    ],
    type: 'none',
    finalQ: '此次网络覆盖共用了多少根光缆？',
    finalUnit: '根',
    finalAns: 46,
  },
]

export const PROBLEMS: ProblemSet = {
  pretest: PRETEST,
  lesson: LESSON,
  homework: HOMEWORK,
  workbook: WORKBOOK,
}

export const PROBLEM_TYPES = [
  {
    tag: 'type1',
    color: 'green',
    label: '题型1·直线型两端都种',
    desc: '棵数=间距数+1=路程÷间距+1。',
    example: '例：100米/5米+1=21棵',
  },
  {
    tag: 'type2',
    color: 'blue',
    label: '题型2·直线型一端不种',
    desc: '棵数=间距数=路程÷间距。',
    example: '例：100米/5米=20棵',
  },
  {
    tag: 'type3',
    color: 'orange',
    label: '题型3·直线型两端不种',
    desc: '棵数=间距数-1=路程÷间距-1。',
    example: '例：100米/5米-1=19棵',
  },
  {
    tag: 'type4',
    color: 'purple',
    label: '题型4·封闭型',
    desc: '棵数=间距数=周长÷间距（首尾相连无端点）。',
    example: '例：周长100米/5米=20棵',
  },
  {
    tag: 'type5',
    color: 'red',
    label: '题型5·行程与速度',
    desc: '利用植树棵数求时间/速度，间距数×间距=路程。',
    example: '例：看到第1到61棵=60个间距',
  },
]

export const TYPE_STYLE: Record<
  string,
  { bg: string; border: string; titleColor: string; textColor: string }
> = {
  type1: {
    bg: 'bg-green-50',
    border: 'border-l-green-500',
    titleColor: 'text-green-800',
    textColor: 'text-green-900',
  },
  type2: {
    bg: 'bg-blue-50',
    border: 'border-l-blue-500',
    titleColor: 'text-blue-800',
    textColor: 'text-blue-900',
  },
  type3: {
    bg: 'bg-orange-50',
    border: 'border-l-orange-500',
    titleColor: 'text-orange-800',
    textColor: 'text-orange-900',
  },
  type4: {
    bg: 'bg-purple-50',
    border: 'border-l-purple-500',
    titleColor: 'text-purple-800',
    textColor: 'text-purple-900',
  },
  type5: {
    bg: 'bg-red-50',
    border: 'border-l-red-500',
    titleColor: 'text-red-800',
    textColor: 'text-red-900',
  },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-green-100 text-green-800',
  type2: 'bg-blue-100 text-blue-800',
  type3: 'bg-orange-100 text-orange-800',
  type4: 'bg-purple-100 text-purple-800',
  type5: 'bg-red-100 text-red-800',
}
