import type { Problem, ProblemSet } from '@rosie/core'

const PRETEST: Problem[] = [
  {
    id: '43-P1',
    title: '课前测1 · 求第101项',
    tag: 'type1',
    tagLabel: '求第几项', difficulty: 3,
    text: '一个等差数列 <strong>2、5、8、11</strong>、……请问，这个数列的第 <strong>101</strong> 项是多少？',
    analysis: [
      '公差 d = 5 − 2 = 3',
      '第 n 项 = 首项 + (n − 1) × 公差',
      '第 101 项 = 2 + (101 − 1) × 3 = 2 + 300 = <strong>302</strong>',
    ],
    type: 'none',
    finalQ: '第 101 项是多少？',
    finalUnit: '',
    finalAns: 302,
  },
  {
    id: '43-P2',
    title: '课前测2 · 求项数',
    tag: 'type2',
    tagLabel: '求项数', difficulty: 2,
    text: '等差数列 <strong>1、5、9、13、17</strong>、……<strong>401</strong>，请问项数是多少？',
    analysis: [
      '公差 d = 4，首项 a₁ = 1',
      '项数 = (末项 − 首项) ÷ 公差 + 1',
      '项数 = (401 − 1) ÷ 4 + 1 = 100 + 1 = <strong>101</strong>',
    ],
    type: 'none',
    finalQ: '这个数列共有多少项？',
    finalUnit: '项',
    finalAns: 101,
  },
  {
    id: '43-P3',
    title: '课前测3 · 求公差与第15项',
    tag: 'type3',
    tagLabel: '求公差/首末项', difficulty: 3,
    text: '一个等差数列首项是 <strong>7</strong>，第 <strong>10</strong> 项是 <strong>97</strong>，那么这个等差数列的公差是多少？第 <strong>15</strong> 项是多少？',
    analysis: [
      '第 10 项比首项多 (10 − 1) = 9 个公差',
      '公差 d = (97 − 7) ÷ 9 = 90 ÷ 9 = <strong>10</strong>',
      '第 15 项 = 7 + (15 − 1) × 10 = 7 + 140 = <strong>147</strong>',
    ],
    type: 'none',
    finalQ: '第 15 项是多少？',
    finalUnit: '',
    finalAns: 147,
  },
  {
    id: '43-P4',
    title: '课前测4 · 剧场座位总数',
    tag: 'type4',
    tagLabel: '数列应用', difficulty: 3,
    text: '一个剧场设置了 <strong>22</strong> 排座位，第一排有 <strong>15</strong> 个座位，往后每排都比前一排多 <strong>2</strong> 个座位，这个剧场共有多少个座位？',
    analysis: [
      '末排座位 = 15 + (22 − 1) × 2 = 15 + 42 = 57',
      '座位总数 = (首项 + 末项) × 项数 ÷ 2',
      '= (15 + 57) × 22 ÷ 2 = 72 × 11 = <strong>792</strong>',
    ],
    type: 'none',
    finalQ: '这个剧场共有多少个座位？',
    finalUnit: '个',
    finalAns: 792,
  },
  {
    id: '43-P5',
    title: '课前测5 · 连续自然数求和',
    tag: 'type5',
    tagLabel: '首末项求和', difficulty: 2,
    text: '用等差数列求和公式，计算：<strong>5 + 6 + 7 + 8 + …… + 45 = ?</strong>',
    analysis: [
      '首末项求和：和 = (首项+末项) × 项数 ÷ 2',
      '首项 5，末项 45，项数 = (45 − 5) + 1 = 41',
      '和 = (5 + 45) × 41 ÷ 2 = <strong>1025</strong>',
    ],
    type: 'none',
    finalQ: '和是多少？',
    finalUnit: '',
    finalAns: 1025,
  },
]

const LESSON: Problem[] = [
  {
    id: '43-L1',
    title: '例1 · 递增数列第12项',
    tag: 'type1',
    tagLabel: '求第几项', difficulty: 1,
    text: '约约在纸上写了一串数：<strong>2，5，8，11，14</strong>，……如果按照此规律一直写下去，请问第 <strong>12</strong> 个数是多少？',
    analysis: [
      '公差 d = 3，首项 a₁ = 2',
      '第 12 项 = 2 + (12 − 1) × 3 = 2 + 33 = <strong>35</strong>',
    ],
    type: 'none',
    finalQ: '第 12 个数是多少？',
    finalUnit: '',
    finalAns: 35,
  },
  {
    id: '43-L2',
    title: '练一练 · 递减数列第10项',
    tag: 'type1',
    tagLabel: '求第几项', difficulty: 2,
    text: '<strong>47，45，43，41，39</strong>，……是按照规律排列的一串数，请问第 <strong>10</strong> 个数是多少？',
    analysis: [
      '公差 d = −2，首项 a₁ = 47',
      '第 10 项 = 47 + (10 − 1) × (−2) = 47 − 18 = <strong>29</strong>',
    ],
    type: 'none',
    finalQ: '第 10 个数是多少？',
    finalUnit: '',
    finalAns: 29,
  },
  {
    id: '43-L3',
    title: '例2 · 大于100的奇数第31个',
    tag: 'type1',
    tagLabel: '求第几项', difficulty: 2,
    text: '立立把比 <strong>100</strong> 大的奇数从小到大排成一列，你知道他写的第 <strong>31</strong> 个数是多少吗？',
    analysis: [
      '比 100 大的第一个奇数是 101',
      '奇数列公差 d = 2',
      '第 31 项 = 101 + (31 − 1) × 2 = 101 + 60 = <strong>161</strong>',
    ],
    type: 'none',
    finalQ: '第 31 个数是多少？',
    finalUnit: '',
    finalAns: 161,
  },
  {
    id: '43-L4',
    title: '练一练 · 从0开始的偶数第102个',
    tag: 'type1',
    tagLabel: '求第几项', difficulty: 2,
    text: '苗苗把从 <strong>0</strong> 开始的偶数从小到大排成一列，请问她写的第 <strong>102</strong> 个数是多少？',
    analysis: [
      '偶数列：0，2，4，6……公差 d = 2',
      '第 102 项 = 0 + (102 − 1) × 2 = <strong>202</strong>',
    ],
    type: 'none',
    finalQ: '第 102 个数是多少？',
    finalUnit: '',
    finalAns: 202,
  },
  {
    id: '43-L5',
    title: '例3 · 已知两项求公差',
    tag: 'type3',
    tagLabel: '求公差/首末项', difficulty: 2,
    text: '已知一个等差数列第 <strong>4</strong> 项等于 <strong>13</strong>，第 <strong>7</strong> 项等于 <strong>25</strong>，请问这个等差数列的公差是多少？',
    analysis: [
      '第 7 项比第 4 项多 3 个公差',
      '公差 d = (25 − 13) ÷ 3 = <strong>4</strong>',
    ],
    type: 'none',
    finalQ: '公差是多少？',
    finalUnit: '',
    finalAns: 4,
  },
  {
    id: '43-L6',
    title: '练一练 · 已知首项和第7项',
    tag: 'type3',
    tagLabel: '求公差/首末项', difficulty: 2,
    text: '已知一个等差数列首项是 <strong>13</strong>，第 <strong>7</strong> 项是 <strong>49</strong>，这个等差数列的公差是多少？',
    analysis: [
      '第 7 项比首项多 6 个公差',
      '公差 d = (49 − 13) ÷ 6 = 36 ÷ 6 = <strong>6</strong>',
    ],
    type: 'none',
    finalQ: '公差是多少？',
    finalUnit: '',
    finalAns: 6,
  },
  {
    id: '43-L7',
    title: '例4 · 求首项与第15项',
    tag: 'type3',
    tagLabel: '求公差/首末项', difficulty: 3,
    text: '已知一个等差数列第 <strong>5</strong> 项等于 <strong>16</strong>，第 <strong>8</strong> 项等于 <strong>25</strong>，请问这个等差数列的第 <strong>1</strong> 项是多少？第 <strong>15</strong> 项是多少？',
    analysis: [
      '公差 d = (25 − 16) ÷ 3 = 3',
      '第 1 项 = 16 − 4 × 3 = <strong>4</strong>',
      '第 15 项 = 4 + 14 × 3 = <strong>46</strong>',
    ],
    type: 'none',
    finalQ: '第 15 项是多少？',
    finalUnit: '',
    finalAns: 46,
  },
  {
    id: '43-L8',
    title: '练一练 · 求首项与第29项',
    tag: 'type3',
    tagLabel: '求公差/首末项', difficulty: 3,
    text: '一个等差数列第 <strong>7</strong> 项等于 <strong>32</strong>，第 <strong>9</strong> 项等于 <strong>40</strong>，请问这个等差数列的首项是多少？第 <strong>29</strong> 项是多少？',
    analysis: [
      '公差 d = (40 − 32) ÷ 2 = 4',
      '首项 = 32 − 6 × 4 = <strong>8</strong>',
      '第 29 项 = 8 + 28 × 4 = <strong>120</strong>',
    ],
    type: 'none',
    finalQ: '第 29 项是多少？',
    finalUnit: '',
    finalAns: 120,
  },
  {
    id: '43-L9',
    title: '例5 · 弹珠递减求公差',
    tag: 'type4',
    tagLabel: '数列应用', difficulty: 3,
    text: '编号为 <strong>1~9</strong> 的九个盒子里放有一些弹珠，每个盒子中的弹珠比前一个盒子<strong>少</strong>的颗数都相同。如果 <strong>1</strong> 号盒子中放了 <strong>77</strong> 颗，<strong>9</strong> 号盒子中放了 <strong>5</strong> 颗，请问每个盒子比前一个盒子中的弹珠少几颗？',
    analysis: [
      '9 个盒子成等差数列，首项 77，末项 5',
      '公差 d = (5 − 77) ÷ 8 = −9',
      '每个盒子比前一个<strong>少 9 颗</strong>',
    ],
    type: 'none',
    finalQ: '每个盒子比前一个少几颗？',
    finalUnit: '颗',
    finalAns: 9,
  },
  {
    id: '43-L10',
    title: '练一练 · 卖包子递增',
    tag: 'type4',
    tagLabel: '数列应用', difficulty: 3,
    text: '功夫熊猫连续卖了 <strong>7</strong> 天包子，这 7 天卖的包子个数恰好形成了一个等差数列，已知它第 <strong>1</strong> 天卖了 <strong>10</strong> 个，第 <strong>7</strong> 天卖了 <strong>22</strong> 个，请问相邻的两天后一天比前一天多卖几个包子？',
    analysis: [
      '7 天成等差数列，首项 10，末项 22',
      '公差 d = (22 − 10) ÷ 6 = <strong>2</strong>',
      '后一天比前一天多卖 2 个',
    ],
    type: 'none',
    finalQ: '后一天比前一天多卖几个？',
    finalUnit: '个',
    finalAns: 2,
  },
  {
    id: '43-L11',
    title: '例6 · 报数求人数',
    tag: 'type4',
    tagLabel: '数列应用', difficulty: 3,
    text: '体育课上老师指挥大家排成一排，阿立站排头报 <strong>17</strong>，阿奇站排尾报 <strong>157</strong>，每位同学报的数都比前一位多 <strong>7</strong>，那么队伍里一共有多少人？',
    analysis: [
      '报数成等差数列：首项 17，末项 157，公差 7',
      '人数 = (157 − 17) ÷ 7 + 1 = 140 ÷ 7 + 1 = <strong>21</strong> 人',
    ],
    type: 'none',
    finalQ: '队伍里一共有多少人？',
    finalUnit: '人',
    finalAns: 21,
  },
  {
    id: '43-L12',
    title: '练一练 · 读书天数',
    tag: 'type4',
    tagLabel: '数列应用', difficulty: 3,
    text: '悦悦读一本课外书，第一天读了 <strong>15</strong> 页，以后每天都比前一天多读 <strong>3</strong> 页，最后一天读了 <strong>36</strong> 页，刚好把书读完。请问悦悦一共读了多少天？',
    analysis: [
      '每天页数成等差数列：首项 15，末项 36，公差 3',
      '天数 = (36 − 15) ÷ 3 + 1 = 7 + 1 = <strong>8</strong> 天',
    ],
    type: 'none',
    finalQ: '悦悦一共读了多少天？',
    finalUnit: '天',
    finalAns: 8,
  },
  {
    id: '43-L13',
    title: '附加题1(1) · 4加到76',
    tag: 'type5',
    tagLabel: '首末项求和', difficulty: 3,
    text: '用等差数列求和公式计算：<strong>4 + 5 + 6 + …… + 76 = ?</strong>',
    analysis: [
      '首末项求和：和 = (首项+末项) × 项数 ÷ 2',
      '首项 4，末项 76，项数 = (76 − 4) + 1 = 73',
      '和 = (4 + 76) × 73 ÷ 2 = <strong>2920</strong>',
    ],
    type: 'none',
    finalQ: '和是多少？',
    finalUnit: '',
    finalAns: 2920,
  },
  {
    id: '43-L14',
    title: '附加题1(2) · 奇数求和',
    tag: 'type5',
    tagLabel: '首末项求和', difficulty: 3,
    text: '用等差数列求和公式计算：<strong>1 + 3 + 5 + 7 + …… + 57 + 59 = ?</strong>',
    analysis: [
      '首末项求和：和 = (首项+末项) × 项数 ÷ 2',
      '首项 1，末项 59，公差 2，项数 = (59 − 1) ÷ 2 + 1 = 30',
      '和 = (1 + 59) × 30 ÷ 2 = <strong>900</strong>',
    ],
    type: 'none',
    finalQ: '和是多少？',
    finalUnit: '',
    finalAns: 900,
  },
  {
    id: '43-L15',
    title: '附加题2(1) · 连续偶数求最大',
    tag: 'type7',
    tagLabel: '中项求和', difficulty: 3,
    text: '<strong>7</strong> 个连续偶数的和是 <strong>70</strong>，其中最大的偶数是多少？',
    analysis: [
      '中项求和：和 = 中项 × 项数',
      '中项（第 4 个偶数）= 70 ÷ 7 = <strong>10</strong>',
      '7 个偶数：4，6，8，10，12，14，16 → 最大 <strong>16</strong>',
    ],
    type: 'none',
    finalQ: '最大的偶数是多少？',
    finalUnit: '',
    finalAns: 16,
  },
  {
    id: '43-L16',
    title: '附加题2(2) · 连续自然数求最小',
    tag: 'type7',
    tagLabel: '中项求和', difficulty: 3,
    text: '<strong>6</strong> 个连续自然数的和是 <strong>135</strong>，其中最小的自然数是多少？',
    analysis: [
      '中项求和：和 = 中项 × 项数（中项为各项的平均数）',
      '中项 = 135 ÷ 6 = 22.5',
      '最小数 = 22.5 − (6−1)÷2 = <strong>20</strong>',
    ],
    type: 'none',
    finalQ: '最小的自然数是多少？',
    finalUnit: '',
    finalAns: 20,
  },
]

const HOMEWORK: Problem[] = [
  {
    id: '43-H1',
    title: '巩固1 · 求末项',
    tag: 'type3',
    tagLabel: '求公差/首末项', difficulty: 2,
    text: '一个等差数列共有 <strong>10</strong> 项，每一项都比它的前一项大 <strong>3</strong>，并且首项为 <strong>23</strong>，那么末项是多少？',
    analysis: [
      '末项 = 23 + (10 − 1) × 3 = 23 + 27 = <strong>50</strong>',
    ],
    type: 'none',
    finalQ: '末项是多少？',
    finalUnit: '',
    finalAns: 50,
  },
  {
    id: '43-H2',
    title: '巩固2 · 递减求首项',
    tag: 'type3',
    tagLabel: '求公差/首末项', difficulty: 2,
    text: '一个等差数列共 <strong>18</strong> 项，每一项都比它的前一项小 <strong>4</strong>，并且末项为 <strong>32</strong>，那么首项是多少？',
    analysis: [
      '首项 = 32 + (18 − 1) × 4 = 32 + 68 = <strong>100</strong>',
    ],
    type: 'none',
    finalQ: '首项是多少？',
    finalUnit: '',
    finalAns: 100,
  },
  {
    id: '43-H3',
    title: '巩固3 · 已知两项求第8项',
    tag: 'type1',
    tagLabel: '求第几项', difficulty: 3,
    text: '如果一个等差数列的第 <strong>4</strong> 项为 <strong>21</strong>，第 <strong>13</strong> 项为 <strong>75</strong>，它的第 <strong>8</strong> 项是多少呢？',
    analysis: [
      '公差 d = (75 − 21) ÷ 9 = 6',
      '第 8 项 = 21 + (8 − 4) × 6 = 21 + 24 = <strong>45</strong>',
    ],
    type: 'none',
    finalQ: '第 8 项是多少？',
    finalUnit: '',
    finalAns: 45,
  },
  {
    id: '43-H4',
    title: '巩固4 · 求项数',
    tag: 'type2',
    tagLabel: '求项数', difficulty: 2,
    text: '已知数列 <strong>2，6，10，14，18，22</strong>，……，<strong>162</strong>，这个数列共有多少项？',
    analysis: [
      '公差 d = 4',
      '项数 = (162 − 2) ÷ 4 + 1 = 40 + 1 = <strong>41</strong>',
    ],
    type: 'none',
    finalQ: '这个数列共有多少项？',
    finalUnit: '项',
    finalAns: 41,
  },
  {
    id: '43-H5',
    title: '巩固5 · 三项综合',
    tag: 'type6',
    tagLabel: '综合规律', difficulty: 4,
    text: '对于数列 <strong>4，7，10，13，16，19</strong>，……，第 <strong>10</strong> 项是多少？<strong>49</strong> 是这个数列的第几项？第 <strong>100</strong> 项与第 <strong>50</strong> 项的差是多少？',
    analysis: [
      '公差 d = 3',
      '第 10 项 = 4 + 9 × 3 = <strong>31</strong>',
      '49 是第 (49 − 4) ÷ 3 + 1 = <strong>16</strong> 项',
      '第 100 项 − 第 50 项 = (100 − 50) × 3 = <strong>150</strong>',
    ],
    type: 'none',
    finalQ: '第 100 项与第 50 项的差是多少？',
    finalUnit: '',
    finalAns: 150,
  },
  {
    id: '43-H6',
    title: '巩固6 · 圆木堆梯形',
    tag: 'type4',
    tagLabel: '数列应用', difficulty: 3,
    text: '有一堆粗细均匀的圆木，堆成了一个梯形，最上面的一层有 <strong>6</strong> 根圆木，每向下一层增加 <strong>1</strong> 根，一共堆放了 <strong>20</strong> 层。请问最下面一层有多少根？',
    analysis: [
      '每层根数成等差数列：首项 6，公差 1，共 20 层',
      '最下层 = 6 + (20 − 1) × 1 = <strong>25</strong> 根',
    ],
    type: 'none',
    finalQ: '最下面一层有多少根？',
    finalUnit: '根',
    finalAns: 25,
  },
]

const WORKBOOK: Problem[] = [
  {
    id: '43-W1',
    title: '闯关1 · 公差个数与第26项',
    tag: 'type1',
    tagLabel: '求第几项', difficulty: 3,
    text: '等差数列 <strong>300，296，292，288，284，280</strong>……请问这个数列第 <strong>1</strong> 项和第 <strong>10</strong> 项之间相差多少个公差？第 <strong>26</strong> 项是多少？',
    analysis: [
      '第 1 项与第 10 项之间相差 10 − 1 = <strong>9</strong> 个公差',
      '公差 d = −4，第 26 项 = 300 + 25 × (−4) = <strong>200</strong>',
    ],
    type: 'none',
    finalQ: '第 26 项是多少？',
    finalUnit: '',
    finalAns: 200,
  },
  {
    id: '43-W2',
    title: '闯关2 · 分苹果',
    tag: 'type4',
    tagLabel: '数列应用', difficulty: 3,
    text: '<strong>5</strong> 个人共领取 <strong>55</strong> 个苹果，从第二个人起，每人比前一人多领取 <strong>2</strong> 个，第一个人领取了多少个？',
    analysis: [
      '5 人领取数成等差数列，公差 2，总和 55',
      '5a + (0+2+4+6+8) = 55 → 5a + 20 = 55 → a = <strong>9</strong>',
    ],
    type: 'none',
    finalQ: '第一个人领取了多少个？',
    finalUnit: '个',
    finalAns: 9,
  },
  {
    id: '43-W3',
    title: '闯关3 · 已知两项',
    tag: 'type3',
    tagLabel: '求公差/首末项', difficulty: 3,
    text: '已知一个等差数列第 <strong>8</strong> 项是 <strong>50</strong>，第 <strong>15</strong> 项是 <strong>71</strong>。那么这个等差数列的公差是多少？第 <strong>11</strong> 项是多少？',
    analysis: [
      '公差 d = (71 − 50) ÷ 7 = 3',
      '第 11 项 = 50 + 3 × 3 = <strong>59</strong>',
    ],
    type: 'none',
    finalQ: '第 11 项是多少？',
    finalUnit: '',
    finalAns: 59,
  },
  {
    id: '43-W4',
    title: '闯关4 · 循环算式',
    tag: 'type6',
    tagLabel: '综合规律', difficulty: 5,
    text: '算式 <strong>1+3，2+5，3+7，4+9，1+11，2+13，3+15，4+17，1+19</strong>……请问第 <strong>31</strong> 个算式是什么？（只填和）',
    analysis: [
      '左加数循环 1、2、3、4；右加数 = 3 + 2×(n−1)',
      '第 31 个：左加数 = (31−1) mod 4 + 1 = 3',
      '右加数 = 3 + 60 = 63，算式和 = 3 + 63 = <strong>66</strong>',
    ],
    type: 'none',
    finalQ: '第 31 个算式的和是多少？',
    finalUnit: '',
    finalAns: 66,
  },
  {
    id: '43-W5',
    title: '闯关5 · 连续偶数求最大',
    tag: 'type7',
    tagLabel: '中项求和', difficulty: 3,
    text: '九个连续偶数的和为 <strong>72</strong>，那么其中最大的偶数是多少？',
    analysis: [
      '中项求和：和 = 中项 × 项数',
      '中项（第 5 个偶数）= 72 ÷ 9 = <strong>8</strong>',
      '9 个偶数：0，2，4，6，8，10，12，14，16 → 最大 <strong>16</strong>',
    ],
    type: 'none',
    finalQ: '最大的偶数是多少？',
    finalUnit: '',
    finalAns: 16,
  },
  {
    id: '43-W6',
    title: '闯关6(1) · 3加到77',
    tag: 'type5',
    tagLabel: '首末项求和', difficulty: 3,
    text: '用等差数列求和公式计算：<strong>3 + 4 + 5 + 6 + …… + 76 + 77 = ?</strong>',
    analysis: [
      '项数 = 77 − 3 + 1 = 75',
      '和 = (3 + 77) × 75 ÷ 2 = <strong>3000</strong>',
    ],
    type: 'none',
    finalQ: '和是多少？',
    finalUnit: '',
    finalAns: 3000,
  },
  {
    id: '43-W7',
    title: '闯关6(2) · 奇数求和',
    tag: 'type5',
    tagLabel: '首末项求和', difficulty: 3,
    text: '用等差数列求和公式计算：<strong>1 + 3 + 5 + 7 + …… + 87 + 89 = ?</strong>',
    analysis: [
      '项数 = (89 − 1) ÷ 2 + 1 = 45',
      '和 = (1 + 89) × 45 ÷ 2 = <strong>2025</strong>',
    ],
    type: 'none',
    finalQ: '和是多少？',
    finalUnit: '',
    finalAns: 2025,
  },
  {
    id: '43-W8',
    title: '闯关6(3) · 公差3求和',
    tag: 'type5',
    tagLabel: '首末项求和', difficulty: 3,
    text: '用等差数列求和公式计算：<strong>4 + 7 + 10 + 13 + …… + 43 + 46 = ?</strong>',
    analysis: [
      '项数 = (46 − 4) ÷ 3 + 1 = 15',
      '和 = (4 + 46) × 15 ÷ 2 = <strong>375</strong>',
    ],
    type: 'none',
    finalQ: '和是多少？',
    finalUnit: '',
    finalAns: 375,
  },
  {
    id: '43-W9',
    title: '闯关7 · 拆数成等差数列',
    tag: 'type4',
    tagLabel: '数列应用', difficulty: 4,
    text: '把 <strong>210</strong> 拆成 <strong>7</strong> 个自然数的和，使这 7 个数从小到大排成一行后，相邻两个数的差都是 <strong>5</strong>，请问第 <strong>2</strong> 个数与第 <strong>7</strong> 个数分别是多少？',
    analysis: [
      '7 项和 = 7a + (0+5+10+15+20+25+30) = 7a + 105 = 210',
      'a = 15，第 2 个数 = 20，第 7 个数 = <strong>45</strong>',
    ],
    type: 'none',
    finalQ: '第 7 个数是多少？',
    finalUnit: '',
    finalAns: 45,
  },
  {
    id: '43-W10',
    title: '闯关8 · 电影院座位',
    tag: 'type4',
    tagLabel: '数列应用', difficulty: 4,
    text: '一个电影院有 <strong>18</strong> 排座位，后一排比前一排多 <strong>2</strong> 个座位，最后一排有 <strong>50</strong> 个座位，这个电影院一共有多少个座位？',
    analysis: [
      '首排 = 50 − 17 × 2 = 16',
      '总座位 = (16 + 50) × 18 ÷ 2 = <strong>594</strong>',
    ],
    type: 'none',
    finalQ: '这个电影院一共有多少个座位？',
    finalUnit: '个',
    finalAns: 594,
  },
  {
    id: '43-W11',
    title: '闯关9 · 前5项和求第5项',
    tag: 'type3',
    tagLabel: '求公差/首末项', difficulty: 3,
    text: '一个等差数列的第 <strong>1</strong> 项是 <strong>3</strong>，前 <strong>5</strong> 项的和为 <strong>40</strong>，这个数列的第 <strong>5</strong> 项是多少？',
    analysis: [
      'S₅ = 5/2 × (2×3 + 4d) = 40 → 6 + 4d = 16 → d = 2.5',
      '第 5 项 = 3 + 4 × 2.5 = <strong>13</strong>',
    ],
    type: 'none',
    finalQ: '第 5 项是多少？',
    finalUnit: '',
    finalAns: 13,
  },
  {
    id: '43-W12',
    title: '闯关10 · 中间三项的和',
    tag: 'type6',
    tagLabel: '综合规律', difficulty: 5,
    text: '一个等差数列共 <strong>9</strong> 项，已知前 <strong>3</strong> 项的和为 <strong>24</strong>，最后 <strong>3</strong> 项的和为 <strong>84</strong>，请问中间三项的和是多少？',
    analysis: [
      '3a₁ + 3d = 24，3a₁ + 21d = 84 → 18d = 60 → d = 10/3',
      '中间三项 = 3 × 第 5 项 = 3 × 18 = <strong>54</strong>',
    ],
    type: 'none',
    finalQ: '中间三项的和是多少？',
    finalUnit: '',
    finalAns: 54,
  },
  {
    id: '43-W13',
    title: '闯关11 · 奇偶项之差',
    tag: 'type6',
    tagLabel: '综合规律', difficulty: 5,
    text: '已知等差数列 <strong>1，5，9，13</strong>，……<strong>97，101</strong>。求这个数列的奇数项之和与偶数项之和的差是多少？',
    analysis: [
      '共 26 项；奇数位 13 项：1，9，17……和 = 325',
      '偶数位 13 项：5，13，21……和 = 377',
      '差 = 325 − 377 = <strong>52</strong>（奇数项和比偶数项和小 52）',
    ],
    type: 'none',
    finalQ: '奇数项之和与偶数项之和相差多少？（填正数）',
    finalUnit: '',
    finalAns: 52,
  },
  {
    id: '43-W14',
    title: '闯关12 · 算式和的总和',
    tag: 'type6',
    tagLabel: '综合规律', difficulty: 5,
    text: '加法算式的和组成等差数列：<strong>4+1，5+3，6+5，7+7，8+9</strong>，……最后一个算式的和为 <strong>83</strong>。那么所有项的和是多少？',
    analysis: [
      '第 k 个算式和 = 5 + 3k；83 = 5 + 3k → k = 26，共 27 项',
      '总和 = 27×5 + 3×(0+1+…+26) = 135 + 1053 = <strong>1188</strong>',
    ],
    type: 'none',
    finalQ: '所有算式的和的总和是多少？',
    finalUnit: '',
    finalAns: 1188,
  },
]

const SUPPLEMENT: Problem[] = [
  {
    id: '43-S1',
    title: '附加1(1) · 奇数列第18项',
    tag: 'type1',
    tagLabel: '求第几项', difficulty: 2,
    text: '数列 <strong>1，3，5，7</strong>，……第 <strong>18</strong> 项是多少？',
    analysis: [
      '公差 d = 2，第 18 项 = 1 + 17 × 2 = <strong>35</strong>',
    ],
    type: 'none',
    finalQ: '第 18 项是多少？',
    finalUnit: '',
    finalAns: 35,
  },
  {
    id: '43-S2',
    title: '附加1(2) · 256是第几项',
    tag: 'type2',
    tagLabel: '求项数', difficulty: 2,
    text: '数列 <strong>2，4，6，8</strong>，……其中 <strong>256</strong> 是这个数列的第几项？',
    analysis: [
      '项数 = (256 − 2) ÷ 2 + 1 = <strong>128</strong>',
    ],
    type: 'none',
    finalQ: '256 是第几项？',
    finalUnit: '项',
    finalAns: 128,
  },
  {
    id: '43-S3',
    title: '附加1(3) · 求项数',
    tag: 'type2',
    tagLabel: '求项数', difficulty: 2,
    text: '数列 <strong>3，6，9</strong>，……，<strong>180</strong>，这个数列共有多少项？',
    analysis: [
      '项数 = (180 − 3) ÷ 3 + 1 = <strong>60</strong>',
    ],
    type: 'none',
    finalQ: '这个数列共有多少项？',
    finalUnit: '项',
    finalAns: 60,
  },
  {
    id: '43-S4',
    title: '附加2(1) · 6的倍数个数',
    tag: 'type2',
    tagLabel: '求项数', difficulty: 2,
    text: '<strong>1</strong> 至 <strong>100</strong> 中 <strong>6</strong> 的倍数有多少个？',
    analysis: [
      '6 的倍数：6，12，……96',
      '个数 = 100 ÷ 6 = <strong>16</strong> 个（取整）',
    ],
    type: 'none',
    finalQ: '6 的倍数有多少个？',
    finalUnit: '个',
    finalAns: 16,
  },
  {
    id: '43-S5',
    title: '附加2(2) · 除以6余1求和',
    tag: 'type5',
    tagLabel: '首末项求和', difficulty: 3,
    text: '<strong>1</strong> 至 <strong>100</strong> 中除以 <strong>6</strong> 余 <strong>1</strong> 的数的和是多少？',
    analysis: [
      '数列：1，7，13，……97，公差 6，共 17 项',
      '和 = (1 + 97) × 17 ÷ 2 = <strong>833</strong>',
    ],
    type: 'none',
    finalQ: '这些数的和是多少？',
    finalUnit: '',
    finalAns: 833,
  },
  {
    id: '43-S6',
    title: '附加4 · 交错数列第100项',
    tag: 'type6',
    tagLabel: '综合规律', difficulty: 5,
    text: '有一列数：<strong>2，3，5，6，8，9，11，12</strong>，……，问这列数的第 <strong>100</strong> 个是多少？',
    analysis: [
      '奇数位：2，5，8，11……公差 3；第 100 个在偶数位',
      '偶数位：3，6，9，12……第 50 个 = 3 + 49×3 = <strong>150</strong>',
    ],
    type: 'none',
    finalQ: '第 100 个数是多少？',
    finalUnit: '',
    finalAns: 150,
  },
  {
    id: '43-S7',
    title: '附加4(2) · 前100项的和',
    tag: 'type5',
    tagLabel: '首末项求和', difficulty: 5,
    text: '数列 <strong>2，3，5，6，8，9，11，12</strong>，……前 <strong>100</strong> 项的和是多少？',
    analysis: [
      '奇数位：2，5，8……50 项，和 = 50/2×(2+149) = 3775',
      '偶数位：3，6，9……50 项，和 = 50/2×(3+150) = 3825',
      '前 100 项和 = 3775 + 3825 = <strong>7600</strong>',
    ],
    type: 'none',
    finalQ: '前 100 项的和是多少？',
    finalUnit: '',
    finalAns: 7600,
  },
  {
    id: '43-S8',
    title: '附加5 · 前15项的和',
    tag: 'type5',
    tagLabel: '首末项求和', difficulty: 4,
    text: '有一列等差数列，它的前 <strong>5</strong> 项的和为 <strong>130</strong>，前 <strong>10</strong> 项的和为 <strong>310</strong>，它的前 <strong>15</strong> 项的和是多少？',
    analysis: [
      '5a₁ + 10d = 130 → a₁ + 2d = 26',
      '10a₁ + 45d = 310 → 2a₁ + 9d = 62',
      'd = 2，a₁ = 22，S₁₅ = 15/2 × (44 + 28) = <strong>540</strong>',
    ],
    type: 'none',
    finalQ: '前 15 项的和是多少？',
    finalUnit: '',
    finalAns: 540,
  },
]

export const PROBLEMS: ProblemSet = {
  pretest: PRETEST,
  lesson: LESSON,
  homework: HOMEWORK,
  workbook: WORKBOOK,
  supplement: SUPPLEMENT,
}

export const PROBLEM_TYPES = [
  {
    tag: 'type1',
    color: 'blue',
    label: '题型1 · 求第几项',
    desc: '已知首项、公差和项数位置，用 第n项 = 首项 + (n−1)×公差 求指定项。',
    example: '例：2,5,8…→ 第12项 = 2+11×3 = 35',
  },
  {
    tag: 'type2',
    color: 'green',
    label: '题型2 · 求项数',
    desc: '已知首项、末项和公差，用 项数 = (末项−首项)÷公差 + 1。',
    example: '例：1,5,9…401 → (401−1)÷4+1 = 101项',
  },
  {
    tag: 'type3',
    color: 'orange',
    label: '题型3 · 求公差/首末项',
    desc: '利用两项之差求公差，再反推首项或末项。',
    example: '例：第4项13、第7项25 → d=4',
  },
  {
    tag: 'type4',
    color: 'purple',
    label: '题型4 · 数列应用',
    desc: '把生活中的数量关系抽象成等差数列，求公差、项数或总量。',
    example: '例：报数17→157，每人+7 → 21人',
  },
  {
    tag: 'type5',
    color: 'red',
    label: '题型5 · 首末项求和',
    desc: '已知首项和末项，用 和 = (首项+末项)×项数÷2 求和。',
    example: '例：5+6+…+45 → 和1025',
  },
  {
    tag: 'type7',
    color: 'teal',
    label: '题型7 · 中项求和',
    desc: '已知项数与总和，用 和 = 中项×项数 求中项，再反推最大/最小项。',
    example: '例：7个连续偶数和70 → 中项10',
  },
  {
    tag: 'type6',
    color: 'pink',
    label: '题型6 · 综合规律',
    desc: '循环算式、奇偶项分组、算式和数列等需要发现规律再计算。',
    example: '例：1+3,2+5,3+7…第31个和=66',
  },
]

export const TYPE_STYLE: Record<
  string,
  { bg: string; border: string; titleColor: string; textColor: string }
> = {
  type1: {
    bg: 'bg-blue-50',
    border: 'border-l-blue-500',
    titleColor: 'text-blue-800',
    textColor: 'text-blue-900',
  },
  type2: {
    bg: 'bg-green-50',
    border: 'border-l-green-500',
    titleColor: 'text-green-800',
    textColor: 'text-green-900',
  },
  type3: {
    bg: 'bg-orange-50',
    border: 'border-l-orange-500',
    titleColor: 'text-orange-800',
    textColor: 'text-orange-900',
  },
  type4: {
    bg: 'bg-purple-50',
    border: 'border-l-purple-500',
    titleColor: 'text-purple-800',
    textColor: 'text-purple-900',
  },
  type5: {
    bg: 'bg-red-50',
    border: 'border-l-red-500',
    titleColor: 'text-red-800',
    textColor: 'text-red-900',
  },
  type7: {
    bg: 'bg-teal-50',
    border: 'border-l-teal-500',
    titleColor: 'text-teal-800',
    textColor: 'text-teal-900',
  },
  type6: {
    bg: 'bg-pink-50',
    border: 'border-l-pink-500',
    titleColor: 'text-pink-800',
    textColor: 'text-pink-900',
  },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-blue-100 text-blue-800',
  type2: 'bg-green-100 text-green-800',
  type3: 'bg-orange-100 text-orange-800',
  type4: 'bg-purple-100 text-purple-800',
  type5: 'bg-red-100 text-red-800',
  type7: 'bg-teal-100 text-teal-800',
  type6: 'bg-pink-100 text-pink-800',
}
