import type { Problem, ProblemSet } from '@rosie/core'

const PRETEST: Problem[] = [
  {
    id: '18-P1',
    title: '课前测1 · 和倍问题',
    tag: 'type1',
    tagLabel: '题型1·和倍问题', difficulty: 2,
    text: '学校将 <strong>360</strong> 本书分给二、三两个年级，已知三年级所分得的本数是二年级的 <strong>2 倍</strong>，问二、三年级各分得多少本图书？',
    analysis: [
      '二年级是1份，三年级是2份，共1+2=3份',
      '二年级 = 360 ÷ 3 = <strong>120</strong> 本',
      '三年级 = 120 × 2 = <strong>240</strong> 本',
    ],
    type: 'none',
    finalQ: '二年级分得多少本？',
    finalUnit: '本',
    finalAns: 120,
  },
  {
    id: '18-P2',
    title: '课前测2 · 和倍变形',
    tag: 'type2',
    tagLabel: '题型2·和倍变形', difficulty: 3,
    text: '学校将 <strong>360</strong> 本图书分给二、三两个年级，已知三年级所分得的本数比二年级的 <strong>2 倍还多 60 本</strong>，问二、三年级各分得多少本图书？',
    analysis: [
      '假设二年级是1份：三年级 = 二年级×2 + 60',
      '把多出的60本去掉：360 - 60 = 300，这时共3份',
      '二年级 = 300 ÷ 3 = <strong>100</strong> 本',
      '三年级 = 100 × 2 + 60 = <strong>260</strong> 本',
    ],
    type: 'none',
    finalQ: '二年级分得多少本？',
    finalUnit: '本',
    finalAns: 100,
  },
  {
    id: '18-P3',
    title: '课前测3 · 差倍问题',
    tag: 'type3',
    tagLabel: '题型3·差倍问题', difficulty: 2,
    text: '奇奇存款数是立立的 <strong>4 倍</strong>，奇奇比立立多存 <strong>600 元</strong>。奇奇、立立两人各存款多少元？',
    analysis: [
      '立立是1份，奇奇是4份，差 = 4-1 = 3份',
      '立立 = 600 ÷ 3 = <strong>200</strong> 元',
      '奇奇 = 200 × 4 = <strong>800</strong> 元',
    ],
    type: 'none',
    finalQ: '立立存款多少元？',
    finalUnit: '元',
    finalAns: 200,
  },
  {
    id: '18-P4',
    title: '课前测4 · 差倍问题',
    tag: 'type3',
    tagLabel: '题型3·差倍问题', difficulty: 2,
    text: '思思的科技书比故事书少 <strong>16 本</strong>，故事书是科技书的 <strong>3 倍</strong>，思思的科技书和故事书各有多少本？',
    analysis: [
      '科技书是1份，故事书是3份，差 = 3-1 = 2份',
      '科技书 = 16 ÷ 2 = <strong>8</strong> 本',
      '故事书 = 8 × 3 = <strong>24</strong> 本',
    ],
    type: 'none',
    finalQ: '科技书有多少本？',
    finalUnit: '本',
    finalAns: 8,
  },
  {
    id: '18-P5',
    title: '课前测5 · 差倍变形',
    tag: 'type4',
    tagLabel: '题型4·差倍变形', difficulty: 4,
    text: '苗苗和悦悦都是集邮爱好者，已知苗苗集的张数比悦悦<strong>多 26 张</strong>，且苗苗集的张数比悦悦的 <strong>3 倍少 14 张</strong>。苗苗和悦悦各集有多少张精品邮票？',
    analysis: [
      '设悦悦有 x 张，则苗苗 = 3x - 14',
      '苗苗 - 悦悦 = 26，即 3x - 14 - x = 26',
      '2x = 40，x = <strong>20</strong>（悦悦）',
      '苗苗 = 20 × 3 - 14 = <strong>46</strong> 张',
    ],
    type: 'none',
    finalQ: '悦悦有多少张邮票？',
    finalUnit: '张',
    finalAns: 20,
  },
]

const LESSON: Problem[] = [
  {
    id: '18-L1',
    title: '例1-1 · 和倍基本型',
    tag: 'type1',
    tagLabel: '题型1·和倍问题', difficulty: 1,
    text: '爸爸买了单线本和英语本共 <strong>20 本</strong>，已知单线本的数量是英语本的 <strong>3 倍</strong>，请问爸爸买回的单线本和英语本各多少本？',
    analysis: [
      '英语本是1份，单线本是3份，共 1+3=4份',
      '英语本 = 20 ÷ 4 = <strong>5</strong> 本',
      '单线本 = 5 × 3 = <strong>15</strong> 本',
    ],
    type: 'none',
    finalQ: '英语本有多少本？',
    finalUnit: '本',
    finalAns: 5,
  },
  {
    id: '18-L2',
    title: '例1-2 · 和倍变形',
    tag: 'type2',
    tagLabel: '题型2·和倍变形', difficulty: 2,
    text: '爸爸买了单线本和英语本共 <strong>31 本</strong>，已知单线本的数量比英语本的 <strong>4 倍多 1 本</strong>，请问爸爸买回的单线本和英语本各多少本？',
    analysis: [
      '单线本 = 英语本×4 + 1',
      '去掉多出的1本：31 - 1 = 30，共 1+4=5份',
      '英语本 = 30 ÷ 5 = <strong>6</strong> 本',
      '单线本 = 6 × 4 + 1 = <strong>25</strong> 本',
    ],
    type: 'none',
    finalQ: '英语本有多少本？',
    finalUnit: '本',
    finalAns: 6,
  },
  {
    id: '18-L3',
    title: '练一练 · 和倍变形',
    tag: 'type2',
    tagLabel: '题型2·和倍变形', difficulty: 2,
    text: '立立和妹妹共有 <strong>38 辆</strong>玩具小汽车，已知立立的玩具小汽车数量比妹妹的 <strong>3 倍多 2 辆</strong>，请问立立和妹妹分别有多少辆玩具小汽车？',
    analysis: [
      '立立 = 妹妹×3 + 2',
      '去掉多出的2辆：38 - 2 = 36，共 1+3=4份',
      '妹妹 = 36 ÷ 4 = <strong>9</strong> 辆',
      '立立 = 9 × 3 + 2 = <strong>29</strong> 辆',
    ],
    type: 'none',
    finalQ: '妹妹有多少辆？',
    finalUnit: '辆',
    finalAns: 9,
  },
  {
    id: '18-L4',
    title: '例2 · 和倍变形（少N型）',
    tag: 'type2',
    tagLabel: '题型2·和倍变形', difficulty: 3,
    text: '某校一年级（3）班和（4）班共有学生 <strong>64 人</strong>，（3）班学生人数比（4）班的 <strong>2 倍少 2 人</strong>，请问一年级（3）班和（4）班各有学生多少人？',
    analysis: [
      '（3）班 = （4）班×2 - 2',
      '补上少的2人：64 + 2 = 66，共 1+2=3份',
      '（4）班 = 66 ÷ 3 = <strong>22</strong> 人',
      '（3）班 = 22 × 2 - 2 = <strong>42</strong> 人',
    ],
    type: 'none',
    finalQ: '（4）班有多少人？',
    finalUnit: '人',
    finalAns: 22,
  },
  {
    id: '18-L5',
    title: '练一练 · 和倍变形（少N型）',
    tag: 'type2',
    tagLabel: '题型2·和倍变形', difficulty: 2,
    text: '思思和弟弟一共折了 <strong>30 只</strong>纸鹤，思思折的纸鹤的数量比弟弟的 <strong>4 倍少 5 只</strong>，思思和弟弟各折了多少只纸鹤？',
    analysis: [
      '思思 = 弟弟×4 - 5',
      '补上少的5只：30 + 5 = 35，共 1+4=5份',
      '弟弟 = 35 ÷ 5 = <strong>7</strong> 只',
      '思思 = 7 × 4 - 5 = <strong>23</strong> 只',
    ],
    type: 'none',
    finalQ: '弟弟折了多少只？',
    finalUnit: '只',
    finalAns: 7,
  },
  {
    id: '18-L6',
    title: '例3 · 三量和倍',
    tag: 'type6',
    tagLabel: '题型6·三量和倍', difficulty: 3,
    text: '植树节那天老师要把 <strong>60 棵</strong>小树苗分给甲、乙、丙三位同学，已知甲分到的棵数是乙的 <strong>3 倍</strong>，丙分到的棵数是甲的 <strong>2 倍</strong>，甲、乙、丙三人各分得多少棵小树苗？',
    analysis: [
      '设乙 = 1份，则甲 = 3份，丙 = 甲×2 = 6份',
      '总份数 = 1 + 3 + 6 = 10份',
      '乙 = 60 ÷ 10 = <strong>6</strong> 棵',
      '甲 = 6 × 3 = 18 棵，丙 = 6 × 6 = 36 棵',
    ],
    type: 'none',
    finalQ: '乙分得多少棵？',
    finalUnit: '棵',
    finalAns: 6,
  },
  {
    id: '18-L7',
    title: '练一练 · 三量和倍',
    tag: 'type6',
    tagLabel: '题型6·三量和倍', difficulty: 3,
    text: '立立、纳纳、约约做计算题打卡，一共做对了 <strong>54 道</strong>，纳纳做对的题目数量是立立的 <strong>2 倍</strong>，约约做对的题目数量是纳纳的 <strong>3 倍</strong>，立立、纳纳、约约分别做对了几道题？',
    analysis: [
      '设立立 = 1份，则纳纳 = 2份，约约 = 纳纳×3 = 6份',
      '总份数 = 1 + 2 + 6 = 9份',
      '立立 = 54 ÷ 9 = <strong>6</strong> 道',
      '纳纳 = 6 × 2 = 12 道，约约 = 6 × 6 = 36 道',
    ],
    type: 'none',
    finalQ: '立立做对多少道？',
    finalUnit: '道',
    finalAns: 6,
  },
  {
    id: '18-L8',
    title: '例4-1 · 差倍基本型',
    tag: 'type3',
    tagLabel: '题型3·差倍问题', difficulty: 2,
    text: '长方形的长比宽多 <strong>16 厘米</strong>，长是宽的 <strong>5 倍</strong>，这个长方形的长和宽各是多少厘米？',
    analysis: [
      '宽是1份，长是5份，差 = 5-1 = 4份',
      '宽 = 16 ÷ 4 = <strong>4</strong> 厘米',
      '长 = 4 × 5 = <strong>20</strong> 厘米',
    ],
    type: 'none',
    finalQ: '宽是多少厘米？',
    finalUnit: '厘米',
    finalAns: 4,
  },
  {
    id: '18-L9',
    title: '例4-2 · 差倍变形',
    tag: 'type4',
    tagLabel: '题型4·差倍变形', difficulty: 3,
    text: '风风和悦悦两人集邮，风风的邮票数量比悦悦多 <strong>15 张</strong>，风风的邮票数量比悦悦的 <strong>4 倍多 3 张</strong>，那么风风和悦悦各有多少张邮票？',
    analysis: [
      '设悦悦有 x 张，风风 = 4x + 3',
      '风风 - 悦悦 = 15，即 4x + 3 - x = 15',
      '3x = 12，x = <strong>4</strong>（悦悦）',
      '风风 = 4 × 4 + 3 = <strong>19</strong> 张',
    ],
    type: 'none',
    finalQ: '悦悦有多少张邮票？',
    finalUnit: '张',
    finalAns: 4,
  },
  {
    id: '18-L10',
    title: '练一练 · 差倍基本型',
    tag: 'type3',
    tagLabel: '题型3·差倍问题', difficulty: 2,
    text: '妈妈的年龄比奇奇大 <strong>24 岁</strong>，今年妈妈的年龄正好是奇奇年龄的 <strong>3 倍</strong>，今年妈妈多少岁？奇奇多少岁？',
    analysis: [
      '奇奇是1份，妈妈是3份，差 = 3-1 = 2份',
      '奇奇 = 24 ÷ 2 = <strong>12</strong> 岁',
      '妈妈 = 12 × 3 = <strong>36</strong> 岁',
    ],
    type: 'none',
    finalQ: '奇奇多少岁？',
    finalUnit: '岁',
    finalAns: 12,
  },
  {
    id: '18-L11',
    title: '例5 · 差倍变形（少N型）',
    tag: 'type4',
    tagLabel: '题型4·差倍变形', difficulty: 3,
    text: '小猴聪聪比皮皮多 <strong>18 根</strong>香蕉，聪聪的香蕉比皮皮的 <strong>3 倍少 4 根</strong>，聪聪和皮皮各有多少根香蕉？',
    analysis: [
      '设皮皮有 x 根，聪聪 = 3x - 4',
      '聪聪 - 皮皮 = 18，即 3x - 4 - x = 18',
      '2x = 22，x = <strong>11</strong>（皮皮）',
      '聪聪 = 11 × 3 - 4 = <strong>29</strong> 根',
    ],
    type: 'none',
    finalQ: '皮皮有多少根香蕉？',
    finalUnit: '根',
    finalAns: 11,
  },
  {
    id: '18-L12',
    title: '练一练 · 差倍变形（少N型）',
    tag: 'type4',
    tagLabel: '题型4·差倍变形', difficulty: 3,
    text: '秋秋 11 月份比立立多存了 <strong>15 元</strong>，秋秋存的钱比立立的 <strong>4 倍还少 3 元</strong>，请问 11 月份秋秋和立立分别存了多少元钱？',
    analysis: [
      '设立立有 x 元，秋秋 = 4x - 3',
      '秋秋 - 立立 = 15，即 4x - 3 - x = 15',
      '3x = 18，x = <strong>6</strong>（立立）',
      '秋秋 = 6 × 4 - 3 = <strong>21</strong> 元',
    ],
    type: 'none',
    finalQ: '立立存了多少元？',
    finalUnit: '元',
    finalAns: 6,
  },
  {
    id: '18-L13',
    title: '例6 · 移动变倍',
    tag: 'type5',
    tagLabel: '题型5·移动变倍', difficulty: 3,
    text: '甲筐大鸭梨的重量是乙筐的 <strong>4 倍</strong>，如果从甲筐取出 <strong>60 千克</strong>放入乙筐，那么两筐大鸭梨重量就相等，两筐大鸭梨原来各有多少千克？',
    analysis: [
      '设乙筐原来有 x 千克，甲筐 = 4x',
      '取出60千克后相等：4x - 60 = x + 60',
      '3x = 120，x = <strong>40</strong>（乙筐）',
      '甲筐 = 40 × 4 = <strong>160</strong> 千克',
    ],
    type: 'none',
    finalQ: '乙筐原来有多少千克？',
    finalUnit: '千克',
    finalAns: 40,
  },
  {
    id: '18-L14',
    title: '练一练 · 移动变倍',
    tag: 'type5',
    tagLabel: '题型5·移动变倍', difficulty: 3,
    text: '立立和爸爸一起去果园摘草莓，爸爸摘得的草莓数是立立的 <strong>5 倍</strong>，如果爸爸分 <strong>12 颗</strong>给立立，那么两人的草莓数量就相等，请问立立和爸爸各自摘了多少颗草莓？',
    analysis: [
      '设立立原来有 x 颗，爸爸 = 5x',
      '爸爸给立立12颗后相等：5x - 12 = x + 12',
      '4x = 24，x = <strong>6</strong>（立立）',
      '爸爸 = 6 × 5 = <strong>30</strong> 颗',
    ],
    type: 'none',
    finalQ: '立立摘了多少颗？',
    finalUnit: '颗',
    finalAns: 6,
  },
]

const HOMEWORK: Problem[] = [
  {
    id: '18-H1',
    title: '巩固1 · 和倍基本型',
    tag: 'type1',
    tagLabel: '题型1·和倍问题', difficulty: 1,
    text: '果园里有桃树和梨树共 <strong>35 棵</strong>，桃树的棵数是梨树的 <strong>4 倍</strong>，两种果树各有多少棵？',
    analysis: [
      '梨树是1份，桃树是4份，共 1+4=5份',
      '梨树 = 35 ÷ 5 = <strong>7</strong> 棵',
      '桃树 = 7 × 4 = <strong>28</strong> 棵',
    ],
    type: 'none',
    finalQ: '梨树有多少棵？',
    finalUnit: '棵',
    finalAns: 7,
  },
  {
    id: '18-H2',
    title: '巩固2 · 和倍变形',
    tag: 'type2',
    tagLabel: '题型2·和倍变形', difficulty: 2,
    text: '甲、乙两个工程队共有 <strong>57 人</strong>，甲队人数比乙队人数的 <strong>4 倍还多 2 人</strong>，求甲、乙两队各有多少人？',
    analysis: [
      '甲队 = 乙队×4 + 2',
      '去掉多出的2人：57 - 2 = 55，共 1+4=5份',
      '乙队 = 55 ÷ 5 = <strong>11</strong> 人',
      '甲队 = 11 × 4 + 2 = <strong>46</strong> 人',
    ],
    type: 'none',
    finalQ: '乙队有多少人？',
    finalUnit: '人',
    finalAns: 11,
  },
  {
    id: '18-H3',
    title: '巩固3 · 和倍变形（少N型）',
    tag: 'type2',
    tagLabel: '题型2·和倍变形', difficulty: 2,
    text: '学校将 <strong>76 本</strong>图书分给二、三两个年级，已知三年级所分得的本数比二年级的 <strong>3 倍还少 4 本</strong>，问二、三年级各分得多少本图书？',
    analysis: [
      '三年级 = 二年级×3 - 4',
      '补上少的4本：76 + 4 = 80，共 1+3=4份',
      '二年级 = 80 ÷ 4 = <strong>20</strong> 本',
      '三年级 = 20 × 3 - 4 = <strong>56</strong> 本',
    ],
    type: 'none',
    finalQ: '二年级分得多少本？',
    finalUnit: '本',
    finalAns: 20,
  },
  {
    id: '18-H4',
    title: '巩固4 · 差倍基本型',
    tag: 'type3',
    tagLabel: '题型3·差倍问题', difficulty: 2,
    text: '饲养场里养的白兔比灰兔多 <strong>32 只</strong>，已知白兔的只数是灰兔的 <strong>5 倍</strong>，求白兔、灰兔各养了多少只？',
    analysis: [
      '灰兔是1份，白兔是5份，差 = 5-1 = 4份',
      '灰兔 = 32 ÷ 4 = <strong>8</strong> 只',
      '白兔 = 8 × 5 = <strong>40</strong> 只',
    ],
    type: 'none',
    finalQ: '灰兔有多少只？',
    finalUnit: '只',
    finalAns: 8,
  },
  {
    id: '18-H5',
    title: '巩固5 · 差倍变形',
    tag: 'type4',
    tagLabel: '题型4·差倍变形', difficulty: 3,
    text: '便利店里的牛奶比酸奶多 <strong>15 箱</strong>，已知牛奶的数量比酸奶的 <strong>4 倍还少 3 箱</strong>，便利店的牛奶和酸奶各多少箱？',
    analysis: [
      '设酸奶有 x 箱，牛奶 = 4x - 3',
      '牛奶 - 酸奶 = 15，即 4x - 3 - x = 15',
      '3x = 18，x = <strong>6</strong>（酸奶）',
      '牛奶 = 6 × 4 - 3 = <strong>21</strong> 箱',
    ],
    type: 'none',
    finalQ: '酸奶有多少箱？',
    finalUnit: '箱',
    finalAns: 6,
  },
  {
    id: '18-H6',
    title: '巩固6 · 移动变倍',
    tag: 'type5',
    tagLabel: '题型5·移动变倍', difficulty: 3,
    text: '甲仓存粮吨数是乙仓的 <strong>5 倍</strong>，如果从甲仓中运出 <strong>80 吨</strong>粮食到乙仓，甲、乙两个粮仓存粮吨数正好相等。甲、乙两个粮仓原来各存粮多少吨？',
    analysis: [
      '设乙仓原来有 x 吨，甲仓 = 5x',
      '运出80吨后相等：5x - 80 = x + 80',
      '4x = 160，x = <strong>40</strong>（乙仓）',
      '甲仓 = 40 × 5 = <strong>200</strong> 吨',
    ],
    type: 'none',
    finalQ: '乙仓原来有多少吨？',
    finalUnit: '吨',
    finalAns: 40,
  },
]

const WORKBOOK: Problem[] = [
  {
    id: '18-W1',
    title: '闯关1 · 和倍基本型',
    tag: 'type1',
    tagLabel: '题型1·和倍问题', difficulty: 1,
    text: '用锡和铝制成 <strong>60 千克</strong>的合金，铝的重量是锡的 <strong>3 倍</strong>，锡和铝各用了多少千克？',
    analysis: [
      '锡是1份，铝是3份，共 1+3=4份',
      '锡 = 60 ÷ 4 = <strong>15</strong> 千克',
      '铝 = 15 × 3 = <strong>45</strong> 千克',
    ],
    type: 'none',
    finalQ: '锡用了多少千克？',
    finalUnit: '千克',
    finalAns: 15,
  },
  {
    id: '18-W2',
    title: '闯关2 · 和倍变形',
    tag: 'type2',
    tagLabel: '题型2·和倍变形', difficulty: 2,
    text: '姐妹二人共有 <strong>89 元</strong>零用钱，已知姐姐的零用钱比妹妹的 <strong>3 倍多 5 元</strong>，请问姐妹二人各存款多少元？',
    analysis: [
      '姐姐 = 妹妹×3 + 5',
      '去掉多出的5元：89 - 5 = 84，共 1+3=4份',
      '妹妹 = 84 ÷ 4 = <strong>21</strong> 元',
      '姐姐 = 21 × 3 + 5 = <strong>68</strong> 元',
    ],
    type: 'none',
    finalQ: '妹妹有多少元？',
    finalUnit: '元',
    finalAns: 21,
  },
  {
    id: '18-W3',
    title: '闯关3 · 和倍变形（少N型）',
    tag: 'type2',
    tagLabel: '题型2·和倍变形', difficulty: 2,
    text: 'A、B 两个篮球队的成员一共 <strong>34 人</strong>，A 队的人数比 B 队的 <strong>3 倍还少 2 人</strong>，请问 A、B 两个篮球队分别有多少人？',
    analysis: [
      'A队 = B队×3 - 2',
      '补上少的2人：34 + 2 = 36，共 1+3=4份',
      'B队 = 36 ÷ 4 = <strong>9</strong> 人',
      'A队 = 9 × 3 - 2 = <strong>25</strong> 人',
    ],
    type: 'none',
    finalQ: 'B队有多少人？',
    finalUnit: '人',
    finalAns: 9,
  },
  {
    id: '18-W4',
    title: '闯关4 · 差倍基本型',
    tag: 'type3',
    tagLabel: '题型3·差倍问题', difficulty: 2,
    text: '思思的铅笔比奇奇多 <strong>12 支</strong>，思思铅笔的数量是奇奇的 <strong>3 倍</strong>，请问思思和奇奇分别有多少支铅笔？',
    analysis: [
      '奇奇是1份，思思是3份，差 = 3-1 = 2份',
      '奇奇 = 12 ÷ 2 = <strong>6</strong> 支',
      '思思 = 6 × 3 = <strong>18</strong> 支',
    ],
    type: 'none',
    finalQ: '奇奇有多少支铅笔？',
    finalUnit: '支',
    finalAns: 6,
  },
  {
    id: '18-W5',
    title: '闯关5 · 差倍变形（多N型）',
    tag: 'type4',
    tagLabel: '题型4·差倍变形', difficulty: 3,
    text: '教务老师买来的 A4 纸比 A3 纸多 <strong>14 箱</strong>，A4 纸的箱数比 A3 纸的 <strong>3 倍还多 4 箱</strong>，请问 A4 纸有多少箱？A3 纸有多少箱？',
    analysis: [
      '设 A3 纸有 x 箱，A4 纸 = 3x + 4',
      'A4 - A3 = 14，即 3x + 4 - x = 14',
      '2x = 10，x = <strong>5</strong>（A3）',
      'A4 = 5 × 3 + 4 = <strong>19</strong> 箱',
    ],
    type: 'none',
    finalQ: 'A3 纸有多少箱？',
    finalUnit: '箱',
    finalAns: 5,
  },
  {
    id: '18-W6',
    title: '闯关6 · 差倍变形（少N型）',
    tag: 'type4',
    tagLabel: '题型4·差倍变形', difficulty: 3,
    text: '秋秋买的兰花比月季多 <strong>17 朵</strong>，已知兰花的朵数比月季的 <strong>3 倍少 1 朵</strong>，秋秋买了兰花多少朵？月季多少朵？',
    analysis: [
      '设月季有 x 朵，兰花 = 3x - 1',
      '兰花 - 月季 = 17，即 3x - 1 - x = 17',
      '2x = 18，x = <strong>9</strong>（月季）',
      '兰花 = 9 × 3 - 1 = <strong>26</strong> 朵',
    ],
    type: 'none',
    finalQ: '月季有多少朵？',
    finalUnit: '朵',
    finalAns: 9,
  },
  {
    id: '18-W7',
    title: '闯关7 · 移动变倍',
    tag: 'type5',
    tagLabel: '题型5·移动变倍', difficulty: 3,
    text: '大桶油的重量是小桶油的 <strong>3 倍</strong>，如果把大桶中 <strong>6 千克</strong>油倒入小桶，那么两桶油重量相等，问这两桶油原来的重量各多少千克？',
    analysis: [
      '设小桶原来有 x 千克，大桶 = 3x',
      '倒入6千克后相等：3x - 6 = x + 6',
      '2x = 12，x = <strong>6</strong>（小桶）',
      '大桶 = 6 × 3 = <strong>18</strong> 千克',
    ],
    type: 'none',
    finalQ: '小桶原来有多少千克？',
    finalUnit: '千克',
    finalAns: 6,
  },
  {
    id: '18-W8',
    title: '闯关8 · 移动变倍（同减型）',
    tag: 'type5',
    tagLabel: '题型5·移动变倍', difficulty: 4,
    text: '欢欢家有 <strong>30 本</strong>课外书，乐乐家有 <strong>10 本</strong>课外书，两人都捐出同样多的课外书后，欢欢家剩下的课外书是乐乐家剩下课外书的 <strong>5 倍</strong>，两人都捐出了几本书？',
    analysis: [
      '设各捐出 x 本，则剩余：欢欢 30-x，乐乐 10-x',
      '(30-x) = 5×(10-x)',
      '30 - x = 50 - 5x',
      '4x = 20，x = <strong>5</strong> 本',
    ],
    type: 'none',
    finalQ: '两人各捐出多少本？',
    finalUnit: '本',
    finalAns: 5,
  },
  {
    id: '18-W9',
    title: '闯关9 · 移动变倍',
    tag: 'type5',
    tagLabel: '题型5·移动变倍', difficulty: 3,
    text: '欢欢和乐乐一起去果园摘桃子，欢欢摘的桃子数量是乐乐的 <strong>4 倍</strong>，如果欢欢给乐乐 <strong>12 个</strong>桃子，那么两人的桃子数量就相等，请问欢欢和乐乐各摘了几个桃子？',
    analysis: [
      '设乐乐原来有 x 个，欢欢 = 4x',
      '欢欢给乐乐12个后相等：4x - 12 = x + 12',
      '3x = 24，x = <strong>8</strong>（乐乐）',
      '欢欢 = 8 × 4 = <strong>32</strong> 个',
    ],
    type: 'none',
    finalQ: '乐乐摘了多少个？',
    finalUnit: '个',
    finalAns: 8,
  },
  {
    id: '18-W10',
    title: '闯关10 · 三量和倍',
    tag: 'type6',
    tagLabel: '题型6·三量和倍', difficulty: 3,
    text: '仓库里存有面粉、大米和小米共 <strong>120 吨</strong>，已知面粉的重量是小米的 <strong>3 倍</strong>，大米的重量是面粉的 <strong>2 倍</strong>，仓库里存有面粉、大米和小米各多少吨？',
    analysis: [
      '设小米 = 1份，面粉 = 3份，大米 = 面粉×2 = 6份',
      '总份数 = 1 + 3 + 6 = 10份',
      '小米 = 120 ÷ 10 = 12 吨',
      '面粉 = 12 × 3 = <strong>36</strong> 吨，大米 = 12 × 6 = 72 吨',
    ],
    type: 'none',
    finalQ: '面粉有多少吨？',
    finalUnit: '吨',
    finalAns: 36,
  },
  {
    id: '18-W11',
    title: '闯关11 · 三量和倍（变形）',
    tag: 'type6',
    tagLabel: '题型6·三量和倍', difficulty: 4,
    text: '欢欢、乐乐、贝贝暑假完成了学校布置的暑假作业，总页数是 <strong>40 页</strong>，其中乐乐完成的页数是欢欢的 <strong>2 倍</strong>，欢欢完成的页数比贝贝的 <strong>2 倍少 3 页</strong>，三人分别完成了多少页暑假作业？',
    analysis: [
      '设贝贝 = x 页，欢欢 = 2x-3，乐乐 = (2x-3)×2 = 4x-6',
      '总量：x + (2x-3) + (4x-6) = 40',
      '7x - 9 = 40，x = <strong>7</strong>（贝贝）',
      '欢欢 = 11 页，乐乐 = 22 页',
    ],
    type: 'none',
    finalQ: '贝贝完成了多少页？',
    finalUnit: '页',
    finalAns: 7,
  },
  {
    id: '18-W12',
    title: '闯关12 · 三量和倍（综合）',
    tag: 'type6',
    tagLabel: '题型6·三量和倍', difficulty: 4,
    text: '欢欢家买了一些故事书、漫画书和科技书共 <strong>103 本</strong>，其中漫画书的数量是科技书的 <strong>3 倍</strong>，故事书的数量比漫画书的 <strong>2 倍还多 3 本</strong>，三种书各买了多少本？',
    analysis: [
      '设科技书 = x 本，漫画书 = 3x，故事书 = 6x+3',
      '总量：x + 3x + (6x+3) = 103',
      '10x + 3 = 103，x = <strong>10</strong>（科技书）',
      '漫画书 = 30 本，故事书 = 63 本',
    ],
    type: 'none',
    finalQ: '科技书有多少本？',
    finalUnit: '本',
    finalAns: 10,
  },
]

export const PROBLEMS: ProblemSet = {
  pretest: PRETEST,
  lesson: LESSON,
  homework: HOMEWORK,
  workbook: WORKBOOK,
}

export const PROBLEM_TYPES = [
  {
    tag: 'type1',
    color: 'blue',
    label: '题型1·和倍问题',
    desc: '总量÷(倍数+1)=小量，小量×倍数=大量。',
    example: '例：共20本，单线是英语3倍→英语=20÷4=5',
  },
  {
    tag: 'type2',
    color: 'green',
    label: '题型2·和倍变形',
    desc: '总量中含"多N个"或"少N个"时，先调整再求份数。',
    example: '例：共31，单线比英语4倍多1→(31-1)÷5=6',
  },
  {
    tag: 'type3',
    color: 'orange',
    label: '题型3·差倍问题',
    desc: '差÷(倍数-1)=小量，小量×倍数=大量。',
    example: '例：差16，长是宽5倍→宽=16÷4=4',
  },
  {
    tag: 'type4',
    color: 'purple',
    label: '题型4·差倍变形',
    desc: '差中含"多N"或"少N"时，先调整再除(倍数-1)。',
    example: '例：差15，4倍多3→(15-3)÷3=4',
  },
  {
    tag: 'type5',
    color: 'red',
    label: '题型5·移动变倍',
    desc: '通过移动N个使一方变为另一方的K倍，建立方程。',
    example: '例：甲给乙N个后甲是乙K倍',
  },
  {
    tag: 'type6',
    color: 'pink',
    label: '题型6·三量和倍',
    desc: '三个量互有倍数关系，化成最小份数统一计算。',
    example: '例：甲=乙×3，丙=甲×2→总=1+3+6=10份',
  },
]

export const TYPE_STYLE: Record<
  string,
  { bg: string; border: string; titleColor: string; textColor: string }
> = {
  type1: {
    bg: 'bg-blue-50',
    border: 'border-l-blue-500',
    titleColor: 'text-blue-800',
    textColor: 'text-blue-900',
  },
  type2: {
    bg: 'bg-green-50',
    border: 'border-l-green-500',
    titleColor: 'text-green-800',
    textColor: 'text-green-900',
  },
  type3: {
    bg: 'bg-orange-50',
    border: 'border-l-orange-500',
    titleColor: 'text-orange-800',
    textColor: 'text-orange-900',
  },
  type4: {
    bg: 'bg-purple-50',
    border: 'border-l-purple-500',
    titleColor: 'text-purple-800',
    textColor: 'text-purple-900',
  },
  type5: {
    bg: 'bg-red-50',
    border: 'border-l-red-500',
    titleColor: 'text-red-800',
    textColor: 'text-red-900',
  },
  type6: {
    bg: 'bg-pink-50',
    border: 'border-l-pink-500',
    titleColor: 'text-pink-800',
    textColor: 'text-pink-900',
  },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-blue-100 text-blue-800',
  type2: 'bg-green-100 text-green-800',
  type3: 'bg-orange-100 text-orange-800',
  type4: 'bg-purple-100 text-purple-800',
  type5: 'bg-red-100 text-red-800',
  type6: 'bg-pink-100 text-pink-800',
}
