import type { Problem, ProblemSet } from '@rosie/core'

const PRETEST: Problem[] = [
  {
    id: '30-P1',
    title: '课前测1 · 三种球各多少',
    tag: 'type3',
    tagLabel: '题型3·三量和倍', difficulty: 3,
    text: '体育室买来 <strong>75</strong> 个球，其中篮球是足球的 <strong>2</strong> 倍，排球比足球多 <strong>3</strong> 个，这三种球各多少个？',
    analysis: [
      '设足球 = x 个',
      '篮球 = 2x，排球 = x + 3',
      '足球 + 篮球 + 排球 = x + 2x + (x+3) = 4x + 3 = 75',
      '4x = 72，x = 18，即足球 = <strong>18</strong> 个',
      '篮球 = 36 个，排球 = 21 个',
    ],
    type: 'none',
    finalQ: '足球有多少个？',
    finalUnit: '个',
    finalAns: 18,
  },
  {
    id: '30-P2',
    title: '课前测2 · 被除数是多少',
    tag: 'type1',
    tagLabel: '题型1·特殊和差关系', difficulty: 3,
    text: '两个自然数相除，商是 <strong>4</strong>，余数是 <strong>1</strong>，如果被除数、除数、商及余数的和是 <strong>46</strong>，那么被除数是多少？',
    analysis: [
      '被除数 = 除数 × 4 + 1',
      '被除数 + 除数 + 商 + 余数 = 46',
      '即：(4×除数+1) + 除数 + 4 + 1 = 46',
      '5×除数 + 6 = 46，除数 = 8',
      '被除数 = 4×8 + 1 = <strong>33</strong>',
    ],
    type: 'none',
    finalQ: '被除数是多少？',
    finalUnit: '',
    finalAns: 33,
  },
  {
    id: '30-P3',
    title: '课前测3 · 第三根绳多长',
    tag: 'type2',
    tagLabel: '题型2·三量和差', difficulty: 2,
    text: '有三根绳子，共长 <strong>68</strong> 米，第一根比第二根长 <strong>7</strong> 米，第二根比第三根长 <strong>8</strong> 米，那么这三根绳子各长多少米？',
    analysis: [
      '设第三根 = x 米',
      '第二根 = x + 8，第一根 = x + 15',
      'x + (x+8) + (x+15) = 3x + 23 = 68',
      '3x = 45，x = <strong>15</strong>（第三根）',
      '第二根 = 23 米，第一根 = 30 米',
    ],
    type: 'none',
    finalQ: '第三根绳子多长？',
    finalUnit: '米',
    finalAns: 15,
  },
  {
    id: '30-P4',
    title: '课前测4 · 丁数是多少',
    tag: 'type3',
    tagLabel: '题型3·三量和倍', difficulty: 3,
    text: '甲数是乙数的 <strong>3</strong> 倍，丙数是乙数的 <strong>4</strong> 倍，丁数是丙数的一半，四个数的和是 <strong>100</strong>，丁数是多少？',
    analysis: [
      '设乙 = x',
      '甲 = 3x，丙 = 4x，丁 = 2x',
      '3x + x + 4x + 2x = 10x = 100',
      'x = 10，丁 = 2x = <strong>20</strong>',
    ],
    type: 'none',
    finalQ: '丁数是多少？',
    finalUnit: '',
    finalAns: 20,
  },
  {
    id: '30-P5',
    title: '课前测5 · 丙物体多重',
    tag: 'type4',
    tagLabel: '题型4·三量差倍', difficulty: 4,
    text: '三个物体的总重量是 <strong>63</strong> 千克，甲物体比乙丙两个物体重量之和轻 <strong>1</strong> 千克，乙物体比丙物体重量的 <strong>2</strong> 倍还重 <strong>2</strong> 千克，三个物体各重多少千克？',
    analysis: [
      '甲 = 乙 + 丙 − 1，设丙 = x',
      '乙 = 2x + 2，甲 = (2x+2) + x − 1 = 3x + 1',
      '总 = (3x+1) + (2x+2) + x = 6x + 3 = 63',
      '6x = 60，x = <strong>10</strong>（丙）',
      '乙 = 22 千克，甲 = 31 千克',
    ],
    type: 'none',
    finalQ: '丙物体多少千克？',
    finalUnit: '千克',
    finalAns: 10,
  },
]

const LESSON: Problem[] = [
  {
    id: '30-L1',
    title: '例1 · 被减数是多少',
    tag: 'type1',
    tagLabel: '题型1·特殊和差关系', difficulty: 3,
    text: '在一个减法算式中，被减数、减数、差的和是 <strong>80</strong>，而减数比差大 <strong>10</strong>，那么被减数是多少？',
    analysis: [
      '被减数 = 减数 + 差（减法关系）',
      '设差 = d，则减数 = d + 10',
      '被减数 = (d+10) + d = 2d + 10',
      '总和：(2d+10) + (d+10) + d = 4d + 20 = 80',
      '4d = 60，d = 15（差），减数 = 25',
      '被减数 = 25 + 15 = <strong>40</strong>',
    ],
    type: 'none',
    finalQ: '被减数是多少？',
    finalUnit: '',
    finalAns: 40,
  },
  {
    id: '30-L2',
    title: '练一练 · 差是多少',
    tag: 'type1',
    tagLabel: '题型1·特殊和差关系', difficulty: 2,
    text: '在一个减法算式中，被减数、减数与差的和是 <strong>34</strong>，而减数比差小 <strong>5</strong>，请问差是几？',
    analysis: [
      '设差 = d，减数 = d − 5',
      '被减数 = 减数 + 差 = (d−5) + d = 2d − 5',
      '总和：(2d−5) + (d−5) + d = 4d − 10 = 34',
      '4d = 44，d = <strong>11</strong>（差）',
      '减数 = 6，被减数 = 17，验证：17+6+11=34 ✓',
    ],
    type: 'none',
    finalQ: '差是多少？',
    finalUnit: '',
    finalAns: 11,
  },
  {
    id: '30-L3',
    title: '例2 · 语文小组有多少人',
    tag: 'type2',
    tagLabel: '题型2·三量和差', difficulty: 3,
    text: '语文、数学、英语三个兴趣小组共有 <strong>180</strong> 人，语文、数学两个小组人数之和比英语小组多 <strong>20</strong> 人，语文小组比数学小组少 <strong>40</strong> 人，请问语文小组有多少人？',
    analysis: [
      '语文 + 数学 + 英语 = 180',
      '语文 + 数学 = 英语 + 20，代入得：英语 + 20 + 英语 = 180 → 英语 = 80',
      '语文 + 数学 = 100',
      '语文 = 数学 − 40，代入：(数学−40) + 数学 = 100 → 数学 = 70',
      '语文 = 70 − 40 = <strong>30</strong>',
    ],
    type: 'none',
    finalQ: '语文组有多少人？',
    finalUnit: '人',
    finalAns: 30,
  },
  {
    id: '30-L4',
    title: '练一练 · 杏树有多少棵',
    tag: 'type2',
    tagLabel: '题型2·三量和差', difficulty: 3,
    text: '果园里桃树、杏树和梨树共 <strong>59</strong> 棵，其中桃树比杏树多 <strong>2</strong> 棵，梨树比桃树和杏树的总数少 <strong>9</strong> 棵，那么桃树、杏树和梨树各有多少棵？',
    analysis: [
      '设杏树 = x，桃树 = x + 2',
      '梨树 = (x + x+2) − 9 = 2x − 7',
      '总：x + (x+2) + (2x−7) = 4x − 5 = 59',
      '4x = 64，x = <strong>16</strong>（杏树）',
      '桃树 = 18 棵，梨树 = 25 棵',
    ],
    type: 'none',
    finalQ: '杏树有多少棵？',
    finalUnit: '棵',
    finalAns: 16,
  },
  {
    id: '30-L5',
    title: '例3 · 乙粮仓有多少吨',
    tag: 'type3',
    tagLabel: '题型3·三量和倍', difficulty: 3,
    text: '甲、乙、丙三个粮仓共有大米 <strong>78</strong> 吨，甲粮仓的吨数比乙粮仓的 <strong>3</strong> 倍多 <strong>2</strong> 吨，乙粮仓的吨数又比丙粮仓的 <strong>2</strong> 倍多 <strong>1</strong> 吨，那么三个粮仓各有多少吨大米？',
    analysis: [
      '设丙 = x，乙 = 2x + 1',
      '甲 = 3×(2x+1) + 2 = 6x + 5',
      '总：x + (2x+1) + (6x+5) = 9x + 6 = 78',
      '9x = 72，x = 8（丙），乙 = 2×8+1 = <strong>17</strong>',
      '甲 = 6×8+5 = 53 吨，验证：8+17+53=78 ✓',
    ],
    type: 'none',
    finalQ: '乙粮仓有多少吨？',
    finalUnit: '吨',
    finalAns: 17,
  },
  {
    id: '30-L6',
    title: '练一练 · 第一组比第三组多多少人',
    tag: 'type3',
    tagLabel: '题型3·三量和倍', difficulty: 4,
    text: '纳约组织同学们冬令营，分为三个小组，共有 <strong>205</strong> 人。第一组人数比第二组人数的 <strong>2</strong> 倍多 <strong>2</strong> 人，而第二组的人数比第三组的 <strong>3</strong> 倍多 <strong>1</strong> 人。请问第一组比第三组多多少人？',
    analysis: [
      '设第三组 = x，第二组 = 3x + 1',
      '第一组 = 2×(3x+1) + 2 = 6x + 4',
      '总：x + (3x+1) + (6x+4) = 10x + 5 = 205',
      '10x = 200，x = 20（第三组）',
      '第二组 = 61，第一组 = 124',
      '第一组 − 第三组 = 124 − 20 = <strong>104</strong>',
    ],
    type: 'none',
    finalQ: '第一组比第三组多多少人？',
    finalUnit: '人',
    finalAns: 104,
  },
  {
    id: '30-L7',
    title: '例4 · 三连比一连多几辆',
    tag: 'type4',
    tagLabel: '题型4·三量差倍', difficulty: 4,
    text: '三个坦克连共有 <strong>145</strong> 辆坦克，二连坦克数量比一连的 <strong>3</strong> 倍少 <strong>1</strong> 辆，三连的坦克数量比二连的 <strong>2</strong> 倍少 <strong>2</strong> 辆，那么三连比一连多几辆坦克？',
    analysis: [
      '设一连 = x，二连 = 3x − 1',
      '三连 = 2×(3x−1) − 2 = 6x − 4',
      '总：x + (3x−1) + (6x−4) = 10x − 5 = 145',
      '10x = 150，x = 15（一连）',
      '二连 = 44，三连 = 86',
      '三连 − 一连 = 86 − 15 = <strong>71</strong>',
    ],
    type: 'none',
    finalQ: '三连比一连多多少辆？',
    finalUnit: '辆',
    finalAns: 71,
  },
  {
    id: '30-L8',
    title: '练一练 · 甲有多少元',
    tag: 'type4',
    tagLabel: '题型4·三量差倍', difficulty: 4,
    text: '甲、乙、丙共有 <strong>99</strong> 元钱，甲的钱比乙的钱的 <strong>2</strong> 倍少 <strong>2</strong> 元，乙的钱比丙的钱的 <strong>3</strong> 倍少 <strong>3</strong> 元。请问甲有多少元钱？',
    analysis: [
      '设丙 = x，乙 = 3x − 3',
      '甲 = 2×(3x−3) − 2 = 6x − 8',
      '总：x + (3x−3) + (6x−8) = 10x − 11 = 99',
      '10x = 110，x = 11（丙）',
      '乙 = 30 元，甲 = 6×11−8 = <strong>58</strong> 元',
    ],
    type: 'none',
    finalQ: '甲有多少元？',
    finalUnit: '元',
    finalAns: 58,
  },
  {
    id: '30-L9',
    title: '例5 · 课外活动共多少人',
    tag: 'type5',
    tagLabel: '题型5·特殊变形', difficulty: 4,
    text: '一年级学生参加课外活动，其中做游戏的人数最多，既是跳绳人数的 <strong>2</strong> 倍，又是打球人数的 <strong>5</strong> 倍，如果跳绳比打球的多 <strong>30</strong> 人，请问参加课外活动的共有多少人？',
    analysis: [
      '设打球 = x，跳绳 = x + 30',
      '游戏 = 跳绳 × 2 = 2(x+30) = 2x + 60',
      '游戏也 = 打球 × 5 = 5x',
      '5x = 2x + 60 → 3x = 60 → x = 20（打球）',
      '跳绳 = 50，游戏 = 100',
      '总人数 = 20 + 50 + 100 = <strong>170</strong>',
    ],
    type: 'none',
    finalQ: '参加课外活动共多少人？',
    finalUnit: '人',
    finalAns: 170,
  },
  {
    id: '30-L10',
    title: '练一练 · 一共有多少盆花',
    tag: 'type5',
    tagLabel: '题型5·特殊变形', difficulty: 4,
    text: '学校门口放有红、黄、蓝三种颜色的花，其中黄花的盆数最多，既是红花盆数的 <strong>3</strong> 倍，也是蓝花盆数的 <strong>4</strong> 倍，如果红花比蓝花多 <strong>30</strong> 盆，请问学校门口一共有多少盆花？',
    analysis: [
      '设蓝花 = x，红花 = x + 30',
      '黄花 = 红花 × 3 = 3(x+30) = 3x + 90',
      '黄花也 = 蓝花 × 4 = 4x',
      '4x = 3x + 90 → x = 90（蓝花）',
      '红花 = 120，黄花 = 360',
      '总 = 90 + 120 + 360 = <strong>570</strong>',
    ],
    type: 'none',
    finalQ: '一共有多少盆花？',
    finalUnit: '盆',
    finalAns: 570,
  },
  {
    id: '30-L11',
    title: '例6 · 文具盒里共多少支笔',
    tag: 'type6',
    tagLabel: '题型6·综合变形', difficulty: 4,
    text: '纳纳的文具盒里铅笔的数量是钢笔的 <strong>2</strong> 倍，圆珠笔的数量恰好是铅笔数和钢笔数之和，如果有 <strong>1</strong> 支圆珠笔变成了铅笔，那么圆珠笔和铅笔将一样多，请问纳纳的文具盒里一共有多少支笔？',
    analysis: [
      '设钢笔 = x，铅笔 = 2x，圆珠笔 = 3x',
      '1支圆珠变铅笔后：圆珠−1 = 铅笔+1',
      '3x − 1 = 2x + 1 → x = 2（钢笔）',
      '铅笔 = 4，圆珠笔 = 6',
      '总 = 2 + 4 + 6 = <strong>12</strong>',
    ],
    type: 'none',
    finalQ: '文具盒里共多少支笔？',
    finalUnit: '支',
    finalAns: 12,
  },
  {
    id: '30-L12',
    title: '练一练 · 绿纸鹤多少个',
    tag: 'type6',
    tagLabel: '题型6·综合变形', difficulty: 4,
    text: '悦悦折了红、黄、绿三种颜色的纸鹤，已知黄纸鹤的只数是红纸鹤的 <strong>3</strong> 倍，绿纸鹤的只数恰好是红纸鹤和黄纸鹤只数之和，如果把 <strong>2</strong> 只绿纸鹤变成了黄纸鹤，那么黄纸鹤和绿纸鹤将一样多，请问悦悦折了多少个绿纸鹤？',
    analysis: [
      '设红 = x，黄 = 3x，绿 = x+3x = 4x',
      '2只绿变黄后，黄+2 = 绿−2',
      '3x + 2 = 4x − 2 → x = 4（红）',
      '黄 = 12，绿 = 4×4 = <strong>16</strong>',
      '验证：黄+2 = 14，绿−2 = 14，相等 ✓',
    ],
    type: 'none',
    finalQ: '悦悦折了多少个绿纸鹤？',
    finalUnit: '个',
    finalAns: 16,
  },
]

const HOMEWORK: Problem[] = []

const WORKBOOK: Problem[] = [
  {
    id: '30-W1',
    title: '闯关1 · 一班捐了多少本',
    tag: 'type2',
    tagLabel: '题型2·三量和差', difficulty: 3,
    text: '纳约小学发动全校同学给山区学生捐书，一(1)班、一(2)班、一(3)班三个班共捐书 <strong>300</strong> 本，一(1)班、一(2)班两个班捐书总数比一(3)班多 <strong>60</strong> 本，如果一(3)班拿出 <strong>20</strong> 本给一(2)班，则两个班捐书数目相等。请问三个班各捐了多少本书？',
    analysis: [
      '一(1)+一(2) = 一(3)+60，代入总和：(一(3)+60)+一(3)=300',
      '2×一(3) = 240，一(3) = 120，一(1)+一(2) = 180',
      '一(3)拿20给一(2)后相等：一(3)−20 = 一(2)+20',
      '120−20 = 100 = 一(2)+20，一(2) = 80',
      '一(1) = 180 − 80 = <strong>100</strong>，一(2) = 80，一(3) = 120',
    ],
    type: 'none',
    finalQ: '一班捐了多少本？',
    finalUnit: '本',
    finalAns: 100,
  },
  {
    id: '30-W2',
    title: '闯关2 · 上层放书多少本',
    tag: 'type2',
    tagLabel: '题型2·三量和差', difficulty: 2,
    text: '一个三层书架共放书 <strong>96</strong> 本。上层比中层多放 <strong>11</strong> 本，下层比中层少放 <strong>5</strong> 本，上、中、下三层各放书多少本？',
    analysis: [
      '设中层 = x，上层 = x + 11，下层 = x − 5',
      '总：x + (x+11) + (x−5) = 3x + 6 = 96',
      '3x = 90，x = 30（中层）',
      '上层 = 30 + 11 = <strong>41</strong> 本，下层 = 25 本',
    ],
    type: 'none',
    finalQ: '上层放书多少本？',
    finalUnit: '本',
    finalAns: 41,
  },
  {
    id: '30-W3',
    title: '闯关3 · 最后留下多少人',
    tag: 'type2',
    tagLabel: '题型2·三量和差', difficulty: 3,
    text: '一辆公共汽车出发时有 <strong>48</strong> 人，到达第一站时有若干人下车，下车的比留下的多 <strong>8</strong> 人。到达第二站时又有人下车，这次下车的比留下的少 <strong>8</strong> 人，请问最后有多少个人留在了车上？（每个车站都无人上车）',
    analysis: [
      '第一站：下车+留下=48，下车−留下=8',
      '下车 = (48+8)÷2 = 28，留下 = 20',
      '第二站：下车+留下=20，留下−下车=8',
      '留下 = (20+8)÷2 = <strong>14</strong>',
    ],
    type: 'none',
    finalQ: '最后留下多少人？',
    finalUnit: '人',
    finalAns: 14,
  },
  {
    id: '30-W4',
    title: '闯关4 · 甲有多少本书',
    tag: 'type2',
    tagLabel: '题型2·三量和差', difficulty: 3,
    text: '甲的书比乙多 <strong>9</strong> 本，比丙多 <strong>2</strong> 本，乙、丙共有书 <strong>47</strong> 本。问：甲、乙、丙各有多少本书？',
    analysis: [
      '设乙 = x，则丙 = x − 7，甲 = x + 9',
      '乙 + 丙 = x + (x−7) = 2x − 7 = 47',
      '2x = 54，x = 27（乙），丙 = 20',
      '甲 = 27 + 9 = <strong>36</strong> 本',
    ],
    type: 'none',
    finalQ: '甲有多少本书？',
    finalUnit: '本',
    finalAns: 36,
  },
  {
    id: '30-W5',
    title: '闯关5 · 胖胖有几块糖',
    tag: 'type3',
    tagLabel: '题型3·三量和倍', difficulty: 1,
    text: '纳纳、约约和胖胖共有 <strong>40</strong> 块糖，纳纳的糖是胖胖的 <strong>2</strong> 倍，约约的糖和胖胖一样多，请问胖胖有几块糖？',
    analysis: [
      '设胖胖 = x，纳纳 = 2x，约约 = x',
      '2x + x + x = 4x = 40',
      'x = <strong>10</strong>（胖胖）',
    ],
    type: 'none',
    finalQ: '胖胖有几块糖？',
    finalUnit: '块',
    finalAns: 10,
  },
  {
    id: '30-W6',
    title: '闯关6 · 被除数是多少',
    tag: 'type1',
    tagLabel: '题型1·特殊和差关系', difficulty: 3,
    text: '两数相除，商 <strong>3</strong> 余 <strong>1</strong>，如果被除数、除数、商及余数相加，和是 <strong>41</strong>，那么被除数和除数分别是多少？',
    analysis: [
      '被除数 = 除数 × 3 + 1',
      '被除数 + 除数 + 商 + 余数 = 41',
      '(3×除数+1) + 除数 + 3 + 1 = 4×除数 + 5 = 41',
      '4×除数 = 36，除数 = 9',
      '被除数 = 3×9 + 1 = <strong>28</strong>',
    ],
    type: 'none',
    finalQ: '被除数是多少？',
    finalUnit: '',
    finalAns: 28,
  },
  {
    id: '30-W7',
    title: '闯关7 · 橘子有多少千克',
    tag: 'type4',
    tagLabel: '题型4·三量差倍', difficulty: 3,
    text: '商店运来橘子、苹果、香蕉共 <strong>53</strong> 千克，橘子的重量比苹果的 <strong>3</strong> 倍少 <strong>3</strong> 千克，香蕉的重量比苹果的 <strong>2</strong> 倍多 <strong>2</strong> 千克，那么商店运来橘子多少千克？',
    analysis: [
      '设苹果 = x，橘子 = 3x − 3，香蕉 = 2x + 2',
      '总：x + (3x−3) + (2x+2) = 6x − 1 = 53',
      '6x = 54，x = 9（苹果）',
      '橘子 = 3×9 − 3 = <strong>24</strong> 千克，香蕉 = 20 千克',
    ],
    type: 'none',
    finalQ: '橘子有多少千克？',
    finalUnit: '千克',
    finalAns: 24,
  },
  {
    id: '30-W8',
    title: '闯关8 · 车+马+炮等于多少',
    tag: 'type3',
    tagLabel: '题型3·三量和倍', difficulty: 4,
    text: '用中国象棋的车马炮分别代表不同的自然数，已知：车÷马 = <strong>2</strong>，炮÷车 = <strong>4</strong>，炮 − 马 = <strong>35</strong>，求"车 + 马 + 炮"等于多少？',
    analysis: [
      '车 = 2×马，炮 = 4×车 = 8×马',
      '炮 − 马 = 8马 − 马 = 7马 = 35',
      '马 = 5，车 = 10，炮 = 40',
      '车 + 马 + 炮 = 10 + 5 + 40 = <strong>55</strong>',
    ],
    type: 'none',
    finalQ: '车+马+炮等于多少？',
    finalUnit: '',
    finalAns: 55,
  },
  {
    id: '30-W9',
    title: '闯关9 · 甲有多少本书',
    tag: 'type5',
    tagLabel: '题型5·特殊变形', difficulty: 4,
    text: '甲、乙各有若干本书，若甲给乙 <strong>45</strong> 本，则二人的书相等；若乙给甲 <strong>45</strong> 本，则甲的本数是乙的 <strong>4</strong> 倍，甲、乙各有书多少本？',
    analysis: [
      '甲给乙45：甲−45 = 乙+45 → 甲−乙 = 90 … ①',
      '乙给甲45：甲+45 = 4×(乙−45) = 4乙−180',
      '甲 − 4乙 = −225 … ②',
      '由①：甲 = 乙+90，代入②：(乙+90)−4乙 = −225',
      '−3乙 = −315，乙 = 105',
      '甲 = 105 + 90 = <strong>195</strong>',
    ],
    type: 'none',
    finalQ: '甲有多少本书？',
    finalUnit: '本',
    finalAns: 195,
  },
  {
    id: '30-W10',
    title: '闯关10 · 魏国军队多少万人',
    tag: 'type3',
    tagLabel: '题型3·三量和倍', difficulty: 3,
    text: '三国时期，魏国、蜀国、吴国三国交战。已知吴国军队比蜀国军队多 <strong>20</strong> 万人；魏国军队人数是吴国的 <strong>2</strong> 倍，又是蜀国的 <strong>3</strong> 倍。魏国军队有多少人？',
    analysis: [
      '设蜀 = x，吴 = x + 20，魏 = 3x',
      '魏 = 2×吴 → 3x = 2×(x+20) = 2x + 40',
      'x = 40（蜀），吴 = 60',
      '魏 = 3×40 = <strong>120</strong> 万人',
    ],
    type: 'none',
    finalQ: '魏国军队有多少万人？',
    finalUnit: '万人',
    finalAns: 120,
  },
  {
    id: '30-W11',
    title: '闯关11 · 三种公鸡共多少只',
    tag: 'type4',
    tagLabel: '题型4·三量差倍', difficulty: 3,
    text: '小丸子家养了一些鸡，红公鸡比黑公鸡多 <strong>13</strong> 只，比白公鸡少 <strong>18</strong> 只，白公鸡的只数是红公鸡的 <strong>2</strong> 倍，请问小丸子家白公鸡、红公鸡、黑公鸡一共多少只？',
    analysis: [
      '设红 = x，白 = 2x，黑 = x − 13',
      '白 = 红 + 18 → 2x = x + 18 → x = 18（红）',
      '白 = 36，黑 = 5',
      '总 = 18 + 36 + 5 = <strong>59</strong>',
    ],
    type: 'none',
    finalQ: '三种公鸡共多少只？',
    finalUnit: '只',
    finalAns: 59,
  },
  {
    id: '30-W12',
    title: '闯关12 · 甲班原有多少人',
    tag: 'type2',
    tagLabel: '题型2·三量和差', difficulty: 4,
    text: '纳约小学三年级有甲、乙、丙 <strong>3</strong> 个班，一共有学生 <strong>72</strong> 人，如果从甲班转出 <strong>2</strong> 个人到乙班，则甲、乙两班人数相同，如果这时再从丙班转出 <strong>3</strong> 个人到乙班，则乙、丙两班人数相同，请问甲班原有多少人？',
    analysis: [
      '甲给乙2人后甲=乙：甲−2 = 乙+2 → 甲 = 乙+4 … ①',
      '此时乙已变为乙+2，丙给乙3人后乙=丙：乙+2 = 丙−3 → 丙 = 乙+5 … ②',
      '甲+乙+丙=72：(乙+4)+乙+(乙+5) = 3乙+9 = 72',
      '3乙 = 63，乙 = 21',
      '甲 = 21+4 = <strong>25</strong>，丙 = 21+5 = 26',
    ],
    type: 'none',
    finalQ: '甲班原有多少人？',
    finalUnit: '人',
    finalAns: 25,
  },
]

export const PROBLEMS: ProblemSet = {
  pretest: PRETEST,
  lesson: LESSON,
  homework: HOMEWORK,
  workbook: WORKBOOK,
}

export const PROBLEM_TYPES = [
  {
    tag: 'type1',
    color: 'orange',
    label: '题型1·特殊和差关系',
    desc: '利用被减数=减数+差，通过"被减数+减数+差=总和"列方程。',
    example: '例：被减数+减数+差=80',
  },
  {
    tag: 'type2',
    color: 'blue',
    label: '题型2·三量和差',
    desc: '三个量的和已知，再给两两之间的差，逐步求各量。',
    example: '例：语+数+英=180，语+数比英多20，语比数少40',
  },
  {
    tag: 'type3',
    color: 'green',
    label: '题型3·三量和倍',
    desc: '三量互有倍数关系，转为份数统一计算。',
    example: '例：甲=乙×3+2，乙=丙×2+1',
  },
  {
    tag: 'type4',
    color: 'purple',
    label: '题型4·三量差倍',
    desc: '三量中含差和倍数，逐步化简求解。',
    example: '例：甲=乙×3-1，乙=丙×2-2',
  },
  {
    tag: 'type5',
    color: 'red',
    label: '题型5·特殊变形',
    desc: '同倍数关系下的双量问题，或通过"相等时"建立等式。',
    example: '例：游戏=跳绳×2=打球×5，跳绳比打球多30',
  },
  {
    tag: 'type6',
    color: 'pink',
    label: '题型6·综合变形',
    desc: '跨类型综合题，需要多步推导。',
    example: '例：圆珠笔=铅笔+钢笔，变化后相等',
  },
]

export const TYPE_STYLE: Record<
  string,
  { bg: string; border: string; titleColor: string; textColor: string }
> = {
  type1: {
    bg: 'bg-orange-50',
    border: 'border-l-orange-500',
    titleColor: 'text-orange-800',
    textColor: 'text-orange-900',
  },
  type2: {
    bg: 'bg-blue-50',
    border: 'border-l-blue-500',
    titleColor: 'text-blue-800',
    textColor: 'text-blue-900',
  },
  type3: {
    bg: 'bg-green-50',
    border: 'border-l-green-500',
    titleColor: 'text-green-800',
    textColor: 'text-green-900',
  },
  type4: {
    bg: 'bg-purple-50',
    border: 'border-l-purple-500',
    titleColor: 'text-purple-800',
    textColor: 'text-purple-900',
  },
  type5: {
    bg: 'bg-red-50',
    border: 'border-l-red-500',
    titleColor: 'text-red-800',
    textColor: 'text-red-900',
  },
  type6: {
    bg: 'bg-pink-50',
    border: 'border-l-pink-500',
    titleColor: 'text-pink-800',
    textColor: 'text-pink-900',
  },
}

export const TAG_STYLE: Record<string, string> = {
  type1: 'bg-orange-100 text-orange-800',
  type2: 'bg-blue-100 text-blue-800',
  type3: 'bg-green-100 text-green-800',
  type4: 'bg-purple-100 text-purple-800',
  type5: 'bg-red-100 text-red-800',
  type6: 'bg-pink-100 text-pink-800',
}
