// AUTO-GENERATED from 教材 PDF + docs/chinese/一下课课贴.pdf（写字表字段）
// Generated by docs/tmp/extract-chinese-g1b.py

import type { AccumulationUnit } from './types'

export const ACCUMULATION: AccumulationUnit[] = [
  {
    "unit": 4,
    "kind": "idiom_4",
    "items": [
      {
        "text": "尊老爱幼"
      },
      {
        "text": "其乐融融"
      },
      {
        "text": "血浓于水"
      },
      {
        "text": "手足情深"
      },
      {
        "text": "同心协力"
      },
      {
        "text": "同甘共苦"
      },
      {
        "text": "天伦之乐"
      },
      {
        "text": "欢聚一堂"
      }
    ]
  },
  {
    "unit": 5,
    "kind": "xiehouyu",
    "items": [
      {
        "text": "芝麻开花",
        "answer": "节节高"
      },
      {
        "text": "竹篮打水",
        "answer": "一场空"
      },
      {
        "text": "十五个吊桶打水",
        "answer": "七上八下"
      }
    ]
  },
  {
    "unit": 6,
    "kind": "proverb",
    "items": [
      {
        "text": "朝霞不出门，晚霞行千里。"
      },
      {
        "text": "有雨山戴帽，无雨半山腰。"
      },
      {
        "text": "早晨下雨当日晴，晚上下雨到天明。"
      },
      {
        "text": "蚂蚁搬家蛇过道，大雨不久要来到。"
      }
    ]
  },
  {
    "unit": 7,
    "kind": "quote",
    "items": [
      {
        "text": "不知则问，不能则学。",
        "source": "《荀子》"
      },
      {
        "text": "读万卷书，行万里路。",
        "source": "董其昌"
      },
      {
        "text": "读书破万卷，下笔如有神。",
        "source": "杜甫"
      }
    ]
  }
]
