// AUTO-GENERATED from 教材 PDF + docs/chinese/一下课课贴.pdf（写字表字段）
// Generated by docs/tmp/extract-chinese-g1b.py

import type { LessonCharGroup } from './types'

export const LESSON_CHARS: LessonCharGroup[] = [
  {
    "lessonKey": "u1-garden",
    "unit": 1,
    "lesson": 0,
    "lessonTitle": "语文园地一",
    "lessonKind": "garden",
    "recognize": [
      "识",
      "组",
      "计",
      "算",
      "减",
      "式",
      "图",
      "形",
      "卡",
      "合",
      "唱",
      "团"
    ],
    "recognizePinyin": [
      "shí",
      "zǔ",
      "jì",
      "suàn",
      "jiǎn",
      "shì",
      "tú",
      "xíng",
      "kǎ",
      "hé",
      "chàng",
      "tuán"
    ],
    "write": [
      "文",
      "卡",
      "片",
      "合"
    ],
    "writePinyin": [
      "wén",
      "kǎ",
      "piàn",
      "hé"
    ]
  },
  {
    "lessonKey": "u1-l1",
    "unit": 1,
    "lesson": 1,
    "lessonTitle": "春夏秋冬",
    "lessonKind": "lesson",
    "recognize": [
      "霜",
      "吹",
      "落",
      "降",
      "飘",
      "游",
      "池",
      "入"
    ],
    "recognizePinyin": [
      "shuāng",
      "chuī",
      "luò",
      "jiàng",
      "piāo",
      "yóu",
      "chí",
      "rù"
    ],
    "write": [
      "春",
      "冬",
      "吹",
      "花",
      "飞",
      "入"
    ],
    "writePinyin": [
      "chūn",
      "dōng",
      "chuī",
      "huā",
      "fēi",
      "rù"
    ]
  },
  {
    "lessonKey": "u1-l2",
    "unit": 1,
    "lesson": 2,
    "lessonTitle": "姓氏歌",
    "lessonKind": "lesson",
    "recognize": [
      "氏",
      "什",
      "李",
      "张",
      "弓",
      "古",
      "胡",
      "吴",
      "言",
      "孙"
    ],
    "recognizePinyin": [
      "shì",
      "shén",
      "lǐ",
      "zhāng",
      "gōng",
      "gǔ",
      "hú",
      "wú",
      "yán",
      "sūn"
    ],
    "write": [
      "什",
      "么",
      "古",
      "胡",
      "双",
      "言"
    ],
    "writePinyin": [
      "shén",
      "me",
      "gǔ",
      "hú",
      "shuāng",
      "yán"
    ]
  },
  {
    "lessonKey": "u1-l3",
    "unit": 1,
    "lesson": 3,
    "lessonTitle": "小青蛙",
    "lessonKind": "lesson",
    "recognize": [
      "河",
      "晴",
      "眼",
      "睛",
      "保",
      "护",
      "苗",
      "吃",
      "事",
      "情",
      "请",
      "让"
    ],
    "recognizePinyin": [
      "hé",
      "qíng",
      "yǎn",
      "jīng",
      "bǎo",
      "hù",
      "miáo",
      "chī",
      "shì",
      "qíng",
      "qǐng",
      "ràng"
    ],
    "write": [
      "青",
      "清",
      "晴",
      "苗",
      "请",
      "生"
    ],
    "writePinyin": [
      "qīng",
      "qīng",
      "qíng",
      "miáo",
      "qǐng",
      "shēng"
    ]
  },
  {
    "lessonKey": "u1-l4",
    "unit": 1,
    "lesson": 4,
    "lessonTitle": "猜字谜",
    "lessonKind": "lesson",
    "recognize": [
      "猜",
      "边",
      "凉",
      "喜",
      "欢",
      "时",
      "怕",
      "攻",
      "令",
      "感",
      "动",
      "万",
      "无"
    ],
    "recognizePinyin": [
      "cāi",
      "biān",
      "liáng",
      "xǐ",
      "huān",
      "shí",
      "pà",
      "gōng",
      "lìng",
      "gǎn",
      "dòng",
      "wàn",
      "wú"
    ],
    "write": [
      "字",
      "红",
      "动",
      "万",
      "无",
      "明"
    ],
    "writePinyin": [
      "zì",
      "hóng",
      "dòng",
      "wàn",
      "wú",
      "míng"
    ]
  },
  {
    "lessonKey": "u2-garden",
    "unit": 2,
    "lesson": 0,
    "lessonTitle": "语文园地二",
    "lessonKind": "garden",
    "recognize": [
      "认",
      "连",
      "选",
      "圈",
      "涂",
      "填",
      "试",
      "练"
    ],
    "recognizePinyin": [
      "rèn",
      "lián",
      "xuǎn",
      "quān",
      "tú",
      "tián",
      "shì",
      "liàn"
    ],
    "write": [
      "写",
      "认"
    ],
    "writePinyin": [
      "xiě",
      "rèn"
    ]
  },
  {
    "lessonKey": "u2-l1",
    "unit": 2,
    "lesson": 1,
    "lessonTitle": "热爱中国共产党",
    "lessonKind": "lesson",
    "recognize": [
      "热",
      "爱",
      "共",
      "产",
      "党",
      "太",
      "阳",
      "光",
      "怀",
      "抱",
      "幸",
      "福",
      "成"
    ],
    "recognizePinyin": [
      "rè",
      "ài",
      "gòng",
      "chǎn",
      "dǎng",
      "tài",
      "yáng",
      "guāng",
      "huái",
      "bào",
      "xìng",
      "fú",
      "chéng"
    ],
    "write": [
      "共",
      "产",
      "党",
      "太",
      "阳",
      "光"
    ],
    "writePinyin": [
      "gòng",
      "chǎn",
      "dǎng",
      "tài",
      "yáng",
      "guāng"
    ]
  },
  {
    "lessonKey": "u2-l2",
    "unit": 2,
    "lesson": 2,
    "lessonTitle": "吃水不忘挖井人",
    "lessonKind": "lesson",
    "recognize": [
      "井",
      "城",
      "村",
      "毛",
      "主",
      "席",
      "住",
      "乡",
      "亲",
      "战",
      "士",
      "想",
      "念"
    ],
    "recognizePinyin": [
      "jǐng",
      "chéng",
      "cūn",
      "máo",
      "zhǔ",
      "xí",
      "zhù",
      "xiāng",
      "qīn",
      "zhàn",
      "shì",
      "xiǎng",
      "niàn"
    ],
    "write": [
      "井",
      "主",
      "江",
      "住",
      "方",
      "后"
    ],
    "writePinyin": [
      "jǐng",
      "zhǔ",
      "jiāng",
      "zhù",
      "fāng",
      "hòu"
    ]
  },
  {
    "lessonKey": "u2-l3",
    "unit": 2,
    "lesson": 3,
    "lessonTitle": "我多想去看看",
    "lessonKind": "lesson",
    "recognize": [
      "告",
      "诉",
      "走",
      "京",
      "座",
      "安",
      "广",
      "场",
      "非",
      "宽",
      "丽",
      "洁"
    ],
    "recognizePinyin": [
      "gào",
      "sù",
      "zǒu",
      "jīng",
      "zuò",
      "ān",
      "guǎng",
      "chǎng",
      "fēi",
      "kuān",
      "lì",
      "jié"
    ],
    "write": [
      "告",
      "的",
      "会",
      "北",
      "京",
      "广"
    ],
    "writePinyin": [
      "gào",
      "de",
      "huì",
      "běi",
      "jīng",
      "guǎng"
    ]
  },
  {
    "lessonKey": "u3-garden",
    "unit": 3,
    "lesson": 0,
    "lessonTitle": "语文园地三",
    "lessonKind": "garden",
    "recognize": [
      "母",
      "页",
      "止",
      "斤",
      "寸",
      "丁",
      "千",
      "全",
      "旦"
    ],
    "recognizePinyin": [
      "mǔ",
      "yè",
      "zhǐ",
      "jīn",
      "cùn",
      "dīng",
      "qiān",
      "quán",
      "dàn"
    ],
    "write": [
      "止",
      "斤",
      "寸",
      "丁",
      "千",
      "旦"
    ],
    "writePinyin": [
      "zhǐ",
      "jīn",
      "cùn",
      "dīng",
      "qiān",
      "dàn"
    ]
  },
  {
    "lessonKey": "u3-l4",
    "unit": 3,
    "lesson": 4,
    "lessonTitle": "小公鸡和小鸭子",
    "lessonKind": "lesson",
    "recognize": [
      "玩",
      "得",
      "急",
      "直",
      "哭",
      "跟",
      "忽",
      "然",
      "听",
      "喊",
      "快",
      "己",
      "背"
    ],
    "recognizePinyin": [
      "wán",
      "de",
      "jí",
      "zhí",
      "kū",
      "gēn",
      "hū",
      "rán",
      "tīng",
      "hǎn",
      "kuài",
      "jǐ",
      "bèi"
    ],
    "write": [
      "走",
      "河",
      "说",
      "让",
      "自",
      "已"
    ],
    "writePinyin": [
      "zǒu",
      "hé",
      "shuō",
      "ràng",
      "zì",
      "yǐ"
    ]
  },
  {
    "lessonKey": "u3-l5",
    "unit": 3,
    "lesson": 5,
    "lessonTitle": "树和喜鹊",
    "lessonKind": "lesson",
    "recognize": [
      "只",
      "很",
      "孤",
      "单",
      "种",
      "每",
      "都",
      "邻",
      "居",
      "叫",
      "招",
      "呼",
      "乐"
    ],
    "recognizePinyin": [
      "zhǐ",
      "hěn",
      "gū",
      "dān",
      "zhǒng",
      "měi",
      "dōu",
      "lín",
      "jū",
      "jiào",
      "zhāo",
      "hū",
      "lè"
    ],
    "write": [
      "从",
      "好",
      "们",
      "叫",
      "他",
      "回"
    ],
    "writePinyin": [
      "cóng",
      "hǎo",
      "men",
      "jiào",
      "tā",
      "huí"
    ]
  },
  {
    "lessonKey": "u3-l6",
    "unit": 3,
    "lesson": 6,
    "lessonTitle": "怎么都快乐",
    "lessonKind": "lesson",
    "recognize": [
      "怎",
      "独",
      "跳",
      "绳",
      "当",
      "还",
      "乐",
      "得",
      "羽",
      "球",
      "劲",
      "轮",
      "排"
    ],
    "recognizePinyin": [
      "zěn",
      "dú",
      "tiào",
      "shéng",
      "dàng",
      "huán",
      "lè",
      "de",
      "yǔ",
      "qiú",
      "jìn",
      "lún",
      "pái"
    ],
    "write": [
      "快",
      "乐",
      "当",
      "书",
      "画",
      "毛"
    ],
    "writePinyin": [
      "kuài",
      "lè",
      "dàng",
      "shū",
      "huà",
      "máo"
    ]
  },
  {
    "lessonKey": "u4-garden",
    "unit": 4,
    "lesson": 0,
    "lessonTitle": "语文园地四",
    "lessonKind": "garden",
    "recognize": [
      "册",
      "支",
      "台",
      "电",
      "视",
      "部",
      "机",
      "衣",
      "裤",
      "被"
    ],
    "recognizePinyin": [
      "cè",
      "zhī",
      "tái",
      "diàn",
      "shì",
      "bù",
      "jī",
      "yī",
      "kù",
      "bèi"
    ],
    "write": [
      "册",
      "支",
      "电",
      "衣"
    ],
    "writePinyin": [
      "cè",
      "zhī",
      "diàn",
      "yī"
    ]
  },
  {
    "lessonKey": "u4-l7",
    "unit": 4,
    "lesson": 7,
    "lessonTitle": "静夜思",
    "lessonKind": "lesson",
    "recognize": [
      "静",
      "思",
      "床",
      "疑",
      "举",
      "望",
      "低",
      "故"
    ],
    "recognizePinyin": [
      "jìng",
      "sī",
      "chuáng",
      "yí",
      "jǔ",
      "wàng",
      "dī",
      "gù"
    ],
    "write": [
      "思",
      "床",
      "前",
      "地",
      "故",
      "乡"
    ],
    "writePinyin": [
      "sī",
      "chuáng",
      "qián",
      "dì",
      "gù",
      "xiāng"
    ]
  },
  {
    "lessonKey": "u4-l8",
    "unit": 4,
    "lesson": 8,
    "lessonTitle": "夜色",
    "lessonKind": "lesson",
    "recognize": [
      "胆",
      "敢",
      "勇",
      "讲",
      "窗",
      "乱",
      "拉",
      "样",
      "笑",
      "再",
      "睡",
      "觉"
    ],
    "recognizePinyin": [
      "dǎn",
      "gǎn",
      "yǒng",
      "jiǎng",
      "chuāng",
      "luàn",
      "lā",
      "yàng",
      "xiào",
      "zài",
      "shuì",
      "jiào"
    ],
    "write": [
      "色",
      "把",
      "讲",
      "样",
      "笑",
      "再"
    ],
    "writePinyin": [
      "sè",
      "bǎ",
      "jiǎng",
      "yàng",
      "xiào",
      "zài"
    ]
  },
  {
    "lessonKey": "u4-l9",
    "unit": 4,
    "lesson": 9,
    "lessonTitle": "端午粽",
    "lessonKind": "lesson",
    "recognize": [
      "端",
      "粽",
      "节",
      "总",
      "煮",
      "盼",
      "米",
      "枣",
      "甜",
      "分",
      "鲜",
      "肉",
      "了"
    ],
    "recognizePinyin": [
      "duān",
      "zòng",
      "jié",
      "zǒng",
      "zhǔ",
      "pàn",
      "mǐ",
      "zǎo",
      "tián",
      "fēn",
      "xiān",
      "ròu",
      "le"
    ],
    "write": [
      "节",
      "米",
      "间",
      "分",
      "吃",
      "肉"
    ],
    "writePinyin": [
      "jié",
      "mǐ",
      "jiān",
      "fēn",
      "chī",
      "ròu"
    ]
  },
  {
    "lessonKey": "u5-garden",
    "unit": 5,
    "lesson": 0,
    "lessonTitle": "语文园地五",
    "lessonKind": "garden",
    "recognize": [
      "饭",
      "饱",
      "茶",
      "泡",
      "轻",
      "穿",
      "袍",
      "鞭",
      "炮"
    ],
    "recognizePinyin": [
      "fàn",
      "bǎo",
      "chá",
      "pào",
      "qīng",
      "chuān",
      "páo",
      "biān",
      "pào"
    ],
    "write": [
      "饱",
      "抱"
    ],
    "writePinyin": [
      "bǎo",
      "bào"
    ]
  },
  {
    "lessonKey": "u5-l5",
    "unit": 5,
    "lesson": 5,
    "lessonTitle": "动物儿歌",
    "lessonKind": "lesson",
    "recognize": [
      "物",
      "捉",
      "迷",
      "藏",
      "造",
      "蚂",
      "蚁",
      "运",
      "食",
      "粮",
      "房",
      "结",
      "网"
    ],
    "recognizePinyin": [
      "wù",
      "zhuō",
      "mí",
      "cáng",
      "zào",
      "mǎ",
      "yǐ",
      "yùn",
      "shí",
      "liáng",
      "fáng",
      "jié",
      "wǎng"
    ],
    "write": [
      "物",
      "造",
      "运",
      "欢",
      "房",
      "网"
    ],
    "writePinyin": [
      "wù",
      "zào",
      "yùn",
      "huān",
      "fáng",
      "wǎng"
    ]
  },
  {
    "lessonKey": "u5-l6",
    "unit": 5,
    "lesson": 6,
    "lessonTitle": "古对今",
    "lessonKind": "lesson",
    "recognize": [
      "圆",
      "严",
      "寒",
      "酷",
      "暑",
      "暖",
      "晨",
      "细",
      "朝",
      "霞",
      "夕",
      "杨",
      "香"
    ],
    "recognizePinyin": [
      "yuán",
      "yán",
      "hán",
      "kù",
      "shǔ",
      "nuǎn",
      "chén",
      "xì",
      "cháo",
      "xiá",
      "xī",
      "yáng",
      "xiāng"
    ],
    "write": [
      "对",
      "今",
      "雪",
      "细",
      "夕",
      "语"
    ],
    "writePinyin": [
      "duì",
      "jīn",
      "xuě",
      "xì",
      "xī",
      "yǔ"
    ]
  },
  {
    "lessonKey": "u5-l7",
    "unit": 5,
    "lesson": 7,
    "lessonTitle": "操场上",
    "lessonKind": "lesson",
    "recognize": [
      "操",
      "拔",
      "拍",
      "跑",
      "踢",
      "铃",
      "真",
      "闹",
      "丢",
      "沙",
      "身",
      "体"
    ],
    "recognizePinyin": [
      "cāo",
      "bá",
      "pāi",
      "pǎo",
      "tī",
      "líng",
      "zhēn",
      "nào",
      "diū",
      "shā",
      "shēn",
      "tǐ"
    ],
    "write": [
      "打",
      "皮",
      "跑",
      "足",
      "沙",
      "包"
    ],
    "writePinyin": [
      "dǎ",
      "pí",
      "pǎo",
      "zú",
      "shā",
      "bāo"
    ]
  },
  {
    "lessonKey": "u5-l8",
    "unit": 5,
    "lesson": 8,
    "lessonTitle": "人之初",
    "lessonKind": "lesson",
    "recognize": [
      "之",
      "初",
      "相",
      "近",
      "习",
      "远",
      "教",
      "道",
      "专",
      "幼",
      "玉",
      "知",
      "义"
    ],
    "recognizePinyin": [
      "zhī",
      "chū",
      "xiāng",
      "jìn",
      "xí",
      "yuǎn",
      "jiào",
      "dào",
      "zhuān",
      "yòu",
      "yù",
      "zhī",
      "yì"
    ],
    "write": [
      "近",
      "习",
      "远",
      "学",
      "玉",
      "义"
    ],
    "writePinyin": [
      "jìn",
      "xí",
      "yuǎn",
      "xué",
      "yù",
      "yì"
    ]
  },
  {
    "lessonKey": "u6-garden",
    "unit": 6,
    "lesson": 0,
    "lessonTitle": "语文园地六",
    "lessonKind": "garden",
    "recognize": [
      "棍",
      "豆",
      "汤",
      "蚊",
      "扇",
      "椅",
      "牵",
      "织",
      "斗"
    ],
    "recognizePinyin": [
      "gùn",
      "dòu",
      "tāng",
      "wén",
      "shàn",
      "yǐ",
      "qiān",
      "zhī",
      "dòu"
    ],
    "write": [
      "豆",
      "斗"
    ],
    "writePinyin": [
      "dòu",
      "dòu"
    ]
  },
  {
    "lessonKey": "u6-l10",
    "unit": 6,
    "lesson": 10,
    "lessonTitle": "古诗二首",
    "lessonKind": "lesson",
    "recognize": [
      "诗",
      "首",
      "偷",
      "浮",
      "萍",
      "泉",
      "惜",
      "照",
      "柔",
      "荷",
      "露",
      "角"
    ],
    "recognizePinyin": [
      "shī",
      "shǒu",
      "tōu",
      "fú",
      "píng",
      "quán",
      "xī",
      "zhào",
      "róu",
      "hé",
      "lù",
      "jiǎo"
    ],
    "write": [
      "首",
      "池",
      "采",
      "尖",
      "角",
      "早"
    ],
    "writePinyin": [
      "shǒu",
      "chí",
      "cǎi",
      "jiān",
      "jiǎo",
      "zǎo"
    ]
  },
  {
    "lessonKey": "u6-l11",
    "unit": 6,
    "lesson": 11,
    "lessonTitle": "浪花",
    "lessonKind": "lesson",
    "recognize": [
      "浪",
      "迈",
      "悄",
      "泪",
      "次",
      "给",
      "壳",
      "虾",
      "装",
      "像",
      "淘",
      "娃"
    ],
    "recognizePinyin": [
      "làng",
      "mài",
      "qiāo",
      "lèi",
      "cì",
      "gěi",
      "ké",
      "xiā",
      "zhuāng",
      "xiàng",
      "táo",
      "wá"
    ],
    "write": [
      "眼",
      "泪",
      "它",
      "贝",
      "气",
      "娃"
    ],
    "writePinyin": [
      "yǎn",
      "lèi",
      "tā",
      "bèi",
      "qì",
      "wá"
    ]
  },
  {
    "lessonKey": "u6-l12",
    "unit": 6,
    "lesson": 12,
    "lessonTitle": "荷叶圆圆",
    "lessonKind": "lesson",
    "recognize": [
      "珠",
      "摇",
      "篮",
      "亮",
      "晶",
      "停",
      "坪",
      "展",
      "透",
      "翅",
      "膀",
      "朵"
    ],
    "recognizePinyin": [
      "zhū",
      "yáo",
      "lán",
      "liàng",
      "jīng",
      "tíng",
      "píng",
      "zhǎn",
      "tòu",
      "chì",
      "bǎng",
      "duǒ"
    ],
    "write": [
      "机",
      "台",
      "唱",
      "伞",
      "朵",
      "美"
    ],
    "writePinyin": [
      "jī",
      "tái",
      "chàng",
      "sǎn",
      "duǒ",
      "měi"
    ]
  },
  {
    "lessonKey": "u6-l13",
    "unit": 6,
    "lesson": 13,
    "lessonTitle": "要下雨了",
    "lessonKind": "lesson",
    "recognize": [
      "要",
      "腰",
      "阴",
      "沉",
      "呀",
      "忙",
      "呢",
      "吗",
      "面",
      "空",
      "闷",
      "吧",
      "消",
      "息"
    ],
    "recognizePinyin": [
      "yào",
      "yāo",
      "yīn",
      "chén",
      "ya",
      "máng",
      "ne",
      "ma",
      "miàn",
      "kōng",
      "mèn",
      "ba",
      "xiāo",
      "xī"
    ],
    "write": [
      "这",
      "看",
      "鱼",
      "面",
      "问",
      "加"
    ],
    "writePinyin": [
      "zhè",
      "kàn",
      "yú",
      "miàn",
      "wèn",
      "jiā"
    ]
  },
  {
    "lessonKey": "u7-garden",
    "unit": 7,
    "lesson": 0,
    "lessonTitle": "语文园地七",
    "lessonKind": "garden",
    "recognize": [
      "刷",
      "梳",
      "巾",
      "皂",
      "洗",
      "澡",
      "脸",
      "盆"
    ],
    "recognizePinyin": [
      "shuā",
      "shū",
      "jīn",
      "zào",
      "xǐ",
      "zǎo",
      "liǎn",
      "pén"
    ],
    "write": [
      "巾",
      "洗"
    ],
    "writePinyin": [
      "jīn",
      "xǐ"
    ]
  },
  {
    "lessonKey": "u7-l14",
    "unit": 7,
    "lesson": 14,
    "lessonTitle": "文具的家",
    "lessonKind": "lesson",
    "recognize": [
      "具",
      "铅",
      "新",
      "平",
      "盒",
      "些",
      "此",
      "仔",
      "检",
      "查",
      "所",
      "伙",
      "伴"
    ],
    "recognizePinyin": [
      "jù",
      "qiān",
      "xīn",
      "píng",
      "hé",
      "xiē",
      "cǐ",
      "zǎi",
      "jiǎn",
      "chá",
      "suǒ",
      "huǒ",
      "bàn"
    ],
    "write": [
      "笔",
      "知",
      "道",
      "放",
      "平",
      "安"
    ],
    "writePinyin": [
      "bǐ",
      "zhī",
      "dào",
      "fàng",
      "píng",
      "ān"
    ]
  },
  {
    "lessonKey": "u7-l15",
    "unit": 7,
    "lesson": 15,
    "lessonTitle": "一分钟",
    "lessonKind": "lesson",
    "recognize": [
      "钟",
      "迟",
      "背",
      "灯",
      "等",
      "啊",
      "决",
      "定",
      "已",
      "经",
      "位",
      "表"
    ],
    "recognizePinyin": [
      "zhōng",
      "chí",
      "bèi",
      "dēng",
      "děng",
      "a",
      "jué",
      "dìng",
      "yǐ",
      "jīng",
      "wèi",
      "biǎo"
    ],
    "write": [
      "元",
      "灯",
      "车",
      "站",
      "坐",
      "老",
      "师"
    ],
    "writePinyin": [
      "yuán",
      "dēng",
      "chē",
      "zhàn",
      "zuò",
      "lǎo",
      "shī"
    ]
  },
  {
    "lessonKey": "u7-l16",
    "unit": 7,
    "lesson": 16,
    "lessonTitle": "动物王国开大会",
    "lessonKind": "lesson",
    "recognize": [
      "虎",
      "熊",
      "通",
      "注",
      "意",
      "遍",
      "百",
      "为",
      "因",
      "舌",
      "理",
      "呀",
      "忘",
      "第"
    ],
    "recognizePinyin": [
      "hǔ",
      "xióng",
      "tōng",
      "zhù",
      "yì",
      "biàn",
      "bǎi",
      "wèi",
      "yīn",
      "shé",
      "lǐ",
      "ya",
      "wàng",
      "dì"
    ],
    "write": [
      "国",
      "都",
      "百",
      "听",
      "时",
      "点",
      "林"
    ],
    "writePinyin": [
      "guó",
      "dōu",
      "bǎi",
      "tīng",
      "shí",
      "diǎn",
      "lín"
    ]
  },
  {
    "lessonKey": "u7-l17",
    "unit": 7,
    "lesson": 17,
    "lessonTitle": "小猴子下山",
    "lessonKind": "lesson",
    "recognize": [
      "猴",
      "块",
      "结",
      "兴",
      "掰",
      "扛",
      "往",
      "棵",
      "满",
      "扔",
      "摘",
      "捧",
      "追"
    ],
    "recognizePinyin": [
      "hóu",
      "kuài",
      "jiē",
      "xīng",
      "bāi",
      "káng",
      "wǎng",
      "kē",
      "mǎn",
      "rēng",
      "zhāi",
      "pěng",
      "zhuī"
    ],
    "write": [
      "高",
      "兴",
      "着",
      "往",
      "瓜",
      "兔",
      "进"
    ],
    "writePinyin": [
      "gāo",
      "xīng",
      "zhe",
      "wǎng",
      "guā",
      "tù",
      "jìn"
    ]
  },
  {
    "lessonKey": "u8-garden",
    "unit": 8,
    "lesson": 0,
    "lessonTitle": "语文园地八",
    "lessonKind": "garden",
    "recognize": [
      "吵",
      "现",
      "顶",
      "胖",
      "票",
      "户",
      "交",
      "父"
    ],
    "recognizePinyin": [
      "chǎo",
      "xiàn",
      "dǐng",
      "pàng",
      "piào",
      "hù",
      "jiāo",
      "fù"
    ],
    "write": [
      "页",
      "户",
      "交",
      "父"
    ],
    "writePinyin": [
      "yè",
      "hù",
      "jiāo",
      "fù"
    ]
  },
  {
    "lessonKey": "u8-l18",
    "unit": 8,
    "lesson": 18,
    "lessonTitle": "棉花姑娘",
    "lessonKind": "lesson",
    "recognize": [
      "棉",
      "姑",
      "娘",
      "病",
      "她",
      "治",
      "燕",
      "帮",
      "害",
      "别",
      "干",
      "惊",
      "奇"
    ],
    "recognizePinyin": [
      "mián",
      "gū",
      "niáng",
      "bìng",
      "tā",
      "zhì",
      "yàn",
      "bāng",
      "hài",
      "bié",
      "gàn",
      "jīng",
      "qí"
    ],
    "write": [
      "她",
      "空",
      "还",
      "干",
      "身",
      "星",
      "久"
    ],
    "writePinyin": [
      "tā",
      "kōng",
      "hái",
      "gàn",
      "shēn",
      "xīng",
      "jiǔ"
    ]
  },
  {
    "lessonKey": "u8-l19",
    "unit": 8,
    "lesson": 19,
    "lessonTitle": "咕咚",
    "lessonKind": "lesson",
    "recognize": [
      "咕",
      "咚",
      "熟",
      "掉",
      "湖",
      "吓",
      "啦",
      "鹿",
      "象",
      "野",
      "拦",
      "哪",
      "那",
      "领"
    ],
    "recognizePinyin": [
      "gū",
      "dōng",
      "shú",
      "diào",
      "hú",
      "xià",
      "la",
      "lù",
      "xiàng",
      "yě",
      "lán",
      "nǎ",
      "nà",
      "lǐng"
    ],
    "write": [
      "吓",
      "为",
      "怕",
      "家",
      "象",
      "没",
      "到"
    ],
    "writePinyin": [
      "xià",
      "wèi",
      "pà",
      "jiā",
      "xiàng",
      "méi",
      "dào"
    ]
  },
  {
    "lessonKey": "u8-l20",
    "unit": 8,
    "lesson": 20,
    "lessonTitle": "小壁虎借尾巴",
    "lessonKind": "lesson",
    "recognize": [
      "壁",
      "借",
      "咬",
      "难",
      "哪",
      "爬",
      "您",
      "拨",
      "赶",
      "摆",
      "过",
      "孩",
      "转"
    ],
    "recognizePinyin": [
      "bì",
      "jiè",
      "yǎo",
      "nán",
      "nǎ",
      "pá",
      "nín",
      "bō",
      "gǎn",
      "bǎi",
      "guò",
      "hái",
      "zhuǎn"
    ],
    "write": [
      "向",
      "边",
      "行",
      "草",
      "赶",
      "过",
      "找"
    ],
    "writePinyin": [
      "xiàng",
      "biān",
      "xíng",
      "cǎo",
      "gǎn",
      "guò",
      "zhǎo"
    ]
  }
]
