// AUTO-GENERATED from 教材 PDF + docs/chinese/一下课课贴.pdf（写字表字段）
// Generated by docs/tmp/extract-chinese-g1b.py

import type { ChineseUnitEntry } from './types'

export const UNITS: ChineseUnitEntry[] = [
  {
    "unit": 1,
    "title": "第一单元·识字",
    "unitType": "literacy",
    "lessons": [
      {
        "lesson": 1,
        "title": "春夏秋冬",
        "requiresRecite": true
      },
      {
        "lesson": 2,
        "title": "姓氏歌",
        "requiresRecite": true
      },
      {
        "lesson": 3,
        "title": "小青蛙",
        "requiresRecite": false
      },
      {
        "lesson": 4,
        "title": "猜字谜",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地一",
        "kind": "garden"
      },
      {
        "lesson": 0,
        "title": "快乐读书吧",
        "kind": "happy_reading"
      }
    ]
  },
  {
    "unit": 2,
    "title": "第二单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 1,
        "title": "热爱中国共产党",
        "requiresRecite": false
      },
      {
        "lesson": 2,
        "title": "吃水不忘挖井人",
        "requiresRecite": false
      },
      {
        "lesson": 3,
        "title": "我多想去看看",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地二",
        "kind": "garden"
      }
    ]
  },
  {
    "unit": 3,
    "title": "第三单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 4,
        "title": "小公鸡和小鸭子",
        "requiresRecite": false
      },
      {
        "lesson": 5,
        "title": "树和喜鹊",
        "requiresRecite": false
      },
      {
        "lesson": 6,
        "title": "怎么都快乐",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地三",
        "kind": "garden"
      }
    ]
  },
  {
    "unit": 4,
    "title": "第四单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 7,
        "title": "静夜思",
        "requiresRecite": true,
        "isPoem": true
      },
      {
        "lesson": 8,
        "title": "夜色",
        "requiresRecite": false
      },
      {
        "lesson": 9,
        "title": "端午粽",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地四",
        "kind": "garden"
      }
    ]
  },
  {
    "unit": 5,
    "title": "第五单元·识字",
    "unitType": "literacy",
    "lessons": [
      {
        "lesson": 5,
        "title": "动物儿歌",
        "requiresRecite": false
      },
      {
        "lesson": 6,
        "title": "古对今",
        "requiresRecite": false
      },
      {
        "lesson": 7,
        "title": "操场上",
        "requiresRecite": false
      },
      {
        "lesson": 8,
        "title": "人之初",
        "requiresRecite": true
      },
      {
        "lesson": 0,
        "title": "语文园地五",
        "kind": "garden"
      }
    ]
  },
  {
    "unit": 6,
    "title": "第六单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 10,
        "title": "古诗二首",
        "requiresRecite": true,
        "isPoem": true,
        "subPoems": [
          "池上",
          "小池"
        ]
      },
      {
        "lesson": 11,
        "title": "浪花",
        "requiresRecite": false
      },
      {
        "lesson": 12,
        "title": "荷叶圆圆",
        "requiresRecite": true
      },
      {
        "lesson": 13,
        "title": "要下雨了",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地六",
        "kind": "garden"
      }
    ]
  },
  {
    "unit": 7,
    "title": "第七单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 14,
        "title": "文具的家",
        "requiresRecite": false
      },
      {
        "lesson": 15,
        "title": "一分钟",
        "requiresRecite": false
      },
      {
        "lesson": 16,
        "title": "动物王国开大会",
        "requiresRecite": false
      },
      {
        "lesson": 17,
        "title": "小猴子下山",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地七",
        "kind": "garden"
      }
    ]
  },
  {
    "unit": 8,
    "title": "第八单元·阅读",
    "unitType": "reading",
    "lessons": [
      {
        "lesson": 18,
        "title": "棉花姑娘",
        "requiresRecite": false
      },
      {
        "lesson": 19,
        "title": "咕咚",
        "requiresRecite": false
      },
      {
        "lesson": 20,
        "title": "小壁虎借尾巴",
        "requiresRecite": false
      },
      {
        "lesson": 0,
        "title": "语文园地八",
        "kind": "garden"
      }
    ]
  }
]
