import type { WordEntry } from '@rosie/core'

/**
 * 4B vocabulary backup — 223 words across Units 7–12.
 * Generated 2026-06-05 from docs/4B.pdf.
 *
 * NOT imported by runtime code. The canonical data lives in Supabase
 * `word_entries` table (see docs/4b-upsert.sql for the load script).
 * This file exists for version-control / disaster-recovery / re-seeding.
 */
const _RAW_WORDS_4B: WordEntry[] = [
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 1",
    "word": "national park",
    "explanation": "an area of land that is protected by the government for people to visit because of its natural beauty and historical or scientific interest",
    "ipa": "/ˈnæʃnəl pɑːk/",
    "example": "Last summer we visited a national park and saw three iguanas."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 1",
    "word": "iguana",
    "explanation": "a large tropical American lizard",
    "ipa": "/ɪˈɡwɑːnə/",
    "example": "Dad showed me a green iguana sitting on a warm rock."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 1",
    "word": "branch",
    "explanation": "a part of a tree that grows out from the trunk",
    "ipa": "/brɑːntʃ/",
    "example": "A little bird was singing on a branch of the apple tree."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 1",
    "word": "jungle",
    "explanation": "an area of tropical forest where trees and plants grow very thickly",
    "ipa": "/ˈdʒʌŋɡl/",
    "example": "We saw colourful parrots flying high above the green jungle."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 1",
    "word": "lay eggs",
    "explanation": "to produce and put eggs outside the body, like birds do",
    "ipa": "/leɪ eɡz/",
    "example": "Our hens lay eggs every morning in the little wooden box."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 1",
    "word": "sand",
    "explanation": "the very tiny, loose pieces of rock that cover beaches, deserts, etc.",
    "ipa": "/sænd/",
    "example": "Rosie built a tall sand castle on the sunny beach."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 1",
    "word": "leaf",
    "explanation": "a flat green part of a plant, growing from a stem or branch or from the root",
    "ipa": "/liːf/",
    "example": "A tiny caterpillar was eating a green leaf in the garden."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 1",
    "word": "volcano",
    "explanation": "a mountain with a hole in the top or side that sometimes sends out rocks, ash, lava, etc., in a sudden explosion (called an eruption)",
    "ipa": "/vɒlˈkeɪnəʊ/",
    "example": "The huge volcano on the island sent smoke high into the sky."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 1",
    "word": "nest",
    "explanation": "the place where a bird lays its eggs and takes care of its young",
    "ipa": "/nest/",
    "example": "Three baby birds were chirping happily in their cosy nest."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 1",
    "word": "wildlife",
    "explanation": "animals living in nature",
    "ipa": "/ˈwaɪldlaɪf/",
    "example": "The national park is home to lots of amazing wildlife."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 1",
    "word": "soil",
    "explanation": "the top layer of earth in which plants grow",
    "ipa": "/sɔɪl/",
    "example": "We dug holes in the soft soil to plant our sunflower seeds."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 1",
    "word": "erupt",
    "explanation": "to send out rocks, ash, lava, etc., in a sudden explosion",
    "ipa": "/ɪˈrʌpt/",
    "example": "The old volcano can still erupt and send out red lava."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 1",
    "word": "stone",
    "explanation": "a small piece of rock of any shape",
    "ipa": "/stəʊn/",
    "example": "Rosie picked up a smooth grey stone beside the river."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 1",
    "word": "active",
    "explanation": "likely to explode violently or produce fire and hot liquid rock",
    "ipa": "/ˈæktɪv/",
    "example": "The active volcano on the island sometimes shoots out hot lava."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 2",
    "word": "humid",
    "explanation": "(of the air or climate) warm and slightly wet",
    "ipa": "/ˈhjuːmɪd/",
    "example": "The jungle air felt very humid and sticky in the afternoon."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 2",
    "word": "smell",
    "explanation": "the quality of a thing that you can sense with your nose",
    "ipa": "/smel/",
    "example": "I love the sweet smell of Mum's freshly baked cookies."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 2",
    "word": "alive",
    "explanation": "living; not dead",
    "ipa": "/əˈlaɪv/",
    "example": "The little fish we found in the pond was still alive."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 2",
    "word": "creature",
    "explanation": "a living thing, real or imaginary, that can move around, such as an animal",
    "ipa": "/ˈkriːtʃə/",
    "example": "A tiny furry creature was hiding under the garden bench."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 2",
    "word": "curious",
    "explanation": "having a strong desire to know about something",
    "ipa": "/ˈkjʊəriəs/",
    "example": "Rosie is very curious about how baby chicks hatch from eggs."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 2",
    "word": "liquid",
    "explanation": "a substance that is able to flow freely",
    "ipa": "/ˈlɪkwɪd/",
    "example": "Hot lava is a red liquid that flows down the volcano."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 2",
    "word": "massive",
    "explanation": "very large, heavy and solid",
    "ipa": "/ˈmæsɪv/",
    "example": "We saw a massive elephant drinking water at the zoo."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 2",
    "word": "stem",
    "explanation": "the main long and thin part of a plant that rises above the soil and supports the leaves and flowers",
    "ipa": "/stem/",
    "example": "The sunflower has a long green stem and bright yellow petals."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 2",
    "word": "slippery",
    "explanation": "difficult to stand on, move on, or hold because of being smooth, wet, icy, etc.",
    "ipa": "/ˈslɪpəri/",
    "example": "Be careful, the kitchen floor is very slippery when it's wet."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 2",
    "word": "trap",
    "explanation": "to catch and hold something (or someone) so it cannot escape",
    "ipa": "/træp/",
    "example": "The clever plant can trap little flies inside its leaves."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 2",
    "word": "sticky",
    "explanation": "having a substance (such as glue or honey) on it that things easily attach to: covered in a substance that things stick to",
    "ipa": "/ˈstɪki/",
    "example": "My fingers got really sticky after eating the honey toast."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 2",
    "word": "climate",
    "explanation": "the regular pattern of weather conditions of a particular place",
    "ipa": "/ˈklaɪmət/",
    "example": "The jungle has a warm and wet climate all year round."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 2",
    "word": "variety",
    "explanation": "several different sorts of the same thing",
    "ipa": "/vəˈraɪəti/",
    "example": "The park has a wide variety of beautiful flowers and trees."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 3",
    "word": "sanctuary",
    "explanation": "an area where wild birds or animals are protected and encouraged to produce young",
    "ipa": "/ˈsæŋktʃuəri/",
    "example": "We visited a bird sanctuary and saw many baby pandas being cared for."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 3",
    "word": "success",
    "explanation": "the fact that you have achieved something that you want and have been trying to do or get",
    "ipa": "/səkˈses/",
    "example": "Rosie's first school play was a huge success with her parents."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 3",
    "word": "endangered",
    "explanation": "(used especially about groups of animals, plants, etc.) at risk of no longer existing",
    "ipa": "/ɪnˈdeɪndʒəd/",
    "example": "Giant pandas are endangered animals that need our care and love."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 3",
    "word": "cause",
    "explanation": "to make something happen, especially something bad or unpleasant; to make somebody do something",
    "ipa": "/kɔːz/",
    "example": "Heavy rain can cause the little river to flood the fields."
  },
  {
    "stage": "4B",
    "unit": "Unit 7",
    "lesson": "Lesson 3",
    "word": "ocean",
    "explanation": "the mass of salt water that covers most of the earth's surface",
    "ipa": "/ˈəʊʃn/",
    "example": "Lots of amazing creatures live deep down in the blue ocean."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 1",
    "word": "cover",
    "explanation": "to place something over or in front of something in order to hide, protect or decorate it",
    "ipa": "/ˈkʌvə/",
    "example": "She used a blanket to cover the puppy when it was cold."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 1",
    "word": "battery",
    "explanation": "a device that is placed inside a machine (such as a clock, toy, or car) to supply it with electricity",
    "ipa": "/ˈbætəri/",
    "example": "Dad put a new battery into my noisy toy robot."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 1",
    "word": "dump",
    "explanation": "to put (something) somewhere in a quick and careless way",
    "ipa": "/dʌmp/",
    "example": "Don't dump your wet socks on the clean kitchen floor."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 1",
    "word": "can",
    "explanation": "a metal container in which food and drink is sold",
    "ipa": "/kæn/",
    "example": "Mum opened a can of tomato soup for our quick lunch."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 1",
    "word": "landfill",
    "explanation": "an area where waste is buried under the ground",
    "ipa": "/ˈlændfɪl/",
    "example": "Too much plastic from our city ends up in the landfill."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 1",
    "word": "cardboard",
    "explanation": "a stiff and thick kind of paper that is used especially for making boxes",
    "ipa": "/ˈkɑːdbɔːd/",
    "example": "We built a cool spaceship from an old cardboard box."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 1",
    "word": "environmental",
    "explanation": "connected with the natural conditions in which people, animals and plants live; connected with the environment",
    "ipa": "/ɪnˌvaɪrənˈmentl/",
    "example": "Our class joined an environmental project to clean the park."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 1",
    "word": "electronics",
    "explanation": "devices (such as televisions, radios, and computers) that operate using many small electrical parts",
    "ipa": "/ɪˌlekˈtrɒnɪks/",
    "example": "Please don't throw old electronics into the rubbish bin."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 1",
    "word": "improve",
    "explanation": "to become better than before; to make something/somebody better than before",
    "ipa": "/ɪmˈpruːv/",
    "example": "Rosie practises every day to improve her English reading."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 1",
    "word": "newspaper",
    "explanation": "a set of large printed sheets of paper, or a website, containing news, articles, advertisements, etc. and published every day or every week",
    "ipa": "/ˈnjuːzpeɪpə/",
    "example": "Grandpa reads the newspaper at breakfast every Sunday morning."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 1",
    "word": "system",
    "explanation": "a group of related parts that move or work together",
    "ipa": "/ˈsɪstəm/",
    "example": "Our school has a new system for sorting paper and plastic."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 1",
    "word": "plastic bag",
    "explanation": "a light bag made of plastic",
    "ipa": "/ˈplæstɪk bæɡ/",
    "example": "She carried the apples home in a small plastic bag."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 1",
    "word": "recreation",
    "explanation": "something people do to relax or have fun",
    "ipa": "/ˌrekriˈeɪʃn/",
    "example": "Riding bikes in the park is my favourite weekend recreation."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 1",
    "word": "rubber",
    "explanation": "A strong substance that can be stretched and does not allow liquids to pass through it, used for making tyres, boots, etc.",
    "ipa": "/ˈrʌbə/",
    "example": "My new rain boots are made of soft yellow rubber."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 1",
    "word": "association",
    "explanation": "an official group of people who have joined together for a particular purpose",
    "ipa": "/əˌsəʊsiˈeɪʃn/",
    "example": "Our parents joined an association to plant trees near the school."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 1",
    "word": "handle",
    "explanation": "to deal with a situation, a person, an area of work or a strong emotion",
    "ipa": "/ˈhændl/",
    "example": "Rosie can handle her homework all by herself now."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 2",
    "word": "petrol",
    "explanation": "a liquid made from petroleum and used especially as a fuel for engines",
    "ipa": "/ˈpetrəl/",
    "example": "Dad stopped the car to buy some petrol before our trip."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 2",
    "word": "pollute",
    "explanation": "to make (land, water, air, etc.) dirty and not safe or suitable to use",
    "ipa": "/pəˈluːt/",
    "example": "Cars and factories pollute the air in many big cities."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 2",
    "word": "recycle",
    "explanation": "to treat things that have already been used so that they can be used again",
    "ipa": "/ˌriːˈsaɪkl/",
    "example": "We recycle paper and bottles in the green bin at home."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 2",
    "word": "tap water",
    "explanation": "water supplied through pipes to taps in a building",
    "ipa": "/tæp ˈwɔːtə/",
    "example": "I filled my bottle with cold tap water from the kitchen."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 2",
    "word": "throw away",
    "explanation": "to get rid of something that you no longer want",
    "ipa": "/θrəʊ əˈweɪ/",
    "example": "Please don't throw away the box; we can paint it."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 2",
    "word": "destroy",
    "explanation": "to damage something so badly that it no longer exists, works, etc.",
    "ipa": "/dɪˈstrɔɪ/",
    "example": "The big storm nearly destroyed our wooden treehouse last night."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 2",
    "word": "oil",
    "explanation": "a thick liquid that is found in rock underground",
    "ipa": "/ɔɪl/",
    "example": "Big ships carry oil across the ocean to many countries."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 2",
    "word": "air conditioning",
    "explanation": "a system that cools and dries the air in a building or car",
    "ipa": "/ˈeə kənˌdɪʃənɪŋ/",
    "example": "The air conditioning kept our classroom cool on the hot day."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 2",
    "word": "fan",
    "explanation": "a machine that creates a current of air",
    "ipa": "/fæn/",
    "example": "Mum turned on the fan because the kitchen was too warm."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 2",
    "word": "free",
    "explanation": "not costing any money",
    "ipa": "/friː/",
    "example": "The zoo gives kids a free balloon on their birthday."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 2",
    "word": "green",
    "explanation": "trying to protect or meant to protect the natural world",
    "ipa": "/ɡriːn/",
    "example": "Our school is very green and saves water every day."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 2",
    "word": "product",
    "explanation": "a thing that is grown, produced or created, usually for sale",
    "ipa": "/ˈprɒdʌkt/",
    "example": "This shampoo is a new product made from natural plants."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 2",
    "word": "waste",
    "explanation": "materials that are no longer needed and are thrown away",
    "ipa": "/weɪst/",
    "example": "Our family puts all food waste into a small brown bin."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 2",
    "word": "by mistake",
    "explanation": "in a way that is not planned or organised",
    "ipa": "/baɪ mɪˈsteɪk/",
    "example": "I put salt in my tea by mistake this morning."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 2",
    "word": "ecosystem",
    "explanation": "all the plants and living creatures in a particular area considered in relation to their physical environment",
    "ipa": "/ˈiːkəʊsɪstəm/",
    "example": "Frogs and fish share the same pond ecosystem in our garden."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 3",
    "word": "shade",
    "explanation": "an area that is dark and cool under or behind something, for example a tree or building, because the sun's light does not get to it",
    "ipa": "/ʃeɪd/",
    "example": "We had our picnic in the shade of a tall tree."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 3",
    "word": "oxygen",
    "explanation": "A chemical element. A gas that is present in air and water and is necessary for people, animals and plants to live.",
    "ipa": "/ˈɒksɪdʒən/",
    "example": "Trees give us the oxygen we breathe every day."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 3",
    "word": "drip",
    "explanation": "(of liquid) to fall in small drops",
    "ipa": "/drɪp/",
    "example": "Rain began to drip from the leaves onto my hat."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 3",
    "word": "global warming",
    "explanation": "the increase in temperature of the earth's atmosphere that is caused by the increase of particular gases, especially carbon dioxide",
    "ipa": "/ˌɡləʊbl ˈwɔːmɪŋ/",
    "example": "Planting more trees can help slow down global warming."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 3",
    "word": "explorer",
    "explanation": "a person who travels to places where few people have been before or places that are not well known",
    "ipa": "/ɪkˈsplɔːrə/",
    "example": "Rosie dreams of becoming a brave explorer in the jungle."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 3",
    "word": "tool",
    "explanation": "something (such as a hammer, saw, shovel, etc.) that you hold in your hand and use for a particular task",
    "ipa": "/tuːl/",
    "example": "Dad picked the right tool to fix my broken bicycle."
  },
  {
    "stage": "4B",
    "unit": "Unit 8",
    "lesson": "Lesson 3",
    "word": "generation",
    "explanation": "a group of people born and living during the same time",
    "ipa": "/ˌdʒenəˈreɪʃn/",
    "example": "Our generation must care for the planet for future kids."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 1",
    "word": "design",
    "explanation": "to plan and make decisions about (something that is being built or created)",
    "ipa": "/dɪˈzaɪn/",
    "example": "The children helped design the new playground at our school."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 1",
    "word": "cross the road",
    "explanation": "to walk from one side of the road to the other",
    "ipa": "/krɒs ðə rəʊd/",
    "example": "Always look both ways before you cross the road."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 1",
    "word": "follow (the) directions",
    "explanation": "to do what someone tells you or to go the way someone shows you",
    "ipa": "/ˈfɒləʊ ðə dəˈrekʃnz/",
    "example": "Follow the directions on the map to find the park."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 1",
    "word": "go past (the traffic lights)",
    "explanation": "to move beyond something — like walking or driving beyond the traffic lights",
    "ipa": "/ɡəʊ pɑːst ðə ˈtræfɪk laɪts/",
    "example": "Go past the traffic lights and you will see my house."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 1",
    "word": "information",
    "explanation": "knowledge that you get about someone or something",
    "ipa": "/ˌɪnfəˈmeɪʃn/",
    "example": "Our teacher gave us information about the school trip."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 1",
    "word": "go straight on",
    "explanation": "to keep moving in the same direction without turning",
    "ipa": "/ɡəʊ streɪt ɒn/",
    "example": "Go straight on until you reach the big bookshop."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 1",
    "word": "sight",
    "explanation": "the interesting places, especially in a town or city, that are often visited by tourists",
    "ipa": "/saɪt/",
    "example": "We visited many famous sights on our holiday in London."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 1",
    "word": "turn left/right",
    "explanation": "to change direction and move to the left or right",
    "ipa": "/tɜːn left raɪt/",
    "example": "Turn left at the corner to find the playground."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 1",
    "word": "location",
    "explanation": "a place or position",
    "ipa": "/ləʊˈkeɪʃn/",
    "example": "The new playground has a sunny location near our school."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 1",
    "word": "scavenger hunt",
    "explanation": "a game in which players have to find various objects",
    "ipa": "/ˈskævɪndʒə hʌnt/",
    "example": "We played a fun scavenger hunt in the garden on Saturday."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 1",
    "word": "treasure",
    "explanation": "a collection of valuable things such as gold, silver and jewellery",
    "ipa": "/ˈtreʒə/",
    "example": "The pirates buried their treasure on a tiny island."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 1",
    "word": "go around the corner",
    "explanation": "to walk or move past a bend or turning in the road",
    "ipa": "/ɡəʊ əˈraʊnd ðə ˈkɔːnə/",
    "example": "Go around the corner and you will see the ice cream shop."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 1",
    "word": "mark",
    "explanation": "to give marks to students' work",
    "ipa": "/mɑːk/",
    "example": "My teacher will mark our spelling test tonight at home."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 2",
    "word": "cheap",
    "explanation": "not costing a lot of money",
    "ipa": "/tʃiːp/",
    "example": "The little toy car was very cheap at the shop."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 2",
    "word": "expensive",
    "explanation": "costing a lot of money",
    "ipa": "/ɪkˈspensɪv/",
    "example": "That shiny new bike is too expensive for my pocket money."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 2",
    "word": "collection",
    "explanation": "a group of objects, often of the same sort, that have been collected",
    "ipa": "/kəˈlekʃn/",
    "example": "My sister has a big collection of pretty seashells."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 2",
    "word": "bank",
    "explanation": "a business where people keep their money, borrow money, etc.",
    "ipa": "/bæŋk/",
    "example": "Dad went to the bank to get some cash today."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 2",
    "word": "fish",
    "explanation": "to catch or try to catch fish",
    "ipa": "/fɪʃ/",
    "example": "We like to fish in the little pond on weekends."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 2",
    "word": "ferry",
    "explanation": "a boat or ship that carries people, vehicles and goods across a river or across a narrow part of the sea",
    "ipa": "/ˈferi/",
    "example": "We took a ferry across the river on our holiday."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 2",
    "word": "spend",
    "explanation": "to pay for something",
    "ipa": "/spend/",
    "example": "I want to spend my pocket money on a new book."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 2",
    "word": "shopping centre (AmE shopping center)",
    "explanation": "a group of shops built together, sometimes under one roof",
    "ipa": "/ˈʃɒpɪŋ ˈsentə/",
    "example": "Mum took us to the shopping centre on Saturday morning."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 2",
    "word": "ticket",
    "explanation": "a piece of paper that allows you to see a show, participate in an event, travel on a vehicle, etc.",
    "ipa": "/ˈtɪkɪt/",
    "example": "Dad bought a ticket for the puppet show this weekend."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 2",
    "word": "skyscraper",
    "explanation": "a very tall building in a city",
    "ipa": "/ˈskaɪskreɪpə/",
    "example": "The shiny skyscraper in the city touches the fluffy clouds."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 2",
    "word": "try",
    "explanation": "to make an effort to do something",
    "ipa": "/traɪ/",
    "example": "I will try to finish my homework before dinner tonight."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 2",
    "word": "square",
    "explanation": "an open area in a town, usually with four sides, surrounded by buildings",
    "ipa": "/skweə/",
    "example": "Children played with balloons in the town square on Sunday."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 2",
    "word": "steps",
    "explanation": "the surfaces that you walk on when you go up or down stairs",
    "ipa": "/steps/",
    "example": "We sat on the steps in front of our house."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 2",
    "word": "outer space",
    "explanation": "the area outside the earth's atmosphere where all the other planets and stars are",
    "ipa": "/ˈaʊtə speɪs/",
    "example": "Astronauts travel to outer space inside very fast rockets."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 2",
    "word": "bagel",
    "explanation": "a hard bread roll in the shape of a ring",
    "ipa": "/ˈbeɪɡl/",
    "example": "I ate a warm bagel with cream cheese for breakfast."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 2",
    "word": "chewy",
    "explanation": "needing to be chewed a lot before it can be eaten",
    "ipa": "/ˈtʃuːi/",
    "example": "The toffee sweets in my lunchbox are very chewy."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 3",
    "word": "opinion",
    "explanation": "your feelings or thoughts about somebody/something, rather than a fact",
    "ipa": "/əˈpɪnjən/",
    "example": "My opinion is that puppies make the very best pets."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 3",
    "word": "origin",
    "explanation": "the beginning or cause of something",
    "ipa": "/ˈɒrɪdʒɪn/",
    "example": "Our teacher told us about the origin of the pizza."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 3",
    "word": "material",
    "explanation": "a substance that things can be made from",
    "ipa": "/məˈtɪəriəl/",
    "example": "We used soft material to make a cosy dog bed."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 3",
    "word": "local",
    "explanation": "belonging to or connected with the particular place or area that you are talking about or with the place where you live",
    "ipa": "/ˈləʊkl/",
    "example": "We buy fresh apples from the local farm every weekend."
  },
  {
    "stage": "4B",
    "unit": "Unit 9",
    "lesson": "Lesson 3",
    "word": "jog",
    "explanation": "to run slowly especially for exercise",
    "ipa": "/dʒɒɡ/",
    "example": "Dad and I jog around the park every Saturday morning."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 1",
    "word": "social media",
    "explanation": "websites and software programs used for social networking",
    "ipa": "/ˈsəʊʃl ˈmiːdiə/",
    "example": "Mum says I'm too young to use social media yet."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 1",
    "word": "album",
    "explanation": "a book in which you keep photographs, stamps, etc.",
    "ipa": "/ˈælbəm/",
    "example": "Grandma showed me an old album full of family photos."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 1",
    "word": "app",
    "explanation": "a piece of software that you can download to a device such as a smartphone or tablet, for example to look up information or to play a game",
    "ipa": "/æp/",
    "example": "Dad downloaded a new maths app for my tablet."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 1",
    "word": "print",
    "explanation": "to cause (words, images, etc.) to appear on paper or cloth by using a machine (called a printer)",
    "ipa": "/prɪnt/",
    "example": "My teacher asked me to print the homework on white paper."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 1",
    "word": "digital",
    "explanation": "of or relating to information that is stored in the form of the numbers 0 and 1",
    "ipa": "/ˈdɪdʒɪtl/",
    "example": "I keep all my holiday photos in a digital album."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 1",
    "word": "show",
    "explanation": "to let somebody see something",
    "ipa": "/ʃəʊ/",
    "example": "Please show me your new puppy after school today."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 1",
    "word": "download",
    "explanation": "to get data from another computer, usually using the internet",
    "ipa": "/ˌdaʊnˈləʊd/",
    "example": "Can I download this game onto your phone, Dad?"
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 1",
    "word": "comment",
    "explanation": "something that you say or write that gives an opinion on or explains somebody/something",
    "ipa": "/ˈkɒment/",
    "example": "My friend left a kind comment under my drawing online."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 1",
    "word": "internet",
    "explanation": "a system that connects computers throughout the world",
    "ipa": "/ˈɪntənet/",
    "example": "We use the internet to find fun science facts at home."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 1",
    "word": "post",
    "explanation": "to put information or pictures on a website",
    "ipa": "/pəʊst/",
    "example": "Mum likes to post photos of our dog online."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 1",
    "word": "upload",
    "explanation": "to send data to another computer",
    "ipa": "/ˌʌpˈləʊd/",
    "example": "I'll upload my school project to the class website tonight."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 1",
    "word": "share",
    "explanation": "to give some of what you have to somebody else",
    "ipa": "/ʃeə(r)/",
    "example": "I always share my cookies with my little sister."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 1",
    "word": "film",
    "explanation": "special thin plastic used for making photographs or moving pictures, used in cameras",
    "ipa": "/fɪlm/",
    "example": "Grandpa's old camera still needs a roll of film."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 1",
    "word": "rugby",
    "explanation": "A game played by two teams of 13 or 15 players, using an oval ball which may be kicked or carried. Teams try to put the ball over the other team's line.",
    "ipa": "/ˈrʌɡbi/",
    "example": "My brother plays rugby with his friends every Saturday morning."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 1",
    "word": "selfie",
    "explanation": "a photo of yourself that you take, typically with a smartphone or webcam, and usually put on social media",
    "ipa": "/ˈselfi/",
    "example": "We took a funny selfie with the puppy at the park."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 1",
    "word": "sticker",
    "explanation": "a small digital image that you can use to express an idea or emotion on social media or on a messaging app",
    "ipa": "/ˈstɪkə(r)/",
    "example": "I sent Mum a smiling cat sticker after lunch."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 2",
    "word": "invent",
    "explanation": "to create or produce (something useful) for the first time",
    "ipa": "/ɪnˈvent/",
    "example": "One day I want to invent a robot that cleans rooms."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 2",
    "word": "programme (AmE program)",
    "explanation": "something that people watch on television or listen to on the radio",
    "ipa": "/ˈprəʊɡræm/",
    "example": "My favourite programme about animals starts at seven tonight."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 2",
    "word": "quality",
    "explanation": "how good or bad something is",
    "ipa": "/ˈkwɒləti/",
    "example": "The quality of this new cartoon is really wonderful."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 2",
    "word": "record",
    "explanation": "to store (something, such as sounds, music, images, etc.) on tape or on a disk so that it can be heard or seen later",
    "ipa": "/rɪˈkɔːd/",
    "example": "Dad will record the football match for me to watch later."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 2",
    "word": "technology",
    "explanation": "the use of science in industry, engineering, etc., to invent useful things or to solve problems",
    "ipa": "/tekˈnɒlədʒi/",
    "example": "New technology helps farmers grow tastier fruit and vegetables."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 2",
    "word": "entertain",
    "explanation": "to interest somebody or make somebody laugh in order to please them",
    "ipa": "/ˌentəˈteɪn/",
    "example": "Dad tells funny stories to entertain us during long car trips."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 2",
    "word": "imagine",
    "explanation": "to form a picture in your mind of what something might be like",
    "ipa": "/ɪˈmædʒɪn/",
    "example": "I like to imagine flying over the mountains with my dog."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 2",
    "word": "cartoon",
    "explanation": "an animated film or television show",
    "ipa": "/kɑːˈtuːn/",
    "example": "My little brother watches a cartoon about rabbits every morning."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 2",
    "word": "documentary",
    "explanation": "a film or a radio or television programme giving facts about something",
    "ipa": "/ˌdɒkjuˈmentri/",
    "example": "We watched a documentary about pandas in the bamboo forest."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 2",
    "word": "news",
    "explanation": "information that is reported in a newspaper, magazine, television news programme, etc.",
    "ipa": "/njuːz/",
    "example": "Grandpa watches the evening news while eating his dinner."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 2",
    "word": "reality show",
    "explanation": "television shows that are based on real people (not actors) in real situations, presented as entertainment",
    "ipa": "/riˈæləti ʃəʊ/",
    "example": "Mum loves a cooking reality show with real families competing."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 2",
    "word": "series",
    "explanation": "a set of regularly presented television shows involving the same group of characters or the same subject",
    "ipa": "/ˈsɪəriːz/",
    "example": "My favourite series about magic ponies has a new episode tonight."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 2",
    "word": "sitcom",
    "explanation": "a regular comedy programme on television that shows the same characters in different funny situations",
    "ipa": "/ˈsɪtkɒm/",
    "example": "We laugh together at our favourite family sitcom every Friday night."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 2",
    "word": "virtual reality",
    "explanation": "images and sounds created by a computer that seem almost real to the user, who can interact with them by using sensors (= VR)",
    "ipa": "/ˌvɜːtʃuəl riˈæləti/",
    "example": "My cousin tried virtual reality and swam with friendly cartoon dolphins."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 3",
    "word": "follower",
    "explanation": "a person who chooses to regularly receive somebody's messages using a social media service",
    "ipa": "/ˈfɒləʊə(r)/",
    "example": "My aunt has a new follower on her cooking page today."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 3",
    "word": "channel",
    "explanation": "a television station",
    "ipa": "/ˈtʃænl/",
    "example": "There is a channel that shows cartoons all day long."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 3",
    "word": "review",
    "explanation": "a report in the media in which someone gives their opinion of something such as a new book or movie",
    "ipa": "/rɪˈvjuː/",
    "example": "I read a great review of that new dinosaur film online."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 3",
    "word": "review (verb)",
    "explanation": "to write a report of a book, play, film, product, etc. in which you give your opinion of it",
    "ipa": "/rɪˈvjuː/",
    "example": "My sister loves to review her favourite story books online."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 3",
    "word": "voice",
    "explanation": "the sounds that are made when people speak or sing",
    "ipa": "/vɔɪs/",
    "example": "My grandma has a soft, kind voice when she sings."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 3",
    "word": "generous",
    "explanation": "freely giving or sharing money and other valuable things",
    "ipa": "/ˈdʒenərəs/",
    "example": "My generous uncle always brings sweets for all the children."
  },
  {
    "stage": "4B",
    "unit": "Unit 10",
    "lesson": "Lesson 3",
    "word": "neighbourhood (AmE neighborhood)",
    "explanation": "a district or an area of a town",
    "ipa": "/ˈneɪbəhʊd/",
    "example": "Lots of friendly cats live in our quiet neighbourhood."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 1",
    "word": "destination",
    "explanation": "a place to which a person is going or something is being sent",
    "ipa": "/ˌdestɪˈneɪʃn/",
    "example": "Our holiday destination this summer is a sunny beach in Spain."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 1",
    "word": "bus stop",
    "explanation": "a place at the side of a road that is marked with a sign, where buses stop",
    "ipa": "/bʌs stɒp/",
    "example": "Mum waits with me at the bus stop every school morning."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 1",
    "word": "get on",
    "explanation": "to enter a vehicle (bus, train, plane, etc.)",
    "ipa": "/ɡet ɒn/",
    "example": "We get on the school bus right after breakfast each day."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 1",
    "word": "driver",
    "explanation": "a person who drives a vehicle",
    "ipa": "/ˈdraɪvə(r)/",
    "example": "Our bus driver smiled and waved at every child this morning."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 1",
    "word": "get off",
    "explanation": "to leave a vehicle (bus, train, plane, etc.)",
    "ipa": "/ɡet ɒf/",
    "example": "We get off the train at the next stop near grandma's house."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 1",
    "word": "bike lane",
    "explanation": "a part of a road that only bicycles are allowed to use",
    "ipa": "/baɪk leɪn/",
    "example": "Dad and I rode safely along the new bike lane on Sunday."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 1",
    "word": "parking",
    "explanation": "a space or an area for leaving vehicles",
    "ipa": "/ˈpɑːkɪŋ/",
    "example": "The parking near the playground was full on Saturday afternoon."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 1",
    "word": "tram",
    "explanation": "a vehicle that travels on streets on metal tracks and that is used for carrying passengers",
    "ipa": "/træm/",
    "example": "We took a bright yellow tram to the museum in the city."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 1",
    "word": "pedestrian",
    "explanation": "a person walking in the street and not travelling in a vehicle",
    "ipa": "/pəˈdestriən/",
    "example": "A kind pedestrian helped my little brother cross the busy road."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 1",
    "word": "motorbike",
    "explanation": "a road vehicle with two wheels, driven by an engine, with one seat for the driver and often a seat for a passenger behind the driver",
    "ipa": "/ˈməʊtəbaɪk/",
    "example": "My uncle rides his shiny red motorbike to work every day."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 1",
    "word": "traffic",
    "explanation": "the vehicles that are on a road at a particular time",
    "ipa": "/ˈtræfɪk/",
    "example": "The traffic was very heavy on our way home from school."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 1",
    "word": "scooter",
    "explanation": "a light motorbike, usually with small wheels and a curved cover at the front to protect the rider's legs",
    "ipa": "/ˈskuːtə(r)/",
    "example": "My cousin rides a little blue scooter to the corner shop."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 1",
    "word": "resident",
    "explanation": "a person who lives in a particular place or who has their home there",
    "ipa": "/ˈrezɪdənt/",
    "example": "Every resident on our street came to the weekend garden party."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 1",
    "word": "transport (AmE transportation)",
    "explanation": "a system for carrying people or goods from one place to another using vehicles, roads, etc.",
    "ipa": "/ˈtrænspɔːt/",
    "example": "Buses and trains are the main transport in our small town."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 1",
    "word": "planner",
    "explanation": "a person whose job is to plan the growth and development of a town",
    "ipa": "/ˈplænə(r)/",
    "example": "The town planner showed us a map of the new playground."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 2",
    "word": "passenger",
    "explanation": "a person who is travelling in a car, bus, train, plane or ship and who is not driving it or working on it",
    "ipa": "/ˈpæsɪndʒə(r)/",
    "example": "Every passenger on the bus smiled at the cute little puppy."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 2",
    "word": "track",
    "explanation": "rails (= metal bars) that a train moves along",
    "ipa": "/træk/",
    "example": "We watched the long train rumble loudly along the shiny track."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 2",
    "word": "billion",
    "explanation": "1,000,000,000; one thousand million",
    "ipa": "/ˈbɪljən/",
    "example": "More than a billion people around the world love football."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 2",
    "word": "display",
    "explanation": "to put something in a place where people can see it easily",
    "ipa": "/dɪˈspleɪ/",
    "example": "Our teacher will display our paintings on the classroom wall today."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 2",
    "word": "inspector",
    "explanation": "a person whose job is to check tickets on a bus or train",
    "ipa": "/ɪnˈspektə(r)/",
    "example": "The friendly inspector checked our tickets on the train to London."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 2",
    "word": "escalator",
    "explanation": "moving stairs that carry people between different floors of a large building",
    "ipa": "/ˈeskəleɪtə(r)/",
    "example": "We rode the long escalator up to the toy shop floor."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 2",
    "word": "lift",
    "explanation": "a machine that carries people or goods up and down to different levels in a building or a mine",
    "ipa": "/lɪft/",
    "example": "We took the lift up to the tenth floor of the hotel."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 2",
    "word": "gallery",
    "explanation": "a room or building for showing works of art, especially to the public",
    "ipa": "/ˈɡæləri/",
    "example": "Our class visited a bright art gallery on Friday afternoon."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 2",
    "word": "loudspeaker",
    "explanation": "a device that is used to make sound (such as music or a person's voice) louder and to send it out so that many people can hear it in a public space",
    "ipa": "/ˌlaʊdˈspiːkə(r)/",
    "example": "The loudspeaker at the station told us our train was late."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 2",
    "word": "ticket machine",
    "explanation": "an automatic device that sells tickets for public transportation (trains, buses, etc.), parking, or events without needing a human cashier",
    "ipa": "/ˈtɪkɪt məˌʃiːn/",
    "example": "Dad bought our train tickets from the shiny ticket machine quickly."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 2",
    "word": "timetable",
    "explanation": "a chart showing the times at which trains, buses and planes leave and arrive",
    "ipa": "/ˈtaɪmteɪbl/",
    "example": "We checked the timetable to find the next train to grandma's."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 2",
    "word": "the planet",
    "explanation": "the planet Earth",
    "ipa": "/ðə ˈplænɪt/",
    "example": "We must take care of the planet by recycling our rubbish."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 2",
    "word": "chandelier",
    "explanation": "a large, decorated light that hangs from a ceiling and has branches for holding many light bulbs or candles",
    "ipa": "/ˌʃændəˈlɪə(r)/",
    "example": "A huge sparkling chandelier hung above the dining table at grandma's."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 2",
    "word": "mosaic",
    "explanation": "a picture or pattern made by placing together small pieces of glass, stone, etc. of different colours",
    "ipa": "/məʊˈzeɪɪk/",
    "example": "We made a beautiful mosaic of a fish in art class today."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 2",
    "word": "sculpture",
    "explanation": "a work of art that is a solid figure or object made by carving or shaping wood, stone, clay, metal, etc.",
    "ipa": "/ˈskʌlptʃə(r)/",
    "example": "A tall stone sculpture of a lion stood near the museum door."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 3",
    "word": "pass",
    "explanation": "a card or ticket which shows that you are allowed to enter or leave a particular place or to ride a vehicle",
    "ipa": "/pɑːs/",
    "example": "I showed my bus pass to the driver before sitting down."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 3",
    "word": "gondola",
    "explanation": "a long boat with a flat bottom and high parts at each end, used on canals in Venice",
    "ipa": "/ˈɡɒndələ/",
    "example": "We rode a black gondola along a quiet canal in Venice."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 3",
    "word": "romantic",
    "explanation": "making someone think of love",
    "ipa": "/rəʊˈmæntɪk/",
    "example": "Mum says a sunset boat ride is very romantic and sweet."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 3",
    "word": "cable car",
    "explanation": "a vehicle that hangs from and is pulled by a moving cable and that carries passengers up and down a mountain",
    "ipa": "/ˈkeɪbl kɑː(r)/",
    "example": "We rode a swinging cable car up the snowy mountain yesterday."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 3",
    "word": "means",
    "explanation": "a way of achieving or doing something",
    "ipa": "/miːnz/",
    "example": "Riding bikes is a fun means of getting to school quickly."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 3",
    "word": "aquarium",
    "explanation": "a building where people can go to see fish and other water creatures",
    "ipa": "/əˈkweəriəm/",
    "example": "We saw a giant turtle at the aquarium on Saturday morning."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 3",
    "word": "entire",
    "explanation": "including everything, everyone or every part",
    "ipa": "/ɪnˈtaɪə(r)/",
    "example": "My entire family went to the park for a big picnic."
  },
  {
    "stage": "4B",
    "unit": "Unit 11",
    "lesson": "Lesson 3",
    "word": "distance",
    "explanation": "the amount of space between two places or things",
    "ipa": "/ˈdɪstəns/",
    "example": "The distance from our house to school is about one kilometre."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 1",
    "word": "check",
    "explanation": "to look at (something) carefully to find mistakes, problems, etc., or to make sure there is nothing wrong with it",
    "ipa": "/tʃek/",
    "example": "Please check your homework before you put it in your bag."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 1",
    "word": "artist",
    "explanation": "a person who creates art",
    "ipa": "/ˈɑːtɪst/",
    "example": "My sister wants to be an artist when she grows up."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 1",
    "word": "patient",
    "explanation": "able to wait for a long time or accept annoying behaviour or difficulties without becoming angry",
    "ipa": "/ˈpeɪʃnt/",
    "example": "Be patient and wait for your turn on the slide."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 1",
    "word": "chef",
    "explanation": "a professional cook who usually is in charge of a kitchen in a restaurant",
    "ipa": "/ʃef/",
    "example": "The chef made us a delicious pizza for dinner."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 1",
    "word": "customer",
    "explanation": "a person who buys goods or services from a shop or business",
    "ipa": "/ˈkʌstəmə(r)/",
    "example": "The shop owner smiled kindly at every customer who came in."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 1",
    "word": "detective",
    "explanation": "a person, especially a police officer, whose job is to investigate crimes and catch criminals",
    "ipa": "/dɪˈtektɪv/",
    "example": "The detective found important clues at the playground."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 1",
    "word": "queue",
    "explanation": "a line of people, cars, etc. waiting for something or to do something",
    "ipa": "/kjuː/",
    "example": "We stood in a long queue to buy ice cream."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 1",
    "word": "mechanic",
    "explanation": "a person whose job is repairing machines, especially the engines of vehicles",
    "ipa": "/məˈkænɪk/",
    "example": "The mechanic fixed our car after it broke down on holiday."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 1",
    "word": "opinion",
    "explanation": "your feelings or thoughts about somebody/something, rather than a fact",
    "ipa": "/əˈpɪnjən/",
    "example": "In my opinion, chocolate ice cream is the best flavour."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 1",
    "word": "reporter",
    "explanation": "a person who collects and reports news for newspapers, radio or television",
    "ipa": "/rɪˈpɔːtə(r)/",
    "example": "The reporter asked the children about their school sports day."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 1",
    "word": "skill",
    "explanation": "a particular ability or type of ability",
    "ipa": "/skɪl/",
    "example": "Riding a bike is a useful skill to learn."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 1",
    "word": "sailor",
    "explanation": "a person who works on a ship as a member of the crew",
    "ipa": "/ˈseɪlə(r)/",
    "example": "The brave sailor waved to us from the big ship."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 1",
    "word": "tax",
    "explanation": "money that you have to pay to the government so that it can pay for public services",
    "ipa": "/tæks/",
    "example": "Dad said we pay tax to help build new schools and roads."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 1",
    "word": "desire",
    "explanation": "a strong wish to have or do something",
    "ipa": "/dɪˈzaɪə(r)/",
    "example": "She had a strong desire to visit the zoo on Saturday."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 1",
    "word": "sense",
    "explanation": "one of the five powers (sight, hearing, smell, taste and touch) that your body uses to get information about the world around you",
    "ipa": "/sens/",
    "example": "Dogs have a much better sense of smell than people."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 1",
    "word": "taste",
    "explanation": "the sense you have that allows you to recognize different foods and drinks when you put them in your mouth",
    "ipa": "/teɪst/",
    "example": "My sense of taste is weaker when I have a cold."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 1",
    "word": "taste (verb)",
    "explanation": "to test the taste of something by eating or drinking a small amount of it",
    "ipa": "/teɪst/",
    "example": "Please taste the soup and tell me if it needs more salt."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "designer",
    "explanation": "a person who plans how something new will look and be made",
    "ipa": "/dɪˈzaɪnə(r)/",
    "example": "The designer drew a pretty dress for the school play."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "day off",
    "explanation": "a day on which you do not have to work",
    "ipa": "/deɪ ɒf/",
    "example": "Mum took a day off so we could go to the park."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "focus on",
    "explanation": "to give attention, effort, or energy to one specific task, goal, or activity",
    "ipa": "/ˈfəʊkəs ɒn/",
    "example": "Try to focus on your reading and ignore the noise outside."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "full-time",
    "explanation": "done during the full number of hours considered normal or standard",
    "ipa": "/ˌfʊl ˈtaɪm/",
    "example": "My dad has a full-time job at the hospital."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "part-time",
    "explanation": "working or involving fewer hours than is considered normal or standard",
    "ipa": "/ˌpɑːt ˈtaɪm/",
    "example": "My aunt has a part-time job at the small bakery."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "job",
    "explanation": "the work that a person does regularly in order to earn money",
    "ipa": "/dʒɒb/",
    "example": "My mum has a job at a busy children's hospital."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "author",
    "explanation": "a person who writes books or the person who wrote a particular book",
    "ipa": "/ˈɔːθə(r)/",
    "example": "The author of my favourite story book visited our school."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "career",
    "explanation": "the job or series of jobs that you do during your working life, especially if you continue to get better jobs and earn more money",
    "ipa": "/kəˈrɪə(r)/",
    "example": "She wants a career as a doctor when she grows up."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "employee",
    "explanation": "a person who is paid to work for somebody",
    "ipa": "/ɪmˈplɔɪiː/",
    "example": "Every employee at the toy shop wore a bright red shirt."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "experience",
    "explanation": "the knowledge and skill that you have gained through doing something for a period of time",
    "ipa": "/ɪkˈspɪəriəns/",
    "example": "Grandma has lots of experience baking yummy birthday cakes."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "manager",
    "explanation": "a person who is in charge of running a business, a shop or a similar organisation or part of one",
    "ipa": "/ˈmænɪdʒə(r)/",
    "example": "The manager of the bookshop helped us find a fun story."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "staff",
    "explanation": "a group of people who work for an organisation or business",
    "ipa": "/stɑːf/",
    "example": "The staff at our school are kind and very helpful."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "organisation (AmE organization)",
    "explanation": "a group of people who form a business, club, etc. together in order to achieve a particular aim",
    "ipa": "/ˌɔːɡənaɪˈzeɪʃn/",
    "example": "We joined an organisation that helps look after stray puppies."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "the Arctic",
    "explanation": "the regions of the world around the North Pole",
    "ipa": "/ðə ˈɑːktɪk/",
    "example": "Polar bears and seals live in the Arctic all year round."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "surface",
    "explanation": "the outside or top layer of something",
    "ipa": "/ˈsɜːfɪs/",
    "example": "Tiny ants crawled across the surface of the picnic table."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "rover",
    "explanation": "a spacecraft designed to move on a planet or moon",
    "ipa": "/ˈrəʊvə(r)/",
    "example": "The rover sent back amazing photos from the surface of Mars."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "greenhouse",
    "explanation": "a building with glass sides and a glass roof for growing plants in",
    "ipa": "/ˈɡriːnhaʊs/",
    "example": "Grandpa grows juicy tomatoes inside his little greenhouse."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "shelter",
    "explanation": "a structure built to give protection, especially from the weather or from attack",
    "ipa": "/ˈʃeltə(r)/",
    "example": "We built a shelter from branches to hide from the rain."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "planetary",
    "explanation": "relating to a planet or planets",
    "ipa": "/ˈplænətri/",
    "example": "The museum had a cool planetary display about Jupiter and Mars."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "toxic",
    "explanation": "containing poison",
    "ipa": "/ˈtɒksɪk/",
    "example": "Never touch toxic plants or berries you find in the woods."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 2",
    "word": "dust",
    "explanation": "a fine powder that consists of very small pieces of sand, earth, etc.",
    "ipa": "/dʌst/",
    "example": "There was a thick layer of dust on the old toy box."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 3",
    "word": "submarine",
    "explanation": "a ship that can travel underwater",
    "ipa": "/ˌsʌbməˈriːn/",
    "example": "The yellow submarine dived deep to see colourful fish."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 3",
    "word": "attract",
    "explanation": "to cause (someone or something) to go to or move to or towards a place",
    "ipa": "/əˈtrækt/",
    "example": "Sweet flowers attract bees and butterflies to our garden."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 3",
    "word": "brave",
    "explanation": "willing to do things that are difficult or dangerous; not afraid",
    "ipa": "/breɪv/",
    "example": "My little brother was very brave at the dentist today."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 3",
    "word": "professional",
    "explanation": "doing something as a paid job rather than as a hobby",
    "ipa": "/prəˈfeʃənl/",
    "example": "My cousin is a professional football player on a big team."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 3",
    "word": "worry",
    "explanation": "something that worries you",
    "ipa": "/ˈwʌri/",
    "example": "My biggest worry is forgetting my lines in the school play."
  },
  {
    "stage": "4B",
    "unit": "Unit 12",
    "lesson": "Lesson 3",
    "word": "seriously",
    "explanation": "in a serious way",
    "ipa": "/ˈsɪəriəsli/",
    "example": "The coach spoke seriously about playing safely on the field."
  }
]

export const SYLLABLE_MAP_4B: Record<string, string[]> = {
  "active": ["ac", "tive"],
  "air conditioning": ["air", "con", "di", "tion", "ing"],
  "album": ["al", "bum"],
  "alive": ["a", "live"],
  "app": ["app"],
  "aquarium": ["a", "quar", "i", "um"],
  "artist": ["ar", "tist"],
  "association": ["as", "so", "ci", "a", "tion"],
  "attract": ["at", "tract"],
  "author": ["au", "thor"],
  "bagel": ["ba", "gel"],
  "bank": ["bank"],
  "battery": ["bat", "ter", "y"],
  "bike lane": ["bike", "lane"],
  "billion": ["bil", "lion"],
  "branch": ["branch"],
  "brave": ["brave"],
  "bus stop": ["bus", "stop"],
  "by mistake": ["by", "mi", "stake"],
  "cable car": ["ca", "ble", "car"],
  "can": ["can"],
  "cardboard": ["card", "board"],
  "career": ["ca", "reer"],
  "cartoon": ["car", "toon"],
  "cause": ["cause"],
  "chandelier": ["chan", "de", "lier"],
  "channel": ["chan", "nel"],
  "cheap": ["cheap"],
  "check": ["check"],
  "chef": ["chef"],
  "chewy": ["chew", "y"],
  "climate": ["cli", "mate"],
  "collection": ["col", "lec", "tion"],
  "comment": ["com", "ment"],
  "cover": ["cov", "er"],
  "creature": ["crea", "ture"],
  "cross the road": ["cross", "the", "road"],
  "curious": ["cu", "ri", "ous"],
  "customer": ["cus", "to", "mer"],
  "day off": ["day", "off"],
  "design": ["de", "sign"],
  "designer": ["de", "sign", "er"],
  "desire": ["de", "sire"],
  "destination": ["des", "ti", "na", "tion"],
  "destroy": ["de", "stroy"],
  "detective": ["de", "tec", "tive"],
  "digital": ["dig", "i", "tal"],
  "display": ["dis", "play"],
  "distance": ["dis", "tance"],
  "documentary": ["doc", "u", "men", "ta", "ry"],
  "download": ["down", "load"],
  "drip": ["drip"],
  "driver": ["dri", "ver"],
  "dump": ["dump"],
  "dust": ["dust"],
  "ecosystem": ["e", "co", "sys", "tem"],
  "electronics": ["e", "lec", "tron", "ics"],
  "employee": ["em", "ploy", "ee"],
  "endangered": ["en", "dan", "gered"],
  "entertain": ["en", "ter", "tain"],
  "entire": ["en", "tire"],
  "environmental": ["en", "vi", "ron", "men", "tal"],
  "erupt": ["e", "rupt"],
  "escalator": ["es", "ca", "la", "tor"],
  "expensive": ["ex", "pen", "sive"],
  "experience": ["ex", "pe", "ri", "ence"],
  "explorer": ["ex", "plor", "er"],
  "fan": ["fan"],
  "ferry": ["fer", "ry"],
  "film": ["film"],
  "fish": ["fish"],
  "focus on": ["fo", "cus", "on"],
  "follow (the) directions": ["fol", "low", "the", "di", "rec", "tions"],
  "follower": ["fol", "low", "er"],
  "free": ["free"],
  "full-time": ["full", "time"],
  "gallery": ["gal", "ler", "y"],
  "generation": ["gen", "er", "a", "tion"],
  "generous": ["gen", "er", "ous"],
  "get off": ["get", "off"],
  "get on": ["get", "on"],
  "global warming": ["glo", "bal", "warm", "ing"],
  "go around the corner": ["go", "a", "round", "the", "cor", "ner"],
  "go past (the traffic lights)": ["go", "past", "the", "traf", "fic", "lights"],
  "go straight on": ["go", "straight", "on"],
  "gondola": ["gon", "do", "la"],
  "green": ["green"],
  "greenhouse": ["green", "house"],
  "handle": ["han", "dle"],
  "humid": ["hu", "mid"],
  "iguana": ["i", "gua", "na"],
  "imagine": ["i", "ma", "gine"],
  "improve": ["im", "prove"],
  "information": ["in", "for", "ma", "tion"],
  "inspector": ["in", "spec", "tor"],
  "internet": ["in", "ter", "net"],
  "invent": ["in", "vent"],
  "job": ["job"],
  "jog": ["jog"],
  "jungle": ["jun", "gle"],
  "landfill": ["land", "fill"],
  "lay eggs": ["lay", "eggs"],
  "leaf": ["leaf"],
  "lift": ["lift"],
  "liquid": ["liq", "uid"],
  "local": ["lo", "cal"],
  "location": ["lo", "ca", "tion"],
  "loudspeaker": ["loud", "speak", "er"],
  "manager": ["man", "a", "ger"],
  "mark": ["mark"],
  "massive": ["mas", "sive"],
  "material": ["ma", "te", "ri", "al"],
  "means": ["means"],
  "mechanic": ["me", "chan", "ic"],
  "mosaic": ["mo", "sa", "ic"],
  "motorbike": ["mo", "tor", "bike"],
  "national park": ["na", "tion", "al", "park"],
  "neighbourhood (ame neighborhood)": ["neigh", "bour", "hood"],
  "nest": ["nest"],
  "news": ["news"],
  "newspaper": ["news", "pa", "per"],
  "ocean": ["o", "cean"],
  "oil": ["oil"],
  "opinion": ["o", "pin", "ion"],
  "organisation (ame organization)": ["or", "gan", "i", "sa", "tion"],
  "origin": ["or", "i", "gin"],
  "outer space": ["out", "er", "space"],
  "oxygen": ["ox", "y", "gen"],
  "parking": ["par", "king"],
  "part-time": ["part", "time"],
  "pass": ["pass"],
  "passenger": ["pas", "sen", "ger"],
  "patient": ["pa", "tient"],
  "pedestrian": ["pe", "des", "tri", "an"],
  "petrol": ["pet", "rol"],
  "planetary": ["plan", "e", "ta", "ry"],
  "planner": ["plan", "ner"],
  "plastic bag": ["plas", "tic", "bag"],
  "pollute": ["pol", "lute"],
  "post": ["post"],
  "print": ["print"],
  "product": ["pro", "duct"],
  "professional": ["pro", "fes", "sion", "al"],
  "programme (ame program)": ["pro", "gramme"],
  "quality": ["qual", "i", "ty"],
  "queue": ["queue"],
  "reality show": ["re", "al", "i", "ty", "show"],
  "record": ["rec", "ord"],
  "recreation": ["rec", "re", "a", "tion"],
  "recycle": ["re", "cy", "cle"],
  "reporter": ["re", "por", "ter"],
  "resident": ["res", "i", "dent"],
  "review": ["re", "view"],
  "review (verb)": ["re", "view"],
  "romantic": ["ro", "man", "tic"],
  "rover": ["ro", "ver"],
  "rubber": ["rub", "ber"],
  "rugby": ["rug", "by"],
  "sailor": ["sai", "lor"],
  "sanctuary": ["sanc", "tu", "ar", "y"],
  "sand": ["sand"],
  "scavenger hunt": ["scav", "en", "ger", "hunt"],
  "scooter": ["scoo", "ter"],
  "sculpture": ["sculp", "ture"],
  "selfie": ["sel", "fie"],
  "sense": ["sense"],
  "series": ["se", "ries"],
  "seriously": ["se", "ri", "ous", "ly"],
  "shade": ["shade"],
  "share": ["share"],
  "shelter": ["shel", "ter"],
  "shopping centre (ame shopping center)": ["shop", "ping", "cen", "tre"],
  "show": ["show"],
  "sight": ["sight"],
  "sitcom": ["sit", "com"],
  "skill": ["skill"],
  "skyscraper": ["sky", "scrap", "er"],
  "slippery": ["slip", "per", "y"],
  "smell": ["smell"],
  "social media": ["so", "cial", "me", "di", "a"],
  "soil": ["soil"],
  "spend": ["spend"],
  "square": ["square"],
  "staff": ["staff"],
  "stem": ["stem"],
  "steps": ["steps"],
  "sticker": ["stick", "er"],
  "sticky": ["stick", "y"],
  "stone": ["stone"],
  "submarine": ["sub", "ma", "rine"],
  "success": ["suc", "cess"],
  "surface": ["sur", "face"],
  "system": ["sys", "tem"],
  "tap water": ["tap", "wa", "ter"],
  "taste": ["taste"],
  "taste (verb)": ["taste"],
  "tax": ["tax"],
  "technology": ["tech", "nol", "o", "gy"],
  "the arctic": ["the", "arc", "tic"],
  "the planet": ["the", "plan", "et"],
  "throw away": ["throw", "a", "way"],
  "ticket": ["tick", "et"],
  "ticket machine": ["tick", "et", "ma", "chine"],
  "timetable": ["time", "ta", "ble"],
  "tool": ["tool"],
  "toxic": ["tox", "ic"],
  "track": ["track"],
  "traffic": ["traf", "fic"],
  "tram": ["tram"],
  "transport (ame transportation)": ["trans", "port"],
  "trap": ["trap"],
  "treasure": ["trea", "sure"],
  "try": ["try"],
  "turn left/right": ["turn", "left", "right"],
  "upload": ["up", "load"],
  "variety": ["va", "ri", "e", "ty"],
  "virtual reality": ["vir", "tu", "al", "re", "al", "i", "ty"],
  "voice": ["voice"],
  "volcano": ["vol", "ca", "no"],
  "waste": ["waste"],
  "wildlife": ["wild", "life"],
  "worry": ["wor", "ry"]
}

export const KW_MAP_4B: Record<string, [string, string][]> = {
  "active": [["likely to explode violently", "kw-red"], ["fire and hot liquid rock", "kw-gold"]],
  "air conditioning": [["cools and dries the air", "kw-red"], ["building or car", "kw-gold"]],
  "album": [["keep photographs", "kw-red"], ["stamps", "kw-gold"]],
  "alive": [["living; not dead", "kw-red"]],
  "app": [["piece of software", "kw-red"], ["smartphone or tablet", "kw-gold"]],
  "aquarium": [["see fish and other water creatures", "kw-red"]],
  "artist": [["creates art", "kw-red"]],
  "association": [["official group of people", "kw-red"], ["particular purpose", "kw-gold"]],
  "attract": [["go to or move to", "kw-red"], ["towards a place", "kw-gold"]],
  "author": [["writes books", "kw-red"], ["wrote a particular book", "kw-gold"]],
  "bagel": [["hard bread roll", "kw-red"], ["shape of a ring", "kw-gold"]],
  "bank": [["people keep their money", "kw-red"], ["borrow money", "kw-gold"]],
  "battery": [["placed inside a machine", "kw-red"], ["supply it with electricity", "kw-gold"]],
  "bike lane": [["only bicycles are allowed", "kw-red"], ["part of a road", "kw-gold"]],
  "billion": [["one thousand million", "kw-red"]],
  "branch": [["part of a tree", "kw-red"], ["grows out from the trunk", "kw-gold"]],
  "brave": [["willing to do things", "kw-red"], ["difficult or dangerous", "kw-gold"]],
  "bus stop": [["side of a road", "kw-red"], ["buses stop", "kw-gold"]],
  "by mistake": [["not planned or organised", "kw-red"]],
  "cable car": [["hangs from", "kw-red"], ["up and down a mountain", "kw-gold"]],
  "can": [["metal container", "kw-red"], ["food and drink is sold", "kw-gold"]],
  "cardboard": [["stiff and thick kind of paper", "kw-red"], ["making boxes", "kw-gold"]],
  "career": [["job or series of jobs", "kw-red"], ["during your working life", "kw-gold"]],
  "cartoon": [["animated film", "kw-red"], ["television show", "kw-gold"]],
  "cause": [["make happen", "kw-red"], ["bad or unpleasant", "kw-gold"]],
  "chandelier": [["hangs from a ceiling", "kw-red"], ["many light bulbs or candles", "kw-gold"]],
  "channel": [["television station", "kw-red"]],
  "cheap": [["not costing a lot of money", "kw-red"]],
  "check": [["find mistakes, problems", "kw-red"], ["make sure", "kw-gold"]],
  "chef": [["professional cook", "kw-red"], ["in charge of a kitchen", "kw-gold"]],
  "chewy": [["needing to be chewed a lot", "kw-red"]],
  "climate": [["regular pattern of weather conditions", "kw-red"]],
  "collection": [["group of objects", "kw-red"], ["have been collected", "kw-gold"]],
  "comment": [["gives an opinion", "kw-red"], ["say or write", "kw-gold"]],
  "cover": [["place over", "kw-red"], ["hide, protect or decorate", "kw-gold"]],
  "creature": [["living thing", "kw-red"], ["can move around", "kw-gold"]],
  "cross the road": [["one side of the road", "kw-red"], ["walk to other side", "kw-gold"]],
  "curious": [["strong desire to know", "kw-red"]],
  "customer": [["buys goods or services", "kw-red"], ["from a shop or business", "kw-gold"]],
  "day off": [["do not have to work", "kw-red"]],
  "design": [["plan and make decisions", "kw-red"]],
  "designer": [["plan new things", "kw-red"], ["will look and be made", "kw-gold"]],
  "desire": [["strong wish", "kw-red"], ["have or do", "kw-gold"]],
  "destination": [["place going to", "kw-red"], ["being sent", "kw-gold"]],
  "destroy": [["damage badly", "kw-red"], ["no longer exists", "kw-gold"]],
  "detective": [["investigate crimes", "kw-red"], ["catch criminals", "kw-gold"]],
  "digital": [["stored in the form", "kw-red"], ["numbers 0 and 1", "kw-gold"]],
  "display": [["people can see it easily", "kw-red"]],
  "distance": [["amount of space between two places", "kw-red"]],
  "documentary": [["giving facts", "kw-red"], ["film or a radio", "kw-gold"]],
  "download": [["get data from another computer", "kw-red"], ["using the internet", "kw-gold"]],
  "drip": [["fall in small drops", "kw-red"]],
  "driver": [["drives a vehicle", "kw-red"]],
  "dump": [["quick and careless way", "kw-red"]],
  "dust": [["fine powder", "kw-red"], ["small pieces of sand, earth", "kw-gold"]],
  "ecosystem": [["plants and living creatures", "kw-red"], ["physical environment", "kw-gold"]],
  "electronics": [["operate using many small electrical parts", "kw-red"]],
  "employee": [["paid to work", "kw-red"]],
  "endangered": [["at risk of no longer existing", "kw-red"]],
  "entertain": [["interest people", "kw-red"], ["make people laugh", "kw-gold"]],
  "entire": [["including everything", "kw-red"], ["every part", "kw-gold"]],
  "environmental": [["natural conditions", "kw-red"], ["connected with the environment", "kw-gold"]],
  "erupt": [["send out rocks, ash, lava", "kw-red"], ["sudden explosion", "kw-gold"]],
  "escalator": [["moving stairs", "kw-red"], ["between different floors", "kw-gold"]],
  "expensive": [["costing a lot of money", "kw-red"]],
  "experience": [["knowledge and skill", "kw-red"], ["through doing", "kw-gold"]],
  "explorer": [["travels to places", "kw-red"], ["few people have been before", "kw-gold"]],
  "fan": [["creates a current of air", "kw-red"]],
  "ferry": [["carries people, vehicles and goods", "kw-red"], ["across a river", "kw-gold"]],
  "film": [["special thin plastic", "kw-red"], ["making photographs or moving pictures", "kw-gold"]],
  "fish": [["catch or try to catch fish", "kw-red"]],
  "focus on": [["give attention, effort, or energy", "kw-red"], ["one specific task", "kw-gold"]],
  "follow (the) directions": [["do as told", "kw-red"], ["go as shown", "kw-gold"]],
  "follower": [["regularly receive messages", "kw-red"], ["social media service", "kw-gold"]],
  "free": [["not costing any money", "kw-red"]],
  "full-time": [["full number of hours", "kw-red"], ["normal or standard", "kw-gold"]],
  "gallery": [["showing works of art", "kw-red"], ["for public", "kw-gold"]],
  "generation": [["born and living", "kw-red"], ["same time", "kw-gold"]],
  "generous": [["freely giving or sharing", "kw-red"], ["money and other valuable things", "kw-gold"]],
  "get off": [["leave a vehicle", "kw-red"]],
  "get on": [["enter a vehicle", "kw-red"]],
  "global warming": [["increase in temperature", "kw-red"], ["earth's atmosphere", "kw-gold"]],
  "go around the corner": [["walk or move past a bend", "kw-red"], ["turning in the road", "kw-gold"]],
  "go past (the traffic lights)": [["move beyond", "kw-red"], ["beyond the traffic lights", "kw-gold"]],
  "go straight on": [["keep moving in the same direction", "kw-red"], ["without turning", "kw-gold"]],
  "gondola": [["long boat with a flat bottom", "kw-red"], ["canals in Venice", "kw-gold"]],
  "green": [["protect the natural world", "kw-red"]],
  "greenhouse": [["glass sides and a glass roof", "kw-red"], ["growing plants", "kw-gold"]],
  "handle": [["deal with a situation", "kw-red"], ["strong emotion", "kw-gold"]],
  "humid": [["warm and slightly wet", "kw-red"]],
  "iguana": [["large tropical American lizard", "kw-red"]],
  "imagine": [["form a picture in your mind", "kw-red"]],
  "improve": [["become better than before", "kw-red"], ["make better", "kw-gold"]],
  "information": [["knowledge that you get", "kw-red"]],
  "inspector": [["check tickets", "kw-red"], ["bus or train", "kw-gold"]],
  "internet": [["connects computers", "kw-red"], ["throughout the world", "kw-gold"]],
  "invent": [["create or produce", "kw-red"], ["for the first time", "kw-gold"]],
  "job": [["work that a person does", "kw-red"], ["earn money", "kw-gold"]],
  "jog": [["run slowly", "kw-red"], ["for exercise", "kw-gold"]],
  "jungle": [["tropical forest", "kw-red"], ["grow very thickly", "kw-gold"]],
  "landfill": [["waste is buried", "kw-red"], ["under the ground", "kw-gold"]],
  "lay eggs": [["produce and put eggs", "kw-red"], ["like birds do", "kw-gold"]],
  "leaf": [["flat green part of a plant", "kw-red"], ["from a stem or branch", "kw-gold"]],
  "lift": [["carries people or goods", "kw-red"], ["up and down to different levels", "kw-gold"]],
  "liquid": [["able to flow freely", "kw-red"]],
  "local": [["place where you live", "kw-red"]],
  "location": [["place or position", "kw-red"]],
  "loudspeaker": [["make sound", "kw-red"], ["many people can hear it", "kw-gold"]],
  "manager": [["in charge of running a business", "kw-red"]],
  "mark": [["give marks to students' work", "kw-red"]],
  "massive": [["very large, heavy and solid", "kw-red"]],
  "material": [["substance", "kw-red"], ["things can be made from", "kw-gold"]],
  "means": [["way of achieving", "kw-red"]],
  "mechanic": [["repairing machines", "kw-red"], ["engines of vehicles", "kw-gold"]],
  "mosaic": [["small pieces of glass", "kw-red"], ["different colours", "kw-gold"]],
  "motorbike": [["two wheels", "kw-red"], ["driven by an engine", "kw-gold"]],
  "national park": [["protected by the government", "kw-red"], ["natural beauty", "kw-gold"]],
  "neighbourhood (AmE neighborhood)": [["district or area", "kw-red"], ["of a town", "kw-gold"]],
  "nest": [["where a bird lays its eggs", "kw-red"], ["takes care of its young", "kw-gold"]],
  "news": [["information that is reported", "kw-red"], ["newspaper, magazine, television", "kw-gold"]],
  "newspaper": [["large printed sheets of paper", "kw-red"], ["containing news, articles, advertisements", "kw-gold"]],
  "ocean": [["mass of salt water", "kw-red"], ["covers most of the earth", "kw-gold"]],
  "oil": [["thick liquid", "kw-red"], ["rock underground", "kw-gold"]],
  "opinion": [["your feelings or thoughts", "kw-red"], ["rather than a fact", "kw-gold"]],
  "organisation (AmE organization)": [["group of people", "kw-red"], ["achieve a particular aim", "kw-gold"]],
  "origin": [["beginning or cause", "kw-red"]],
  "outer space": [["outside the earth's atmosphere", "kw-red"], ["other planets and stars", "kw-gold"]],
  "oxygen": [["chemical element", "kw-red"], ["present in air and water", "kw-gold"]],
  "parking": [["leaving vehicles", "kw-red"]],
  "part-time": [["fewer hours", "kw-red"], ["normal or standard", "kw-gold"]],
  "pass": [["allowed to enter or leave", "kw-red"], ["ride a vehicle", "kw-gold"]],
  "passenger": [["travelling in a car", "kw-red"], ["not driving it", "kw-gold"]],
  "patient": [["wait for a long time", "kw-red"], ["without becoming angry", "kw-gold"]],
  "pedestrian": [["walking in the street", "kw-red"], ["not travelling in a vehicle", "kw-gold"]],
  "petrol": [["liquid made from petroleum", "kw-red"], ["fuel for engines", "kw-gold"]],
  "planetary": [["relating to a planet", "kw-red"]],
  "planner": [["plan the growth and development", "kw-red"], ["of a town", "kw-gold"]],
  "plastic bag": [["light bag", "kw-red"], ["made of plastic", "kw-gold"]],
  "pollute": [["dirty and not safe", "kw-red"], ["land, water, air", "kw-gold"]],
  "post": [["put information or pictures", "kw-red"], ["on a website", "kw-gold"]],
  "print": [["appear on paper or cloth", "kw-red"], ["using a machine", "kw-gold"]],
  "product": [["grown, produced or created", "kw-red"], ["usually for sale", "kw-gold"]],
  "professional": [["paid job", "kw-red"], ["rather than as a hobby", "kw-gold"]],
  "programme (AmE program)": [["watch on television", "kw-red"], ["listen to on the radio", "kw-gold"]],
  "quality": [["how good or bad", "kw-red"]],
  "queue": [["line of people", "kw-red"], ["waiting", "kw-gold"]],
  "reality show": [["based on real people", "kw-red"], ["presented as entertainment", "kw-gold"]],
  "record": [["store", "kw-red"], ["heard or seen later", "kw-gold"]],
  "recreation": [["relax or have fun", "kw-red"]],
  "recycle": [["already been used", "kw-red"], ["used again", "kw-gold"]],
  "reporter": [["collects and reports news", "kw-red"], ["newspapers, radio or television", "kw-gold"]],
  "resident": [["lives in a particular place", "kw-red"], ["has their home there", "kw-gold"]],
  "review": [["gives their opinion", "kw-red"], ["new book or movie", "kw-gold"]],
  "review (verb)": [["write a report", "kw-red"], ["give your opinion", "kw-gold"]],
  "romantic": [["think of love", "kw-red"]],
  "rover": [["spacecraft designed to move", "kw-red"], ["on a planet or moon", "kw-gold"]],
  "rubber": [["strong substance", "kw-red"], ["can be stretched", "kw-gold"]],
  "rugby": [["two teams of 13 or 15 players", "kw-red"], ["oval ball", "kw-gold"]],
  "sailor": [["works on a ship", "kw-red"], ["member of the crew", "kw-gold"]],
  "sanctuary": [["wild birds or animals are protected", "kw-red"], ["produce young", "kw-gold"]],
  "sand": [["tiny, loose pieces of rock", "kw-red"], ["cover beaches, deserts", "kw-gold"]],
  "scavenger hunt": [["find various objects", "kw-red"], ["players find objects", "kw-gold"]],
  "scooter": [["light motorbike", "kw-red"], ["protect the rider's legs", "kw-gold"]],
  "sculpture": [["work of art", "kw-red"], ["carving or shaping wood", "kw-gold"]],
  "selfie": [["photo of yourself", "kw-red"], ["smartphone or webcam", "kw-gold"]],
  "sense": [["one of the five powers", "kw-red"], ["information about the world", "kw-gold"]],
  "series": [["regularly presented television shows", "kw-red"], ["same group of characters", "kw-gold"]],
  "seriously": [["in a serious way", "kw-red"]],
  "shade": [["dark and cool", "kw-red"], ["under or behind", "kw-gold"]],
  "share": [["give some of what you have", "kw-red"]],
  "shelter": [["structure built to give protection", "kw-red"], ["from the weather or from attack", "kw-gold"]],
  "shopping centre (AmE shopping center)": [["group of shops", "kw-red"], ["under one roof", "kw-gold"]],
  "show": [["let people see", "kw-red"]],
  "sight": [["interesting places", "kw-red"], ["visited by tourists", "kw-gold"]],
  "sitcom": [["regular comedy programme", "kw-red"], ["different funny situations", "kw-gold"]],
  "skill": [["particular ability", "kw-red"]],
  "skyscraper": [["very tall building", "kw-red"], ["in a city", "kw-gold"]],
  "slippery": [["difficult to stand on", "kw-red"], ["smooth, wet, icy", "kw-gold"]],
  "smell": [["sense with your nose", "kw-red"]],
  "social media": [["used for social networking", "kw-red"]],
  "soil": [["top layer of earth", "kw-red"], ["plants grow", "kw-gold"]],
  "spend": [["pay for", "kw-red"]],
  "square": [["open area in a town", "kw-red"], ["surrounded by buildings", "kw-gold"]],
  "staff": [["group of people who work", "kw-red"], ["for an organisation or business", "kw-gold"]],
  "stem": [["main long and thin part", "kw-red"], ["supports the leaves and flowers", "kw-gold"]],
  "steps": [["surfaces that you walk on", "kw-red"], ["up or down stairs", "kw-gold"]],
  "sticker": [["small digital image", "kw-red"], ["express an idea or emotion", "kw-gold"]],
  "sticky": [["things easily attach to", "kw-red"], ["things stick to", "kw-gold"]],
  "stone": [["small piece of rock", "kw-red"]],
  "submarine": [["ship that can travel underwater", "kw-red"]],
  "success": [["achieved what you want", "kw-red"]],
  "surface": [["outside or top layer", "kw-red"]],
  "system": [["group of related parts", "kw-red"], ["move or work together", "kw-gold"]],
  "tap water": [["supplied through pipes", "kw-red"], ["taps in a building", "kw-gold"]],
  "taste": [["recognize different foods and drinks", "kw-red"], ["put them in your mouth", "kw-gold"]],
  "taste (verb)": [["test the taste", "kw-red"], ["eating or drinking a small amount", "kw-gold"]],
  "tax": [["pay to the government", "kw-red"], ["pay for public services", "kw-gold"]],
  "technology": [["use of science", "kw-red"], ["invent useful things", "kw-gold"]],
  "the Arctic": [["regions of the world", "kw-red"], ["around the North Pole", "kw-gold"]],
  "the planet": [["planet Earth", "kw-red"]],
  "throw away": [["get rid of", "kw-red"], ["no longer want", "kw-gold"]],
  "ticket": [["allows you to see a show", "kw-red"], ["travel on a vehicle", "kw-gold"]],
  "ticket machine": [["sells tickets", "kw-red"], ["without needing a human cashier", "kw-gold"]],
  "timetable": [["chart showing the times", "kw-red"], ["leave and arrive", "kw-gold"]],
  "tool": [["hold in your hand", "kw-red"], ["particular task", "kw-gold"]],
  "toxic": [["containing poison", "kw-red"]],
  "track": [["train moves along", "kw-red"], ["metal bars", "kw-gold"]],
  "traffic": [["vehicles that are on a road", "kw-red"]],
  "tram": [["travels on streets on metal tracks", "kw-red"], ["carrying passengers", "kw-gold"]],
  "transport (AmE transportation)": [["carrying people or goods", "kw-red"], ["from one place to another", "kw-gold"]],
  "trap": [["catch and hold", "kw-red"], ["cannot escape", "kw-gold"]],
  "treasure": [["collection of valuable things", "kw-red"], ["gold, silver and jewellery", "kw-gold"]],
  "try": [["make an effort", "kw-red"]],
  "turn left/right": [["change direction", "kw-red"], ["move to the left or right", "kw-gold"]],
  "upload": [["send data to another computer", "kw-red"]],
  "variety": [["several different sorts", "kw-red"]],
  "virtual reality": [["created by a computer", "kw-red"], ["seem almost real", "kw-gold"]],
  "voice": [["sounds that are made", "kw-red"], ["people speak or sing", "kw-gold"]],
  "volcano": [["mountain with a hole", "kw-red"], ["sudden explosion", "kw-gold"]],
  "waste": [["no longer needed", "kw-red"], ["thrown away", "kw-gold"]],
  "wildlife": [["animals living in nature", "kw-red"]],
  "worry": [["what worries you", "kw-red"]]
}

export const CHINESE_DEF_MAP_4B: Record<string, string> = {
  "national park": "国家公园",
  "iguana": "鬣蜥",
  "branch": "树枝",
  "jungle": "丛林；热带雨林",
  "lay eggs": "产卵；下蛋",
  "sand": "沙子",
  "leaf": "叶子",
  "volcano": "火山",
  "nest": "鸟巢；窝",
  "wildlife": "野生动物",
  "soil": "土壤",
  "erupt": "（火山）喷发",
  "stone": "石头",
  "active": "（火山）活跃的；活火山的",
  "humid": "潮湿的；湿润的",
  "smell": "气味",
  "alive": "活着的；有生命的",
  "creature": "生物；动物",
  "curious": "好奇的",
  "liquid": "液体",
  "massive": "巨大的；厚重的",
  "stem": "茎；干",
  "slippery": "滑的；湿滑的",
  "trap": "困住；诱捕",
  "sticky": "黏的；黏糊糊的",
  "climate": "气候",
  "variety": "种类；多样",
  "sanctuary": "（鸟类、动物的）保护区",
  "success": "成功",
  "endangered": "濒危的",
  "cause": "导致；引起",
  "ocean": "海洋",
  "cover": "盖；遮盖；覆盖",
  "battery": "电池",
  "dump": "丢弃；倾倒；随意乱放",
  "can": "罐头；金属罐",
  "landfill": "垃圾填埋场",
  "cardboard": "硬纸板；卡纸",
  "environmental": "环境的；有关环境的",
  "electronics": "电子设备；电子产品",
  "improve": "改善；提高；变得更好",
  "newspaper": "报纸",
  "system": "系统；体系",
  "plastic bag": "塑料袋",
  "recreation": "娱乐；消遣",
  "rubber": "橡胶",
  "association": "协会；社团",
  "handle": "处理；应对",
  "petrol": "汽油",
  "pollute": "污染",
  "recycle": "回收利用；再利用",
  "tap water": "自来水",
  "throw away": "扔掉；丢弃",
  "destroy": "摧毁；毁坏",
  "oil": "石油；原油",
  "air conditioning": "空调；空调系统",
  "fan": "风扇",
  "free": "免费的",
  "green": "环保的；绿色的",
  "product": "产品；制品",
  "waste": "废料；垃圾",
  "by mistake": "错误地；无意中",
  "ecosystem": "生态系统",
  "shade": "阴凉处；树荫",
  "oxygen": "氧气",
  "drip": "滴下；滴落",
  "global warming": "全球变暖",
  "explorer": "探险家；勘探者",
  "tool": "工具",
  "generation": "一代人；一代",
  "design": "设计；规划",
  "cross the road": "过马路；穿过马路",
  "follow (the) directions": "按照指示；听从指引",
  "go past (the traffic lights)": "经过（红绿灯）；走过（红绿灯）",
  "information": "信息；资料",
  "go straight on": "一直往前走；笔直走",
  "sight": "（旅游）景点；名胜",
  "turn left/right": "向左/右转",
  "location": "位置；地点",
  "scavenger hunt": "寻物游戏；寻宝游戏",
  "treasure": "财宝；珍宝",
  "go around the corner": "拐过街角；绕过转角",
  "mark": "批改（作业）；打分",
  "cheap": "便宜的；廉价的",
  "expensive": "昂贵的；价格高的",
  "collection": "收藏品；收集",
  "bank": "银行",
  "fish": "钓鱼；捕鱼",
  "ferry": "渡船；轮渡",
  "spend": "花费（钱）；支付",
  "shopping centre (AmE shopping center)": "购物中心；商场",
  "ticket": "票；入场券",
  "skyscraper": "摩天大楼",
  "try": "尝试；努力",
  "square": "广场",
  "steps": "台阶；楼梯",
  "outer space": "外太空；太空",
  "bagel": "百吉饼；贝果",
  "chewy": "有嚼劲的；耐嚼的",
  "opinion": "观点；看法",
  "origin": "起源；由来",
  "material": "材料；原料",
  "local": "当地的；本地的",
  "jog": "慢跑（锻炼）",
  "social media": "社交媒体",
  "album": "相册；集邮册",
  "app": "应用程序",
  "print": "打印；印刷",
  "digital": "数字的；数码的",
  "show": "给…看；展示",
  "download": "下载",
  "comment": "评论；意见",
  "internet": "互联网",
  "post": "发布（信息或图片到网上）",
  "upload": "上传",
  "share": "分享",
  "film": "胶卷；胶片",
  "rugby": "橄榄球（运动）",
  "selfie": "自拍照",
  "sticker": "（聊天/社交媒体上的）表情贴纸",
  "invent": "发明；创造",
  "programme (AmE program)": "（电视或广播）节目",
  "quality": "质量；品质",
  "record": "录制；录音",
  "technology": "技术；科技",
  "entertain": "使快乐；使有兴趣",
  "imagine": "想象",
  "cartoon": "动画片；卡通片",
  "documentary": "纪录片",
  "news": "新闻",
  "reality show": "真人秀",
  "series": "（电视）系列节目；剧集",
  "sitcom": "情景喜剧",
  "virtual reality": "虚拟现实（VR）",
  "follower": "（社交媒体上的）关注者；粉丝",
  "channel": "（电视）频道；电视台",
  "review": "评论文章；评价",
  "review (verb)": "评论；写评论",
  "voice": "嗓音；声音",
  "generous": "慷慨的；大方的",
  "neighbourhood (AmE neighborhood)": "街区；社区",
  "destination": "目的地",
  "bus stop": "公共汽车站",
  "get on": "上车",
  "driver": "司机",
  "get off": "下车",
  "bike lane": "自行车道",
  "parking": "停车场；停车位",
  "tram": "有轨电车",
  "pedestrian": "行人",
  "motorbike": "摩托车",
  "traffic": "交通；车流",
  "scooter": "小型摩托车",
  "resident": "居民",
  "transport (AmE transportation)": "交通运输",
  "planner": "城市规划师",
  "passenger": "乘客",
  "track": "铁轨",
  "billion": "十亿",
  "display": "展示；陈列",
  "inspector": "检票员",
  "escalator": "自动扶梯",
  "lift": "电梯",
  "gallery": "美术馆；画廊",
  "loudspeaker": "扩音器；喇叭",
  "ticket machine": "售票机",
  "timetable": "时刻表",
  "the planet": "地球",
  "chandelier": "枝形吊灯",
  "mosaic": "马赛克；镶嵌画",
  "sculpture": "雕塑",
  "pass": "通行证；乘车卡",
  "gondola": "贡多拉（威尼斯小船）",
  "romantic": "浪漫的",
  "cable car": "缆车",
  "means": "方法；方式",
  "aquarium": "水族馆",
  "entire": "整个的；全部的",
  "distance": "距离",
  "check": "检查；查看",
  "artist": "艺术家",
  "patient": "有耐心的",
  "chef": "厨师；大厨",
  "customer": "顾客",
  "detective": "侦探",
  "queue": "队伍；排队的人",
  "mechanic": "机械师；修理工",
  "reporter": "记者",
  "skill": "技能；技巧",
  "sailor": "水手；船员",
  "tax": "税；税款",
  "desire": "渴望；愿望",
  "sense": "感官；知觉",
  "taste": "味觉",
  "taste (verb)": "品尝；尝味道",
  "designer": "设计师",
  "day off": "休息日",
  "focus on": "专注于；集中于",
  "full-time": "全职的",
  "part-time": "兼职的",
  "job": "工作；职业",
  "author": "作家；作者",
  "career": "职业；事业",
  "employee": "雇员；员工",
  "experience": "经验；经历",
  "manager": "经理；管理者",
  "staff": "全体员工",
  "organisation (AmE organization)": "组织；机构",
  "the Arctic": "北极地区",
  "surface": "表面",
  "rover": "漫游车；探测车",
  "greenhouse": "温室；暖房",
  "shelter": "避难所；遮蔽处",
  "planetary": "行星的",
  "toxic": "有毒的",
  "dust": "灰尘；尘土",
  "submarine": "潜水艇",
  "attract": "吸引",
  "brave": "勇敢的",
  "professional": "专业的；职业的",
  "worry": "烦恼；担忧的事",
  "seriously": "严肃地；认真地"
}

export const SAMPLE_WORDS_4B: WordEntry[] = _RAW_WORDS_4B.map(w => ({
  ...w,
  chineseDef: CHINESE_DEF_MAP_4B[w.word] ?? undefined,
  syllables: SYLLABLE_MAP_4B[w.word.toLowerCase()] ?? undefined,
  keywords: KW_MAP_4B[w.word] ?? undefined,
}))
